(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Epson_Logo = function() {
	this.initialize(img.Epson_Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,131,48);


(lib.image_01 = function() {
	this.initialize(img.image_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,359,144);


(lib.image_01_LG = function() {
	this.initialize(img.image_01_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,282,406);


(lib.image_02 = function() {
	this.initialize(img.image_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,359,144);


(lib.image_02_LG = function() {
	this.initialize(img.image_02_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,282,406);


(lib.image_03 = function() {
	this.initialize(img.image_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,359,144);


(lib.image_03_LG = function() {
	this.initialize(img.image_03_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,282,406);


(lib.Printer = function() {
	this.initialize(img.Printer);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,174);


(lib.printer_light = function() {
	this.initialize(img.printer_light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,163,22);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_onARoll = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AMhBjIAAgXIAIAAQAIABAEgFQADgEABgHIghh2IAgAAIARBRIABAAIAPhRIAeAAIgcBuIgIAXQgEAKgEAFQgFAEgHACQgHABgLABgAN/BRQAGgCADgFQADgFAAgFIAAgDIgMAAIAAgjIAdAAIAAAdIgBAQQgBAGgEAGQgDAFgFAEQgGAEgJAAgALVA8QgIgCgGgIQgFgHgDgMQgDgMAAgSQAAgRADgMQAEgMAGgHQAHgHAJgDQAIgDALAAQAVAAALAMQAKAMAAAWIgdAAIAAgJIgCgIQgCgDgCgCQgDgCgEAAQgGAAgDADQgEACgCAFIgCAMIAAAkIACANQACAFADACQAEADAFAAQAHAAAEgGQADgIAAgOIAdAAQAAAYgKALQgLANgYAAQgLAAgJgDgAIHA5QgKgFgEgJQgFgJgBgMIgBgWQAAgKACgMQACgKAFgJQAFgJAJgFQAJgFAQAAQANAAAIAFQAJADAFAJQAEAHACALQACALAAAOIAAAGIg8AAIABAUIACAJQACADADACQADADAEAAQAIAAADgGQADgFACgMIAbAAQgBAWgKAKQgKALgWAAQgQAAgJgGgAIZglQgDACgCADIgCAIIgBAIIAAAFIAfAAIgBgMIgCgJQgCgEgDgBQgDgDgFAAQgEAAgDADgAFwA9QgJgDgFgFQgFgEgCgIQgCgGAAgJIAAgEIAcAAIAAAEQAAAHAEAFQAEAFAHAAQAHAAAFgEQAEgDAAgHQAAgGgDgDQgEgDgEgBIgVgIQgNgFgGgHQgHgIAAgNQAAgHADgGQACgGAFgGQAGgEAIgDQAIgDAMAAQAUAAAKAJQAKAIAAARIAAAEIgbAAQAAgIgDgFQgDgFgHAAQgGAAgEAEQgFADAAAHQAAAEADAEQADADAHACIATAGQAOAFAGAHQAGAIAAAOQAAAJgDAHQgEAHgGAFQgFAEgIACQgIACgKAAQgNAAgIgCgADkA9QgJgDgFgFQgFgEgCgIQgCgGAAgJIAAgEIAcAAIAAAEQAAAHAEAFQAEAFAHAAQAHAAAFgEQAEgDAAgHQAAgGgDgDQgEgDgEgBIgVgIQgNgFgGgHQgHgIAAgNQAAgHADgGQACgGAFgGQAGgEAIgDQAIgDAMAAQAUAAAKAJQAKAIAAARIAAAEIgbAAQAAgIgDgFQgDgFgHAAQgGAAgEAEQgFADAAAHQAAAEADAEQADADAHACIATAGQAOAFAGAHQAGAIAAAOQAAAJgDAHQgEAHgGAFQgFAEgIACQgIACgKAAQgNAAgIgCgAAZA7QgJgDgFgIQgGgIgCgMQgCgMAAgPQAAgOACgMQADgLAFgIQAGgIAJgEQAJgEANAAQANAAAJADQAJAFAGAIQAFAIACALQACAMAAAOQAAAQgCALQgDAMgFAHQgGAJgJADQgJAEgMAAQgOAAgJgEgAAngkQgEADgBAGIgCAMIAAAhIACANQABAGAEADQADADAGAAQAJAAADgKQAEgJAAgXQAAgVgEgKQgDgJgJgBQgGAAgDAEgAhGA8QgIgCgGgIQgFgHgDgMQgDgMAAgSQAAgRADgMQAEgMAGgHQAHgHAJgDQAIgDALAAQAVAAALAMQAKAMAAAWIgdAAIAAgJIgCgIQgCgDgCgCQgDgCgEAAQgGAAgDADQgEACgCAFIgCAMIAAAkIACANQACAFADACQAEADAFAAQAHAAAEgGQADgIAAgOIAdAAQAAAYgKALQgLANgYAAQgLAAgJgDgAkfA5QgJgFgFgJQgEgJgBgMIgBgWQAAgKACgMQABgKAFgJQAFgJAJgFQAKgFAPAAQANAAAJAFQAIADAFAJQAFAHACALQABALAAAOIAAAGIg8AAIABAUIADAJQABADADACQADADAEAAQAIAAAEgGQADgFABgMIAcAAQgBAWgKAKQgKALgWAAQgRAAgJgGgAkNglQgDACgBADIgDAIIgBAIIAAAFIAfAAIgBgMIgCgJQgBgEgDgBQgDgDgFAAQgFAAgDADgAohA7QgJgDgFgIQgFgIgCgMQgDgMAAgPQAAgOADgMQACgLAGgIQAFgIAJgEQAJgEANAAQAOAAAJADQAJAFAFAIQAFAIACALQADAMAAAOQAAAQgDALQgCAMgGAHQgFAJgJADQgJAEgNAAQgOAAgJgEgAoTgkQgDADgCAGIgCAMIAAAhIACANQACAGADADQAEADAFAAQAJAAAEgKQADgJAAgXQAAgVgDgKQgEgJgJgBQgFAAgEAEgAq8A9QgIgDgFgFQgFgEgCgIQgCgGAAgJIAAgEIAbAAIAAAEQAAAHAEAFQAEAFAIAAQAHAAAEgEQAEgDAAgHQAAgGgDgDQgDgDgFgBIgVgIQgNgFgGgHQgGgIAAgNQAAgHACgGQACgGAGgGQAFgEAIgDQAJgDALAAQAVAAAKAJQAKAIAAARIAAAEIgcAAQAAgIgDgFQgDgFgHAAQgGAAgEAEQgEADAAAHQAAAEACAEQADADAIACIASAGQAPAFAFAHQAGAIAAAOQAAAJgDAHQgDAHgGAFQgGAEgIACQgIACgKAAQgMAAgJgCgAsuA3QgIgIAAgRIAAhXIAeAAIAABRQAAAJADAEQADADAHAAQAQABAAgVIAAhNIAfAAIAAB2IgdAAIAAgPIgBAAQgFAKgHADQgIAEgKAAQgOAAgIgIgAuCA8QgIgCgGgIQgFgHgDgMQgDgMAAgSQAAgRADgMQAEgMAGgHQAHgHAJgDQAIgDALAAQAVAAALAMQAKAMAAAWIgdAAIAAgJIgCgIQgCgDgCgCQgDgCgEAAQgGAAgDADQgEACgCAFIgCAMIAAAkIACANQACAFADACQAEADAFAAQAHAAAEgGQADgIAAgOIAdAAQAAAYgKALQgLANgYAAQgLAAgJgDgAHPA8QgFgBgDgEQgDgEgBgFIgBgQIAAhCIgQAAIAAgVIAQAAIAAghIAeAAIAAAhIARAAIAAAVIgRAAIAAA/QAAAHACADQACADAHAAIADgBIADAAIAAAWIgTAAIgPgBgApcA8QgGgBgDgEQgDgEgBgFIgBgQIAAhCIgPAAIAAgVIAPAAIAAghIAeAAIAAAhIASAAIAAAVIgSAAIAAA/QAAAHACADQACADAHAAIAEgBIADAAIAAAWIgUAAIgOgBgAKTA9IAAhRQAAgKgDgDQgDgEgHABQgQAAAAATIAABOIgfAAIAAh2IAdAAIAAAOIABAAQAFgJAHgEQAIgEAKAAQAOAAAIAIQAIAIAAASIAABXgAEwA9IAAh2IAeAAIAAB2gAClA9IAAhRQAAgKgDgDQgDgEgHABQgQAAAAATIAABOIgfAAIAAh2IAdAAIAAAOIABAAQAFgJAHgEQAIgEAKAAQAOAAAIAIQAIAIAAASIAABXgAjOA9IAAh2IAdAAIAAAQIAAAAQAFgJAHgEQAGgGAKAAIACAAIADAAIAAAdIgJAAIgIABIgIAEQgDADgCAEQgCADAAAHIAABGgAlcA9IAAhSQAAgIgDgEQgDgDgGAAQgHAAgEAEQgFAFAAALIAABNIgeAAIAAhSQAAgIgDgEQgDgDgGAAQgHAAgEAEQgFAFAAALIAABNIgeAAIAAh2IAdAAIAAANIAAAAQAGgJAHgEQAHgDAKAAQALAAAHAFQAHAFADAJQAEgKAHgEQAIgFALAAQAPAAAHAJQAHAJAAARIAABWgAEwhHIAAgaIAeAAIAAAag");
	this.shape.setTransform(3.475,-483.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_onARoll, new cjs.Rectangle(-88.9,-493.7,184.8,19.69999999999999), null);


(lib.txt_Immediatelamination = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgTAYIAAgvIAnAAIAAAvg");
	this.shape.setTransform(122.075,-107.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AAVBVIAAhyQgBgNgEgFQgEgEgKAAQgVgBgBAcIAABtIgqAAIAAilIAoAAIAAATIABAAQAHgMALgGQAKgFAOgBQAUABALAKQAMALAAAaIAAB6g");
	this.shape_1.setTransform(111.35,-114.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgfBSQgMgFgIgLQgHgLgDgQQgEgRAAgWQAAgUAEgQQADgRAIgLQAIgLAMgGQANgFARAAQATgBANAGQANAFAHALQAIAMADAQQADAQAAAVQAAAWgEAQQgDARgIALQgHALgNAFQgNAFgSAAIgCAAQgRAAgMgFgAgLg1QgFAEgCAIQgDAIAAALIgBAWIABAYQAAALADAIQACAHAFAFQAEAEAHAAQANAAAFgOQAFgNAAggQAAgegFgOQgFgNgNAAQgHAAgEAEg");
	this.shape_2.setTransform(96.925,-113.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgUBwIAAimIAqAAIAACmgAgUhKIAAglIAqAAIAAAlg");
	this.shape_3.setTransform(86.55,-116.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgCBqQgJgCgDgFQgFgFgCgIQgBgJAAgMIAAhfIgWAAIAAgdIAWAAIAAgwIAqAAIAAAwIAYAAIAAAdIgYAAIAABZQAAAKADAEQADAFAJAAIAFgBIAEAAIAAAeIgNAAIgOABQgMAAgHgCg");
	this.shape_4.setTransform(79.1,-116.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_5.setTransform(67.625,-113.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAUBVIAAhyQAAgNgEgFQgEgEgKAAQgVgBgBAcIAABtIgqAAIAAilIAoAAIAAATIABAAQAHgMALgGQAKgFANgBQAVABALAKQAMALAAAaIAAB6g");
	this.shape_6.setTransform(53.3,-114.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgVBwIAAimIAqAAIAACmgAgVhKIAAglIAqAAIAAAlg");
	this.shape_7.setTransform(42.6,-116.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AA9BVIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgqAAIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgrAAIAAilIApAAIAAARIABAAQAIgMAKgEQAKgGAOAAQAPAAAJAHQAKAHADANIABAAQAFgNALgHQALgGAPgBQAVAAAKANQAKANAAAZIAAB3g");
	this.shape_8.setTransform(27.925,-114.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_9.setTransform(9.375,-113.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgVBvIAAjdIArAAIAADdg");
	this.shape_10.setTransform(-0.9,-116.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgiBPQgNgHgHgNQgGgNgBgQIgCgeQAAgRADgPQACgQAHgMQAHgMANgHQANgHAVAAQASAAAMAGQAMAGAHALQAHALACAPQADAQAAATIAAAJIhUAAIAAANIABAPIAEAMQACAFAEAEQAEADAFAAQALAAAFgIQAFgIACgPIAmAAQgBAdgOAPQgPAPgeAAQgWAAgNgIgAgJg2QgEADgCAFIgEAKIgBAMIAAAGIArAAIgCgQQAAgIgDgFQgCgFgEgDQgEgCgHAAQgFAAgFADg");
	this.shape_11.setTransform(-17.675,-113.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgDBqQgHgCgFgFQgEgFgCgIQgBgJAAgMIAAhfIgVAAIAAgdIAVAAIAAgwIAqAAIAAAwIAZAAIAAAdIgZAAIAABZQAAAKADAEQACAFAKAAIAFgBIAFAAIAAAeIgOAAIgOABQgMAAgIgCg");
	this.shape_12.setTransform(-28.6,-116.225);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_13.setTransform(-40.075,-113.925);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgUBwIAAimIApAAIAACmgAgUhKIAAglIApAAIAAAlg");
	this.shape_14.setTransform(-50.35,-116.75);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("Ag0BcQgMgUAAgvQAAgtAMgVQAMgUAbAAQAMAAAHAFQAJAFAHAKIAAAAIAAhHIArAAIAADdIgpAAIAAgRIgBAAQgHALgIAFQgIAEgNAAQgbABgMgVgAgSgOQgEANAAAaQAAAcAEANQAFAPANAAQAOAAAEgPQAEgNAAgcQAAgagEgNQgEgOgOAAQgNAAgFAOg");
	this.shape_15.setTransform(-61.225,-116.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgiBPQgNgHgHgNQgGgNgBgQIgCgeQAAgRADgPQACgQAHgMQAHgMANgHQANgHAVAAQASAAAMAGQAMAGAHALQAHALACAPQADAQAAATIAAAJIhUAAIAAANIABAPIAEAMQACAFAEAEQAEADAFAAQALAAAFgIQAFgIACgPIAmAAQgBAdgOAPQgPAPgeAAQgWAAgNgIgAgJg2QgEADgCAFIgEAKIgBAMIAAAGIArAAIgCgQQAAgIgDgFQgCgFgEgDQgEgCgHAAQgFAAgFADg");
	this.shape_16.setTransform(-75.225,-113.925);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AA9BVIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgqAAIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgrAAIAAilIApAAIAAARIABAAQAIgMAKgEQAKgGAOAAQAPAAAJAHQAKAHADANIABAAQAFgNALgHQALgGAPgBQAVAAAKANQAKANAAAZIAAB3g");
	this.shape_17.setTransform(-93.375,-114.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AA9BVIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgqAAIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgrAAIAAilIApAAIAAARIABAAQAIgMAKgEQAKgGAOAAQAPAAAJAHQAKAHADANIABAAQAFgNALgHQALgGAPgBQAVAAAKANQAKANAAAZIAAB3g");
	this.shape_18.setTransform(-116.075,-114.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgWBvIAAjdIAsAAIAADdg");
	this.shape_19.setTransform(-131,-116.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_Immediatelamination, new cjs.Rectangle(-144.8,-137.3,279.6,40.60000000000001), null);


(lib.txt_greaterConsistency = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AJpBiIAAgWIAIAAQAJAAADgEQAEgEABgIIgih1IAgAAIASBRIAAAAIAPhRIAfAAIgdBtIgHAYQgEAJgFAGQgFAFgHABQgHABgLAAgALIBQQAFgBADgEQADgGAAgFIAAgEIgLAAIAAgiIAdAAIAAAdIgCAPQgBAIgEAFQgDAGgFADQgGAEgIAAgAIeA8QgJgCgGgIQgFgHgDgMQgDgMAAgRQAAgSADgMQAFgMAFgHQAHgHAJgDQAIgDALAAQAVAAALAMQALANAAAVIgdAAIgBgIIgCgJQgBgDgDgCQgDgCgEAAQgGAAgDACQgEADgBAFIgDANIAAAkIADAMQACAFACACQAEADAFAAQAIAAADgGQAEgIAAgOIAdAAQAAAXgLAMQgLANgXAAQgMAAgIgDgAFPA6QgJgGgFgJQgFgJAAgMIgCgWQABgLACgLQABgLAFgIQAFgJAJgFQAKgFAPAAQANAAAIAEQAJAFAFAIQAEAHACAMQACALAAANIAAAGIg8AAIABATIACAJQACAFADABQADADAEAAQAIAAAEgFQADgGABgLIAbAAQAAAUgLALQgKALgVAAQgRAAgJgFgAFhglQgDACgCAEIgCAHIgBAJIAAAEIAfAAIgBgMIgCgJQgBgEgEgCQgDgCgEAAQgFABgDACgAC4A8QgIgCgGgFQgEgEgCgIQgCgGgBgJIAAgEIAcAAIAAADQAAAJAEAEQAEAFAHAAQAIAAAEgDQAEgEAAgHQAAgGgDgDQgDgDgFgCIgVgIQgNgDgGgIQgHgIABgMQAAgIACgGQACgHAGgEQAFgFAIgDQAIgDAMAAQAUAAALAJQAKAJAAAPIAAAFIgcAAQAAgJgDgEQgDgEgHgBQgGABgEADQgFADABAGQgBAFADADQADAEAHACIATAHQAPAEAFAHQAGAIAAANQAAAKgDAHQgEAHgFAFQgGAEgIACQgIACgKAAQgMAAgJgDgAAsA8QgJgCgEgFQgFgEgDgIQgBgGAAgJIAAgEIAbAAIAAADQAAAJAEAEQAEAFAIAAQAGAAAFgDQAEgEAAgHQAAgGgDgDQgEgDgEgCIgVgIQgNgDgGgIQgGgIgBgMQABgIACgGQACgHAFgEQAGgFAIgDQAIgDAMAAQAUAAAKAJQAKAJAAAPIAAAFIgbAAQAAgJgDgEQgDgEgHgBQgGABgEADQgEADgBAGQABAFACADQADAEAIACIASAHQAOAEAGAHQAGAIAAANQAAAKgDAHQgDAHgHAFQgFAEgIACQgIACgKAAQgMAAgJgDgAieA7QgJgDgFgIQgFgHgDgMQgCgMAAgPQAAgPACgLQADgMAFgIQAGgIAJgEQAJgEANAAQANAAAKADQAJAEAFAIQAFAIACAMQADAMAAAPQAAAOgDAMQgDAMgFAIQgGAHgIAEQgKAEgMAAQgOAAgJgEgAiQgkQgEADgBAFIgCAOIAAAgIACANQABAGAEADQADADAGAAQAJAAAEgKQADgKAAgVQAAgWgDgKQgEgKgJAAQgGABgDADgAj+A8QgIgCgFgIQgGgHgDgMQgDgMAAgRQAAgSAEgMQADgMAHgHQAGgHAJgDQAIgDALAAQAWAAAKAMQALANgBAVIgdAAIAAgIIgCgJQgCgDgCgCQgCgCgFAAQgGAAgDACQgEADgCAFIgCANIAAAkIACAMQACAFAEACQADADAFAAQAIAAADgGQAEgIgBgOIAdAAQABAXgLAMQgLANgYAAQgLAAgJgDgAnXA7QgJgDgEgIQgGgHgCgMQgDgMAAgPQAAgPADgLQACgMAGgIQAGgIAIgEQAKgEANAAQANAAAJADQAJAEAGAIQAEAIADAMQACAMAAAPQAAAOgCAMQgDAMgFAIQgGAHgJAEQgJAEgMAAQgOAAgKgEgAnIgkQgEADgCAFIgBAOIAAAgIABANQACAGAEADQADADAGAAQAIAAAEgKQADgKAAgVQAAgWgDgKQgEgKgIAAQgGABgDADgApqA7QgKgDgFgIQgFgHgCgMQgCgMgBgPQABgPACgLQACgMAGgIQAFgIAKgEQAIgEANAAQAOAAAJADQAJAEAFAIQAGAIABAMQADAMAAAPQAAAOgDAMQgCAMgGAIQgFAHgJAEQgJAEgNAAQgOAAgIgEgApdgkQgDADgBAFIgDAOIAAAgIADANQABAGADADQAEADAFAAQAKAAADgKQADgKAAgVQAAgWgDgKQgDgKgKAAQgFABgEADgArKA8QgJgCgFgIQgFgHgDgMQgEgMAAgRQABgSADgMQAEgMAGgHQAHgHAIgDQAJgDALAAQAVAAAKAMQALANAAAVIgdAAIgBgIIgBgJQgCgDgDgCQgCgCgEAAQgGAAgDACQgEADgCAFIgCANIAAAkIACAMQACAFADACQADADAFAAQAIAAAEgGQADgIAAgOIAdAAQAAAXgLAMQgKANgYAAQgMAAgIgDgAEYA8QgGgBgDgEQgDgDgBgGIgBgPIAAhDIgQAAIAAgVIAQAAIAAgiIAeAAIAAAiIARAAIAAAVIgRAAIAAA/QAAAHACADQACADAHAAIAEAAIACAAIAAAUIgTABIgOgBgAHbA8IAAhQQAAgJgDgEQgDgEgHAAQgQABAAATIAABNIgeAAIAAh1IAdAAIAAAOIAAAAQAFgJAHgEQAJgEAJAAQAOAAAJAIQAHAIABARIAABXgAB4A8IAAh1IAeAAIAAB1gAgSA8IAAhQQAAgJgDgEQgDgEgHAAQgQABAAATIAABNIgeAAIAAh1IAcAAIAAAOIABAAQAFgJAHgEQAIgEAKAAQAOAAAIAIQAHAIABARIAABXgAmGA8IAAh1IAdAAIAAAQIAAAAQAGgIAGgGQAHgFAJAAIADAAIACABIAAAcIgJAAIgIABIgIAEQgCACgCAEQgCAFgBAFIAABGgAoZA8IAAibIAeAAIAACbgAB4hIIAAgZIAeAAIAAAZg");
	this.shape.setTransform(-7.2,-465.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_greaterConsistency, new cjs.Rectangle(-81.2,-475.6,148.10000000000002,19.700000000000045), null);


(lib.txt_greater = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AkBBaQgLgIAAgQIAdAAQAAAHAFACIAFADIAFABQAKAAADgGQAEgGgBgJIAAgPQgFAGgGAEQgHAEgHAAQgSAAgJgNQgKgOAAgfIACgWQABgLAEgIQAEgJAHgGQAHgFANAAQAGAAAHADQAHAEAEAKIAAgOIAeAAIAABwQAAAWgMAMQgLAMgbAAQgTAAgKgJgAjngkQgDACgCAFQgCAEAAAJIAAAeQAAAGACAFQABAEAEACQACADAGAAQAEAAADgDQADgCACgEIADgMIAAgNQAAgUgDgKQgDgIgJgBQgFABgDACgAIrA3QgKgFgEgJQgEgJgCgMIAAgVQAAgMABgLQACgLAFgIQAFgJAJgFQAKgFAPAAQANAAAJAEQAIAFAFAIQAFAHACAMQABALAAANIAAAGIg8AAIABATIADAJQABAFADABQADADAEAAQAIAAADgFQADgGACgLIAcAAQgCAUgJALQgKALgXAAQgQAAgJgGgAI9gnQgDACgBADIgDAIIgBAJIAAAEIAfAAIgBgMIgCgJQgBgEgDgCQgEgCgFAAQgEABgDACgACyA3QgJgFgFgJQgEgJgCgMIAAgVQgBgMACgLQACgLAFgIQAFgJAJgFQAKgFAPAAQANAAAJAEQAIAFAFAIQAFAHACAMQABALAAANIAAAGIg8AAIABATIADAJQABAFADABQADADAEAAQAIAAADgFQAEgGABgLIAcAAQgCAUgJALQgKALgXAAQgQAAgJgGgADEgnQgDACgBADIgDAIIgBAJIAAAEIAfAAIgBgMIgCgJQgCgEgCgCQgEgCgFAAQgEABgDACgAANA6QgFgCgEgGQgEgEAAgHIgCgLQAAgJACgGQABgFAEgFQADgEAGgCIAOgFIARgFQAGgBADgDQADgEAAgGQAAgGgEgEQgCgFgJAAQgGABgEAEQgEAEABAHIAAADIgbAAIAAgCQAAgLACgHQAEgHAFgEQAGgEAIgCQAIgCAIAAQAOAAAIACQAIADAFAFQAEAFACAGQACAHAAAJIAABJIADAKIgdAAIgDgMIAAAAQgGAKgHACQgHADgLAAQgHAAgGgDgAAyADIgGACQgKACgDAFQgEAEgBAJQABAGADAFQACAFAGAAIAGgBQAEgBACgCQADgCACgEQACgDAAgGIAAgWgAhOA3QgJgFgFgJQgFgJAAgMIgCgVQABgMACgLQABgLAFgIQAFgJAJgFQAJgFAQAAQANAAAIAEQAJAFAFAIQAEAHACAMQACALAAANIAAAGIg8AAIABATIACAJQACAFADABQADADAEAAQAIAAAEgFQADgGABgLIAbAAQAAAUgLALQgKALgVAAQgRAAgJgGgAg8gnQgDACgCADIgCAIIgBAJIAAAEIAfAAIgBgMIgCgJQgBgEgEgCQgDgCgEAAQgFABgDACgAmLA3QgJgFgFgJQgFgJgBgMIgBgVQAAgMACgLQACgLAFgIQAFgJAJgFQAKgFAPAAQANAAAJAEQAIAFAFAIQAEAHACAMQACALAAANIAAAGIg8AAIABATIACAJQACAFADABQADADAEAAQAIAAAEgFQACgGACgLIAbAAQAAAUgKALQgLALgWAAQgQAAgJgGgAl5gnQgDACgCADIgCAIIgBAJIAAAEIAfAAIgBgMIgCgJQgCgEgDgCQgCgCgGAAQgEABgDACgAGKA6QgFgBgDgEQgDgEgBgFIgBgQIAAhCIgQAAIAAgVIAQAAIAAgiIAeAAIAAAiIARAAIAAAVIgRAAIAAA/QAAAHACADQACADAHAAIAEgBIACAAIAAAVIgTABIgPgBgAB6A6QgFgBgDgEQgDgEgBgFIgBgQIAAhCIgPAAIAAgVIAPAAIAAgiIAeAAIAAAiIASAAIAAAVIgSAAIAAA/QAAAHACADQACADAHAAIAEgBIADAAIAAAVIgUABIgPgBgAHtA6IAAhQQAAgJgDgEQgDgEgGAAQgQABgBATIAABNIgeAAIAAibIAeAAIAAAzIABAAQAIgQAUAAQAPAAAIAIQAIAIAAASIAABWgAECA6IAAh1IAdAAIAAAQIABAAQAFgIAHgGQAGgFAKAAIACAAIADABIAAAcIgKAAIgIABIgHAEQgDACgCAEQgCAFAAAFIAABGgAiiA6IAAh1IAdAAIAAAQIABAAQAFgIAGgGQAHgFAJAAIACAAIADABIAAAcIgJAAIgIABIgHAEQgEACgCAEQgBAFAAAFIAABGgAnIA6IAAhQQAAgJgEgEQgCgEgIAAQgQABAAATIAABNIgeAAIAAibIAeAAIAAAzIABAAQAJgQAUAAQAOAAAIAIQAIAIAAASIAABWgApNA6IAAiBIgjAAIAAgaIBkAAIAAAaIgiAAIAACBg");
	this.shape.setTransform(3.6,-503.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_greater, new cjs.Rectangle(-58.9,-513.5,125,19.69999999999999), null);


(lib.txt_AmazingProductivity = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgTAYIAAgvIAnAAIAAAvg");
	this.shape.setTransform(122.975,-109.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("Ag2BuIAAggIAMABQALAAAGgGQAFgGABgKIgvimIAsAAIAYByIABAAIAVhyIArAAIgoCbIgLAhQgFANgHAHQgGAHgJACQgKACgPAAg");
	this.shape_1.setTransform(113.125,-112.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgCBqQgJgCgDgFQgFgFgCgIQgBgJAAgMIAAhfIgWAAIAAgdIAWAAIAAgwIAqAAIAAAwIAYAAIAAAdIgYAAIAABZQAAAKADAEQADAFAJAAIAFgBIAEAAIAAAeIgNAAIgOABQgMAAgHgCg");
	this.shape_2.setTransform(102.5,-117.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgUBwIAAimIApAAIAACmgAgUhKIAAglIApAAIAAAlg");
	this.shape_3.setTransform(94.9,-118.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgXBUIgrinIAsAAIAXB3IABAAIAWh3IArAAIgpCng");
	this.shape_4.setTransform(85.075,-115.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgVBwIAAimIArAAIAACmgAgVhKIAAglIArAAIAAAlg");
	this.shape_5.setTransform(75.25,-118.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgDBqQgIgCgEgFQgEgFgCgIQgBgJAAgMIAAhfIgVAAIAAgdIAVAAIAAgwIAqAAIAAAwIAZAAIAAAdIgZAAIAABZQAAAKADAEQADAFAJAAIAFgBIAFAAIAAAeIgOAAIgOABQgNAAgHgCg");
	this.shape_6.setTransform(67.8,-117.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgbBTQgMgEgIgKQgIgKgEgRQgEgRAAgZQAAgYAFgRQAFgRAJgKQAJgKANgEQAMgEAOAAQAeAAAPARQAPARAAAeIgpAAIgBgMIgDgLQgCgFgEgCQgDgDgGAAQgHAAgFADQgFAEgDAHQgCAHgBAKIgBAZIABAaQABALACAHQADAHAEAEQAFADAGAAQALAAAFgJQAFgKAAgUIApAAQAAAhgPARQgPARgiAAQgPAAgMgEg");
	this.shape_7.setTransform(56.725,-115.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgzBKQgMgKAAgZIAAh7IAsAAIAAByQAAANAEAFQAEAFAKAAQAVAAABgbIAAhuIAqAAIAACmIgoAAIAAgUIgBAAQgHANgLAFQgKAFgNAAQgVAAgLgLg");
	this.shape_8.setTransform(42.55,-115.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("Ag0BcQgMgUAAguQAAguAMgVQAMgUAbAAQAMAAAHAFQAJAFAHAKIAAAAIAAhHIArAAIAADdIgpAAIAAgSIgBAAQgHAMgIAFQgIAFgNgBQgbAAgMgUgAgSgPQgEAOAAAbQAAAbAEANQAFAOANABQAOgBAEgOQAEgNAAgbQAAgbgEgOQgEgNgOAAQgNAAgFANg");
	this.shape_9.setTransform(27.625,-117.95);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgfBSQgMgFgIgLQgHgLgDgQQgEgRAAgWQAAgUAEgQQADgRAIgLQAIgLAMgGQANgFARAAQATgBANAGQANAFAHALQAIAMADAQQADAQAAAVQAAAWgEAQQgDARgIALQgHALgNAFQgNAFgSAAIgCAAQgRAAgMgFgAgLg1QgFAEgCAIQgDAIAAALIgBAWIABAYQAAALADAIQACAHAFAFQAEAEAHAAQANAAAFgOQAFgNAAggQAAgegFgOQgFgNgNAAQgHAAgEAEg");
	this.shape_10.setTransform(13.375,-115.425);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgrBWIAAinIApAAIAAAXIABAAQAGgMAIgIQAKgGANAAIAEAAIAEAAIAAApIgHgBIgHAAIgLACQgFACgFADQgEAEgDAFQgCAGAAAIIAABkg");
	this.shape_11.setTransform(2.2,-115.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhABwIAAjbIApAAIAAASIABAAQAHgMAIgFQAIgFANAAQAbAAAMAUQAMAVAAAuQAAAugMAUQgMAUgbAAQgMAAgHgEQgJgFgHgKIAAAAIAABFgAgRhBQgEAOAAAbQAAAbAEANQAEAOANAAQAOAAAFgOQAEgNAAgbQAAgbgEgOQgFgNgOAAQgNAAgEANg");
	this.shape_12.setTransform(-10.425,-112.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgvBmQgOgLAAgWIApAAQAAAIAGAEIAHAEIAHACQANAAAFgJQAFgIAAgNIAAgWIgBAAQgGAJgKAGQgIAGgKgBQgaABgMgUQgNgTAAgtIABgdQACgPAFgNQAGgMAKgIQALgIARABQAJAAAJAEQAJAFAGANIABAAIAAgTIApAAIAACeQAAAhgQAPQgQAQgkABQgcAAgPgMgAgKhMQgEACgDAIQgCAGgBAMIgBAdIABAQQABAGACAGQADAHAEADQAEAEAGAAQAHAAAEgEQAFgDACgHQADgGABgHIABgUQAAgegFgNQgFgNgMAAQgGAAgFAEg");
	this.shape_13.setTransform(-32.225,-112.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AAUBWIAAhyQABgOgFgEQgEgGgKAAQgWABABAbIAABuIgsAAIAAinIAqAAIAAAUIABAAQAGgMALgGQAKgGANABQAVAAALALQALAKAAAaIAAB7g");
	this.shape_14.setTransform(-46.75,-115.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgUBwIAAimIAqAAIAACmgAgUhKIAAglIAqAAIAAAlg");
	this.shape_15.setTransform(-57.45,-118.25);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("Ag5BUIAAghIBBhiIg+AAIAAgkIBxAAIAAAiIhCBiIBCAAIAAAjg");
	this.shape_16.setTransform(-67,-115.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_17.setTransform(-80.425,-115.425);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AA9BWIAAh0QAAgKgEgGQgEgFgJgBQgKABgGAGQgGAHAAAPIAABtIgqAAIAAh0QAAgKgEgGQgEgFgJgBQgKABgGAGQgGAHAAAPIAABtIgrAAIAAinIApAAIAAASIABAAQAIgLAKgGQAKgEAOAAQAPAAAJAGQAKAHADANIABAAQAFgNALgHQALgHAPABQAVAAAKAMQAKANAAAYIAAB5g");
	this.shape_18.setTransform(-98.725,-115.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AAoBvIgLgvIg5AAIgLAvIguAAIA6jdIA3AAIA6DdgAAWAbIgWhiIAAAAIgVBiIArAAg");
	this.shape_19.setTransform(-118.275,-118.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_AmazingProductivity, new cjs.Rectangle(-140.3,-138.8,279.6,40.60000000000001), null);


(lib.SureColor_lockup_intro = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AMlDvQgMgHgGgLQgFgMgCgPIgBgdQAAgQACgOQACgOAGgLQAHgLAMgHQAMgGAUAAQARAAALAFQALAFAHALQAGAKACAOQADAPAAASIAAAJIhPAAIABAZIAEAMQACAFAEADQADACAGABQAKAAAEgIQAFgGACgPIAjAAQgBAbgNANQgNAPgdAAQgVAAgMgIgAM9BzQgEADgCAEIgEAKIgBARIApAAIgBgQIgEgLQgCgFgDgDQgEgBgHAAQgFgBgEADgAgvDzQgMgDgGgGQgGgHgDgIQgDgJAAgMIAAgEIAkAAIAAAEQAAALAFAFQAGAHAKAAQAJgBAFgEQAGgEAAgKQAAgHgFgEQgEgEgGgCIgcgKQgQgGgIgKQgIgKAAgRQAAgKADgIQADgJAHgGQAHgGAKgEQALgDAQAAQAZgBANALQANAMAAAWIAAAFIgiAAQAAgLgEgGQgEgFgKAAQgHAAgGAEQgGAEAAAIQAAAGAEAFQAEAEAKADIAWAIQATAHAIAJQAIALAAASQAAALgFAKQgEAJgIAGQgHAGgLACQgJADgNAAQgQAAgLgEgAisDvQgMgHgFgLQgGgMgCgPIgBgdQAAgQACgOQADgOAGgLQAGgLAMgHQAMgGAUAAQASAAALAFQALAFAGALQAGAKACAOQADAPAAASIAAAJIhOAAIABAZIADAMQACAFAEADQAEACAFABQAKAAAFgIQAEgGACgPIAjAAQgBAbgNANQgNAPgcAAQgWAAgMgIgAiUBzQgEADgCAEIgDAKIgBARIAoAAIgBgQQgBgGgCgFQgCgFgEgDQgEgBgGAAQgGgBgEADgAn2DyQgMgFgHgMQgIgMgDgSQgDgTAAgbIACgpQABgTAGgPQAHgPANgJQAMgJAXAAQATAAAMAFQAMAFAHAMQAIAMACATQADATAAAbIgBAoQgBATgHAPQgGAQgNAIQgNAJgWAAQgTAAgMgFgAniBHQgFADgCAJQgDAHAAAOIAABVQAAAMADAIQADAGAEADQAEACAHABQAHAAAEgDQAEgEADgIQACgIABgNIAAhWQgBgMgDgHQgCgHgFgDQgEgCgGAAQgHAAgEADgAr0DyQgMgFgIgMQgHgMgDgSQgDgTAAgbIABgpQACgTAGgPQAGgPANgJQANgJAWAAQATAAAMAFQAMAFAIAMQAHAMADATQADATAAAbIgBAoQgCATgGAPQgGAQgNAIQgNAJgXAAQgSAAgMgFgArhBHQgEADgCAJQgDAHgBAOIAABVQABAMADAIQACAGAFADQAEACAGABQAHAAAFgDQAEgEACgIQADgIABgNIAAhWQgBgMgDgHQgCgHgFgDQgEgCgHAAQgGAAgFADgAt3DxQgMgEgGgJQgHgJgCgJQgCgKAAgJIAAgGIAnAAIABALQAAAGACAFQADAFAEADQAEAEAGAAQANAAAGgKQAFgKAAgUIgBgVQgBgIgDgEQgCgGgFgBQgEgCgHAAQgJAAgFAEQgFAFgBAJIglAAIAIhuIBpAAIAAAgIhKAAIgFAuIABAAQAGgIAJgDQAJgEANAAQAOAAAKAFQAKAGAFAJQAGAJACAMQADAMAAAMQAAAQgDAOQgDAOgHAKQgIAJgMAGQgNAFgTAAQgUAAgLgGgALhDyQgIgBgDgEQgEgGgCgHQgBgIAAgMIAAhYIgUAAIAAgbIAUAAIAAgsIAnAAIAAAsIAXAAIAAAbIgXAAIAABUQAAAJADAEQADADAIAAIAJAAIAAAbIgaACQgLgBgHgCgAOLDzIAAiaIAmAAIAAAVIAAAAQAGgLAJgHQAJgGAMAAIAHAAIAAAlIgXABQgFACgEAEQgEADgDAFQgDAGAAAHIAABcgAKODzIAAhqQAAgMgEgEQgDgFgJAAQgVAAAAAZIAABmIgoAAIAAiaIAmAAIAAASIABAAQAGgLAKgGQAKgEANAAQATAAAKAKQAKAKAAAYIAABxgAIIDzIAAiaIAoAAIAACagAGyDzIAAiaIAmAAIAAAVIAAAAQAGgLAJgHQAIgGANAAIAHAAIAAAlIgXABQgFACgEAEQgEADgDAFQgDAGAAAHIAABcgAEpDzIAAjMIBIAAQAQAAAKAFQALAGAHAJQAGAIADALQADALAAAMQAAAPgFAMQgFAMgIAHQgJAIgLADQgNAEgOAAIgWAAIAABRgAFSCDIASAAQANAAAHgHQAIgHAAgQQAAgPgHgJQgGgIgQAAIgRAAgAC1DzIAAhqQAAgMgEgEQgDgFgJAAQgVAAAAAZIAABmIgoAAIAAiaIAmAAIAAASQAHgLAKgGQAKgEANAAQATAAAKAKQAKAKAAAYIAABxgAAvDzIAAiaIAnAAIAACagAj2DzQgDgEgBgGIgCgyQgBgMgFgHQgGgGgMAAIgXAAIAABVIgpAAIAAjMIBMAAQAaAAAOANQAPAOAAAaQAAAVgJAMQgIANgRAEIAAABQAPACAHAIQAHAHACARIADA1QACAJAGADIAAABgAkrCBIASAAQAOgBAJgGQAHgIAAgQQAAgcgcgBIgUAAgAp/DzQADgSAEgUQAFgUAHgVQAIgVALgVQALgVAPgVIhWAAIAAgjIB9AAIAAAgQgMASgKATQgKAVgIAVQgHAVgFAXQgFAWgCAVgAvCDzQgDgEgBgGIgCgyQgBgMgGgHQgFgGgNAAIgWAAIAABVIgpAAIAAjMIBMAAQAaAAAOANQAPAOAAAaQAAAVgJAMQgIANgRAEIAAABQAPACAHAIQAHAHACARIADA1QACAJAGADIAAABgAv3CBIASAAQAOgBAIgGQAIgIAAgQQAAgcgcgBIgUAAgAIIBGIAAgiIAoAAIAAAigAAvBGIAAgiIAnAAIAAAigALrgnQgLgFgHgKQgHgKgDgQQgDgPAAgTQAAgVADgOQADgQAIgKQAHgKALgGQAMgEARAAQARgBAMAFQAMAFAHALQAHAKACAPQAEAPAAAVQAAATgEAPQgDAQgHAJQgHALgMAFQgLAEgRAAIgDABQgQAAgLgFgAL9ilQgEAFgCAGQgCAHgBAKIAAAsQABAKACAIQACAGAEAEQAEAEAIABQAMAAAEgNQAFgNAAgcQAAgegFgMQgEgNgMAAQgIAAgEAEgAI2gnQgMgFgHgKQgHgKgCgQQgEgPAAgTQAAgVAEgOQADgQAHgKQAHgKAMgGQALgEARAAQASgBAMAFQAMAFAHALQAGAKADAPQADAPAAAVQAAATgDAPQgDAQgIAJQgHALgLAFQgMAEgRAAIgDABQgQAAgKgFgAJIilQgEAFgDAGQgCAHAAAKIAAAsQAAAKACAIQADAGAEAEQAEAEAHABQANAAAEgNQAFgNAAgcQAAgegFgMQgEgNgNAAQgHAAgEAEgAGsgqQgOgHgHgPQgHgOgCgTQgCgTAAgYQAAgXACgUQACgTAHgPQAHgNAOgIQAOgIAXAAQAWAAANAHQANAHAGALQAGALACANIABAYIgpAAQAAgXgFgKQgFgJgPgBQgHAAgFAFQgFADgDAKQgDAJgBAPIgBAlQAAAXABAOQACAPADAIQADAHAFAEQAGACAGAAQAFAAAFgCQAFgCADgFQAEgGACgKQACgKAAgRIApAAQAAARgDAPQgCAPgHALQgHALgNAGQgNAHgUgBQgXABgOgIgAErgpQgMgIgGgLQgGgMgBgOIgBgeQAAgPACgPQACgPAGgLQAHgLAMgGQAMgHAUABQARgBALAGQALAGAGAKQAHAKACAPQACAOAAARIAAAJIhOAAIABAaIADALQADAGADACQAEADAFABQALgBAEgGQAFgIACgPIAjAAQgBAbgNAPQgNANgdAAQgVAAgMgGgAFCimQgDADgDAFIgDAJIgBARIApAAIgBgPIgEgMQgCgFgDgCQgFgDgGAAQgFAAgFADgABLgsQgLgLAAgWIAAhzIAoAAIAABrQAAAMAEAFQAEAEAJAAQAVAAAAgaIAAhmIAnAAIAACaIgmAAIAAgSIAAAAQgHAMgJAFQgKAEgNAAQgTABgKgKgAg/gxQgPgQAAgcIAAgJIAqAAIABATQABAHADADQADAFAGACQAFACAIAAQAJAAAHgGQAIgGAAgNQAAgHgCgFQgCgFgFgEQgEgEgGgEIgRgGIgYgKQgKgGgHgHQgGgHgEgKQgCgKAAgMQAAgeAQgPQARgPAeAAQAMAAAMADQALADAJAGQAJAIAEAKQAFAKAAAPIAAAGIgoAAQAAgPgFgIQgFgHgLgBQgHAAgFACQgEACgDADQgCAEgBAEIgCAJQAAAKAFAGQAEAHANAFIAfAOQALAFAIAFQAHAGAFAGQAEAHACAIQABAHAAAKQAAAggSAPQgTAOghAAQgiAAgQgOgAmggpQgMgIgFgLQgGgMgCgOIgBgeQAAgPACgPQACgPAHgLQAGgLAMgGQAMgHAUABQARgBAMAGQALAGAGAKQAGAKACAPQADAOAAARIAAAJIhOAAIAAAaIAEALQACAGAEACQAEADAFABQAKgBAFgGQAEgIACgPIAjAAQgBAbgNAPQgNANgcAAQgWAAgMgGgAmIimQgEADgCAFIgEAJIAAARIAoAAIgBgPQgBgIgCgEQgCgFgEgCQgEgDgGAAQgGAAgEADgArogpQgMgIgGgLQgGgMgBgOIgBgeQAAgPACgPQACgPAGgLQAHgLAMgGQAMgHAUABQARgBALAGQALAGAGAKQAHAKACAPQACAOAAARIAAAJIhOAAIABAaIADALQADAGADACQAEADAFABQALgBAEgGQAFgIACgPIAjAAQgBAbgNAPQgNANgdAAQgVAAgMgGgArRimQgDADgDAFIgDAJIgBARIApAAIgBgPIgEgMQgCgFgDgCQgFgDgGAAQgFAAgFADgANOgmIAAiaIAmAAIAAAVIABAAQAGgLAIgHQAJgHAMABIAHAAIAAAmIgMgBIgKACQgGABgEADQgEADgDAGQgCAFAAAIIAABcgAKagmIAAjMIAoAAIAADMgADDgmIAAiaIAmAAIAAAVIABAAQAGgLAIgHQAJgHAMABIAHAAIAAAmIgMgBIgKACQgGABgEADQgEADgDAGQgCAFAAAIIAABcgAjQgmIgUhtIgBAAIgTBtIguAAIghiaIAoAAIASBuIAThuIArAAIAVBuIAShuIAmAAIghCagAnygmIgyiPIgBAAIAACPIgmAAIAAjMIAwAAIAyCMIAAiMIAmAAIAADMgAsygmIAAhqQAAgMgEgFQgEgEgJAAQgVAAAAAZIAABmIgoAAIAAjMIAoAAIAABCIABAAQALgTAaAAQATgBAKALQAKAKAAAXIAABygAvagmIAAiqIgsAAIAAgiICCAAIAAAiIgtAAIAACqgAPRhxQgLgFgIgHQgHgIgFgLQgEgKAAgMQAAgMAEgLQAFgJAHgJQAIgHALgFQAKgFAMAAQAMAAALAFQAKAFAIAHQAIAJAEAJQAFALAAAMQAAAMgFAKQgEALgIAIQgIAHgKAFQgLAEgMAAQgMAAgKgEgAPXjLQgHADgGAFQgFAGgDAHQgDAIAAAIQAAAJADAHQADAIAFAFQAGAFAHAEQAIADAIAAQAJAAAHgDQAIgEAFgFQAGgFACgIQADgHAAgJQAAgIgDgIQgCgHgGgGQgFgFgIgDQgHgEgJAAQgIAAgIAEgAPyiHIgOgZIgGAAIAAAZIgNAAIAAg+IAYAAQAMAAAGAFQAGAFAAAJQAAAJgEAEQgFAEgGAAIAPAagAPeirIALAAIAHgBQADgBAAgGIgBgEIgDgCIgIgBIgJAAg");
	this.shape.setTransform(-13.275,-78.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.SureColor_lockup_intro, new cjs.Rectangle(-118.9,-103.1,211.3,49.39999999999999), null);


(lib.SureColor_lockup = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ASpBWQgKgGgFgKQgFgLgCgNIgBgZQAAgOACgLQACgNAGgJQAFgKALgGQAKgFASAAQAPAAAJAEQAKAFAFAJQAGAJACAMQACANAAAPIAAAHIhEAAIABAXIADAKIAFAHQADACAFABQAJAAAEgHQADgGACgNIAfAAQgBAYgMAMQgLAMgZAAQgSABgLgHgAS+gVIgFAFIgDAJIgBAIIAAAGIAjAAIgBgNQgBgFgCgFQgBgEgEgCQgDgCgGAAQgFAAgDADgAHJBZQgJgDgGgFQgFgGgDgHQgCgIAAgKIAAgFIAfAAIAAAFQAAAIAFAGQAEAFAJABQAIAAAFgFQAFgDAAgJQAAgGgEgEIgJgFIgYgJQgPgEgHgJQgHgKAAgNQAAgIADgHQACgIAHgGQAGgFAJgEQAJgCAOAAQAXgBALALQAMAJAAATIAAAGIgfAAQAAgLgEgFQgDgFgJAAQgGAAgFAEQgFADAAAHQAAAFADAEQADAEAJADIAVAGQAQAFAHAJQAGAKAAAPQAAAKgDAJQgEAHgHAFQgGAGgJACQgJACgLAAQgPAAgKgDgAFeBWQgKgGgFgKQgFgLgCgNIgBgZQAAgOACgLQACgNAGgJQAFgKALgGQAKgFASAAQAPAAAJAEQAKAFAFAJQAGAJACAMQACANAAAPIAAAHIhEAAIABAXIADAKIAFAHQADACAFABQAJAAAEgHQADgGACgNIAfAAQgBAYgMAMQgLAMgZAAQgSABgLgHgAFzgVIgFAFIgDAJIgBAIIAAAGIAjAAIgBgNQgBgFgCgFQgBgEgEgCQgDgCgGAAQgFAAgDADgABBBYQgLgEgGgLQgGgJgDgRQgDgQAAgYIABgjQACgQAFgNQAGgOALgIQALgHAUgBQAQAAALAFQAKAFAHAKQAGAKADARQACAQAAAXIgBAjQgBARgGANQgFANgLAIQgMAHgTAAQgQABgLgFgABSg8QgEADgCAGQgCAIgBALIAABKQABALACAGQADAGADADQAEACAGAAQAGAAADgDQAEgEACgGQADgHAAgMIAAhKQAAgKgDgHQgCgGgEgCQgDgCgGAAQgGAAgEADgAiaBYQgLgEgGgLQgGgJgDgRQgDgQAAgYIABgjQACgQAFgNQAGgOALgIQALgHAUgBQAQAAALAFQAKAFAHAKQAGAKADARQACAQAAAXIgBAjQgBARgGANQgFANgLAIQgMAHgTAAQgQABgLgFgAiJg8QgEADgCAGQgCAIgBALIAABKQABALACAGQADAGADADQAEACAGAAQAGAAADgDQAEgEACgGQADgHAAgMIAAhKQAAgKgDgHQgCgGgEgCQgDgCgGAAQgGAAgEADgAkMBYQgKgEgFgIQgGgHgCgJQgCgIAAgJIAAgEIAjAAIAAAKQABAFACAEQABAEAEADQAEADAFAAQALAAAFgIQAFgJAAgRIgBgSQgBgIgCgEQgCgEgEgBQgFgCgFAAQgIAAgEADQgEAFgBAHIghAAIAHhfIBcAAIAAAcIhBAAIgEAoIAAAAQAFgHAJgDQAHgDAMAAQANAAAIAFQAIAEAFAJQAFAIACAJQACAKAAAKQAAAPgCAMQgDAMgGAJQgHAJgLAEQgLAFgQgBQgRABgLgFgApxBYQgKgEgGgIQgGgJgDgOQgCgOAAgRQAAgRADgNQACgNAHgIQAGgKAKgEQAKgFAPABQAPgBAKAEQALAFAGAJQAGAJACANQADANAAARQAAARgDAOQgDANgGAJQgGAJgKAEQgLAFgOgBQgQAAgKgEgAphgUQgEADgCAHQgCAFAAAIIAAAnQAAAIACAGQACAHAEADQADADAHABQAKgBAEgKQAEgLAAgaQAAgYgEgLQgEgLgKAAQgHAAgDAEgAsRBYQgKgEgGgIQgGgJgDgOQgCgOAAgRQAAgRADgNQACgNAHgIQAGgKAKgEQAKgFAPABQAPgBAKAEQALAFAGAJQAGAJACANQADANAAARQAAARgDAOQgDANgGAJQgGAJgKAEQgLAFgOgBQgQAAgKgEgAsBgUQgEADgCAHQgCAFAAAIIAAAnQAAAIACAGQACAHAEADQADADAHABQAKgBAEgKQAEgLAAgaQAAgYgEgLQgEgLgKAAQgHAAgDAEgAuKBWQgMgHgGgMQgHgMgCgSQgBgQAAgVQAAgTABgRQACgSAHgLQAGgNAMgGQAMgIAUABQATgBAMAHQALAGAFAJQAGAKABAMIACAUIglAAQAAgTgEgJQgFgJgMAAQgHAAgEADQgEAFgDAIQgCAHgBAOIgBAeIABAhQABANADAHQADAHAEACQAFADAFAAQAFAAAEgCQAFgBACgFQAEgGABgJQACgIAAgOIAkAAQAAAOgCANQgDANgGAJQgGAKgLAGQgLAFgSAAQgUAAgMgGgAv7BWQgLgGgFgKQgFgLgBgNIgBgZQAAgOACgLQACgNAFgJQAGgKAKgGQALgFARAAQAPAAAKAEQAJAFAGAJQAFAJADAMQACANAAAPIAAAHIhFAAIABAXIADAKIAFAHQADACAFABQAJAAAEgHQAEgGACgNIAfAAQgCAYgLAMQgLAMgZAAQgTABgKgHgAvngVIgFAFIgDAJIgBAIIAAAGIAkAAIgCgNQAAgFgCgFQgCgEgDgCQgEgCgFAAQgFAAgEADgAzABTQgJgIAAgVIAAhiIAiAAIAABcQAAALAEADQADAEAIABQASgBAAgWIAAhYIAjAAIAACFIghAAIAAgPIgBAAQgFAKgJAEQgJAFgLgBQgQAAgJgJgA06BPQgNgOAAgYIAAgHIAkAAIABARQABAEADAEQADADAEACQAFACAHABQAIAAAHgGQAHgFAAgMQAAgFgCgFQgCgEgEgEQgDgDgGgDIgPgGQgNgEgIgEQgJgGgGgFQgGgHgDgHQgCgJAAgLQAAgbAOgNQAPgNAaABQAMgBAKADQAKADAIAFQAHAHAEAJQAEAJAAAMIAAAGIgiAAQAAgNgFgHQgEgHgLAAQgGAAgEABQgEACgCAEIgDAGIgBAHQAAAJADAGQAEAFALAFIAcAMQAKAFAHADQAGAFAEAGQAEAFACAHQABAHAAAIQAAAcgQANQgRANgdAAQgfAAgNgNgARuBZQgGgCgDgEQgEgEgBgHQgBgGAAgLIAAhLIgSAAIAAgYIASAAIAAgmIAiAAIAAAmIAUAAIAAAYIgUAAIAABIQAAAHADADQACAEAIAAIADAAIAEgBIAAAYIgWABIgRgBgAUBBZIAAiFIAhAAIAAASIAAAAQAGgJAHgHQAIgFAKAAIADAAIAEAAIAAAhIgLgBIgJACQgFABgEADQgDADgDAFQgCADAAAGIAABRgAQoBZIAAhbQAAgLgEgEQgDgEgIAAQgSAAAAAVIAABZIgjAAIAAiFIAhAAIAAAQIABAAQAFgLAJgEQAJgFALABQAQgBAJAKQAJAIAAAVIAABigAOzBZIAAiFIAjAAIAACFgANpBZIAAiFIAhAAIAAASIABAAQAFgJAHgHQAIgFALAAIADAAIADAAIAAAhIgLgBIgJACQgEABgEADQgEADgCAFQgCADAAAGIAABRgALzBZIAAixIA/AAQANAAAKAFQAJAEAGAIQAGAHACAKQADAJAAAKQAAAOgEALQgFAKgHAGQgHAFgLAEQgKADgNAAIgTAAIAABHgAMXgIIAQAAQAKAAAHgFQAHgHAAgOQAAgNgGgIQgGgHgNAAIgPAAgAKQBZIAAhbQAAgLgDgEQgEgEgIAAQgSAAAAAVIAABZIgiAAIAAiFIAhAAIAAAQIAAAAQAGgLAIgEQAJgFALABQARgBAJAKQAJAIAAAVIAABigAIcBZIAAiFIAiAAIAACFgAEeBZQgCgDgBgFIgCgtQgBgKgFgGQgEgGgMAAIgTAAIAABLIgkAAIAAixIBDAAQAWAAANAMQAMAKAAAYQAAASgHAMQgHAKgPADIAAAAQANACAGAHQAHAHABAPIADAuQABAHAFADIAAABgADwgKIAPAAQANAAAHgGQAHgHAAgOQAAgZgZAAIgRAAgAg0BZQABgQAFgRQAEgSAGgSQAHgSAJgSQAKgSAMgSIhKAAIAAgfIBsAAIAAAcQgLAPgIASQgJASgHARQgFATgEAUQgFASgCATgAlMBZQgCgDgBgFIgCgtQgBgKgFgGQgEgGgMAAIgTAAIAABLIgkAAIAAixIBDAAQAWAAANAMQAMAKAAAYQAAASgHAMQgHAKgPADIAAAAQANACAGAHQAHAHABAPIADAuQABAHAFADIAAABgAl6gKIAPAAQANAAAHgGQAHgHAAgOQAAgZgZAAIgRAAgAoaBZIAAiFIAhAAIAAASIABAAQAFgJAHgHQAIgFALAAIADAAIADAAIAAAhIgLgBIgJACQgEABgEADQgEADgCAFQgCADAAAGIAABRgAq5BZIAAixIAjAAIAACxgAxWBZIAAiFIAhAAIAAASIAAAAQAGgJAHgHQAIgFAKAAIADAAIAEAAIAAAhIgLgBIgJACQgFABgEADQgDADgDAFQgCADAAAGIAABRgAOzg9IAAgdIAjAAIAAAdgAIcg9IAAgdIAiAAIAAAdg");
	this.shape.setTransform(-12.325,-68.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.SureColor_lockup, new cjs.Rectangle(-147.5,-77.9,270.4,18.500000000000007), null);


(lib.printer_light_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.printer_light();
	this.instance.setTransform(-81.5,-11);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_light_1, new cjs.Rectangle(-81.5,-11,163,22), null);


(lib.image_03_slices = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_03_LG();
	this.instance.setTransform(-141,-203);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_03_slices, new cjs.Rectangle(-141,-203,282,406), null);


(lib.image_02_slices = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_02_LG();
	this.instance.setTransform(-141,-203);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_02_slices, new cjs.Rectangle(-141,-203,282,406), null);


(lib.image_01_slices = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_01_LG();
	this.instance.setTransform(-141,-203);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_01_slices, new cjs.Rectangle(-141,-203,282,406), null);


(lib.image_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_01();
	this.instance.setTransform(-179.5,-72);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_01_1, new cjs.Rectangle(-179.5,-72,359,144), null);


(lib.epson_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Epson_Logo();
	this.instance.setTransform(-72,-31,0.593,0.593);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.epson_logo, new cjs.Rectangle(-72,-31,77.7,28.5), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape.setTransform(61.025,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_1.setTransform(47.475,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag1A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAfABAWAVQAXAXAAAeQAAAggXAVQgWAXgfAAQgfAAgWgXgAghghQgOAOAAATQAAAUAOAOQAOAPATAAQAUAAAOgPQAOgOAAgUQAAgTgOgOQgOgPgUAAQgTAAgOAPg");
	this.shape_2.setTransform(31.275,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBBMQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIglhSIgBAAIgMBOQAAADgEABIgSAAQgFgBABgEIAZiNQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAuBiIAAAAIAuhiQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAIADAAQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIAZCNQABAEgFABIgTAAQgDgBgBgDIgMhOIgBAAIglBSQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(13.1508,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BMQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIhUheIgBAAIAABZQAAAEgEABIgTAAQgEgBAAgEIAAiMQAAgDAEgBIADAAQABABAAAAQAAAAABAAQAAAAABAAQAAABABAAIBUBaIAAAAIAAhVQAAgFAFAAIATAAQAEAAAAAFIAACMQAAADgEABg");
	this.shape_4.setTransform(-10,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_5.setTransform(-25.075,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAwBLQgEgBgCgEIgLgWIg+AAIgKAWQgBAEgFABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIBBiNQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIACAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIBACNQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAVAYIgVgtIAAAAIgUAtIApAAg");
	this.shape_6.setTransform(-39.85,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_7.setTransform(-52.925,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBKQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAB1IA0AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_8.setTransform(-64.475,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_9.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,162.5,51.5), null);


(lib.printer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// printer_light
	this.instance = new lib.printer_light_1();
	this.instance.setTransform(-15.3,-47.6,0.9639,0.9639,0,0,0,-0.1,-0.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(10).to({_off:false},0).to({_off:true},42).wait(289));

	// Gradient
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],0.3,-8.6,0.3,8.6).s().p("AtlBWIAAirIbLAAIAACrg");
	this.shape.setTransform(-15,18.475);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(8).to({_off:false},0).wait(44).to({_off:true},1).wait(287));

	// image_Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AukFgIAAq/IdJAAIAAK/g");
	var mask_graphics_9 = new cjs.Graphics().p("AukFgIAAq/IdJAAIAAK/g");
	var mask_graphics_53 = new cjs.Graphics().p("AukFgIAAq/IdJAAIAAK/g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-14.4,y:45.375}).wait(1).to({graphics:null,x:0,y:0}).wait(8).to({graphics:mask_graphics_9,x:-14.4,y:45.375}).wait(44).to({graphics:mask_graphics_53,x:-14.4,y:45.375}).wait(1).to({graphics:null,x:0,y:0}).wait(287));

	// image_01
	this.instance_1 = new lib.image_01_1();
	this.instance_1.setTransform(-14.25,-24.9,0.4802,0.4802);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({y:46.3},42,cjs.Ease.quadInOut).wait(1).to({_off:true},1).wait(287));

	// printer
	this.instance_2 = new lib.Printer();
	this.instance_2.setTransform(-160,-87);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},1).wait(8).to({_off:false},0).wait(44).to({_off:true},1).wait(287));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160,-87,320,174);


(lib.image_03_LG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// slice_01_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgEDAhdMAAAhC5IP7AAMAAABC5g");
	var mask_graphics_69 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:76,y:6}).wait(69).to({graphics:mask_graphics_69,x:100.975,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(311));

	// Layer_1
	this.instance = new lib.image_03_slices();
	this.instance.setTransform(0,-422);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(22).to({_off:true},1).wait(311));

	// slice_01_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EgHfAhdMAAAhC5IO/AAMAAABC5g");
	var mask_1_graphics_69 = new cjs.Graphics().p("EgHfAhdMAAAhC5IO/AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:-0.025,y:6}).wait(69).to({graphics:mask_1_graphics_69,x:-0.025,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(311));

	// Layer_1
	this.instance_1 = new lib.image_03_slices();
	this.instance_1.setTransform(0,-422);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(15).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(37).to({_off:true},1).wait(311));

	// slice_01_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");
	var mask_2_graphics_69 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:-97.025,y:6}).wait(69).to({graphics:mask_2_graphics_69,x:-97.025,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(311));

	// Layer_1
	this.instance_2 = new lib.image_03_slices();
	this.instance_2.setTransform(0,-422);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:0},17,cjs.Ease.quadOut).wait(52).to({_off:true},1).wait(311));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141,-208,282,411);


(lib.image_02_LG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// slice_01_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgEDAhdMAAAhC5IP7AAMAAABC5g");
	var mask_graphics_113 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:76,y:6}).wait(113).to({graphics:mask_graphics_113,x:100.975,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(267));

	// Layer_1
	this.instance = new lib.image_02_slices();
	this.instance.setTransform(0,-422);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(66).to({_off:true},1).wait(267));

	// slice_01_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EgHfAhdMAAAhC5IO/AAMAAABC5g");
	var mask_1_graphics_113 = new cjs.Graphics().p("EgHfAhdMAAAhC5IO/AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:-0.025,y:6}).wait(113).to({graphics:mask_1_graphics_113,x:-0.025,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(267));

	// Layer_1
	this.instance_1 = new lib.image_02_slices();
	this.instance_1.setTransform(0,-422);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(15).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(81).to({_off:true},1).wait(267));

	// slice_01_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");
	var mask_2_graphics_113 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:-97.025,y:6}).wait(113).to({graphics:mask_2_graphics_113,x:-97.025,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(267));

	// Layer_1
	this.instance_2 = new lib.image_02_slices();
	this.instance_2.setTransform(0,-422);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:0},17,cjs.Ease.quadOut).wait(96).to({_off:true},1).wait(267));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141,-208,282,411);


(lib.image_01_LG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// slice_01_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgEDAhdMAAAhC5IP7AAMAAABC5g");
	var mask_graphics_168 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:76,y:6}).wait(168).to({graphics:mask_graphics_168,x:100.975,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(212));

	// Layer_1
	this.instance = new lib.image_01_slices();
	this.instance.setTransform(0,-422);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(121).to({_off:true},1).wait(212));

	// slice_01_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EgHfAhdMAAAhC5IO/AAMAAABC5g");
	var mask_1_graphics_168 = new cjs.Graphics().p("EgHfAhdMAAAhC5IO/AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:-0.025,y:6}).wait(168).to({graphics:mask_1_graphics_168,x:-0.025,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(212));

	// Layer_1
	this.instance_1 = new lib.image_01_slices();
	this.instance_1.setTransform(0,-422);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(15).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(136).to({_off:true},1).wait(212));

	// slice_01_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");
	var mask_2_graphics_168 = new cjs.Graphics().p("EgH9AhdMAAAhC5IP7AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:-97.025,y:6}).wait(168).to({graphics:mask_2_graphics_168,x:-97.025,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(212));

	// Layer_1
	this.instance_2 = new lib.image_01_slices();
	this.instance_2.setTransform(0,-422);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:0},17,cjs.Ease.quadOut).wait(151).to({_off:true},1).wait(212));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141,-208,282,411);


// stage content:
(lib.Epson_RDrive_300x250_V3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// epson_logo
	this.instance = new lib.epson_logo();
	this.instance.setTransform(76.5,41);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},9).wait(34).to({alpha:0},11).wait(178).to({alpha:1},9).wait(119));

	// Layer_4
	this.instance_1 = new lib.txt_AmazingProductivity();
	this.instance_1.setTransform(147.05,185,1,1,0,0,0,-3,0);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(281).to({_off:false},0).to({y:172,alpha:1},8,cjs.Ease.quadOut).wait(31).to({alpha:0},8).wait(32));

	// txt_Immediatelamination
	this.instance_2 = new lib.txt_Immediatelamination();
	this.instance_2.setTransform(148.05,185.05,1,1,0,0,0,-6,0);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(232).to({_off:false},0).to({y:172.05,alpha:1},9,cjs.Ease.quadOut).wait(32).to({alpha:0},8).wait(79));

	// SureColor_lockup
	this.instance_3 = new lib.SureColor_lockup();
	this.instance_3.setTransform(162.05,139.95);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(326).to({_off:false},0).to({alpha:1},15).wait(19));

	// ctaBtn_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_345 = new cjs.Graphics().p("AmuCUQgjAAAAgjIAAAAIAAjhQAAgjAjAAIAAAAINdAAQAjAAAAAjIAAAAIAADhQAAAjgjAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(345).to({graphics:mask_graphics_345,x:150.0142,y:111.7143}).wait(15));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-12.6,-9.7,12.7,9.6).s().p("AnTFdIKqt6ID9DBIqqN6g");
	this.shape_1.setTransform(87.875,90.6);
	this.shape_1._off = true;

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-12.6,-9.7,12.7,9.6).s().p("AnTFdIKqt7ID9DCIqqN7g");
	this.shape_2.setTransform(89.125,91);
	this.shape_2._off = true;

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-12.6,-9.7,12.7,9.6).s().p("AnTFdIKqt7ID9DCIqqN6g");
	this.shape_3.setTransform(211.575,130.7);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},345).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_1}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(345).to({_off:false},0).to({_off:true},1).wait(4).to({_off:false,x:119.775,y:100.95},0).to({_off:true},1).wait(1).to({_off:false,x:150.375,y:110.85},0).to({_off:true},1).wait(1).to({_off:false,x:180.975,y:120.75},0).wait(1).to({x:192.475,y:124.5},0).wait(1).to({x:201.375,y:127.4},0).wait(1).to({x:207.775,y:129.45},0).to({_off:true},1).wait(1).to({_off:false,x:212.875,y:131.1},0).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(346).to({_off:false},0).wait(1).to({x:92.975,y:92.25},0).wait(1).to({x:99.375,y:94.3},0).wait(1).to({x:108.275,y:97.2},0).to({_off:true},1).wait(1).to({_off:false,x:133.775,y:105.5},0).to({_off:true},1).wait(1).to({_off:false,x:166.975,y:116.2},0).to({_off:true},1).wait(6));

	// ctaBtn
	this.instance_4 = new lib.ctaBtn();
	this.instance_4.setTransform(150.05,111.7,0.5728,0.5728,0,0,0,0.1,0);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(335).to({_off:false},0).to({alpha:1},10).wait(15));

	// printer_mc
	this.instance_5 = new lib.printer_mc("single",9);
	this.instance_5.setTransform(151.15,150.1,0.8379,0.8379,0,0,0,0.2,0.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(232).to({_off:false},0).to({regY:0,scaleX:0.9423,scaleY:0.9423,x:151.2,y:155,alpha:1,mode:"synched",loop:false},9,cjs.Ease.quadOut).wait(44).to({mode:"single",startPosition:53},0).wait(35).to({startPosition:53},0).to({regX:0.4,regY:0.1,scaleX:0.6661,scaleY:0.6661,x:150.25,y:184.1},15,cjs.Ease.quadOut).wait(25));

	// BG
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_4.setTransform(150,125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,255,255,0.11)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_5.setTransform(150,125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0.224)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_6.setTransform(150,125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.333)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_7.setTransform(150,125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,255,255,0.443)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_8.setTransform(150,125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(255,255,255,0.557)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_9.setTransform(150,125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0.667)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_10.setTransform(150,125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.776)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_11.setTransform(150,125);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(255,255,255,0.89)").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_12.setTransform(150,125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_13.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_4}]},223).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).wait(128));

	// txt_onARoll
	this.instance_6 = new lib.txt_greater();
	this.instance_6.setTransform(144.05,528.4);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(54).to({_off:false},0).to({alpha:1},9).wait(158).to({alpha:0},11).to({_off:true},1).wait(127));

	// Layer_1
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#2D3482").ss(2,2,1).p("AgJAAIATAA");
	this.shape_14.setTransform(56.75,53.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#2D3482").ss(2,2,1).p("AgUAAIApAA");
	this.shape_15.setTransform(57.9,53.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#2D3482").ss(2,2,1).p("Ag3AAIBvAA");
	this.shape_16.setTransform(61.4,53.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#2D3482").ss(2,2,1).p("AhxAAIDjAA");
	this.shape_17.setTransform(67.2,53.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#2D3482").ss(2,2,1).p("AjCAAIGFAA");
	this.shape_18.setTransform(75.325,53.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#2D3482").ss(2,2,1).p("AkTAAIInAA");
	this.shape_19.setTransform(83.425,53.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#2D3482").ss(2,2,1).p("AlNAAIKbAA");
	this.shape_20.setTransform(89.225,53.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#2D3482").ss(2,2,1).p("AlwAAILhAA");
	this.shape_21.setTransform(92.725,53.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#2D3482").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_22.setTransform(93.875,53.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("rgba(45,52,130,0.91)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_23.setTransform(93.875,53.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("rgba(45,52,130,0.82)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_24.setTransform(93.875,53.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("rgba(45,52,130,0.725)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_25.setTransform(93.875,53.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("rgba(45,52,130,0.635)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_26.setTransform(93.875,53.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("rgba(45,52,130,0.545)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_27.setTransform(93.875,53.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("rgba(45,52,130,0.455)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_28.setTransform(93.875,53.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("rgba(45,52,130,0.365)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_29.setTransform(93.875,53.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("rgba(45,52,130,0.275)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_30.setTransform(93.875,53.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("rgba(45,52,130,0.18)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_31.setTransform(93.875,53.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("rgba(45,52,130,0.09)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_32.setTransform(93.875,53.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("rgba(45,52,130,0)").ss(2,2,1).p("Al8AAIL5AA");
	this.shape_33.setTransform(93.875,53.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_14}]},160).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_22}]},53).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[]},1).wait(127));

	// txt_onARoll
	this.instance_7 = new lib.txt_onARoll();
	this.instance_7.setTransform(74.05,528.4);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(147).to({_off:false},0).to({x:144.05,alpha:1},11,cjs.Ease.quadOut).wait(63).to({alpha:0},11).to({_off:true},1).wait(127));

	// txt_Immediatelamination
	this.instance_8 = new lib.txt_greaterConsistency();
	this.instance_8.setTransform(157.3,509.65);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(54).to({_off:false},0).to({alpha:1},9).wait(73).to({x:230.8,alpha:0},11,cjs.Ease.quadOut).to({_off:true},86).wait(127));

	// Image_Strip_Mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_54 = new cjs.Graphics().p("AHxfuIAA2gIOSAAIAAWggAnBfuIAA2gIOVAAIAAWggA2CfuIAA2gIOjAAIAAWggAHxjvIAA7JIAAg2IOSAAIAAb/gAnBjvIAA7/IOVAAIAAA2IAAbJgA2CjvIAA7/IOjAAIAAb/g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(54).to({graphics:mask_1_graphics_54,x:151.05,y:268.05}).wait(179).to({graphics:null,x:0,y:0}).wait(127));

	// image_03_LG
	this.instance_9 = new lib.image_03_LG_1("synched",0,false);
	this.instance_9.setTransform(151,210);
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(163).to({_off:false},0).to({_off:true},70).wait(127));

	// image_02_LG
	this.instance_10 = new lib.image_02_LG_1("synched",0,false);
	this.instance_10.setTransform(151,210);
	this.instance_10._off = true;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(109).to({_off:false},0).to({_off:true},114).wait(137));

	// image_01_LG
	this.instance_11 = new lib.image_01_LG_1("synched",0,false);
	this.instance_11.setTransform(151,210);
	this.instance_11._off = true;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(54).to({_off:false},0).to({_off:true},169).wait(137));

	// logo_Lockup
	this.instance_12 = new lib.SureColor_lockup_intro();
	this.instance_12.setTransform(163.3,163.55);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({y:154.55,alpha:1},9).wait(34).to({alpha:0},10).to({_off:true},1).wait(306));

	// wht_fade
	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("rgba(255,255,255,0)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_34.setTransform(150.05,177.075);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("rgba(255,255,255,0.102)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_35.setTransform(150.05,177.075);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("rgba(255,255,255,0.2)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_36.setTransform(150.05,177.075);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("rgba(255,255,255,0.302)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_37.setTransform(150.05,177.075);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("rgba(255,255,255,0.4)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_38.setTransform(150.05,177.075);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("rgba(255,255,255,0.502)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_39.setTransform(150.05,177.075);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("rgba(255,255,255,0.6)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_40.setTransform(150.05,177.075);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("rgba(255,255,255,0.698)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_41.setTransform(150.05,177.075);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("rgba(255,255,255,0.8)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_42.setTransform(150.05,177.075);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(255,255,255,0.898)").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_43.setTransform(150.05,177.075);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("A3SLaIAA2zMAukAAAIAAWzg");
	this.shape_44.setTransform(150.05,177.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_34}]},43).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[]},1).wait(306));

	// printer_mc
	this.instance_13 = new lib.printer_mc("single",0);
	this.instance_13.setTransform(147.45,170.15,0.7582,0.7582,0,0,0,0.6,0.2);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({regX:0.4,scaleX:0.8269,scaleY:0.8269,x:147.35,y:175.15,alpha:1,startPosition:9},9,cjs.Ease.quadOut).to({_off:true},45).wait(306));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(135.1,124,166.6,289);
// library properties:
lib.properties = {
	id: 'A4BDA2797E5D4A2296AB1960FDA0E060',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Epson_Logo.png", id:"Epson_Logo"},
		{src:"image_01.jpg", id:"image_01"},
		{src:"image_01_LG.jpg", id:"image_01_LG"},
		{src:"image_02.jpg", id:"image_02"},
		{src:"image_02_LG.jpg", id:"image_02_LG"},
		{src:"image_03.jpg", id:"image_03"},
		{src:"image_03_LG.jpg", id:"image_03_LG"},
		{src:"Printer.jpg", id:"Printer"},
		{src:"printer_light.png", id:"printer_light"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['A4BDA2797E5D4A2296AB1960FDA0E060'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;