(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Epson_Logo = function() {
	this.initialize(img.Epson_Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,51);


(lib.projector_image = function() {
	this.initialize(img.projector_image);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,643,250);


(lib.shield_icon = function() {
	this.initialize(img.shield_icon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,108,126);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_Tolerant = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgvCHQgUgFgMgLQgKgLgFgQQgEgQgBgTIAAgKIA+AAIAAAJQAAASAKAKQAJALARAAQAQAAAJgIQAKgIAAgQQgBgNgHgHQgIgGgKgEIgvgSQgcgKgPgRQgPgSAAgdQAAgQAGgPQAFgPAMgLQANgLASgGQATgHAZAAQAwAAAWAUQAWAUABAlIAAALIg+AAQAAgVgHgKQgHgKgRAAQgMAAgJAIQgLAHABAOQAAAKAFAIQAHAIARAGIApAOQAhALANARQANARAAAfQABAVgIAQQgIAQgNAKQgNALgSAEQgTAFgVAAQgdAAgSgGg");
	this.shape.setTransform(408.4,-69.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgFCrQgMgDgHgIQgHgIgCgOQgDgNAAgVIAAiZIgjAAIAAgvIAjAAIAAhNIBEAAIAABNIAoAAIAAAvIgoAAIAACRQAAAQAFAHQAFAGAPAAIAIAAIAHgBIAAAwIgWABIgXABQgUAAgMgDg");
	this.shape_1.setTransform(390.25,-73.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AAhCKIAAi4QAAgWgHgIQgHgIgPAAQgkAAAAAsIAACyIhFAAIAAkMIBCAAIAAAgIABAAQALgVARgJQARgJAXAAQAgAAASASQASASAAAoIAADHg");
	this.shape_2.setTransform(370.5,-69.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("Ag4CAQgVgMgKgVQgKgUgDgaIgCgyQAAgbAEgZQAEgZALgTQALgUAVgLQAVgMAiAAQAeAAATAKQAUAKALARQALASAEAZQAEAaAAAfIAAAOIiIAAIAAAWIACAXIAGAUQAEAJAGAFQAHAFAIAAQASAAAIgMQAIgNADgZIA+AAQgCAvgXAYQgXAZgyAAQgkAAgVgNgAgOhYQgHAFgEAIIgGARIgCATIAAAKIBGAAIgCgbQgCgMgDgIQgEgIgHgFQgHgEgKAAQgKAAgGAFg");
	this.shape_3.setTransform(346.675,-69.625);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("ABiCKIAAi7QAAgRgHgJQgGgJgOAAQgRAAgKALQgJALAAAYIAACwIhFAAIAAi7QAAgRgGgJQgGgJgPAAQgQAAgKALQgJALgBAYIAACwIhEAAIAAkMIBCAAIAAAbIAAAAQAOgSAPgIQARgIAXAAQAXAAAQALQAQALAFAVIACAAQAHgWASgKQASgLAYAAQAjAAARAVQAQAVAAAmIAADDg");
	this.shape_4.setTransform(316.4,-69.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AAhCKIAAi4QAAgWgHgIQgHgIgPAAQgkAAAAAsIAACyIhFAAIAAkMIBCAAIAAAgIABAAQALgVASgJQAQgJAWAAQAiAAARASQASASAAAoIAADHg");
	this.shape_5.setTransform(285.2,-69.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgzCFQgUgIgMgSQgMgSgFgbQgFgaAAgjQAAgiAGgaQAFgbANgRQAMgSAUgKQAVgJAcAAQAfAAAVAIQAUAJAMASQAMASAFAbQAFAaAAAjQAAAigGAbQgFAagNASQgMASgVAIQgTAJgeAAIgDAAQgcAAgUgIgAgThWQgHAHgEANQgEAMgBASIgBAlIABAmQABARAEANQAEAMAHAHQAIAHALAAQAVAAAIgWQAIgWAAgyQAAgygIgWQgIgWgVAAQgLAAgIAHg");
	this.shape_6.setTransform(260.95,-69.6249);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AhGCKIAAkMIBCAAIAAAkIABAAQAKgUAPgLQAPgMAVAAIAGABIAHAAIAABCIgLAAIgLgBIgSACQgJADgHAGQgIAFgEAKQgEAJAAANIAAChg");
	this.shape_7.setTransform(241.925,-69.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AghC1IAAkMIBDAAIAAEMgAghh5IAAg6IBDAAIAAA6g");
	this.shape_8.setTransform(226.8,-74.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgmCHIhGkMIBIAAIAmC/IABAAIAli/IBEAAIhDEMg");
	this.shape_9.setTransform(209.95,-69.55);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AAhCKIAAi4QAAgWgHgIQgHgIgQAAQgjAAAAAsIAACyIhFAAIAAkMIBCAAIAAAgIABAAQALgVARgJQARgJAXAAQAgAAASASQASASAAAoIAADHg");
	this.shape_10.setTransform(186.6,-69.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("Ag4CAQgVgMgKgVQgKgUgDgaIgCgyQAAgbAEgZQAEgZALgTQALgUAVgLQAVgMAiAAQAeAAATAKQAUAKALARQALASAEAZQAEAaAAAfIAAAOIiIAAIAAAWIACAXIAGAUQAEAJAGAFQAHAFAIAAQASAAAIgMQAIgNADgZIA+AAQgCAvgXAYQgXAZgyAAQgkAAgVgNgAgOhYQgHAFgEAIIgGARIgCATIAAAKIBGAAIgCgbQgCgMgDgIQgEgIgHgFQgHgEgKAAQgKAAgGAFg");
	this.shape_11.setTransform(162.775,-69.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhXCyIAAg0IASACQATAAAIgKQAJgKABgRIhLkMIBIAAIAmC5IABAAIAji5IBFAAIhAD6QgKAigIAUQgIAVgLAMQgLALgPADQgQAEgYAAg");
	this.shape_12.setTransform(501.7,-121.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AhGCKIAAkMIBCAAIAAAkIABAAQAKgTAPgMQAPgMAVAAIAGAAIAHABIAABCIgLAAIgLgBIgSADQgJACgHAGQgIAGgEAIQgEAKAAAOIAACgg");
	this.shape_13.setTransform(483.575,-126);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgzCFQgUgIgMgSQgMgSgFgbQgFgaAAgjQAAgiAGgaQAFgbANgRQAMgSAUgKQAVgJAcAAQAfAAAVAIQAUAJAMASQAMASAFAbQAFAaAAAjQAAAigGAbQgFAagNASQgMASgVAIQgUAJgdAAIgDAAQgcAAgUgIgAgThWQgHAHgEANQgEAMgBASIgBAlIABAmQABARAEANQAEAMAHAHQAIAHALAAQAVAAAIgWQAIgWAAgyQAAgygIgWQgIgWgVAAQgLAAgIAHg");
	this.shape_14.setTransform(462.45,-125.7249);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgECrQgOgDgGgIQgHgIgDgOQgCgNAAgVIAAiZIgjAAIAAgvIAjAAIAAhNIBEAAIAABNIAoAAIAAAvIgoAAIAACRQAAAQAFAHQAEAGAPAAIAIAAIAIgBIAAAwIgWABIgXABQgUAAgLgDg");
	this.shape_15.setTransform(443.4,-129.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgsCHQgTgHgNgQQgNgQgGgbQgHgcAAgoQAAgpAIgbQAIgbAPgRQAOgQAUgGQAUgHAXAAQAwAAAZAcQAYAcAAAwIhCAAIgBgTIgFgRQgDgIgGgFQgGgFgKAAQgMAAgIAGQgIAGgEALQgEALgBARIgCAoIACArQABASAEALQAEAMAIAFQAHAFAKAAQASAAAIgPQAIgPAAghIBCAAQAAA1gYAcQgYAcg3AAQgZAAgTgGg");
	this.shape_16.setTransform(424.575,-125.725);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AhFCHQgMgHgIgLQgHgLgEgNQgDgOAAgOQgBgTAEgOQAFgNAIgKQAIgJANgGQAMgHATgFIAmgKQAPgEAGgHQAGgHAAgOQAAgPgHgJQgIgJgQAAQgQAAgIAKQgIAJAAAQIAAAIIg+AAIAAgHQAAgXAIgQQAHgQANgKQAMgJASgEQARgFATAAQAfAAASAGQATAGALALQALALADAPQAEAQAAASIAACMIACAeIAGAWIhBAAIgGgNIgDgPIgBAAQgMAVgQAHQgOAGgaAAQgRAAgNgGgAAPAKIgOAEQgVAFgJAKQgIALgBASQABAPAFALQAGALAOAAIAOgCQAHgCAHgFQAGgFAEgIQAEgIAAgLIAAg1g");
	this.shape_17.setTransform(401.05,-125.725);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgkC2IAAjdIgjAAIAAgvIAjAAIAAgeQAAgTAFgMQAFgMAJgIQAKgIAMgDQAOgDAQAAIAlACIAAAwIgHAAIgHAAQgOAAgGAFQgGAFAAALIAAAYIAoAAIAAAvIgoAAIAADdg");
	this.shape_18.setTransform(382.15,-130.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgkC2IAAjdIgjAAIAAgvIAjAAIAAgeQAAgTAFgMQAFgMAJgIQAKgIAMgDQAOgDAQAAIAlACIAAAwIgHAAIgGAAQgPAAgGAFQgGAFAAALIAAAYIAoAAIAAAvIgoAAIAADdg");
	this.shape_19.setTransform(355.85,-130.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgyCFQgVgIgMgSQgMgSgFgbQgFgaAAgjQAAgiAFgaQAGgbAMgRQANgSAUgKQAUgJAdAAQAfAAAUAIQAVAJAMASQAMASAFAbQAFAaAAAjQAAAigFAbQgGAagMASQgNASgVAIQgTAJgeAAIgDAAQgcAAgTgIgAgThWQgIAHgDANQgEAMgBASIgBAlIABAmQABARAEANQADAMAIAHQAHAHAMAAQAVAAAIgWQAIgWAAgyQAAgygIgWQgIgWgVAAQgMAAgHAHg");
	this.shape_20.setTransform(336.6,-125.7249);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgECrQgOgDgGgIQgHgIgDgOQgCgNAAgVIAAiZIgjAAIAAgvIAjAAIAAhNIBEAAIAABNIAoAAIAAAvIgoAAIAACRQAAAQAFAHQAEAGAQAAIAHAAIAIgBIAAAwIgWABIgXABQgUAAgLgDg");
	this.shape_21.setTransform(305.8,-129.425);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AAhCKIAAi5QAAgUgHgJQgHgIgQAAQgjAAAAAsIAACyIhFAAIAAkMIBCAAIAAAfIABAAQALgUARgJQARgJAXAAQAgAAASASQASASAAApIAADGg");
	this.shape_22.setTransform(286.05,-126);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AhFCHQgNgHgHgLQgHgLgEgNQgDgOAAgOQAAgTAEgOQADgNAJgKQAIgJANgGQANgHARgFIAmgKQAQgEAGgHQAGgHAAgOQAAgPgHgJQgHgJgRAAQgQAAgIAKQgIAJAAAQIAAAIIg+AAIAAgHQAAgXAHgQQAIgQANgKQAMgJASgEQARgFATAAQAeAAAUAGQATAGAKALQALALADAPQAEAQAAASIAACMIACAeIAHAWIhDAAIgEgNIgEgPIgBAAQgMAVgQAHQgOAGgZAAQgTAAgMgGgAAPAKIgPAEQgTAFgJAKQgKALABASQgBAPAHALQAGALAOAAIANgCQAHgCAHgFQAGgFAEgIQAEgIAAgLIAAg1g");
	this.shape_23.setTransform(261.6,-125.725);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AhGCKIAAkMIBCAAIAAAkIABAAQAKgTAPgMQAPgMAVAAIAGAAIAHABIAABCIgLAAIgLgBIgSADQgJACgHAGQgIAGgEAIQgEAKAAAOIAACgg");
	this.shape_24.setTransform(242.725,-126);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("Ag4CAQgVgMgKgVQgKgUgDgaIgCgyQAAgbAEgZQAEgZALgTQALgUAVgLQAVgMAiAAQAeAAATAKQAUAKALARQALASAEAZQAEAaAAAfIAAAOIiIAAIAAAWIACAXIAGAUQAEAJAGAFQAHAFAIAAQASAAAIgMQAIgNADgZIA+AAQgCAvgXAYQgXAZgyAAQgkAAgVgNgAgOhYQgHAFgEAIIgGARIgCATIAAAKIBGAAIgCgbQgCgMgDgIQgEgIgHgFQgHgEgKAAQgKAAgGAFg");
	this.shape_25.setTransform(222.025,-125.725);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgiCyIAAljIBFAAIAAFjg");
	this.shape_26.setTransform(204.7,-130.05);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgyCFQgVgIgMgSQgMgSgFgbQgFgaAAgjQAAgiAGgaQAFgbANgRQAMgSAUgKQAVgJAcAAQAfAAAUAIQAVAJAMASQAMASAFAbQAFAaAAAjQAAAigFAbQgGAagMASQgNASgVAIQgUAJgdAAIgDAAQgcAAgTgIgAgThWQgIAHgDANQgEAMgBASIgBAlIABAmQABARAEANQADAMAIAHQAIAHALAAQAVAAAIgWQAIgWAAgyQAAgygIgWQgIgWgVAAQgLAAgIAHg");
	this.shape_27.setTransform(186.95,-125.7249);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AgjCyIAAkpIhOAAIAAg6IDjAAIAAA6IhOAAIAAEpg");
	this.shape_28.setTransform(163.2,-130.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_Tolerant, new cjs.Rectangle(149.2,-162.2,904.0999999999999,119.19999999999999), null);


(lib.txt_toDyeFor = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgOARIAAghIAdAAIAAAhg");
	this.shape.setTransform(17.05,-144.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgeA9IAAh2IAdAAIAAAQIAAAAQAEgIAHgFQAGgGAKAAIACAAIADABIAAAdIgFgBIgEAAIgIABIgIAEQgDADgCAEQgBAEAAAGIAABGg");
	this.shape_1.setTransform(11.725,-148.575);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgWA7QgJgEgFgIQgFgIgCgMQgDgMAAgPQAAgOADgMQACgLAGgIQAFgIAJgEQAJgEAMAAQAOAAAJAEQAJADAFAJQAFAHACAMQADALAAAPQAAAPgDAMQgCAMgGAHQgFAJgJADQgJAEgNAAQgNAAgJgDgAgIglQgDADgCAGIgCAMIAAAQIAAARIACANQACAGADADQAEADAEAAQAJAAAEgKQADgKAAgWQAAgVgDgJQgEgLgJAAQgEAAgEAEg");
	this.shape_2.setTransform(2.825,-148.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgPBQIAAhhIgPAAIAAgVIAPAAIAAgNQAAgIACgFQACgGAEgDQAEgEAFgBIANgBIARAAIAAAWIgEAAIgCAAQgHAAgDACQgCADAAAFIAAAJIASAAIAAAVIgSAAIAABhg");
	this.shape_3.setTransform(-5.15,-150.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgYA4QgJgFgFgJQgEgJgBgMIgBgVQAAgLACgMQABgKAFgJQAFgJAJgFQAKgFAOAAQANAAAJAFQAIADAFAIQAFAJACAKQABALAAAOIAAAGIg7AAIAAAKIABAKIADAJQABADADACQADADADAAQAIAAAEgGQADgFABgMIAcAAQgBAVgKALQgKALgWAAQgQAAgJgGgAgGgmQgDACgBADIgDAIIgBAIIAAAFIAeAAIgBgMIgCgJQgBgDgDgCQgDgCgFgBQgEAAgDADg");
	this.shape_4.setTransform(-17.775,-148.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgmBOIAAgWIAIAAQAJAAADgEQAEgEABgIIgih1IAgAAIARBRIAAAAIAPhRIAfAAIgdBtIgHAYQgEAJgFAFQgEAFgHACQgHABgKAAg");
	this.shape_5.setTransform(-27.225,-146.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AglBBQgIgOAAghQAAggAIgPQAJgOATAAQAIAAAFADQAGAEAFAHIABAAIAAgyIAeAAIAACcIgdAAIAAgMIAAAAQgFAIgHADQgFAEgJAAQgTAAgJgPgAgMgKQgDAKAAASQAAATADAKQADAKAJAAQAKAAADgKQADgKAAgTQAAgSgDgKQgDgKgKAAQgJAAgDAKg");
	this.shape_6.setTransform(-37.225,-150.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgWA7QgJgEgFgIQgFgIgCgMQgDgMAAgPQAAgOADgMQACgLAGgIQAFgIAJgEQAJgEAMAAQAOAAAJAEQAJADAFAJQAFAHACAMQADALAAAPQAAAPgDAMQgCAMgGAHQgFAJgJADQgJAEgNAAQgNAAgJgDgAgIglQgDADgCAGIgCAMIAAAQIAAARIACANQACAGADADQAEADAEAAQAJAAAEgKQADgKAAgWQAAgVgDgJQgEgLgJAAQgEAAgEAEg");
	this.shape_7.setTransform(-52.125,-148.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AAMBMIgOgBQgFgBgDgEQgDgDgBgGIgBgPIAAhDIgQAAIAAgVIAQAAIAAghIAdAAIAAAhIARAAIAAAVIgRAAIAAA/QAAAHACADQACADAHAAIAEAAIACAAIAAAVIgJAAg");
	this.shape_8.setTransform(-60.1,-150.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgUA8QgJgDgFgFQgFgFgCgGQgCgIAAgIIAAgEIAcAAIAAAEQAAAHAEAFQAEAFAHAAQAGAAAFgEQAEgDAAgHQAAgGgDgDQgEgDgEgBIgUgIQgNgFgGgHQgHgIAAgNQAAgGADgHQACgGAFgGQAGgEAIgDQAIgDALAAQAUAAAKAJQAKAIAAARIAAAEIgbAAQAAgIgDgFQgDgFgHAAQgFAAgEAEQgFADAAAHQAAAEADAEQADADAHACIASAGQAOAFAGAHQAGAIAAAOQAAAJgDAHQgEAHgGAEQgFAFgIACQgIACgKAAQgMAAgIgCg");
	this.shape_9.setTransform(-72.525,-148.45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgMAjIAAhFIAaAAIAABFg");
	this.shape_10.setTransform(-79.75,-154.675);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AAMBMIgOgBQgFgBgDgEQgDgDgBgGIgBgPIAAhDIgQAAIAAgVIAQAAIAAghIAdAAIAAAhIARAAIAAAVIgRAAIAAA/QAAAHACADQACADAHAAIAEAAIACAAIAAAVIgJAAg");
	this.shape_11.setTransform(-85.3,-150.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgPBPIAAidIAfAAIAACdg");
	this.shape_12.setTransform(-90.9,-150.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_toDyeFor, new cjs.Rectangle(-221.8,-165.6,369,30), null);


(lib.txt_sureColor_f10070_endFrame = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AHMA1QgGgCgEgGQgEgHgCgJQgCgKABgOIABgVQAAgLADgHQAEgIAGgFQAIgFAMAAQAJAAAGADQAHACADAHQAFAHABAJQACAKAAAOIgBAVQgBALgDAHQgDAIgHAFQgHAEgLAAQgKAAgHgDgAHWgkQgCACgBAEQgCAEAAAIIAAAsQAAAGACAEQABAEACABQADACAEAAQADAAACgCQACgCACgEIACgMIAAgsQgBgGgBgEQgCgEgCgBQgCgBgDAAQgEAAgDABgAE/A1QgGgCgEgGQgEgHgCgJIgBgYIAAgVQABgLAEgHQADgIAHgFQAHgFAMAAQAKAAAGADQAHACAEAHQADAHACAJIABAYIAAAVQgBALgEAHQgDAIgGAFQgIAEgLAAQgKAAgHgDgAFKgkQgDACgBAEIgBAMIAAAsIABAKQABAEADABQACACAEAAQADAAACgCQACgCACgEIACgMIAAgsIgCgKQgCgEgCgBQgCgBgDAAQgEAAgCABgAD5A1QgGgCgFgGQgDgHgBgJQgDgKAAgOIABgVQACgLADgHQACgIAHgFQAIgFALAAQAKAAAHADQAGACAEAHQAEAHACAJQABAKAAAOIgBAVQgBALgDAHQgDAIgHAFQgHAEgMAAQgKAAgGgDgAEDgkQgCACgBAEQgCAEAAAIIAAAsQAAAGACAEQABAEACABQADACADAAQAEAAACgCQACgCACgEQABgFAAgHIAAgsQAAgGgCgEQgBgEgCgBQgCgBgEAAQgDAAgDABgAgrA1QgHgCgDgFQgEgGgBgIQgCgIAAgKQAAgLACgHQABgIAFgFQADgGAGgCQAHgDAIAAQAJAAAHACQAGADAEAFQACAGACAIIABASIgBASQgCAIgDAFQgEAGgGACQgGADgJAAQgJAAgGgDgAgigMQgCACgBAEIgCAIIAAAXIACAJQABAEACACQACACAEAAQAHAAACgGQADgHAAgPQAAgPgDgGQgCgHgHAAQgEAAgCACgAiUA1QgGgCgEgFQgDgGgCgIIgBgSIABgSQACgIAEgFQAEgGAFgCQAHgDAJAAQAJAAAHACQAGADADAFQAEAGACAIIABASIgBASQgCAIgEAFQgEAGgGACQgGADgJAAQgKAAgGgDgAiKgMQgDACAAAEQgCAEAAAEIAAAXQAAAFACAEQAAAEADACQACACAEAAQAGAAADgGQACgHAAgPQAAgPgCgGQgDgHgGAAQgEAAgCACgAjhA0QgHgEgFgHQgDgIgBgKIgBgXIABgWQABgKADgHQAFgIAHgEQAIgEAMAAQALAAAIAEQAGADAEAGQADAGAAAHIABAMIgWAAQAAgLgCgFQgDgGgHAAQgFAAgCACQgDACgCAFIgCANIAAATIAAAUQABAHACAEQACAEADACIAGABIAFAAIAFgFQABgCABgGQACgFgBgJIAWAAIgBARQgBAHgEAGQgEAGgGAEQgIADgKAAQgMAAgIgEgAkqA0QgFgEgEgGQgDgGgBgIIAAgPIABgPQABgIAEgFQADgHAHgDQAFgDAMAAQAIAAAGADQAHADACAFQADAFADAIIAAAQIAAAFIgpAAIAAANIADAHQAAAAAAABQAAABAAAAQABAAAAABQAAAAABABIAFABQAFAAADgEQACgDACgIIATAAQgCAOgGAHQgHAIgQAAQgKAAgIgEgAkdgNQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABIgDAFIAAAIIAWAAIgBgHIgCgGIgDgEQgCgBgEAAQgCAAgDABgAmoAzQgEgGAAgMIAAg8IAUAAIAAA4QAAAGACADQACACAEAAQALAAAAgNIAAg2IAWAAIAABSIgUAAIAAgKIgBAAQgDAGgGACQgFADgGAAQgKAAgGgFgAn1AwQgIgIAAgPIAAgFIAWAAIAAAKQABADACADQABACADABIAHABQAFAAAEgDQAEgDAAgHIgBgGIgDgFIgGgEIgJgDIgMgFIgJgGQgEgEgCgGIgBgLQAAgQAIgIQAJgIARAAQAGAAAGACQAHABAEAEQAFADACAGQACAGABAHIAAADIgVAAQAAgHgDgFQgCgEgHAAQgEAAgCABQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAAAABIgCAEIAAAEQAAAFACAEQACADAHADIARAIQAGACAEACIAGAHQACADACAEIAAAJQAAARgKAIQgKAIgSAAQgSAAgIgIgAGAA3IAEgVIAGgWIAKgVIAOgWIgtAAIAAgTIBCAAIAAARQgHAKgFAKQgFALgEALQgEALgDAMIgEAXgAC6A3IAAhLIgVAAIAAgPIACAAQALAAAFgDQAHgFACgJIAQAAIAABrgABjA3IAAhsIA8AAIAAASIgnAAIAAAaIAlAAIAAAQIglAAIAAAwgAAMA3IAAhSIAUAAIAAAMQADgGAFgEQAFgDAGAAIACAAIACAAIAAAUIgHgBIgFABIgFADQgDABgBAEIgBAFIAAAygAhbA3IAAhsIAWAAIAABsgAlkA3IAAhSIAUAAIAAAMIAAAAIAIgKQAFgDAGAAIACAAIACAAIAAAUIgGgBIgGABQgDABgBACQgDABgCAEIgBAFIAAAyg");
	this.shape.setTransform(29.3,-200.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("ApYBFIAAgQIAFABQAFAAADgEQACgCABgGIgXhRIAWAAIAMA4IABAAIAKg4IAWAAIgUBMIgFARIgHAKQgDADgFABIgMABgAJJAoQgHgDgCgHQgEgGgBgIIAAgPIAAgQQACgHAEgGQADgGAGgEQAHgDALAAQAIABAGACQAGADADAFQAFAGAAAIIABAQIAAAEIgqAAIABAOIACAGIADAFIAFABQAGAAACgEQACgDACgJIASAAQAAAPgIAIQgGAHgQAAQgLAAgGgEgAJVgZQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIgCAGIgBAJIAXAAIgBgJIgCgGQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBgBAAQgBgCgDAAQgEAAgCACgACFApQgGgBgEgHQgDgEgCgJIgBgSIABgSQACgJAEgFQAEgFAGgDQAGgCAJgBQAJAAAHADQAFACAFAGQADAGACAHQABAJABAKQgBAKgBAIQgCAIgEAFQgEAGgFACQgHADgJAAQgJAAgHgDgACPgYQgDACgBADQgBAEAAAGIAAAVQAAAGABAEQABAEADACQACACAEAAQAHAAACgHQACgGAAgPQAAgQgCgGQgCgHgHAAQgEAAgCADgAgUAqQgEgBgBgEQgDgEgBgEIgCgIQABgGABgEQABgEAEgDQACgEAEAAIAJgEIALgCQAFgCACgCQACgCAAgEQgBgFgCgDQgCgDgFAAQgEAAgDADQgCADAAAFIAAACIgTAAIAAgCQAAgGADgFQABgGAEgCQAEgDAGgCIAKgBQAKABAFABQAFACAEADQADAEABAEQACAFgBAFIABA0IACAGIgUAAIgCgEIAAgFIgBAAQgEAIgFABQgDACgJAAQgEAAgFgCgAABAFQgFACgDADQgCADAAAGQAAAEABAEQACADAEAAIAEgBIAEgBIADgFIACgFIAAgQgAj+ApQgEgBgEgHIAAAJIgVAAIAAhsIAWAAIAAAiIABAAQADgEADgDQAFgBAGgBQANAAAGAKQAFAKAAAXQAAAXgFAKQgGAJgNAAQgHAAgEgDgAkDgSQgCAHAAANQAAAMACAIQACAGAHABQAHgBACgGQABgIAAgMQAAgNgBgHQgCgHgHABQgHgBgCAHgAlfAmQgFgFgBgMIAAg8IAVAAIAAA4QAAAHADACQACACAFABQALgBAAgOIAAg1IAVAAIAABRIgUAAIAAgJIgBAAQgDAFgFADQgFADgIAAQgKAAgFgGgAmtAkQgIgIAAgQIAAgEIAXAAIAAAKQAAAEACABIAEAFIAIABQAFgBADgDQAFgDAAgHQAAgEgCgCIgDgFIgFgEIgKgDIgNgEIgIgIQgEgEgBgFQgCgFAAgGQAAgRAIgIQAKgIAPAAQAIAAAHACQAFACAFADQAEAEAEAFQABAGAAAHIAAAEIgVAAQAAgIgDgFQgCgEgHAAQgEAAgCABQgBABAAAAQgBAAAAABQgBAAAAABQAAAAgBAAIgBAEIgBAFQAAAFACADQACAEAHADIASAHIAJAGIAHAGIADAHIABAJQAAASgKAHQgKAIgSAAQgSAAgJgIgAoNAoQgGgDgDgHQgDgGgBgIIAAgPIABgQQABgHADgGQAEgGAGgEQAHgDAKAAQAKABAFACQAGADADAFQAEAGABAIQABAIABAIIAAAEIgqAAIAAAOIACAGQABADADACQABABADAAQAFAAADgEQACgDACgJIASAAQAAAPgHAIQgHAHgQAAQgLAAgHgEgAn/gZQgBAAgBABQAAAAgBAAQAAABAAAAQAAABgBAAIgCAGIAAAJIAWAAIgCgJQAAgDgBgDQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgCgCgDAAQgEAAgBACgAIhAqQgEgBgCgDIgDgGIAAgKIAAguIgLAAIAAgPIALAAIAAgXIAVAAIAAAXIAMAAIAAAPIgMAAIAAArQAAAEACADQABACAEAAIAFAAIAAAOIgOABIgKgBgAA4AqQgDgBgCgDQgCgCgBgEQgBgEAAgGIAAguIgKAAIAAgPIAKAAIAAgXIAVAAIAAAXIAMAAIAAAPIgMAAIAAArIABAHQACACAFAAIAEAAIAAAOIgOABIgKgBgAKCAqIAAhRIAUAAIAAAMIAAAAQAEgHAEgEQAFgDAGAAIAEAAIAAAUIgMABQgDABgCACQgCABgBADQgDADAAAEIAAAwgAHyAqIAAg4QABgGgDgDQgCgBgFAAQgLAAAAANIAAA1IgUAAIAAhRIAUAAIAAAJQADgFAFgDQAGgCAGgBQALAAAFAGQAGAFAAANIAAA7gAGoAqIAAhRIAUAAIAABRgAF3AqIAAhRIAVAAIAAAMQACgHAGgEQAEgDAHAAIADAAIAAAUIgMABIgFADQgDABgBADIgBAHIAAAwgAErAqIAAhsIAmAAQAIAAAHADQAFADAEAEQADAFACAGIACAMQAAAIgDAHQgDAGgEAFQgFADgHACQgGACgHAAIgNAAIAAAqgAFAgQIAKAAQAHgBAEgDQAEgEAAgJQAAgIgDgEQgEgEgIgBIgKAAgADnAqIAAg4QAAgGgCgDQgCgBgFAAQgLAAAAANIAAA1IgUAAIAAhRIATAAIAAAJIABAAQADgFAFgDQAGgCAGgBQAKAAAGAGQAFAFABANIAAA7gABWAqIAAhRIAVAAIAABRgAg7AqIAAg4QAAgGgCgCQgDgDgEABQgFAAgEACQgCADAAAIIAAA1IgVAAIAAg4QAAgGgCgCQgCgDgEABQgFAAgDACQgEADAAAIIAAA1IgVAAIAAhRIAVAAIAAAIQAEgFAFgDQAFgBAHgBQAHAAAFADQAGAEABAHQACgHAGgEQAFgDAIAAQAKAAAGAHQAEAGAAAMIAAA6gAiuAqIAAhRIAVAAIAABRgAjRAqIAAhsIAXAAIAABsgAqsAqIAAhsIAkAAQAMAAAHAEQAHAEAEAHQADAGACALIABAVQAAAOgCAKQgBALgEAHQgFAGgHAEQgHADgMAAgAqWAaIAJAAQAHAAADgCQADgCADgEQACgFAAgIIAAghQAAgIgCgEQgBgFgFgCQgDgCgHgBIgJAAgAGogxIAAgSIAUAAIAAASgABWgxIAAgSIAVAAIAAASgAiugxIAAgSIAVAAIAAASg");
	this.shape_1.setTransform(12.8,-181.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070_endFrame, new cjs.Rectangle(-55.7,-205.7,137,31), null);


(lib.txt_sureColor_f10070 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ApBCSIAAgPIAFABQAFAAADgEQADgDAAgEIgXhPIAVAAIANA2IAAAAIAKg2IAUAAIgTBJIgEARQgDAFgDAEQgEAEgFAAIgLABgAIzB3QgHgEgCgGQgEgGAAgHIgBgQIABgPQABgIAEgFQADgFAHgEQAFgDALAAQAIAAAGADQAGACADAGQADAFACAHIABARIAAAEIgpAAIABANIACAHIADADQAAABABAAQABAAAAABQABAAAAAAQABAAAAAAQAGAAACgDQADgEABgIIASAAQgBAOgGAHQgIAIgOAAQgLgBgGgDgAI/A3IgDAEIgCAEIgBAJIAWAAIgBgIQAAgDgCgDIgDgEIgFgBQgDABgCABgACAB4QgFgCgEgFQgDgGgCgIQgBgHAAgLQAAgKABgIQACgHADgGQAEgFAGgCQAGgDAJAAQAJAAAGACQAFADAFAFQADAGABAHQACAIAAAKQAAALgCAHQgBAIgEAFQgEAGgFACQgHACgIABQgJgBgHgCgACKA3QgCACgCAEIgBAJIAAAWIABAJQACAEACACQACACAEAAQAGAAACgGQACgHAAgPQAAgOgCgHQgCgGgGgBQgEAAgCACgAgSB5QgEgCgCgEIgDgHIgBgIIABgKQABgEACgCIAGgFIAJgDIALgEQAFAAABgDQACgCAAgEQAAgFgCgCQgCgCgGgBQgDAAgDADQgCADAAAEIAAADIgSAAIAAgCQAAgHACgFQACgEAEgDQAEgDAFgBQAFgBAEAAQAKAAAGACQAFABAEADQACAEABAEIABAKIABAyIACAHIgUAAIgBgEIgBgEQgEAGgFACQgDACgHAAQgFAAgEgCgAAGBUIgFABQgFABgDADQgCADAAAGQAAAEABAEQACADAFAAIADgBIAEgCIADgDIABgGIAAgQgAj0B5QgEgDgEgFIAAAAIAAAIIgTAAIAAhpIAUAAIAAAhIAAAAQAEgEAEgDQADgCAGAAQANAAAFAKQAGAJABAWQgBAXgGAJQgFAJgNABQgGAAgEgCgAj5A9QgCAIAAAMQAAANACAHQACAGAGAAQAHAAACgGQACgHAAgNQAAgMgCgIQgCgFgHgBQgGABgCAFgAlSB1QgEgFAAgMIAAg6IAUAAIAAA2QAAAHACACQACADAEgBQALAAAAgNIAAg0IAVAAIAABPIgUAAIAAgJIgBAAQgCAGgGACQgFACgGABQgKAAgGgGgAmcBzQgIgIAAgPIAAgEIAWAAIAAAJIACAGQACACACABQADACAEgBQAFAAAEgDQAEgDAAgHIgBgGIgDgFIgGgDIgJgDIgMgGQgFgCgEgFQgDgDgBgFQgCgFgBgHQAAgPAJgHQAJgIAPAAQAHAAAGACQAGABAFADQAEADACAGQADAFAAAIIAAADIgVAAQAAgIgCgDQgDgEgGgBIgGABIgEADIgBAEIgBAFQgBAEADAEQACADAHADIAQAHIAKAGIAGAFQACAEABAEIABAIQAAARgKAIQgJAIgSAAQgSgBgHgHgAn4B3QgHgEgCgGQgDgGgBgHIgBgQIACgPQABgIADgFQAEgFAFgEQAHgDAKAAQAJAAAGADQAFACADAGQADAFABAHIABARIAAAEIgnAAIAAANIACAHIADADQACACADAAQAFAAADgDQACgEAAgIIASAAQAAAOgHAHQgHAIgOAAQgLgBgGgDgAnsA3IgDAEIgCAEIAAAJIAUAAIAAgIIgBgGIgEgEIgEgBQgEABgCABgAJqB5IAAhPIAUAAIAAAKQADgFAEgEQAFgDAGAAIABAAIACAAIAAATIgLABIgFACQgCACgCADQgBADAAADIAAAwgAIWB5IgJAAQgEgCgBgCIgEgGIAAgKIAAguIgLAAIAAgNIALAAIAAgXIAUAAIAAAXIAMAAIAAANIgMAAIAAArQAAAFACACQABACAEAAIAFgBIAAAPgAHgB5IAAg3QAAgGgCgCQgCgDgFAAQgKAAgBAOIAAA0IgUAAIAAhPIATAAIAAAJIABAAQADgGAFgCQAFgDAHAAQAKgBAFAGQAGAFAAAMIAAA7gAGYB5IAAhPIAVAAIAABPgAFpB5IAAhPIATAAIAAAKIABAAQADgFAEgEQAFgDAGAAIACAAIACAAIAAATIgMABIgFACIgDAFIgCAGIAAAwgAEgB5IAAhpIAlAAQAIAAAGACQAFADAEAEQADAFABAGQACAFAAAGQAAAJgDAFQgCAGgFAEQgEAEgGACQgHACgGAAIgMAAIAAAqgAE1A/IAJAAQAGAAAFgDQADgFABgIQgBgIgDgEQgDgEgIAAIgJAAgADfB5IAAg3QAAgGgCgCQgCgDgEAAQgLAAAAAOIAAA0IgVAAIAAhPIAUAAIAAAJIAAAAQADgGAGgCQAFgDAGAAQAKgBAFAGQAFAFAAAMIAAA7gABTB5IAAhPIAUAAIAABPgABAB5IgJAAQgEgCgBgCIgEgGIAAgKIAAguIgLAAIAAgNIALAAIAAgXIAUAAIAAAXIAMAAIAAANIgMAAIAAArQAAAFACACQABACAEAAIAFgBIAAAPgAg4B5IAAg4QAAgEgDgDQgCgDgEAAQgFAAgDAEQgCADAAAHIAAA0IgVAAIAAg4QAAgEgCgDQgCgDgEAAQgEAAgDAEQgEADAAAHIAAA0IgUAAIAAhPIAUAAIAAAIQAEgFAEgDQAFgCAHAAQAHAAAFADQAFADABAGQADgGAFgDQAFgDAIAAQAKgBAEAHQAFAGAAALIAAA6gAinB5IAAhPIAVAAIAABPgAjIB5IAAhpIAUAAIAABpgAqSB5IAAhpIAjAAQALAAAHADQAHAEADAGQAEAIABAJIACAVQAAANgCALQgBALgFAGQgEAGgGADQgIAEgKAAgAp9BpIAKAAQAGAAADgBQADgCACgFQADgEAAgIIAAghQAAgHgCgEQgCgFgEgCQgDgDgHAAIgJAAgAGYAgIAAgRIAVAAIAAARgABTAgIAAgRIAUAAIAAARgAinAgIAAgRIAVAAIAAARgAJAgoQgHgDgDgFQgEgHgCgJQgBgKgBgOIABgUQABgKAEgIQADgHAGgFQAHgFALAAQAKAAAGADQAGACAEAGQAEAHABAJQABAJAAAPIgBAUQAAALgDAHQgDAIgHAEQgGAEgMABQgJAAgGgDgAJJh/IgDAGIgCAKIAAAsIACAKQABAEACABIAGABQADAAACgCQADgCACgDIABgLIAAgsIgCgKQgBgDgDgBQgCgCgDAAQgEAAgCACgAG4goQgGgDgEgFQgDgHgCgJQgBgKgBgOIABgUQABgKADgIQADgHAHgFQAGgFAMAAQAJAAAGADQAGACAFAGQADAHABAJQACAJAAAPIgBAUQgBALgCAHQgDAIgHAEQgHAEgLABQgJAAgHgDgAHCh/QgCABgBAFIgCAKIAAAsIACAKQABAEACABIAGABQADAAACgCIAEgFIACgLIAAgsIgCgKQgCgDgCgBQgCgCgDAAQgEAAgCACgAF0goQgGgDgEgFQgEgHgBgJQgBgKAAgOIABgUQAAgKADgIQADgHAHgFQAGgFAMAAQAJAAAHADQAGACAEAGQADAHACAJQABAJABAPIgBAUQgBALgDAHQgDAIgHAEQgGAEgMABQgJAAgHgDgAF/h/IgEAGIgCAKIAAAsQAAAGACAEQABAEADABIAFABQAEAAACgCQACgCABgDIACgLIAAgsIgCgKQgBgDgCgBQgCgCgEAAQgEAAgBACgAAdgoQgGgDgEgEQgDgGgBgIQgCgHAAgLQAAgJACgJQACgHADgFQAEgFAFgDQAHgDAIAAQAJAAAGACQAGADAEAGQADAEABAIQACAIAAAKQAAAKgCAIQgCAIgDAFQgDAFgGADQgHADgIAAQgJgBgGgCgAAmhoQgCACgBADIgBAJIAAAXIABAIQABAEACACQACACAEAAQAGAAADgGQABgHAAgPQAAgPgBgGQgDgHgGAAQgEABgCACgAhHgoQgFgDgEgEQgDgGgBgIQgCgHAAgLQAAgJACgJQABgHADgFQAEgFAGgDQAGgDAJAAQAIAAAHACQAFADAFAGQACAEACAIQACAIgBAKQABAKgCAIQgCAIgDAFQgEAFgGADQgGADgIAAQgJgBgHgCgAg9hoQgDACAAADIgBAJIAAAXIABAIQAAAEADACQACACAEAAQAGAAADgGQABgHAAgPQAAgPgBgGQgDgHgGAAQgEABgCACgAiQgqQgIgDgDgIQgEgGgBgLIgBgVIABgXQABgJAEgHQADgHAIgFQAGgDAMAAQAMAAAGADQAHADACAGQAEAGABAHIABALIgWAAQABgLgDgFQgDgFgHAAQgEAAgDACQgCACgBAFQgCAEgBAIIAAATIABATQAAAIACADQACAEACACQADACAEgBIAEgBQADgBACgCQABgEABgEIABgPIAWAAIgBARQgCAIgEAFQgDAGgHADQgGADgLABQgMAAgGgFgAjWgqQgHgDgCgGQgDgGgBgHIAAgQIABgOQABgIADgGQAEgFAFgEQAHgDAKAAQAIAAAGADQAGADADAFQADAFABAHIABARIAAAFIgnAAIAAAMIACAHIADADQAAABABAAQABAAAAABQABAAAAAAQABAAAAAAQAFAAADgEQADgDAAgIIASAAQAAAOgHAHQgHAHgOABQgLAAgGgFgAjKhpIgDAEIgCAFIAAAIIAUAAIgBgIQABgDgCgCQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBgBgEgBQgDABgCABgAlQgrQgFgFAAgMIAAg6IAUAAIAAA2QAAAGACADQACADAFgBQALAAgBgNIAAg0IAVAAIAABPIgUAAIAAgJQgDAFgFADQgGADgGAAQgJgBgGgFgAmaguQgIgHAAgOIAAgFIAWAAIAAAKIACAFQABACAEABQACACAEgBQAFABADgEQAFgDAAgGIgBgHIgEgEIgFgEIgJgDIgMgGIgJgGQgDgDgBgFQgCgGAAgGQgBgPAJgIQAJgHAPAAQAHgBAGACQAGACAEADQAFADACAGQACAFAAAHIAAADIgUAAQAAgHgDgEQgCgEgHAAIgFABIgEACQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgBAFQAAAFACADQADADAGADIARAHIAJAGIAHAGQACADABAEIAAAIQAAASgJAHQgKAHgRABQgSAAgHgJgAn2gqQgGgDgDgGQgDgGAAgHIAAgQIABgOQAAgIADgGQAEgFAGgEQAGgDAKAAQAJAAAGADQAGADADAFQADAFABAHIABARIAAAFIgoAAIAAAMIACAHIAEADQAAABABAAQAAAAABABQAAAAABAAQAAAAABAAQAFAAADgEQACgDABgIIASAAQAAAOgIAHQgGAHgPABQgKAAgHgFgAnphpIgEAEIgCAFIAAAIIAVAAIgBgIQAAgDgCgCQAAgBAAgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgCgBgEgBQgCABgCABgAH3gnIADgUQACgLAEgKIAKgVQAFgLAIgLIgrAAIAAgSIBAAAIAAAQQgIAKgEAJQgFALgEALQgEALgCALQgDAMgBALgAE4gnIAAhJIgVAAIAAgOIADAAQAKAAAFgEQAHgEABgJIAQAAIAABogADjgnIAAhpIA7AAIAAARIglAAIAAAZIAjAAIAAASIgjAAIAAAtgABTgnIAAhPIATAAIAAALIABAAQADgGAEgEQAFgDAGAAIACAAIACABIAAATIgMAAIgFACQgCACgBADQgBACAAAEIAAAwgAgQgnIAAhpIAUAAIAABpgAkOgnIAAhPIATAAIAAALQADgGAFgEQAEgDAGAAIACAAIABABIAAATIgLAAIgEACQgDACgBADQgBACgBAEIAAAwgAofgnIAAg2QAAgHgCgCQgCgDgEAAQgMAAAAAOIAAA0IgUAAIAAhpIAUAAIAAAiIABAAQAGgKANAAQAKAAAFAFQAFAFAAAMIAAA7gAp4gnIAAhYIgXAAIAAgRIBDAAIAAARIgYAAIAABYgACThUIgIgGQgDgDgCgFQgCgEAAgGQAAgFACgEQACgFADgEQAEgDAEgCQAEgCAFAAQAGAAAFACQAEACADADQAEAEACAFQACAEAAAFQAAAGgCAEQgCAFgEADIgHAGQgFACgGAAQgFAAgEgCgACWh8IgGAEQgDACAAADIgCAHIACAIQAAADADACQACADAEABIAGABQAFABACgCQAEgBADgDQACgCABgDIABgIIgBgHQgBgDgCgCIgHgEQgCgBgFgBIgGACgAChheIgGgLIgCAAIAAALIgHAAIAAgbIAMAAQAFAAACACQADADAAAEQAAADgCACIgFACIAHALgACZhtIAFAAIADgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIgBgCIgBgBIgHAAg");
	this.shape.setTransform(-25.6,-183.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070, new cjs.Rectangle(-91.5,-198.1,131.8,29.299999999999983), null);


(lib.txt_purposeBuilt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AhVCuIAAgyIARACQATgBAIgJQAIgKACgQIhKkHIBGAAIAmC1IABAAIAji1IBDAAIg/D1QgJAhgIAUQgIAUgLALQgKAMgQADQgPADgYAAg");
	this.shape.setTransform(549.575,-57.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgECoQgNgDgGgIQgIgIgCgOQgCgNAAgUIAAiWIgiAAIAAguIAiAAIAAhLIBDAAIAABLIAmAAIAAAuIgmAAIAACOQAAAPAEAHQAEAHAQAAIAHgBIAHAAIAAAvIgVAAIgXABQgTAAgLgCg");
	this.shape_1.setTransform(531.8,-65.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AghCxIAAkHIBDAAIAAEHgAghh2IAAg6IBDAAIAAA6g");
	this.shape_2.setTransform(518.825,-66.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AghCvIAAldIBDAAIAAFdg");
	this.shape_3.setTransform(507.325,-65.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AghCxIAAkHIBDAAIAAEHgAghh2IAAg6IBDAAIAAA6g");
	this.shape_4.setTransform(495.825,-66.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgLCqQgOgHgLgTIgBAAIAAAcIhBAAIAAldIBDAAIAABvIACAAQAKgQAOgHQAMgIAUAAQApAAAUAgQATAhAABIQAABKgTAgQgUAggpAAQgVAAgNgIgAgcgXQgHAVAAAqQAAArAHAWQAHAWAVAAQAXAAAGgWQAHgWAAgrQAAgqgHgVQgGgWgXAAQgVAAgHAWg");
	this.shape_5.setTransform(478.25,-65.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AhECEQgMgGgHgLQgHgLgEgOQgDgNAAgNQAAgTADgNQAFgOAHgJQAJgJAMgGQANgHARgFIAlgKQAPgEAHgGQAFgIAAgNQABgPgIgIQgGgJgRAAQgPAAgJAKQgHAIAAARIAAAGIg9AAIAAgGQAAgWAHgQQAIgPANgKQALgJASgFQAQgEAUAAQAdAAASAGQAUAGAJAKQALALADAPQAEAQAAARIAACJIACAdIAGAXIhAAAIgFgOIgEgOIgBAAQgLAVgQAGQgOAGgYAAQgSAAgNgGgAAPAJIgPAFQgTAEgIAKQgKALABARQgBAPAGALQAGALAOAAIANgCQAHgCAHgFQAFgFAFgIQADgIAAgKIAAg1g");
	this.shape_6.setTransform(454,-61.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AghCxIAAkHIBDAAIAAEHgAghh2IAAg6IBDAAIAAA6g");
	this.shape_7.setTransform(436.775,-66.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AghCvIAAldIBDAAIAAFdg");
	this.shape_8.setTransform(425.275,-65.85);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("Ag3B9QgUgLgKgVQgKgUgCgZIgDgwQAAgbAEgZQAEgZALgSQALgUAUgLQAVgLAhAAQAeAAATAKQASAJALASQALARAEAYQAEAaAAAeIAAAOIiFAAIAAAVIACAWIAGAUQADAJAHAFQAGAGAIgBQASAAAIgMQAHgMADgZIA9AAQgCAugXAYQgWAYgxAAQgjAAgVgNgAgOhXQgHAGgDAHIgGARIgCATIAAAKIBEAAIgCgbQgBgMgEgHQgDgJgHgEQgHgEgKAAQgJAAgHAEg");
	this.shape_9.setTransform(408.325,-61.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AhECHIAAkGIBAAAIAAAjIABAAQAKgTAOgMQAPgLAVAAIAGAAIAGABIAABAIgKAAIgLgBIgRADQgKACgHAGQgHAGgEAJQgEAJAAANIAACdg");
	this.shape_10.setTransform(390.15,-61.875);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AghCvIAAldIBDAAIAAFdg");
	this.shape_11.setTransform(363.825,-65.85);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhECEQgMgGgHgLQgIgLgDgOQgEgNAAgNQAAgTAFgNQAEgOAHgJQAJgJAMgGQAMgHATgFIAlgKQAPgEAFgGQAHgIgBgNQABgPgIgIQgGgJgRAAQgQAAgHAKQgIAIAAARIAAAGIg9AAIAAgGQAAgWAHgQQAIgPAMgKQAMgJASgFQAQgEAUAAQAdAAATAGQASAGAKAKQALALAEAPQADAQAAARIAACJIACAdIAGAXIhAAAIgFgOIgEgOIAAAAQgMAVgQAGQgOAGgZAAQgRAAgNgGgAAPAJIgOAFQgUAEgIAKQgJALAAARQgBAPAGALQAGALAOAAIANgCQAIgCAFgFQAGgFAFgIQADgIAAgKIAAg1g");
	this.shape_12.setTransform(346.25,-61.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AAgCHIAAi1QABgUgIgIQgGgIgPAAQgkAAABArIAACuIhEAAIAAkGIBBAAIAAAeIABAAQALgTARgJQAQgJAWAAQAgAAASARQARASAAAoIAADCg");
	this.shape_13.setTransform(322.65,-61.875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgxCDQgUgJgNgRQgLgSgFgaQgFgaAAgjQAAggAGgaQAFgaANgRQAMgSATgJQAVgJAbAAQAegBAUAJQAVAIAMATQALARAFAaQAFAaAAAhQAAAjgFAaQgGAagMARQgNARgTAIQgUAJgdAAIgDAAQgcAAgSgHgAgThUQgHAHgEAMQgDANgBAQIgBAkIABAmQABARADANQAEALAHAIQAIAGALAAQAVAAAIgWQAHgVABgyQgBgwgHgWQgIgVgVAAQgLAAgIAHg");
	this.shape_14.setTransform(298.9,-61.5999);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AghCxIAAkHIBDAAIAAEHgAghh2IAAg6IBDAAIAAA6g");
	this.shape_15.setTransform(281.525,-66.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgFCoQgMgDgGgIQgHgIgDgOQgCgNAAgUIAAiWIgiAAIAAguIAiAAIAAhLIBCAAIAABLIAnAAIAAAuIgnAAIAACOQABAPAEAHQAEAHAQAAIAHgBIAHAAIAAAvIgVAAIgWABQgUAAgMgCg");
	this.shape_16.setTransform(268.75,-65.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AhmCyIAAlcIBBAAIAAAcIABAAQALgSAOgJQANgHAUgBQAqABATAgQAUAhAABJQAABJgUAfQgTAhgqAAQgTAAgMgIQgOgHgLgPIgBAAIAABtgAgchnQgGAWgBArQABAqAGAWQAHAWAWAAQAWAAAGgWQAHgWAAgqQAAgrgHgWQgGgVgWgBQgWABgHAVg");
	this.shape_17.setTransform(249.7,-57.65);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("Ag3B9QgUgLgKgVQgKgUgCgZIgDgwQAAgbAEgZQAEgZALgSQALgUAUgLQAVgLAhAAQAeAAATAKQASAJALASQALARAEAYQAEAaAAAeIAAAOIiFAAIAAAVIACAWIAGAUQADAJAHAFQAGAGAIgBQASAAAIgMQAHgMADgZIA9AAQgCAugXAYQgWAYgxAAQgjAAgVgNgAgOhXQgHAGgDAHIgGARIgCATIAAAKIBEAAIgCgbQgBgMgEgHQgDgJgHgEQgHgEgKAAQgJAAgHAEg");
	this.shape_18.setTransform(226.075,-61.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgrCEQgTgGgMgQQgNgQgGgbQgHgbAAgoQAAgnAIgbQAIgbAOgPQAPgQATgHQAUgGAWAAQAvAAAYAcQAYAbAAAvIhBAAIgBgTIgEgRQgEgIgGgEQgFgFgKAAQgMAAgHAGQgIAFgEALQgEALgBARIgCAnIACAqQABASAEAKQAEAMAHAFQAHAGAKgBQARAAAIgOQAIgPAAggIBBAAQAAAzgXAbQgYAcg2AAQgYAAgTgGg");
	this.shape_19.setTransform(203.675,-61.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AAnCEIgnhWIgmBWIhHAAIBIiHIhFiAIBHAAIAjBQIAkhQIBHAAIhFCAIBICHg");
	this.shape_20.setTransform(181.325,-61.525);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("Ag3B9QgUgLgKgVQgKgUgCgZIgDgwQAAgbAEgZQAEgZALgSQALgUAUgLQAVgLAhAAQAeAAATAKQASAJALASQALARAEAYQAEAaAAAeIAAAOIiFAAIAAAVIACAWIAGAUQADAJAHAFQAGAGAIgBQASAAAIgMQAHgMADgZIA9AAQgCAugXAYQgWAYgxAAQgjAAgVgNgAgOhXQgHAGgDAHIgGARIgCATIAAAKIBEAAIgCgbQgBgMgEgHQgDgJgHgEQgHgEgKAAQgJAAgHAEg");
	this.shape_21.setTransform(158.925,-61.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AhFCHIAAkGIBCAAIAAAjIABAAQAIgTAPgMQAPgLAVAAIAGAAIAHABIAABAIgLAAIgLgBIgSADQgIACgIAGQgHAGgFAJQgDAJAAANIAACdg");
	this.shape_22.setTransform(466.25,-116.825);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AgyCCQgTgIgMgSQgMgQgFgbQgFgaAAgiQAAghAFgaQAGgaAMgSQAMgRAVgJQATgJAcAAQAeAAAVAIQATAIAMASQAMASAFAaQAFAaAAAiQAAAhgGAaQgFAagMASQgNARgTAJQgUAIgdAAIgDAAQgcAAgTgIgAgShUQgIAGgDANQgEANgBAQIgBAlIABAlQABARAEAMQADANAIAGQAHAIALAAQAVAAAHgXQAJgVgBgxQABgxgJgVQgHgWgVAAQgLAAgHAHg");
	this.shape_23.setTransform(445.55,-116.5499);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgjCyIAAjYIgiAAIAAguIAiAAIAAgeQAAgSAEgMQAGgMAJgIQAJgHAMgDQANgDARAAIAkABIAAAwIgHAAIgHAAQgOAAgGAEQgFAFgBAMIAAAXIAoAAIAAAuIgoAAIAADYg");
	this.shape_24.setTransform(426.9,-121.125);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgFCoQgMgDgHgIQgGgIgDgOQgCgNAAgUIAAiWIgiAAIAAguIAiAAIAAhLIBCAAIAABLIAoAAIAAAuIgoAAIAACOQABAPAEAHQAFAHAPAAIAHgBIAIAAIAAAvIgWAAIgWABQgUAAgMgCg");
	this.shape_25.setTransform(401.15,-120.175);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AghCvIAAldIBDAAIAAFdg");
	this.shape_26.setTransform(388.175,-120.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AghCxIAAkHIBDAAIAAEHgAghh2IAAg6IBDAAIAAA6g");
	this.shape_27.setTransform(376.675,-121);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AhSB1QgRgQAAgoIAAjDIBEAAIAAC1QAAAVAGAIQAIAIAPAAQAiAAABgsIAAiuIBDAAIAAEHIhBAAIAAgfIgBAAQgKAUgRAIQgRAJgWgBQggABgSgSg");
	this.shape_28.setTransform(358.8,-116.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AgLCqQgOgHgLgTIgBAAIAAAcIhBAAIAAldIBDAAIAABvIABAAQALgQAOgHQAMgIAUAAQApAAATAgQAUAhAABIQAABKgUAgQgTAggpAAQgVAAgNgIgAgcgXQgGAVgBAqQABArAGAWQAHAWAVAAQAWAAAHgWQAHgWAAgrQAAgqgHgVQgHgWgWAAQgVAAgHAWg");
	this.shape_29.setTransform(334.85,-120.525);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AhEAdIAAg5ICJAAIAAA5g");
	this.shape_30.setTransform(313.525,-117.45);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("Ag3B9QgUgLgKgUQgKgVgCgYIgDgyQAAgbAEgXQAEgZALgTQALgTAUgMQAVgLAhAAQAeAAATAJQASAKALARQALASAEAZQAEAYAAAfIAAAOIiFAAIAAAVIACAXIAGAUQADAIAHAFQAGAFAIABQASAAAIgNQAHgMADgaIA9AAQgCAvgXAYQgWAYgxAAQgjAAgVgNgAgOhWQgHAEgDAIIgGARIgCASIAAALIBEAAIgCgbQgBgLgEgJQgDgHgHgFQgHgEgKAAQgJAAgHAFg");
	this.shape_31.setTransform(293.375,-116.55);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#353535").s().p("AguCEQgUgFgLgLQgKgLgEgPQgGgQAAgSIAAgJIA+AAIAAAIQgBARAJALQAKAKARABQAPAAAJgJQAJgIAAgPQAAgNgHgHQgIgGgJgEIgvgRQgcgKgOgRQgPgRAAgdQAAgPAGgPQAFgOAMgLQAMgLASgGQATgHAZAAQAtAAAXATQAWAUAAAkIAAALIg9AAQAAgVgGgKQgHgJgRAAQgMAAgJAHQgKAHABAOQAAALAFAHQAHAIARAGIAnANQAgALANARQANARABAeQAAAUgIAQQgHAPgNALQgNAKgSAEQgRAFgWAAQgcAAgSgGg");
	this.shape_32.setTransform(271.4,-116.55);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#353535").s().p("AgyCCQgUgIgLgSQgMgQgFgbQgFgaAAgiQAAghAGgaQAFgaANgSQAMgRATgJQAVgJAbAAQAeAAAUAIQAVAIAMASQALASAFAaQAFAaAAAiQAAAhgFAaQgGAagMASQgNARgTAJQgUAIgdAAIgDAAQgcAAgTgIgAgShUQgIAGgEANQgDANgBAQIgBAlIABAlQABARADAMQAEANAIAGQAHAIALAAQAVAAAIgXQAHgVABgxQgBgxgHgVQgIgWgVAAQgLAAgHAHg");
	this.shape_33.setTransform(249.05,-116.5499);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#353535").s().p("AhmCxIAAlbIBBAAIAAAdIABAAQALgUAOgHQANgIAVAAQApgBATAhQAUAgAABKQAABIgUAhQgTAfgpAAQgUAAgMgGQgNgIgMgQIgBAAIAABtgAgchmQgGAVgBArQABAqAGAWQAHAWAVAAQAWAAAHgWQAHgWAAgqQAAgrgHgVQgHgXgWAAQgVAAgHAXg");
	this.shape_34.setTransform(225.6,-112.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#353535").s().p("AhECHIAAkGIBAAAIAAAjIABAAQAJgTAPgMQAPgLAVAAIAGAAIAGABIAABAIgLAAIgKgBIgRADQgKACgHAGQgHAGgEAJQgEAJAAANIAACdg");
	this.shape_35.setTransform(206.2,-116.825);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#353535").s().p("AhRB1QgSgQAAgoIAAjDIBDAAIAAC1QABAVAGAIQAIAIAPAAQAiAAABgsIAAiuIBDAAIAAEHIhBAAIAAgfIgBAAQgKAUgRAIQgRAJgWgBQggABgRgSg");
	this.shape_36.setTransform(185,-116.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#353535").s().p("AhtCvIAAldIB7AAQAbAAASAKQASAJAMAOQALAPAFASQAFAUAAATQAAAbgIAUQgIAUgPAMQgOANgVAGQgVAGgXAAIgmAAIAACMgAgmgQIAfAAQAUAAANgNQANgMAAgbQAAgagLgOQgLgOgaAAIgdAAg");
	this.shape_37.setTransform(161.025,-120.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_purposeBuilt, new cjs.Rectangle(145.6,-152.4,997.8000000000001,116.9), null);


(lib.txt_industrialLevel = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgyCNQgUgHgMgLQgLgLgFgQQgEgRAAgUIAAgKIBAAAIAAAJQAAASAJAMQAKALASAAQAQAAAKgJQAKgHAAgSQAAgNgIgHQgIgHgLgEIgwgSQgfgLgOgRQgPgUAAgeQgBgRAHgPQAFgPANgLQAMgMATgHQAUgGAaAAQAygBAWAVQAYAVAAAmIAAALIhAAAQAAgWgIgKQgGgJgSgBQgMAAgKAIQgKAHAAAQQAAAKAFAJQAHAHASAGIArAPQAhALAOARQAOAUABAfQgBAXgHAPQgIARgOALQgOALgTAFQgSAEgXAAQgdAAgVgFg");
	this.shape.setTransform(515.5,-74.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AhYCbQgUgjAAhOQAAhNAUgiQAVgiAsAAQAUgBAOAJQAOAIAMARIABAAIAAh1IBHAAIAAFyIhEAAIAAgeIgBAAQgMATgPAJQgOAHgWAAQgsAAgVghgAgegZQgHAXAAAsQAAAvAHAXQAHAXAXAAQAYAAAHgXQAHgXAAgvQAAgsgHgXQgHgYgYAAQgXAAgHAYg");
	this.shape_1.setTransform(490.875,-78.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("Ag6CFQgWgNgLgVQgKgWgDgaIgCg0QAAgcAEgaQAEgaAMgUQALgUAWgNQAWgMAkABQAfgBAUAKQAUAKALATQAMATAEAaQAEAaAAAhIAAAOIiNAAIAAAXIACAYIAGAVQAEAJAHAGQAGAFAJAAQATAAAIgNQAIgNADgbIBBAAQgCAygYAZQgYAZg0AAQglAAgWgNgAgPhcQgHAFgEAIIgGASIgCAUIAAALIBIAAIgCgcQgBgNgEgIQgEgJgHgEQgHgFgLAAQgKAAgHAFg");
	this.shape_2.setTransform(466.425,-74.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("Ag6CFQgWgNgLgVQgKgWgDgaIgCg0QAAgcAEgaQAEgaAMgUQALgUAWgNQAWgMAkABQAfgBAUAKQAUAKALATQAMATAEAaQAEAaAAAhIAAAOIiNAAIAAAXIACAYIAGAVQAEAJAHAGQAGAFAJAAQATAAAIgNQAIgNADgbIBBAAQgCAygYAZQgYAZg0AAQglAAgWgNgAgPhcQgHAFgEAIIgGASIgCAUIAAALIBIAAIgCgcQgBgNgEgIQgEgJgHgEQgHgFgLAAQgKAAgHAFg");
	this.shape_3.setTransform(442.625,-74.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AhsC9IAAlxIBEAAIAAAdIABAAQAMgTAPgJQAOgIAWAAQAsAAAVAiQAUAiAABOQAABNgUAjQgVAhgsAAQgUAAgOgHQgOgIgMgQIgBAAIAAB0gAgehtQgHAXAAAtQAAAuAHAXQAHAXAXAAQAYAAAHgXQAHgXAAguQAAgtgHgXQgHgYgYAAQgXAAgHAYg");
	this.shape_4.setTransform(418.175,-69.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgyCNQgUgHgLgLQgMgLgEgQQgGgRAAgUIAAgKIBBAAIAAAJQAAASAKAMQAJALATAAQAPAAAKgJQAKgHAAgSQAAgNgIgHQgHgHgLgEIgygSQgegLgPgRQgOgUAAgeQAAgRAFgPQAGgPAMgLQANgMAUgHQATgGAaAAQAygBAWAVQAZAVAAAmIAAALIhBAAQAAgWgHgKQgHgJgSgBQgNAAgKAIQgJAHgBAQQAAAKAHAJQAGAHATAGIApAPQAjALAOARQANAUAAAfQAAAXgIAPQgHARgOALQgOALgTAFQgTAEgWAAQgdAAgVgFg");
	this.shape_5.setTransform(393.6,-74.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAiCQIAAjBQAAgVgHgJQgHgIgQgBQgmAAAAAvIAAC5IhHAAIAAkXIBEAAIAAAgIABAAQAMgUASgKQARgJAYAAQAiAAATASQASATAAAqIAADPg");
	this.shape_6.setTransform(357.1,-74.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("Ag0CKQgWgJgMgSQgNgSgFgcQgFgcAAglQAAgiAGgcQAFgbANgTQANgTAVgJQAVgJAeAAQAggBAVAJQAWAJANATQAMATAFAbQAFAcAAAjQAAAlgFAbQgGAcgNASQgNATgVAIQgVAJgfAAIgCABQgeAAgUgJgAgUhaQgIAIgDANQgEANgBASIgBAmIABAoQABASAEANQADAOAIAGQAIAIAMAAQAWAAAIgXQAJgXAAg1QAAgzgJgXQgIgWgWgBQgMABgIAGg");
	this.shape_7.setTransform(331.875,-74.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgjC8IAAkXIBHAAIAAEXgAgjh9IAAg+IBHAAIAAA+g");
	this.shape_8.setTransform(313.45,-78.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgFCyQgNgDgHgIQgIgJgCgOQgDgOAAgWIAAifIgkAAIAAgxIAkAAIAAhQIBHAAIAABQIAqAAIAAAxIgqAAIAACXQAAAQAGAHQAEAHAQAAIAIAAIAIgBIAAAyIgYABIgXABQgUAAgNgDg");
	this.shape_9.setTransform(299.9,-77.975);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AguCMQgUgHgNgRQgNgQgHgdQgHgdAAgqQAAgpAJgdQAIgcAPgRQAPgRAVgHQAVgGAYAAQAxAAAaAcQAZAdAAAzIhFAAIgBgUIgFgSQgDgIgGgGQgGgEgLAAQgMAAgIAFQgJAHgEALQgEALgBATIgCApIACAsQABATAEAMQAEAMAIAGQAHAFALAAQATAAAIgQQAIgQAAghIBFAAQAAA2gZAdQgZAdg5AAQgaAAgUgGg");
	this.shape_10.setTransform(280.325,-74.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AhXB9QgSgSAAgrIAAjOIBHAAIAADAQABAWAHAIQAHAKARgBQAkABABgvIAAi5IBHAAIAAEXIhFAAIAAghIgBAAQgLAVgSAJQgSAJgXAAQgiAAgTgSg");
	this.shape_11.setTransform(255.55,-73.75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhYCbQgUgjAAhOQAAhNAUgiQAVgiAsAAQAUgBAOAJQAOAIAMARIABAAIAAh1IBHAAIAAFyIhEAAIAAgeIgBAAQgMATgPAJQgOAHgWAAQgsAAgVghgAgegZQgHAXAAAsQAAAvAHAXQAHAXAXAAQAYAAAHgXQAHgXAAgvQAAgsgHgXQgHgYgYAAQgXAAgHAYg");
	this.shape_12.setTransform(229.475,-78.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("Ag0CKQgWgJgMgSQgNgSgFgcQgFgcAAglQAAgiAGgcQAFgbANgTQANgTAVgJQAVgJAeAAQAggBAVAJQAWAJANATQAMATAFAbQAFAcAAAjQAAAlgFAbQgGAcgNASQgNATgVAIQgVAJgfAAIgCABQgeAAgUgJgAgUhaQgIAIgDANQgEANgBASIgBAmIABAoQABASAEANQADAOAIAGQAIAIAMAAQAWAAAIgXQAJgXAAg1QAAgzgJgXQgIgWgWgBQgMABgIAGg");
	this.shape_13.setTransform(204.575,-74.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AhICQIAAkXIBEAAIAAAmIABAAQAKgVAPgMQARgMAWAAIAGAAIAGAAIAABFIgKAAIgLgBIgUADQgJACgIAHQgIAFgEAKQgEAKAAANIAACog");
	this.shape_14.setTransform(184.8,-74.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AhsC9IAAlxIBEAAIAAAdIABAAQAMgTAPgJQAOgIAWAAQAsAAAVAiQAUAiAABOQAABNgUAjQgVAhgsAAQgUAAgOgHQgOgIgMgQIgBAAIAAB0gAgehtQgHAXAAAtQAAAuAHAXQAHAXAXAAQAYAAAHgXQAHgXAAguQAAgtgHgXQgHgYgYAAQgXAAgHAYg");
	this.shape_15.setTransform(162.625,-69.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgjC6IAAlzIBHAAIAAFzg");
	this.shape_16.setTransform(451.6,-134.05);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("Ag6CFQgWgNgLgVQgKgWgDgaIgCg0QAAgcAEgaQAEgaAMgUQALgUAWgNQAWgMAkABQAfgBAUALQAUAJALATQAMATAEAaQAEAaAAAhIAAAOIiNAAIAAAXIACAYIAGAVQAEAJAHAFQAGAGAJAAQATAAAIgNQAIgNADgbIBBAAQgCAygYAYQgYAag0AAQglAAgWgNgAgPhcQgHAFgEAIIgGASIgCAUIAAALIBIAAIgCgdQgBgMgEgIQgEgJgHgEQgHgFgLAAQgKABgHAEg");
	this.shape_17.setTransform(433.575,-129.55);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgnCMIhJkXIBLAAIAnDHIABAAIAmjHIBIAAIhHEXg");
	this.shape_18.setTransform(410.3,-129.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("Ag6CFQgWgNgLgVQgKgWgDgaIgCg0QAAgcAEgaQAEgaAMgUQALgUAWgNQAWgMAkABQAfgBAUALQAUAJALATQAMATAEAaQAEAaAAAhIAAAOIiNAAIAAAXIACAYIAGAVQAEAJAHAFQAGAGAJAAQATAAAIgNQAIgNADgbIBBAAQgCAygYAYQgYAag0AAQglAAgWgNgAgPhcQgHAFgEAIIgGASIgCAUIAAALIBIAAIgCgdQgBgMgEgIQgEgJgHgEQgHgFgLAAQgKABgHAEg");
	this.shape_19.setTransform(386.975,-129.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgjC6IAAlzIBHAAIAAFzg");
	this.shape_20.setTransform(369,-134.05);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AhIAfIAAg9ICRAAIAAA9g");
	this.shape_21.setTransform(353.425,-130.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AgjC6IAAlzIBHAAIAAFzg");
	this.shape_22.setTransform(337.85,-134.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AhICMQgNgHgIgLQgHgMgEgOQgEgOAAgOQAAgUAFgOQAEgPAIgKQAJgJANgHQANgHATgEIAogLQAQgFAGgHQAGgIAAgOQAAgPgHgKQgIgIgRgBQgRAAgIAKQgIAKAAAQIAAAIIhBAAIAAgHQAAgXAIgRQAIgQANgKQANgLASgEQASgFAUABQAgAAATAFQAUAHALALQALAMAEAPQAEARAAASIAACTIACAeIAHAYIhFAAIgFgPIgEgPIgBAAQgMAWgRAHQgPAGgaAAQgTAAgNgGgAAQAJIgQAGQgUAFgKAKQgJALAAATQAAAQAGAMQAGALAPAAIAOgCQAIgCAGgGQAHgFAEgJQAEgIAAgMIAAg3g");
	this.shape_23.setTransform(319.175,-129.55);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgjC8IAAkXIBHAAIAAEXgAgjh9IAAg+IBHAAIAAA+g");
	this.shape_24.setTransform(300.9,-134.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AhJCQIAAkXIBFAAIAAAmIABAAQAKgVAQgMQAPgMAWAAIAHAAIAGABIAABEIgLgBIgLAAIgSADQgKACgIAHQgIAFgEAKQgEAKAAANIAACog");
	this.shape_25.setTransform(287.35,-129.85);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgFCyQgNgDgHgIQgHgJgDgOQgCgOAAgWIAAifIglAAIAAgxIAlAAIAAhQIBGAAIAABQIAqAAIAAAxIgqAAIAACXQAAAQAFAHQAFAHAQAAIAIAAIAIgBIAAAyIgXABIgYABQgUAAgNgDg");
	this.shape_26.setTransform(270.3,-133.425);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgyCNQgUgHgMgLQgLgLgFgQQgEgRAAgUIAAgKIBAAAIAAAJQAAASAKAMQAJALATAAQAPAAAKgJQAKgHAAgSQAAgNgIgHQgIgHgLgEIgwgSQgfgLgOgRQgQgUABgeQgBgQAHgQQAFgPANgLQAMgMATgHQAUgGAaAAQAygBAWAVQAYAVABAmIAAAMIhBAAQAAgXgHgKQgIgJgRgBQgNAAgJAIQgKAHAAAQQAAAKAFAJQAHAHATAGIAqAPQAhALAOARQAPAUAAAfQgBAXgHAPQgIARgOALQgOALgTAFQgSAEgXAAQgdAAgVgFg");
	this.shape_27.setTransform(251.25,-129.55);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AhXB9QgSgSAAgrIAAjOIBHAAIAADAQAAAWAIAJQAHAJARAAQAlAAgBgvIAAi5IBIAAIAAEXIhFAAIAAghIgBAAQgLAVgSAJQgRAJgYAAQgiAAgTgSg");
	this.shape_28.setTransform(226.95,-129.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AhYCbQgUgjAAhOQAAhMAUgjQAVgiAsAAQAUgBAOAJQAOAIAMARIABAAIAAh2IBHAAIAAFzIhEAAIAAgeIgBAAQgMATgPAIQgOAIgWAAQgsAAgVghgAgegZQgHAXAAAsQAAAvAHAXQAHAXAXAAQAYAAAHgXQAHgXAAgvQAAgsgHgXQgHgYgYABQgXgBgHAYg");
	this.shape_29.setTransform(200.875,-133.75);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AAjCQIAAjBQAAgVgIgJQgHgIgRAAQgkgBgBAvIAAC5IhHAAIAAkXIBFAAIAAAgIABAAQALgUASgKQASgJAXAAQAiAAATASQASATAAAqIAADPg");
	this.shape_30.setTransform(175.45,-129.85);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgkC6IAAlzIBKAAIAAFzg");
	this.shape_31.setTransform(156,-134.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_industrialLevel, new cjs.Rectangle(147.3,-167.4,887.8,120.9), null);


(lib.txt_humor = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgOA1IAHgNIAEgMIACgOIABgOIgBgNIgCgOIgEgNIgHgMIANAAQAIAOAEANQAEANAAAMQAAANgEANQgEANgIAOg");
	this.shape.setTransform(11.875,-152.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgHAJIAAgRIAPAAIAAARg");
	this.shape_1.setTransform(9.4,-149.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgQAhIAAg/IAQAAIAAAIQABgFAEgDQAEgCAFAAIABAAIACAAIAAAQIgDgBIgCAAIgFABIgDACIgEAEIAAAFIAAAmg");
	this.shape_2.setTransform(6.65,-152.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgLAgQgGgCgCgFQgDgEgCgGIgBgPIABgOQACgGADgEQADgFAFgCQAFgCAGAAQAHAAAFACQAFACADAEQADAFABAGQABAGABAIQgBAIgBAHQgBAGgEAEQgCAEgGADQgEACgHAAQgHAAgEgCgAgEgUQgCACgBADIgBAHIAAAIIAAAJIABAHQABADACACQACACACAAQAFAAACgGQABgFAAgMQAAgLgBgFQgCgGgFAAQgCAAgCACg");
	this.shape_3.setTransform(1.95,-152.13);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AAXAhIAAgsQAAgEgBgDQgCgCgDAAQgEABgCACQgDADAAAFIAAAqIgQAAIAAgsQAAgEgBgDQgCgCgDAAQgDABgDACQgDADABAFIAAAqIgRAAIAAg/IAQAAIAAAGQADgEAEgCQAEgCAGAAQAFAAADACQAEADABAFQADgFAEgDQAEgCAGAAQAIAAAEAEQAEAGAAAJIAAAug");
	this.shape_4.setTransform(-5.05,-152.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgTAcQgEgDgBgKIAAgvIARAAIAAArQAAAGACABQACACADAAQAIAAAAgKIAAgqIARAAIAABAIgQAAIAAgIQgEAFgEACQgCACgGAAQgIAAgEgFg");
	this.shape_5.setTransform(-12.2,-152.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAIArIAAgsQAAgFgCgCQgBgCgEAAQgIAAAAAKIAAArIgRAAIAAhVIARAAIAAAcIABAAQAEgIAKAAQAIAAAEAEQAFAEgBAKIAAAvg");
	this.shape_6.setTransform(-17.8,-153.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgQAhIAAg/IAQAAIAAAIQACgFADgDQAEgCAFAAIABAAIACAAIAAAQIgDgBIgCAAIgEABIgFACIgCAEIgBAFIAAAmg");
	this.shape_7.setTransform(-24.55,-152.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgNAfQgFgDgCgFQgDgFAAgGIgBgMIABgMQABgGADgFQADgEAFgDQAFgDAHAAQAHAAAFACQAEADADAEQADAEABAGIABAOIAAACIggAAIAAAGIAAAFIACAFIACADQABABAAAAQABAAAAAAQABABAAAAQAAAAAAAAQAEAAACgDQACgDABgGIAPAAQgBALgFAGQgGAGgMAAQgIAAgFgDgAgDgVIgCADIgCAFIAAAEIAAADIAQAAIgBgHIgBgFIgCgDIgFgBIgDABg");
	this.shape_8.setTransform(-29.175,-152.125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgNAfQgFgDgCgFQgDgFAAgGIgBgMIABgMQABgGADgFQADgEAFgDQAFgDAHAAQAHAAAFACQAEADADAEQADAEABAGIABAOIAAACIggAAIAAAGIAAAFIACAFIACADQABABAAAAQABAAAAAAQABABAAAAQAAAAAAAAQAEAAACgDQACgDABgGIAPAAQgBALgFAGQgGAGgMAAQgIAAgFgDgAgDgVIgCADIgCAFIAAAEIAAADIAQAAIgBgHIgBgFIgCgDIgFgBIgDABg");
	this.shape_9.setTransform(-34.325,-152.125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AAIAhIAAgsQAAgFgCgCQgCgCgDAAQgIAAAAALIAAAqIgQAAIAAg/IAPAAIAAAHQAEgFADgCQAEgCAFAAQAIAAAEAEQAEAFAAAJIAAAvg");
	this.shape_10.setTransform(-39.7,-152.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgHArIAAg/IAPAAIAAA/gAgHgcIAAgOIAPAAIAAAOg");
	this.shape_11.setTransform(-43.725,-153.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgRAnQgGgEAAgIIAQAAQAAADACACIADABIACAAQAFAAACgDQACgDAAgFIAAgIQgDADgEACQgCADgEAAQgKAAgFgIQgFgHAAgRIABgMQABgFABgFQADgFADgDQAFgDAGAAIAGACQAEACADAFIAAgHIAQAAIAAA8QAAANgGAGQgHAGgNAAQgLAAgFgFgAgDgdIgDAEIgBAHIAAALIAAAGIABAFQABAAAAABQAAAAAAABQABAAAAABQABAAAAAAQAAABABAAQAAAAABAAQAAABABAAQAAAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBIADgDIACgFIAAgIQAAgLgCgFQgCgFgEAAIgEABg");
	this.shape_12.setTransform(-47.85,-151.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AAIAhIAAgsQAAgFgCgCQgBgCgEAAQgIAAAAALIAAAqIgRAAIAAg/IARAAIAAAHQACgFAFgCQADgCAFAAQAIAAAEAEQAFAFgBAJIAAAvg");
	this.shape_13.setTransform(-53.35,-152.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgNAfQgFgDgCgFQgDgFAAgGIgBgMIABgMQABgGADgFQADgEAFgDQAFgDAHAAQAHAAAFACQAEADADAEQADAEABAGIABAOIAAACIggAAIAAAGIAAAFIACAFIACADQABABAAAAQAAAAABAAQABABAAAAQAAAAAAAAQAEAAACgDQACgDABgGIAPAAQgBALgFAGQgGAGgMAAQgIAAgFgDgAgDgVIgCADIgCAFIAAAEIAAADIAQAAIgBgHIgBgFIgCgDIgFgBIgDABg");
	this.shape_14.setTransform(-58.725,-152.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgHALQADgBABgDQACgDAAgDIAAgBIgGAAIAAgSIAPAAIAAAPIgBAIQgBAEgCADIgEAEQgCADgFAAg");
	this.shape_15.setTransform(-64.95,-148.85);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgUAqIAAgMIAFABQAEAAACgCQACgDAAgEIgSg/IASAAIAIArIAJgrIAQAAIgPA7IgFAMQgCAFgCAEQgCACgEABIgKAAg");
	this.shape_16.setTransform(-68.65,-151.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AgQAhIAAg/IAQAAIAAAIQABgFAEgDQAEgCAFAAIACAAIABAAIAAAQIgDgBIgCAAIgEABIgFACIgCAEIgBAFIAAAmg");
	this.shape_17.setTransform(-72.6,-152.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgQAhIAAg/IAQAAIAAAIQABgFAEgDQAEgCAFAAIABAAIACAAIAAAQIgDgBIgCAAIgFABIgDACIgEAEIAAAFIAAAmg");
	this.shape_18.setTransform(-76.15,-152.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgLAgQgGgCgCgFQgDgEgCgGIgBgPIABgOQACgGADgEQADgFAFgCQAFgCAGAAQAHAAAFACQAFACADAEQADAFABAGQABAGAAAIQAAAIgBAHQgBAGgEAEQgCAEgGADQgEACgHAAQgHAAgEgCgAgEgUQgCACgBADIgBAHIAAAIIAAAJIABAHQABADACACQACACACAAQAFAAACgGQABgFAAgMQAAgLgBgFQgCgGgFAAQgCAAgCACg");
	this.shape_19.setTransform(-80.85,-152.13);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgVAmQgGgGAAgNIAAgDIARAAIAAACIABAGIABAEIADADIAFABQAFAAADgCQACgDAAgFIAAgGIgCgDIgGgEIgGgCIgKgEQgEgDgCgCQgEgDgBgEIgBgJQAAgNAHgGQAHgHAMAAQAFAAAFACQAFABADADQAEADACAEQACAFAAAGIAAACIgRAAQAAgGgCgEQgCgCgFAAIgEAAIgDACIgBADIgBAFQAAADACADQACACAFADIAMAGIAIADIAGAGIACAFIAAAHQAAAOgHAGQgIAGgNAAQgPAAgGgGg");
	this.shape_20.setTransform(-86.45,-153.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AACA1QgIgOgEgNQgEgNAAgNQAAgMAEgNQAEgNAIgOIANAAIgHAMIgEANIgCAOIgBANIABAOIACAOIAEAMIAHANg");
	this.shape_21.setTransform(-90.625,-152.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_humor, new cjs.Rectangle(-224,-162.4,369,18.200000000000017), null);


(lib.printer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.projector_image();
	this.instance.setTransform(-393.95,-153.15,1.2254,1.2254);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_mc, new cjs.Rectangle(-393.9,-153.1,787.9,306.29999999999995), null);


(lib.Epson_Logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Epson_Logo();
	this.instance.setTransform(-94.65,-44.6,0.3994,0.3994);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Epson_Logo_1, new cjs.Rectangle(-94.6,-44.6,61.49999999999999,20.400000000000002), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape.setTransform(61.025,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_1.setTransform(47.475,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag1A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAfABAWAVQAXAXAAAeQAAAggXAVQgWAXgfAAQgfAAgWgXgAghghQgOAOAAATQAAAUAOAOQAOAPATAAQAUAAAOgPQAOgOAAgUQAAgTgOgOQgOgPgUAAQgTAAgOAPg");
	this.shape_2.setTransform(31.275,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBBMQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIglhSIgBAAIgMBOQAAADgEABIgSAAQgFgBABgEIAZiNQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAuBiIAAAAIAuhiQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAIADAAQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIAZCNQABAEgFABIgTAAQgDgBgBgDIgMhOIgBAAIglBSQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(13.1508,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BMQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIhUheIgBAAIAABZQAAAEgEABIgTAAQgEgBAAgEIAAiMQAAgDAEgBIADAAQABABAAAAQAAAAABAAQAAAAABAAQAAABABAAIBUBaIAAAAIAAhVQAAgFAFAAIATAAQAEAAAAAFIAACMQAAADgEABg");
	this.shape_4.setTransform(-10,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_5.setTransform(-25.075,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAwBLQgEgBgCgEIgLgWIg+AAIgKAWQgBAEgFABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIBBiNQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIACAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIBACNQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAVAYIgVgtIAAAAIgUAtIApAAg");
	this.shape_6.setTransform(-39.85,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_7.setTransform(-52.925,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBKQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAB1IA0AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_8.setTransform(-64.475,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_9.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,162.5,51.5), null);


(lib.shield_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon();
	this.instance.setTransform(-54,-63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shield_mc, new cjs.Rectangle(-54,-63,108,126), null);


(lib.gauge_needle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#06539E").s().p("AhYBiIgCgCIgDgDQgmgmAAg3QAAg2AmgnQAngmA2AAQA3AAAmAmIADADIACACQAiAmAAAyQAAA3gnAmQgmAng3AAQgyAAgmgig");
	this.shape.setTransform(-1.125,0.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_1.setTransform(33.9503,-32.507);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(6).p("AkNFzIKfryIgDgKQgJgDgBABQgBACsMKWQgKALgCASQgFAlAlAnQAeAfAmgMQAbgIAIgOg");
	this.shape_2.setTransform(34.1373,-32.507);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_3.setTransform(33.9503,-32.507);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.gauge_needle, new cjs.Rectangle(-16.3,-75.1,94.1,89.3), null);


(lib.checkMark_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(14).p("AgwgMQAgARAdAX");
	this.shape.setTransform(30.8836,-45.505);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(14).p("AiSgqQCCAUBnBQ");
	this.shape_1.setTransform(23.5006,-48.4675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(14).p("Ai6grQAZgCAbAAQC2AACLBq");
	this.shape_2.setTransform(13.5125,-48.805);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(14).p("AkvAjQB+hQCfAAQC2AACMBq");
	this.shape_3.setTransform(1.8625,-48.805);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(14).p("AmdDIQAnhtBYhYQCdibDcAAQC3AACMBr");
	this.shape_4.setTransform(-9.1375,-38.1235);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(14).p("AmLFqQghhYAAhlQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_5.setTransform(-10.6375,-17.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(14).p("AhnICQhcgnhMhMQididAAjdQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_6.setTransform(-10.6375,-2.0625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(14).p("AG9GQQiWCHjNAAQjdAAicidQidicAAjeQAAjdCdicQCcidDdAAQC3AACLBs");
	this.shape_7.setTransform(-9,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(14).p("AIWgeQABAPAAAPQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_8.setTransform(-0.025,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#06539E").ss(14).p("AHjjoQA0BqAAB+QAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_9.setTransform(-0.025,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#06539E").ss(14).p("AGdlTQB6CRAADCQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACLBs");
	this.shape_10.setTransform(-0.025,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#06539E").ss(14).p("AIXAAQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQDdAACdCdQCdCcAADdg");
	this.shape_11.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).wait(133));

	// Layer_3
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#06539E").ss(14,2,1).p("AgJgKIATAV");
	this.shape_12.setTransform(-19.3125,1.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#06539E").ss(14,2,1).p("AgkgmIBJBN");
	this.shape_13.setTransform(-16.6125,4.1875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#06539E").ss(14).p("AAZgYIgyAx");
	this.shape_14.setTransform(-4.4,11.7375);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#06539E").ss(14,1,1).p("AAXAYIgtgv");
	this.shape_15.setTransform(-9.275,11.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#06539E").ss(14,2,1).p("AgrgtIBXBb");
	this.shape_16.setTransform(-15.975,4.85);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#06539E").ss(14).p("ABEhCIiHCF");
	this.shape_17.setTransform(-0.125,7.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#06539E").ss(14).p("ACAh9Ij/D7");
	this.shape_18.setTransform(5.8875,1.6125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#06539E").ss(14).p("AChieIlBE9");
	this.shape_19.setTransform(9.175,-1.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#06539E").ss(14).p("ACtioIlZFR");
	this.shape_20.setTransform(10.3,-2.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#06539E").ss(14).p("ACoijIlPFH");
	this.shape_21.setTransform(9.8,-2.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_12}]},8).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_17}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_18}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_20}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_21}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).wait(129));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-60.4,152.7,152.6);


(lib.shield_icon_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// shield_mc (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_5 = new cjs.Graphics().p("Aobp1IQ3AAIAATrIw3AAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(5).to({graphics:mask_graphics_5,x:0,y:0}).wait(113));

	// shine
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(0.1).p("ADQjAIAAAdAjPDBIAAlm");
	this.shape.setTransform(-106.25,31.8125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGDHBMgiKAdaIpJH4g");
	this.shape_1.setTransform(-66.2,-76.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAOIAAgb");
	this.shape_2.setTransform(-84.35,15.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGDHBMgrTAlSg");
	this.shape_3.setTransform(-65.05,-75.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4qPKMArTglTIGDHBMgrTAlSg");
	this.shape_4.setTransform(-61.6,-71.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArUglTIGDHBMgrUAlSg");
	this.shape_5.setTransform(-55.8,-64.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAPIAAgd");
	this.shape_6.setTransform(-67,34);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGEHBMgrUAlSg");
	this.shape_7.setTransform(-47.7,-56.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAPIAAgc");
	this.shape_8.setTransform(-56.6,45.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(0.1).p("AjPDBIAAlmADQjAIAAAd");
	this.shape_9.setTransform(23.75,172.825);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4qPKMArTglTIGDHBMgiLAdbIpIH3g");
	this.shape_10.setTransform(63.8,64.725);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[{t:this.shape_3,p:{x:-65.05,y:-75.025}},{t:this.shape_2,p:{x:-84.35,y:15.2}}]},1).to({state:[{t:this.shape_4,p:{x:-61.6,y:-71.275}},{t:this.shape_2,p:{x:-80.9,y:18.95}}]},1).to({state:[{t:this.shape_5},{t:this.shape_2,p:{x:-75.1,y:25.25}}]},1).to({state:[{t:this.shape_7},{t:this.shape_6,p:{x:-67,y:34}}]},1).to({state:[{t:this.shape_4,p:{x:-37.3,y:-44.925}},{t:this.shape_8,p:{x:-56.6,y:45.3}}]},1).to({state:[{t:this.shape_4,p:{x:-24.6,y:-31.175}},{t:this.shape_8,p:{x:-43.9,y:59.05}}]},1).to({state:[{t:this.shape_3,p:{x:-9.6,y:-14.875}},{t:this.shape_8,p:{x:-28.9,y:75.35}}]},1).to({state:[{t:this.shape_3,p:{x:7.2,y:3.325}},{t:this.shape_6,p:{x:-12.1,y:93.55}}]},1).to({state:[{t:this.shape_4,p:{x:22.2,y:19.625}},{t:this.shape_8,p:{x:2.9,y:109.85}}]},1).to({state:[{t:this.shape_4,p:{x:34.9,y:33.375}},{t:this.shape_8,p:{x:15.6,y:123.6}}]},1).to({state:[{t:this.shape_3,p:{x:45.3,y:44.675}},{t:this.shape_8,p:{x:26,y:134.9}}]},1).to({state:[{t:this.shape_3,p:{x:53.4,y:53.425}},{t:this.shape_8,p:{x:34.1,y:143.65}}]},1).to({state:[{t:this.shape_4,p:{x:59.2,y:59.725}},{t:this.shape_8,p:{x:39.9,y:149.95}}]},1).to({state:[{t:this.shape_3,p:{x:62.65,y:63.475}},{t:this.shape_8,p:{x:43.35,y:153.7}}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).wait(98));

	// shield_mc
	this.instance = new lib.shield_mc();
	this.instance.setTransform(0,0,0.7857,0.7857);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.7921,scaleY:0.7921,alpha:0.121},0).wait(1).to({scaleX:0.8091,scaleY:0.8091,alpha:0.4415},0).wait(1).to({scaleX:0.8386,scaleY:0.8386,alpha:1},0).wait(1).to({scaleX:0.9035,scaleY:0.9035},0).wait(1).to({scaleX:0.977,scaleY:0.977},0).wait(1).to({scaleX:1.0343,scaleY:1.0343},0).wait(1).to({scaleX:1.0671,scaleY:1.0671},0).wait(1).to({scaleX:1.0794,scaleY:1.0794},0).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).wait(106));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.3,-68,116.6,136);


(lib.shield_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon_1("synched",0,false);
	this.instance.setTransform(24.4,-73.65,1.1164,1.1164);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(66).to({startPosition:66},0).to({_off:true},1).wait(293));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_Tolerant();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(58).to({_off:true},1).wait(293));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.6,-149.5,1093.8999999999999,155.8);


(lib.gauge_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// gauge_needle
	this.instance = new lib.gauge_needle();
	this.instance.setTransform(0.15,-0.95,0.0838,0.0838,-132.9925,0,0,0.1,0.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({regX:-0.3,regY:0.5,scaleX:1,scaleY:1,rotation:-132.9917,y:-0.9},5).wait(1).to({regX:31.7,regY:-30.5,rotation:-133.4994,x:-44.25,y:-2.75},0).wait(1).to({rotation:-134.6077,x:-44.3,y:-1.95},0).wait(1).to({regX:-0.1,regY:0.5,scaleX:0.9999,scaleY:0.9999,rotation:-136.3899,x:0.15,y:-1.05},0).to({regX:-0.2,scaleX:1,scaleY:1,rotation:6.0191,x:0.25,y:-0.75},11,cjs.Ease.quadInOut).to({regY:0.4,rotation:-1.643,x:0.2,y:-0.85},3).to({regY:0.3,rotation:3.7245,x:0.3,y:-0.95},3).to({rotation:-1.0125,x:0.25},3).to({rotation:3.7245,x:0.3},3).to({rotation:-0.2544},3).to({rotation:3.7245},3).to({rotation:-1.4769,x:0.25},3).to({rotation:3.7245,x:0.3},3).wait(37));

	// gauge_dial
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(15).p("AgmDdQAAjJBVil");
	this.shape.setTransform(-76.2611,-24.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(15).p("AhcEyQAAk2DNji");
	this.shape_1.setTransform(-70.8283,-33.4625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(15).p("Aj1GiQAAlMDqjqQCJiKCsg4");
	this.shape_2.setTransform(-55.508,-44.6875);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(15).p("AoDG2QAAlMDqjqQDrjqFLAAQB6AABtAf");
	this.shape_3.setTransform(-28.5375,-46.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(15).p("AqrG2QAAlMDqjqQDrjqFLAAQFNAADqDq");
	this.shape_4.setTransform(-11.75,-46.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(15).p("AsFG2QAAlMDqjqQDrjqFLAAQFMAADrDqQB5B6A7CS");
	this.shape_5.setTransform(-2.7375,-46.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(15).p("AsbG2QAAlMDrjqQDrjqFKAAQFNAADqDqQC3C2ApDx");
	this.shape_6.setTransform(-0.5875,-46.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(15).p("AsgG2QAAlMDrjqQDrjqFKAAQFNAADqDqQDXDWATEo");
	this.shape_7.setTransform(-0.0875,-46.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(15).p("AshG2QAAlMDrjqQDrjqFLAAQFMAADrDqQDrDqAAFM");
	this.shape_8.setTransform(0,-46.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).wait(71));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-108.4,-117.8,196.10000000000002,182.7);


(lib.checkMark_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// checkMark_anim
	this.instance = new lib.checkMark_anim("synched",0,false);
	this.instance.setTransform(35.3,-51.75,1,1,0,0,0,15.8,15.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(78).to({startPosition:78},0).to({_off:true},1).wait(281));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_purposeBuilt();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:19.65,alpha:1},8,cjs.Ease.quadOut).wait(70).to({_off:true},1).wait(281));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-41,-132.7,1184.4,157.39999999999998);


(lib.gauge_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_10
	this.instance = new lib.gauge_anim("synched",0,false);
	this.instance.setTransform(22.45,-64.8,1,1,0,0,0,0,-38.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(46).to({startPosition:20},0).wait(18).to({startPosition:20},0).wait(8).to({startPosition:28},0).to({_off:true},1).wait(287));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_industrialLevel();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(64).to({_off:true},1).wait(287));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84.5,-143.8,1119.6,146.60000000000002);


// stage content:
(lib.Epson_DyeSub_V3_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// Epson_Logo
	this.instance = new lib.Epson_Logo_1();
	this.instance.setTransform(80.75,40.55,0.8039,0.8039);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},5).wait(355));

	// ctaBtn_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_352 = new cjs.Graphics().p("Aj+BXQgVAAAAgUIAAAAIAAiFQAAgUAVAAIAAAAIH9AAQAVAAAAAUIAAAAIAACFQAAAUgVAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(352).to({graphics:mask_graphics_352,x:285.6582,y:23.9585}).wait(8));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.1,-10.9,14.2,10.8).s().p("AoLGHIL8vmIEbDZIr8Pmg");
	this.shape_1.setTransform(244.075,3.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.1,-10.9,14.2,10.8).s().p("AoLGHIL8vnIEbDZIr8Pog");
	this.shape_2.setTransform(247.35,5.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.1,-10.9,14.3,10.9).s().p("AoNGJIL/vqIEcDaIr+Ppg");
	this.shape_3.setTransform(257.15,11.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.2,-10.9,14.3,10.9).s().p("AoPGKIMCvuIEdDbIsBPug");
	this.shape_4.setTransform(273.525,21.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.3,-11,14.4,11).s().p("AoSGMIMGvzIEfDcIsGPzg");
	this.shape_5.setTransform(294.825,33.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.4,-11,14.4,11).s().p("AoUGNIMIv3IEhDdIsJP4g");
	this.shape_6.setTransform(311.225,42.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.4,-11.1,14.5,11).s().p("AoWGOIMLv5IEiDdIsMP6g");
	this.shape_7.setTransform(321.025,48.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.5,-11.1,14.4,11).s().p("AoWGPIMLv7IEiDeIsMP7g");
	this.shape_8.setTransform(324.3,50.475);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},352).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).wait(1));

	// ctaBtn
	this.instance_1 = new lib.ctaBtn();
	this.instance_1.setTransform(285.7,23.95,0.3393,0.3393,0,0,0,0.1,0);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(348).to({_off:false},0).to({alpha:1},6).wait(6));

	// txt_sureColor_f10070
	this.instance_2 = new lib.txt_sureColor_f10070_endFrame();
	this.instance_2.setTransform(93.85,27.5,0.8983,0.8983,0,0,0,12.8,-192.2);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(345).to({_off:false},0).to({y:22.5,alpha:1},6,cjs.Ease.quadOut).wait(9));

	// printer_mc
	this.instance_3 = new lib.printer_mc();
	this.instance_3.setTransform(254.7,23.05,0.1616,0.1616);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(343).to({_off:false},0).to({scaleX:0.1192,scaleY:0.1192,x:205.2,alpha:1},6,cjs.Ease.quadOut).wait(11));

	// txt_toDyeFor
	this.instance_4 = new lib.txt_humor();
	this.instance_4.setTransform(157.25,201.4,1,1,0,0,0,-2,6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(313).to({_off:false},0).to({y:192.35,alpha:1},6,cjs.Ease.quadOut).wait(19).to({alpha:0},6).to({_off:true},1).wait(15));

	// txt_toDyeFor
	this.instance_5 = new lib.txt_toDyeFor();
	this.instance_5.setTransform(157.25,201.4,1,1,0,0,0,-2,6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(286).to({_off:false},0).to({y:179.35,alpha:1},5,cjs.Ease.quadOut).wait(22).to({y:173.75},6,cjs.Ease.quadOut).wait(19).to({alpha:0},6).to({_off:true},1).wait(15));

	// printer_mc
	this.instance_6 = new lib.printer_mc();
	this.instance_6.setTransform(385.2,23.05,0.1616,0.1616);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(283).to({_off:false},0).to({x:254.7},8,cjs.Ease.quadInOut).to({_off:true},52).wait(17));

	// shield_animation
	this.instance_7 = new lib.shield_animation("synched",0,false);
	this.instance_7.setTransform(91.05,63.55,0.315,0.315,0,0,0,0,49.4);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(216).to({_off:false},0).wait(67).to({mode:"single",startPosition:49},0).to({y:14.05},7,cjs.Ease.quadInOut).to({_off:true},1).wait(69));

	// checkMark_animation
	this.instance_8 = new lib.checkMark_animation("synched",0,false);
	this.instance_8.setTransform(92.05,63.55,0.315,0.315,0,0,0,0.1,49.4);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(133).to({_off:false},0).wait(79).to({mode:"single",startPosition:49},0).to({y:13.55},6,cjs.Ease.quadInOut).to({_off:true},1).wait(141));

	// gauge_animation
	this.instance_9 = new lib.gauge_animation("synched",0,false);
	this.instance_9.setTransform(90.8,64.65,0.3149,0.3149,0,0,0,0,49.7);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(56).to({_off:false},0).wait(73).to({mode:"single",startPosition:49},0).to({y:17.65},6,cjs.Ease.quadInOut).to({_off:true},1).wait(224));

	// txt_sureColor_f10070
	this.instance_10 = new lib.txt_sureColor_f10070();
	this.instance_10.setTransform(149.05,222.95);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(19).to({_off:false},0).to({y:208.95,alpha:1},7,cjs.Ease.quadOut).wait(23).to({alpha:0},6).to({_off:true},1).wait(304));

	// printer_mc
	this.instance_11 = new lib.printer_mc();
	this.instance_11.setTransform(149.2,76.6,0.3784,0.3784);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({y:52.6,alpha:1},7,cjs.Ease.quadOut).wait(5).to({scaleX:0.1627,scaleY:0.1627,x:256.2,y:23.05},7,cjs.Ease.quadInOut).wait(30).to({alpha:0},6).to({_off:true},1).wait(304));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(95.2,-27.1,356.90000000000003,161.7);
// library properties:
lib.properties = {
	id: '3E1D9D289AAA471FB8DD4F28FE5CF1AF',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Epson_Logo.png", id:"Epson_Logo"},
		{src:"projector_image.jpg", id:"projector_image"},
		{src:"shield_icon.png", id:"shield_icon"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3E1D9D289AAA471FB8DD4F28FE5CF1AF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;