(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,258,96);


(lib.Image_01 = function() {
	this.initialize(img.Image_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,393);


(lib.Image_02 = function() {
	this.initialize(img.Image_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,299,384);


(lib.Image_03 = function() {
	this.initialize(img.Image_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,299,384);


(lib.Image_04 = function() {
	this.initialize(img.Image_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,299,384);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_celebratingTenYears = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3FA1C7").s().p("AgKAwIgMgFIgJgGIgHgHIATgQQAEAHAGADQAGAEAHgBQAGAAADgCQADgDAAgEIgBgDIgEgDIgGgCIgIgCIgKgDIgKgFQgEgCgDgFQgDgFAAgHQAAgGADgFQACgGAFgDQAEgFAHgCQAGgCAHAAIAMABQAFABAFACIAIAGIAIAHIgSAOQgEgFgFgDQgEgDgIAAQgEAAgDACQgDADAAADIABAEIAEADIAFACIAIABIALADIAKAFQAFACACAFQADAFAAAHQAAAIgCAFQgDAGgFAEQgFAEgGACQgHADgIAAQgHAAgGgBg");
	this.shape.setTransform(82.475,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#3FA1C7").s().p("AAOAwIgNgdIgRAAIAAAdIgXAAIAAhfIApAAQAIABAGACQAHADAFAEQAEAEACAGQADAHAAAGQAAAKgEAFQgEAIgIAEIATAjgAgQgBIAQAAQAHAAAEgDQADgEAAgFQAAgGgDgDQgEgEgHAAIgQAAg");
	this.shape_1.setTransform(73.45,-0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#3FA1C7").s().p("AAXAwIgFgPIgjAAIgFAPIgXAAIAjhfIAVAAIAjBfgAALAOIgLggIgKAgIAVAAg");
	this.shape_2.setTransform(63.1,-0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#3FA1C7").s().p("AggAwIAAhfIBBAAIAAAVIgqAAIAAAQIAqAAIAAAUIgqAAIAAAQIAqAAIAAAWg");
	this.shape_3.setTransform(53.525,-0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#3FA1C7").s().p("AgKAwIAAgpIggg2IAZAAIARAjIASgjIAZAAIggA3IAAAog");
	this.shape_4.setTransform(44.15,-0.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#3FA1C7").s().p("AgOAuQgHgCgFgGQgFgGgDgJQgCgJAAgNIAAgDQAAgMADgJQADgJAFgFQAFgGAHgCQAGgDAHAAQAIAAAHADQAGACAGAGQAFAFADAJQACAJAAAMIAAADQAAAOgCAJQgDAJgFAFQgFAGgHACQgHADgIAAQgHAAgHgDgAgFgZQgDABgCADIgDAHIgBANIAAACIABANQABAFACADQACADADABQADABACAAQAEAAACgBQADgBACgDQACgDABgFIABgNIAAgCIgBgNQgBgFgCgDIgFgEIgGgBQgCAAgDACg");
	this.shape_5.setTransform(30.425,-0.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#3FA1C7").s().p("AAAAwIAAg9QgCAFgFADQgFACgHABIgDAAIAAgXIABAAQALABAGgGQAFgFAAgMIAWAAIAABfg");
	this.shape_6.setTransform(22.125,-0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#3FA1C7").s().p("AgSAtQgJgEgGgHQgHgHgDgJQgEgIAAgKQAAgJAEgJQAEgJAGgHQAGgGAJgEQAJgEAKAAQAOAAAKAFQAKAFAHAJIgTAOQgEgGgFgDQgFgDgIAAQgEAAgFADQgFACgDADQgEAEgCAFQgCAFAAAFQAAAGACAFQACAFADADQAEAEAFACQAFACAFAAQAIAAAFgEQAGgEACgHIgZAAIAAgUIAyAAIAAAKQAAAJgDAJQgEAIgGAHQgGAGgIAEQgJAEgKAAQgLAAgJgEg");
	this.shape_7.setTransform(9.125,-0.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#3FA1C7").s().p("AASAwIgkg7IAAA7IgVAAIAAhfIAXAAIAjA4IAAg4IAWAAIAABfg");
	this.shape_8.setTransform(-1.9,-0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#3FA1C7").s().p("AgKAwIAAhfIAVAAIAABfg");
	this.shape_9.setTransform(-9.5,-0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#3FA1C7").s().p("AgKAwIAAhKIgaAAIAAgVIBJAAIAAAVIgaAAIAABKg");
	this.shape_10.setTransform(-16.575,-0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#3FA1C7").s().p("AAXAwIgFgPIgjAAIgFAPIgXAAIAjhfIAVAAIAjBfgAALAOIgLggIgKAgIAVAAg");
	this.shape_11.setTransform(-26.5,-0.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#3FA1C7").s().p("AAOAwIgNgdIgRAAIAAAdIgXAAIAAhfIApAAQAIABAGACQAHADAFAEQAEAEACAGQADAHAAAGQAAAKgEAFQgEAIgIAEIASAjgAgQgBIAQAAQAHAAAEgDQADgEAAgFQAAgGgDgDQgEgEgHAAIgQAAg");
	this.shape_12.setTransform(-36.35,-0.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#3FA1C7").s().p("AgkAwIAAhfIAlAAQARAAAJAIQAIAGAAAOQAAAGgDAFQgCAEgEADQAFADADAEQADAFAAAHQAAAPgJAIQgLAGgQABgAgOAbIAPAAQAHAAADgCQADgCAAgFQAAgFgDgBQgDgDgHAAIgPAAgAgOgKIAQAAQAFABADgDQADgDgBgEQABgDgDgDQgDgCgFAAIgQAAg");
	this.shape_13.setTransform(-46.15,-0.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#3FA1C7").s().p("AggAwIAAhfIBBAAIAAAVIgqAAIAAAQIAqAAIAAAUIgqAAIAAAQIAqAAIAAAWg");
	this.shape_14.setTransform(-55.425,-0.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#3FA1C7").s().p("AgfAwIAAhfIAXAAIAABJIAoAAIAAAWg");
	this.shape_15.setTransform(-64.1,-0.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#3FA1C7").s().p("AggAwIAAhfIBBAAIAAAVIgqAAIAAAQIAqAAIAAAUIgqAAIAAAQIAqAAIAAAWg");
	this.shape_16.setTransform(-72.875,-0.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#3FA1C7").s().p("AgRAtQgJgEgGgHQgGgGgEgJQgDgJAAgKQAAgKADgJQAEgIAGgHQAHgHAJgDQAJgEAJAAQAHAAAGACQAHABAFADIAKAIIAIAJIgUANQgEgGgFgEQgGgEgIAAQgEAAgFACQgFACgDAEIgFAIQgCAFAAAFQAAAFACAFQABAFAEADQADAEAFACQAEACAFAAQAJAAAFgEQAGgFADgGIAVALQgDAGgEAFIgKAIQgGAEgGACQgHACgIAAQgKAAgJgEg");
	this.shape_17.setTransform(-82.725,-0.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_celebratingTenYears, new cjs.Rectangle(-108.5,-10.5,217.1,21.1), null);


(lib.txt_qualityCare = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiFHoQgdgMgVgWQgVgVgNgcQgMgdAAghQAAghAMgcQANgdAVgVQAVgWAdgMQAcgNAhAAQAhAAAcANQAcAMAVAWQAWAVAMAdQAMAcAAAhQAAAhgMAdQgMAcgWAVQgVAWgbAMQgdAMghAAQghAAgcgMgAhpEIQgPAHgLAMQgLALgHAQQgGAPAAASQAAASAGAPQAGAPALAMQAMAMAPAGQAPAHASAAQASAAAPgHQAQgGALgMQALgMAFgPQAGgPAAgSQAAgSgGgPQgFgQgLgLQgMgMgPgHQgPgHgSAAQgSAAgPAHgAuoHuQgSgGgMgLQgNgMgGgPQgHgPAAgTQAAgPAFgMQAFgMAIgKQAIgLALgIIAWgQIgMgRIgJgQIgEgQIgBgUQAAgPAGgPQAHgOAMgLQALgKAQgGQAQgHASAAQASAAAQAGQAPAGAMALQAMAKAGAOQAHAOAAAQQAAANgEALQgEALgHAJQgGAKgJAIIgUAPIAeAdIAwg4IBTAAIhUBjIBXBVIhfAAIgkgjIgXATQgLAHgKAFQgLAFgMACIgYABQgXAAgSgGgAuPGIQgIAIAAALQAAAMAIAHQAIAIANAAQALAAAJgEQAJgFAMgLIgrgrQgMAIgHAJgAt4D5QgGAFAAAJQAAAJADAIQAEAHAKALQALgIAIgIQAHgJAAgKQAAgJgHgFQgGgGgJAAQgJAAgGAGgAGmHwIAAkyIDUAAIAABEIiLAAIAAAyICLAAIAABEIiLAAIAAA0ICLAAIAABEgAEwHwIgrhcIg6AAIAABcIhJAAIAAkyICEAAQAcAAAVAIQAVAIAPAPQAPAOAHATQAIATAAAWQAAAdgNAYQgOAYgXANIA6BvgADLFSIA1AAQAYAAALgMQALgMAAgRQAAgTgLgLQgLgKgYAAIg1AAgAlGHwIAAjCIhRBtIhQhtIAADCIhIAAIAAkyIBGAAIBSByIBWhyIBCAAIAAEygALXCZQgUgEgRgJQgRgIgNgLQgNgLgLgNIA/gzQAOAVASALQATAMAaAAQASAAAKgIQAKgIAAgNQAAgIgEgFQgEgFgIgDIhSgYQgRgFgOgKQgOgJgIgQQgJgPAAgYQAAgUAIgRQAJgRAOgNQAPgNAUgHQAVgHAZAAQAVAAARAEQARADAPAHQAOAHANAKIAZAYIg7AuQgLgSgPgJQgQgKgXAAQgTAAgJAJQgIAIAAALQAAAHAEAEQAEAFAJADIBQAWQARAFAPALQAOAJAKAQQAJAQAAAZQAAAWgJASQgJASgPANQgQAOgVAHQgWAIgZAAQgaAAgUgFgADOCZQgUgEgRgJQgRgIgNgLQgNgLgLgNIA/gzQAOAVASALQATAMAaAAQASAAAKgIQAKgIAAgNQAAgIgEgFQgEgFgIgDIhSgYQgRgFgOgKQgOgJgIgQQgJgPAAgYQAAgUAIgRQAJgRAOgNQAPgNAUgHQAVgHAZAAQAVAAARAEQARADAPAHQAOAHANAKIAZAYIg7AuQgLgSgPgJQgQgKgXAAQgTAAgJAJQgIAIAAALQAAAHAEAEQAEAFAJADIBQAWQARAFAPALQAOAJAKAQQAJAQAAAZQAAAWgJASQgJASgPANQgQAOgVAHQgWAIgZAAQgaAAgUgFgAhDCZQgUgEgRgJQgRgIgNgLQgNgLgLgNIA/gzQAOAVASALQATAMAaAAQASAAAJgIQAKgIAAgNQAAgIgEgFQgEgFgIgDIhRgYQgRgFgOgKQgOgJgIgQQgJgPAAgYQAAgUAIgRQAJgRAOgNQAPgNAUgHQAVgHAZAAQAVAAAQAEQARADAPAHQAOAHANAKIAZAYIg7AuQgLgSgPgJQgPgKgXAAQgTAAgJAJQgIAIAAALQAAAHAEAEQAEAFAJADIBPAWQARAFAPALQAOAJAKAQQAJAQAAAZQAAAWgJASQgJASgPANQgQAOgVAHQgWAIgYAAQgaAAgUgFgAuHCSQgdgNgUgVQgVgVgLgdQgMgdAAghQAAggAMgdQAMgdAVgVQAVgVAdgMQAcgMAiAAQAWAAAVAFQAUAGASAKQARAKAPAOQAOAOAKARIhAAoQgLgUgSgMQgSgMgZAAQgTAAgPAGQgPAHgLAMQgLALgGAQQgGAQAAAQQAAASAGAPQAGAQALALQALAMAOAGQAPAHATAAQAcAAASgOQATgOAJgWIBEAlQgKASgOAQQgOAQgSAMQgSALgWAHQgVAGgZAAQgjAAgdgMgAGZCaIAAkyIDTAAIAABEIiKAAIAAAzICKAAIAABDIiKAAIAAA0ICKAAIAABEgAjnCaIgQguIh1AAIgQAuIhKAAIBxkyIBGAAIByEygAkOAsIgkhmIgkBmIBIAAgAqcCaIAAkyIBJAAIAADsICGAAIAABGgAJBi8QgUgFgQgIQgRgIgNgMQgOgLgKgNIA/gyQANAUATAMQASALAaAAQATAAAKgIQAJgIAAgNQAAgHgDgFQgEgFgIgEIhSgXQgRgGgOgKQgOgKgJgPQgJgQAAgXQAAgUAJgSQAIgRAPgNQAOgMAVgHQAVgHAYAAQAVAAASADQARAEAOAHQAPAHANAKIAZAXIg7AuQgLgRgQgKQgPgJgXAAQgTAAgJAIQgJAJAAAKQAAAHAFAFQAEAFAIADIBQAVQASAGAOAKQAPAKAJAQQAJAQAAAZQAAAWgJASQgIATgQANQgQANgVAIQgVAHgaAAQgZAAgVgEgACYjEQgcgMgVgWQgVgVgLgcQgLgdAAghQAAgiALgcQAMgdAVgVQAVgWAdgMQAdgMAiAAQAWAAAUAGQAUAFASAKQASAKAOAOQAOAOAKARIhAApQgKgVgSgMQgTgMgZAAQgSAAgPAHQgQAHgKALQgLAMgGAQQgHAPAAASQAAASAGAPQAGAPALAMQALALAPAHQAPAHASAAQAcAAATgOQASgOAKgWIBDAkQgJATgPAQQgOAQgSALQgSAMgVAGQgWAGgYAAQgjAAgegMgAMRi8IAAkyIDUAAIAABEIiLAAIAAAyICLAAIAABEIiLAAIAAA0ICLAAIAABEgAGKi8IAAkyIBKAAIAAEygAgki8IgrhcIg5AAIAABcIhJAAIAAkyICDAAQAcAAAVAIQAWAIANAPQAPAOAIATQAHATAAAWQAAAdgNAYQgNAYgWANIA4BvgAiIlaIA1AAQAXAAAMgMQALgMAAgRQAAgTgMgLQgLgKgXAAIg1AAgAnXi8IAAkyIDTAAIAABEIiKAAIAAAyICKAAIAABEIiKAAIAAA0ICKAAIAABEgApGi8Ig0hfIg1BfIhRAAIBdieIhXiUIBPAAIAyBZIAzhZIBPAAIhZCWIBdCcgAvdi8IAAkyIDUAAIAABEIiLAAIAAAyICLAAIAABEIiLAAIAAA0ICLAAIAABEg");
	this.shape.setTransform(-15.975,1.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_qualityCare, new cjs.Rectangle(-115.6,-48.9,199.3,100), null);


(lib.txt_earlyDetection = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ANaKXQgVgFgRgIQgRgJgOgLQgNgMgLgNIBBg0QANAVATAMQATAMAbAAQATAAAKgJQAKgIAAgNQgBgHgDgGQgEgFgJgEIhTgYQgRgFgPgKQgOgLgJgPQgJgQAAgZQAAgUAJgSQAIgRAPgNQAPgNAVgIQAWgHAYAAQAWAAASAEQASADAOAIQAPAHANAKIAaAYIg8AvQgLgSgQgJQgRgKgXAAQgUAAgJAJQgJAIAAALQABAHAEAFQAEAFAJADIBSAWQASAGAPAKQAOALAKAQQAKAQAAAaQgBAWgIATQgKATgPANQgQAOgWAIQgWAHgaAAQgaAAgVgEgAEoKPQgegNgVgWQgVgVgMgeQgLgdAAgiQAAgiAMgeQAMgdAVgWQAWgVAegNQAdgMAjAAQAXAAAUAGQAVAFASAKQASAKAPAPQAOAOAKARIhCAqQgKgVgSgMQgTgMgaAAQgTAAgQAGQgPAHgLAMQgLAMgHAQQgFAQAAASQAAASAFAQQAHAQAKAMQALALAQAHQAPAHAUAAQAcAAASgOQAUgPAJgWIBGAlQgLATgOARQgOAQgSAMQgTAMgXAGQgWAGgYAAQglAAgdgMgAudKXQgWgFgQgIQgSgJgNgLQgNgMgMgNIBBg0QAOAVASAMQAUAMAaAAQATAAALgJQAJgIAAgNQAAgHgEgGQgDgFgJgEIhTgYQgSgFgPgKQgNgLgKgPQgIgQgBgZQAAgUAJgSQAJgRAOgNQAPgNAVgIQAWgHAZAAQAVAAATAEQARADAPAIQAOAHANAKIAaAYIg8AvQgLgSgQgJQgQgKgYAAQgTAAgJAJQgJAIAAALQAAAHAEAFQAFAFAJADIBSAWQARAGAPAKQAPALAJAQQAKAQAAAaQAAAWgJATQgJATgQANQgQAOgWAIQgWAHgaAAQgaAAgUgEgAIUKXIAAk6IDZAAIAABGIiPAAIAAA0ICPAAIAABFIiPAAIAAA2ICPAAIAABFgABiKXIAAk6IBLAAIAAE6gAhuKXIh0k6IBOAAIBKDUIBKjUIBNAAIhzE6gAkvKXIgsheIg6AAIAABeIhLAAIAAk6ICHAAQAcAAAWAJQAWAJAPAOQAPAPAIATQAIAUgBAWQAAAegNAZQgOAYgXAOIA6BxgAmVH1IA2AAQAZAAALgMQALgMAAgSQAAgTgLgLQgMgLgYAAIg2AAgArdKXIAAk6IDYAAIAABGIiOAAIAAA0ICOAAIAABFIiOAAIAAA2ICOAAIAABFgAC9E6QgegMgVgWQgVgWgNgdQgMgeAAghQAAgiAMgdQANgdAVgWQAVgWAegNQAdgNAiAAQAhAAAeANQAdANAVAWQAXAWAMAdQANAdAAAiQAAAhgNAeQgNAdgVAWQgWAWgdAMQgdANgiAAQgiAAgdgNgADaBVQgQAHgLAMQgLAMgHAQQgGAQAAASQAAASAGAQQAHAPALAMQALAMAQAHQAQAHASAAQATAAAPgHQAPgHAMgMQAMgMAGgPQAGgQAAgSQAAgSgGgQQgGgQgMgMQgMgMgQgHQgPgHgSAAQgSAAgQAHgAqZE/QgYgJgQgQQgQgRgJgYQgJgXAAgfIAAi+IBMAAIAAC+QAAAbANAOQAOAOAYAAQAWAAAPgOQAOgOgBgbIAAi+IBNAAIAAC+QgBAfgIAXQgJAYgRARQgQAQgYAJQgYAIgcAAQgdAAgYgIgAujFCQgUgEgSgJQgQgIgOgMQgNgLgLgOIBAgzQANAVAUALQASAMAbAAQAUAAAJgIQAKgIAAgNQAAgIgDgFQgFgFgIgEIhUgYQgRgGgPgKQgNgKgJgQQgKgQABgYQAAgVAIgRQAIgSAPgNQAQgNAUgHQAWgHAZAAQAWAAARADQASAEAPAHQAPAHANALIAaAYIg9AuQgLgRgQgKQgQgJgYAAQgTAAgJAIQgJAJAAAKQAAAIAFAEQAEAFAIADIBSAWQATAGAOALQAPAKAKAQQAJARAAAZQAAAXgJASQgJATgQAOQgQAOgWAHQgWAIgaAAQgZAAgWgFgAMjFDIAAj1IhVAAIAAhFIDyAAIAABFIhUAAIAAD1gAJpFDIgshfIg7AAIAABfIhKAAIAAk6ICHAAQAbAAAWAIQAXAJAOAPQAPAOAJAUQAHAUAAAWQAAAegOAYQgNAZgXANIA6BygAICChIA3AAQAYAAALgNQALgMAAgSQAAgTgLgLQgMgLgXAAIg3AAgAipFDIAAk6IB+AAQAbAAAVAJQAWAJARAQQAPAQAJAVQAIAWAAAYQAAAYgIAVQgJAVgPARQgQAQgXAJQgVAKgcAAIgyAAIAABPgAheCuIAuAAQAWAAANgNQANgNABgWQgBgWgNgOQgNgNgWAAIguAAgAm/FDIAAk6IB9AAQAcAAAVAJQAXAJAQAQQAQAQAIAVQAJAWAAAYQAAAYgJAVQgIAVgQARQgPAQgXAJQgXAKgbAAIgzAAIAABPgAl1CuIAvAAQAVAAAOgNQAOgNAAgWQAAgWgOgOQgOgNgVAAIgvAAgAEXgRIAAiDIhni3IBRAAIA9BxIA7hxIBQAAIhnC4IAACCgAAEgRIAAk6IBLAAIAADyICJAAIAABIgAhvgRIAAk6IBMAAIAAE6gAjvgRIAAjHIhSBvIhShuIAADGIhKAAIAAk6IBHAAIBVB2IBXh2IBEAAIAAE6gAo8gRIgRgvIh3AAIgRAvIhLAAIB0k6IBIAAIBzE4IAAACgApjiBIglhpIgmBpIBLAAgAvmgRIAAk6IDXAAIAABHIiNAAIAAA4ICNAAIAABFIiNAAIAAB2gAgRlgIAAh5IhnAAIAAB5IhLAAIAAk6IBLAAIAAB3IBnAAIAAh3IBKAAIAAE6gAl4lgIAAj1IhWAAIAAhFIDzAAIAABFIhUAAIAAD1gAoylgIAAk6IBMAAIAAE6gArklgIg3jGIg2DGIhLAAIhXk6IBNAAIAxDBIA2jBIBIAAIA2DCIAyjCIBLAAIhYE6g");
	this.shape.setTransform(-12.4,18.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_earlyDetection, new cjs.Rectangle(-114.8,-47.8,204.89999999999998,133.5), null);


(lib.txt_cancerHatesUs = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("An+HrQgTgFgRgHQgPgJgNgKQgNgMgLgNIA9gwQANATATALQARAMAaAAQASAAAKgIQAKgIAAgMQgBgIgEgEQgDgFgIgEIgTgHIg9gQQgQgFgOgKQgNgJgKgQQgIgPAAgXQAAgTAIgRQAJgRAOgNQAOgMAUgHQAVgHAXAAQAVAAARAEQAQADAPAHQAOAHANAKIAYAWIg6AtQgKgRgQgIQgPgKgWAAQgTAAgIAIQgJAJAAAJQAAAIAFAEQAEAFAIADIBOAVQARAFAOAKQAOALAKAPQAIAPABAZQAAAVgJASQgIASgQANQgPANgVAHQgVAIgZAAQgYgBgVgEgAsdHoQgWgJgQgQQgQgPgIgXQgJgWAAgdIAAi2IBJAAIAAC2QAAAZANAOQANANAWAAQAWAAANgNQANgOAAgZIAAi2IBJAAIAAC2QABAdgKAWQgIAXgPAPQgQAQgXAJQgWAHgbABQgdgBgWgHgAEICYQgUgEgQgJQgQgHgNgMQgNgLgLgNIA+gxQANAVASAKQASAMAZAAQATAAAKgIQAJgIAAgMQAAgHgEgGQgEgEgHgEIgTgHIg+gQQgQgFgOgKQgNgJgJgPQgJgPAAgXQAAgUAJgRQAIgQAOgMQAPgNATgHQAVgHAYAAQAUAAASAEQAQADAOAHQAPAHAMAKIAZAXIg6AtQgLgRgPgJQgPgKgXAAQgSAAgJAJQgIAHgBALQABAGAEAFQAFAFAHADIBPAUQARAGAOAKQAOAJAJAQQAJAPAAAYQAAAWgIASQgJARgQANQgOAOgWAHQgVAIgYgBQgZAAgUgEgAg9CZIAAkrIDOAAIAABDIiIAAIAAAxICIAAIAABBIiIAAIAAAzICIAAIAABDgAjyCZIAAjoIhRAAIAAhDIDnAAIAABDIhQAAIAADogAl8CZIgPgtIhzAAIgQAtIhIAAIBvkrIBFAAIBvErgAmiAuIgjhkIgjBkIBGAAgAq5CZIAAhzIhiAAIAABzIhIAAIAAkrIBIAAIAABxIBiAAIAAhxIBHAAIAAErgACCjHQgcgMgUgVQgUgUgMgdQgKgcgBgfQAAgiAMgcQALgcAVgUQAUgVAcgMQAdgLAhAAQAVgBAVAGQATAGARAJQASAKANAOQAOANAKARIg/AnQgKgUgSgLQgRgMgZAAQgRAAgPAGQgPAHgLALQgKAMgHAPQgFAPgBASQABAQAFAPQAGAPALALQALAMAOAGQAPAHARAAQAcAAARgOQATgOAJgUIBCAiQgKATgOAQQgNAPgRALQgSAMgVAGQgVAGgYAAQgjAAgcgMgAsPjHQgcgMgUgVQgVgUgKgdQgLgcAAgfQAAgiALgcQALgcAVgUQAVgVAcgMQAcgLAhAAQAWgBATAGQAUAGARAJQARAKAPAOQANANAKARIg+AnQgLgUgSgLQgRgMgYAAQgTAAgPAGQgOAHgLALQgKAMgHAPQgFAPAAASQAAAQAFAPQAGAPAKALQALAMAPAGQAOAHATAAQAaAAATgOQASgOAJgUIBCAiQgKATgOAQQgNAPgSALQgRAMgVAGQgVAGgYAAQgiAAgdgMgAMci/IgqhaIg5AAIAABaIhHAAIAAksICBAAQAbAAAVAJQAVAIAOAOQAPAOAHASQAHAUAAAVQAAAcgNAXQgNAXgWANIA3BtgAK5laIA0AAQAYAAALgLQAKgMAAgRQAAgSgLgKQgLgLgXAAIg0AAgAFyi/IAAksIDPAAIAABDIiHAAIAAAxICHAAIAABCIiHAAIAAAzICHAAIAABDgAhFi/Ih2i8IAAC8IhEAAIAAksIBLAAIBwC0IAAi0IBEAAIAAEsgAlji/IgPgtIhzAAIgQAtIhIAAIBvksIBFAAIBuEsgAmJkqIgjhlIgjBlIBGAAg");
	this.shape.setTransform(-27.15,-0.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_cancerHatesUs, new cjs.Rectangle(-114.6,-50.2,174.89999999999998,99.1), null);


(lib.txt_cancerHatesFighters = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AOOHvQgVgFgRgIQgRgIgNgMQgOgMgLgNIBBgzQANAVATALQATAMAbAAQATAAAKgJQAKgIAAgMQAAgIgEgGQgEgEgIgFIhUgXQgRgGgPgKQgOgKgJgQQgJgQAAgZQAAgUAJgSQAIgRAPgNQAPgNAVgHQAWgIAZABQAVgBASAEQASADAPAIQAOAHANAKIAaAYIg8AvQgLgSgQgJQgQgKgYAAQgTAAgJAJQgJAIAAALQAAAIAEAEQAFAFAIADIBSAWQASAGAPALQAPAKAJAQQAKAQAAAaQAAAWgJATQgJATgQANQgQAPgWAHQgWAIgaAAQgaAAgVgFgAEvHnQgegMgVgXQgWgVgMgdQgNgeAAghQAAgiANgdQAMgdAWgXQAVgWAegMQAdgNAiAAQAhAAAdANQAeAMAVAWQAWAXANAdQAMAdAAAiQAAAhgMAeQgNAdgVAVQgWAXgdAMQgdANgiAAQgiAAgdgNgAFMECQgQAGgLANQgLAMgHAQQgGAPAAATQAAARAGARQAGAPAMAMQALAMAQAHQAPAHATAAQASAAAQgHQAPgHAMgMQALgMAHgPQAGgRAAgRQAAgTgGgPQgHgQgLgMQgMgNgQgGQgPgHgSAAQgTAAgPAHgALdHvIgsheIg7AAIAABeIhKAAIAAk6ICHAAQAcAAAWAJQAWAJAPAPQAPAOAIAUQAHAUAAAVQAAAfgNAYQgOAZgXANIA6BxgAJ2FNIA3AAQAYAAALgMQAMgMAAgSQAAgTgMgLQgLgLgYAAIg3AAgABjHvIAAk6IBMAAIAAE6gAgPHvIgsheIg7AAIAABeIhKAAIAAk6ICHAAQAcAAAWAJQAVAJAPAPQAPAOAIAUQAHAUAAAVQAAAfgNAYQgOAZgXANIA6BxgAh2FNIA3AAQAYAAALgMQAMgMAAgSQAAgTgMgLQgLgLgYAAIg3AAgAktHvIgsheIg7AAIAABeIhLAAIAAk6ICHAAQAcAAAWAJQAWAJAPAPQAPAOAIAUQAIAUAAAVQAAAfgOAYQgNAZgYANIA7BxgAmUFNIA2AAQAZAAALgMQALgMAAgSQAAgTgLgLQgMgLgYAAIg2AAgAo7HvIgRgvIh4AAIgQAvIhMAAIB0k6IBIAAIB1E6gApjF/IglhpIglBpIBKAAgAuiHvIg3jGIg2DGIhLAAIhWk6IBMAAIAxDCIA3jCIBHAAIA3DDIAxjDIBLAAIhXE6gAi9CSQgegMgVgWQgVgVgLgeQgMgdAAghQAAgiAMgeQAMgeAWgVQAVgWAegMQAdgNAjAAQAXAAAUAHQAVAFASAKQASAKAPAOQANAPALARIhBAqQgLgVgSgMQgTgMgagBQgTABgPAGQgQAHgLAMQgLAMgGAQQgGAQAAASQAAARAGAQQAGAPALANQALALAPAHQAQAHATAAQAcAAATgPQATgOAKgWIBEAlQgKATgOARQgOAPgSAMQgTAMgWAHQgWAGgZAAQgkAAgegNgAxMCSQgegMgVgWQgVgVgMgeQgLgdAAghQAAgiAMgeQAMgeAVgVQAWgWAdgMQAegNAiAAQAXAAAVAHQAUAFATAKQASAKAOAOQAPAPAKARIhCAqQgKgVgTgMQgSgMgagBQgTABgQAGQgPAHgLAMQgLAMgHAQQgGAQAAASQAAARAGAQQAGAPALANQALALAQAHQAPAHATAAQAcAAATgPQATgOAKgWIBFAlQgKATgOARQgPAPgSAMQgSAMgXAHQgWAGgZAAQgkAAgdgNgAHiCbIgsheIg7AAIAABeIhLAAIAAk5ICHAAQAcAAAWAIQAWAJAPAPQAPAPAIATQAIAUAAAWQAAAegOAYQgNAYgYAOIA7BxgAF7gGIA2AAQAZAAALgNQALgMAAgRQAAgUgLgLQgMgKgYgBIg2AAgAAsCbIAAk5IDYAAIAABGIiOAAIAAAzICOAAIAABFIiOAAIAAA2ICOAAIAABFgAmCCbIh7jFIAADFIhIAAIAAk5IBOAAIB3C7IAAi7IBHAAIAAE5gAqcCbIgRgvIh4AAIgQAvIhMAAIB0k5IBIAAIB1E5gArEArIglhpIglBpIBKAAgABii0QgVgFgRgIQgRgJgNgLQgOgMgLgNIBBgzQANAUATAMQATAMAbAAQATAAAKgIQAKgJAAgMQAAgIgEgGQgEgFgIgEIhUgYQgRgFgPgKQgOgLgJgPQgJgQAAgZQAAgUAJgSQAIgRAPgNQAPgNAVgIQAWgGAZAAQAVgBASAEQASADAPAIQAOAHANAKIAaAZIg8AuQgLgSgQgJQgQgKgYAAQgTABgJAIQgJAJAAAKQAAAIAEAEQAFAFAIADIBSAWQASAGAPALQAPAKAJAQQAKAQAAAaQAAAWgJATQgJATgQANQgQAPgWAHQgWAIgaAAQgaAAgVgFgAPZi0IAAk6IDYAAIAABGIiOAAIAAA0ICOAAIAABFIiOAAIAAA2ICOAAIAABFgANni0IgsheIg7AAIAABeIhLAAIAAk6ICHAAQAcAAAWAJQAWAJAPAPQAPAOAIAUQAIAUAAAVQAAAegOAZQgNAZgYANIA7BxgAMAlWIA2AAQAZAAALgMQALgMAAgSQAAgTgLgLQgMgLgYAAIg2AAgAI1i0IAAk6IBMAAIAAE6gAEbi0IAAk6IB+AAQAbAAAWAKQAXAJAQAQQAQAQAIAVQAJAVAAAYQAAAZgJAUQgIAWgQAQQgQARgWAJQgXAKgcAAIgyAAIAABOgAFmlIIAvAAQAVAAAOgNQAOgNAAgXQAAgVgOgOQgOgNgVAAIgvAAgAhYi0Ih7jFIAADFIhIAAIAAk6IBOAAIB3C9IAAi9IBHAAIAAE6gAmRi0IAAk6IBMAAIAAE6gAr4i0IAAk6IDZAAIAABGIiOAAIAAA0ICOAAIAABFIiOAAIAAA2ICOAAIAABFgAuii0Ig3jGIg2DGIhLAAIhWk6IBMAAIAxDCIA3jCIBHAAIA3DDIAxjDIBLAAIhXE6g");
	this.shape.setTransform(4.575,-0.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_cancerHatesFighters, new cjs.Rectangle(-115.5,-50.8,240.2,99.9), null);


(lib.txt_advancedTreatment = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACtHrQgTgEgRgIQgQgIgNgLQgNgLgKgNIA9gxQANAUASALQASALAaAAQASAAAKgIQAJgIAAgMQAAgHgEgFQgDgFgIgEIgTgHIg9gQQgRgFgOgKQgNgJgJgPQgIgQAAgXQAAgTAIgRQAIgRAOgMQAPgNAUgHQAUgHAYAAQAVAAARAEQAQADAPAHQAOAHAMAKIAZAXIg6AtQgKgRgQgJQgPgKgWAAQgTAAgIAJQgJAIAAAKQAAAHAEAEQAFAFAIADIBOAVQARAFAOAKQAOALAJAPQAJAQAAAYQAAAVgIASQgJASgPANQgPANgVAIQgVAHgZAAQgZAAgUgFgAiKHsIAAksIBIAAIAADnICBAAIAABFgAjzHsIgPgtIhzAAIgPAtIhJAAIBvksIBFAAIBvEsgAlfGBIBHAAIgjhlgAoxHsIAAksIBIAAIAAEsgAqbHsIgrhaIg4AAIAABaIhHAAIAAksICBAAQAbAAAVAJQAVAIAOAOQAOAOAIASQAHATAAAVQAAAdgNAXQgNAXgWANIA3BtgAr+FRIA0AAQAXAAALgLQALgMAAgRQAAgSgLgLQgLgKgXAAIg0AAgAv7HsIAAjpIhRAAIAAhDIDnAAIAABDIhQAAIAADpgAJxCRQgcgMgUgVQgUgVgLgcQgLgcAAggQAAggALgcQAMgcAUgVQAVgUAcgMQAcgMAhAAQAWAAAUAGQATAFARAKQASAJAOAOQAOAOAJAQIg+AoQgLgUgRgMQgSgLgYAAQgSAAgPAGQgPAHgLALQgKALgGAQQgGAPAAAQQAAARAGAPQAFAPALALQALAMAOAGQAPAHASAAQAbAAASgOQASgOAJgVIBCAjQgJATgOAQQgOAPgRALQgSAMgVAGQgVAGgYAAQgiAAgdgMgAnqCYQgTgEgRgIQgQgIgNgLQgNgLgKgNIA9gxQANAUASALQASALAaAAQASAAAKgIQAJgIAAgMQAAgHgEgFQgDgFgIgEIgTgHIg9gQQgRgFgOgKQgNgIgJgPQgIgQAAgXQAAgTAIgRQAIgRAOgMQAPgNAUgHQAUgHAYAAQAVAAARAEQAQADAPAHQAOAHAMAKIAZAXIg6AtQgKgRgQgJQgPgKgWAAQgTAAgIAJQgJAIAAAKQAAAHAEAEQAFAFAIADIBOAVQARAFAOAKQAOAKAJAPQAJAQAAAYQAAAVgIASQgJASgPANQgPANgVAIQgVAHgZAAQgZAAgUgFgAQLCZIAAhzIhiAAIAABzIhIAAIAAkrIBIAAIAAByIBiAAIAAhyIBHAAIAAErgAG0CZIgqhaIg4AAIAABaIhIAAIAAkrICBAAQAbAAAVAJQAVAIAOAOQAPAOAHASQAIATAAAVQAAAdgOAWQgMAXgXANIA4BtgAFSgBIA0AAQAXAAALgLQAKgMAAgRQAAgSgLgLQgLgKgWAAIg0AAgAChCZIgPgtIhzAAIgPAtIhHAAIAAgBIBtkqIBFAAIBvErgAA1AuIBHAAIgjhkgAkaCZIAAkrIDPAAIAABDIiIAAIAAAxICIAAIAABBIiIAAIAAAzICIAAIAABDgAsvCZIAAkrIDPAAIAABDIiIAAIAAAxICIAAIAABBIiIAAIAAAzICIAAIAABDgAudCUIgrhaIg4AAIAABaIhHAAIAAkrICBAAQAbAAAVAJQAVAIAOAOQAOAOAIASQAHATAAAVQAAAdgNAWQgNAXgWANIA3BtgAwAgGIA0AAQAXAAALgLQALgMAAgRQAAgSgLgLQgLgKgXAAIg0AAgAtKi0IAAksIDPAAIAABDIiIAAIAAAxICIAAIAABCIiIAAIAAAzICIAAIAABDgAwAi0IAAjpIhRAAIAAhDIDnAAIAABDIhQAAIAADpgANSi7QgSgGgMgLQgMgLgHgPQgGgQAAgSQAAgOAFgMQAEgMAIgKQAIgKALgIIAVgQIgMgQIgIgPIgEgRIgCgSQAAgQAHgOQAHgOALgKQALgLAQgGQAPgGASAAQARAAAQAGQAPAGALAKQAMAKAGAOQAHANAAAQQAAANgEALQgEAKgHAJQgGAJgJAIIgTAPIAdAdIAvg3IBRAAIhSBgIBVBUIhdAAIgjgjIgWATQgLAHgKAFQgLAEgLACIgYACQgWAAgRgGgANqkfQgIAIAAAKQAAAMAIAHQAIAIAMAAQALAAAJgEQAJgFALgLIgqgqQgLAIgHAJgAOAmrQgGAFAAAJQAAAJAEAHQADAIAKAKQALgIAHgIQAHgIAAgKQAAgJgGgFQgGgFgJAAQgJAAgGAFgAG9jBQgdgNgUgVQgVgVgKgcQgLgcAAgfQAAggALgdQAMgcAUgUQAUgVAdgMQAcgMAiAAQArAAAgARQAgAQAVAcIg8AqQgLgRgRgJQgRgJgXAAQgRAAgPAHQgPAGgLAMQgMALgGAQQgHAQAAASQAAATAGAQQAHAPALAMQALALAQAHQAPAGATAAQAZAAASgNQASgMAHgWIhTAAIAAhCIChAAIAAAiQAAAdgKAbQgLAbgTAUQgTAUgbAMQgbAMggAAQglAAgdgMgADvi5Ih1i8IAAC8IhFAAIAAksIBLAAIBxC0IAAi0IBEAAIAAEsgAhBi5IAAksIBHAAIAAEsgAkCi5IAAjpIhRAAIAAhDIDnAAIAABDIhQAAIAADpgAoPi/QgTgEgRgIQgQgIgNgLQgNgLgKgNIA9gxQANAUASALQASALAaAAQASAAAKgIQAJgIAAgMQAAgHgEgFQgDgFgIgEIgTgHIg9gQQgRgFgOgKQgNgJgJgPQgIgQAAgXQAAgTAIgRQAIgRAOgMQAPgNAUgHQAUgHAYAAQAVAAARAEQAQADAPAHQAOAHAMAKIAZAXIg6AtQgKgRgQgJQgPgKgWAAQgTAAgIAJQgJAIAAAKQAAAHAEAEQAFAFAIADIBOAVQARAFAOAKQAOALAJAPQAJAQAAAYQAAAVgIASQgJASgPANQgPANgVAIQgVAHgZAAQgZAAgUgFg");
	this.shape.setTransform(-2.825,1.775);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_advancedTreatment, new cjs.Rectangle(-113.4,-47.8,221.2,99.19999999999999), null);


(lib.safeCare_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.749)").s().p("AhYFIQhmgZhGhOIgCgDIhyANIBtgtIAAABIAHAIIAAABQBCBSBlAcQBlAcBigoQBigpA1heQAzhcgNhoIgBgJIBuguIhaBJIAAAEQAEBYgnBQQgoBQhKAwQgbARgaALQg8AZg9AAQgnAAgogKgAhgEtQhmgdg/hVIAEgBQA/BTBjAcQBkAeBggoQBhgoAyhcQAyhbgOhmIADgBQANBZgkBTQglBThLAxQgcARgVAJQg4AXg5AAQgrAAgrgNgAmdDUIhYgmIBMgfIAnBfIABABIB3gNIi2BLgAgJEJIgCgbIALAAQAJgBABAKQAAAKgKAAIgEABIAAAHgAgFDzIAAAKIAFgBQAEAAAAgFQAAgFgEAAgAAMDtIALgCQAEAAADACQADACABAEQABAFgEADIAHAJIgGABIgGgIIgGABIACAJIgFABgAAXDwIgFABIABAJIAGgBQAFgBgBgFQgBgDgDAAIgCAAgAg7EFIADgbIASADIAAAFIgNgCIgBAGIANACIgBAEIgMgBIgBAGIAMACIAAAFgAhHECIgDgJIgFgCIgCAIIgFgBIAGgaIAKADQAKACgCAJQgBAFgGACIADALgAhODzIAFABQAFABABgEQABgFgFgBIgFgBgAgZEDQgEAAAAgEQAAgFAFABQAEAAAAAEQgBAEgDAAIgBAAgAAlDpIARgFIACAFIgNADIACAGIAMgDIACAEIgNAEIACAGIAMgEIABAFIgRAFgAhgD7IAAgFIgLgEIgDAEIgFgCIASgWIAFACIABAdgAhoDuIAIADIAAgMgAA6DjIAFgCIAOAQIAAgVIAFgCIAAAdIgEACgABWDYIAQgJIACAFIgLAGIACAFIAMgGIACAEIgLAGIADAGIALgGIACAEIgQAJgAiFDrIALgZIAKAFQAIAEgDAJQgFAKgJgFIgEgCIgDAGgAh7DiIAEACQAFADACgFQACgEgFgDIgEgCgAm5BgIFaiOIACgBIAJgDIAAgBIAdgMIACAAIAHgDIAEgCIAOgGIACAAIAFgDIACAAIAGgDIABAAIAIgEIAAAAIB1gwIAEgCIDshiIA5CLIh0AwIgBAAIgBABIgBAAIiuBHIgDACIg8AYIAAABIgJADIAAAAIgHADIgBAAIgGADIgCABIgFACIgCABIgFACIgCAAIgLAFIgCABIgFACIgBABIgOAGIgBAAIgIADIgBAAIg7AZIgDABIixBKIgBAAIgBABIhzAvgAl3C1QAWALAWgJQAVgJABgTQABgHgDgGQgDgIgHgEQgIgFgTADIgOABQgFAAgCgDQgBgDACgDQABgDAFgDQAFgCAGAAQAFABAGAEIAKgTIgDgCQgSgIgSAIQgLAFgGAJQgGAJACAJIACAHQAEALAMADQAHACANgCIAOgCQAGAAABAEQAEAIgLAFQgNAFgNgJgAkrBFIAEBeIABADIAIgDIABgBIAFgCIABAAIACgBIAAAAIACgBIABAAIgBgOIAfgOIAKALIAUgIIhChIgAjvAsIAjBVIAUgIIgNggIAlgQIgIgSIglAPIgGgPIAlgQIgIgTgAinAOIALAdIABAAIAXA4IA5gYIgIgSIglAPIgBgCIgEgJIgBgDIAAAAIAlgQIgCgFIAAgBIgGgNIglAQIgFgNIgBgBIAmgQIgIgRgAgXAXIAAAAIgBAEIAAABIABADIABABIABADIAJAVIACAAIAFgCIABgBIADgBIADgCIgSgvgAAAAiIAEgCIABAAIADgCIAAAAIADgBIABgBIACAAIAAgCIgBgCIgCgEIgDgHIgBgBIgVgKgAgvAPIABACIAAABIABACIAAABIABADIAAAAIAEAIIAJgEIADgBIABgBIAKgXIgSAIIgCAAIgGADIAAAAgAg3gCIgDABIgIACIgDACIABACIABAEIABACIADAIIABAAIAXgKIADAAIASgIIgWgIIgCAAIAAAAIgCABIgBAAgAgNABIAWAKIACgBIAEgBIACgBIABgBIALgEIAAAAIAIgDIgBgDIgBgCIgBgDIgBgCIgCgGgABNhYIgIAEQgLAIgFAMIgCAEQgCAHAAAFIAAAKIACAIIACADIAAACIABACIADAFIABACIAFAFIABABIAKAIQAQAIAUgGIADgBQAGgCAFgEIAGgFQALgNAAgPIgWgDIAAAEQgCAJgGAFIgGAEIAAAAIgHACQgHABgGgDIgFgEIgFgFIgCgFIgCgHIAAgHIACgHQAEgIAIgEIAFgBQAKgCAHAFIABABIAAAAIACABIADgEIAAgBIAJgNQgMgJgPAAIgEAAQgIABgGACgAgRAAIgJgUIAAgBIgEgKIgFACIgBAAIgGADIgBAAIgDABIAAABIABABIADAIIABADIABACIACABIACABIATAIgAAHgcIgFACIgCABIgCABIgBABIgBAAIgBACIgIAVIAVgJIAAAAIAHgDIAAgBIgCgFIAAgBIgCgDIAAAAIgBgDIAAgBIgBgDgAgUg1IgCABIgDABIgJAEIAHASIABACIACAFIAAABIAJAVIAJgYIgBgCIgBgDIgBAAIgKgYgACOhxIAFBhIAUgIIgBgPIACAAIAdgNIAKALIAUgIIhChIgADziaIgJADIgkAPIAjBUIAUgIIgLgZIAQgHIAVAUIABABIABAAIAAgBIABAAIAUgIIgcgYIADgFQADgIgBgIIgCgKQgCgFgEgFIgCgBQgFgGgIgBIgJgBgAESioIAjBVIA5gYIgHgTIgmAQIgGgPIAmgPIgIgTIgmAQIgFgOIAlgQIgIgTgAibDeIAOgXIAPAJIgCAFIgLgHIgDAFIALAHIgDAEIgLgHIgDAGIALAGIgCAFgABqDNIAFgEIAUAJIgKgPIAEgDIAPAXIgEADIgVgJIALAQIgFACgAilDXIACgJIgFgEIgFAHIgEgDIAQgWIAIAHQAIAGgFAHQgDAFgFgBIgCALgAilDGIAEAEQAEADADgEQACgEgEgDIgEgDgACJC8IgFAFIgEgEIAQgNIADAEIgGAFIAOARIgDADgAhYCyQghgOgZgYIAEgCQAZAYAfANQAiAOAlABQAkAAAigOQAjgOAagbQAZgaAOgjQANgfABgiIAEgCQgBAkgNAhQgWA4gyAfQgLAIgTAIQgjAPglAAQglgBgkgPgAi4C+IgEgEIgFAGIgEgEIASgUIAIAHQAHAHgGAHQgDADgEABQgEAAgDgDgAi5C2IAEAEQADAEAEgEQADgDgEgFIgEgDgACfC5QgDgDADgDQADgDADADQADAEgDACIgDACIgDgCgAhUCnQgbgMgXgUIAmgQIACABIACgDIACAAIgDAEIALAHIAIgSIAFgCIgMAUIALAGIABAAIAKgeIAGgDIgPAhIAMAFIAJgoIAIgDIgQArIANADIAGgwIAIgDIgNAzIANADIABg3IAIgDIgJA6IAOAAIgEg6IAHgDIABAAIAUgJIABgBIAGgCIABgBIANgFIABAAIAHgDIABgBIAHgDIAmAsIAJgKIgugiIAIgDIAmAkIAIgKIgtgbIAIgDIAlAdIAHgLIgpgTIAIgEIAhAWIAGgMIghgMIAGgDIAbAOIAEgMIgVgGIAFgCIAQAHQADgHAAgGIgDgBIACAAIACAAIAAgBIAmgQQgCArgWAlQgVAmgkAXQgNAJgPAGQghAOghAAQgjAAgjgPgAgRCdQgDADABAEQAAAEADACQADADADAAQAKgBgBgJQAAgEgDgDQgCgCgEAAQgEAAgDADgAgyCfQgBAKAJABQAGACADgFIgDgDQgDACgCAAQgFgBABgFQABgFAEABQADABABACIAEgBQgBgFgGgBIgDAAQgGAAgCAHgAAHCZIALARIAEgBIADgUIgFABIgBANIgHgLgAAjCSIAHARIAEgBIgGgSgAA5CIIgGADIAJAQIAGgDQAIgEgEgJQgDgFgFAAIgFACgAgOCRIAOAAIgKg7gAAACRIAMgCIgOg6gAANCOIANgDIgVg4gAAbCLIALgEIABgBIgag1gAAoCGIALgGIgfgygABQCCIADADIAHgGIgDgDgAA0CAIALgHIgkgvgABAB5IAKgIIgogsgABsB3IADgDIgOgNIgDADQAEADgDAEIgBAAIAEADIAAgBQAAAAABAAQAAgBAAgBQABAAAAgBQAAAAgBgBgABLBwIAJgJIgrgngAB3BjIgCACIACAEIAEgEQAEgHgIgGQgDgCgDAAQgEABgBACQgEAFAFAEQAGAEADgFQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBgBAAQADACgCAEgACgCfIAHgJQAGgHAIAGQAHAGgGAIIgDAEIAFAFIgDAEgACqCaIgDAEIAIAGIADgEQADgEgEgDIgDgBQgBAAAAAAQAAAAgBAAQAAAAgBABQAAAAgBABgAgPCkQAAgGAFAAQAFAAAAAFQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgEAAgBgFgACvCMIAGgJQAFgJAIAGQAFADgBAFIALABIgDAFIgKgBIgDAFIAHAFIgDAEgAC4CGIgCAEIAHAFIADgEQADgEgEgDIgDgBQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABgAA5CNIACgBQAFgEACAGQADAEgFADIgCABgADHB/QgFgCgCgGQgCgGADgFQACgFAGgCQAFgBAFACQAFADACAFQACAGgDAFQgCAFgFACIgEABQgEAAgDgCgADKBqQgDABgCAEQgBADABADQABAEADABQAIAFAEgIQAEgIgIgEIgEgBIgDAAgAkXBbIAWAYIgUAIgADOBaIgCAHIgFgCIAHgTIAFACIgDAHIAVAIIgCAFgABwBeQgBAAAAAAQgBgBAAAAQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAABAAQAAABAAAAQABABAAAAQAAAAAAABQgBAAAAABIgCABIgBgBgADQBIIAEgSIAFABIgDANIAFACIAEgNIAEABIgDANIAGACIADgNIAFABIgFASgADiA1QgGgBgDgFQgDgFABgFQAAgIAIgDIACAFQgEABgBAFQgBAEACADQACADAEAAQAEABACgCQADgCABgEQABgFgFgDIADgEQAHAFgBAIQgBAGgFADQgDADgEAAIgDAAgAk1ijQA3hoBsgtQBrgsBwAiQBvAiBDBfIgQAHQhAhZhoggQhpgghmAqQgdANgVANQhOAzglBXQgmBXAPBcIgPAHQgUhyA2hmgAkfiaQA0hfBigpQA5gXA9AAQA8ABA5AYQBPAiA0BGIgEACQgyhEhPgiQg4gYg7gBQg8AAg4AXQgaAKgXAPQhKAxglBTQgkBSAOBZIgEABQgQhoAyhdgADZAWIAAgUIAFAAIAAAIIAWABIAAAFIgWgBIgBAIgAjBhLQAPgkAagaQAagbAjgOQAjgPAmAAQAkABAkAPQAiAPAaAaIgEABQgagZgggOQgigOgkgBQglAAgiAOQgRAIgNAIQgwAfgWA3QgOAiAAAjIgEABQAAglAOgjgAkagJIABgQQABgPALABQAGABACAEQACgEAGAAQAMABgBAPIgBAQgAkCgXIAAAGIAHABIABgHQABgFgFAAIAAAAQgDAAgBAFgAkRgZIgBAHIAIABIAAgHQAAgFgDAAQgEAAAAAEgAikhnQAdgsAxgUQAwgUA0AKQAyAKAmAkIglAPIgDgCIgDAFIgDABIAFgHIgLgHIgJAUIgGACIAOgWIgMgGIgKAgIgHADIAQgjQgGgDgGgCIgKAqIgHADIAQgtIgNgEIgGAyIgHAEIANg2IgNgCIgBA4IgQAHIgBAAIgGADIgBAAIgUAIIgBABIgVAIIAAABIgIADIgoguIgJAKIAxAkIgIADIgqgnIgHALIAwAdIgJADIgogfIgHALIAtAVIgIADIglgXIgGAMIAmAOIgHACIgfgPIgEANIAaAGIgGACIgUgIIgDANIAIACIgDABIgGgCIAAAFIgmAPQACg0AdgrgAhIg+IgkgyIgKAJIAuApgAhChDIgfg2IgKAIIApAugAg7hIIgag4IgKAGIgBABIAlAxgAg0hMIgUg6IgMAGIAgA0gAgthPIgOg8IgMAFIAaA3gAglhSIgIg8IgNADIAVA5gAgdhTIgCg9IgNACIAPA7gAgMhUIAJg7IgOgBgAgfiQIAKA8IAEg8gAibhkQgFAHAHAGQADADAEgBQAEAAACgEQADgEgCgGIgEACQAAABAAABQAAAAAAABQAAAAAAABQAAABAAAAQgDAFgEgEQgEgCACgFQACgCADAAIAAgEQgGAAgCAEgAiHh8QgCACAAAEQAAAEACADQADADAEAAQAEAAADgDQACgCAAgEQAAgEgCgDQgDgDgEAAQgEAAgDADgAh2iLIAQAMIADgCIgEgTIgEACIADANIgKgIgAhaibIAIARIAEgCIgIgRgAhBilIgHACIAGASIAGgCQAJgCgDgJQgCgHgGAAIgDAAgAACiYIAFACQAJACABgKQABgEgBgDQgCgDgDgBQgHgBgBAHQgBAGAGABQAAAAABAAQAAAAABAAQAAAAABgBQAAAAABAAQgBADgEAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBgAgNiZIAFABIAAgTIgEAAQAAAFgFgBIAAAEIABAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAABgBgAgoiiIAAAEIAKgBIgBgEgAGehcIAAAAIgohgIBLgeIgjBYIBYAmIi2BLgAj4gpQgKgCADgNIABgHQgEgBgBAFQAAAEACACIgGAIQgFgHACgJQADgNAMACIARAFIgCAIIgEgBQAEAFgCAGQgBAJgGAAIgDgBgAj5g4QAAAFACAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAgBQABgGgEgCIAAgBgAhOg4gACjhbIAVAYIgTAIgAjnhHQABAAAAAAQABgBAAAAQABAAAAgBQAAAAAAgBQABgDgDgDIgBgBIgeABIADgJIASAAIgNgMIADgJIAZAXQAIAHgDAJQgCAFgEADgAkDh5IAEgIIAmAUIgEAIgADhh+IAPgGQAMgFAFALQAEALgMAFIgOAGgAiDhyQgEgEADgDQAFgEADAEQADAEgDADQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAgAjkh4QgGgEgBgGQgCgGAEgGQADgGAHgBQAGgCAFAEQAGAEABAGQABAGgDAGQgEAGgGABIgDAAQgEAAgEgCgAjiiJQgDAFAFAEQAGAEADgGQAEgGgGgDIgEgCQgDAAgCAEgAjcihIAGgHIADADQgDgFAFgEIAEgEIAFAJIgEACQgEAFAFAEIAMAKIgGAHgAhCigIACAAQAFgCABAFQABAGgEAAIgCABgAAJijQAAAAAAgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBgACAitQgFgFgBgGQAAgGAEgFQAEgFAGAAQAGgBAFAEQAFAFABAGQAAAGgEAFIgCADIgQgPQgCAFAEADQADACAEAAIACAIIgEAAQgFAAgFgEgACHjAIAKAIQABgDgDgEQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAAAgBAAIgDAAgAi1isIACgKQAGACAFgEQAEgEgDgCQgCgCgHADQgLAHgGgIQgDgEABgFQAAgFAFgEQAHgGAKABIgCAJQgFgBgFADQgEAEADACQACABAHgDQALgGAGAHQAEAEgBAGQgBAGgFAEQgGAGgIAAIgEgBgABui7QgIgGAGgKIAFgIIgEgDIAFgHIAEADIADgGIAKABIgGAKIAGAEIgEAHIgGgEIgFAIQgBABAAAAQAAABAAAAQAAABAAABQAAAAABAAIACABIAAAIIgBAAQgDAAgEgCgAiUjCQgGgCgEgFQgDgFABgHQABgGAGgDQAJgGAIAGIgFAIQgDgDgEACQgCABgBADQgBADACACQADAGAGgEQADgCgBgEIAKgCQABALgJAFQgEADgEAAIgDgBgABVjLIAOgaIAIAEIgNAagABIjSIAGgPQADgFgFgCQgEgBgCAFIgGAPIgJgEIARgoIAIAEIgGAPQADgCAFACQAKAEgEALIgHARgAh7jRQgGgDgCgGQgDgGACgGQACgGAHgCQAGgDAGACQAGADACAFQADAGgCAGQgCAGgHADIgGACIgGgBgAh4jmQgFADACAGQADAGAGgDQAGgCgDgHQgCgEgDAAIgEABgAhejlIgDgKIgFABIgDgHIAFgCIgCgGIAHgHIAEAKIAGgCIADAIIgHACIADAKQAAABABAAQAAABAAAAQABABAAAAQABAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAIAGAFQgDAEgEABIgEABQgGAAgDgJgAAkjfIgCgaIgMAXIgJgCIgDgqIAKADIABAZIAMgXIAIACIACAaIALgXIAJADIgSAkgAhHjsIgCgKIgFABIgBgIIAEgBIgBgGIAIgHIACALIAHgBIACAIIgHABIACAKQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIACgBIAGAGQgEADgDABIgDAAQgHAAgDgKgABojlQgEgDACgEQADgFAEACQAGADgDAFQgCADgDAAIgDgBgAgljoQgEgEAAgEQAAgGAIgGQgEgEAAgEQAAgFADgDQADgDAFAAQALAAAAAKQAAAFgGAFIAEAEIAGgHIALAAIgLANIALALIgMAAIgEgFQgGAGgGAAQgGAAgDgDgAgfjxQAAABAAAAQAAABABAAQAAABABAAQAAAAABAAQADAAADgCIgGgGQgDADAAACgAgdkFQABADACACQADgCAAgDQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQAAABgBAAQAAABAAAAg");
	this.shape.setTransform(0.025,0.0143);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.safeCare_logo, new cjs.Rectangle(-50.1,-33.7,100.30000000000001,67.5), null);


(lib.BSWH_Icon = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// blue_bottom
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1B449D").s().p("AgFAQIAAgUIALgLIAAAfg");
	this.shape.setTransform(-0.625,1.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1B449D").s().p("AgWBBIAAhUIAtgtIAACBg");
	this.shape_1.setTransform(-2.525,6.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1B449D").s().p("AgkBsIAAiMIBJhLIAADXg");
	this.shape_2.setTransform(-4.175,11.275);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1B449D").s().p("AgxCQIAAi8IBihjIAAEfg");
	this.shape_3.setTransform(-5.55,15.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1B449D").s().p("Ag7CtIAAjiIB3h3IAAFZg");
	this.shape_4.setTransform(-6.675,18.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1B449D").s().p("AhDDEIAAkAICHiHIAAGHg");
	this.shape_5.setTransform(-7.575,20.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1B449D").s().p("AhIDUIAAkVICRiTIAAGog");
	this.shape_6.setTransform(-8.225,22.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1B449D").s().p("AhMDeIAAkiICYiZIAAG7g");
	this.shape_7.setTransform(-8.6,23.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1B449D").s().p("AhNDiIAAknICbicIAAHDg");
	this.shape_8.setTransform(-8.725,23.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},5).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_8}]},6).to({state:[]},1).wait(352));

	// blue_Rt
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1B449D").s().p("AgEAFIgLgKIAfAAIAAAKg");
	this.shape_9.setTransform(1.7,0.65);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1B449D").s().p("AgTAWIgtgsICBAAIAAAsg");
	this.shape_10.setTransform(6.825,2.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#1B449D").s().p("AggAlIhLhJIDXAAIAABJg");
	this.shape_11.setTransform(11.275,4.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#1B449D").s().p("AgsAyIhjhiIEfAAIAABig");
	this.shape_12.setTransform(15.075,5.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1B449D").s().p("Ag1A8Ih3h3IFZAAIAAB3g");
	this.shape_13.setTransform(18.15,6.775);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#1B449D").s().p("Ag8BEIiHiHIGHAAIAACHg");
	this.shape_14.setTransform(20.525,7.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#1B449D").s().p("AhBBJIiTiRIGoAAIAACRg");
	this.shape_15.setTransform(22.25,8.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#1B449D").s().p("AhEBNIiZiYIG7AAIAACYg");
	this.shape_16.setTransform(23.3,8.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#1B449D").s().p("AhFBOIicibIHDAAIAACbg");
	this.shape_17.setTransform(23.625,8.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_9}]},9).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_17}]},2).to({state:[]},1).wait(352));

	// lt_blue_lt
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#1690BF").s().p("AgKAFIAAgKIAVAAIgLAKg");
	this.shape_18.setTransform(-1.15,0.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#1690BF").s().p("AgsAWIAAgsIBZAAIgtAsg");
	this.shape_19.setTransform(-4.725,2.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#1690BF").s().p("AhJAlIAAhJICTAAIhKBJg");
	this.shape_20.setTransform(-7.825,4.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#1690BF").s().p("AhhAyIAAhiIDDAAIhiBig");
	this.shape_21.setTransform(-10.425,5.65);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#1690BF").s().p("Ah1A8IAAh3IDrAAIh2B3g");
	this.shape_22.setTransform(-12.55,6.775);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#1690BF").s().p("AiFBEIAAiHIELAAIiHCHg");
	this.shape_23.setTransform(-14.225,7.675);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#1690BF").s().p("AiQBJIAAiRIEhAAIiSCRg");
	this.shape_24.setTransform(-15.425,8.325);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#1690BF").s().p("AiXBNIAAiYIEvAAIiYCYg");
	this.shape_25.setTransform(-16.15,8.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#1690BF").s().p("AiZBOIAAibIEzAAIibCbg");
	this.shape_26.setTransform(-16.375,8.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18}]}).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_26}]},11).to({state:[]},1).wait(352));

	// blue_lt
	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#1B449D").s().p("AgPAGIAAgLIAUAAIALALg");
	this.shape_27.setTransform(-1.675,-0.625);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#1B449D").s().p("AhAAXIAAgtIBUAAIAtAtg");
	this.shape_28.setTransform(-6.8,-2.525);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#1B449D").s().p("AhrAlIAAhJICMAAIBLBJg");
	this.shape_29.setTransform(-11.25,-4.175);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#1B449D").s().p("AiPAyIAAhiIC8AAIBjBig");
	this.shape_30.setTransform(-15,-5.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#1B449D").s().p("AitA8IAAh3IDjAAIB4B3g");
	this.shape_31.setTransform(-18.075,-6.725);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#1B449D").s().p("AjEBEIAAiHIEAAAICICHg");
	this.shape_32.setTransform(-20.45,-7.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#1B449D").s().p("AjUBJIAAiRIEWAAICTCRg");
	this.shape_33.setTransform(-22.175,-8.275);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#1B449D").s().p("AjeBNIAAiYIEjAAICaCYg");
	this.shape_34.setTransform(-23.225,-8.65);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#1B449D").s().p("AjhBOIAAibIEnAAICcCbg");
	this.shape_35.setTransform(-23.55,-8.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_27}]},7).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_35}]},4).to({state:[]},1).wait(352));

	// yellow_top
	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FDB61B").s().p("AgFAAIAAgKIALAAIAAAVg");
	this.shape_36.setTransform(-0.625,-1.15);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FDB61B").s().p("AgWAAIAAgsIAtAAIAABZg");
	this.shape_37.setTransform(-2.525,-4.725);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FDB61B").s().p("AgkAAIAAhJIBJAAIAACTg");
	this.shape_38.setTransform(-4.175,-7.825);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FDB61B").s().p("AgxAAIAAhhIBiAAIAADDg");
	this.shape_39.setTransform(-5.55,-10.45);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FDB61B").s().p("Ag7AAIAAh1IB3AAIAADrg");
	this.shape_40.setTransform(-6.675,-12.575);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FDB61B").s().p("AhDgBIAAiEICHAAIAAELg");
	this.shape_41.setTransform(-7.575,-14.25);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FDB61B").s().p("AhIAAIAAiQICRAAIAAEhg");
	this.shape_42.setTransform(-8.225,-15.45);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FDB61B").s().p("AhMAAIAAiXICYAAIAAEvg");
	this.shape_43.setTransform(-8.6,-16.175);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FDB61B").s().p("AhNgBIAAiYICbAAIAAEzg");
	this.shape_44.setTransform(-8.725,-16.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_36}]}).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_44}]},11).to({state:[]},1).wait(352));

	// blue_top
	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#1B449D").s().p("AgFgPIAKAAIAAAUIgKALg");
	this.shape_45.setTransform(0.65,-1.675);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#1B449D").s().p("AgWhAIAsAAIAABUIgsAtg");
	this.shape_46.setTransform(2.55,-6.8);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#1B449D").s().p("AgkhrIBJAAIAACMIhJBLg");
	this.shape_47.setTransform(4.225,-11.25);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#1B449D").s().p("AgwiPIBiAAIAAC8IhiBjg");
	this.shape_48.setTransform(5.65,-15.025);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#1B449D").s().p("Ag7itIB3AAIAADjIh3B4g");
	this.shape_49.setTransform(6.775,-18.1);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#1B449D").s().p("AhDjDICHAAIAAEAIiHCHg");
	this.shape_50.setTransform(7.675,-20.475);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#1B449D").s().p("AhIjUICRAAIAAEWIiRCSg");
	this.shape_51.setTransform(8.325,-22.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#1B449D").s().p("AhLjeICYAAIAAEkIiYCZg");
	this.shape_52.setTransform(8.7,-23.25);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#1B449D").s().p("AhNjhICbAAIAAEnIibCcg");
	this.shape_53.setTransform(8.825,-23.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_45}]},5).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_53}]},6).to({state:[]},1).wait(352));

	// lt_blue_rt
	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#1690BF").s().p("AgKAGIAKgLIALAAIAAALg");
	this.shape_54.setTransform(1.2,-0.625);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#1690BF").s().p("AgsAXIAsgtIAtAAIAAAtg");
	this.shape_55.setTransform(4.775,-2.525);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#1690BF").s().p("AhJAlIBKhJIBJAAIAABJg");
	this.shape_56.setTransform(7.875,-4.175);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#1690BF").s().p("AhhAyIBihiIBhAAIAABig");
	this.shape_57.setTransform(10.525,-5.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#1690BF").s().p("Ah1A8IB2h3IB1AAIAAB3g");
	this.shape_58.setTransform(12.65,-6.725);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#1690BF").s().p("AiFBEICGiHICFAAIAACHg");
	this.shape_59.setTransform(14.325,-7.625);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#1690BF").s().p("AiQBJICRiRICQAAIAACRg");
	this.shape_60.setTransform(15.525,-8.275);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#1690BF").s().p("AiXBNICYiYICXAAIAACYg");
	this.shape_61.setTransform(16.25,-8.65);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#1690BF").s().p("AiZBOICaibICZAAIAACbg");
	this.shape_62.setTransform(16.475,-8.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_54}]},3).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_62}]},8).to({state:[]},1).wait(352));

	// yellow_bottom
	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FDB61B").s().p("AgFALIAAgVIAKAKIAAALg");
	this.shape_63.setTransform(0.65,1.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FDB61B").s().p("AgWAtIAAhZIAsAsIAAAtg");
	this.shape_64.setTransform(2.55,4.775);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FDB61B").s().p("AgkBKIAAiTIBJBKIAABJg");
	this.shape_65.setTransform(4.225,7.875);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FDB61B").s().p("AgwBiIAAjDIBiBiIAABhg");
	this.shape_66.setTransform(5.65,10.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FDB61B").s().p("Ag7B2IAAjrIB3B2IAAB1g");
	this.shape_67.setTransform(6.775,12.625);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FDB61B").s().p("AhDCGIAAkLICHCHIAACEg");
	this.shape_68.setTransform(7.675,14.3);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FDB61B").s().p("AhICRIAAkhICRCSIAACPg");
	this.shape_69.setTransform(8.325,15.5);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FDB61B").s().p("AhLCYIAAkvICYCYIAACXg");
	this.shape_70.setTransform(8.7,16.225);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FDB61B").s().p("AhNCaIAAkzICbCaIAACZg");
	this.shape_71.setTransform(8.825,16.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_63}]},2).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_71}]},9).to({state:[]},1).wait(352));

	// Registration
	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("rgba(27,68,157,0.667)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFgEgSQgCgCgGAAQgFAAgKACgAAAABIgDAKIgEAAIAAgVIAIAAIAJAVg");
	this.shape_72.setTransform(3.075,35.85);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("rgba(27,68,157,0.722)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQADgEgDgTQgCgBgGAAIgPABgAgGALIgBgBIAAgUIAHAAIAAAAIgGAAIAAAQIAAAEIADAAIAAABIgDAAgAgDAKgAgCAFIACgCIAAgBIgBADIgCAFg");
	this.shape_73.setTransform(3.075,35.85);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("rgba(27,68,157,0.776)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQADgEgEgTQgBgBgGAAIgPABgAgGALIgBgBIAAgUIAIAAIAEAKIgFgJIgGAAIAAANIABADIADAAIgBADIgCABgAAGAJIgGgHIgBACIgBADIAAgCIABgBIACgDIAGADIACAHgAgCAHg");
	this.shape_74.setTransform(3.075,35.85);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("rgba(27,68,157,0.835)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQADgEgEgTQgBgCgGAAIgPACgAgFALIgCgBIAAgUIAIAAIADAHIgEgGIgFAAIAAAMIABACIACAAIgBAFIgCABgAAGAKIgGgIIAAAAIgBABIABgBIACgCIAEACIADAIg");
	this.shape_75.setTransform(3.075,35.85);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("rgba(27,68,157,0.89)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFgFgTQgBgBgFAAQgFAAgLACgAgFALIgCAAIAAgVIAIAAIACAGIgDgEIgEAAIAAAJIABACIAAAAIAAAGIgBACgAAGAKIgGgHIAAgBIgBAAIABgBIACgBIADAAIAEAKg");
	this.shape_76.setTransform(3.075,35.85);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("rgba(27,68,157,0.945)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFgFgTQgCgBgFAAQgFAAgKACgAgEALIgDAAIAAgVIAIAAIADAFIgEgDIgEAAIAAAIIACABIABAAIABgBIADAAIACAAIAEAKIgDABIgFgIIgBgBIgDAAIgBAJg");
	this.shape_77.setTransform(3.075,35.85);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#1B449D").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFAAgHQAAgGgEgFQgFgEgHAAQgGAAgFAEgAAGALIgGgKIgDAAIAAAKIgEAAIAAgVIAIAAQAIgBAAAHQAAAEgGABIAHAKgAgDAAIADAAQAGAAAAgEQAAgDgFAAIgEAAg");
	this.shape_78.setTransform(3.075,35.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_72}]},13).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_77}]},1).to({state:[{t:this.shape_78}]},1).to({state:[]},1).wait(352));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.4,-46.1,106.5,92.30000000000001);


(lib.image_05 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#008FBE").s().p("A3bfQMAAAg+fMAu3AAAMAAAA+fg");
	this.shape.setTransform(0,3.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.instance = new lib.Image_01();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_05, new cjs.Rectangle(-150,-196.9,300,399.9), null);


(lib.image_04 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image_04();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_04, new cjs.Rectangle(-150,-196.5,299,384), null);


(lib.image_03 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image_03();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_03, new cjs.Rectangle(-150,-196.5,299,384), null);


(lib.image_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image_02();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_02, new cjs.Rectangle(-150,-196.5,299,384), null);


(lib.image_01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image_01();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_01, new cjs.Rectangle(-150,-196.5,300,393), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// TALK_TO_US_TODAY
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8A8A8").s().p("AgDAyQgHgDgGgFQgGgGgCgHQgEgIAAgKIAAg9IAZAAIAAA9QABAIADAFQAEAFAIAAQAHAAAFgFQAEgFABgIIAAg9IAZAAIAAA9QgBAKgDAIQgDAHgFAGQgFAFgIADQgHACgKAAQgJAAgHgCgAiDAxQgKgFgHgHQgHgHgEgJQgEgKAAgLQAAgKAEgKQAEgJAHgHQAHgIAKgEQAJgDALAAQALAAAJADQAKAEAHAIQAHAHAEAJQAFAKAAAKQAAALgFAKQgEAJgHAHQgHAHgKAFQgJADgLAAQgLAAgJgDgAh6gaQgFADgDAEQgEADgDAGQgCAFAAAFQAAAGACAFQACAFAEAEQAEAEAFACQAFADAGAAQAGAAAFgDQAGgCADgEIAGgJQACgFAAgGQAAgFgCgFQgDgGgDgDQgEgEgFgDQgFgCgGAAQgGAAgFACgAIvAzIAAgrIghg6IAaAAIATAlIAUglIAaAAIgiA6IAAArgAHYAzIAAgnIghAAIAAAnIgYAAIAAhlIAYAAIAAAmIAhAAIAAgmIAZAAIAABlgAFMAzIgSg/IgRA/IgYAAIgchlIAYAAIAQA+IASg+IAXAAIASA+IAQg+IAYAAIgcBlgAByAzIAAhPIgcAAIAAgWIBQAAIAAAWIgcAAIAABPgAlNAzIAAhlIAlAAQALAAALADQAJAEAIAHQAGAHAEAJQAEAKAAAKQAAALgEAJQgEAKgHAGQgHAHgJAEQgLAEgLAAgAk0AcIALAAQAHAAAFgCQAFgCAFgEQADgEACgFQADgFAAgGQAAgFgDgGQgCgFgDgEQgEgDgFgDQgGgCgIAAIgKAAgAmGAzIgog/IAAA/IgYAAIAAhlIAaAAIAmA8IAAg8IAYAAIAABlgAoAAzIAAhlIAYAAIAABlgApoAzIAAhlIBHAAIAAAXIguAAIAAASIAuAAIAAAWIguAAIAAAmg");
	this.shape.setTransform(3.15,0.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(201,201,198,0.298)","rgba(201,201,198,0)"],[0,0.608],-53.5,0,68.2,0).s().p("AnICpIFLlRIJGAAIAAFRg");
	this.shape_1.setTransform(33.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// _Path__1
	this.instance = new lib.Bitmap1();
	this.instance.setTransform(-89,-33,0.7554,0.8156);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-89,-33,194.9,78.3), null);


(lib.bswh_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.BSWH_Icon("synched",0,false);
	this.instance.setTransform(1.2,-43.3,0.7829,0.7829,-44.2419,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:0.2,scaleX:0.7828,scaleY:0.7828,rotation:-0.7885,x:1.3,y:-43.35,startPosition:6},6,cjs.Ease.quadOut).to({regX:0.1,scaleX:0.7829,scaleY:0.7829,rotation:0,x:1.25,y:-43.25,mode:"single",startPosition:19},13).wait(1).to({startPosition:19},0).to({_off:true},1).wait(99));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3FA1C7").s().p("AKgAaQgJgKAAgPQAAgOAJgLQAJgKAPAAQALAAAIAGQAJAHABALIgOAAQgBgFgEgDQgEgDgGAAQgHAAgEADQgEADgCAFQgCAGAAAFQAAAJAFAHQAFAGAJAAQAHAAADgEQAEgEABgHIAOAAQgBANgIAHQgIAHgMAAQgPAAgJgJgAHsAaQgJgKAAgPQAAgPAJgKQAJgKAPAAQAMAAAIAGQAIAHABALIgOAAQgBgFgEgDQgEgDgGAAQgHAAgDADQgFADgCAFQgBAFAAAGQAAAJAEAHQAFAGAJAAQAHAAAEgEQADgEABgHIAPAAQgCANgHAHQgJAHgMAAQgPAAgJgJgAFUAdQgHgHAAgNIAAgpIAOAAIAAApQAAAGADAEQADAEAIAAQAIAAADgDQADgDAAgIIAAgpIAPAAIAAApQAAANgHAHQgHAGgPAAQgOAAgHgGgAECAaQgJgKAAgPQAAgOAJgLQAJgKAPAAQAQAAAIAKQAJAKAAAPQAAAPgJAKQgIAJgQAAQgPAAgJgJgAEQgSQgFAEgBAEQgCAGAAAFQAAAJAFAHQAEAGAJAAQAJAAAFgGQAEgHAAgJQAAgFgBgGQgCgFgEgDQgEgDgHAAQgHAAgDADgAC7AeQgIgHAAgLIAPAAQAAAGAEADQAEADAGAAIAGgBIAFgCQACgCAAgDIAAgDIgCgCIgCgCIgEgBIgTgGIgGgCQgEgDgBgDQgCgDAAgFQAAgGAEgFQAEgEAFgDQAHgCAGAAQAGAAAHACQAGACAEAFQADAFAAAIIgOAAQAAgKgNAAQgEAAgDACQgDABAAAEQAAAEADABIARAFQAJADAEACQAHAFAAAJQAAAKgIAGQgHAFgNAAQgNAAgIgFgAjRAaQgJgKAAgPQAAgPAJgKQAJgKAPAAQAMAAAIAGQAIAHABALIgOAAQgBgFgEgDQgEgDgGAAQgHAAgDADQgFADgCAFQgBAGAAAFQAAAJAEAHQAFAGAJAAQAHAAAEgEQADgEABgHIAPAAQgCANgIAHQgIAHgMAAQgPAAgJgJgAm0AaQgJgKAAgPQAAgPAJgKQAJgKAPAAQAMAAAIAGQAIAHABALIgOAAQgBgFgEgDQgEgDgGAAQgGAAgFADQgEADgBAFQgCAGAAAFQAAAJAEAHQAFAGAJAAQAHAAAEgEQADgEABgHIAPAAQgBANgIAHQgJAHgMAAQgPAAgJgJgAvwAaQgJgKAAgPQAAgPAJgKQAJgKAPAAQAPAAAJAKQAJALAAAOQAAAPgJAKQgJAJgPAAQgQAAgIgJgAvjgSQgEADgCAFQgBAFAAAGQAAAJAEAHQAFAGAJAAQAJAAAEgGQAFgHAAgJQAAgFgCgGQgCgFgEgDQgDgDgHAAQgHAAgEADgAwxAeQgHgFAAgKIAAgGIAOAAIAAADQAAAGACACQACADAEAAIAEgBIACgBIACgDIAAgDIAAgvIAPAAIAAAtQAAAWgWAAQgKAAgGgFgAQqAiIgBgEIgCgMQAAgFgDgDQgCgCgGAAIgOAAIAAAaIgPAAIAAhCIAkAAQAJAAAFAFQAGAGAAAHQAAANgLADQAJADABANIAAADIABAHIACAGgAQOgCIAQAAQAKAAAAgJQAAgKgKAAIgQAAgAO6AiIAAhCIAyAAIAAAMIgjAAIAAAOIAhAAIAAALIghAAIAAARIAkAAIAAAMgAOIAiIAAg2IgUAAIAAgMIA3AAIAAAMIgUAAIAAA2gANWAiIgcgsIAAAsIgOAAIAAhCIAOAAIAdAsIAAgsIANAAIAABCgALnAiIAAhCIAyAAIAAAMIgjAAIAAAOIAhAAIAAALIghAAIAAARIAkAAIAAAMgAIzAiIAAhCIAzAAIAAAMIgkAAIAAAOIAhAAIAAALIghAAIAAARIAkAAIAAAMgAHFAiIgBgEIgBgMQgBgFgCgDQgDgCgFAAIgPAAIAAAaIgPAAIAAhCIAlAAQAJAAAFAFQAFAGAAAHQAAANgKADQAJADAAANIAAADIABAHIACAGgAGpgCIAQAAQALAAAAgJQAAgKgLAAIgQAAgABzAiIAAhCIAyAAIAAAMIgjAAIAAAOIAgAAIAAALIggAAIAAARIAkAAIAAAMgABSAiIgBgEIgBgMQgBgFgCgDQgDgCgFAAIgPAAIAAAaIgPAAIAAhCIAkAAQAJAAAGAFQAFAGAAAHQAAANgLADQAJADABANIABAKIABADIABADgAA2gCIAQAAQAKAAAAgJQAAgKgKAAIgQAAgAgaAiIgBgEIgBgMQgBgGgDgCQgCgCgGAAIgOAAIAAAaIgPAAIAAhCIAkAAQAJAAAFAFQAGAGAAAHQAAANgLADQAJADABANIAAADIAAAEIABAGIACADgAg2gCIAQAAQAKAAAAgJQAAgKgKAAIgQAAgAiKAiIAAhCIAyAAIAAAMIgjAAIAAAOIAhAAIAAALIghAAIAAARIAkAAIAAAMgAj6AiIgdgsIAAAsIgOAAIAAhCIAPAAIAcAsIAAgsIAOAAIAABCgAlBAiIgGgPIgZAAIgFAPIgPAAIAahCIAPAAIAZBCgAlcAIIASAAIgJgYgAolAiIAAgMIAkgqIghAAIAAgMIA1AAIAAALIgkArIAlAAIAAAMgApTAiIAAg2IgUAAIAAgMIA3AAIAAAMIgUAAIAAA2gAp3AiIgFgPIgZAAIgGAPIgPAAIAahCIAPAAIAZBCgAqSAIIASAAIgJgYgArDAiIgUgeIgIAIIAAAWIgPAAIAAhCIAPAAIAAAcIAagcIASAAIgaAaIAdAogAszAiIgcgsIgBAAIAAAsIgNAAIAAhCIAOAAIAdAsIAAgsIANAAIAABCgAt6AiIgFgPIgZAAIgGAPIgPAAIAahCIAPAAIAZBCgAuUAIIARAAIgIgYIgBAAg");
	this.shape.setTransform(-0.875,59.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1A459F").s().p("AIuDmQgMgNAAgWQAAgVAMgOQANgOAVAAQAPAAAMAJQALAJACAQIgUAAQgBgHgGgFQgGgFgHAAQgJAAgGAFQgGAFgDAHQgCAHAAAIQAAAOAGAJQAHAJANAAQAJAAAFgGQAGgFABgKIAUAAQgCARgLALQgLAKgRAAQgVAAgNgOgADMDmQgNgOAAgVQAAgVANgOQAMgOAVAAQAQAAAMAJQALAJACAQIgUAAQgBgHgGgFQgGgFgIAAQgJAAgFAFQgHAFgCAHQgCAHAAAIQAAAOAGAJQAGAJANAAQAJAAAGgGQAGgFABgKIAUAAQgCARgLALQgMAKgRAAQgVAAgMgOgAlTDrQgMgIAAgQIAVAAQAAAJAFAEQAGAEAJAAIAIgBQAEAAADgDQADgDAAgFIAAgDIgDgDIgDgDIgggJIgJgFQgEgDgCgFQgCgEAAgHQAAgJAFgGQAFgHAIgDQAHgDAKAAQAKAAAIADQAJADAFAHQAFAHAAAKIgUAAQgBgOgRAAQgGAAgEACQgEADAAAFQAAAGAEACQAGACASAFQANADAFAEQAKAIAAAMQAAANgLAJQgKAIgSAAQgSAAgLgJgAscDrQgMgIAAgQIAUAAQAAAJAGAEQAGAEAJAAIAIgBQAEAAADgDQADgDAAgFIgBgDQAAgBAAAAQAAAAAAgBQAAAAgBgBQAAAAgBAAIgDgDIgKgDIgGgCIgFgBIgLgDIgJgFQgEgDgCgFQgDgFAAgGQAAgJAGgGQAFgHAIgDQAHgDAKAAQAKAAAIADQAJADAFAHQAFAHAAAKIgUAAQgBgOgRAAQgGAAgEACQgEADAAAFQAAAFAEADQAHADAQAEQANADAGAEQAJAIAAAMQAAANgKAJQgKAIgTAAQgRAAgLgJgARgDyIgBgHIgCgQQgBgIgDgCQgEgEgHAAIgVAAIAAAlIgVAAIAAheIAzAAQAMAAAIAIQAHAHAAALQAAASgPAFIAAABQANADABATIACASIACAEgAQ5C/IAXAAQAOAAAAgOQAAgNgOAAIgXAAgAPCDyIAAheIBGAAIAAARIgxAAIAAAUIAtAAIAAAQIgtAAIAAAYIAyAAIAAARgAN6DyIAAhNIgdAAIAAgRIBNAAIAAARIgcAAIAABNgAMxDyIgng/IAAA/IgUAAIAAheIAVAAIAnA/IAAAAIAAg/IATAAIAABegAKUDyIAAheIBGAAIAAARIgxAAIAAAUIAtAAIAAAQIgtAAIAAAYIAyAAIAAARgAGZDyIAAheIAUAAIAABNIAuAAIAAARgAFuDyIgHgVIgjAAIgHAVIgVAAIAjheIAVAAIAkBegAFKDOIAYAAIgMgjgACQDyIAAheIAUAAIAABegAAhDyIAAheIAoAAQAUAAALAMQAMAMAAAWQAAAVgLAOQgLANgVAAgAA2DhIASAAQAJAAAIgHQAGgHAAgOQAAgQgGgIQgGgIgPAAIgOAAgAhADyIAAheIBFAAIAAARIgxAAIAAAUIAtAAIAAAQIgtAAIAAAYIAyAAIAAARgAhzDyIAAhCIAAAAIgXBCIgQAAIgXhCIAAAAIAABCIgTAAIAAheIAcAAIAWBBIABAAIAUhBIAdAAIAABegAmhDyIAAhNIgcAAIAAgRIBNAAIAAARIgdAAIAABNgAnqDyIgng/IAAAAIAAA/IgTAAIAAheIAUAAIAnA/IABAAIAAg/IATAAIAABegApYDyIAAheIAUAAIAABegAqDDyIgHgVIgjAAIgHAVIgVAAIAjheIAVAAIAjBegAqoDOIAZAAIgMgjIgBAAgAuuDyIAAheIAUAAIAABNIAuAAIAAARgAwKDyIAAheIAVAAIAABNIAuAAIAAARgAw0DyIgHgVIgjAAIgIAVIgVAAIAkheIAVAAIAjBegAxZDOIAYAAIgLgjIgBAAgAuwBnQgEgEAAgIQAAgHAEgEQAEgEAHAAIAHAAQAIAAAEgGQAMgTAGgPQAEgJAAgHQAAgIgGgRIgdhPIgJgUQgEgIgJgBIgJgCQgCgCAAgDQAAgBAAgBQABgBAAAAQAAgBAAAAQABAAAAAAIAkAAIAgAAQABAAAAAAQABAAAAABQAAAAAAABQABABAAABQAAADgCACIgJACQgJABAAADQAAAEALAfIAMAjIAGAPIAFALQACgBAMgbIAMgdQANgfAAgGQAAgFgJgBIgLgCQgCgCAAgDQAAgBAAgBQABgBAAAAQAAgBABAAQAAAAABAAIA9AAQAAAAABAAQAAAAAAABQABAAAAABQAAABAAABQAAADgCACIgGABQgJABgHAJQgFAIgLAVIgUArQgbA2gfBEQgIARgQAAQgIAAgEgEgAK7AbQgIgVgPgiIgWgyQgjBGgMAjIgEABIgGgBIgZg7IhIibQgGgOgEgEQgGgIgKgBIgJAAQgCgCAAgDQAAgBAAgBQABAAAAgBQAAAAABgBQAAAAABAAIAmABIAqgBQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABQAAADgCADIgJAAQgMABAAAFQAAAFAUAtQAUAuAsBdIAdg8IAFgPIgDgKIgohZQgFgKgFgEQgFgGgJgBIgJAAQgCgDAAgDQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAnABIApgBQABAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAADgCADIgKAAQgKABgCAEQgBADAFANIAdBAIAWgwQAKgXgBgHQAAgGgJgBIgLAAQgCgDAAgDQAAgBAAAAQABgBAAAAQAAgBAAAAQABAAAAAAIAjABIAkgBQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABQAAADgBADIgLAAQgKABgIALIgNAVQgPAbgNAgIgEAJQAAADADAGIAmBVIAhhPQAVgwAJgZQALgfAAgDQAAgIgMgBIgLAAQgCgDAAgDQAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIAkABIADAAQARgBAMgHQAHgEALgJIADAAIABACIgBAvIAABOQAAAGABABQAagUAZAAQAZAAAMAOQALANAAAVIAAA+QAAAUACAFQACAFAKACIAKABQACABgBAEQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQgSgBgTAAQgVAAgNABQgDgBAAgDQAAgEACgBIAHgBQAKgCACgFQACgFAAgUIAAg1QAAgSgIgLQgKgKgRAAQgRAAgMAJQgFAFgCADIgBANIAAA+QAAAUACAFQADAFAJACIAIABQACABAAAEQgBADgCABQgPgBgUAAQgUAAgQABQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAAAQgBgEACgBIAJgBQAKgCADgFQACgFAAgUIAAioQAAgRgCgFQgBgDgDAAQgHADgGAJQgEAIgTArIgbA/QgYA3gXA6IgEABIgFgBgAmjAOQgDgGgDgPQgDgQgBgOQACgCADAAQABAAABAAQAAAAABAAQAAAAABAAQAAABAAAAQAGAVAMAOQASATAcAAQAWAAANgNQAMgKAAgSQAAgPgFgLQgHgOgTgMIgjgXQgogbAAglQAAgcAUgRQAVgTAjAAQARAAARAFIANACQADAHACANQACAOAAALQAAAAgBABQAAAAgBAAQAAABgBAAQgBAAgBAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQgFgSgJgJQgNgPgYAAQgYAAgMAOQgIALAAARQAAAZAfAUIAeATQAvAdAAAqQAAAfgWASQgWATgjAAQgiAAgZgOgAS/AUQgOgGgIgLQgQgUAAgcQAAgjAVgYQAVgZAhAAQAXAAAPAOQAPANAAASQAAAHgCACQgBADgVAAIhFAAQgHAAgBABQgCACAAAHQAAAdAQAUQARATAdAAQAKAAAHgDQAJgDAIgLQADgBACACQABAAAAAAQAAABAAAAQABABAAAAQAAABAAABQgIAQgSAJQgQAIgRAAQgRAAgOgHgATDhqQgMALgBAKQAAAAAAABQABAAAAAAQAAAAABABQABAAAAAAIAaAAQAiAAAFgEQACgBAAgGQAAgJgGgHQgHgIgPAAQgQAAgNAMgARLAPQgHgJAAgSIAAhVIgBgJQgBgCgGAAIgKAAIgCgDIAAgFQARgEAHgHQAJgIAHgOQAGgCACAEIAAAQQAAAGABABIAGAAIApAAQADADAAAGQAAAFgDACIgqAAQgEAAgCACQgBABAAAGIAABGQAAATAFAJQAGAMARAAQAGAAAEgCIAJgFQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABAEQgGAHgJAFQgLAFgNAAQgWAAgKgMgAC/APQgIgJAAgSIAAhVQAAgIgBgBQgBgCgFAAIgLAAIgCgDQAAgBAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAQgEAIgHQAIgIAHgOQAGgCACAEIAAAQQAAAGABABIAGAAIApAAQADADAAAGQAAAFgDACIgpAAQgFAAgBACQgBABAAAGIAABGQAAATAEAJQAGAMARAAQAGAAAEgCIAJgFQABAAAAAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgGAHgJAFQgLAFgNAAQgWAAgJgMgABPAPQgIgJAAgSIAAhVQAAgIgBgBQgBgCgGAAIgKAAQgBAAAAgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAQgEAIgHQAIgIAHgOQAGgCACAEIAAAQIABAHIAGAAIApAAQADADAAAGQAAAGgDABIgqAAQgEAAgBACQgBABAAAGIAABGQAAATAEAJQAGAMARAAQAFAAAFgCIAJgFQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIABAEQgPARgYAAQgWAAgJgMgAhhAGQgWgUAAgiQAAgjAXgXQAXgXAhAAQAgAAAUAWQAXAVAAAiQAAAjgWAWQgVAWgjAAQghAAgVgVgAhLhlQgMASAAAeQAAAcAMAUQANAVAXAAQAXAAALgUQAIgQAAgaQAAgcgKgUQgNgYgYAAQgTAAgMARgAjtAIQgVgTAAgjQAAghAWgXQAZgbArAAQATAAAOAHQAGAFAAAKQAAAFgDAEQgCAEgEAAQgDAAgCgCQgHgJgJgFQgKgGgLAAQgVAAgOAPQgQARAAAcQAAAYAPASQARAUAcAAQAPAAAKgGQAJgEAHgLQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQABABAAAAQgJASgTALQgQAIgTAAQgfAAgUgTgAq5AGQgWgUAAgiQAAgjAXgXQAXgXAhAAQAgAAAWAWQAWAVAAAiQAAAjgWAWQgWAWgjAAQggAAgWgVgAqjhlQgMASAAAeQAAAcAMAUQANAVAXAAQAXAAALgUQAJgQAAgaQAAgcgLgUQgNgYgYAAQgTAAgMARgAvsAQQgDgFgCAAIgPAHIgMAGQgIADgHAAQgQAAgKgIQgLgKAAgPQAAgMAGgGQAHgHASgHIAsgQQAEgBABgDIABgHIABgRQAAgNgFgIQgHgLgQAAQgIAAgHAEQgIAEAAAIQgBALgDACQgEADgHACQgGACgEAAQgGAAAAgFQAAgOAZgQQAYgQAVAAQAUAAAKAMQAJALgBAVIgCBAQgBAgASAAQAEAAAFgCIAFgDQADAAAAAFQAAADgJAGQgLAHgLAAQgPAAgKgLgAwDgmQgSAGgGAFQgIAGAAAKQAAAHAEAGQAGAJANAAQAFAAAIgEQAGgDAEgDQACgCABgEIABgKIABgWQAAgFgEAAQgFAAgKAEgAE9AGQgWgSAAgcQAAgpAqgTQgOgQAAgQQAAgTANgOQAOgNATAAQAOAAAKAHQALAJAAAMQAAAMgKAIQgIAGgHAAQgIAAAFgGQAGgHgDgKQgCgFgFgEQgGgFgHAAQgLgBgGAGQgIAGAAAJQAAAJAHAIQAHAHATAKQAgASAOAMQAXAUARAhQAMgPAAgUQAAgOgIgLQgFgGgIgCQgLgBgIAHQgCACgDgBQgDgBABgHQABgKAJgGQAJgGAOAAQAHAAAMACIAOACQAGAAADgEIACgBQADAAABADQAAATgZAHQAFAMAAAMQAAAagUAXQAIAOAJAGQAJAHAOAAQAGAAADgCIAHgBQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABQAAAFgKADQgLAEgPAAQgOAAgJgEQgJgEgNgLQgSALgOAEQgOAEgQAAQghAAgYgTgAFDg+QAAAdAVAVQAUAVAbAAQALAAAHgDQAIgCAMgFQgJgJgHgMIgIgLQgOgUgOgOIgYgTIgIgGQgWAFAAAZgAP/AWQgVAAgOABQgCgBAAgDQAAgEABgBIAIgBQAKgCADgFQABgFAAgUIAAhBQAAgLgBgDQgBgEgHgFIgEgCQAAgBAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIABgEQAIgCAMgGIATgKQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQgBAWAAAYIAABDQAAAUACAFQACAFAKACIAIABQACABgBAEQAAAAAAABQAAABAAAAQAAABgBAAQAAABgBAAQgPgBgUAAgAn+AWQgWAAgMABQgCgBgBgDQAAgEACgBIAHgBQAKgCACgFQACgFAAgUIAAhBQAAgLgBgDQgCgEgHgFIgEgCIAAgDQAAgBAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQASgGATgMQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIAAAVIAAAEIAVgQQALgHAKAAQAHAAAEAFQAFAEAAAGQAAAIgGAFQgEAEgGAAQgDAAgFgCQgIgGgIAAQgIAAgGAHQgEAHAAAWIAAAyQAAAUACAFQACAGAKABIAOABQACABgBAEQAAAAAAABQAAABAAAAQgBABAAAAQAAABgBAAIgpgBgAsAAWQgVAAgPABQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBgBAAAAQAAgEACgBIAIgBQAKgCACgFQACgFAAgUIAAioQAAgQgBgFQgCgFgIgEIgEgDQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAdgKALgGQABAAAAAAQABAAABABQAAAAAAAAQABABAAAAIgBAvIAACvQAAAUACAFQACAFAKACIAJABQACABAAAEQgBADgCABQgQgBgUAAgAzoAWIgrABQAAAAAAgBQgBAAAAgBQAAAAAAgBQgBgBAAAAQAAgEACgBIAGgBQAPgDADgHQADgGAAgeIAAiNQAAgWgDgGQgDgHgMgBIgMgBQgCgCAAgDQAAgBAAgBQAAAAABgBQAAgBAAAAQAAgBABAAQAegCAyAAQAqAAAUAKQAdAOAAAhQAAASgLANQgJALgSAIQAAAFAHABQASADAOAPQASARAAAbQAAAhgZASQgZAUgxAAIgtgBgAzWhlQgEACAAAGIAAA3QAAAfAIAIQAJAKAUAAQAbAAAPgLQARgNAAgaQAAgbgPgQQgTgVgoAAQgOAAgEACgAzVjSIgEADIgBAHIAABMQAAAHADACQADABAOAAQAdgBAOgKQAPgMAAgZQAAgZgRgNQgPgMgYAAQgMAAgFACgAPvikQgFgFAAgIQAAgJAGgGQAFgFAJAAQAIAAAFAGQAFAFAAAIQAAAKgGAFQgFAFgIAAQgJAAgFgGg");
	this.shape_1.setTransform(-0.73,19.5875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape}]},20).to({state:[]},1).wait(99));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-131.2,-79.6,261,142.7);


// stage content:
(lib.BSWH_CancerHatesUs_V4_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(450));

	// BSWH_Logo
	this.instance = new lib.bswh_logo("synched",0,false);
	this.instance.setTransform(149.2,466.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1,mode:"single",startPosition:20},20).wait(430));

	// txt_Celebrating_TenYears
	this.instance_1 = new lib.txt_celebratingTenYears();
	this.instance_1.setTransform(150.05,563.25);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},9).wait(392).to({alpha:0},8).wait(41));

	// cta_btn
	this.instance_2 = new lib.ctaBtn();
	this.instance_2.setTransform(148,595.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(409).to({_off:false},0).wait(1).to({regX:8.5,regY:6.2,x:156.5,y:596.95,alpha:0.1786},0).wait(1).to({y:592.35,alpha:0.3564},0).wait(1).to({y:588,alpha:0.5237},0).wait(1).to({y:584.1,alpha:0.6735},0).wait(1).to({y:580.75,alpha:0.8027},0).wait(1).to({y:577.95,alpha:0.911},0).wait(1).to({regX:0,regY:0,x:148,y:569.45,alpha:1},0).wait(1).to({regX:8.5,regY:6.2,x:156.5,y:573.55},0).wait(1).to({y:571.9},0).wait(1).to({y:570.6},0).wait(1).to({y:569.65},0).wait(1).to({y:569},0).wait(1).to({regX:0,regY:0,x:148,y:562.4},0).wait(28));

	// txt_cancerHatesUs
	this.instance_3 = new lib.txt_cancerHatesUs();
	this.instance_3.setTransform(125.2,-51.85);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(354).to({_off:false},0).to({y:328.3},47,cjs.Ease.quadOut).wait(49));

	// image_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_338 = new cjs.Graphics().p("A1PcSMAAAg4jMAqfAAAMAAAA4jg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(338).to({graphics:mask_graphics_338,x:149,y:194.05}).wait(112));

	// safeCare_logo
	this.instance_4 = new lib.safeCare_logo();
	this.instance_4.setTransform(183.7,98.05,3.3814,3.3814,5.4832,0,0,0.1,0.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(400).to({_off:false},0).to({regX:0,scaleX:1.3334,scaleY:1.3334,rotation:0,x:183.35,alpha:1},9,cjs.Ease.quadOut).to({scaleX:1.5457,scaleY:1.5457,y:98},15,cjs.Ease.quadOut).wait(26));

	// image_05
	this.instance_5 = new lib.image_05();
	this.instance_5.setTransform(150.2,-207.3);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(338).to({_off:false},0).wait(2).to({y:-202.9},0).to({y:197.1},34,cjs.Ease.quadOut).wait(76));

	// txt_qualityCare
	this.instance_6 = new lib.txt_qualityCare();
	this.instance_6.setTransform(127.2,-54.85);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(280).to({_off:false},0).to({y:60.65},26,cjs.Ease.quadOut).wait(144));

	// image_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_255 = new cjs.Graphics().p("A1PcSMAAAg4jMAqfAAAMAAAA4jg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(255).to({graphics:mask_1_graphics_255,x:149,y:194.05}).wait(195));

	// image_04
	this.instance_7 = new lib.image_04();
	this.instance_7.setTransform(150.2,-185.3);
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(255).to({_off:false},0).wait(2).to({y:197.1},34,cjs.Ease.quadOut).wait(159));

	// txt_advancedTreatment
	this.instance_8 = new lib.txt_advancedTreatment();
	this.instance_8.setTransform(125.2,-53.85);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(197).to({_off:false},0).to({y:59.65},26,cjs.Ease.quadOut).wait(227));

	// image_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_175 = new cjs.Graphics().p("A1PcSMAAAg4jMAqfAAAMAAAA4jg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(175).to({graphics:mask_2_graphics_175,x:149,y:194.05}).wait(275));

	// image_03
	this.instance_9 = new lib.image_03();
	this.instance_9.setTransform(150.2,-185.3);
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(175).to({_off:false},0).wait(2).to({y:197.1},34,cjs.Ease.quadOut).wait(239));

	// txt_earlyDetection
	this.instance_10 = new lib.txt_earlyDetection();
	this.instance_10.setTransform(125.2,-95.35);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(115).to({_off:false},0).to({y:60.65},26,cjs.Ease.quadOut).wait(309));

	// image_mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_95 = new cjs.Graphics().p("A1PcSMAAAg4jMAqfAAAMAAAA4jg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(95).to({graphics:mask_3_graphics_95,x:149,y:194.05}).wait(355));

	// image_02
	this.instance_11 = new lib.image_02();
	this.instance_11.setTransform(150.2,-185.3);
	this.instance_11._off = true;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(95).to({_off:false},0).wait(2).to({y:197.1},34,cjs.Ease.quadOut).wait(319));

	// txt_cancerHatesFighters
	this.instance_12 = new lib.txt_cancerHatesFighters();
	this.instance_12.setTransform(127.2,-51.85);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(35).to({_off:false},0).to({y:62.65},26,cjs.Ease.quadOut).wait(389));

	// image_mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("A1PcSMAAAg4jMAqfAAAMAAAA4jg");
	mask_4.setTransform(149,194.05);

	// image_01
	this.instance_13 = new lib.image_01();
	this.instance_13.setTransform(150.2,-185.3);

	var maskedShapeInstanceList = [this.instance_13];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(14).to({y:197.1},34,cjs.Ease.quadOut).wait(402));

	// background
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(450));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(149,156.9,152,483.80000000000007);
// library properties:
lib.properties = {
	id: 'FC95E511C6C24CD7B72756EF013CB206',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Bitmap1.png", id:"Bitmap1"},
		{src:"Image_01.jpg", id:"Image_01"},
		{src:"Image_02.jpg", id:"Image_02"},
		{src:"Image_03.jpg", id:"Image_03"},
		{src:"Image_04.jpg", id:"Image_04"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['FC95E511C6C24CD7B72756EF013CB206'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;