(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG_image = function() {
	this.initialize(img.BG_image);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,250);


(lib.Epson_Logo = function() {
	this.initialize(img.Epson_Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,51);


(lib.projector_image = function() {
	this.initialize(img.projector_image);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,143);


(lib.shield_icon = function() {
	this.initialize(img.shield_icon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,108,126);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.BG_Image = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG_image();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BG_Image, new cjs.Rectangle(-150,-300,300,250), null);


(lib.txt_Tolerant = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgoBzQgRgGgJgJQgKgJgDgNQgFgOAAgQIAAgIIA1AAIAAAHQAAAPAIAKQAIAIAPABQAMAAAJgIQAIgGAAgNQgBgMgGgFQgGgGgJgDIgogQQgYgHgMgPQgMgQAAgYQgBgOAFgNQAEgMALgJQAKgJAQgGQAQgGAWABQAnAAATAQQATARABAgIAAAJIg1AAQAAgSgGgIQgGgJgOAAQgKAAgIAHQgIAFAAANQAAAJAEAGQAGAHAPAFIAiALQAbAKAMAOQALAPAAAaQAAASgGAOQgGANgMAIQgKAJgRAFQgOADgTAAQgYAAgQgEg");
	this.shape.setTransform(327.8,-75.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgECRQgLgCgGgHQgFgHgCgMQgCgLAAgSIAAiBIgeAAIAAgoIAeAAIAAhBIA5AAIAABBIAiAAIAAAoIgiAAIAAB6QAAAOAEAGQAEAFANAAIAHAAIAGgBIAAApIgTABIgTAAQgRAAgKgCg");
	this.shape_1.setTransform(312.5,-78.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AAcB1IAAicQAAgSgGgHQgGgHgNAAQgeAAAAAlIAACXIg6AAIAAjjIA4AAIAAAbIABAAQAIgSAQgHQAOgIASAAQAcAAAPAPQAPAPABAjIAACog");
	this.shape_2.setTransform(295.8,-76);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgwBtQgRgLgJgRQgIgSgCgWIgCgpQAAgYADgUQADgWAKgQQAJgRASgJQASgKAdAAQAZAAAQAHQARAJAJAPQAJAPAEAVQADAWAAAaIAAANIhzAAIAAASIACATIAFARQADAHAGAFQAFAEAHABQAPAAAHgLQAGgKADgXIA1AAQgCAogUAWQgTAUgqAAQgfABgSgLgAgMhLQgGAFgDAGIgFAOIgCAQIAAAJIA7AAIgCgXQgBgJgDgHQgDgIgGgDQgGgDgJgBQgIABgFADg");
	this.shape_3.setTransform(275.675,-75.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("ABTB1IAAifQAAgOgGgHQgFgIgMAAQgOAAgJAJQgIAJAAAVIAACVIg5AAIAAifQAAgOgGgHQgFgIgMAAQgOAAgIAJQgJAJAAAVIAACVIg6AAIAAjjIA4AAIAAAXIABAAQALgQANgGQAOgHATAAQAUAAANAJQAOAKAFARIABAAQAGgSAQgJQAOgJAVAAQAeAAANARQAOASAAAhIAAClg");
	this.shape_4.setTransform(250.075,-76);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AAcB1IAAicQAAgSgGgHQgGgHgNAAQgeAAAAAlIAACXIg6AAIAAjjIA3AAIAAAbIABAAQAKgSAPgHQANgIAUAAQAbAAAPAPQAQAPgBAjIAACog");
	this.shape_5.setTransform(223.65,-76);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgrBxQgRgHgKgPQgKgPgFgXQgEgXAAgdQAAgdAFgWQAEgWALgQQALgPARgIQARgHAYAAQAagBASAIQARAHAKAPQAKAQAFAWQAEAXAAAdQAAAdgFAWQgEAXgLAPQgLAPgRAHQgRAIgZAAQgZAAgSgHgAgQhIQgGAFgDALQgEALgBAOIAAAgIAAAgQABAPAEAKQADALAGAGQAGAGAKAAQASAAAHgTQAGgSAAgrQAAgqgGgTQgHgSgSAAQgKAAgGAGg");
	this.shape_6.setTransform(203.175,-75.7516);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("Ag7B1IAAjjIA4AAIAAAeIABAAQAIgQAMgKQAOgKASAAIAEAAIAGABIAAA4IgJgBIgJAAIgQACQgHACgGAFQgHAFgDAIQgEAHAAAMIAACIg");
	this.shape_7.setTransform(187.1,-76);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgcCZIAAjjIA5AAIAADjgAgchmIAAgyIA5AAIAAAyg");
	this.shape_8.setTransform(174.325,-79.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AggByIg7jjIA9AAIAgCiIAAAAIAgiiIA6AAIg5Djg");
	this.shape_9.setTransform(160.15,-75.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AAcB1IAAicQAAgSgGgHQgGgHgNAAQgeAAAAAlIAACXIg6AAIAAjjIA3AAIAAAbIABAAQAKgSAPgHQANgIAUAAQAbAAAPAPQAQAPgBAjIAACog");
	this.shape_10.setTransform(140.4,-76);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgwBtQgRgLgJgRQgIgSgCgWIgCgpQAAgYADgUQADgWAKgQQAJgRASgJQASgKAdAAQAZAAAQAHQARAJAJAPQAJAPAEAVQADAWAAAaIAAANIhzAAIAAASIACATIAFARQADAHAGAFQAFAEAHABQAPAAAHgLQAGgKADgXIA1AAQgCAogUAWQgTAUgqAAQgfABgSgLgAgMhLQgGAFgDAGIgFAOIgCAQIAAAJIA7AAIgCgXQgBgJgDgHQgDgIgGgDQgGgDgJgBQgIABgFADg");
	this.shape_11.setTransform(120.275,-75.75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhJCXIAAgsIAPABQAQAAAHgIQAHgJABgOIhAjjIA9AAIAhCdIABAAIAeidIA6AAIg3DUQgIAcgGASQgIARgJAKQgIAKgOADQgOADgTAAg");
	this.shape_12.setTransform(406.5,-119.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("Ag7B1IAAjjIA4AAIAAAfIABAAQAIgRAMgKQANgKATAAIAEABIAGAAIAAA4IgJgBIgJAAIgQACQgHACgGAFQgHAFgEAHQgDAJAAALIAACIg");
	this.shape_13.setTransform(391.2,-123.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgrBxQgRgHgKgPQgKgPgFgXQgEgXAAgdQAAgdAFgWQAEgWALgQQALgPARgIQARgHAYAAQAagBASAIQARAHAKAPQAKAQAFAWQAEAXAAAdQAAAdgFAWQgEAXgLAPQgLAPgRAHQgRAIgZAAQgZAAgSgHgAgQhIQgGAFgDALQgEALgBAOIAAAgIAAAgQABAPAEAKQADALAGAGQAGAGAKAAQASAAAHgTQAGgSAAgrQAAgqgGgTQgHgSgSAAQgKAAgGAGg");
	this.shape_14.setTransform(373.375,-122.8516);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgECRQgKgCgGgHQgGgHgCgMQgCgLAAgSIAAiBIgeAAIAAgoIAeAAIAAhBIA5AAIAABBIAiAAIAAAoIgiAAIAAB6QAAAOAEAGQAFAFAMAAIAGAAIAHgBIAAApIgSABIgUAAQgRAAgKgCg");
	this.shape_15.setTransform(357.25,-126.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AglByQgRgGgKgNQgLgOgGgXQgFgXAAgiQAAgjAHgXQAGgXANgOQAMgNARgGQARgFATgBQApABAVAXQAUAYAAAoIg4AAIgBgQIgEgOQgDgHgFgEQgFgEgIAAQgKAAgHAFQgGAEgEAKQgDAJgBAQIgCAhIACAkQABAPADAKQAEAKAGAEQAGAFAJgBQAOAAAHgMQAHgNAAgcIA4AAQAAAtgUAXQgUAZgvAAQgVgBgQgFg");
	this.shape_16.setTransform(341.425,-122.85);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("Ag7ByQgKgGgHgJQgGgJgDgMQgCgMAAgLQAAgQADgLQADgMAHgJQAHgHALgFQALgGAPgEIAggJQANgEAFgFQAFgHABgKQgBgOgFgHQgHgIgNABQgOAAgHAIQgHAHAAAOIAAAHIg0AAIAAgHQgBgTAHgOQAGgNALgIQALgJAOgDQAPgDARgBQAZAAAQAGQAQAEAJAKQAJAKADAMQADANABAPIAAB3IABAZIAGATIg5AAIgDgLIgDgMIgCAAQgJARgOAGQgMAFgWABQgOgBgMgFgAAMAIIgLAEQgSAEgHAIQgHAKgBAPQAAANAGAJQAFAKAMgBIALgCQAGgBAFgEQAFgFAEgHQAEgHAAgIIAAgtg");
	this.shape_17.setTransform(321.5,-122.85);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgeCaIAAi7IgeAAIAAgoIAeAAIAAgaQAAgPAEgLQAFgKAHgHQAIgGAKgDQAMgCAOAAIAfABIAAApIgGAAIgGAAQgLAAgFAEQgGAFAAAJIAAAUIAiAAIAAAoIgiAAIAAC7g");
	this.shape_18.setTransform(305.5,-126.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgeCaIAAi7IgeAAIAAgoIAeAAIAAgaQAAgPAEgLQAFgKAHgHQAIgGAKgDQAMgCAOAAIAfABIAAApIgGAAIgGAAQgLAAgGAEQgFAFAAAJIAAAUIAiAAIAAAoIgiAAIAAC7g");
	this.shape_19.setTransform(283.35,-126.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgrBxQgRgHgKgPQgKgPgFgXQgEgXAAgdQAAgdAFgWQAEgWALgQQALgPARgIQARgHAYAAQAagBASAIQARAHAKAPQAKAQAFAWQAEAXAAAdQAAAdgFAWQgEAXgLAPQgLAPgRAHQgRAIgZAAQgZAAgSgHgAgQhIQgGAFgDALQgEALgBAOIAAAgIAAAgQABAPAEAKQADALAGAGQAGAGAKAAQASAAAHgTQAGgSAAgrQAAgqgGgTQgHgSgSAAQgKAAgGAGg");
	this.shape_20.setTransform(267.125,-122.8516);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgDCRQgMgCgGgHQgFgHgCgMQgCgLAAgSIAAiBIgeAAIAAgoIAeAAIAAhBIA5AAIAABBIAiAAIAAAoIgiAAIAAB6QAAAOAFAGQADAFANAAIAGAAIAHgBIAAApIgTABIgTAAQgRAAgJgCg");
	this.shape_21.setTransform(241.1,-126.025);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AAcB1IAAidQAAgRgGgHQgGgHgNAAQgeAAAAAmIAACWIg7AAIAAjjIA4AAIAAAaIACAAQAIgRAPgHQAPgIASAAQAdAAAPAPQAOAQAAAiIAACog");
	this.shape_22.setTransform(224.4,-123.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("Ag6ByQgLgGgGgJQgHgJgCgMQgDgMAAgLQAAgQADgLQADgMAHgJQAHgHALgFQAKgGAQgEIAggJQANgEAGgFQAEgHAAgKQAAgOgFgHQgHgIgOABQgNAAgHAIQgHAHAAAOIAAAHIg1AAIAAgHQAAgTAHgOQAHgNAKgIQALgJAPgDQAOgDAQgBQAaAAAQAGQARAEAIAKQAJAKADAMQADANAAAPIAAB3IACAZIAFATIg3AAIgEgLIgEgMIgBAAQgKARgNAGQgNAFgUABQgPgBgLgFgAANAIIgNAEQgQAEgIAIQgHAKAAAPQAAANAEAJQAGAKALgBIAMgCQAGgBAGgEQAEgFAEgHQAEgHgBgIIAAgtg");
	this.shape_23.setTransform(203.75,-122.85);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("Ag7B1IAAjjIA4AAIAAAfIABAAQAIgRAMgKQANgKATAAIAEABIAGAAIAAA4IgJgBIgJAAIgQACQgHACgGAFQgHAFgEAHQgCAJgBALIAACIg");
	this.shape_24.setTransform(187.8,-123.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgwBtQgRgLgJgSQgIgRgCgWIgCgqQAAgWADgWQADgVAKgRQAJgQASgKQASgJAdgBQAZABAQAHQARAJAJAPQAJAPAEAWQADAVAAAaIAAANIhzAAIAAASIACATIAFARQADAIAGAEQAFAFAHgBQAPABAHgLQAGgLADgVIA1AAQgCAogUAUQgTAWgqAAQgfgBgSgKgAgMhLQgGAEgDAHIgFAPIgCAQIAAAJIA7AAIgCgYQgBgKgDgHQgDgGgGgEQgGgEgJABQgIgBgFAEg");
	this.shape_25.setTransform(170.325,-122.85);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgcCXIAAktIA5AAIAAEtg");
	this.shape_26.setTransform(155.725,-126.525);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgrBxQgRgHgKgPQgKgPgFgXQgEgXAAgdQAAgdAFgWQAEgWALgQQALgPARgIQARgHAYAAQAagBASAIQARAHAKAPQAKAQAFAWQAEAXAAAdQAAAdgFAWQgEAXgLAPQgLAPgRAHQgRAIgZAAQgZAAgSgHgAgQhIQgGAFgDALQgEALgBAOIAAAgIAAAgQABAPAEAKQADALAGAGQAGAGAKAAQASAAAHgTQAGgSAAgrQAAgqgGgTQgHgSgSAAQgKAAgGAGg");
	this.shape_27.setTransform(140.725,-122.8516);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AgeCXIAAj8IhCAAIAAgxIDBAAIAAAxIhCAAIAAD8g");
	this.shape_28.setTransform(120.625,-126.525);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_Tolerant, new cjs.Rectangle(108.5,-154.1,372.5,101.19999999999999), null);


(lib.txt_sureColor_f10070_endFrame = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AvmD5IAAgbIAIACQAKAAAEgFQAEgGABgIIgmiJIAkAAIAVBeIABAAIARheIAjAAIghCAQgEAQgFALQgEALgGAGQgFAGgJACQgIABgMAAgAPMDKQgLgHgEgKQgFgKgCgOIgBgaQABgNABgOQACgMAFgKQAHgKAKgFQALgGARAAQAPAAALAEQAKAFAFAKQAGAJACAMQACAOAAAPIAAAIIhGAAIABAXIADAKQACAEADAEQAEACAFAAQAJAAADgHQAFgFABgOIAgAAQgCAYgLAMQgMANgZAAQgSAAgMgGgAPhBbQgDACgCAEIgDAJIgBAQIAkAAIgBgPQgBgGgCgEQgBgEgEgDQgDgCgFAAQgGABgEACgADdDMQgKgFgGgIQgGgJgCgOQgCgOgBgRQABgRACgPQADgMAGgKQAHgJAJgFQALgEAPAAQAQgBAKAFQAKAEAHAKQAGAJADANQACAOAAASQAAARgCAOQgDAOgHAJQgGAIgKAEQgLAFgPAAQgQAAgLgEgADuBdQgEADgCAGQgCAHgBAIIAAAnQABAJACAGQACAHAEADQAEAEAGAAQAKAAAFgLQAEgMgBgZQABgagEgLQgFgMgKAAQgGAAgEAFgAggDMQgHgDgDgFQgFgGgCgGQgBgIAAgHQgBgKADgGQACgHAEgFQAFgFAGgEIAPgFIATgFQAJgDACgDQADgDABgIQAAgHgEgFQgEgEgJgBQgHAAgFAGQgDAEAAAIIAAAFIggAAIAAgFQAAgLAEgIQAEgIAGgEQAHgGAJgCQAIgCAJAAQAQAAAKADQAJADAFAGQAFAFADAIQACAIAAAIIABBYIADALIgiAAIgCgHIgBgHIgBAAQgGALgIACQgIAEgMAAQgKAAgFgEgAAKCNIgIACQgKADgEAFQgFAFABAKQAAAIACAFQAEAGAGAAIAHgBQAEgBADgDQADgCACgEQADgFAAgFIAAgbgAmnDMQgHgEgGgJIgBAAIAAAOIghAAIAAi1IAjAAIAAA5IAAAAQAGgIAHgEQAHgEAJAAQAWAAAKARQALAQAAAnQAAAmgLAQQgKARgWAAQgKAAgHgEgAmwBnQgDALAAAXQAAAWADALQAEAMALAAQAMAAADgMQAEgLgBgWQABgXgEgLQgDgLgMAAQgLAAgEALgApIDHQgJgJAAgUIAAhmIAjAAIAABeQAAAMAEADQADAFAIAAQASAAAAgXIAAhbIAjAAIAACJIghAAIAAgQIgBAAQgFAKgJAEQgIAFgMAAQgRAAgJgJgArJDCQgNgNAAgZIAAgHIAkAAIABAQQAAAFADAFQADADAFACQAFACAIAAQAHAAAHgGQAHgFAAgMQAAgGgCgEQgCgEgEgFQgDgCgGgEIgQgFQgMgFgJgEQgJgGgGgGQgFgHgDgIQgDgIAAgLQAAgbAPgOQAPgNAaAAQAMAAALADQAKADAHAGQAIAFAEAKQAEAJAAANIAAAFIgiAAQgBgNgFgHQgEgHgLAAQgGAAgEACQgEABgCADQgDAEgBADIgBAIQAAAJAEAFQADAFAMAGIAcAMQALAFAGAEQAHAFAEAGQAEAGACAHIABAPQAAAdgRANQgQANgeAAQgfAAgNgOgAtoDKQgLgHgFgKQgFgKgCgOIgBgaQAAgNACgOQACgMAGgKQAGgKALgFQAKgGASAAQAPAAAKAEQAKAFAFAKQAGAJACAMQACAOAAAPIAAAIIhGAAIABAXIADAKQACAEAEAEQADACAFAAQAIAAAFgHQAEgFACgOIAfAAQgBAYgMAMQgLANgZAAQgUAAgKgGgAtTBbQgEACgCAEIgDAJIgBAQIAlAAIgCgPQAAgGgDgEQgBgEgDgDQgEgCgFAAQgGABgDACgAOLDMQgHgBgDgEQgDgFgBgGIgBgSIAAhNIgSAAIAAgZIASAAIAAgmIAiAAIAAAmIAVAAIAAAZIgVAAIAABJQAAAIADAEQACADAIAAIAIgBIAAAZIgYABQgKAAgGgCgABeDMQgFgBgEgEQgEgFAAgGQgCgHAAgLIAAhNIgSAAIAAgZIASAAIAAgmIAiAAIAAAmIAVAAIAAAZIgVAAIAABJQABAIACAEQACADAJAAIAHgBIAAAZIgXABQgKAAgHgCgAQrDNIAAiJIAiAAIAAATIABAAQAFgKAHgGQAIgGALAAIADAAIADABIAAAgIgLAAIgJABQgEACgEADQgEACgCAGQgCAEgBAHIAABSgAM+DNIAAheQAAgLgFgFQgCgDgJAAQgSAAgBAWIAABbIgiAAIAAiJIAhAAIAAARIABAAQAFgLAKgFQAIgEAMAAQAQAAAJAJQAKAJAAAVIAABlgALBDNIAAiJIAjAAIAACJgAJwDNIAAiJIAiAAIAAATIAAAAQAGgKAHgGQAHgGALAAIAEAAIADABIAAAgIgLAAIgJABIgJAFQgDACgDAGQgDAEABAHIAABSgAHxDNIAAi1IBAAAQAOAAAKAFQAJAEAGAIQAGAHACALQADAJAAAKQAAAOgEALQgEAKgIAHQgIAGgKAEQgLACgNAAIgTAAIAABJgAIWBpIAQAAQALAAAHgGQAGgHAAgOQAAgNgFgHQgGgHgOgBIgPAAgAGBDNIAAheQAAgLgEgFQgDgDgIAAQgSAAAAAWIAABbIgjAAIAAiJIAhAAIAAARIABAAQAGgLAIgFQAJgEALAAQARAAAJAJQAJAJAAAVIAABlgACPDNIAAiJIAjAAIAACJgAhjDNIAAhfQAAgJgEgFQgDgEgHAAQgJAAgFAFQgEAGAAAMIAABaIgkAAIAAhfQAAgJgDgFQgDgEgHAAQgJAAgFAFQgEAGgBAMIAABaIgiAAIAAiJIAhAAIAAAOIAAAAQAHgJAIgEQAJgEALAAQAMAAAIAFQAJAGADALIAAAAQAEgLAJgGQAIgFAOAAQARAAAIALQAIAKAAATIAABkgAkiDNIAAiJIAjAAIAACJgAlbDNIAAi1IAkAAIAAC1gAxyDNIAAi1IA8AAQAUAAALAGQAMAGAGAMQAGALADARQACAQAAAUQAAAYgDARQgCATgIALQgHALgLAGQgNAFgSAAgAxNCyIAQAAQAKAAAGgDQAGgDADgIQADgHABgOIABg5QgBgMgDgHQgDgJgGgDQgIgEgKgBIgPAAgALBAzIAAgdIAjAAIAAAdgACPAzIAAgdIAjAAIAAAdgAkiAzIAAgdIAjAAIAAAdgALbhCQgLgDgGgLQgHgKgCgRQgDgRAAgXIACgkQABgRAFgNQAFgNAMgJQALgHAUgBQARAAALAFQAKAFAGALQAHAKADARQACAPAAAYIgBAkQgCARgFANQgGAOgLAIQgLAHgUABQgRgBgKgFgALtjYQgFADgCAHQgCAHgBALIAABNQABALACAFQACAHAFACQADACAGAAQAGAAAEgDQADgDADgGQACgIABgLIAAhMQgBgLgCgGQgDgGgDgDQgEgCgGAAQgGABgDACgAHxhCQgKgDgHgLQgHgKgCgRQgDgRAAgXIACgkQABgRAFgNQAFgNAMgJQAMgHATgBQARAAALAFQAKAFAHALQAGAKADARQACAPAAAYIgBAkQgCARgFANQgGAOgLAIQgLAHgUABQgRgBgKgFgAIDjYQgFADgCAHQgCAHgBALIAABNQABALACAFQACAHAFACQADACAGAAQAGAAAEgDQAEgDACgGQACgIABgLIAAhMQgBgLgCgGQgDgGgDgDQgEgCgGAAQgGABgDACgAF9hCQgLgDgHgLQgGgKgDgRQgDgRAAgXIACgkQABgRAFgNQAFgNAMgJQAMgHATgBQARAAALAFQAKAFAHALQAGAKADARQACAPAAAYIgBAkQgCARgFANQgGAOgLAIQgLAHgUABQgQgBgKgFgAGOjYQgFADgCAHQgCAHAAALIAABNQAAALACAFQACAHAFACQAEACAFAAQAGAAAEgDQAEgDACgGQACgIABgLIAAhMQgBgLgCgGQgDgGgDgDQgEgCgGAAQgGABgDACgAhrhCQgKgEgGgIQgGgJgDgOQgCgOAAgRQAAgRACgOQADgNAHgJQAFgJALgFQALgEAOAAQAPgBALAFQAKAEAGAKQAGAIADANQACAOAAASQAAARgCAOQgDANgHAJQgFAJgLAEQgKAFgPAAQgPAAgLgFgAhbiwQgEADgBAHQgCAGgBAJIAAAmQABAJACAGQABAHAEADQAEAEAGAAQALAAADgLQAEgMABgZQgBgagEgKQgDgMgLAAQgGAAgEAEgAkZhCQgJgEgGgIQgHgJgCgOQgDgOAAgRQAAgRADgOQADgNAGgJQAHgJAJgFQALgEAOAAQAQgBALAFQAKAEAGAKQAGAIADANQACAOAAASQAAARgCAOQgEANgFAJQgHAJgKAEQgLAFgPAAQgPAAgLgFgAkJiwQgDADgCAHQgCAGgBAJIAAAmQABAJACAGQACAHADADQAEAEAGAAQALAAAFgLQADgMAAgZQAAgagDgKQgFgMgLAAQgGAAgEAEgAmZhEQgMgGgGgNQgHgMgCgRQgBgRAAgVQAAgUABgSQACgRAHgMQAGgNAMgGQANgIAUAAQAUAAALAGQALAHAFAJQAGAKACAMIABAVIgkAAQgBgUgEgJQgEgJgOAAQgGAAgFAEQgEADgDAIQgCAIgBAOIgBAgIABAhQACANADAHQADAHAEACQAEADAHAAQAEAAAFgCQADgBADgFQAEgFABgKQACgJAAgOIAkAAQAAAPgBANQgDANgGAKQgHAJgLAGQgLAGgSAAQgUAAgNgHgAoRhDQgLgHgFgKQgEgLgCgNIgBgZQABgOABgMQACgNAFgKQAHgKAKgGQAKgFASAAQAQAAAJAEQAKAGAFAIQAGAKACAMQACANAAAPIAAAIIhFAAIAAAXIAEAKQABAFAEACQAEADAEAAQAJAAAEgHQAEgGABgNIAgAAQgBAYgMAMQgLANgaAAQgSAAgLgGgAn8ixQgEADgBADIgEAJIAAAPIAjAAIAAgOQgBgGgCgFQgCgDgDgCQgEgDgFAAQgGAAgDADgArjhGQgJgJAAgUIAAhlIAiAAIAABeQABALADADQADAFAJAAQASAAAAgXIAAhaIAjAAIAACIIgiAAIAAgQIAAAAQgGAKgJAEQgIAFgMAAQgQAAgJgJgAtkhLQgNgNAAgZIAAgHIAlAAIABARQABAEACAEQADADAFACQAFADAGAAQAIAAAHgGQAHgFAAgMQAAgFgBgFIgGgIQgDgDgHgEIgPgFIgVgJQgJgFgGgHQgGgFgDgJQgCgIAAgMQgBgbAQgNQAPgNAZAAQAMAAALADQAKADAIAFQAHAGAEAKQAEAJAAAMIAAAGIgjAAQABgNgFgHQgEgHgLAAQgHAAgEACQgDABgDADIgDAHIgBAIQAAAIADAGQAEAGALAFIAdALQAKAFAGAFQAHAFAEAFQAEAHACAGQABAHAAAIQAAAdgRANQgQANgeAAQgfAAgNgOgAJehAQABgPAFgTQAEgSAGgSQAHgSAKgTQAJgSANgTIhLAAIAAgeIBuAAIAAAbQgLAPgIATQgKARgGAUQgHASgDAUQgFAUgDASgAEThAIAAh+IgjAAIAAgYIAEAAQARAAALgGQALgHACgQIAbAAIAACzgACChAIAAi0IBlAAIAAAeIhBAAIAAAqIA9AAIAAAeIg9AAIAABOgAgNhAIAAiIIAhAAIAAASIAAAAQAGgKAHgGQAIgFAKAAIAEAAIACAAIAAAhIgKAAIgJABQgFACgEACQgDADgDAFQgDAFABAGIAABSgAi5hAIAAi0IAjAAIAAC0gApyhAIAAiIIAhAAIAAASIABAAQAFgKAHgGQAIgFALAAIADAAIADAAIAAAhIgKAAIgKABQgFACgDACQgEADgCAFQgDAFABAGIAABSg");
	this.shape.setTransform(-1.25,-134.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070_endFrame, new cjs.Rectangle(-115.1,-159.1,227.8,49.8), null);


(lib.txt_sureColor_f10070 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AvqD5IAAgbIAJACQAKAAAFgGQAEgFAAgIIgmiJIAkAAIAVBeIAAAAIASheIAjAAIghB/QgEARgFALQgDALgHAFQgFAHgIABQgJACgLAAgAPPDJQgLgGgFgLQgFgKgCgNIgBgZQAAgPACgNQACgNAFgJQAHgKAKgGQALgGASAAQAQAAAJAFQAKAFAGAJQAFAJADANQABAOAAAOIAAAIIhFAAIAAAYIAEAKQABAEAEADQADACAFAAQAJAAAEgGQAEgHABgNIAhAAQgCAZgMAMQgMANgZAAQgTAAgKgHgAPkBbQgEACgBAEIgEAJIAAAPIAjAAIAAgPQgBgFgCgFQgCgEgEgCQgDgCgGAAQgFAAgDADgADeDLQgKgEgGgIQgHgJgCgOQgCgOgBgRQABgSACgOQADgOAGgIQAHgKAKgEQAKgFAPAAQAQAAALAEQAKAEAGAKQAHAKACAMQACAOABATQgBAQgCAOQgDAOgGAJQgHAJgKAEQgLAEgPABQgQgBgKgEgADvBcQgFADgCAHQgCAGAAAJIAAAnQAAAIACAHQACAGAFAEQADADAGAAQALABAEgLQAEgMAAgZQAAgbgEgKQgEgMgLAAQgGAAgDAEgAghDMQgGgDgEgGQgDgFgDgHIgBgOQAAgKACgHQABgHAFgFQAEgEAHgEIAPgFIATgGQAJgCACgEQADgDAAgHQAAgIgDgEQgEgFgJAAQgIAAgEAFQgEAFAAAIIAAAEIgfAAIAAgEQAAgMAEgIQAEgHAGgFQAHgGAIgBQAJgDAJAAQAQAAAJADQAKADAFAGQAFAFADAIQACAIAAAJIABBXIACAMIggAAIgEgHIgBgHIgBAAQgFAKgIADQgIADgMABQgJgBgHgDgAAJCMIgHADQgKADgEAEQgFAGAAAJQAAAIADAGQADAFAHAAIAHgBIAHgDQADgCACgFQACgEAAgGIAAgagAmpDMQgGgEgGgJIAAAOIgiAAIAAi2IAjAAIAAA5IABAAQAFgHAGgFQAIgEAJAAQAXAAAKARQAJARABAnQgBAmgJAQQgKARgXAAQgKAAgIgEgAmxBmQgEAMABAXQgBAVAEAMQAEAMALAAQALAAADgMQAFgMAAgVQAAgXgFgMQgDgKgLAAQgLAAgEAKgApKDHQgIgJgBgVIAAhlIAjAAIAABeQAAALAFAEQACAFAJAAQASAAAAgYIAAhaIAjAAIAACJIgiAAIAAgRIAAAAQgFALgJAEQgJAEgMABQgRAAgJgJgArLDCQgOgNAAgZIAAgIIAlAAIABARQABAFADAEQADAEAEABQAFADAHAAQAJAAAGgGQAHgFAAgMQAAgHgCgEQgCgEgDgEIgKgHIgPgFQgNgEgIgFQgJgFgGgHQgGgGgDgIQgDgJAAgLQAAgbAOgOQAQgMAbAAQALAAALACQAKADAHAGQAIAFAFAKQADAJAAANIAAAFIgjAAQABgMgFgIQgFgGgLAAQgGAAgEABQgEABgDAEQgCADAAADIgCAJQAAAIAEAGQAEAFAMAFIAcAMQAKAFAHAFQAGAFAEAGQAEAFACAIQABAGABAIQgBAegQANQgRANgeAAQgfAAgNgOgAtrDJQgKgGgGgLQgFgKgBgNIgBgZQAAgPACgNQACgNAGgJQAFgKALgGQALgGASAAQAPAAAJAFQAKAFAGAJQAGAJACANQABAOAAAOIAAAIIhFAAIABAYIADAKQABAEAEADQADACAFAAQAJAAAFgGQAEgHABgNIAgAAQgCAZgMAMQgKANgaAAQgTAAgLgHgAtWBbQgEACgBAEIgDAJIgBAPIAkAAIgBgPQAAgFgDgFQgCgEgDgCQgDgCgGAAQgGAAgDADgAONDMQgGgCgEgDQgDgFgBgHIgBgRIAAhOIgSAAIAAgYIASAAIAAgnIAjAAIAAAnIAUAAIAAAYIgUAAIAABKQAAAIACAEQADADAHAAIAIgBIAAAZIgXAAIgRgBgABfDMQgGgCgEgDQgEgFgBgHQgBgGAAgLIAAhOIgSAAIAAgYIASAAIAAgnIAiAAIAAAnIAVAAIAAAYIgVAAIAABKQABAIACAEQADADAHAAIAIgBIAAAZIgXAAIgQgBgAQuDNIAAiJIAiAAIAAASQAGgKAHgGQAIgGALAAIADAAIADABIAAAhIgLgBIgJACQgFABgEADQgDADgDAFQgCAFAAAGIAABTgANADNIAAheQAAgMgFgEQgCgDgJAAQgSAAgBAWIAABbIgjAAIAAiJIAiAAIAAAQIABAAQAEgLAKgEQAJgFAMAAQAQAAAJAJQAKAKAAAUIAABmgALDDNIAAiJIAjAAIAACJgAJxDNIAAiJIAiAAIAAASIABAAQAFgKAHgGQAIgGALAAIADAAIAEABIAAAhIgLgBIgKACQgEABgEADQgFADgCAFQgCAFAAAGIAABTgAHyDNIAAi2IBBAAQANAAAKAFQAKAEAFAIQAGAHADALQACAJAAAKQAAAPgDAKQgFALgHAGQgIAHgLADQgLADgNAAIgTAAIAABJgAIXBpIARAAQAKAAAIgHQAFgGAAgOQABgOgGgGQgGgJgNAAIgQAAgAGCDNIAAheQAAgMgDgEQgEgDgIAAQgTAAAAAWIAABbIgiAAIAAiJIAgAAIAAAQIABAAQAGgLAJgEQAJgFALAAQARAAAJAJQAJAKAAAUIAABmgACPDNIAAiJIAjAAIAACJgAhkDNIAAhgQABgJgEgFQgDgDgIAAQgJgBgFAGQgEAFAAANIAABaIgjAAIAAhgQAAgJgEgFQgDgDgHAAQgJgBgEAGQgGAFAAANIAABaIgjAAIAAiJIAiAAIAAAOQAIgKAIgEQAHgEANAAQAMAAAIAGQAIAFADALIAAAAQAFgLAJgFQAIgGANAAQARAAAJALQAIAKAAAUIAABkgAkjDNIAAiJIAkAAIAACJgAlbDNIAAi2IAjAAIAAC2gAx1DNIAAi2IA8AAQATAAAMAGQAMAGAGAMQAHAMACAQQACAQAAAVQAAAYgCAQQgEATgHALQgHAMgMAFQgMAGgSAAgAxQCyIAQAAQAKAAAGgDQAFgDAEgJQAEgHABgNIAAg6QgBgMgEgHQgCgIgHgEQgGgEgLgBIgPAAgALDAzIAAgeIAjAAIAAAegACPAzIAAgeIAjAAIAAAegAkjAzIAAgeIAkAAIAAAegAPkhBQgLgEgGgKQgGgLgDgQQgDgSABgXIAAgkQACgRAGgNQAFgNAMgJQALgHATgBQARAAALAFQAKAFAHAKQAGAKADASQADAPAAAYIgCAkQgBARgFAOQgGAOgLAHQgLAIgVAAQgQAAgLgFgAP2jYQgEAEgCAGQgCAGgCANIAABLQACALACAHQACAGAEADQAEABAFAAQAHAAADgCQAEgDADgHQACgIAAgLIAAhNQAAgKgDgGQgCgHgEgCQgDgCgHAAQgGAAgDADgAL6hBQgLgEgHgKQgFgLgDgQQgDgSAAgXIABgkQACgRAFgNQAGgNALgJQALgHAUgBQARAAAKAFQALAFAGAKQAHAKACASQADAPAAAYIgBAkQgBARgGAOQgGAOgKAHQgMAIgUAAQgRAAgKgFgAMLjYQgDAEgDAGQgCAGgBANIAABLQABALACAHQADAGADADQAEABAGAAQAGAAAEgCQAEgDADgHQACgIAAgLIAAhNQAAgKgDgGQgDgHgDgCQgEgCgGAAQgHAAgDADgAKFhBQgLgEgGgKQgHgLgDgQQgCgSAAgXIABgkQACgRAFgNQAGgNALgJQALgHAUgBQAQAAALAFQALAFAHAKQAGAKADASQACAPAAAYIgBAkQgBARgGAOQgGAOgLAHQgLAIgUAAQgRAAgKgFgAKWjYQgDAEgDAGQgCAGgBANIAABLQABALACAHQADAGADADQAEABAGAAQAGAAADgCQAEgDADgHQACgIABgLIAAhNQgBgKgCgGQgDgHgEgCQgDgCgGAAQgHAAgDADgAAyhBQgLgEgGgIQgGgKgDgNQgCgOAAgRQAAgSACgOQADgNAHgJQAGgIALgGQAKgEAPAAQAPgBALAFQAKAFAHAJQAFAJACANQAEANAAATQAAARgEANQgCAOgHAJQgGAJgKAEQgLAFgOAAQgQAAgKgFgABCivQgEADgCAGQgCAGAAAJIAAAnQAAAJACAGQACAGAEAEQADADAHAAQAKABAEgLQAEgMAAgZQAAgagEgLQgEgMgKAAQgHABgDAEgAh7hBQgKgEgGgIQgGgKgDgNQgCgOAAgRQAAgSACgOQADgNAGgJQAHgIAKgGQAKgEAPAAQAPgBALAFQAKAFAGAJQAGAJADANQACANAAATQAAARgCANQgDAOgGAJQgGAJgLAEQgLAFgOAAQgPAAgLgFgAhrivQgEADgBAGQgCAGgBAJIAAAnQABAJACAGQABAGAEAEQAEADAGAAQALABADgLQAEgMABgZQgBgagEgLQgDgMgLAAQgGABgEAEgAj8hDQgMgHgHgMQgGgNgCgQQgBgSgBgVQABgVABgRQACgRAGgMQAHgNAMgGQANgIAUAAQAUAAALAHQALAGAFAKQAHAKAAALIACAVIglAAQAAgUgEgJQgFgJgMAAQgHAAgFAEQgEAEgCAIQgDAIgBANIgBAhIABAhQACANADAGQADAHAEADQAEACAHABIAJgCQADgCAEgFQACgFACgJQACgJAAgOIAkAAQAAAPgCANQgCAMgHAKQgFAKgMAFQgLAGgSABQgUAAgNgHgAl0hDQgLgGgFgLQgFgKgCgNIAAgZQAAgOACgNQACgNAFgKQAGgKAKgFQALgGASAAQAPAAAJAEQALAGAFAJQAGAJACAMQABANABAQIAAAIIhGAAIABAXIAEAJQABAFAEADQADADAEgBQAKAAAEgGQADgHACgMIAgAAQgCAYgMAMQgLANgZAAQgSgBgLgGgAlfiwQgEABgBAEIgEAJIgBAPIAkAAIgBgOQAAgFgCgFQgCgEgEgCQgDgDgGAAQgFABgDADgApHhFQgJgJAAgVIAAhlIAiAAIAABfQAAAKAFAEQACAEAIABQATgBAAgWIAAhbIAjAAIAACIIgiAAIAAgPIAAAAQgFAKgJAEQgJAFgMAAQgQAAgJgJgArIhKQgNgNAAgZIAAgIIAlAAIAAARQABAFADAEQACADAGADQAEACAHAAQAIgBAHgFQAHgGAAgLQAAgGgBgFQgCgDgFgFQgCgDgHgDIgPgGQgMgEgJgEQgJgFgGgHQgGgGgDgJQgCgIgBgLQAAgbAPgNQAPgOAaAAQAMAAALADQAKADAIAGQAHAGAEAJQAEAJAAAMIAAAGIgiAAQgBgMgFgIQgEgHgLAAQgGAAgEACQgEACgDADQgBADgBADIgCAIQAAAIAEAHQAEAEALAGIAcAMQALAEAGAFQAHAGAEAFQAEAGACAHQABAGAAAJQAAAcgRANQgQAOgeAAQgfAAgNgOgAtmhDQgLgGgFgLQgFgKgBgNIgCgZQAAgOACgNQACgNAGgKQAGgKALgFQAKgGASAAQAPAAAKAEQAJAGAGAJQAGAJACAMQACANAAAQIAAAIIhFAAIAAAXIADAJQACAFAEADQADADAFgBQAIAAAFgGQAEgHACgMIAfAAQgBAYgMAMQgLANgaAAQgTgBgKgGgAtRiwQgEABgCAEIgDAJIAAAPIAkAAIgCgOQAAgFgDgFQgBgEgDgCQgEgDgFAAQgGABgDADgANmhAIAHghQAEgTAGgSQAIgSAJgTQAJgSANgTIhLAAIAAgfIBvAAIAAAcQgMAQgIASQgJARgHAUQgGASgEAUQgFAUgCASgAIchAIAAh+IgkAAIAAgYIAEAAQASAAAKgHQALgGADgQIAaAAIAACzgAGKhAIAAi0IBlAAIAAAeIhBAAIAAAqIA9AAIAAAeIg9AAIAABOgACQhAIAAiIIAhAAIAAATIABAAQAFgLAIgFQAIgGALAAIADAAIACABIAAAhIgLgBIgJACQgEABgEADQgEADgCAEQgCAFgBAHIAABRgAgchAIAAi0IAiAAIAAC0gAnWhAIAAiIIAiAAIAAATIAAAAQAGgLAHgFQAIgGAKAAIAEAAIACABIAAAhIgKgBIgJACQgFABgEADQgDADgDAEQgCAFAAAHIAABRgAuuhAIAAhdQAAgLgEgFQgDgDgIAAQgTAAAAAWIAABaIgiAAIAAi0IAiAAIAAA7IABAAQAKgSAXAAQARAAAIAJQAJAJAAAVIAABkgAxJhAIAAiWIgoAAIAAgeIB0AAIAAAeIgoAAIAACWgAD+iNQgIgEgGgGQgHgGgDgHQgDgIAAgKQAAgJADgIQADgHAHgGQAGgHAIgDQAIgDAJAAQAJAAAIADQAIADAGAHQAGAGAEAHQADAIAAAJQAAAKgDAIQgEAHgGAGQgGAGgIAEQgIADgJAAQgJAAgIgDgAEDjTQgGADgEAFQgEADgDAHQgCAFAAAGQAAAHACAGQADAFAEAFQAEAEAGACQAFADAHAAQAHAAAFgDQAEgBAEgDIACgCQAEgFACgFQACgGABgHQgBgGgCgFQgCgHgEgDQgEgFgGgDQgFgBgHAAQgHAAgFABgAEXidIgLgTIgEAAIAAATIgKAAIAAgwIASAAQAJAAAFADQAFAFAAAGQAAAHgEADQgDADgGABIANAUgAEIi5IAIAAIAGgBQACgBAAgFIgBgCQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAIgDgBIgKAAg");
	this.shape.setTransform(0.35,-127.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070, new cjs.Rectangle(-113.8,-152.2,228.39999999999998,49.79999999999998), null);


(lib.txt_purposeBuilt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("Ag7B5IAAgjIANABQANAAAFgHQAGgHABgLIg0i2IAxAAIAbB+IAAAAIAYh+IAvAAIgsCqQgGAWgGAPQgGAOgHAHQgHAIgKACQgLADgRAAg");
	this.shape.setTransform(361.775,-84.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgDB0QgIgBgFgHQgFgFgCgJQgBgJAAgOIAAhoIgYAAIAAggIAYAAIAAg0IAtAAIAAA0IAcAAIAAAgIgcAAIAABiQABALADAEQADAFALAAIAFAAIAFgBIAAAhIgPAAIgPABQgOAAgIgCg");
	this.shape_1.setTransform(349.4,-90.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_2.setTransform(340.325,-90.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_3.setTransform(332.275,-90.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_4.setTransform(324.225,-90.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgHB2QgKgFgHgNIgBAAIAAATIgtAAIAAjxIAvAAIAABMIABAAQAHgLAJgFQAIgFANAAQAdAAAOAWQAOAXAAAyQAAAzgOAWQgOAWgdAAQgOAAgIgFgAgTgQQgEAPAAAdQAAAeAEAPQAEAPAQAAQAPAAAEgPQAFgPAAgeQAAgdgFgPQgEgPgPAAQgQAAgEAPg");
	this.shape_5.setTransform(311.95,-90.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AguBbQgJgEgFgIQgFgHgDgJQgCgKAAgJQAAgNADgJQACgJAGgHQAFgGAKgEQAIgFAMgDIAagHQAKgDAFgFQADgEAAgKQAAgKgEgGQgGgGgKAAQgLAAgFAHQgGAGAAALIAAAFIgqAAIAAgFQAAgQAFgKQAFgLAJgHQAJgGALgDQALgDAOAAQAUAAANAEQANAEAHAIQAIAHACALQADAKgBAMIAABfIABAUIAFAQIgtAAIgDgKIgDgJIAAAAQgJAOgKAEQgKAFgQAAQgNAAgIgFgAALAGIgKADQgOAEgGAHQgGAHAAAMQAAALAEAHQAEAIAKAAIAIgCQAFgBAFgEQAEgDADgGQADgFgBgIIAAgkg");
	this.shape_6.setTransform(295.05,-87.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_7.setTransform(283.025,-90.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_8.setTransform(274.975,-90.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_9.setTransform(263.175,-87.875);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_10.setTransform(250.475,-88.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_11.setTransform(232.075,-90.825);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgvBbQgIgEgFgIQgFgHgDgJQgCgKAAgJQAAgNADgJQACgJAGgHQAFgGAKgEQAIgFAMgDIAagHQAKgDAFgFQADgEAAgKQABgKgGgGQgFgGgKAAQgLAAgFAHQgGAGAAALIAAAFIgqAAIAAgFQAAgQAFgKQAFgLAJgHQAIgGAMgDQALgDAOAAQAUAAANAEQANAEAHAIQAIAHACALQACAKAAAMIAABfIABAUIAFAQIgtAAIgDgKIgDgJIAAAAQgIAOgLAEQgKAFgQAAQgNAAgJgFgAALAGIgKADQgOAEgGAHQgGAHAAAMQAAALAEAHQAEAIAKAAIAJgCQAEgBAFgEQAEgDADgGQACgFAAgIIAAgkg");
	this.shape_12.setTransform(219.8,-87.875);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AAWBeIAAh9QAAgPgEgFQgFgGgLAAQgYAAAAAeIAAB5IgvAAIAAi2IAtAAIAAAVIABAAQAIgNALgHQALgGAPAAQAXAAAMAMQANANAAAbIAACHg");
	this.shape_13.setTransform(203.35,-88.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgEgTQgDgSAAgYQAAgWAEgSQAEgSAIgMQAIgMAOgHQAOgGATAAQAVAAAOAGQAOAGAIAMQAIAMAEASQADASAAAXQAAAYgDASQgEASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgMg6QgGAEgCAJQgDAJgBALIAAAZIAAAaQABAMADAJQACAIAGAFQAEAFAIAAQAOAAAGgPQAFgPAAgjQAAghgFgPQgGgPgOAAQgIAAgEAFg");
	this.shape_14.setTransform(186.8,-87.8769);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_15.setTransform(174.675,-90.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgDB0QgIgBgFgHQgFgFgBgJQgCgJAAgOIAAhoIgYAAIAAggIAYAAIAAg0IAuAAIAAA0IAbAAIAAAgIgbAAIAABiQAAALADAEQADAFAKAAIAGAAIAFgBIAAAhIgPAAIgQABQgNAAgIgCg");
	this.shape_16.setTransform(165.75,-90.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AhHB7IAAjxIAtAAIAAAUIACAAQAHgNAJgGQAJgFAOAAQAdAAAOAWQANAXAAAzQAAAygNAWQgOAWgdAAQgMAAgJgFQgKgFgGgLIgBAAIAABMgAgThHQgFAPABAeQgBAdAFAPQAEAPAPAAQAQAAAEgPQAFgPAAgdQAAgegFgPQgEgPgQAAQgPAAgEAPg");
	this.shape_17.setTransform(152.45,-85.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_18.setTransform(136.025,-87.875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgeBbQgNgEgIgLQgJgLgEgTQgFgSAAgcQAAgbAGgTQAFgSAKgLQAKgLANgFQAOgEAPAAQAhAAAQATQARATAAAhIgtAAIgBgNIgDgMQgCgGgEgDQgEgDgHAAQgIAAgFAEQgFAEgDAHQgDAIgBAMIgBAbIABAdQABAMADAIQADAHAEAEQAFAEAHAAQAMAAAGgLQAFgKAAgWIAtAAQAAAkgQATQgRATglAAQgQAAgOgFg");
	this.shape_19.setTransform(120.425,-87.875);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AAbBcIgbg8IgaA8IgxAAIAyheIgwhZIAxAAIAYA3IAag3IAwAAIgvBZIAxBeg");
	this.shape_20.setTransform(104.8,-87.85);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_21.setTransform(89.225,-87.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_22.setTransform(303.475,-125.225);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgDgTQgEgSAAgYQAAgWAEgSQADgSAJgMQAIgMAOgHQAOgGATAAQAVAAAOAGQAOAGAJAMQAIAMADASQADASAAAXQAAAYgDASQgEASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgMg6QgFAEgDAJQgDAJgBALIAAAZIAAAaQABAMADAJQADAIAFAFQAEAFAIAAQAOAAAGgPQAFgPAAgjQAAghgFgPQgGgPgOAAQgIAAgEAFg");
	this.shape_23.setTransform(289.05,-125.0269);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgYB8IAAiWIgYAAIAAggIAYAAIAAgVQAAgMADgJQADgIAHgFQAGgFAIgDQAKgCALAAIAZABIAAAiIgFgBIgEAAQgKAAgEAEQgEADgBAIIAAAQIAcAAIAAAgIgcAAIAACWg");
	this.shape_24.setTransform(276.05,-128.225);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgDB0QgIgBgFgHQgFgFgCgJQgBgJAAgPIAAhnIgYAAIAAggIAYAAIAAg0IAtAAIAAA0IAcAAIAAAgIgcAAIAABiQABALADAEQADAFAKAAIAGAAIAFAAIAAAgIgPAAIgPABQgOAAgIgCg");
	this.shape_25.setTransform(258.05,-127.55);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_26.setTransform(248.975,-127.975);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_27.setTransform(240.925,-128.125);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("Ag5BSQgLgNgBgbIAAiHIAvAAIAAB9QABAPAFAGQAEAFALAAQAXABAAgfIAAh5IAwAAIAAC3IgtAAIAAgWIgCAAQgGANgNAHQgLAFgPAAQgWABgNgMg");
	this.shape_28.setTransform(228.45,-124.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AgIB2QgJgFgIgNIgBAAIAAATIgtAAIAAjxIAwAAIAABMIABAAQAGgLAKgFQAJgFANAAQAcAAAOAWQANAXAAAyQAAAzgNAWQgOAWgcAAQgOAAgKgFgAgTgQQgFAPABAdQgBAeAFAPQAEAPAPAAQAPAAAFgPQAFgPAAgeQAAgdgFgPQgFgPgPAAQgPAAgEAPg");
	this.shape_29.setTransform(211.75,-127.775);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AgvAUIAAgnIBfAAIAAAng");
	this.shape_30.setTransform(196.9,-125.675);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_31.setTransform(182.875,-125.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#353535").s().p("AggBcQgNgEgIgIQgHgHgDgLQgEgKAAgOIAAgGIArAAIAAAGQAAAMAGAHQAGAIAMAAQAKAAAHgGQAGgFAAgLQAAgJgFgFQgGgEgHgDIgfgMQgTgHgLgLQgJgMgBgUQAAgLAFgKQADgKAIgIQAJgHAMgFQANgEARAAQAgAAAPAOQAQANAAAZIAAAIIgrAAQAAgPgEgGQgFgHgLAAQgIAAgHAFQgGAFgBAKQAAAHAFAFQAEAFAMAEIAbAKQAXAHAIALQAKAMgBAVQAAAPgEAKQgGALgJAHQgJAHgMADQgNAEgOAAQgTAAgNgEg");
	this.shape_32.setTransform(167.6,-125.025);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgDgTQgEgSAAgYQAAgWAEgSQAEgSAIgMQAIgMAPgHQANgGATAAQAVAAAOAGQAOAGAJAMQAHAMADASQAEASAAAXQAAAYgEASQgDASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgMg6QgFAEgDAJQgDAJAAALIgBAZIABAaQAAAMADAJQADAIAFAFQAEAFAIAAQAPAAAFgPQAFgPAAgjQAAghgFgPQgFgPgPAAQgIAAgEAFg");
	this.shape_33.setTransform(152,-125.0269);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#353535").s().p("AhGB7IAAjxIAtAAIAAAUIABAAQAHgNAKgGQAJgFANAAQAeAAANAWQAOAXAAAzQAAAygOAWQgNAWgeAAQgNAAgIgFQgJgFgIgLIgBAAIAABMgAgThHQgEAPgBAeQABAdAEAPQAEAPAQAAQAPAAAEgPQAFgPAAgdQAAgegFgPQgEgPgPAAQgQAAgEAPg");
	this.shape_34.setTransform(135.65,-122.275);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_35.setTransform(122.125,-125.225);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#353535").s().p("Ag4BSQgMgNAAgbIAAiHIAvAAIAAB9QAAAPAEAGQAFAFAKAAQAZABAAgfIAAh5IAuAAIAAC3IgtAAIAAgWIAAAAQgIANgLAHQgLAFgPAAQgXABgMgMg");
	this.shape_36.setTransform(107.35,-124.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#353535").s().p("AhLB5IAAjxIBUAAQATAAANAGQANAGAHAKQAIAKAEAOQADANAAANQAAATgGAOQgFAOgKAIQgKAIgPAFQgOAEgQAAIgaAAIAABhgAgagLIAVAAQAOAAAJgJQAJgIAAgTQAAgSgIgKQgHgJgSAAIgUAAg");
	this.shape_37.setTransform(90.675,-127.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_purposeBuilt, new cjs.Rectangle(79.4,-150.5,369,81.3), null);


(lib.txt_industrialLevel = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AguCFQgUgGgLgLQgKgKgEgQQgGgPAAgUIAAgJIA+AAIAAAJQgBARAJAKQAKAMARAAQAPgBAJgHQAJgJAAgPQAAgNgHgGQgIgHgJgEIgvgRQgcgKgOgQQgPgTAAgbQAAgRAGgPQAFgOAMgLQAMgKASgGQATgHAZAAQAtAAAXATQAWAUAAAkIAAALIg9AAQAAgVgGgKQgHgJgRAAQgMAAgJAIQgJAGAAAOQAAALAFAHQAHAIARAGIAnANQAgALANAQQANARABAeQAAAWgIAPQgHAPgNALQgNAKgSAEQgRAFgWAAQgcAAgSgFg");
	this.shape.setTransform(459.5,-66);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AhTCSQgTggAAhKQAAhIATghQAUggApAAQATAAANAIQAOAHAKAQIACAAIAAhvIBDAAIAAFdIhBAAIAAgcIgBAAQgLATgOAHQgNAIgVAAQgpAAgUgggAgcgXQgHAVAAAqQAAArAHAWQAGAWAWAAQAWAAAHgWQAHgWAAgrQAAgqgHgVQgHgWgWAAQgWAAgGAWg");
	this.shape_1.setTransform(436.15,-69.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("Ag3B9QgUgMgKgTQgKgVgCgYIgDgyQAAgbAEgYQAEgZALgSQALgTAUgMQAVgLAhAAQAeAAATAKQASAJALASQALARAEAZQAEAYAAAfIAAAOIiFAAIAAAVIACAWIAGAUQADAJAHAFQAGAGAIAAQASAAAIgNQAHgMADgaIA9AAQgCAvgXAYQgWAYgxAAQgjAAgVgNgAgOhXQgHAGgDAHIgGARIgCATIAAAKIBEAAIgCgbQgBgLgEgIQgDgJgHgEQgHgEgKAAQgJAAgHAEg");
	this.shape_2.setTransform(412.925,-66);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("Ag3B9QgUgMgKgTQgKgVgCgYIgDgyQAAgbAEgYQAEgZALgSQALgTAUgMQAVgLAhAAQAeAAATAKQASAJALASQALARAEAZQAEAYAAAfIAAAOIiFAAIAAAVIACAWIAGAUQADAJAHAFQAGAGAIAAQASAAAIgNQAHgMADgaIA9AAQgCAvgXAYQgWAYgxAAQgjAAgVgNgAgOhXQgHAGgDAHIgGARIgCATIAAAKIBEAAIgCgbQgBgLgEgIQgDgJgHgEQgHgEgKAAQgJAAgHAEg");
	this.shape_3.setTransform(390.325,-66);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AhmCyIAAlcIBBAAIAAAcIABAAQALgSAOgJQANgHAVgBQApAAAUAhQATAhAABJQAABJgTAfQgUAhgpgBQgUABgMgIQgOgHgKgPIgCAAIAABtgAgchmQgHAVAAArQAAAqAHAWQAHAWAVAAQAXAAAGgWQAHgWAAgqQAAgrgHgVQgGgXgXAAQgVAAgHAXg");
	this.shape_4.setTransform(367.1,-62.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgvCFQgSgGgLgLQgMgKgEgQQgEgPAAgUIAAgJIA8AAIAAAJQABARAIAKQAJAMASAAQAOgBAKgHQAJgJAAgPQAAgNgIgGQgGgHgLgEIgugRQgcgKgOgQQgOgTAAgbQgBgRAGgPQAFgOAMgLQAMgKATgGQARgHAaAAQAtAAAWATQAXAUAAAkIAAALIg9AAQAAgVgHgKQgGgJgQAAQgNAAgJAIQgKAGAAAOQAAALAHAHQAFAIASAGIAoANQAfALAOAQQANARgBAeQABAWgIAPQgHAPgNALQgNAKgSAEQgSAFgVAAQgbAAgUgFg");
	this.shape_5.setTransform(343.7,-66);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAhCHIAAi1QAAgUgIgIQgGgIgPAAQgjAAAAArIAACuIhEAAIAAkGIBBAAIAAAeIABAAQAKgTASgJQAQgJAWAAQAgAAARARQASASAAAoIAADCg");
	this.shape_6.setTransform(308.95,-66.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgxCDQgVgJgMgRQgLgRgFgbQgFgaAAgjQAAggAFgaQAGgaAMgRQAMgSAVgJQAUgJAbAAQAeAAAVAIQATAIAMATQAMARAFAaQAFAaAAAhQAAAjgGAaQgEAagNARQgMASgUAIQgUAIgdAAIgDAAQgcAAgSgHgAgThUQgHAGgDANQgEAMgBARIgBAkIABAmQABARAEANQADALAHAIQAIAGALABQAVAAAHgXQAJgVgBgyQABgwgJgWQgHgVgVAAQgLAAgIAHg");
	this.shape_7.setTransform(285,-65.9999);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AghCxIAAkHIBDAAIAAEHgAghh2IAAg6IBDAAIAAA6g");
	this.shape_8.setTransform(267.425,-70.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgFCoQgMgDgGgIQgHgIgDgOQgCgNAAgUIAAiWIgiAAIAAguIAiAAIAAhLIBCAAIAABLIAoAAIAAAuIgoAAIAACOQABAPAEAHQAFAHAPAAIAHgBIAIAAIAAAvIgWAAIgWABQgUAAgMgCg");
	this.shape_9.setTransform(254.45,-69.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgrCEQgTgGgMgQQgNgQgGgbQgHgbAAgoQAAgnAIgbQAIgbAOgQQAPgPATgGQAUgHAWAAQAvAAAYAcQAYAbAAAvIhBAAIgBgTIgEgRQgEgIgGgEQgFgFgKAAQgMAAgHAGQgIAFgEALQgEALgBARIgCAnIACAqQABASAEAKQAEAMAHAFQAHAGAKAAQARAAAIgPQAIgPAAggIBBAAQAAA0gXAaQgYAcg2AAQgYAAgTgGg");
	this.shape_10.setTransform(235.825,-66);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AhSB1QgRgQAAgoIAAjDIBEAAIAAC1QgBAVAIAIQAGAIAPAAQAkAAAAgsIAAiuIBDAAIAAEHIhBAAIAAgfIgBAAQgLAUgRAIQgQAIgWAAQggAAgSgRg");
	this.shape_11.setTransform(212.3,-65.65);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhTCSQgTggAAhKQAAhIATghQAUggAqAAQASAAANAIQANAHALAQIABAAIAAhvIBEAAIAAFdIhBAAIAAgcIgBAAQgLATgOAHQgNAIgUAAQgqAAgUgggAgcgXQgHAVAAAqQAAArAHAWQAHAWAVAAQAWAAAHgWQAHgWgBgrQABgqgHgVQgHgWgWAAQgVAAgHAWg");
	this.shape_12.setTransform(187.55,-69.975);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgyCDQgTgJgNgRQgLgRgFgbQgFgaAAgjQAAggAGgaQAFgaANgRQAMgSATgJQAVgJAbAAQAeAAAUAIQAVAIAMATQALARAFAaQAFAaAAAhQAAAjgFAaQgGAagMARQgNASgTAIQgUAIgdAAIgDAAQgcAAgTgHgAgThUQgHAGgEANQgDAMgBARIgBAkIABAmQABARADANQAEALAHAIQAIAGALABQAVAAAIgXQAHgVABgyQgBgwgHgWQgIgVgVAAQgLAAgIAHg");
	this.shape_13.setTransform(163.9,-65.9999);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AhFCHIAAkGIBBAAIAAAjIABAAQAJgTAPgMQAPgLAVAAIAGAAIAGABIAABAIgLAAIgKgBIgSADQgJACgHAGQgHAGgFAJQgDAJAAANIAACdg");
	this.shape_14.setTransform(145.1,-66.275);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AhmCyIAAlcIBBAAIAAAcIABAAQALgSAOgJQANgHAVgBQApAAAUAhQATAhAABJQAABJgTAfQgUAhgpgBQgUABgMgIQgNgHgMgPIgBAAIAABtgAgchmQgHAVAAArQAAAqAHAWQAHAWAVAAQAXAAAGgWQAHgWAAgqQAAgrgHgVQgGgXgXAAQgVAAgHAXg");
	this.shape_15.setTransform(124,-62.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AghCvIAAldIBDAAIAAFdg");
	this.shape_16.setTransform(399.175,-124.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("Ag3B+QgUgMgKgVQgKgUgCgZIgDgwQAAgbAEgYQAEgaALgSQALgUAUgKQAVgMAhAAQAeAAATAJQASAKALARQALASAEAYQAEAaAAAeIAAAOIiFAAIAAAVIACAXIAGATQADAJAHAFQAGAFAIAAQASAAAIgMQAHgMADgZIA9AAQgCAugXAYQgWAYgxAAQgjAAgVgMgAgOhXQgHAFgDAIIgGARIgCASIAAALIBEAAIgCgbQgBgLgEgJQgDgHgHgFQgHgEgKAAQgJAAgHAEg");
	this.shape_17.setTransform(382.025,-119.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AglCEIhEkHIBGAAIAlC8IABAAIAki8IBDAAIhCEHg");
	this.shape_18.setTransform(359.875,-119.875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("Ag3B+QgUgMgKgVQgKgUgCgZIgDgwQAAgbAEgYQAEgaALgSQALgUAUgKQAVgMAhAAQAeAAATAJQASAKALARQALASAEAYQAEAaAAAeIAAAOIiFAAIAAAVIACAXIAGATQADAJAHAFQAGAFAIAAQASAAAIgMQAHgMADgZIA9AAQgCAugXAYQgWAYgxAAQgjAAgVgMgAgOhXQgHAFgDAIIgGARIgCASIAAALIBEAAIgCgbQgBgLgEgJQgDgHgHgFQgHgEgKAAQgJAAgHAEg");
	this.shape_19.setTransform(337.725,-119.95);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AghCvIAAldIBDAAIAAFdg");
	this.shape_20.setTransform(320.575,-124.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AhEAdIAAg5ICJAAIAAA5g");
	this.shape_21.setTransform(305.725,-120.85);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AghCvIAAldIBDAAIAAFdg");
	this.shape_22.setTransform(290.825,-124.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AhDCEQgNgHgHgKQgHgLgEgNQgDgOgBgNQAAgTAEgNQAFgNAIgKQAIgJAMgGQAMgGASgFIAmgLQAPgDAFgIQAGgGABgOQgBgOgGgKQgIgIgQAAQgPAAgIAKQgIAIAAAQIAAAHIg9AAIAAgGQAAgXAIgPQAHgPAMgKQANgJAQgFQARgEATAAQAeAAATAGQASAGALALQAKALADAOQAFAQAAARIAACKIABAcIAHAWIhBAAIgFgNIgDgOIgBAAQgMAUgQAHQgOAGgZAAQgRAAgMgGgAAPAKIgPAEQgTAEgJALQgIAKgBARQABAPAFAMQAGALAOgBIANgCQAIgCAFgFQAHgFADgHQAFgJAAgKIAAg0g");
	this.shape_23.setTransform(273.05,-119.95);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AghCxIAAkGIBDAAIAAEGgAghh2IAAg6IBDAAIAAA6g");
	this.shape_24.setTransform(255.625,-124.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AhFCHIAAkGIBCAAIAAAjIABAAQAJgTAOgMQAPgLAVAAIAGAAIAHABIAABAIgLAAIgLgBIgRADQgJACgIAGQgHAGgFAJQgDAJAAANIAACdg");
	this.shape_25.setTransform(242.7,-120.225);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgFCoQgMgDgHgIQgGgIgDgOQgCgNAAgUIAAiWIgjAAIAAguIAjAAIAAhLIBDAAIAABLIAnAAIAAAuIgnAAIAACOQgBAPAFAHQAEAHAPAAIAIgBIAIAAIAAAvIgWAAIgWABQgUAAgMgCg");
	this.shape_26.setTransform(226.4,-123.575);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AguCEQgUgFgLgLQgLgLgDgPQgGgQAAgSIAAgJIA+AAIAAAIQgBARAKALQAIALASgBQAOABAKgJQAJgHAAgQQAAgNgHgHQgHgGgKgEIgvgRQgcgKgOgRQgPgSAAgcQABgPAFgPQAGgOAMgMQALgKASgHQASgGAaAAQAtAAAXAUQAWATAAAkIAAALIg9AAQAAgVgGgJQgHgKgRAAQgLAAgKAHQgKAHAAAPQABAJAFAJQAHAHARAFIAnAOQAhALAMARQAOARAAAdQgBAVgGAQQgIAQgNAKQgNAKgSAFQgSAEgVAAQgcAAgSgGg");
	this.shape_27.setTransform(208.2,-119.95);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AhRB2QgSgSAAgnIAAjCIBDAAIAAC0QAAAVAIAIQAGAIAPAAQAjAAAAgsIAAitIBEAAIAAEGIhBAAIAAgfIgBAAQgKAUgSAIQgQAJgWAAQggAAgRgRg");
	this.shape_28.setTransform(185.15,-119.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AhTCSQgTggAAhKQAAhIATghQAUggApAAQAUAAAMAIQANAHAMAQIABAAIAAhvIBDAAIAAFdIhBAAIAAgcIgBAAQgLATgOAHQgNAIgVAAQgpAAgUgggAgcgXQgHAVAAAqQAAArAHAWQAGAWAWAAQAWAAAHgWQAHgWAAgrQAAgqgHgVQgHgWgWAAQgWAAgGAWg");
	this.shape_29.setTransform(160.4,-123.925);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AAhCHIAAi1QAAgUgIgIQgGgIgPAAQgkAAABArIAACuIhEAAIAAkGIBBAAIAAAeIABAAQAKgTASgJQAQgJAWAAQAgAAASARQARASAAAoIAADCg");
	this.shape_30.setTransform(136.25,-120.225);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgiCvIAAldIBFAAIAAFdg");
	this.shape_31.setTransform(117.775,-124.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_industrialLevel, new cjs.Rectangle(109.5,-155.8,369,115.9), null);


(lib.printer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.projector_image();
	this.instance.setTransform(-393.95,-153.15,1.2254,1.2254);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_mc, new cjs.Rectangle(-393.9,-153.1,392.09999999999997,175.2), null);


(lib.Epson_Logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Epson_Logo();
	this.instance.setTransform(-88.05,-36,0.5856,0.5856);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Epson_Logo_1, new cjs.Rectangle(-88,-36,90.2,29.9), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape.setTransform(61.025,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_1.setTransform(47.475,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag1A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAfABAWAVQAXAXAAAeQAAAggXAVQgWAXgfAAQgfAAgWgXgAghghQgOAOAAATQAAAUAOAOQAOAPATAAQAUAAAOgPQAOgOAAgUQAAgTgOgOQgOgPgUAAQgTAAgOAPg");
	this.shape_2.setTransform(31.275,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBBMQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIglhSIgBAAIgMBOQAAADgEABIgSAAQgFgBABgEIAZiNQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAuBiIAAAAIAuhiQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAIADAAQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIAZCNQABAEgFABIgTAAQgDgBgBgDIgMhOIgBAAIglBSQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(13.1508,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BMQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIhUheIgBAAIAABZQAAAEgEABIgTAAQgEgBAAgEIAAiMQAAgDAEgBIADAAQABABAAAAQAAAAABAAQAAAAABAAQAAABABAAIBUBaIAAAAIAAhVQAAgFAFAAIATAAQAEAAAAAFIAACMQAAADgEABg");
	this.shape_4.setTransform(-10,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_5.setTransform(-25.075,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAwBLQgEgBgCgEIgLgWIg+AAIgKAWQgBAEgFABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIBBiNQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIACAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIBACNQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAVAYIgVgtIAAAAIgUAtIApAAg");
	this.shape_6.setTransform(-39.85,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_7.setTransform(-52.925,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBKQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAB1IA0AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_8.setTransform(-64.475,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_9.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,162.5,51.5), null);


(lib.shield_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon();
	this.instance.setTransform(-54,-63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shield_mc, new cjs.Rectangle(-54,-63,108,126), null);


(lib.gauge_needle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#06539E").s().p("AhYBiIgCgCIgDgDQgmgmAAg3QAAg2AmgnQAngmA2AAQA3AAAmAmIADADIACACQAiAmAAAyQAAA3gnAmQgmAng3AAQgyAAgmgig");
	this.shape.setTransform(-1.125,0.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_1.setTransform(33.9503,-32.507);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(6).p("AkNFzIKfryIgDgKQgJgDgBABQgBACsMKWQgKALgCASQgFAlAlAnQAeAfAmgMQAbgIAIgOg");
	this.shape_2.setTransform(34.1373,-32.507);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_3.setTransform(33.9503,-32.507);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.gauge_needle, new cjs.Rectangle(-16.3,-75.1,94.1,89.3), null);


(lib.checkMark_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(14).p("AgwgMQAgARAdAX");
	this.shape.setTransform(30.8836,-45.505);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(14).p("AiSgqQCCAUBnBQ");
	this.shape_1.setTransform(23.5006,-48.4675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(14).p("Ai6grQAZgCAbAAQC2AACLBq");
	this.shape_2.setTransform(13.5125,-48.805);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(14).p("AkvAjQB+hQCfAAQC2AACMBq");
	this.shape_3.setTransform(1.8625,-48.805);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(14).p("AmdDIQAnhtBYhYQCdibDcAAQC3AACMBr");
	this.shape_4.setTransform(-9.1375,-38.1235);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(14).p("AmLFqQghhYAAhlQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_5.setTransform(-10.6375,-17.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(14).p("AhnICQhcgnhMhMQididAAjdQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_6.setTransform(-10.6375,-2.0625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(14).p("AG9GQQiWCHjNAAQjdAAicidQidicAAjeQAAjdCdicQCcidDdAAQC3AACLBs");
	this.shape_7.setTransform(-9,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(14).p("AIWgeQABAPAAAPQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_8.setTransform(-0.025,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#06539E").ss(14).p("AHjjoQA0BqAAB+QAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_9.setTransform(-0.025,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#06539E").ss(14).p("AGdlTQB6CRAADCQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACLBs");
	this.shape_10.setTransform(-0.025,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#06539E").ss(14).p("AIXAAQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQDdAACdCdQCdCcAADdg");
	this.shape_11.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_11}]},26).to({state:[]},1).to({state:[{t:this.shape_11}]},8).wait(98));

	// Layer_3
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#06539E").ss(14,2,1).p("AgJgKIATAV");
	this.shape_12.setTransform(-19.3125,1.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#06539E").ss(14,2,1).p("AgkgmIBJBN");
	this.shape_13.setTransform(-16.6125,4.1875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#06539E").ss(14).p("AAZgYIgyAx");
	this.shape_14.setTransform(-4.4,11.7375);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#06539E").ss(14,1,1).p("AAXAYIgtgv");
	this.shape_15.setTransform(-9.275,11.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#06539E").ss(14,2,1).p("AgrgtIBXBb");
	this.shape_16.setTransform(-15.975,4.85);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#06539E").ss(14).p("ABEhCIiHCF");
	this.shape_17.setTransform(-0.125,7.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#06539E").ss(14).p("ACAh9Ij/D7");
	this.shape_18.setTransform(5.8875,1.6125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#06539E").ss(14).p("AChieIlBE9");
	this.shape_19.setTransform(9.175,-1.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#06539E").ss(14).p("ACtioIlZFR");
	this.shape_20.setTransform(10.3,-2.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#06539E").ss(14).p("ACoijIlPFH");
	this.shape_21.setTransform(9.8,-2.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_12}]},8).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_17}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_18}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_20}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_21}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},22).to({state:[]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},8).wait(98));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-60.4,152.7,152.6);


(lib.shield_icon_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// shield_mc (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_5 = new cjs.Graphics().p("AAJKEQgggIgigDQibgLiljDQhHhUguhdQgwhfgIhMQgMh6AEieQAFjJAigpQAigpDghRQDGhHBCgMQAxgID4BdQD6BeAHAlQADBsAAB0QAADpgNAsQgpCPgjBDQhZCuijBiQidBegTAEIgGAAQgLAAgRgFg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(5).to({graphics:mask_graphics_5,x:-0.325,y:-0.7371}).wait(113));

	// shine
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4qPKMArTglTIGDHBMgrTAlSg");
	this.shape.setTransform(-110.55,-108.575);
	this.shape._off = true;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGDHBMgrTAlSg");
	this.shape_1.setTransform(-102.85,-100.925);
	this.shape_1._off = true;

	var maskedShapeInstanceList = [this.shape,this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(5).to({_off:false},0).wait(1).to({x:-108.65,y:-106.675},0).to({_off:true},1).wait(1).to({_off:false,x:-93.25,y:-91.325},0).to({_off:true},1).wait(3).to({_off:false,x:-16.3,y:-14.775},0).wait(1).to({x:11.6,y:12.975},0).wait(1).to({x:36.6,y:37.875},0).wait(1).to({x:57.75,y:58.925},0).wait(1).to({x:75.05,y:76.125},0).wait(1).to({x:88.55,y:89.525},0).wait(1).to({x:98.15,y:99.125},0).to({_off:true},1).wait(99));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(7).to({_off:false},0).to({_off:true},1).wait(1).to({_off:false,x:-79.8,y:-77.925},0).wait(1).to({x:-62.45,y:-60.725},0).wait(1).to({x:-41.3,y:-39.675},0).to({_off:true},1).wait(7).to({_off:false,x:103.9,y:104.875},0).wait(1).to({x:105.85,y:106.775},0).wait(98));

	// shield_mc
	this.instance = new lib.shield_mc();
	this.instance.setTransform(0,0,0.7857,0.7857);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.7921,scaleY:0.7921,alpha:0.121},0).wait(1).to({scaleX:0.8091,scaleY:0.8091,alpha:0.4415},0).wait(1).to({scaleX:0.8386,scaleY:0.8386,alpha:1},0).wait(1).to({scaleX:0.9035,scaleY:0.9035},0).wait(1).to({scaleX:0.977,scaleY:0.977},0).wait(1).to({scaleX:1.0343,scaleY:1.0343},0).wait(1).to({scaleX:1.0671,scaleY:1.0671},0).wait(1).to({scaleX:1.0794,scaleY:1.0794},0).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).wait(106));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.3,-68,116.6,136);


(lib.shield_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon_1("synched",0,false);
	this.instance.setTransform(4,-68.55);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(47).to({startPosition:47},0).to({_off:true},1).wait(312));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_Tolerant();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(39).to({_off:true},1).wait(312));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54.2,-136.5,535.2,136);


(lib.gauge_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// gauge_needle
	this.instance = new lib.gauge_needle();
	this.instance.setTransform(0.15,-0.95,0.0838,0.0838,-132.9925,0,0,0.1,0.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({regX:-0.3,regY:0.5,scaleX:1,scaleY:1,rotation:-132.9917,y:-0.9},5).wait(1).to({regX:31.7,regY:-30.5,rotation:-133.4994,x:-44.25,y:-2.75},0).wait(1).to({rotation:-134.6077,x:-44.3,y:-1.95},0).wait(1).to({regX:-0.1,regY:0.5,scaleX:0.9999,scaleY:0.9999,rotation:-136.3899,x:0.15,y:-1.05},0).to({regX:-0.2,scaleX:1,scaleY:1,rotation:6.0191,x:0.25,y:-0.75},11,cjs.Ease.quadInOut).to({regY:0.4,rotation:-1.643,x:0.2,y:-0.85},3).to({regY:0.3,rotation:3.7245,x:0.3,y:-0.95},3).to({rotation:-1.0125,x:0.25},3).to({rotation:3.7245,x:0.3},3).to({rotation:-0.2544},3).to({rotation:3.7245},3).to({rotation:-1.4769,x:0.25},3).to({rotation:3.7245,x:0.3},3).wait(37));

	// gauge_dial
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(15).p("AgmDdQAAjJBVil");
	this.shape.setTransform(-76.2611,-24.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(15).p("AhcEyQAAk2DNji");
	this.shape_1.setTransform(-70.8283,-33.4625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(15).p("Aj1GiQAAlMDqjqQCJiKCsg4");
	this.shape_2.setTransform(-55.508,-44.6875);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(15).p("AoDG2QAAlMDqjqQDrjqFLAAQB6AABtAf");
	this.shape_3.setTransform(-28.5375,-46.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(15).p("AqrG2QAAlMDqjqQDrjqFLAAQFNAADqDq");
	this.shape_4.setTransform(-11.75,-46.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(15).p("AsFG2QAAlMDqjqQDrjqFLAAQFMAADrDqQB5B6A7CS");
	this.shape_5.setTransform(-2.7375,-46.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(15).p("AsbG2QAAlMDrjqQDrjqFKAAQFNAADqDqQC3C2ApDx");
	this.shape_6.setTransform(-0.5875,-46.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(15).p("AsgG2QAAlMDrjqQDrjqFKAAQFNAADqDqQDXDWATEo");
	this.shape_7.setTransform(-0.0875,-46.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(15).p("AshG2QAAlMDrjqQDrjqFLAAQFMAADrDqQDrDqAAFM");
	this.shape_8.setTransform(0,-46.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).wait(71));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-108.4,-117.8,196.10000000000002,182.7);


(lib.checkMark_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// checkMark_anim
	this.instance = new lib.checkMark_anim("synched",0,false);
	this.instance.setTransform(9.8,-51.75,1,1,0,0,0,15.8,15.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(26).to({startPosition:26},0).to({_off:true},1).wait(12).to({_off:false,regX:1.5,regY:2.2,x:-4.5,y:-65.35,startPosition:47},0).wait(1).to({regX:0,regY:0,scaleX:0.8972,scaleY:0.8972,x:-5.0478,y:-71.7827,startPosition:48},0).wait(1).to({scaleX:0.8081,scaleY:0.8081,x:-4.223,y:-75.449,startPosition:49},0).wait(1).to({scaleX:0.7444,scaleY:0.7444,x:-3.6326,y:-78.0732,startPosition:50},0).wait(1).to({scaleX:0.7035,scaleY:0.7035,x:-3.2538,y:-79.7571,startPosition:51},0).wait(1).to({regX:1.4,regY:2.2,scaleX:0.6798,scaleY:0.6798,x:-2.05,y:-79.2,startPosition:52},0).to({_off:true},1).wait(315));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_purposeBuilt();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(18).to({_off:true},1).wait(12).to({_off:false},0).wait(5).to({_off:true},1).wait(315));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-88,-147.1,536.4,171.79999999999998);


(lib.gauge_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_10
	this.instance = new lib.gauge_anim("synched",0,false);
	this.instance.setTransform(2.05,-64.8,1,1,0,0,0,0,-38.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25).to({startPosition:25},0).to({_off:true},1).wait(2).to({_off:false,startPosition:28},0).to({_off:true},1).wait(60).to({_off:false,startPosition:45},0).to({regX:0.1,regY:-38.9,scaleX:0.8707,scaleY:0.8707,x:-8.85,y:-71.45,startPosition:50},5,cjs.Ease.quadOut).to({_off:true},1).wait(265));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_industrialLevel();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(17).to({_off:true},1).wait(2).to({_off:false},0).to({_off:true},1).wait(60).to({_off:false},0).wait(5).to({_off:true},1).wait(265));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.9,-143.8,583.4,153.3);


// stage content:
(lib.Epson_DyeSub_V4_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(238));

	// Epson_Logo
	this.instance = new lib.Epson_Logo_1();
	this.instance.setTransform(80.75,40.55,0.8039,0.8039);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},8).wait(230));

	// ctaBtn_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_195 = new cjs.Graphics().p("Am4CXQgjAAAAgjIAAAAIAAjnQAAgjAjAAIAAAAINxAAQAjAAAAAjIAAAAIAADnQAAAjgjAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(195).to({graphics:mask_graphics_195,x:143.1144,y:120.6144}).wait(43));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.1,-10.9,14.2,10.8).s().p("AoLGHIL8vmIEbDZIr8Pmg");
	this.shape_1.setTransform(73.825,102.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.1,-10.9,14.2,10.8).s().p("AoMGIIL9vnIEcDZIr9Png");
	this.shape_2.setTransform(79.225,104.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.2,-10.9,14.2,10.8).s().p("AoMGIIL9voIEcDZIr9Pog");
	this.shape_3.setTransform(85.975,106.925);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.2,-10.9,14.2,10.9).s().p("AoNGIIL+vpIEdDZIr+Pqg");
	this.shape_4.setTransform(95.4,110.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.2,-10.9,14.3,10.9).s().p("AoOGJIMAvrIEdDaIsAPrg");
	this.shape_5.setTransform(107.55,114.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.2,-10.9,14.3,10.9).s().p("AoPGKIMBvuIEeDbIsBPug");
	this.shape_6.setTransform(122.4,119.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.3,-11,14.3,10.9).s().p("AoQGLIMDvwIEeDbIsEPwg");
	this.shape_7.setTransform(139.95,125.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.3,-11,14.4,11).s().p("AoSGMIMGvzIEfDcIsGPzg");
	this.shape_8.setTransform(157.475,130.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.3,-11,14.4,11).s().p("AoTGNIMHv2IEgDdIsIP2g");
	this.shape_9.setTransform(172.325,135.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.4,-11,14.4,11).s().p("AoUGOIMJv4IEgDdIsJP4g");
	this.shape_10.setTransform(184.475,139.925);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.4,-11.1,14.4,11).s().p("AoVGOIMKv4IEhDcIsKP5g");
	this.shape_11.setTransform(193.9,143.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.5,-11.1,14.4,11).s().p("AoVGOIMKv5IEhDdIsLP6g");
	this.shape_12.setTransform(200.65,145.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.5,-11.1,14.4,11).s().p("AoWGPIMLv7IEiDeIsMP7g");
	this.shape_13.setTransform(204.7,146.725);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1,p:{x:73.825,y:102.85}}]},195).to({state:[{t:this.shape_1,p:{x:75.175,y:103.3}}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13,p:{x:204.7,y:146.725}}]},1).to({state:[{t:this.shape_13,p:{x:206.05,y:147.175}}]},1).wait(29));

	// ctaBtn
	this.instance_1 = new lib.ctaBtn();
	this.instance_1.setTransform(143.15,120.65,0.5859,0.5859,0,0,0,0.1,0.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(185).to({_off:false},0).to({alpha:1},10).wait(43));

	// txt_sureColor_f10070
	this.instance_2 = new lib.txt_sureColor_f10070_endFrame();
	this.instance_2.setTransform(149.05,222.95);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(180).to({_off:false},0).to({y:208.95,alpha:1},12,cjs.Ease.quadOut).wait(46));

	// printer_mc
	this.instance_3 = new lib.printer_mc();
	this.instance_3.setTransform(394.25,247.5,0.7752,0.7752,0,0,0,0.7,0.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(172).to({_off:false},0).to({x:304.25,alpha:1},13,cjs.Ease.quadOut).wait(53));

	// shield_animation
	this.instance_4 = new lib.shield_animation("synched",0,false);
	this.instance_4.setTransform(153.1,208.6,0.4878,0.4878,0,0,0,219.2,-67.8);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(114).to({_off:false},0).wait(48).to({mode:"single",startPosition:21},0).to({alpha:0},9).to({_off:true},1).wait(66));

	// checkMark_animation
	this.instance_5 = new lib.checkMark_animation("synched",0,false);
	this.instance_5.setTransform(173.3,151.55,0.6266,0.6266,0,0,0,196.8,-69.6);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(85).to({_off:false},0).wait(27).to({startPosition:39},0).to({y:143.55,mode:"single",startPosition:44},5,cjs.Ease.quadOut).wait(45).to({startPosition:44},0).to({alpha:0},9).to({_off:true},1).wait(66));

	// gauge_animation
	this.instance_6 = new lib.gauge_animation("synched",0,false);
	this.instance_6.setTransform(141.1,120.15,0.4819,0.4819,0,0,0,190.2,-43.1);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(57).to({_off:false},0).wait(26).to({mode:"single",startPosition:28},0).to({y:87.15},6,cjs.Ease.quadOut).wait(23).to({mode:"synched",startPosition:89,loop:false},0).to({mode:"single",startPosition:94},5,cjs.Ease.quadOut).wait(45).to({startPosition:94},0).to({alpha:0},9).to({_off:true},1).wait(66));

	// txt_sureColor_f10070
	this.instance_7 = new lib.txt_sureColor_f10070();
	this.instance_7.setTransform(149.05,222.95);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(16).to({_off:false},0).to({y:208.95,alpha:1},9,cjs.Ease.quadOut).wait(23).to({alpha:0},8).to({_off:true},1).wait(181));

	// printer_mc
	this.instance_8 = new lib.printer_mc();
	this.instance_8.setTransform(424.55,243.35,0.787,0.787,0,0,0,0.4,0.5);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:304.05,alpha:1},16,cjs.Ease.quadInOut).wait(32).to({alpha:0},8).to({_off:true},1).wait(181));

	// BG_Image
	this.instance_9 = new lib.BG_Image();
	this.instance_9.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(52).to({regX:0.2,regY:0.1,scaleX:3.6566,scaleY:3.6566,x:118.95,y:515.95},13,cjs.Ease.quadOut).wait(97).to({regX:0,regY:0,scaleX:1,scaleY:1,x:150,y:300},9,cjs.Ease.quadOut).wait(67));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-280.3,-456.4,947,789.2);
// library properties:
lib.properties = {
	id: '3E1D9D289AAA471FB8DD4F28FE5CF1AF',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG_image.jpg", id:"BG_image"},
		{src:"Epson_Logo.png", id:"Epson_Logo"},
		{src:"projector_image.png", id:"projector_image"},
		{src:"shield_icon.png", id:"shield_icon"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3E1D9D289AAA471FB8DD4F28FE5CF1AF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;