(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Epson_Logo = function() {
	this.initialize(img.Epson_Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,131,48);


(lib.image_01 = function() {
	this.initialize(img.image_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,359,144);


(lib.image_01_LG = function() {
	this.initialize(img.image_01_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,302,356);


(lib.image_02 = function() {
	this.initialize(img.image_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,359,144);


(lib.image_02_LG = function() {
	this.initialize(img.image_02_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,302,356);


(lib.image_03 = function() {
	this.initialize(img.image_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,359,144);


(lib.image_03_LG = function() {
	this.initialize(img.image_03_LG);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,302,356);


(lib.Printer = function() {
	this.initialize(img.Printer);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,174);


(lib.printer_light = function() {
	this.initialize(img.printer_light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,163,22);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_onARoll = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ASMCPIAAghIAMABQAMAAAFgGQAGgHAAgKIgwirIAuAAIAaB2IABAAIAWh2IAsAAIgqCfQgFAWgGANQgFANgHAIQgHAHgKACQgLACgPAAgAAlBWQgNgFgJgLQgHgMgEgRQgCgRAAgWQAAgVADgRQADgRAJgMQAHgLAOgGQANgGASAAQAUAAANAFQANAGAIAMQAIALADARQADARAAAWQAAAWgDARQgEARgIALQgIALgNAGQgNAFgTAAIgDAAQgSAAgLgFgAA4g1QgEAEgDAIQgCAIAAALIAAAwQAAALACAIQADAIAEAFQAFAEAIAAQAOAAAFgOQAFgOAAggQAAgggFgOQgFgOgOAAQgIAAgFAFgAsYBWQgNgFgJgLQgHgMgEgRQgCgRAAgWQgBgVAEgRQAEgRAHgMQAJgLANgGQANgGASAAQAUAAANAFQANAGAIAMQAIALADARQADARAAAWQAAAWgEARQgDARgIALQgIALgNAGQgNAFgTAAIgDAAQgSAAgLgFgAsEg1QgGAEgCAIQgCAIAAALIAAAwQAAALACAIQACAIAGAFQAFAEAHAAQAOAAAFgOQAFgOAAggQAAgggFgOQgFgOgOAAQgHAAgFAFgAQfBXQgNgEgIgKQgIgLgFgRQgDgRAAgaQAAgaAEgRQAGgSAJgKQAJgLANgEQANgEAPAAQAfAAAQASQAPASAAAfIgqAAIgBgNIgDgLQgCgFgEgDQgEgDgGAAQgJAAgEAEQgFADgDAIQgDAHAAALIAAA0QAAAMADAHQADAHAEAEQAFADAHAAQAMAAAEgJQAFgKABgVIAqAAQAAAigPASQgQARgjAAQgRAAgLgEgALxBTQgNgIgHgNQgGgNgCgQIgBghQABgQACgQQACgQAIgNQAGgMAOgHQAOgIAWAAQATAAAMAGQANAHAGALQAHALAEAQQACARAAAUIAAAIIhYAAIABAdIAFANQACAFAEAEQAEADAGAAQAMAAAEgIQAGgIABgQIApAAQgCAegOAQQgQAPgfAAQgYAAgOgIgAMMg3QgEADgCAFIgFALIgBATIAtAAIAAgRQgCgIgCgFQgDgFgDgDQgFgDgHAAQgGAAgFADgAIWBYQgMgEgHgHQgHgHgDgKQgDgKAAgNIAAgFIAoAAIAAAFQgBALAHAHQAGAHAKAAQALAAAGgFQAGgFAAgKQAAgJgFgEQgEgEgHgDIgfgLQgTgGgIgLQgKgMAAgSQAAgLADgJQAEgJAIgHQAIgIALgEQAMgEASAAQAdAAAPANQAOANAAAXIAAAHIgnAAQAAgNgFgHQgEgGgLAAQgIAAgHAFQgFAEgBAKQAAAGAFAFQAEAFAKAEIAbAJQAVAHAJAKQAIAMAAATQAAAOgFAKQgEAKgJAHQgJAHgLACQgLADgOAAQgUAAgMgDgAFLBYQgMgEgIgHQgHgHgDgKQgCgKAAgNIAAgFIAnAAIAAAFQAAALAGAHQAGAHALAAQAKAAAHgFQAFgFAAgKQAAgJgEgEQgFgEgGgDIgggLQgSgGgJgLQgKgMAAgSQABgLADgJQADgJAJgHQAHgIAMgEQAMgEARAAQAeAAAOANQAPANAAAXIAAAHIgoAAQABgNgFgHQgEgGgMAAQgIAAgGAFQgGAEAAAKQAAAGAEAFQAEAFALAEIAbAJQAUAHAJAKQAIAMABATQgBAOgEAKQgFAKgJAHQgIAHgLACQgMADgOAAQgTAAgMgDgAhmBXQgMgEgIgKQgJgLgDgRQgFgRAAgaQAAgaAGgRQAEgSAKgKQAJgLANgEQAMgEAQAAQAfAAAPASQAQASAAAfIgrAAIAAgNIgDgLQgCgFgEgDQgEgDgGAAQgIAAgGAEQgFADgCAIQgDAHgBALIAAA0QABAMADAHQADAHAEAEQAFADAHAAQALAAAGgJQAEgKAAgVIArAAQAAAigQASQgOARgkAAQgQAAgNgEgAmiBTQgNgIgHgNQgGgNgCgQIgBghQAAgQACgQQACgQAIgNQAHgMAOgHQANgIAXAAQATAAAMAGQAMAHAHALQAHALADAQQADARAAAUIAAAIIhYAAIABAdIAEANQADAFADAEQAEADAGAAQAMAAAFgIQAFgIACgQIAoAAQgBAegPAQQgPAPggAAQgXAAgOgIgAmIg3QgDADgDAFIgEALIgBATIAtAAIgBgRQgBgIgDgFQgCgFgEgDQgEgDgIAAQgGAAgFADgAv6BYQgMgEgIgHQgHgHgDgKQgCgKAAgNIAAgFIAnAAIAAAFQAAALAGAHQAGAHALAAQAKAAAHgFQAFgFAAgKQAAgJgEgEQgFgEgGgDIgggLQgSgGgJgLQgKgMAAgSQABgLADgJQADgJAJgHQAHgIAMgEQAMgEARAAQAeAAAOANQAPANAAAXIAAAHIgoAAQABgNgFgHQgEgGgMAAQgIAAgGAFQgGAEAAAKQAAAGAEAFQAEAFALAEIAbAJQAUAHAJAKQAIAMAAATQAAAOgEAKQgFAKgJAHQgIAHgLACQgMADgOAAQgTAAgMgDgAyhBQQgLgLAAgaIAAh+IAtAAIAAB1QgBAOAFAFQAEAFALAAQAWAAAAgcIAAhxIAtAAIAACrIgqAAIAAgUIgBAAQgHAMgMAGQgKAFgPAAQgVAAgMgLgA0ZBXQgNgEgIgKQgJgLgDgRQgEgRgBgaQABgaAEgRQAFgSAKgKQAJgLANgEQAMgEAQAAQAfAAAPASQAQASAAAfIgrAAIAAgNIgDgLQgCgFgEgDQgEgDgGAAQgJAAgEAEQgFADgDAIQgCAHgCALIAAA0QACAMACAHQADAHAEAEQAFADAHAAQALAAAGgJQAEgKAAgVIArAAQAAAigQASQgOARgkAAQgRAAgLgEgAKiBXQgJgCgEgFQgFgFgBgJQgCgJAAgNIAAhhIgWAAIAAgeIAWAAIAAgyIAsAAIAAAyIAaAAIAAAeIgaAAIAABcQAAAKAEAEQADAFAJAAIAKgBIAAAfIgcABQgOAAgHgCgAtvBXQgIgCgEgFQgFgFgBgJQgCgJAAgNIAAhhIgXAAIAAgeIAXAAIAAgyIAsAAIAAAyIAZAAIAAAeIgZAAIAABcQAAAKADAEQADAFAJAAIAKgBIAAAfIgcABQgNAAgIgCgAUVBYIAAgyIArAAIAAAygAO9BYIAAh2QAAgNgEgGQgEgFgKAAQgYAAAAAdIAABxIgsAAIAAirIAqAAIAAAUIABAAQAHgNALgGQAMgGAOAAQAVAAAMAMQALALAAAaIAAB/gAG6BYIAAirIAsAAIAACrgADvBYIAAh2QABgNgFgGQgEgFgLAAQgWAAAAAdIAABxIgtAAIAAirIAqAAIAAAUIABAAQAHgNAMgGQAKgGAPAAQAVAAALAMQAMALAAAaIAAB/gAktBYIAAirIArAAIAAAXIAAAAQAIgNAJgHQAJgIAOAAIAFAAIADABIAAAqIgNgBIgMACQgGACgFADQgEAEgEAGQgCAGAAAIIAABngAn7BYIAAh4QABgKgFgGQgEgGgJAAQgLAAgGAHQgGAHAAAPIAABxIgsAAIAAh4QAAgKgFgGQgDgGgKAAQgKAAgHAHQgFAHgBAPIAABxIgsAAIAAirIAqAAIAAARIABAAQAIgMALgFQAKgFAOAAQAQAAAKAHQALAHAEAOIAAAAQAFgOALgHQALgHAQAAQAXAAAKANQAKAOAAAZIAAB8gAG6hpIAAglIAsAAIAAAlg");
	this.shape.setTransform(16.4,-90.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_onARoll, new cjs.Rectangle(-117.9,-105.2,268.70000000000005,28.60000000000001), null);


(lib.txt_Immediatelamination = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgTAYIAAgvIAnAAIAAAvg");
	this.shape.setTransform(132.075,8.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AAUBVIAAhyQAAgNgEgFQgEgEgKAAQgVgBAAAcIAABtIgrAAIAAilIAoAAIAAATIABAAQAHgMALgGQAKgFANgBQAVABALAKQAMALAAAaIAAB6g");
	this.shape_1.setTransform(121.35,2.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgfBSQgMgFgIgLQgHgLgDgQQgEgRAAgWQAAgUAEgQQADgRAIgLQAIgLAMgGQANgFARAAQATgBANAGQANAFAHALQAIAMADAQQADAQAAAVQAAAWgEAQQgDARgIALQgHALgNAFQgNAFgSAAIgCAAQgRAAgMgFgAgLg1QgFAEgCAIQgDAIAAALIgBAWIABAYQAAALADAIQACAHAFAFQAEAEAHAAQANAAAFgOQAFgNAAggQAAgegFgOQgFgNgNAAQgHAAgEAEg");
	this.shape_2.setTransform(106.925,2.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgUBwIAAimIAqAAIAACmgAgUhKIAAglIAqAAIAAAlg");
	this.shape_3.setTransform(96.55,-0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgDBqQgHgCgEgFQgFgFgCgIQgBgJAAgMIAAhfIgVAAIAAgdIAVAAIAAgwIAqAAIAAAwIAYAAIAAAdIgYAAIAABZQAAAKADAEQACAFAKAAIAFgBIAEAAIAAAeIgNAAIgOABQgMAAgIgCg");
	this.shape_4.setTransform(89.1,0.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_5.setTransform(77.625,2.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAUBVIAAhyQAAgNgEgFQgEgEgKAAQgVgBAAAcIAABtIgrAAIAAilIAoAAIAAATIABAAQAHgMALgGQAKgFANgBQAVABALAKQAMALAAAaIAAB6g");
	this.shape_6.setTransform(63.3,2.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgUBwIAAimIApAAIAACmgAgUhKIAAglIApAAIAAAlg");
	this.shape_7.setTransform(52.6,-0.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AA9BVIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgqAAIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgrAAIAAilIApAAIAAARIABAAQAIgMAKgEQAKgGAOAAQAPAAAJAHQAKAHADANIABAAQAFgNALgHQALgGAPgBQAVAAAKANQAKANAAAZIAAB3g");
	this.shape_8.setTransform(37.925,2.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_9.setTransform(19.375,2.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgVBvIAAjdIArAAIAADdg");
	this.shape_10.setTransform(9.1,-0.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgiBPQgNgHgHgNQgGgNgBgQIgCgeQAAgRADgPQACgQAHgMQAHgMANgHQANgHAVAAQASAAAMAGQAMAGAHALQAHALACAPQADAQAAATIAAAJIhUAAIAAANIABAPIAEAMQACAFAEAEQAEADAFAAQALAAAFgIQAFgIACgPIAmAAQgBAdgOAPQgPAPgeAAQgWAAgNgIgAgJg2QgEADgCAFIgEAKIgBAMIAAAGIArAAIgCgQQAAgIgDgFQgCgFgEgDQgEgCgHAAQgFAAgFADg");
	this.shape_11.setTransform(-7.675,2.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgDBqQgIgCgEgFQgEgFgCgIQgBgJAAgMIAAhfIgVAAIAAgdIAVAAIAAgwIAqAAIAAAwIAZAAIAAAdIgZAAIAABZQAAAKADAEQADAFAJAAIAFgBIAFAAIAAAeIgOAAIgOABQgNAAgHgCg");
	this.shape_12.setTransform(-18.6,0.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_13.setTransform(-30.075,2.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgUBwIAAimIAqAAIAACmgAgUhKIAAglIAqAAIAAAlg");
	this.shape_14.setTransform(-40.35,-0.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("Ag0BcQgMgUAAgvQAAgtAMgVQAMgUAbAAQAMAAAHAFQAJAFAHAKIAAAAIAAhHIArAAIAADdIgpAAIAAgRIgBAAQgHALgIAFQgIAEgNAAQgbABgMgVgAgSgOQgEANAAAaQAAAcAEAOQAFAOANAAQAOAAAEgOQAEgOAAgcQAAgagEgNQgEgOgOAAQgNAAgFAOg");
	this.shape_15.setTransform(-51.225,0.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgiBPQgNgHgHgNQgGgNgBgQIgCgeQAAgRADgPQACgQAHgMQAHgMANgHQANgHAVAAQASAAAMAGQAMAGAHALQAHALACAPQADAQAAATIAAAJIhUAAIAAANIABAPIAEAMQACAFAEAEQAEADAFAAQALAAAFgIQAFgIACgPIAmAAQgBAdgOAPQgPAPgeAAQgWAAgNgIgAgJg2QgEADgCAFIgEAKIgBAMIAAAGIArAAIgCgQQAAgIgDgFQgCgFgEgDQgEgCgHAAQgFAAgFADg");
	this.shape_16.setTransform(-65.225,2.625);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AA9BVIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgqAAIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgrAAIAAilIApAAIAAARIABAAQAIgMAKgEQAKgGAOAAQAPAAAJAHQAKAHADANIABAAQAFgNALgHQALgGAPgBQAVAAAKANQAKANAAAZIAAB3g");
	this.shape_17.setTransform(-83.375,2.45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AA9BVIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgqAAIAAhzQAAgLgEgFQgEgFgJAAQgKAAgGAGQgGAHAAAPIAABsIgrAAIAAilIApAAIAAARIABAAQAIgMAKgEQAKgGAOAAQAPAAAJAHQAKAHADANIABAAQAFgNALgHQALgGAPgBQAVAAAKANQAKANAAAZIAAB3g");
	this.shape_18.setTransform(-106.075,2.45);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgVBvIAAjdIAsAAIAADdg");
	this.shape_19.setTransform(-121,-0.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_Immediatelamination, new cjs.Rectangle(-134.8,-20.8,279.6,40.7), null);


(lib.txt_greaterConsistency = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AOvCUIAAgiIAMABQAMAAAGgHQAFgGACgLIgzixIAwAAIAbB6IAAAAIAXh6IAuAAIgrClQgGAWgGAOQgFANgHAIQgIAHgKADQgKACgQAAgARDBhQAIgCAFgHQAEgIAAgJIAAgEIgRAAIAAg0IArAAIgBBCQgCAMgFAIQgFAIgIAFQgJAFgNABgAjzBZQgOgFgIgMQgIgMgDgRQgDgSAAgXQAAgWADgRQAEgSAJgLQAHgMAOgGQAOgGATAAQAUgBANAGQAOAGAIAMQAIAMADARQADASAAAWQAAAXgDARQgEASgIALQgIAMgOAGQgNAFgTAAIgDAAQgTAAgMgFgAjfg3QgEAFgDAIQgCAIgBAMIAAAxQABAMACAIQADAIAEAFQAGAEAIAAQAOAAAFgOQAFgPAAghQAAgggFgPQgFgOgOAAQgIAAgGAEgArSBZQgOgFgIgMQgIgMgDgRQgEgSABgXQAAgWADgRQAEgSAIgLQAIgMAOgGQAOgGATAAQAUgBANAGQAOAGAIAMQAIAMAEARQACASAAAWQABAXgEARQgDASgJALQgIAMgOAGQgNAFgTAAIgDAAQgTAAgMgFgAq+g3QgEAFgDAIQgDAIAAAMIAAAxQAAAMADAIQADAIAEAFQAFAEAJAAQAOAAAFgOQAFgPAAghQAAgggFgPQgFgOgOAAQgJAAgFAEgAu1BZQgOgFgIgMQgHgMgEgRQgEgSAAgXQABgWAEgRQADgSAIgLQAJgMANgGQANgGAUAAQAUgBANAGQAOAGAIAMQAIAMAEARQACASAAAWQAAAXgDARQgEASgIALQgIAMgNAGQgOAFgTAAIgDAAQgTAAgMgFgAugg3QgFAFgDAIQgDAIAAAMIAAAxQAAAMADAIQADAIAFAFQAEAEAJAAQANAAAGgOQAFgPAAghQAAgggFgPQgGgOgNAAQgJAAgEAEgAM7BaQgMgEgJgLQgIgKgFgSQgEgSAAgbQAAgaAFgSQAGgSAJgLQAKgLANgEQANgEAQAAQAgAAAQASQAQATAAAfIgsAAIAAgNIgDgLQgDgFgEgDQgEgDgGAAQgJAAgFADQgFAEgDAIQgCAHgBALIAAA2QABAMACAIQADAHAEAEQAFADAIAAQALAAAGgKQAFgJAAgWIAsAAQAAAjgQASQgQASgkAAQgRAAgNgEgAIABWQgOgIgHgOQgGgNgCgRIgBgiQAAgRACgQQADgRAHgMQAIgNANgIQAOgHAXAAQAUAAANAGQANAGAGAMQAIAMACARQADAQAAAVIAAAJIhaAAIACAdIADAOQADAFAEAEQAFADAFAAQAMAAAFgIQAFgIADgRIAoAAQgBAfgPAQQgPAQghAAQgYAAgOgIgAIbg4QgEADgDAFIgDALIgCANIAAAHIAvAAIgBgSQgBgIgDgFQgDgGgEgDQgEgCgIAAQgGAAgFADgAEYBbQgMgEgIgHQgHgHgDgLQgDgKgBgNIAAgGIAqAAIAAAGQgBALAHAHQAFAHANAAQAKAAAGgFQAGgFAAgLQAAgIgEgFQgGgEgGgDIgggMQgTgGgJgLQgKgMAAgTQAAgLADgKQAEgJAIgIQAIgHANgEQALgEATAAQAeAAAPANQAPANAAAYIAAAHIgpAAQAAgOgEgGQgFgGgLAAQgIAAgHAEQgHAFAAAKQABAGAEAGQADAFANAEIAbAJQAVAHAJALQAJAMAAAUQAAAOgFAKQgFALgJAHQgIAGgMADQgNADgOAAQgTAAgNgDgABABbQgMgEgIgHQgHgHgDgLQgDgKAAgNIAAgGIApAAIAAAGQAAALAGAHQAGAHAMAAQAKAAAHgFQAGgFAAgLQAAgIgFgFQgFgEgHgDIgfgMQgUgGgJgLQgJgMAAgTQgBgLAEgKQAEgJAHgIQAJgHAMgEQAMgEASAAQAfAAAPANQAPANAAAYIAAAHIgqAAQAAgOgEgGQgEgGgLAAQgJAAgHAEQgGAFAAAKQAAAGAEAGQAEAFAMAEIAbAJQAVAHAJALQAKAMgBAUQAAAOgEAKQgFALgJAHQgJAGgMADQgMADgOAAQgUAAgNgDgAmFBaQgNgEgJgLQgIgKgEgSQgFgSAAgbQAAgaAGgSQAFgSAKgLQAJgLANgEQANgEAQAAQAgAAARASQAPATAAAfIgrAAIgBgNIgDgLQgCgFgEgDQgEgDgHAAQgIAAgFADQgFAEgDAIQgDAHgBALIAAA2QABAMADAIQADAHAEAEQAFADAHAAQAMAAAFgKQAFgJABgWIArAAQAAAjgPASQgQASglAAQgQAAgNgEgAxIBaQgMgEgIgLQgJgKgEgSQgEgSgBgbQABgaAFgSQAFgSAJgLQALgLANgEQANgEAPAAQAgAAAQASQAQATAAAfIgsAAIAAgNIgDgLQgDgFgEgDQgDgDgHAAQgIAAgGADQgFAEgCAIQgDAHgBALIAAA2QABAMADAIQADAHAEAEQAFADAIAAQALAAAGgKQAEgJAAgWIAsAAQAAAjgQASQgPASgkAAQgSAAgNgEgAGqBaQgIgCgFgFQgEgGgCgJQgBgJgBgNIAAhlIgWAAIAAgfIAWAAIAAgzIAuAAIAAAzIAaAAIAAAfIgaAAIAABfQAAALAEAEQACAFALAAIAJgBIAAAgIgdABQgOAAgIgCgALVBbIAAh6QAAgOgFgFQgFgFgKAAQgYAAAAAdIAAB1IgtAAIAAixIAsAAIAAAVIAAAAQAHgNAMgGQAMgGAOAAQAWAAALALQANAMAAAbIAACDgAC2BbIAAixIAtAAIAACxgAgfBbIAAh6QAAgOgFgFQgEgFgLAAQgYAAAAAdIAAB1IgtAAIAAixIArAAIAAAVIABAAQAHgNAMgGQALgGAPAAQAWAAAKALQANAMAAAbIAACDgApYBbIAAixIAsAAIAAAYIABAAQAHgNAJgIQALgHAOAAIAEAAIAEAAIAAAsIgOgBIgMACQgGABgFAEQgFAEgDAGQgDAGAAAJIAABqgAs5BbIAAjrIAuAAIAADrgAC2hsIAAgnIAtAAIAAAng");
	this.shape.setTransform(5,-73.175);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_greaterConsistency, new cjs.Rectangle(-108.4,-87.9,226.9,29.500000000000007), null);


(lib.txt_greater = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AmLCHQgPgMAAgXIArAAQAAAJAIAFIAHADIAIABQAOAAAFgIQAGgJgBgOIAAgXIAAAAQgHAKgKAGQgKAGgLAAQgbAAgNgVQgOgUgBgwIACggQACgQAGgNQAFgNAMgIQALgIASAAQAKAAAKAFQAKAFAHAOIAAAAIAAgUIAsAAIAACoQAAAigRARQgRASgoAAQgdAAgQgNgAlkg3QgEADgCAIQgDAHgBAMIAAAvQABAIACAHQACAGAFAEQAFAEAHAAQAHAAAFgEQAFgEADgGQACgHABgJIABgVQAAgfgEgOQgGgNgNAAQgHAAgGADgANSBTQgNgIgIgOQgGgNgCgRIgBghQAAgSACgQQADgRAHgMQAIgNAOgIQAOgHAXAAQAUAAAMAGQANAGAHAMQAIAMACARQADAQgBAVIAAAJIhaAAIACAdIAEAOQACAFAEAEQAFADAGAAQAMAAAFgIQAFgIACgRIApAAQgCAfgPAQQgPAQggAAQgZAAgOgIgANtg7QgEADgCAFIgEALIgCANIAAAHIAvAAIgBgSQgBgIgCgFQgDgGgFgDQgEgCgHAAQgHAAgFADgAEPBTQgNgIgHgOQgGgNgCgRIgBghQgBgSADgQQACgRAIgMQAHgNAOgIQAOgHAYAAQATAAAMAGQAOAGAGAMQAIAMADARQACAQAAAVIAAAJIhaAAIACAdIADAOQACAFAFAEQAFADAFAAQAMAAAFgIQAGgIACgRIApAAQgCAfgPAQQgPAQghAAQgZAAgOgIgAErg7QgFADgCAFIgDALIgCANIAAAHIAvAAIgBgSQgCgIgCgFQgCgGgFgDQgEgCgIAAQgGAAgFADgAATBXQgJgEgEgHQgFgHgBgJQgDgJAAgJQAAgNADgJQACgJAFgHQAGgFAIgEQAIgFAMgDIAagHQAKgCAEgFQAEgFAAgJQAAgKgEgGQgGgFgLAAQgLAAgFAGQgFAGAAALIAAAFIgpAAIAAgFQAAgPAFgKQAFgLAIgGQAIgHAMgDQAMgCAMAAQAUAAANAEQANAEAHAHQAGAHADAKQADAKgBAMIAABcIACAUIAEAPIgsAAIgDgJIgCgKIgBAAQgHAOgLAEQgLAEgQAAQgMAAgIgEgABLAFIgKADQgOADgFAHQgGAHAAAMQAAAKAEAHQADAHAKAAIAJgBQAGgCADgDQAFgDACgFQADgGAAgHIAAgigAh5BTQgNgIgIgOQgGgNgCgRIgBghQAAgSACgQQADgRAHgMQAIgNAOgIQAOgHAXAAQAUAAAMAGQANAGAHAMQAIAMACARQADAQgBAVIAAAJIhaAAIACAdIAEAOQACAFAEAEQAFADAGAAQAMAAAFgIQAFgIACgRIApAAQgCAfgPAQQgPAQggAAQgZAAgOgIgAheg7QgEADgCAFIgEALIgCANIAAAHIAvAAIgBgSQgBgIgCgFQgDgGgFgDQgEgCgHAAQgHAAgFADgApfBTQgNgIgIgOQgGgNgCgRIgBghQAAgSACgQQADgRAHgMQAIgNAOgIQAOgHAXAAQAUAAAMAGQANAGAHAMQAIAMACARQADAQgBAVIAAAJIhaAAIACAdIAEAOQACAFAEAEQAFADAGAAQAMAAAFgIQAFgIACgRIApAAQgCAfgPAQQgPAQggAAQgZAAgOgIgApEg7QgEADgCAFIgEALIgCANIAAAHIAvAAIgBgSQgBgIgCgFQgDgGgFgDQgEgCgHAAQgHAAgFADgAJdBXQgJgCgEgFQgEgGgCgJQgCgJAAgNIAAhlIgXAAIAAgfIAXAAIAAgzIAuAAIAAAzIAaAAIAAAfIgaAAIAABfQAAALADAEQADAFAKAAIAKgBIAAAgIgdABQgOAAgIgCgAC7BXQgJgCgFgFQgEgGgCgJQgCgJAAgNIAAhlIgWAAIAAgfIAWAAIAAgzIAuAAIAAAzIAaAAIAAAfIgaAAIAABfQAAALAEAEQACAFAKAAIAKgBIAAAgIgdABQgOAAgHgCgAL0BYIAAh6QAAgOgFgFQgEgFgKAAQgZAAAAAdIAAB1IguAAIAAjrIAuAAIAABMIABAAQANgWAeAAQAWAAAMALQAMAMgBAbIAACDgAGMBYIAAixIAsAAIAAAYIAAAAQAHgNAKgIQAJgHAPAAIAEAAIAEAAIAAAsIgOgBIgMACQgGABgFAEQgFAEgDAGQgDAGAAAJIAABqgAj5BYIAAixIAsAAIAAAYIAAAAQAIgNAJgIQAKgHAPAAIADAAIAFAAIAAAsIgPgBIgLACQgHABgFAEQgEAEgDAGQgEAGAAAJIAABqgAq9BYIAAh6QAAgOgFgFQgEgFgKAAQgZAAAAAdIAAB1IguAAIAAjrIAuAAIAABMIABAAQANgWAeAAQAWAAAMALQAMAMgBAbIAACDgAuHBYIAAjEIgzAAIAAgnICWAAIAAAnIgzAAIAADEg");
	this.shape.setTransform(2.65,-105.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_greater, new cjs.Rectangle(-92.9,-120.6,191.10000000000002,29.5), null);


(lib.txt_AmazingProductivity = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgTAYIAAgvIAnAAIAAAvg");
	this.shape.setTransform(130.975,9.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("Ag2BuIAAggIAMABQALAAAGgGQAFgGABgKIgvimIAsAAIAYByIABAAIAVhyIArAAIgoCbIgLAhQgFANgHAHQgGAHgJACQgKACgPAAg");
	this.shape_1.setTransform(121.125,5.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgCBqQgJgCgDgFQgFgFgBgIQgCgJAAgMIAAhfIgWAAIAAgdIAWAAIAAgwIAqAAIAAAwIAYAAIAAAdIgYAAIAABZQAAAKADAEQADAFAJAAIAFgBIAEAAIAAAeIgNAAIgOABQgNAAgGgCg");
	this.shape_2.setTransform(110.5,0.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgVBwIAAimIAqAAIAACmgAgVhKIAAglIAqAAIAAAlg");
	this.shape_3.setTransform(102.9,0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgXBUIgrinIAsAAIAXB3IABAAIAWh3IArAAIgpCng");
	this.shape_4.setTransform(93.075,3.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgVBwIAAimIArAAIAACmgAgVhKIAAglIArAAIAAAlg");
	this.shape_5.setTransform(83.25,0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgDBqQgHgCgEgFQgFgFgCgIQgBgJAAgMIAAhfIgVAAIAAgdIAVAAIAAgwIAqAAIAAAwIAZAAIAAAdIgZAAIAABZQAAAKADAEQACAFAKAAIAFgBIAFAAIAAAeIgOAAIgOABQgMAAgIgCg");
	this.shape_6.setTransform(75.8,0.825);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgbBTQgMgEgIgKQgIgKgEgRQgEgRAAgZQAAgYAFgRQAFgRAJgKQAJgKANgEQAMgEAOAAQAeAAAPARQAPARAAAeIgpAAIgBgMIgDgLQgCgFgEgCQgDgDgGAAQgHAAgFADQgFAEgDAHQgCAHgBAKIgBAZIABAaQABALACAHQADAHAEAEQAFADAGAAQALAAAFgJQAFgKAAgUIApAAQAAAhgPARQgPARgiAAQgPAAgMgEg");
	this.shape_7.setTransform(64.725,3.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgzBKQgMgKAAgZIAAh7IAsAAIAAByQAAANAEAFQAEAFAKAAQAVAAAAgbIAAhuIArAAIAACmIgoAAIAAgUIgBAAQgHANgLAFQgKAFgNAAQgVAAgLgLg");
	this.shape_8.setTransform(50.55,3.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("Ag0BcQgMgUAAgvQAAgtAMgUQAMgVAbAAQAMAAAHAFQAJAFAHAKIAAAAIAAhGIArAAIAADcIgpAAIAAgSIgBAAQgHAMgIAFQgIAFgNAAQgbgBgMgUgAgSgPQgEAOAAAaQAAAcAEAOQAFAOANgBQAOABAEgOQAEgOAAgcQAAgagEgOQgEgNgOAAQgNAAgFANg");
	this.shape_9.setTransform(35.625,0.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgfBSQgMgFgIgLQgHgLgDgQQgEgRAAgWQAAgUAEgQQADgRAIgLQAIgLAMgGQANgFARAAQATgBANAGQANAFAHALQAIAMADAQQADAQAAAVQAAAWgEAQQgDARgIALQgHALgNAFQgNAFgSAAIgCAAQgRAAgMgFgAgLg1QgFAEgCAIQgDAIAAALIgBAWIABAYQAAALADAIQACAHAFAFQAEAEAHAAQANAAAFgOQAFgNAAggQAAgegFgOQgFgNgNAAQgHAAgEAEg");
	this.shape_10.setTransform(21.375,3.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgrBWIAAinIApAAIAAAXIABAAQAGgMAIgHQAKgIAOABIADAAIAEAAIAAApIgHgBIgHAAIgLACQgFABgFAEQgEADgDAGQgCAGAAAJIAABjg");
	this.shape_11.setTransform(10.2,2.95);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhABwIAAjbIApAAIAAASIABAAQAHgMAIgFQAIgFANAAQAbAAAMAUQAMAVAAAuQAAAugMAUQgMAUgbAAQgMAAgHgEQgJgFgHgKIAAAAIAABFgAgRhBQgEAOAAAbQAAAbAEANQAEAOANAAQAOAAAFgOQAEgNAAgbQAAgbgEgOQgFgNgOAAQgNAAgEANg");
	this.shape_12.setTransform(-2.425,5.625);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgvBmQgOgMAAgVIApAAQAAAIAGAEIAHAEIAHABQANAAAFgIQAFgJAAgMIAAgWIgBAAQgGAJgKAGQgIAGgKAAQgaAAgMgUQgNgTAAgtIABgdQACgPAFgNQAGgMAKgIQALgHARAAQAJAAAJAEQAJAGAGAMIABAAIAAgTIApAAIAACeQAAAhgQAPQgQAQgkABQgcgBgPgLgAgKhMQgEACgDAIQgCAHgBALIgBAcIABARQABAGACAGQADAHAEADQAEAEAGAAQAHAAAEgEQAFgDACgHQADgGABgHIABgUQAAgegFgNQgFgNgMAAQgGABgFADg");
	this.shape_13.setTransform(-24.225,5.75);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AAUBWIAAhzQABgNgFgFQgEgEgKgBQgVAAAAAcIAABuIgrAAIAAinIAoAAIAAAUIACAAQAGgMALgGQAKgGANABQAVgBALALQALAMAAAZIAAB7g");
	this.shape_14.setTransform(-38.75,2.95);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgUBwIAAimIApAAIAACmgAgUhKIAAglIApAAIAAAlg");
	this.shape_15.setTransform(-49.45,0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("Ag6BUIAAgiIBChiIg+AAIAAgjIBwAAIAAAiIhBBiIBBAAIAAAjg");
	this.shape_16.setTransform(-59,3.15);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AgqBTQgIgEgFgGQgEgHgCgJQgDgIAAgJQAAgLADgJQACgIAGgHQAFgFAIgEQAHgEAMgDIAXgGQAJgDAEgEQAEgEAAgJQAAgJgFgGQgEgFgKAAQgKAAgFAGQgFAGAAAJIAAAFIgmAAIAAgEQAAgPAEgJQAFgKAIgGQAIgGALgDQAKgCAMAAQASAAAMADQAMAEAHAHQAGAHACAJQADAKAAALIAABXIABASIAEAOIgpAAIgDgJIgCgJIgBAAQgHANgKAEQgJAEgPAAQgLAAgIgEgAAKAGIgKADQgMADgFAGQgGAHAAALQAAAJAEAHQAEAHAIAAIAJgBQAEgCAEgDIAGgIQADgFAAgHIAAghg");
	this.shape_17.setTransform(-72.425,3.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AA9BWIAAh0QAAgKgEgGQgEgGgJAAQgKAAgGAHQgGAHAAAPIAABtIgqAAIAAh0QAAgKgEgGQgEgGgJAAQgKAAgGAHQgGAHAAAPIAABtIgrAAIAAinIApAAIAAASIABAAQAIgLAKgGQAKgEAOAAQAPgBAJAIQAKAGADANIABAAQAFgNALgHQALgGAPAAQAVAAAKAMQAKANAAAYIAAB5g");
	this.shape_18.setTransform(-90.725,2.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AAoBvIgLgvIg5AAIgLAvIguAAIA6jdIA3AAIA6DdgAAWAbIgWhiIAAAAIgVBiIArAAg");
	this.shape_19.setTransform(-110.275,0.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_AmazingProductivity, new cjs.Rectangle(-132.3,-20.3,279.6,40.7), null);


(lib.SureColor_lockup_intro = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ARBFDQgQgKgIgQQgIgQgCgTIgBgoQAAgVADgTQADgTAIgPQAJgPAQgJQAQgJAbAAQAXAAAPAIQAPAHAIAOQAJAOADATQADATAAAZIAAALIhpAAIABAjIAFAPQADAHAFAEQAFAEAHAAQAOAAAGgJQAGgKADgUIAvAAQgCAlgRASQgSAUgmAAQgdAAgQgKgARhCbQgFAEgDAGIgFANIgBAXIA3AAIgCgVQgCgJgCgGQgDgHgFgDQgGgEgIAAQgIAAgFAEgAg8FIQgPgEgJgJQgIgIgDgMQgEgNAAgOIAAgIIAwAAIAAAHQAAAOAHAIQAHAIAOAAQAMAAAHgGQAGgGAAgNQAAgJgEgGQgGgFgIgDIglgNQgWgIgLgOQgLgOAAgWQAAgNAEgMQAEgLAJgIQAKgJAOgFQAOgFAVAAQAjAAASAPQARAQAAAcIAAAJIgwAAQAAgQgEgIQgGgIgMAAQgKAAgIAGQgIAGAAALQAAAIAFAGQAFAGAOAEIAeALQAaAIAKAOQALAOAAAYQAAAQgGAMQgGAMgKAJQgKAHgPAEQgMAEgRAAQgXAAgPgFgAjjFDQgQgKgIgQQgIgQgCgTIgCgoQAAgVAEgTQACgTAJgPQAJgPAQgJQAQgJAbAAQAXAAAPAIQAPAHAIAOQAJAOADATQADATAAAZIAAALIhpAAIABAjIAEAPQAEAHAFAEQAFAEAHAAQAOAAAGgJQAGgKACgUIAwAAQgCAlgSASQgRAUgmAAQgdAAgQgKgAjDCbQgFAEgEAGIgEANIgBAXIA2AAIgBgVQgCgJgDgGQgCgHgFgDQgGgEgIAAQgIAAgFAEgAqgFGQgQgHgKgQQgKgPgEgZQgEgaAAgkIACg3QABgaAJgUQAIgVASgLQARgNAeAAQAaAAAQAHQAQAHAKAQQAKAQAEAaQAEAYAAAlIgCA2QgCAbgIAUQgJAUgRAMQgRAMgfAAQgYAAgRgHgAqFBgQgHAEgDALQgDALgBARIAAB0QABAQAEAKQADAJAGAEQAGADAIAAQAKAAAFgEQAGgFAEgKQADgLABgSIAAhzQgBgRgEgJQgDgKgGgDQgGgEgJAAQgJAAgFAFgAv3FGQgQgHgKgQQgKgPgEgZQgEgaAAgkIACg3QACgaAIgUQAJgVARgLQARgNAfAAQAZAAAQAHQARAHAKAQQAJAQAEAaQAEAYAAAlIgCA2QgBAbgJAUQgIAUgSAMQgRAMgeAAQgZAAgRgHgAvcBgQgGAEgDALQgEALgBARIAAB0QABAQAEAKQADAJAGAEQAGADAJAAQAJAAAGgEQAGgFADgKQADgLABgSIAAhzQgBgRgEgJQgDgKgGgDQgFgEgJAAQgKAAgFAFgAynFFQgQgGgJgMQgIgLgDgOQgDgNAAgLIAAgIIA1AAIABAPQABAHACAHQADAHAGAFQAFAEAJAAQASAAAHgNQAHgNAAgbIgBgcQgCgLgDgHQgEgHgGgCQgGgDgKAAQgMAAgGAGQgGAIgCALIgyAAIAKiVICOAAIAAAsIhkAAIgGA+IABAAQAIgLAMgFQAMgFASAAQAUAAANAIQANAHAHANQAIAMADAQQADAPAAAQQAAAXgEATQgEASgKAOQgJANgSAHQgRAHgaAAQgZAAgQgIgAPlFHQgKgCgFgGQgGgHgBgKQgCgKAAgQIAAh3IgbAAIAAglIAbAAIAAg7IA1AAIAAA7IAfAAIAAAlIgfAAIAABwQAAAMAEAGQADAFAMAAIAMgBIAAAlIgjABQgPAAgKgCgATKFIIAAjQIAzAAIAAAdIABAAQAIgPAMgKQALgJARAAIAJABIAAAzIgQgBIgOACQgHACgGAEQgFAFgEAHQgEAHAAALIAAB8gAN2FIIAAiPQAAgQgFgHQgFgGgMAAQgdAAAAAiIAACKIg1AAIAAjQIAzAAIAAAZIABAAQAJgQANgHQANgHASAAQAZAAAOAOQAOAOAAAfIAACagALBFIIAAjQIA1AAIAADQgAJNFIIAAjQIAzAAIAAAdIAAAAQAJgPALgKQAMgJAQAAIAKABIAAAzIgRgBIgOACQgHACgFAEQgGAFgEAHQgDAHAAALIAAB8gAGUFIIAAkTIBhAAQAWAAAOAHQAOAHAKAMQAIALAEAPQAEAPAAAPQAAAWgHAPQgGAQgLAKQgMAKgQAGQgQAEgUAAIgdAAIAABugAHMCxIAYAAQARAAAKgKQAKgKAAgVQAAgVgIgLQgJgLgVAAIgXAAgAD5FIIAAiPQAAgQgGgHQgFgGgMAAQgcAAAAAiIAACKIg1AAIAAjQIAzAAIAAAZIAAAAQAJgQANgHQAOgHARAAQAaAAANAOQAOAOAAAfIAACagABEFIIAAjQIA1AAIAADQgAlHFIQgEgGgCgHIgDhEQAAgRgIgJQgHgJgRAAIgeAAIAAB0Ig4AAIAAkTIBnAAQAiAAAUARQATASAAAkQAAAbgLASQgMASgXAFIAAABQAVACAKALQAJAKADAXIAEBHQACAMAIAEIAAACgAmOCtIAXAAQAUAAALgJQAKgKAAgWQAAgngmAAIgaAAgAtYFIQADgZAGgbQAGgbAKgcQAKgcAPgcQAPgdAUgcIhzAAIAAgwICoAAIAAArQgRAYgNAbQgOAcgKAcQgKAdgGAeQgHAegDAdgA0MFIQgEgGgBgHIgDhEQgBgRgIgJQgHgJgRAAIgeAAIAAB0Ig3AAIAAkTIBmAAQAjAAATARQATASAAAkQAAAbgLASQgLASgXAFIAAABQAVACAJALQAKAKACAXIAEBHQADAMAHAEIAAACgA1TCtIAXAAQAUAAALgJQALgKAAgWQAAgngmAAIgbAAgALBBfIAAguIA1AAIAAAugABEBfIAAguIA1AAIAAAugAP0g1QgQgGgJgOQgKgNgDgVQgEgVAAgbQAAgbAEgUQAEgUAKgOQAKgOAPgHQAQgHAXAAQAXAAAQAGQAQAHAKAOQAIAOAEAVQAFAUAAAbQAAAbgFAUQgEAVgKANQgJAOgQAHQgQAGgWAAIgEAAQgWAAgOgGgAQMjeQgFAFgEAKQgCAJgBAOIAAA7QABANACAKQAEAJAFAGQAGAFAKAAQAQAAAGgRQAGgRAAgnQAAgngGgRQgGgRgQAAQgKAAgGAGgAL/g1QgQgGgJgOQgJgNgEgVQgEgVAAgbQAAgbAEgUQAFgUAKgOQAJgOAPgHQAQgHAXAAQAYAAAQAGQAQAHAJAOQAJAOAEAVQAEAUAAAbQAAAbgEAUQgFAVgKANQgJAOgPAHQgQAGgXAAIgDAAQgWAAgPgGgAMYjeQgGAFgDAKQgDAJAAAOIAAA7QAAANADAKQADAJAGAGQAFAFAKAAQARAAAFgRQAHgRAAgnQAAgngHgRQgFgRgRAAQgKAAgFAGgAJGg5QgSgKgKgTQgKgSgDgbQgDgaAAggQAAgfADgaQADgbAKgTQAKgSASgLQASgLAfAAQAeAAASAKQARAJAIAPQAIAPADARIACAhIg4AAQAAgfgHgNQgHgOgTAAQgKAAgHAGQgHAFgEANQgDANgCAUIgCAxQAAAgADATQACATAEALQAFAKAGAEQAHAEAJAAQAHAAAHgDQAGgCAEgIQAFgIADgNQADgOAAgWIA3AAQAAAWgDAUQgEAUgJAPQgJAPgSAJQgRAIgcAAQgfAAgSgKgAGYg4QgQgKgIgQQgIgQgCgTIgCgoQAAgVAEgTQACgTAJgPQAJgPAQgJQAQgJAbAAQAXAAAPAIQAPAHAIAOQAJAOADATQADATAAAZIAAALIhpAAIABAjIAEAPQAEAHAFAEQAFAEAHAAQAOAAAGgJQAGgKACgUIAwAAQgCAkgSATQgRATgmAAQgdAAgQgJgAG4jgQgFAEgEAGIgEANIgBAXIA2AAIgBgVQgCgKgDgGQgCgGgFgEQgGgDgIAAQgIAAgFAEgABqg8QgOgOAAgeIAAibIA1AAIAACQQAAAQAGAGQAFAHAMAAQAcAAAAgjIAAiKIA2AAIAADQIg0AAIAAgYIAAAAQgJAPgNAHQgNAGgSAAQgZAAgOgNgAhPhDQgVgVAAgmIAAgLIA4AAIABAZQACAJAFAFQADAFAIADQAHAEALAAQALAAAKgJQALgIAAgRQAAgKgDgGQgCgHgGgFQgGgGgIgEIgYgJQgSgHgOgHQgNgHgJgKQgJgKgFgNQgDgNAAgRQAAgpAWgUQAXgUAnAAQASAAAQAEQAPAEAMAJQALAJAGAPQAHAOAAATIAAAIIg2AAQAAgUgGgKQgHgLgQAAQgJAAgGADQgGACgEAFQgEAFgBAFIgBAMQAAANAFAJQAGAIARAIIAqASQAQAHAKAHQAKAIAGAJQAGAJACAKQADALAAAMQAAAsgaAUQgZATgsAAQgvAAgUgUgAorg4QgQgKgIgQQgIgQgCgTIgCgoQAAgVAEgTQACgTAJgPQAIgPARgJQAQgJAbAAQAXAAAPAIQAPAHAIAOQAJAOADATQADATAAAZIAAALIhpAAIABAjIAEAPQAEAHAFAEQAEAEAIAAQANAAAGgJQAHgKACgUIAwAAQgCAkgSATQgRATgmAAQgdAAgQgJgAoLjgQgFAEgEAGIgEANIgBAXIA2AAIgBgVIgFgQQgDgGgEgEQgGgDgIAAQgIAAgFAEgAvmg4QgQgKgHgQQgIgQgCgTIgCgoQAAgVADgTQADgTAIgPQAJgPARgJQAQgJAbAAQAXAAAPAIQAOAHAJAOQAJAOACATQAEATAAAZIAAALIhqAAIABAjIAFAPQADAHAFAEQAFAEAHAAQAOAAAGgJQAGgKADgUIAvAAQgBAkgSATQgSATgmAAQgdAAgQgJgAvGjgQgFAEgDAGIgFANIgBAXIA3AAIgCgVQgBgKgDgGQgDgGgFgEQgFgDgJAAQgHAAgGAEgAR5gzIAAjQIA0AAIAAAcIAAAAQAIgOAMgKQAMgJAQAAIAJABIAAAzIgQgBIgOACQgHACgGAEQgFAFgEAHQgDAHAAALIAAB8gAOHgzIAAkTIA1AAIAAETgAEMgzIAAjQIA0AAIAAAcIAAAAQAIgOAMgKQALgJARAAIAJABIAAAzIgQgBIgOACQgHACgGAEQgFAFgEAHQgDAHAAALIAAB8gAkTgzIgciTIAAAAIgaCTIg+AAIgtjQIA2AAIAYCUIAAAAIAaiUIA6AAIAcCUIAAAAIAZiUIAzAAIgsDQgAqagzIhEjBIgBAAIAADBIgzAAIAAkTIBAAAIBDC8IABAAIAAi8IAzAAIAAETgAxKgzIAAiPQAAgQgFgHQgFgGgMAAQgcAAAAAiIAACKIg2AAIAAkTIA2AAIAABZIAAAAQAQgbAjAAQAZAAAOAOQAOAOAAAfIAACagA0rgzIAAjmIg8AAIAAgtICvAAIAAAtIg8AAIAADmgAUtiiQgMgFgKgJQgJgJgFgNQgFgMAAgOQAAgOAFgNQAFgMAJgJQAKgJAMgGQAMgFAOAAQAOAAANAFQAMAGAJAJQAJAJAGAMQAFANAAAOQAAAOgFAMQgGANgJAJQgJAJgMAFQgNAFgOAAQgOAAgMgFgAU1kMQgJAEgHAGQgGAHgDAIQgEAJAAAKQAAAKAEAJQADAIAGAHQAHAHAJADQAIAEAKAAQAKAAAJgEQAJgDAGgHQAHgHADgIQADgJAAgKQAAgKgDgJQgDgIgHgHQgGgGgJgEQgJgEgKAAQgKAAgIAEgAVUi8IgRgdIgGAAIAAAdIgQAAIAAhJIAdAAQAOAAAGAHQAIAFAAALQAAAKgFAEQgGAGgHABIASAdgAU9jmIANAAIAIgBQADgCAAgFIgBgGIgDgCIgUgBg");
	this.shape.setTransform(1.775,-18.425);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.SureColor_lockup_intro, new cjs.Rectangle(-140.1,-51.7,283.79999999999995,66.60000000000001), null);


(lib.SureColor_lockup = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ALsFeQgRgKgJgRQgHgRgDgVIgBgqQAAgXACgUQAEgWAJgPQAJgRASgJQASgJAdAAQAYAAAQAIQAQAHAJAPQAJAPAEAVQADAVAAAaIAAAMIhxAAIABAlIAFARQADAHAGAFQAFAEAIAAQAPAAAGgKQAHgLACgVIA0AAQgCAngUAUQgSAUgqAAQgeAAgSgKgAMPCqQgGAEgDAGIgFAPIgBAYIA6AAIgBgWQgCgKgDgHQgDgGgGgEQgFgEgJAAQgJAAgFAEgAnkFkQgQgEgJgKQgJgJgEgNQgEgNAAgQIAAgIIAzAAIAAAHQAAAPAIAJQAIAJAOAAQAOAAAIgHQAHgGABgOQAAgLgHgFQgFgFgJgEIgogPQgYgHgMgQQgMgPAAgYQAAgNAFgMQAEgMALgKQAJgJAQgFQAPgFAWAAQAnAAASAQQAUAQgBAfIAAAJIgzAAQAAgSgGgHQgFgJgOAAQgLAAgIAHQgIAFAAAMQAAAJAFAGQAFAHAOAEIAiAMQAbAJAMAPQAMAPAAAZQgBASgGAMQgGAOgMAJQgKAIgQAEQgPADgRAAQgZAAgQgEgAqYFeQgRgKgIgRQgIgRgDgVIgBgqQABgXACgUQADgWAKgPQAIgRASgJQARgJAeAAQAZAAAPAIQARAHAIAPQAKAPADAVQADAVAAAaIAAAMIhxAAIABAlIAFARQAEAHAFAFQAFAEAIAAQAOAAAIgKQAGgLADgVIAzAAQgCAngTAUQgSAUgqAAQgfAAgSgKgAp0CqQgHAEgDAGIgFAPIgBAYIA7AAIgCgWQgBgKgDgHQgDgGgHgEQgFgEgIAAQgJAAgFAEgAKJFjQgKgCgGgHQgFgHgCgLQgCgLAAgRIAAiAIgdAAIAAgnIAdAAIAAhAIA6AAIAABAIAgAAIAAAnIggAAIAAB5QAAANADAGQAEAFANAAIAMgBIAAAoIgmABQgPAAgMgCgAN/FkIAAjfIA4AAIAAAeIAAAAQAJgQAMgKQAMgJASAAIAKAAIAAA3IgRgBIgPACQgIACgGAFQgGAFgEAHQgDAIAAALIAACGgAITFkIAAiaQAAgRgHgHQgEgGgOAAQgdAAAAAkIAACUIg5AAIAAjfIA2AAIAAAaIABAAQAJgRAOgHQAPgHASAAQAcAAAPAOQAOAQAAAhIAAClgAFRFkIAAjfIA5AAIAADfgADUFkIAAjfIA3AAIAAAeIABAAQAIgQANgKQAMgJASAAIAKAAIAAA3IgRgBIgPACQgIACgGAFQgGAFgEAHQgDAIAAALIAACGgAAOFkIAAkoIBoAAQAXAAAPAIQARAIAIAMQALANAEAQQADAPAAARQAAAXgGARQgIARgLAKQgMALgSAGQgSAFgUAAIghAAIAAB2gABJDCIAbAAQASAAALgLQALgKgBgXQAAgWgJgMQgJgMgWAAIgaAAgAiYFkIAAiaQAAgRgGgHQgFgGgNAAQgeAAAAAkIAACUIg5AAIAAjfIA3AAIAAAaIABAAQAIgRAOgHQAPgHASAAQAcAAAPAOQAOAQAAAhIAAClgAlaFkIAAjfIA6AAIAADfgAsDFkQgEgGgBgIIgCgRIgCg5QgBgRgIgKQgHgKgTAAIgfAAIAAB9Ig9AAIAAkoIBuAAQAmAAAVATQAUATAAAnQAAAdgLATQgMATgaAGIAAAAQAWADAKAMQAMALACAZIAEBMQADAMAIAFIAAACgAtOC9IAXAAQAXAAALgKQAMgKAAgYQAAgpgpAAIgcAAgAFRBqIAAgxIA5AAIAAAxgAlaBqIAAgxIA6AAIAAAxgARXgyQgSgHgKgRQgLgRgEgbQgEgbAAgnIACg7QABgcAKgWQAIgVAUgNQARgOAiAAQAaAAASAJQASAHAKARQAKARAFAbQAFAbAAAnIgDA7QgCAcgJAWQgJAWgSAMQgTAMggAAQgbAAgSgHgAR0koQgHAEgEAMQgDALgBATIAAB8QABASAEAKQAEAKAGAEQAGAEAKAAQAKAAAFgFQAHgFADgLQAEgMACgTIAAh8QgCgSgEgKQgEgKgGgDQgGgEgJAAQgLAAgFAFgALsgyQgRgHgLgRQgLgRgEgbQgEgbAAgnIACg7QABgcAKgWQAIgVATgNQATgOAhAAQAbAAASAJQARAHAKARQALARAFAbQADAbAAAnIgBA7QgCAcgKAWQgIAWgTAMQgTAMggAAQgbAAgSgHgAMIkoQgFAEgEAMQgEALgBATIAAB8QABASAEAKQAEAKAGAEQAGAEAKAAQAKAAAGgFQAGgFAEgLQADgMABgTIAAh8QgBgSgEgKQgEgKgFgDQgHgEgJAAQgKAAgHAFgAIxgyQgRgIgKgMQgIgMgEgOQgDgOAAgNIAAgIIA5AAIABAQQABAIAEAIQACAHAHAEQAFAFAJAAQAUAAAHgOQAIgOAAgdIgBgeQgCgMgEgHQgEgHgHgDQgGgDgKAAQgNAAgHAHQgGAIgCAMIg2AAIALifICZAAIAAAuIhsAAIgHBCIACAAQAIgLANgGQANgEATAAQAWAAAOAHQANAJAIANQAIANADARQAEAQAAASQAAAYgEAUQgEAUgLAPQgKAOgTAHQgSAHgcAAQgbAAgSgHgAOUgvQADgbAHgdQAGgdALgeQALgfAQgeQAPgfAXgdIh9AAIAAgzIC2AAIAAAtQgTAagOAdQgOAdgLAgQgLAfgGAgQgJAggDAfgAHHgvQgEgHgBgHIgCgRIgCg5QgBgRgHgKQgJgKgSAAIggAAIAAB9Ig8AAIAAkoIBvAAQAlAAAUATQAWATgBAmQAAAegMATQgMATgZAFIAAABQAXAEAKALQAKAKADAaIAFBMQACAMAIAEIAAADgAF7jWIAZAAQAWAAAMgJQAKgLABgYQgBgpgpAAIgcAAgAgsg7QgRgHgKgPQgKgOgEgXQgEgWAAgdQAAgcAEgWQAFgWAKgPQALgPAQgHQARgIAZAAQAYgBARAIQARAHAKAPQAKAPAEAWQAFAWgBAdQAAAdgEAWQgFAWgKAOQgLAPgRAHQgQAHgXAAIgEAAQgYAAgPgGgAgSjxQgGAGgDAKQgDAKgCAPIAAA/QACAOADALQADAKAGAGQAGAGALAAQAQAAAGgSQAIgTgBgqQABgqgIgSQgGgSgQAAQgLAAgGAGgAkzg7QgSgHgJgPQgLgOgEgXQgDgWAAgdQgBgcAFgWQAFgWAKgPQAKgPARgHQARgIAYAAQAagBAQAIQASAHAKAPQAJAPAFAWQAEAWAAAdQAAAdgFAWQgEAWgLAOQgKAPgRAHQgQAHgZAAIgDAAQgYAAgPgGgAkZjxQgHAGgDAKQgDAKgBAPIAAA/QABAOADALQADAKAHAGQAGAGAKAAQASAAAGgSQAHgTAAgqQAAgqgHgSQgGgSgSAAQgKAAgGAGgAn8hAQgTgKgLgUQgLgVgCgcQgEgcAAgiQAAgiAEgcQACgcALgVQALgUATgMQAUgLAhAAQAhAAASAKQASALAJAQQAKAQACASIACAjIg7AAQAAghgIgOQgIgPgUAAQgLAAgHAGQgIAGgEAOQgEANgCAWIgBA1QAAAhACAWQADAUAEAMQAFALAHAEQAHAEAKAAQAIAAAHgDQAHgDAEgIQAGgIACgPQADgOAAgYIA8AAQgBAYgDAVQgEAWgKAQQgJAQgTAJQgSAJgfAAQghAAgUgLgAq3g/QgSgKgHgRQgJgRgCgVIgCgrQABgXADgUQACgVAKgQQAJgQARgJQASgKAdAAQAZAAAQAIQAPAIAKAPQAJAPADAVQADAVAAAZIAAANIhwAAIABAlIAFARQADAHAFAEQAGAFAIAAQAOAAAHgLQAGgKADgVIAzAAQgBAngUAUQgSAUgqAAQgfAAgRgKgAqVjzQgFAEgDAGIgFAPIgBAYIA6AAIgCgWQgBgKgDgHQgDgHgGgEQgGgDgIAAQgIAAgHAEgAwBhDQgPgPAAghIAAilIA6AAIAACaQAAARAGAHQAFAHANAAQAeAAAAglIAAiUIA5AAIAADfIg3AAIAAgbIAAAAQgJARgPAHQgOAHgSAAQgcAAgPgOgAzJhKQgVgXgBgpIAAgLIA8AAIAAAIIABASQACAKAFAFQAFAGAHADQAIAEALAAQAOAAALgJQALgJAAgTQAAgKgDgHQgCgIgHgFQgFgGgLgFIgZgJQgUgHgOgIQgOgIgLgKQgJgLgFgOQgFgNABgTQgBgsAZgVQAZgWAqAAQAUAAAQAEQARAFANAJQALAKAIAPQAGAQAAAVIAAAIIg5AAQAAgVgHgMQgHgLgSAAQgKAAgHADQgFADgFAEQgEAGgBAGIgCAMQABAOAFAKQAFAJAUAIIAuAUQARAHAKAIQAMAIAGAKQAGAJADALQADALgBAOQABAvgcAVQgaAVgyAAQgyAAgWgVgABjg5IAAjfIA2AAIAAAeIABAAQAIgRANgJQAMgKATAAIAKABIAAA2IgSgBIgPACQgHACgGAGQgHAFgEAHQgDAIAAAKIAACHgAihg5IAAkoIA4AAIAAEogAtSg5IAAjfIA4AAIAAAeIAAAAQAJgRAMgJQAMgKASAAIAKABIAAA2IgSgBIgOACQgIACgGAGQgGAFgEAHQgDAIAAAKIAACHg");
	this.shape.setTransform(-5,-1.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.SureColor_lockup, new cjs.Rectangle(-129.7,-37.5,249.5,72), null);


(lib.printer_light_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.printer_light();
	this.instance.setTransform(-81.5,-11);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_light_1, new cjs.Rectangle(-81.5,-11,163,22), null);


(lib.image_03_slices = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_03_LG();
	this.instance.setTransform(-141,-203);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_03_slices, new cjs.Rectangle(-141,-203,302,356), null);


(lib.image_02_slices = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_02_LG();
	this.instance.setTransform(-141,-203);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_02_slices, new cjs.Rectangle(-141,-203,302,356), null);


(lib.image_01_slices = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_01_LG();
	this.instance.setTransform(-141,-203);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_01_slices, new cjs.Rectangle(-141,-203,302,356), null);


(lib.image_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_01();
	this.instance.setTransform(-179.5,-72);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_01_1, new cjs.Rectangle(-179.5,-72,359,144), null);


(lib.epson_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Epson_Logo();
	this.instance.setTransform(-68,-29,0.8125,0.8125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.epson_logo, new cjs.Rectangle(-68,-29,106.5,39), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape.setTransform(61.025,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_1.setTransform(47.475,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag1A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAfABAWAVQAXAXAAAeQAAAggXAVQgWAXgfAAQgfAAgWgXgAghghQgOAOAAATQAAAUAOAOQAOAPATAAQAUAAAOgPQAOgOAAgUQAAgTgOgOQgOgPgUAAQgTAAgOAPg");
	this.shape_2.setTransform(31.275,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBBMQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIglhSIgBAAIgMBOQAAADgEABIgSAAQgFgBABgEIAZiNQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAuBiIAAAAIAuhiQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAIADAAQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIAZCNQABAEgFABIgTAAQgDgBgBgDIgMhOIgBAAIglBSQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(13.1508,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BMQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIhUheIgBAAIAABZQAAAEgEABIgTAAQgEgBAAgEIAAiMQAAgDAEgBIADAAQABABAAAAQAAAAABAAQAAAAABAAQAAABABAAIBUBaIAAAAIAAhVQAAgFAFAAIATAAQAEAAAAAFIAACMQAAADgEABg");
	this.shape_4.setTransform(-10,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_5.setTransform(-25.075,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAwBLQgEgBgCgEIgLgWIg+AAIgKAWQgBAEgFABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIBBiNQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIACAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIBACNQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAVAYIgVgtIAAAAIgUAtIApAAg");
	this.shape_6.setTransform(-39.85,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_7.setTransform(-52.925,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBKQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAB1IA0AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_8.setTransform(-64.475,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_9.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,162.5,51.5), null);


(lib.printer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// printer_light
	this.instance = new lib.printer_light_1();
	this.instance.setTransform(-15.3,-47.6,0.9639,0.9639,0,0,0,-0.1,-0.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(10).to({_off:false},0).to({_off:true},42).wait(289));

	// Gradient
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],0.3,-8.6,0.3,8.6).s().p("AtlBWIAAirIbLAAIAACrg");
	this.shape.setTransform(-15,18.475);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(9).to({_off:false},0).wait(44).to({_off:true},1).wait(287));

	// image_Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_9 = new cjs.Graphics().p("AukFgIAAq/IdJAAIAAK/g");
	var mask_graphics_53 = new cjs.Graphics().p("AukFgIAAq/IdJAAIAAK/g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(9).to({graphics:mask_graphics_9,x:-14.4,y:45.375}).wait(44).to({graphics:mask_graphics_53,x:-14.4,y:45.375}).wait(1).to({graphics:null,x:0,y:0}).wait(287));

	// image_01
	this.instance_1 = new lib.image_01_1();
	this.instance_1.setTransform(-14.25,-24.9,0.4802,0.4802);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({y:46.3},42,cjs.Ease.quadInOut).wait(1).to({_off:true},1).wait(287));

	// printer
	this.instance_2 = new lib.Printer();
	this.instance_2.setTransform(-160,-87);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).wait(44).to({_off:true},1).wait(287));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160,-87,320,174);


(lib.image_03_LG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// slice_01_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgIUAhdMAAAhC5IQpAAMAAABC5g");
	var mask_graphics_69 = new cjs.Graphics().p("EgIUAhdMAAAhC5IQpAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:114.725,y:6}).wait(69).to({graphics:mask_graphics_69,x:114.725,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(311));

	// Layer_1
	this.instance = new lib.image_03_slices();
	this.instance.setTransform(0,-422);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(22).to({_off:true},1).wait(311));

	// slice_01_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EgIAAhdMAAAhC5IQBAAMAAABC5g");
	var mask_1_graphics_69 = new cjs.Graphics().p("EgIAAhdMAAAhC5IQBAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:9.725,y:6}).wait(69).to({graphics:mask_1_graphics_69,x:9.725,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(311));

	// Layer_1
	this.instance_1 = new lib.image_03_slices();
	this.instance_1.setTransform(0,-422);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(15).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(37).to({_off:true},1).wait(311));

	// slice_01_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgIRAhdMAAAhC5IQjAAMAAABC5g");
	var mask_2_graphics_69 = new cjs.Graphics().p("EgIRAhdMAAAhC5IQjAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:-95.025,y:6}).wait(69).to({graphics:mask_2_graphics_69,x:-95.025,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(311));

	// Layer_1
	this.instance_2 = new lib.image_03_slices();
	this.instance_2.setTransform(0,-422);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:0},17,cjs.Ease.quadOut).wait(52).to({_off:true},1).wait(311));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-141,-208,302,361);


(lib.image_02_LG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// slice_01_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgIbAhdMAAAhC5IQ3AAMAAABC5g");
	var mask_graphics_123 = new cjs.Graphics().p("EgIbAhdMAAAhC5IQ3AAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:113.975,y:6}).wait(123).to({graphics:mask_graphics_123,x:113.975,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(257));

	// Layer_1
	this.instance = new lib.image_02_slices();
	this.instance.setTransform(-1,-421.95,1.02,1.02);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({y:1},17,cjs.Ease.quadOut).wait(76).to({_off:true},1).wait(257));

	// slice_01_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EgH4AhdMAAAhC5IPxAAMAAABC5g");
	var mask_1_graphics_123 = new cjs.Graphics().p("EgH4AhdMAAAhC5IPxAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:9.475,y:6}).wait(123).to({graphics:mask_1_graphics_123,x:9.475,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(257));

	// Layer_1
	this.instance_1 = new lib.image_02_slices();
	this.instance_1.setTransform(-1,-421.95,1.02,1.02);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(15).to({_off:false},0).to({y:1},17,cjs.Ease.quadOut).wait(91).to({_off:true},1).wait(257));

	// slice_01_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgIWAhdMAAAhC5IQtAAMAAABC5g");
	var mask_2_graphics_123 = new cjs.Graphics().p("EgIWAhdMAAAhC5IQtAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:-94.525,y:6}).wait(123).to({graphics:mask_2_graphics_123,x:-94.525,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(257));

	// Layer_1
	this.instance_2 = new lib.image_02_slices();
	this.instance_2.setTransform(-1,-421.95,1.02,1.02);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:1},17,cjs.Ease.quadOut).wait(106).to({_off:true},1).wait(257));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-144.8,-208,308.1,365.1);


(lib.image_01_LG_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// slice_01_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgIgAhdMAAAhC5IRBAAMAAABC5g");
	var mask_graphics_178 = new cjs.Graphics().p("EgIgAhdMAAAhC5IRBAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:113.475,y:6}).wait(178).to({graphics:mask_graphics_178,x:113.475,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(202));

	// Layer_1
	this.instance = new lib.image_01_slices();
	this.instance.setTransform(-1,-376);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(30).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(131).to({_off:true},1).wait(202));

	// slice_01_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("EgIHAhdMAAAhC5IQPAAMAAABC5g");
	var mask_1_graphics_178 = new cjs.Graphics().p("EgIHAhdMAAAhC5IQPAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:9.975,y:6}).wait(178).to({graphics:mask_1_graphics_178,x:9.975,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(202));

	// Layer_1
	this.instance_1 = new lib.image_01_slices();
	this.instance_1.setTransform(-1,-376);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(15).to({_off:false},0).to({y:0},17,cjs.Ease.quadOut).wait(146).to({_off:true},1).wait(202));

	// slice_01_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("EgIUAhdMAAAhC5IQpAAMAAABC5g");
	var mask_2_graphics_178 = new cjs.Graphics().p("EgIUAhdMAAAhC5IQpAAMAAABC5g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:-94.775,y:6}).wait(178).to({graphics:mask_2_graphics_178,x:-94.775,y:6}).wait(1).to({graphics:null,x:0,y:0}).wait(202));

	// Layer_1
	this.instance_2 = new lib.image_01_slices();
	this.instance_2.setTransform(-1,-376);

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:0},17,cjs.Ease.quadOut).wait(161).to({_off:true},1).wait(202));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-208,302,361);


// stage content:
(lib.Epson_RDrive_320x480_V3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("EgY/glfMAx/AAAMAAABK/Mgx/AAAg");
	this.shape.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// epson_logo
	this.instance = new lib.epson_logo();
	this.instance.setTransform(76.5,41);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},9).wait(34).to({alpha:0},11).wait(178).to({alpha:1},9).wait(119));

	// Layer_4
	this.instance_1 = new lib.txt_AmazingProductivity();
	this.instance_1.setTransform(147.05,185,1,1,0,0,0,-3,0);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(281).to({_off:false},0).to({y:172,alpha:1},8,cjs.Ease.quadOut).wait(31).to({alpha:0},8).wait(32));

	// txt_Immediatelamination
	this.instance_2 = new lib.txt_Immediatelamination();
	this.instance_2.setTransform(148.05,185.05,1,1,0,0,0,-6,0);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(232).to({_off:false},0).to({y:172.05,alpha:1},9,cjs.Ease.quadOut).wait(32).to({alpha:0},8).wait(79));

	// SureColor_lockup
	this.instance_3 = new lib.SureColor_lockup();
	this.instance_3.setTransform(162.05,139.95);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(326).to({_off:false},0).to({alpha:1},15).wait(19));

	// printer_mc
	this.instance_4 = new lib.printer_mc("single",9);
	this.instance_4.setTransform(161.25,303,0.8735,0.8735,0,0,0,0.3,0);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(232).to({_off:false},0).to({regX:0.2,scaleX:0.9423,scaleY:0.9423,x:161.2,y:308,alpha:1,mode:"synched",loop:false},9,cjs.Ease.quadOut).wait(44).to({mode:"single",startPosition:53},0).wait(31).to({startPosition:53},0).to({y:287},15,cjs.Ease.quadInOut).wait(29));

	// ctaBtn_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_345 = new cjs.Graphics().p("AqnDpQg2AAAAg2IAAAAIAAllQAAg2A2AAIAAAAIVPAAQA2AAAAA2IAAAAIAAFlQAAA2g2AAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(345).to({graphics:mask_graphics_345,x:160.0227,y:424.8225}).wait(15));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-19.3,-14.8,19.4,14.8).s().p("ArKIVIQS1RIGDEoIwSVSg");
	this.shape_1.setTransform(46.375,414.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-19.3,-14.8,19.4,14.8).s().p("ArKIWIQS1TIGDEpIwSVRg");
	this.shape_2.setTransform(48.475,414.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-19.3,-14.8,19.4,14.8).s().p("ArKIVIQS1RIGDEoIwSVRg");
	this.shape_3.setTransform(54.725,416.3);
	this.shape_3._off = true;

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-19.3,-14.8,19.4,14.8).s().p("ArKIWIQS1TIGDEpIwSVSg");
	this.shape_4.setTransform(79.775,422.55);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-19.3,-14.8,19.4,14.8).s().p("ArKIVIQS1SIGDEpIwSVRg");
	this.shape_5.setTransform(232.125,460.5);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},345).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4,p:{x:79.775,y:422.55}}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4,p:{x:217.525,y:456.85}}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4,p:{x:250.925,y:465.2}}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(347).to({_off:false},0).wait(1).to({x:65.175,y:418.9},0).to({_off:true},1).wait(1).to({_off:false,x:98.575,y:427.2},0).wait(1).to({x:121.525,y:432.95},0).wait(1).to({x:148.675,y:439.7},0).wait(1).to({x:175.775,y:446.45},0).wait(1).to({x:198.725,y:452.2},0).to({_off:true},1).wait(2).to({_off:false,x:242.575,y:463.1},0).wait(1).to({x:248.825,y:464.7},0).to({_off:true},1).wait(1));

	// ctaBtn
	this.instance_5 = new lib.ctaBtn();
	this.instance_5.setTransform(160,424.8,0.9029,0.9029);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(335).to({_off:false},0).to({alpha:1},10).wait(15));

	// BG
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_6.setTransform(152.05,302.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.11)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_7.setTransform(152.05,302.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,255,255,0.224)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_8.setTransform(152.05,302.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(255,255,255,0.333)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_9.setTransform(152.05,302.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0.443)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_10.setTransform(152.05,302.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.557)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_11.setTransform(152.05,302.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(255,255,255,0.667)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_12.setTransform(152.05,302.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(255,255,255,0.776)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_13.setTransform(152.05,302.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(255,255,255,0.89)").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_14.setTransform(152.05,302.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ega3AypMAAAhlRMA1vAAAMAAABlRg");
	this.shape_15.setTransform(152.05,302.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_6}]},223).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).wait(128));

	// txt_Immediatelamination
	this.instance_6 = new lib.txt_greater();
	this.instance_6.setTransform(157.3,509.65);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(54).to({_off:false},0).to({alpha:1},9).wait(158).to({alpha:0},11).to({_off:true},1).wait(127));

	// Layer_1
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#2D3482").ss(3,2,1).p("AgJAAIATAA");
	this.shape_16.setTransform(26.275,450.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#2D3482").ss(3,2,1).p("AgaAAIA1AA");
	this.shape_17.setTransform(28.025,450.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#2D3482").ss(3,2,1).p("AhOAAICdAA");
	this.shape_18.setTransform(33.225,450.825);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#2D3482").ss(3,2,1).p("AilAAIFLAA");
	this.shape_19.setTransform(41.925,450.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#2D3482").ss(3,2,1).p("AkfAAII/AA");
	this.shape_20.setTransform(54.075,450.825);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#2D3482").ss(3,2,1).p("AmZAAIMzAA");
	this.shape_21.setTransform(66.25,450.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#2D3482").ss(3,2,1).p("AnvAAIPfAA");
	this.shape_22.setTransform(74.925,450.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#2D3482").ss(3,2,1).p("AokAAIRJAA");
	this.shape_23.setTransform(80.15,450.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#2D3482").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_24.setTransform(81.875,450.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("rgba(45,52,130,0.91)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_25.setTransform(81.875,450.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("rgba(45,52,130,0.82)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_26.setTransform(81.875,450.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("rgba(45,52,130,0.725)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_27.setTransform(81.875,450.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("rgba(45,52,130,0.635)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_28.setTransform(81.875,450.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("rgba(45,52,130,0.545)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_29.setTransform(81.875,450.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("rgba(45,52,130,0.455)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_30.setTransform(81.875,450.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("rgba(45,52,130,0.365)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_31.setTransform(81.875,450.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("rgba(45,52,130,0.275)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_32.setTransform(81.875,450.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("rgba(45,52,130,0.18)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_33.setTransform(81.875,450.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("rgba(45,52,130,0.09)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_34.setTransform(81.875,450.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("rgba(45,52,130,0)").ss(3,2,1).p("Ao1AAIRrAA");
	this.shape_35.setTransform(81.875,450.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_16}]},160).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_24}]},53).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[]},1).wait(127));

	// txt_onARoll
	this.instance_7 = new lib.txt_onARoll();
	this.instance_7.setTransform(4.05,528.4);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(145).to({_off:false},0).to({x:144.05,alpha:1},11,cjs.Ease.quadOut).wait(65).to({alpha:0},11).to({_off:true},1).wait(127));

	// txt_Immediatelamination
	this.instance_8 = new lib.txt_greaterConsistency();
	this.instance_8.setTransform(157.3,509.65);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(54).to({_off:false},0).to({alpha:1},9).wait(73).to({x:305.3,alpha:0},11,cjs.Ease.quadOut).to({_off:true},86).wait(127));

	// Image_Strip_Mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_54 = new cjs.Graphics().p("AIPbqMAAAg2eIAAg1IPDAAMAAAA3TgAnpbqMAAAg3TIPaAAIAAA1MAAAA2egA3SbqMAAAg3JIPLAAMAAAA3Jg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(54).to({graphics:mask_1_graphics_54,x:160.05,y:184}).wait(179).to({graphics:null,x:0,y:0}).wait(127));

	// image_03_LG
	this.instance_9 = new lib.image_03_LG_1("synched",0,false);
	this.instance_9.setTransform(151,210);
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(163).to({_off:false},0).to({_off:true},70).wait(127));

	// image_02_LG
	this.instance_10 = new lib.image_02_LG_1("synched",0,false);
	this.instance_10.setTransform(151,210);
	this.instance_10._off = true;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(109).to({_off:false},0).to({_off:true},124).wait(127));

	// image_01_LG
	this.instance_11 = new lib.image_01_LG_1("synched",0,false);
	this.instance_11.setTransform(151,210);
	this.instance_11._off = true;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(54).to({_off:false},0).to({_off:true},179).wait(127));

	// logo_Lockup
	this.instance_12 = new lib.SureColor_lockup_intro();
	this.instance_12.setTransform(163.3,163.55);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).to({y:154.55,alpha:1},9).wait(34).to({alpha:0},10).to({_off:true},1).wait(306));

	// wht_fade
	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("rgba(255,255,255,0)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_36.setTransform(151.05,310.075);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("rgba(255,255,255,0.102)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_37.setTransform(151.05,309.775);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("rgba(255,255,255,0.2)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_38.setTransform(151.05,309.475);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("rgba(255,255,255,0.302)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_39.setTransform(151.05,309.175);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("rgba(255,255,255,0.4)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_40.setTransform(151.05,308.875);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("rgba(255,255,255,0.502)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_41.setTransform(151.05,308.575);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("rgba(255,255,255,0.6)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_42.setTransform(151.05,308.275);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("rgba(255,255,255,0.698)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_43.setTransform(151.05,307.975);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("rgba(255,255,255,0.8)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_44.setTransform(151.05,307.675);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("rgba(255,255,255,0.898)").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_45.setTransform(151.05,307.375);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("A9ORCMAAAgiDMA6dAAAMAAAAiDg");
	this.shape_46.setTransform(151.05,307.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_36}]},43).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[]},1).wait(306));

	// printer_mc
	this.instance_13 = new lib.printer_mc("single",9);
	this.instance_13.setTransform(160.25,290.15,0.9483,0.9483,0,0,0,0.2,0.1);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({scaleX:1.0172,scaleY:1.0172,x:160.2,y:296.1,alpha:1},9,cjs.Ease.quadOut).to({_off:true},45).wait(306));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(46.1,218,377.7,408.20000000000005);
// library properties:
lib.properties = {
	id: 'A4BDA2797E5D4A2296AB1960FDA0E060',
	width: 320,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Epson_Logo.png", id:"Epson_Logo"},
		{src:"image_01.jpg", id:"image_01"},
		{src:"image_01_LG.jpg", id:"image_01_LG"},
		{src:"image_02.jpg", id:"image_02"},
		{src:"image_02_LG.jpg", id:"image_02_LG"},
		{src:"image_03.jpg", id:"image_03"},
		{src:"image_03_LG.jpg", id:"image_03_LG"},
		{src:"Printer.jpg", id:"Printer"},
		{src:"printer_light.png", id:"printer_light"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['A4BDA2797E5D4A2296AB1960FDA0E060'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;