(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.cartridges_01 = function() {
	this.initialize(img.cartridges_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1020,250);


(lib.ecoTank_logo = function() {
	this.initialize(img.ecoTank_logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,191,71);


(lib.paintColors = function() {
	this.initialize(img.paintColors);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,513,600);


(lib.printer = function() {
	this.initialize(img.printer);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,373,292);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_twoYears = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ARaCeQgZgHgSgNQgTgOgLgVQgLgVAAgdIBDAAQAAAQAGALQAGALAJAHQAKAGAMAEQANADAOAAIATgBQALgCAJgEQAJgFAHgHQAGgIAAgMQAAgNgIgIQgIgIgOgFIhigdQgQgGgOgJQgNgKgIgQQgIgPAAgVQAAgYAKgSQALgSAQgMQARgMAVgGQAVgFAVAAQAZAAAXAFQAWAGASAMQASAMAKATQAKAUAAAbIhDAAQgBgOgFgKQgFgJgIgFQgIgFgLgDIgYgCIgQACQgJACgHAEQgGAFgFAGQgEAHAAAKQAAAJADAGQAEAGAKAEIBlAdQAPAEAQALQAPAJAMARQALARAAAaQAAAVgJATQgIASgRAOQgQANgYAIQgZAHggAAQgaAAgYgGgAMBCFQgjgeAAhBIAAjCIBFAAIAADCIADAaQACAMAHAJQAHAKAMAGQANAGAVAAQAlAAAOgRQAOgQAAgkIAAjCIBFAAIAADCQAABAgjAfQgkAfg/AAQhAAAgjgfgAHhCYQgdgNgUgWQgTgWgLgdQgKgeAAgjQAAgiAKgeQALgeATgWQAUgXAdgNQAdgMAkAAQAlAAAcAMQAdANATAXQAUAWALAeQAKAeAAAiQAAAjgKAeQgLAdgUAWQgTAWgdANQgcAMglAAQgkAAgdgMgAH6hgQgQAJgKAPQgKAPgFAUQgFATAAATQAAAUAFATQAFATAKAPQAKAPAQAJQARAJAXAAQAXAAARgJQAQgJAKgPQAKgPAFgTQAEgTAAgUQAAgTgEgTQgFgUgKgPQgKgPgQgJQgRgJgXAAQgXAAgRAJgAh8CFQgjgeAAhBIAAjCIBFAAIAADCIADAaQACAMAHAJQAHAKAMAGQANAGAVAAQAkAAAOgRQAOgQAAgkIAAjCIBFAAIAADCQAABAgjAfQgkAfg+AAQhAAAgjgfgAmMCYQgdgNgUgWQgTgWgLgdQgKgeAAgjQAAgiAKgeQALgeATgWQAUgXAdgNQAdgMAkAAQAaAAAXAHQAXAIASAOQATAOAMAVQALAVADAcIhCAAQgCgMgGgKQgGgKgKgHQgJgIgMgEQgLgEgNAAQgXAAgRAJQgQAJgKAPQgKAPgFAUQgFATAAATQAAAUAFATQAFATAKAPQAKAPAQAJQARAJAXAAQAgAAARgUQASgTAEggIBDAAQgDAegLAYQgLAXgSARQgSARgYAJQgYAIgdAAQgkAAgdgMgEgwvACbQgSgJgNgOQgMgQgGgUQgGgUAAgYQAAgXAGgVQAHgTANgQQAMgPATgJQATgJAZAAQARAAAPAFQAPAEAMAJQALAJAIANQAIANACAQIgcAAQgFgWgQgLQgRgMgWAAQgTAAgOAIQgOAHgJAMQgIALgFAQQgEAPAAARQAAATAEAQQAFAQAIAMQAJAMAOAIQAOAHATAAQAOAAALgFQALgEAIgJQAIgIAEgLQAFgMABgNIAcAAQgEApgYAWQgXAXgpAAQgZAAgTgJgEAm9ACcQgOgGgKgLQgJgLgFgPQgFgPAAgRQAAgRAFgPQAFgOAJgLQAKgLAOgHQAOgGASAAQATAAAOAGQAOAHAJALQAKALAFAOQAFAPAAARQAAARgFAPQgFAPgKALQgJALgOAGQgOAGgTAAQgSAAgOgGgEAnLAAaQgJAEgHAIQgGAHgEALQgEALAAAOQAAAOAEALQAEALAGAIQAHAHAJAEQAIAEAKAAQAKAAAJgEQAJgEAHgHQAGgIAEgLQAEgLAAgOQAAgOgEgLQgEgLgGgHQgHgIgJgEQgJgDgKAAQgKAAgIADgAfcCeQgKgEgHgIQgGgHgDgKQgCgLAAgMIAAhmIAZAAIAABpQAAAOAJAJQAIAIAPAAQAMAAAIgEQAJgDAFgHQAGgHADgIQADgJAAgLIAAhXIAZAAIAACbIgYAAIAAgZIAAAAQgIAOgNAHQgNAHgRAAQgPAAgKgEgAdACcQgPgGgJgLQgKgLgFgPQgEgPAAgRQAAgRAEgPQAFgOAKgLQAJgLAPgHQAOgGASAAQASAAAOAGQAOAHAKALQAKALAEAOQAFAPAAARQAAARgFAPQgEAPgKALQgKALgOAGQgOAGgSAAQgSAAgOgGgAdNAaQgJAEgGAIQgHAHgEALQgDALAAAOQAAAOADALQAEALAHAIQAGAHAJAEQAJAEAKAAQAKAAAJgEQAIgEAHgHQAHgIADgLQAEgLAAgOQAAgOgEgLQgDgLgHgHQgHgIgIgEQgJgDgKAAQgKAAgJADgAX2CdQgGgGAAgNQgLANgNAGQgOAFgRAAQgKAAgKgCQgJgDgHgFQgHgFgEgIQgEgJAAgLQAAgNAEgJQAFgIAHgFQAIgGAJgCIA4gLQAHgCAFgEQAEgEAAgHQAAgIgDgFQgEgFgEgDQgFgDgHgBIgMAAQgQAAgLAGQgLAGAAARIgaAAQABgOAFgKQAGgKAIgGQAJgHAMgCQAMgDANAAIAVACQAKABAIAFQAJAEAFAJQAFAIAAAOIAABPIABANQABAFAGAAIAIgCIAAAUQgHAEgLAAQgKAAgGgFgAXiBUIgiAFQgIABgHADQgHADgFAGQgEAFAAAKQAAAGADAEQACAFAEACQAEADAGABIALACQANAAAJgEQAJgDAFgGQAGgFADgGQACgGAAgFIAAgaQgEADgIACgA3QCdQgGgGAAgNQgLANgNAGQgOAFgRAAQgKAAgKgCQgJgDgHgFQgHgFgEgIQgEgJAAgLQAAgNAEgJQAFgIAHgFQAIgGAJgCIA4gLQAHgCAFgEQAEgEAAgHQAAgIgDgFQgEgFgEgDQgFgDgHgBIgMAAQgQAAgLAGQgLAGAAARIgaAAQABgOAFgKQAGgKAIgGQAJgHAMgCQAMgDANAAIAVACQAKABAIAFQAJAEAFAJQAFAIAAAOIAABPIABANQABAFAGAAIAIgCIAAAUQgHAEgLAAQgKAAgGgFgA3kBUIgiAFQgIABgHADQgHADgFAGQgEAFAAAKQAAAGADAEQACAFAEACQAEADAGABIALACQANAAAJgEQAJgDAFgGQAGgFADgGQACgGAAgFIAAgaQgEADgIACgEglAACfQgMgCgJgGQgJgHgFgKQgFgKgBgOIAaAAQAAAIADAGQAEAGAGADQAGAEAHABIAPACIANgBIAMgDQAGgDADgEQAEgFAAgHQAAgKgIgFQgHgFgMgDIgYgGQgNgDgLgEQgMgFgHgJQgIgIAAgPQAAgMAGgIQAFgIAIgGQAIgFALgCQAKgDAKAAQANAAAMACQALADAIAFQAJAGAFAJQAFAKABAOIgaAAQAAgIgEgFQgDgFgFgDQgFgDgGgBIgNgBIgLAAIgLAEQgFACgDAEQgDADAAAGQAAAHAFAEQAFAFAHACIA1APQAJACAHAFQAHAFAEAIQAFAHAAALQAAAPgGAJQgGAJgJAGQgKAGgMACQgMACgLAAQgNAAgMgDgEgnVACcQgOgGgJgLQgKgLgEgPQgFgPAAgRQAAgSAFgPQAFgOAKgLQAKgLANgGQAOgGAPAAQAVAAAOAJQANAIAJANQAIAOADAPQADAQAAAOIh0AAQgBAKADAJQADAJAGAHQAGAIAJAEQAJAEANAAQAQAAAKgIQALgHADgPIAZAAQgFAagRANQgSANgaAAQgTAAgNgGgEgnKAAaQgIADgGAGQgFAGgEAIQgDAIAAAJIBZAAQgBgJgDgIQgEgIgGgGQgGgGgHgDQgIgDgKAAQgKAAgIADgEgtuACcQgOgGgKgLQgJgLgFgPQgFgPAAgRQAAgRAFgPQAFgOAJgLQAKgLAOgHQAOgGASAAQATAAAOAGQAOAHAJALQAKALAFAOQAFAPAAARQAAARgFAPQgFAPgKALQgJALgOAGQgOAGgTAAQgSAAgOgGgEgtgAAaQgJAEgHAIQgGAHgEALQgEALAAAOQAAAOAEALQAEALAGAIQAHAHAJAEQAIAEAKAAQAKAAAJgEQAJgEAHgHQAGgIAEgLQAEgLAAgOQAAgOgEgLQgEgLgGgHQgHgIgJgEQgJgDgKAAQgKAAgIADgEAxGACfIAAgiIAhAAIAAAigEAwWACfIg1hRIgYAWIAAA7IgaAAIAAjVIAaAAIAAB9IBHhDIAiAAIg+A4IBCBjgEAt3ACfIAAhpQAAgPgIgIQgIgIgPAAQgMAAgIADQgJAEgGAGQgFAHgDAJQgDAJAAAKIAABYIgaAAIAAibIAYAAIAAAYIABAAQAQgcAiAAQAQAAAKAEQAKAEAGAIQAHAHACALQADAKAAANIAABmgEArYACfIAAibIAaAAIAACbgEApIACfIAAiFIgaAAIAAgWIAaAAIAAgXQAAgSALgKQALgKAVAAIAIABIAIACIAAAWIgHgCIgHAAQgJAAgFADQgGAEAAAKIAAAVIAfAAIAAAWIgfAAIAACFgEAkZACdQgHgBgFgEQgEgDgCgHQgCgGAAgLIAAhjIgbAAIAAgWIAbAAIAAguIAZAAIAAAuIAfAAIAAAWIgfAAIAABgIABAIQAAAAABABQAAAAAAABQAAAAABABQAAAAABABIAGACIAVAAIAAAXgEAjEACfIAAhpQAAgPgIgIQgIgIgPAAQgMAAgIADQgJAEgGAGQgFAHgDAJQgDAJAAAKIAABYIgaAAIAAibIAYAAIAAAYIABAAQAQgcAiAAQAQAAAKAEQAKAEAGAIQAHAHACALQADAKAAANIAABmgAbmCfIAAhmIgBgNQgBgHgDgEQgEgFgFgDQgGgCgKAAQgSAAgLAKQgLALAAASIAABhIgaAAIAAhmIgBgOQgBgGgEgFQgDgEgFgDQgGgCgJAAQgLAAgIAEQgIAFgFAGQgFAGgCAHQgCAHAAAEIAABhIgaAAIAAibIAYAAIAAAWIABAAQARgaAhAAQAPAAALAGQAMAGAFAOQAIgMAMgHQANgHAPAAQAMAAAKADQAJACAHAGQAGAFAEAJQAEAIAAAMIAABygA64CfIAAhpQAAgPgJgIQgIgIgPAAQgLAAgJADQgIAEgGAGQgGAHgDAJQgDAJAAAKIAABYIgZAAIAAjVIAZAAIAABQIABAAQADgHAGgFQAFgFAHgDIAOgEIAOgCQAPAAAKAEQALAEAGAIQAGAHADALQACAKAAANIAABmgA9XCdQgHgBgEgEQgEgDgDgHQgCgGAAgLIAAhjIgaAAIAAgWIAaAAIAAguIAaAAIAAAuIAfAAIAAAWIgfAAIAABgIABAIQAAAAAAABQAAAAABABQAAAAAAABQABAAAAABIAGACIAWAAIAAAXgA+tCfIAAibIAaAAIAACbgEggJACfIggh8IgBAAIgfB8IgbAAIgyibIAcAAIAjB+IABAAIAfh+IAcAAIAgB+IABAAIAjh+IAaAAIgxCbgEgouACfIAAhmIgBgNQgBgHgDgEQgEgFgFgDQgGgCgKAAQgSAAgLAKQgLALAAASIAABhIgaAAIAAhmIgBgOQgBgGgEgFQgDgEgFgDQgGgCgJAAQgLAAgIAEQgIAFgFAGQgFAGgCAHQgCAHAAAEIAABhIgaAAIAAibIAYAAIAAAWIABAAQARgaAhAAQAPAAALAGQAMAGAFAOQAIgMAMgHQANgHAPAAQAMAAAKADQAJACAHAGQAGAFAEAJQAEAIAAAMIAABygACcCdIAAk5IBFAAIAAD/ICZAAIAAA6gApOCdIAAk5IBFAAIAAE5gAuICdIAAk5ICHAAQAeAAAbAKQAaAJATAUQATATALAdQALAdAAAnQAAAigJAdQgJAdgSAVQgSAVgaAMQgbAMgkAAgAtDBjIA9AAQAPAAAOgFQAOgEALgMQALgLAHgSQAHgSAAgaQAAgXgFgTQgFgTgKgOQgLgNgRgIQgSgHgZAAIgxAAgAv+CdIAAk5IBFAAIAAE5gAxnCdQgGgPgBgUIgEgoQgDgZgMgLQgLgLgaAAIhFAAIAAB6IhFAAIAAk5ICpAAQAVAAARAHQARAHAMAMQAMAMAHAPQAGAQAAASQAAAbgMAVQgLAUgbAKIAAAAQANAEAIAHQAJAHAFAKQAFAKADAMIAJBSQACAKAFAGgAzrgOIBLAAQAYAAAMgKQAMgLAAgYQAAgXgMgKQgMgKgYAAIhLAAgEArYgAXIAAgfIAaAAIAAAfgA+tgXIAAgfIAaAAIAAAfg");
	this.shape.setTransform(337.475,46.325);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_twoYears, new cjs.Rectangle(20,29.9,635,32.9), null);


(lib.txt_theAssets = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AXPC1QgPgDgNgIQgNgIgIgNQgKgMgBgSIA5AAQAEAQALAGQAMAGAPAAQAYAAALgOQALgPAAgVIAAgcIgBAAQgJARgRAHQgRAIgTAAQgXAAgRgIQgRgIgKgOQgLgPgGgSQgEgUAAgUQAAgUAFgSQAGgTALgOQAMgOAQgJQARgIAWAAQAUAAAQAHQAPAIAKASIABAAIAAgcIA2AAIAADBQAAAMgEAQQgDARgLANQgMAOgUAKQgWAJgjAAQgQAAgQgEgAXfg5QgIAFgHAIQgFAJgDAKQgCALgBAMIACAVQADALAFAJQAFAIAKAGQAIAFANAAQAMAAAKgEQAJgFAGgIQAGgIADgKQADgKAAgMQAAgLgDgMQgCgLgGgJQgFgJgJgFQgKgFgOAAQgMAAgIAEgA8OBlQgZgMgSgVQgRgUgJgbQgIgagBgeQABgdAIgbQAJgbARgVQASgUAZgNQAZgMAjAAQAhAAAaAMQAZANASAUQARAVAJAbQAJAbAAAdQAAAegJAaQgJAbgRAUQgSAVgZAMQgaANghAAQgjAAgZgNgA7/iOQgTAKgMARQgMARgGAVQgFAVAAAVQAAAWAFAUQAGAVAMARQAMARATAKQASAKAbAAQAZAAAUgKQASgKAMgRQAMgRAGgVQAFgUABgWQgBgVgFgVQgGgVgMgRQgMgRgSgKQgUgKgZAAQgbAAgSAKgAeJBtQgRgEgNgIQgOgIgIgOQgJgOgBgVIA2AAQAAAJAFAHQADAHAHAEQAFAEAIACIAQACIANgCIAMgEQAGgDADgFQAEgFgBgIQABgMgSgHQgRgGgegHIgYgGQgMgEgKgGQgJgFgFgKQgFgJAAgOQAAgUAHgMQAIgNAMgIQAOgHAPgDQAQgDASAAQAQAAAQADQAQADAMAIQANAHAIANQAIANABATIg1AAQgCgQgKgGQgMgGgPAAIgKAAIgLADIgHAGQgEAEAAAGQAAAIAGAEQAGAFAIADIBEASQAMAEAKAFQAJAHAFAKQAGAJAAAPQAAAUgIAOQgIAOgOAIQgNAJgQADQgRAEgSAAQgSAAgSgEgAanBpQgTgIgOgPQgNgOgIgUQgHgUAAgYQAAgWAHgUQAIgUAPgPQAOgOASgJQAUgIAXAAQAbAAAUAKQATAKANARQANASAFAWQAGAWgCAXIiVAAQABAbANANQAMAMAYAAQASAAANgIQALgJADgKIAzAAQgMAlgZARQgZAQgkAAQgXAAgVgIgAa7g5QgIAFgGAHQgFAGgCAIIgDAOIBcAAQgDgWgLgLQgKgLgVAAQgOAAgJAEgATEBoQgRgKgMgPQgLgPgGgUQgGgUABgWQgBgUAGgTQAGgUALgOQAMgPARgJQARgJAXAAQATAAAQAIQAQAHAKAQIABAAIAAhoIA4AAIAAEcIg1AAIAAgaIgBAAQgKARgRAHQgPAIgVAAQgXAAgSgJgATkg4QgKAGgGAJQgGAJgCAMQgDAMAAAMQAAAMADAMQACAMAHAJQAGAJAJAGQAKAGANAAQAOAAAJgGQAKgFAGgKQAFgJADgMQACgMAAgNQAAgMgCgLQgDgMgFgJQgHgJgJgGQgJgFgOAAQgOAAgJAFgAGhBtQgNgEgJgHQgKgIgFgLQgFgMgBgQQABgSAFgLQAHgMAKgGQAJgGANgEIBIgMQAKgCAFgFQAHgEgBgJQAAgJgDgGQgDgFgFgDQgFgDgHgBIgOgBQgRAAgJAHQgKAHgCARIg5AAQACgUAJgNQAIgNAOgIQANgIARgEQARgDASAAIAfACQARACANAHQANAGAIALQAJAMgBATIACCFQACANAEAGIg6AAIgEgUQgNAOgTAGQgSAGgUAAQgOAAgNgEgAH3ALIgMADIgbAEIgMADIgKAGQgFADgDAFQgDAFAAAIQAAAIADAFQACAFAGADIAKAFIAOABQARAAAJgGQAJgFAEgIQAFgIABgIIABgigADLBpQgUgIgNgOQgOgOgHgUQgIgTAAgXQAAgXAHgVQAHgUAOgPQANgPAUgJQATgIAZAAQAUAAAQAFQARAFAOAJQANAKAJAPQAIAOABAUIg3AAQgGgjglAAQgNAAgJAGQgKAGgGAKQgFAKgDALQgCAMAAALQAAALACAMQADALAFAKQAFAJAKAGQAJAGANAAQAUAAAMgLQAKgMADgTIA3AAQgGApgaAWQgbAWgpAAQgXAAgTgIgAh1BpQgTgIgPgOQgNgOgIgUQgIgUAAgZQAAgYAIgUQAIgUANgOQAPgPATgHQAUgIAYAAQAZAAATAIQAUAHANAPQAOAOAIAUQAHAUABAYQgBAZgHAUQgIAUgOAOQgNAOgUAIQgTAIgZAAQgYAAgUgIgAhhg4QgJAGgHAJQgFAKgDAMQgCAMAAALQAAAMACAMQADAMAFAJQAHAKAJAFQAJAGAPAAQAPAAAJgGQAKgFAFgKQAGgJADgMQADgMgBgMQABgLgDgMQgDgMgGgKQgFgJgKgGQgJgFgPAAQgPAAgJAFgAsKBoQgTgHgLgPQgMgOgHgTQgGgTAAgYQAAgWAGgUQAGgUAMgPQANgPARgJQATgIAYAAQASAAAQAEQAPAEAMAJQAMAJAHANQAIANACATIgkAAQgDgUgOgKQgMgLgWAAQgSAAgMAGQgNAHgHALQgHAMgEAOQgDAPAAAOQAAAPADANQAEAOAHALQAHAKAMAHQALAGAQAAQAZAAAOgNQAPgNADgYIAjAAQgFAmgXAVQgYAVgnAAQgYAAgSgIgAt5BoQgJgHAAgRQgOARgSAHQgSAIgWAAQgOAAgNgEQgNgDgIgHQgKgGgFgLQgFgLgBgQQABgRAFgMQAHgLAJgHQAKgHAMgCIBLgPQAKgCAFgFQAGgFAAgKQAAgLgEgHQgEgHgHgDQgGgEgJgBIgQgBQgVAAgPAIQgPAIgBAXIgiAAQABgTAHgOQAIgNALgIQANgIAPgEQAPgDASAAIAcACQANACAMAGQALAGAHALQAHALAAASIAABpIABASQABAGAJAAIAKgCIAAAaQgJAGgQAAQgNAAgHgIgAuUAHIgtAHQgLACgJAEQgKAEgGAHQgFAIgBAMQAAAJAEAFQADAGAGAEQAFAEAHABIAQACQAQAAAMgFQAMgFAIgHQAIgGADgJQADgIABgHIAAgjQgHAFgKACgAyRBuIgTgFQgJgEgIgGQgJgGgGgJIgBAAIAAAbIghAAIAAkcIAhAAIAABrIABAAQAJgSASgHQASgIAWAAQAXAAASAJQASAIAMAPQAMAPAGAUQAGATAAAWQAAAVgGAUQgGAUgLAOQgMAPgTAIQgRAJgXAAgAyjhDQgMAHgIALQgHALgEAOQgDAOgBAOQAAAPAEAOQAEAOAIALQAHALANAGQAMAHASAAQASAAAMgHQALgHAHgLQAIgLADgOQACgPAAgPQAAgNgDgOQgEgOgIgLQgHgKgNgHQgMgGgQAAQgSAAgLAGgAM0BrQgLgBgJgGQgJgFgGgJQgFgKAAgQIAAh4IgiAAIAAgnIAiAAIAAg9IA5AAIAAA9IApAAIAAAnIgpAAIAABlQAAAOAFAFQAEAFAPAAIARgCIAAAsIggACgAkJBrQgMgBgIgGQgJgFgGgJQgFgKAAgQIAAh4IgiAAIAAgnIAiAAIAAg9IA5AAIAAA9IAqAAIAAAnIgqAAIAABlQAAAOAFAFQAFAFAOAAIASgCIAAAsIgiACgEAgmABrIAAg9IA+AAIAAA9gAQ8BrIAAjOIA6AAIAADOgAOfBrIAAjOIA2AAIAAAnIABAAQADgKAHgIQAHgIAJgGQAIgGALgDQAJgDALAAIANACIAAA1IgVgCQgPAAgLAFQgKAFgIAJQgGAJgDAMQgDALAAAOIAABdgAJWBrIAAjOIA2AAIAAAnIABAAQAFgKAGgIQAHgIAIgGQAKgGAJgDQAKgDAMAAIAMACIAAA1IgUgCQgQAAgLAFQgLAFgHAJQgGAJgDAMQgCALAAAOIAABdgAndBrIhHhrIghAdIAABOIgiAAIAAkcIAiAAIAACpIBfhbIAuAAIhSBMIBXCCgA3yBrIAAj8IhgAAIAAggIDlAAIAAAgIhfAAIAAD8gA+pBrIiWjkIAAAAIAADkIgkAAIAAkcIApAAICVDmIABAAIAAjmIAkAAIAAEcgAQ8iDIAAguIA6AAIAAAug");
	this.shape.setTransform(560.55,-85.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_theAssets, new cjs.Rectangle(345.8,-103.8,429.59999999999997,37.099999999999994), null);


(lib.txt_noMore = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAZIAAgxIAxAAIAAAxg");
	this.shape.setTransform(723.375,-30.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgrBwQgVgIgOgQQgOgRgHgXQgHgWAAgaQAAgaAIgWQAIgWAOgRQAPgPAUgKQAUgIAXgBQAfAAAUAOQAVAMAMAUQANAUAEAXQAFAXgBAUIitAAQAAAQADANQAFAOAJALQAJAKANAHQAPAGARAAQAZAAAPgLQAQgMAFgWIAlAAQgHAngaATQgaAVgogBQgbAAgUgJgAgahRQgMAFgJAIQgIAKgFAMQgFALgBAOICFAAQgBgNgFgNQgGgMgIgJQgJgIgMgFQgMgGgOAAQgOAAgMAGg");
	this.shape_1.setTransform(705.0333,-39.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhICiIgOgDIAAgjIAMAEIALABQALAAAJgFQAHgGAEgKIARgoIhdjmIArAAIBDC9IABAAIBBi9IApAAIhlEHIgNAdQgGALgIAIQgIAHgJAEQgKADgNAAg");
	this.shape_2.setTransform(681.05,-35.075);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgOChIgVgGQgKgEgJgGQgKgIgGgKIgBAAIAAAfIgmAAIAAlAIAmAAIAAB4IABAAQAJgTAVgJQAUgJAXAAQAbAAAUAKQAUAKAOARQANARAHAVQAGAWAAAYQAAAZgGAWQgHAWgNARQgNAQgUAKQgUAJgbAAgAgigmQgNAIgJANQgJAMgDAPQgEAPAAAQQAAASAEAPQAEAQAJAMQAIAMAOAIQAOAHATAAQAUAAANgHQAOgIAIgMQAIgNADgQQAEgRAAgRQAAgQgEgPQgFgOgIgNQgJgMgOgHQgOgIgRABQgTAAgOAHg");
	this.shape_3.setTransform(656.825,-43.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgxCZQgUgKgOgQQgNgRgGgWQgHgXAAgYQAAgYAGgWQAHgWANgQQANgQAVgKQATgKAbAAIASACIAVAGQAKAEAJAHQAJAHAHALIABAAIAAh4IAmAAIAAFAIgmAAIAAgfIgBAAQgKATgTAJQgVAIgXAAQgcAAgTgKgAgggmQgNAIgJANQgHANgEAPQgEAPAAASQAAAQAEAPQAFAQAIAMQAJANAOAGQAOAIASgBQATAAANgHQANgIAJgMQAJgMADgQQAEgQAAgQQAAgRgEgQQgEgPgIgMQgKgNgOgHQgNgIgUABQgTAAgNAHg");
	this.shape_4.setTransform(628.45,-43.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgwBwQgVgJgOgRQgPgQgHgWQgHgWAAgZQAAgZAHgWQAHgXAPgRQAOgPAVgKQAVgKAbAAQAcAAAVAKQAVAKAOAPQAOARAIAXQAHAWAAAZQAAAZgHAWQgIAWgOAQQgOARgVAJQgVAJgcAAQgbAAgVgJgAgbhRQgOAGgJALQgKAMgGAQQgGAQAAAVQAAAUAGARQAGAQAKALQAJAMAOAFQANAGAOAAQAPAAANgGQANgFAKgMQAKgLAGgQQAFgRAAgUQAAgVgFgQQgGgQgKgMQgKgLgNgGQgNgGgPAAQgOAAgNAGg");
	this.shape_5.setTransform(602.575,-39.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgwBwQgVgJgOgRQgPgQgHgWQgHgWAAgZQAAgZAHgWQAHgXAPgRQAOgPAVgKQAVgKAbAAQAcAAAVAKQAVAKAOAPQAOARAIAXQAHAWAAAZQAAAZgHAWQgIAWgOAQQgOARgVAJQgVAJgcAAQgbAAgVgJgAgbhRQgOAGgJALQgKAMgGAQQgGAQAAAVQAAAUAGARQAGAQAKALQAJAMAOAFQANAGAOAAQAPAAANgGQANgFAKgMQAKgLAGgQQAFgRAAgUQAAgVgFgQQgGgQgKgMQgKgLgNgGQgNgGgPAAQgOAAgNAGg");
	this.shape_6.setTransform(576.425,-39.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghCiQgRgDgOgJQgOgHgJgNQgJgNAAgUIAlAAQABALAGAHQAGAIAJAEQAJAEAKACIATACQASABAOgHQANgGAJgMQAIgMADgQQAEgQABgTIAAgPIgCAAQgJAVgVAKQgTAKgWAAQgaAAgUgKQgSgIgNgQQgOgRgGgVQgHgVABgXQAAgVAEgWQAGgVAMgTQANgRAVgMQAVgLAdAAQAWAAASAKQATAKAKASIABAAIAAghIAkAAIAADUQAAA5gaAdQgaAcg3AAQgRAAgQgEgAgch9QgNAIgJALQgIAMgDAPQgFAQAAAQQAAAQAEAQQADAPAIANQAHAMANAIQAMAIATAAQASAAANgIQAOgIAIgMQAIgNAEgQQAEgQgBgQQABgPgEgPQgEgPgHgMQgIgMgNgHQgNgIgSABQgRAAgNAGg");
	this.shape_7.setTransform(549.65,-35.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgqCGQgWgEgRgLQgRgLgLgRQgLgTgBgZIBFAAQAAALAFAIQAFAJAHAFQAIAFAKADIATADIARgCIAPgGQAHgDAEgHQAFgGAAgKQAAgQgWgJQgWgHglgJIgfgJQgPgEgMgHQgMgIgHgMQgHgMAAgRQAAgZAKgRQAKgRAQgJQARgJAUgEQAVgDAVgBQAUAAAVAFQAUADAPAKQAQAJALARQAKAQACAYIhFAAQgBgVgOgHQgPgIgSABIgNABIgNACIgKAIQgEAFAAAIQAAAJAHAHQAHAGALAEIAaAHIAeAHIAeAIQAQAFALAIQAMAIAHAMQAHANAAATQAAAZgKASQgLASgQALQgRAKgWAEQgWAEgWAAQgWAAgWgEg");
	this.shape_8.setTransform(508.825,-41.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag0CBQgZgKgRgSQgSgTgJgZQgKgaAAgeQAAgdAKgaQAKgZASgTQASgSAYgLQAZgLAdAAQAiABAZANQAZAMAQAWQAQAWAHAcQAHAcgCAeIi9AAQABAjARAPQAQAQAeAAQAWABAQgLQAPgMAEgMIBAAAQgQAwgfAVQggATgtAAQgeAAgZgJgAgbhNQgLAFgHAKQgHAHgDALIgDARIB1AAQgFgcgNgOQgNgOgbAAQgQAAgMAGg");
	this.shape_9.setTransform(480.1722,-41.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgsC0QgVgFgQgKQgRgLgLgPQgLgQgBgXIBIAAQAFAUAPAJQAOAHATAAQAeAAAOgSQAOgSAAgcIAAgjIgBAAQgMAVgVAKQgWAKgXAAQgeAAgVgKQgVgLgOgSQgOgSgHgXQgGgZAAgbQAAgaAIgXQAHgYAOgSQAPgSAVgKQAVgLAbAAQAZAAAUAKQAUAJANAXIABAAIAAgjIBFAAIAAD2QAAAQgFAUQgEAUgOASQgOASgcALQgaANgtAAQgTAAgUgFgAgZh8QgLAHgHAKQgIALgDANQgDANAAAPIACAcQADAOAHAMQAHAKALAHQALAHAQAAQAQAAALgGQAMgGAIgKQAHgJAEgNQAEgNAAgOQAAgRgDgPQgDgOgHgLQgIgMgLgGQgMgGgSAAQgOAAgLAFg");
	this.shape_10.setTransform(449.075,-36.65);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhDCuQgWgMgPgTQgPgUgHgZQgHgaAAgbQAAgbAHgYQAHgYAPgTQAPgTAWgLQAVgMAeAAQAWAAAWAKQAUAKAMATIABAAIAAiEIBJAAIAAFrIhFAAIAAgiIgBAAQgMAWgVAJQgVAJgZAAQgdAAgXgLgAgbgdQgMAHgIALQgHALgEAPQgDAPAAARQAAAPAEAPQAEAQAHAMQAIALANAIQALAHAQAAQASAAAMgHQALgHAIgMQAHgMADgPQADgQAAgQQAAgQgDgPQgDgPgIgLQgHgLgMgHQgLgHgSAAQgRAAgMAHg");
	this.shape_11.setTransform(417.6,-45.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgjC2IAAkHIBHAAIAAEHgAgjh6IAAg7IBHAAIAAA7g");
	this.shape_12.setTransform(395.625,-46.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhUCHIAAkGIBFAAIAAAxIABAAQAFgNAIgKQAJgLAKgHQALgHANgEQAOgEANAAIAQACIAABDIgNgBIgNgBQgUAAgOAGQgNAHgJALQgHAMgEAPQgDAQgBAQIAAB3g");
	this.shape_13.setTransform(380.15,-41.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAKCqQgOgCgLgHQgLgGgHgNQgHgMAAgUIAAiaIgsAAIAAgxIAsAAIAAhPIBIAAIAABPIA1AAIAAAxIg1AAIAACCQAAASAGAGQAGAGASAAIAMgBIALgBIAAA4IgVACIgWABg");
	this.shape_14.setTransform(359.375,-45.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhUCHIAAkGIBFAAIAAAxIABAAQAFgNAIgKQAIgLALgHQAMgHANgEQAMgEAOAAIAQACIAABDIgNgBIgNgBQgUAAgOAGQgNAHgJALQgIAMgDAPQgEAQABAQIAAB3g");
	this.shape_15.setTransform(341.7,-41.625);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhJCGQgRgEgLgKQgNgKgHgPQgGgPgBgUQABgXAHgOQAIgOAMgJQANgIAQgEIAggHIAhgEIAbgFQAMgCAHgHQAHgFAAgMQAAgMgEgGQgEgHgGgEQgGgEgJgBIgSgBQgVgBgMAKQgMAJgCAVIhJAAQACgZALgRQALgRASgKQARgKAWgEQAVgFAWAAIAoADQAUADARAIQARAIAKAOQALAPAAAZIAACHIACAjQACAQAGAIIhKAAIgEgMIgBgOQgRATgYAGQgXAIgYgBQgTAAgQgEgAAjAJIgOAEIgRACIgQADIgRAEIgNAHQgGAFgDAGQgFAHAAAKQAAAKAFAGQADAHAGAEIAOAFIARACQAUgBANgGQALgIAGgKQAFgJABgKIACgRIAAgbg");
	this.shape_16.setTransform(315.35,-41.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgyCBQgZgKgSgSQgQgSgLgZQgJgZAAgdQAAgeAJgaQAIgaASgTQASgUAZgKQAZgLAeAAQAYAAAVAHQAXAGAQAMQASANAKASQALATACAZIhHAAQgIgtguAAQgRAAgLAHQgLAJgIAMQgHAMgEAPQgDAQAAAOQAAAOADAOQAEAPAHAMQAGAMAMAIQAMAHAQAAQAaAAANgOQAOgPAEgYIBGAAQgHA0giAcQgiAbg0AAQgcAAgZgJg");
	this.shape_17.setTransform(286.2,-41.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag0CBQgZgKgRgSQgSgTgJgZQgKgaAAgeQAAgdAKgaQAKgZASgTQASgSAYgLQAZgLAdAAQAiABAZANQAZAMAQAWQAQAWAHAcQAHAcgCAeIi9AAQABAjARAPQAQAQAeAAQAWABAQgLQAPgMAEgMIBAAAQgQAwgfAVQggATgtAAQgeAAgZgJgAgbhNQgLAFgHAKQgHAHgDALIgDARIB1AAQgFgcgNgOQgNgOgbAAQgQAAgMAGg");
	this.shape_18.setTransform(241.7722,-41.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgmCEIhbkHIBMAAIA2CzIACAAIA4izIBHAAIhZEHg");
	this.shape_19.setTransform(213.55,-41.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgjC2IAAkHIBHAAIAAEHgAgjh6IAAg7IBHAAIAAA7g");
	this.shape_20.setTransform(193.375,-46.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgqCGQgWgEgRgLQgRgLgLgRQgLgTgBgZIBFAAQAAALAFAIQAFAJAHAFQAIAFAKADIATADIARgCIAPgGQAHgDAEgHQAFgGAAgKQAAgQgWgJQgWgHglgJIgfgJQgPgEgMgHQgMgIgHgMQgHgMAAgRQAAgZAKgRQAKgRAQgJQARgJAUgEQAVgDAVgBQAUAAAVAFQAUADAPAKQAQAJALARQAKAQACAYIhFAAQgBgVgOgHQgPgIgSABIgNABIgNACIgKAIQgEAFAAAIQAAAJAHAHQAHAGALAEIAaAHIAeAHIAeAIQAQAFALAIQAMAIAHAMQAHANAAATQAAAZgKASQgLASgQALQgRAKgWAEQgWAEgWAAQgWAAgWgEg");
	this.shape_21.setTransform(172.775,-41.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAzCHIAAiUQAAgggKgQQgKgQgaAAQgdAAgNARQgNASAAAoIAACJIhJAAIAAkGIBFAAIAAAkIACAAQAOgXAVgKQAVgKAXAAQAdAAATAHQATAIAKAOQALAOAEAVQAFAUAAAYIAAChg");
	this.shape_22.setTransform(143.675,-41.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag0CBQgZgKgRgSQgSgTgJgZQgKgaAAgeQAAgdAKgaQAKgZASgTQASgSAYgLQAZgLAdAAQAiABAZANQAZAMAQAWQAQAWAHAcQAHAcgCAeIi9AAQABAjARAPQAQAQAeAAQAWABAQgLQAPgMAEgMIBAAAQgQAwgfAVQggATgtAAQgeAAgZgJgAgbhNQgLAFgHAKQgHAHgDALIgDARIB1AAQgFgcgNgOQgNgOgbAAQgQAAgMAGg");
	this.shape_23.setTransform(113.5722,-41.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AiFC2IAAlkIBFAAIAAAiIABAAQANgWAUgJQAVgKAXAAQAfAAAXAMQAWAMAPATQAPAUAHAZQAHAaAAAcQAAAagHAYQgHAZgPASQgOAUgWALQgWALgdgBQgXAAgVgJQgUgKgOgTIgBAAIAAB9gAgfh3QgLAHgIAMQgHAMgDAPQgDAPAAARQAAAQADAPQADAPAIALQAHALAMAHQAMAIASgBQARABAMgIQAMgHAHgLQAHgLAEgPQADgPAAgQQAAgQgEgPQgDgPgIgNQgHgMgMgHQgMgHgRAAQgSAAgMAHg");
	this.shape_24.setTransform(83.625,-37);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AA2CEIg2hTIg3BTIhRAAIBfiKIhXh9IBTAAIAtBFIAuhFIBQAAIhWB8IBhCLg");
	this.shape_25.setTransform(53.45,-41.275);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ag0CBQgZgKgRgSQgSgTgJgZQgKgaAAgeQAAgdAKgaQAKgZASgTQASgSAYgLQAZgLAdAAQAiABAZANQAZAMAQAWQAQAWAHAcQAHAcgCAeIi9AAQABAjARAPQAQAQAeAAQAWABAQgLQAPgMAEgMIBAAAQgQAwgfAVQggATgtAAQgeAAgZgJgAgbhNQgLAFgHAKQgHAHgDALIgDARIB1AAQgFgcgNgOQgNgOgbAAQgQAAgMAGg");
	this.shape_26.setTransform(24.7722,-41.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgkB2QgSgEgNgKQgOgJgIgPQgIgPgBgWIAnAAQAAAMAFAJQAGAJAJAGQAIAFALACIAWACIATgBIASgFQAIgDAGgIQAFgHAAgKQAAgQgLgHQgLgIgRgEIgkgJQgUgEgRgGQgQgGgMgNQgLgNAAgWQAAgSAIgNQAIgMAMgIQANgIAPgDQAQgFAPAAQATAAAQAEQARADANAIQANAJAHAOQAIAOABAVIgmAAQgBgLgFgIQgFgHgHgFQgIgDgJgDIgSgCIgRABIgQAGQgHACgFAHQgEAFAAAJQAAAKAHAGQAHAHAKAEIAZAHIAaAHIAcAHQAOAFAKAGQALAHAGALQAHAMAAAQQAAAWgJANQgJAOgOAJQgOAJgSADQgSAEgRgBQgTAAgRgDg");
	this.shape_27.setTransform(-15.925,-39.75);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgkB2QgSgEgNgKQgOgJgIgPQgIgPgBgWIAnAAQAAAMAFAJQAGAJAJAGQAIAFALACIAWACIATgBIASgFQAIgDAGgIQAFgHAAgKQAAgQgLgHQgLgIgRgEIgkgJQgUgEgRgGQgQgGgMgNQgLgNAAgWQAAgSAIgNQAIgMAMgIQANgIAPgDQAQgFAPAAQATAAAQAEQARADANAIQANAJAHAOQAIAOABAVIgmAAQgBgLgFgIQgFgHgHgFQgIgDgJgDIgSgCIgRABIgQAGQgHACgFAHQgEAFAAAJQAAAKAHAGQAHAHAKAEIAZAHIAaAHIAcAHQAOAFAKAGQALAHAGALQAHAMAAAQQAAAWgJANQgJAOgOAJQgOAJgSADQgSAEgRgBQgTAAgRgDg");
	this.shape_28.setTransform(-38.775,-39.75);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgSChIAAjoIAlAAIAADogAgShxIAAgvIAlAAIAAAvg");
	this.shape_29.setTransform(-55.35,-44.15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("ABPChIhziiIg1AxIAABxIgrAAIAAlBIArAAIAACgICiigIA3AAIiHCCICMC/g");
	this.shape_30.setTransform(-73.875,-44.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_noMore, new cjs.Rectangle(-141.9,-79.8,923.1999999999999,64.8), null);


(lib.txt_lets = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgnAnIAAhNIBPAAIAABNg");
	this.shape.setTransform(670.6,-55.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AArC2IhIh2IgcAbIAABbIhJAAIAAlrIBJAAIAADCIBbheIBVAAIhjBgIBuCng");
	this.shape_1.setTransform(653.25,-69.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AhUCHIAAkGIBFAAIAAAxIABAAQAFgNAJgKQAHgLAMgHQALgHANgEQAMgEAOAAIAQACIAABDIgMgBIgOgBQgUAAgOAGQgOAHgIALQgHAMgEAPQgEAQAAAQIAAB3g");
	this.shape_2.setTransform(630.75,-65.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("Ag3CBQgagJgRgTQgSgSgKgaQgKgZABgfQgBgfAKgaQAKgaASgSQARgSAagKQAYgKAfAAQAfAAAZAKQAZAKASASQASASAKAaQAKAagBAfQABAfgKAZQgKAagSASQgSATgZAJQgZAJgfAAQgfAAgYgJgAgehMQgMAHgIAMQgHAMgDAPQgDAPAAAQQAAAPADAPQADAPAHAMQAIAMAMAHQAMAIASgBQASABAMgIQANgHAHgMQAHgMAEgPQADgPAAgPQAAgQgDgPQgEgPgHgMQgHgMgNgHQgMgHgSAAQgSAAgMAHg");
	this.shape_3.setTransform(606.45,-64.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAvCEIgviwIAAAAIgtCwIhLAAIhUkHIBNAAIAxCyIABAAIAsiyIBFAAIAtCyIABAAIAwiyIBKAAIhTEHg");
	this.shape_4.setTransform(572.6,-64.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("Ag4CBQgYgJgSgTQgSgSgKgaQgKgZABgfQgBgfAKgaQAKgaASgSQASgSAYgKQAZgKAfAAQAfAAAZAKQAZAKASASQASASAKAaQAKAaAAAfQAAAfgKAZQgKAagSASQgSATgZAJQgZAJgfAAQgfAAgZgJgAgehMQgMAHgIAMQgHAMgDAPQgDAPAAAQQAAAPADAPQADAPAHAMQAIAMAMAHQAMAIASgBQASABAMgIQANgHAHgMQAHgMADgPQAEgPAAgPQAAgQgEgPQgDgPgHgMQgHgMgNgHQgMgHgSAAQgSAAgMAHg");
	this.shape_5.setTransform(527.15,-64.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAKCqQgOgCgLgHQgLgGgHgNQgHgMAAgUIAAiaIgsAAIAAgxIAsAAIAAhPIBIAAIAABPIA1AAIAAAxIg1AAIAACCQAAASAGAGQAGAGASAAIAMgBIALgBIAAA4IgVACIgWABg");
	this.shape_6.setTransform(504.875,-68.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AArC2IhIh2IgcAbIAABbIhJAAIAAlrIBJAAIAADCIBbheIBVAAIhjBgIBuCng");
	this.shape_7.setTransform(474.15,-69.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgzCBQgYgKgRgSQgSgSgJgZQgKgZAAgdQAAgeAJgaQAJgaARgTQARgUAZgKQAagLAeAAQAYAAAVAHQAXAGARAMQARANAKASQALATABAZIhHAAQgHgtguAAQgRAAgLAHQgMAJgHAMQgIAMgCAPQgDAQAAAOQAAAOADAOQACAPAHAMQAHAMAMAIQALAHAQAAQAbAAAOgOQAOgPADgYIBGAAQgHA0giAcQghAbg1AAQgcAAgagJg");
	this.shape_8.setTransform(445.9,-64.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AhJCGQgQgEgNgKQgMgKgHgPQgHgPAAgUQAAgXAIgOQAIgOANgJQAMgIAQgEIAggHIAhgEIAbgFQAMgCAHgHQAHgFAAgMQgBgMgDgGQgEgHgGgEQgHgEgIgBIgSgBQgUgBgNAKQgMAJgCAVIhJAAQACgZAMgRQALgRARgKQARgKAWgEQAVgFAVAAIApADQAUADARAIQARAIALAOQAKAPAAAZIAACHIACAjQACAQAFAIIhJAAIgEgMIgCgOQgQATgYAGQgXAIgYgBQgTAAgQgEgAAkAJIgQAEIgQACIgRADIgQAEIgNAHQgGAFgDAGQgEAHgBAKQABAKAEAGQADAHAGAEIAPAFIAQACQAUgBAMgGQAMgIAFgKQAGgJACgKIABgRIAAgbg");
	this.shape_9.setTransform(418.7,-64.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgcCwQgWgJgMgWIgBAAIAAAiIhFAAIAAlrIBJAAIAACEIAAAAQAOgUAWgKQAXgJAXAAQAVAAATAIQAUAIAOARQARARAJAaQAKAZAAAlQAAAkgKAaQgJAagRARQgOARgUAIQgTAIgVAAQgbAAgYgJgAgcgeQgMAHgHAMQgIALgEAPQgDAPAAARQAAAQADAQQAEAPAIAMQAHALAMAHQAMAHAPAAQAQAAAMgHQALgHAIgLQAHgMAEgPQADgQAAgQQAAgRgDgPQgEgPgHgLQgIgMgLgHQgMgGgQAAQgPAAgMAGg");
	this.shape_10.setTransform(391.6,-69.375);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AAmCrIgdgCQgMgCgHgGQgIgHgDgLQgEgLABgSIAAinIgtAAIAAgmIAtAAIAAhPIAqAAIAABPIA0AAIAAAmIg0AAIAACiIABANQACAEADADIAKADIAQABIAUAAIAAAmg");
	this.shape_11.setTransform(357.85,-68.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgxCAQgYgLgPgSQgQgSgIgaQgIgagBgdQAAgeAJgZQAJgZARgSQAQgSAXgLQAXgJAagBQAjAAAXAPQAYAOAOAWQAOAYAFAZQAFAbgBAXIjEAAQAAARAEAQQAFAPAKANQAKALAQAIQAQAHAUAAQAcAAARgNQASgMAFgbIArAAQgIAsgeAXQgdAXgtAAQgfAAgXgKgAgehdQgNAGgKAKQgKALgFANQgGANgBAQICWAAQgBgPgFgOQgGgOgKgKQgKgKgOgGQgNgFgQAAQgQAAgOAFg");
	this.shape_12.setTransform(339.5077,-64.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgmC4QgTgEgQgJQgPgKgKgPQgLgOgBgWIAsAAQAAANAHAHQAHAJAKAFQAKAFAMACIAVADQAVAAAPgIQAPgHAKgNQAJgNAFgTQAEgSAAgWIAAgRIgBAAQgLAYgXAMQgXALgYAAQgeAAgWgKQgVgMgPgRQgPgTgIgYQgHgXAAgbQAAgXAGgZQAGgZAPgUQAOgUAXgNQAYgNAhAAQAZAAAVALQAVAKAMAXIAAAAIAAgmIApAAIAADwQAABBgeAgQgdAgg/AAQgSAAgTgEgAggiNQgOAIgKANQgJANgFASQgEARAAATQAAASADASQAEARAJAOQAIAOAPAKQAOAJAVAAQAVAAAPgJQAPgKAJgOQAJgOAFgSQAEgSAAgSQAAgSgEgRQgEgRgJgNQgJgNgOgJQgPgIgUAAQgUAAgPAIg");
	this.shape_13.setTransform(312.675,-59.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgpCFQgUgEgPgLQgQgLgJgQQgJgSgBgYIAsAAQAAAOAGAKQAGAKAKAGQAKAGANACIAYADIAWgBIAUgGQAKgEAGgIQAGgJAAgMQAAgQgNgJQgMgJgUgFIgogJQgXgFgTgHQgTgIgNgOQgMgPAAgYQAAgVAJgOQAJgOAOgKQANgIASgEQASgFARAAQAVAAATAEQATAEAPAJQAOAJAJARQAJAQABAXIgrAAQgBgMgGgJQgFgHgJgGQgJgFgKgCIgUgCIgUABIgSAFQgIAEgFAGQgGAHAAAKQAAALAIAHQAIAIANAFIAbAIIAeAHIAgAJQAPAFAMAIQAMAHAIANQAHANAAATQAAAYgKAPQgKAQgQAKQgQAKgUADQgUAFgUAAQgVgBgUgEg");
	this.shape_14.setTransform(276.875,-64.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgbAoQAJAAAFgEQAGgEADgIIAEgQIACgQIgdAAIAAg5IA3AAIAAA5QAAAOgDAOQgDANgHAKQgHAKgKAHQgKAGgPAAg");
	this.shape_15.setTransform(259.525,-81.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AAlCrIgdgCQgLgCgHgGQgHgHgEgLQgEgLAAgSIAAinIgtAAIAAgmIAtAAIAAhPIArAAIAABPIA0AAIAAAmIg0AAIAACiIABANQABAEAEADIAKADIARABIATAAIAAAmg");
	this.shape_16.setTransform(246.4,-68.625);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgxCAQgYgLgPgSQgQgSgIgaQgIgagBgdQAAgeAJgZQAJgZARgSQAQgSAXgLQAXgJAagBQAjAAAXAPQAYAOAOAWQAOAYAFAZQAFAbgBAXIjEAAQAAARAEAQQAFAPAKANQAKALAQAIQAQAHAUAAQAcAAARgNQASgMAFgbIArAAQgIAsgeAXQgdAXgtAAQgfAAgXgKgAgehdQgNAGgKAKQgKALgFANQgGANgBAQICWAAQgBgPgFgOQgGgOgKgKQgKgKgOgGQgNgFgQAAQgQAAgOAFg");
	this.shape_17.setTransform(228.0577,-64.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("Ah3C2IAAlrIAwAAIAAFCIC/AAIAAApg");
	this.shape_18.setTransform(204.25,-69.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_lets, new cjs.Rectangle(186.2,-103.2,491.2,64.80000000000001), null);


(lib.txt_ecoTankPro_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgRApQgIgDgGgGQgGgGgFgJQgCgHgBgKQABgJACgJQAFgHAGgGQAGgGAIgDQAIgDAJAAQAKAAAHADQAIADAHAGQAFAGAFAHQADAJAAAJQAAAKgDAHQgFAJgFAGQgHAGgIADQgHADgKAAQgJAAgIgDgAgMgfQgHACgEAFQgEAFgDAGQgDAGAAAHQAAAIADAFQADAHAEAFQAEAEAHADQAFACAHAAQAHAAAGgCIALgHQAEgFADgHQACgFAAgIQAAgHgCgGQgDgGgEgFQgGgFgFgCQgGgDgHAAQgHAAgFADgAAJAYIgKgUIgHAAIAAAUIgJAAIAAgwIASAAQAIgBAGAEQAFAEgBAHIAAAGIgDAEIgEACIgFACIANAUgAgIgDIAJAAQAEAAADgCQACAAAAgFIgBgDIgCgCIgHgBIgIAAg");
	this.shape.setTransform(392.5788,-35.2501,1.2418,1.2418);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AqYCMQgTgIgLgOQgNgPgGgUQgGgUgBgXQAAgXAIgTQAGgUANgOQAOgPARgIQATgIAVAAQAcAAASAMQARAKAMASQAKASAFAUQAEAVgBATIiaAAQAAANACAMQADANAJAJQAIAJANAGQANAFAPAAQAWAAAOgKQAOgJAEgVIAiAAQgHAjgWASQgYARgjAAQgZAAgTgIgAqIggQgLAEgHAJQgIAIgEAKQgGAKABALIB2AAQAAgLgFgKQgFgLgIgIQgIgIgKgEQgLgFgMAAQgOAAgKAFgAtrCMQgSgIgMgOQgNgPgGgUQgGgUAAgXQAAgXAGgTQAHgUAOgOQANgPARgIQASgIAVAAQAcAAASAMQATAKALASQAKASAEAUQAFAVgBATIibAAQAAANADAMQAEANAIAJQAHAJANAGQANAFARAAQAVAAAOgKQAOgJAFgVIAgAAQgHAjgWASQgXARgjAAQgZAAgTgIgAtcggQgKAEgIAJQgHAIgFAKQgEAKgBALIB3AAQgBgLgFgKQgDgLgJgIQgHgIgLgEQgLgFgMAAQgOAAgLAFgAnKCOQgKgCgFgEQgGgFgCgJQgDgJgBgOIAAiDIgjAAIAAgeIAjAAIAAg+IAjAAIAAA+IApAAIAAAeIgpAAIAACAIABAJQABADACACIAIADIAdAAIAAAfgAvwCQIAAjtIgCAAIhZDtIghAAIhajtIAADtIgkAAIAAkdIA1AAIBaDvIBajvIA0AAIAAEdgAD/CHQgUgGgNgPQgOgOgIgUQgIgUAAgZQAAgZAIgUQAIgUAOgOQANgOAUgIQATgIAYAAQAaAAATAIQAVAIANAOQAPAOAGAUQAJAUgBAZQABAZgJAUQgGAUgPAOQgNAPgVAGQgUAIgZAAQgYAAgTgIgAEUgZQgLAFgFAKQgGAKgCALQgCALAAANQAAAMACAMQACAMAGAJQAFAKALAFQAJAGANAAQAQAAAJgGQAJgFAHgKQAGgJACgMQADgMAAgMQAAgNgDgLQgCgLgGgKQgHgKgJgFQgJgGgQAAQgNAAgJAGgAAcCHQgSgIgNgNQgOgOgIgUQgHgTgBgYQAAgYAIgTQAGgUAOgQQANgPATgIQAVgJAYAAQATAAARAFQARAFANAKQAOAKAIAOQAIAPACATIg4AAQgGgjgkAAQgOAAgKAGQgIAHgGAKQgFAIgDAMQgCAMAAAMQAAALACAMQADALAFAJQAFAKAJAGQAKAGANAAQAUAAALgLQAMgMACgTIA3AAQgFApgcAWQgaAVgpAAQgXAAgUgIgAKECLQgNgEgKgIQgJgHgGgLQgFgMAAgQQAAgRAGgMQAHgLAIgGQALgHANgDIBHgMQAJgDAFgEQAGgFAAgHQgBgKgDgFQgCgFgFgCQgFgEgHgBIgNgBQgRAAgKAHQgJAHgCARIg3AAQAAgUAJgNQAJgNANgIQAOgHARgEQAQgDARAAIAfACQAQACANAGQANAHAIALQAJALgBASIACCEQABAMAFAHIg5AAIgEgUQgNAOgTAFQgRAGgTAAQgPAAgMgDgALYAqIgyAKIgKAFQgFAEgDAFQgDAFAAAIQAAAIADAEQADAGAFACIAKAFIAOABQAQAAAJgGQAJgFAFgIQAEgIABgHIABgigAkUCKIAAkdIDWAAIAAA1IiXAAIAAA+ICLAAIAAAvIiLAAIAABGICaAAIAAA1gASnCJIg5hbIgVAVIAABGIg3AAIAAkZIA3AAIAACXIBHhJIBDAAIhOBKIBWCBgAPKCJIAAhzQgBgYgHgNQgIgNgTAAQgYAAgKAOQgKAOAAAeIAABrIg4AAIAAjLIA1AAIAAAcIACAAQALgRAQgIQARgIARAAQAWAAAPAGQAOAGAJAKQAIALADAQQAEAQAAASIAAB9gAHbCJIAAjlIhVAAIAAg0IDnAAIAAA0IhWAAIAADlg");
	this.shape_1.setTransform(261.95,-30.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_ecoTankPro_Logo, new cjs.Rectangle(136.1,-45,262.20000000000005,29.5), null);


(lib.txt_EcoTankPro = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1F1F1F").s().p("AA6AhIAAgyIAAAAIgUAyIgJAAIgUgyIAAAyIgLAAIAAhBIARAAIASAtIASgtIATAAIAABBgAgxAhIAAg3IgUAAIAAgKIA2AAIAAAKIgVAAIAAA3g");
	this.shape.setTransform(564.75,-151.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1F1F1F").s().p("AgcAcIAAg3IA5AAIAAA3g");
	this.shape_1.setTransform(560.95,-129.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1F1F1F").s().p("AgZCEIAAkHIAzAAIAAEHg");
	this.shape_2.setTransform(551.225,-140.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1F1F1F").s().p("AgZCEIAAkHIAzAAIAAEHg");
	this.shape_3.setTransform(541.825,-140.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1F1F1F").s().p("AgZCEIAAi+IAzAAIAAC+gAgZhYIAAgrIAzAAIAAArg");
	this.shape_4.setTransform(532.475,-140.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1F1F1F").s().p("AAlCEIAAhsQAAgYgIgKQgGgMgUAAQgUAAgJANQgKALAAAeIAABkIg1AAIAAkHIA1AAIAABjIABAAQAKgQAQgIQAOgHAPAAQAVAAAOAFQANAGAHAKQAJAKACAPQAEAPAAAQIAAB2g");
	this.shape_5.setTransform(516.9,-140.025);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1F1F1F").s().p("AgkBdQgSgHgNgNQgMgNgIgSQgHgSAAgVQABgWAGgTQAHgTAMgOQANgNASgIQASgIAWAAQARAAARAEQAPAFANAJQAMAJAHAOQAJANAAATIgzAAQgFghgiAAQgLAAgJAFQgIAGgGAJQgGAJgCALQgCALAAAKQAAAKACALQACALAFAIQAGAJAJAGQAIAFALAAQATAAAKgKQAKgLADgSIAyAAQgEAmgZAVQgYAUgnAAQgUAAgSgIg");
	this.shape_6.setTransform(495.65,-136.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1F1F1F").s().p("AhGCDQgQgFgMgKQgLgLgHgOQgGgPAAgTQAAgOAEgMQAGgLAIgKQAIgJALgHIAWgNQgLgNgHgNQgHgNAAgRQAAgOAGgLQAGgLAJgIQAKgIAMgEQANgEANAAQAPAAAMAEQANAEALAIQAJAIAGAMQAGAMgBAPQAAAXgNAQQgOAQgTALIAiApIAGgPIADgRIAuAAQgCASgGARQgHARgLAOIA2A+IhAAAIgWgaQgQAQgSAHQgRAIgXAAQgRAAgQgFgAgxAWIgLAJQgGAGgDAGQgDAHAAAIQAAAHADAHQADAGAGAFQAEAEAIADQAGADAHAAQAPAAAKgGQAKgHAJgKIgsg3gAghheQgHAHAAAKQgBANAIAJIANASQAMgHAHgIQAIgIgBgPQABgKgHgIQgHgHgKAAQgJAAgHAGg");
	this.shape_7.setTransform(462.95,-139.925);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1F1F1F").s().p("AgZCEIAAkHIAzAAIAAEHg");
	this.shape_8.setTransform(434.725,-140.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1F1F1F").s().p("AgZCEIAAkHIAzAAIAAEHg");
	this.shape_9.setTransform(425.325,-140.025);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1F1F1F").s().p("AgZCEIAAi+IAzAAIAAC+gAgZhYIAAgrIAzAAIAAArg");
	this.shape_10.setTransform(415.975,-140.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#1F1F1F").s().p("AgdCEIAAibIggAAIAAgjIAgAAIAAgPQAAgaAQgQQAPgQAgAAIAOAAIAOABIAAAnIgUgBQgKAAgFAFQgFAFAAAMIAAAMIAlAAIAAAjIglAAIAACbg");
	this.shape_11.setTransform(405.225,-140.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#1F1F1F").s().p("AAIB7QgKgBgJgFQgHgEgFgJQgGgKAAgOIAAhwIgfAAIAAgjIAfAAIAAg6IA0AAIAAA6IAmAAIAAAjIgmAAIAABeQAAAOAEADQAFAFANAAIAJAAIAHgBIAAAoIgOACIgQAAg");
	this.shape_12.setTransform(382.4,-139.15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1F1F1F").s().p("AgeBhQgQgDgMgIQgNgIgIgMQgIgNgBgUIAzAAQAAAJADAGQAEAGAFAEQAGAEAHACIAOACIAMgCIALgEQAFgCADgFQADgFAAgHQAAgMgPgFQgQgGgbgGIgXgHQgLgDgIgFQgJgGgFgIQgFgJAAgNQAAgSAHgMQAHgMAMgHQAMgHAPgCQAPgDAPAAQAPAAAPADQAOADAMAHQALAHAIAMQAHALACASIgyAAQgBgPgLgFQgKgGgNAAIgKABIgJACIgHAFQgDAEAAAGQAAAHAFAEQAFAFAIADIASAFIAWAEIAXAHQALADAIAHQAJAFAFAJQAFAJAAANQAAATgIANQgHANgMAIQgNAHgPADQgQAEgQAAQgQAAgQgEg");
	this.shape_13.setTransform(366.225,-136.375);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#1F1F1F").s().p("Ag1BdQgOgGgIgKQgIgLgDgOQgDgPAAgSIAAh0IA1AAIAABrQAAAYAHALQAIAMATAAQAUAAAJgNQAKgNAAgdIAAhjIA1AAIAAC+IgzAAIAAgaIgBAAQgJAQgRAIQgOAHgRAAQgVAAgNgFg");
	this.shape_14.setTransform(345.55,-136.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#1F1F1F").s().p("AggCDQgPgFgNgKQgMgKgHgPQgIgQAAgVIAAgXIA1AAIAAAMIACARQABAIAEAGQADAGAHADQAGAEALAAQAKAAAHgEQAGgFADgGQADgGAAgIIABgPIAAixIA6AAIAAC0QAAANgDAPQgCAQgKAOQgJANgRAJQgSAJgdAAQgQAAgQgEg");
	this.shape_15.setTransform(323.375,-139.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_EcoTankPro, new cjs.Rectangle(312.1,-165,261.4,48.3), null);


(lib.printer_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.printer();
	this.instance.setTransform(-284.05,-32.95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_02, new cjs.Rectangle(-284,-32.9,373,292), null);


(lib.printer_01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.printer();
	this.instance.setTransform(1040.35,-402.25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_01, new cjs.Rectangle(1040.4,-402.2,373,292), null);


(lib.main_paint = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgmTAvIQgmhrgZihQgylAA/kHIDDuTQgQgugXg3QgshugcgsQgyhLgoiPQhSkfAvlUQAbjIBKkZQCUoxDtmOQBPisBPjqQCdnSAAkvIAjjkQAmjvAWg1INDgFQiNBSiXByQkvDkgyCdQiRIrg8DSQgpBJg1B6QhtDzhCDuQjUL7EZGvIDRkYQA3hXA6hsQBzjXANhkQAWibA+i4QB7lvDBiRQBkhACJgaQEQg0C1DBQA+BTAeCDQA5EHipDzQggAyhkBVQjICqlSCvIhMAnQhfA0hcBEQknDZiiElQBBBQBTBbQCkC0BYAyQB4BNB9BVQD6CqAZAmQAtj8BkkfQDIo8ETipQgFh6AvieQBck7D/ivQBuhLB4hNQDtibAsgNQCHlyCBmqQEBtWgfkZIDIAAQAKAUAHAoQAQBQgNBkQg1EpgqE6QhVJxAyBLIAmg0QAthAAnhAQB9jOANh9IAihZQAuhqA+hTQDIkMEgA4QBfAoBfBLQC+CWAACvQAIBdg9B5Qh7DzlYCQIruE2QAFB1AVCbQArE2BRC8IBZDaQBdDlASA+QAoD2AlFaQBIK0gTH6IBlBZQB6ByBvB8QFgGOBeFkUhN0gAUgAUAAKgAC3naQhLBzgeBfQC2hdCojpQBTh0AwhiQjiBkiWDmg");
	mask.setTransform(-20.9436,175.8081);

	// Layer_1
	this.instance = new lib.paintColors();
	this.instance.setTransform(-279.55,-123.75);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.main_paint, new cjs.Rectangle(-276.9,-123.7,510.4,600), null);


(lib.epson_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AB/B3QgZgKgOgRQgPgRgIgXQgJgYAAgbQAAgbAJgXQAIgYAPgSQAOgSAZgKQAXgKAbAAQAeAAAWAKQAYAKAOASQAQASAJAYQAHAXAAAbQAAAbgHAYQgJAXgQARQgOARgYAKQgWALgeAAQgbAAgXgLgACThLQgNAGgJANQgHAKgEARQgEAPAAAPQAAAPAEAQQAEAOAHANQAJALANAGQANAJARAAQATAAAOgJQAMgGAIgLQAHgNAEgOQAEgQAAgPQAAgPgEgPQgEgRgHgKQgIgNgMgGQgOgJgTAAQgRAAgNAJgAhnB9QgUgGgOgLQgPgKgJgRQgJgQACgXIAzAAQABANAEAIQAFAJAIAEQAGAGALAEQAJABALAAIAPAAQAJgBAHgFQAHgCAFgHQAGgGAAgKQAAgJgHgIIgQgKIhOgWQgNgFgMgHQgJgIgHgMQgGgMAAgQQAAgUAIgPQAIgMAOgLQANgJAQgFQARgEARAAQATAAASADQASAGANAJQAOALAIAOQAHAPAAAXIgzAAQAAgMgFgIQgDgGgGgEQgIgGgIgBIgTgCIgOABQgGACgEAEQgHAEgCAEQgEAFAAAJQAAAHADAEQADAFAIAEIBRAXQAKADALAHQANAHAIANQAKAOAAAWQAAAQgIAOQgFAQgOALQgMAJgUAHQgSAGgbAAQgTAAgTgFgAHbB8IhnilIAAClIgzAAIAAj2IA3AAIBnCkIABAAIAAikIAyAAIAAD2gAmNB8IAAj2IBxAAQAWAAAQAHQAQAFAKALQALALAFAPQAFAPAAANQAAARgFAOQgFAOgLALQgKALgQAGQgQAHgWAAIg7AAIAABZgAlXgGIA9gBQAIgBAHgFQAHgEAEgIQADgGAAgOQAAgKgDgHQgEgHgHgEQgHgFgIgBIg9gBgApqB8IAAj2IC4AAIAAAsIiCAAIAAA1IB4AAIAAApIh4AAIAAA/ICGAAIAAAtgAJHhKQgFgCgFgDIgFgKQgDgFAAgFQAAgHADgFIAFgJQAFgFAFgBQAFgBAEAAQAGAAAGABQAFABADAFIAHAJIAAAMIAAAKIgHAKQgDADgFACQgGABgGAAQgEAAgFgBgAJJh4QgEACgCADQgEACgCAEIgBAKIABAIQACADAEADQACAEAEACIAHABIAJgBQAEgCADgEIAEgGIABgIIgBgKQgBgEgDgCQgDgDgEgCIgJgBIgHABgAJWhVIgGgNIgEAAIAAANIgHAAIAAgeIALAAQAHAAADACQAEACAAAFIAAAEIgCADIgDAAIgDABIAIANgAJMhmIAEAAIAGAAIAAgFIAAgCIAAgBIgKAAg");
	this.shape.setTransform(65.75,33.1971,1.8837,1.8837);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.epson_logo, new cjs.Rectangle(-50.9,8.8,233.4,48.900000000000006), null);


(lib.ecoTank_logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.ecoTank_logo();
	this.instance.setTransform(136.95,-14.4,1.5617,1.5617);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ecoTank_logo_1, new cjs.Rectangle(137,-14.4,298.3,110.9), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAdIAAguIgRAAIAAgLIAvAAIAAALIgSAAIAAAug");
	this.shape.setTransform(25.25,-0.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRAXQgGgFAAgMIAAgiIAMAAIAAAiIAAAFIACAEIAEACQACACADAAQAHAAACgDQADgDAAgHIAAgiIAMAAIAAAiQAAAMgGAFQgHAGgLAAQgLAAgGgGg");
	this.shape_1.setTransform(19.975,-0.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKAcQgGgDgDgEQgEgEgCgFQgCgGAAgGQAAgFACgGQACgFAEgFQADgDAGgDQAEgCAGAAQAHAAAFACQAFADAEADQADAFACAFQACAGAAAFQAAAGgCAGQgCAFgDAEQgEAEgFADQgFACgHAAQgGAAgEgCgAgGgRIgFAEIgDAHIgBAGIABAHIADAGIAFAEQADADADAAQAFAAADgDQADgBABgDIADgGIABgHIgBgGIgDgHIgEgEQgDgCgFAAQgDAAgDACg");
	this.shape_2.setTransform(14,-0.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAdIAAguIgRAAIAAgLIAuAAIAAALIgRAAIAAAug");
	this.shape_3.setTransform(6.5,-0.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFAdIAAg5IALAAIAAA5g");
	this.shape_4.setTransform(2.975,-0.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AALAdIgQgaIgIAHIAAATIgMAAIAAg5IAMAAIAAAYIAWgYIAPAAIgWAXIAYAig");
	this.shape_5.setTransform(-2.775,-0.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgJAcQgGgDgDgEQgEgEgCgFQgCgGAAgGQAAgFACgGQACgFAEgFQADgDAGgDQAFgCAFAAQAFAAAEABQAFACADADQADACACAEQACADABAFIgMAAIgCgEIgCgCIgEgDIgFgBQgDAAgDACIgFAEIgCAHIgBAGIABAHIACAGIAFAEQADADADAAQAGAAADgEQAEgDAAgHIANAAIgDAKQgCAEgDADQgEADgEACQgEACgGAAQgFAAgFgCg");
	this.shape_6.setTransform(-8.775,-0.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgVAdIAAg5IAqAAIAAALIgdAAIAAAMIAaAAIAAAJIgaAAIAAAOIAeAAIAAALg");
	this.shape_7.setTransform(-14.075,-0.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AALAdIAAgZIgWAAIAAAZIgMAAIAAg5IAMAAIAAAXIAWAAIAAgXIANAAIAAA5g");
	this.shape_8.setTransform(-19.625,-0.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJAcQgGgDgDgEQgEgEgCgFQgCgGAAgGQAAgFACgGQACgFAEgFQADgDAGgDQAFgCAFAAQAFAAAEABQAFACADADQADACACAEQACADABAFIgMAAIgCgEIgCgCIgEgDIgFgBQgDAAgDACIgFAEIgCAHIgBAGIABAHIACAGIAFAEQADADADAAQAGAAADgEQAEgDAAgHIANAAIgDAKQgCAEgDADQgEADgEACQgEACgGAAQgFAAgFgCg");
	this.shape_9.setTransform(-25.425,-0.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E61404").s().p("AkjBiQgcAAAAgbIAAiNQAAgbAcAAIJHAAQAcAAAAAbIAACNQAAAbgcAAg");
	this.shape_10.setTransform(-0.125,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-32.1,-9.9,64,19.700000000000003), null);


(lib.cartridge_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.cartridges_01();
	this.instance.setTransform(-244.05,-76.95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.cartridge_mc, new cjs.Rectangle(-244,-76.9,1020,250), null);


// stage content:
(lib.Epson_B2B_NonPro_970x66 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		var root = this; //Declared variable for access to global scope.
		
		this.popUp_btn.addEventListener("click", popUpBtn.bind(this));
		this.panel.addEventListener("click", exitPanel.bind(this));
		
		
		this.on("click", function (e) {
			window.open(clickTag, "_blank");
			console.log("ClickTag pressed");
			
		});
		
		
		function popUpBtn(e) {
			e.stopPropagation();
			root.panel.x = 0;
			root.stop();
			console.log("PopUp button pressed");
		}
		
		
		function exitPanel(e) {
			e.stopPropagation();
			root.panel.x = 970;
			root.play();
			console.log("Panel Closed");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(277));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EBLygFJIAAKTMiXjAAAIAAqTg");
	this.shape.setTransform(485,33);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(277));

	// epson_logo
	this.instance = new lib.epson_logo();
	this.instance.setTransform(41.8,16.25,0.2749,0.2749,0,0,0,67.7,32);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(251).to({_off:false},0).to({alpha:1},8).wait(18));

	// ecoTank_logo
	this.instance_1 = new lib.ecoTank_logo_1();
	this.instance_1.setTransform(110.9,14.55,0.1797,0.1797,0,0,0,286.9,43.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(251).to({_off:false},0).to({alpha:1},8).wait(18));

	// ctaBtn_Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_259 = new cjs.Graphics().p("AlkB4QgiAAAAghIAAAAIAAitQAAghAiAAIAAAAILJAAQAiAAAAAhIAAAAIAACtQAAAhgiAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(259).to({graphics:mask_graphics_259,x:868.4469,y:36.0778}).wait(18));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-14.6,-9.6,14.7,9.5).s().p("Ao9ItINW0YIElC/ItWUYg");
	this.shape_1.setTransform(810.225,16.25);
	this.shape_1._off = true;

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-14.6,-9.6,14.7,9.5).s().p("Ao9ItINW0ZIElDAItWUZg");
	this.shape_2.setTransform(811.025,16.55);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-14.6,-9.6,14.7,9.5).s().p("Ao9ItINW0YIElC/ItWUZg");
	this.shape_3.setTransform(813.375,17.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-14.6,-9.6,14.7,9.5).s().p("Ao9ItINW0ZIElDAItWUYg");
	this.shape_4.setTransform(829.975,23.55);
	this.shape_4._off = true;

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},259).to({state:[{t:this.shape_2,p:{x:811.025,y:16.55}}]},1).to({state:[{t:this.shape_3,p:{x:813.375,y:17.4}}]},1).to({state:[{t:this.shape_2,p:{x:817.325,y:18.9}}]},1).to({state:[{t:this.shape_3,p:{x:822.875,y:20.9}}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_3,p:{x:838.725,y:26.75}}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_3,p:{x:904.725,y:51.15}}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_2,p:{x:917.425,y:55.8}}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_2,p:{x:923.725,y:58.15}}]},1).to({state:[{t:this.shape_1}]},1).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(259).to({_off:false},0).to({_off:true},1).wait(6).to({_off:false,x:848.975,y:30.55},0).wait(1).to({x:860.825,y:34.95},0).to({_off:true},1).wait(1).to({_off:false,x:885.775,y:44.15},0).to({_off:true},1).wait(6).to({_off:false,x:924.525,y:58.45},0).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(264).to({_off:false},0).to({_off:true},1).wait(3).to({_off:false,x:873.875,y:39.75},0).to({_off:true},1).wait(1).to({_off:false,x:896.025,y:47.95},0).to({_off:true},1).wait(1).to({_off:false,x:911.875,y:53.8},0).to({_off:true},1).wait(1).to({_off:false,x:921.375,y:57.3},0).to({_off:true},1).wait(2));

	// ctaBtn
	this.instance_2 = new lib.ctaBtn();
	this.instance_2.setTransform(868.95,36.55,1.223,1.223,0,0,0,0.3,0.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(251).to({_off:false},0).to({alpha:1},8).wait(18));

	// txt_EcoTankPro
	this.instance_3 = new lib.txt_EcoTankPro();
	this.instance_3.setTransform(103.75,122.45,0.65,0.65,0,0,0,0.1,0);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(251).to({_off:false},0).to({alpha:1},8,cjs.Ease.quadOut).wait(18));

	// Layer_85
	this.instance_4 = new lib.printer_02();
	this.instance_4.setTransform(544.35,36.85,0.2467,0.2467,0,0,0,-93.9,110);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(251).to({_off:false},0).to({regX:-94,scaleX:0.2878,scaleY:0.2878,y:39.6,alpha:1},8,cjs.Ease.quadOut).wait(18));

	// Layer_107
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,255,255,0)").s().p("EhPTAaAQgoAAABgpMAAAgyuQgBgoAoABMCemAAAQApgBAAAoIAADTMAAAAsWIAADFQAAApgpAAg");
	this.shape_5.setTransform(491.55,129.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0.09)").s().p("EhPRAZ7QgoAAAAgoMAAAgylQAAgoAoAAMCejAAAQAoAAAAAoMAAAAylQAAAogoAAg");
	this.shape_6.setTransform(491.375,128.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.18)").s().p("EhPPAZ2QgoAAAAgoMAAAgybQAAgoAoAAMCefAAAQAoAAAAAoMAAAAybQAAAogoAAg");
	this.shape_7.setTransform(491.175,128.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,255,255,0.275)").s().p("EhPNAZxQgoAAAAgoMAAAgySQAAgoAoABMCebAAAQAogBAAAoMAAAAySQAAAogoAAg");
	this.shape_8.setTransform(491,127.95);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(255,255,255,0.365)").s().p("EhPLAZtQgoAAAAgoMAAAgyJQAAgoAoAAMCeXAAAQAoAAAAAoMAAAAyJQAAAogoAAg");
	this.shape_9.setTransform(490.825,127.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0.455)").s().p("EhPKAZoQgoAAABgoMAAAgx/QgBgoAoAAMCeUAAAQApAAAAAoMAAAAx/QAAAogpAAg");
	this.shape_10.setTransform(490.65,127.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.545)").s().p("EhPIAZkQgoAAABgoMAAAgx3QgBgoAoAAMCeRAAAQAoAAgBAoMAAAAx3QABAogoAAg");
	this.shape_11.setTransform(490.45,126.575);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(255,255,255,0.635)").s().p("EhPGAZfQgoAAAAgoMAAAgxtQAAgoAoAAMCeNAAAQAoAAAAAoMAAAAxtQAAAogoAAg");
	this.shape_12.setTransform(490.275,126.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(255,255,255,0.725)").s().p("EhPEAZaQgoAAAAgnMAAAgxlQAAgoAoABMCeJAAAQAogBAAAoMAAAAxlQAAAngoAAg");
	this.shape_13.setTransform(490.1,125.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(255,255,255,0.82)").s().p("EhPCAZWQgoAAAAgoMAAAgxbQAAgoAoAAMCeFAAAQAoAAAAAoMAAAAxbQAAAogoAAg");
	this.shape_14.setTransform(489.925,125.175);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(255,255,255,0.91)").s().p("EhPAAZRQgoAAAAgoMAAAgxRQAAgoAoAAMCeBAAAQAoAAAAAoMAAAAxRQAAAogoAAg");
	this.shape_15.setTransform(489.725,124.725);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("EhO/AZMQgoABABgoMAAAgxJQgBgoAoABMCd/AAAQAogBgBAoIAADTMAAAArGIAACwQABAogogBg");
	this.shape_16.setTransform(489.55,124.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5}]},239).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[]},1).wait(26));

	// txt_noMore
	this.instance_5 = new lib.txt_noMore();
	this.instance_5.setTransform(152.65,64.35);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(193).to({_off:false},0).to({y:76.85,alpha:1},8,cjs.Ease.quadOut).to({_off:true},50).wait(26));

	// Layer_102
	this.instance_6 = new lib.cartridge_mc();
	this.instance_6.setTransform(-800.9,32.85,1.0299,1.0299);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(183).to({_off:false},0).to({x:247.1},15,cjs.Ease.quadOut).to({_off:true},53).wait(26));

	// main_paint
	this.instance_7 = new lib.main_paint();
	this.instance_7.setTransform(1263.2,-211.05);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(119).to({_off:false},0).to({x:-240.8},28,cjs.Ease.quadInOut).to({_off:true},1).wait(129));

	// Layer_1 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_90 = new cjs.Graphics().p("EhtZAwOMgAWhgbIFlAAIGIAAIAEAAILoAAMCJLAAAIGMAAIDMAAMAxjAAAMgNBBgRIgCAKg");
	var mask_1_graphics_119 = new cjs.Graphics().p("EhtZAwOMgAWhgbIFlAAIGIAAIAEAAILoAAMCJLAAAIGMAAIDMAAMAxjAAAMgNBBgRIgCAKg");
	var mask_1_graphics_120 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_121 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_122 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_123 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_124 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_125 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_126 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_127 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_128 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_129 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_130 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_131 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_132 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_133 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_134 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_135 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_136 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_137 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_138 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_139 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_140 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_141 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_142 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_143 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_144 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_145 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_146 = new cjs.Graphics().p("EhtZAwOMgAWhgbMDbfAAAMgNDBgbg");
	var mask_1_graphics_147 = new cjs.Graphics().p("EhtZAwOMgAWhgbIFlAAIGIAAIAEAAILoAAMCJLAAAIGMAAIDMAAMAxjAAAMgNBBgRIgCAKg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(90).to({graphics:mask_1_graphics_90,x:660.725,y:62.35}).wait(29).to({graphics:mask_1_graphics_119,x:660.725,y:62.35}).wait(1).to({graphics:mask_1_graphics_120,x:656.875,y:62.35}).wait(1).to({graphics:mask_1_graphics_121,x:645.375,y:62.35}).wait(1).to({graphics:mask_1_graphics_122,x:626.175,y:62.35}).wait(1).to({graphics:mask_1_graphics_123,x:599.275,y:62.35}).wait(1).to({graphics:mask_1_graphics_124,x:564.675,y:62.35}).wait(1).to({graphics:mask_1_graphics_125,x:522.425,y:62.35}).wait(1).to({graphics:mask_1_graphics_126,x:472.475,y:62.35}).wait(1).to({graphics:mask_1_graphics_127,x:414.875,y:62.35}).wait(1).to({graphics:mask_1_graphics_128,x:349.575,y:62.35}).wait(1).to({graphics:mask_1_graphics_129,x:276.525,y:62.35}).wait(1).to({graphics:mask_1_graphics_130,x:195.875,y:62.35}).wait(1).to({graphics:mask_1_graphics_131,x:107.525,y:62.35}).wait(1).to({graphics:mask_1_graphics_132,x:11.475,y:62.35}).wait(1).to({graphics:mask_1_graphics_133,x:-92.275,y:62.35}).wait(1).to({graphics:mask_1_graphics_134,x:-195.975,y:62.35}).wait(1).to({graphics:mask_1_graphics_135,x:-292.025,y:62.35}).wait(1).to({graphics:mask_1_graphics_136,x:-380.375,y:62.35}).wait(1).to({graphics:mask_1_graphics_137,x:-461.075,y:62.35}).wait(1).to({graphics:mask_1_graphics_138,x:-534.075,y:62.35}).wait(1).to({graphics:mask_1_graphics_139,x:-599.375,y:62.35}).wait(1).to({graphics:mask_1_graphics_140,x:-657.025,y:62.35}).wait(1).to({graphics:mask_1_graphics_141,x:-706.975,y:62.35}).wait(1).to({graphics:mask_1_graphics_142,x:-749.225,y:62.35}).wait(1).to({graphics:mask_1_graphics_143,x:-783.825,y:62.35}).wait(1).to({graphics:mask_1_graphics_144,x:-810.675,y:62.35}).wait(1).to({graphics:mask_1_graphics_145,x:-829.925,y:62.35}).wait(1).to({graphics:mask_1_graphics_146,x:-841.425,y:62.35}).wait(1).to({graphics:mask_1_graphics_147,x:-845.275,y:62.35}).wait(1).to({graphics:null,x:0,y:0}).wait(129));

	// epson_logo
	this.instance_8 = new lib.epson_logo();
	this.instance_8.setTransform(42,16.55,0.2759,0.2759,0,0,0,66.3,34.2);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(90).to({_off:false},0).to({alpha:1},8).to({_off:true},39).wait(140));

	// ecoTank_logo
	this.instance_9 = new lib.ecoTank_logo_1();
	this.instance_9.setTransform(111.7,14.7,0.1683,0.1683,0,0,0,287.9,44.2);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(90).to({_off:false},0).to({alpha:1},8).to({_off:true},39).wait(140));

	// Layer_22
	this.instance_10 = new lib.txt_ecoTankPro_Logo();
	this.instance_10.setTransform(148.7,56.9);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(90).to({_off:false},0).to({y:64.4,alpha:1},8,cjs.Ease.quadOut).to({_off:true},39).wait(140));

	// txt_pain
	this.instance_11 = new lib.printer_01();
	this.instance_11.setTransform(617.2,37.85,0.272,0.2485,0,0,0,1227.9,-254.6);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(90).to({_off:false},0).to({regX:1227.8,regY:-254.8,scaleX:0.3128,scaleY:0.2858,y:41.35,alpha:1},8).to({_off:true},39).wait(140));

	// Layer_2 (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_119 = new cjs.Graphics().p("EhniAu5MAI7hdpUAAAgAjA/KAB8IAQAAUAKFAAUA5TAAsUA4iAArAK2AAXMAAABaOg");
	var mask_2_graphics_120 = new cjs.Graphics().p("EhemguwQAAgNIcAIQITAIQkAdIM0AYIAEAAIERAIIMsAYIARABQDgAHJQAKIL1ALIMBALIDYADIbYAVIcqAXQe+AbHwARIAAAKMAAABaDMjPBAABg");
	var mask_2_graphics_121 = new cjs.Graphics().p("EhndAu5MAI7hdnQAAgOIXAGQIQAHQnAeIM1AXIAEAAIEQAIIMrAZIARAAQDhAHJPAKIL0AMIMBAKIDXADIbYAWQQLAMMfALQe5AaH1ARIABAKMAAABaCIm8AEg");
	var mask_2_graphics_122 = new cjs.Graphics().p("EhnWAu6MAI6hdkQAAgRIRADQIJAIQuAdIMzAXIAEAAIERAIIMpAZIARAAQDjAHJMAKILzAMIMAALIDYADIbXAWIcqAXQewAaH+ARIAAAKMAAABZ+Im1AKg");
	var mask_2_graphics_123 = new cjs.Graphics().p("EhnOAu7MAI6hdfQABgVIHgBQIAAHQ2AeIMzAXIAFAAIEQAIIMnAYIAQABQDlAHJJAKILyAMIMAALIDXADIbVAWIcqAXQelAaIKARIAAAKMAAABZ5ImtASg");
	var mask_2_graphics_124 = new cjs.Graphics().p("EhnCAu9MAI5hdZQABgaH7gGQHzAGRDAeIMyAYIAEAAIEQAIIMkAYIARAAQDoAIJDAKILyAMIL+ALIDXADIbTAXIcrAXQeVAaIZAQIABAJMAAABZ1ImjAbg");
	var mask_2_graphics_125 = new cjs.Graphics().p("Ehm0Au/MAI3hdSQACgfHtgMQHkAFRRAeIMxAYIAEAAIEPAHIMhAYIARABQDrAHI+AKILwANIL8AMIDXADIbQAXIcsAXQeDAaIsAQIABAJMAAABZtImXAng");
	var mask_2_graphics_126 = new cjs.Graphics().p("EhmjAvCMAI2hdJQACgnHcgTQHSAERiAeIMvAYIAEAAIEPAIIMdAYIARAAQDvAII3AKILuANIL7AMIDWAEQLfAKPvAMIcsAYQdtAZJCAPIABAJMAAABZlImIA2g");
	var mask_2_graphics_127 = new cjs.Graphics().p("EhmQAvFMAI1hc/QADguHHgcQG+ADR1AfIMuAXIAEAAIEOAIIMZAYIAQAAQD1AIIuAKILsAOIL5AMIDWAEIbLAXIcsAXQdUAZJbAQIACAIMAAABZcIl2BFg");
	var mask_2_graphics_128 = new cjs.Graphics().p("Ehl7AvJMAI0hc1QADg2GxgmQGnACSMAgIMsAWIADAAIEOAIIMUAYIAQABQD6AHIkALQFKAGGgAHIL4AOIDVADQLJAMP9ANIctAWQc4AZJ5APIABAIMAAABZRIljBYg");
	var mask_2_graphics_129 = new cjs.Graphics().p("EhliAvNMAIxhcoQAFhAGXgxQGNAASkAgIMqAXIAEAAIENAIIMOAXIAQABQD/AIIbAKILnAPIL2ANIDUAEQK9AMQFANIcuAXQcYAYKZAPIACAHMAAABZFIlOBtg");
	var mask_2_graphics_130 = new cjs.Graphics().p("EhlHAvSMAIuhcaQAHhMF7g9QFwgBTAAhIMnAXIAFAAIEMAHIMHAYIARAAQEFAIIPALQFMAHGYAIILzAOIDUAEQKvAMQOAOIcvAXQb1AXK8AOIAEAHMAAABY4Ik3CEg");
	var mask_2_graphics_131 = new cjs.Graphics().p("EhkqAvXMAIthcLQAGhYFehKQFRgDTdAhIMmAXIAEAAIELAIIMAAXIAQABQENAIIDALILhAPILwAPIDTAFQKgAMQYAOIcwAXQbOAWLjAOIAEAHMAAABYoIkcCeg");
	var mask_2_graphics_132 = new cjs.Graphics().p("EhkKAvdMAIqhb7QAIhkE8hZQEwgFT8AiIMkAXIAEAAIEKAIIL4AXIARAAQEUAJH2AKILdARILuAQIDSAFQKPAMQjAOIcxAYQalAVMNAOIAEAFMAAABYZIj/C5g");
	var mask_2_graphics_133 = new cjs.Graphics().p("EhjoAvjMAInhbpQAKhzEZhoQEKgHUgAjIMgAXIAEAAIEKAHILvAXIARAAQEdAJHnALILaARILqARIDSAFQJ8ANQvAPIcyAXQZ4AVM7ANIAFAFMAAABYIIjgDWg");
	var mask_2_graphics_134 = new cjs.Graphics().p("EhjFAvpMAIkhbXQALiBD1h3QDmgJVCAkIMeAWIAEAAIEIAIILoAWIAQAAQElAJHZAMILWARILnASIDRAFQJqAOQ7APQN6AMO5ALQZLAUNpANIAFAEMAAABX3IjBDzg");
	var mask_2_graphics_135 = new cjs.Graphics().p("EhilAvvMAIhhbHQANiNDTiGQDEgLViAlIMcAWIAEAAIEIAHILfAWIARABQEsAJHLALILTATILkATIDQAFQJaAORGAQIc0AXMAm0AAfIAGAEMAAABXnIikEOg");
	var mask_2_graphics_136 = new cjs.Graphics().p("EhiIAv0MAIfha4QAOiZC1iTQCkgNWBAlIMZAWIAEAAIEHAIILYAWIARAAQEzAKG/ALILPATILiAUIDQAGQJKAORPAQIc2AXMAm0AAeIAHADMAAABXYIiKEog");
	var mask_2_graphics_137 = new cjs.Graphics().p("EhhuAv5MAIehaqQAPikCYifQCJgOWbAlIMWAWIAFAAIEGAIILSAWIAQAAILuAVILMAUILgAUIDPAGQI8APRYAQQNMAMPrALMAm1AAdIAHADMAAABXLIhyE+g");
	var mask_2_graphics_138 = new cjs.Graphics().p("EhhVAv+MAIbhaeQAQiuCAiqQBugQW0AmIMUAWIAEAAIEGAIILMAVIARABILpAVILKAUILdAVIDOAGQIwAPRgARQNAALP4AMMAm1AAcIAIACMAAABW/IhdFUg");
	var mask_2_graphics_139 = new cjs.Graphics().p("Ehg/AwCMAIZhaTQARi3Bpi0QBXgRXKAnIMTAWIAEAAIEFAIILGAVIARAAILlAWILIAUILcAWIDNAGQIkAQRoAQQM1AMQDAMQWbAQQbALIAIABMAAABW0IhJFng");
	var mask_2_graphics_140 = new cjs.Graphics().p("EhgsAwFMAIYhaIQARi/BVi9QBDgSXdAoIMSAVIAEAAIEEAIILCAVIARABILhAVILGAVILaAWIDNAHQIaAPRvARQMqAMQOAMQWCAQQ1AKIAIABMAAABWrIg4F2g");
	var mask_2_graphics_141 = new cjs.Graphics().p("EhgcAwJMAIXhaAQASjGBEjEQAxgTXuAoIMQAVIAEAAIEFAIIK9AVIARAAILeAWILFAWILYAWIDMAHQISAPR0ARQMiAMQXAMQVsAQRLAKIAJABMAAABWiIgqGFg");
	var mask_2_graphics_142 = new cjs.Graphics().p("EhgOAwLMAIWhZ5QATjLA1jKQAigUX8AoIMPAVIAEAAIEEAIIK6AVIARAAILcAWILDAWILXAXIDMAHQIKAQR5ARQMbALQfAMQVZAQRdAJIAKABMAAABWbIgdGRg");
	var mask_2_graphics_143 = new cjs.Graphics().p("EhgCAwNMAIUhZzQAUjQApjPQAWgVYHAoIMPAWIAEAAIEDAHIK4AVIARABILZAWILCAWILWAXIDLAHQIFAQR9ARQMUAMQlAMQVLAPRtAKIAJAAMAAABWWIgSGag");
	var mask_2_graphics_144 = new cjs.Graphics().p("Ehf5AwPMAIUhZvQATjTAgjUQANgVYQApIMOAVIAEAAIEDAIIK1AUIARABILZAWILAAWILVAYIDMAHQH/AQSAARQMQAMQqAMQU/APR5AJIAJAAMAAABWSIgKGig");
	var mask_2_graphics_145 = new cjs.Graphics().p("EhfzAwQMAIUhZrQATjXAajWQAFgVYYAoIMNAWIAEAAIEDAHIK0AVIARAAILWAXILAAWILUAYIDMAHQH8AQSCARQMNAMQtAMQU3APSBAJIAKAAMAAABWOIgFGog");
	var mask_2_graphics_146 = new cjs.Graphics().p("EhfvAwRMAIThZpIApmwQABgWYcApIMNAVIADAAIEDAIIK0AUIARABILVAWIK/AXILVAXIDMAHQH5ARSEARQMLAMQwAMQUxAPSGAJIAKAAMgABBc3g");
	var mask_2_graphics_147 = new cjs.Graphics().p("EhfuAwRMAI7hgZQAAgWYdApIMMAVIAEAAIEDAIQJ/ASMbAZIK/AXILUAXIDLAHUANOAAcApqAAeQU2APSMAJMAAABc3g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(119).to({graphics:mask_2_graphics_119,x:1977.925,y:-34.6017}).wait(1).to({graphics:mask_2_graphics_120,x:1973.975,y:-34.5524}).wait(1).to({graphics:mask_2_graphics_121,x:1962.125,y:-34.4628}).wait(1).to({graphics:mask_2_graphics_122,x:1942.325,y:-34.3542}).wait(1).to({graphics:mask_2_graphics_123,x:1914.65,y:-34.275}).wait(1).to({graphics:mask_2_graphics_124,x:1879.025,y:-34.175}).wait(1).to({graphics:mask_2_graphics_125,x:1835.525,y:-34.05}).wait(1).to({graphics:mask_2_graphics_126,x:1784.075,y:-33.9}).wait(1).to({graphics:mask_2_graphics_127,x:1724.75,y:-33.775}).wait(1).to({graphics:mask_2_graphics_128,x:1657.5,y:-33.6}).wait(1).to({graphics:mask_2_graphics_129,x:1582.325,y:-33.375}).wait(1).to({graphics:mask_2_graphics_130,x:1499.25,y:-33.1783}).wait(1).to({graphics:mask_2_graphics_131,x:1408.25,y:-32.9375}).wait(1).to({graphics:mask_2_graphics_132,x:1309.325,y:-32.7071}).wait(1).to({graphics:mask_2_graphics_133,x:1202.525,y:-32.4333}).wait(1).to({graphics:mask_2_graphics_134,x:1095.725,y:-32.215}).wait(1).to({graphics:mask_2_graphics_135,x:996.825,y:-32.001}).wait(1).to({graphics:mask_2_graphics_136,x:905.825,y:-31.7828}).wait(1).to({graphics:mask_2_graphics_137,x:822.75,y:-31.6153}).wait(1).to({graphics:mask_2_graphics_138,x:747.575,y:-31.4349}).wait(1).to({graphics:mask_2_graphics_139,x:680.325,y:-31.283}).wait(1).to({graphics:mask_2_graphics_140,x:620.975,y:-31.1817}).wait(1).to({graphics:mask_2_graphics_141,x:569.55,y:-31.0559}).wait(1).to({graphics:mask_2_graphics_142,x:526.025,y:-30.9583}).wait(1).to({graphics:mask_2_graphics_143,x:490.425,y:-30.8835}).wait(1).to({graphics:mask_2_graphics_144,x:462.725,y:-30.8448}).wait(1).to({graphics:mask_2_graphics_145,x:442.95,y:-30.7978}).wait(1).to({graphics:mask_2_graphics_146,x:431.1,y:-30.7841}).wait(1).to({graphics:mask_2_graphics_147,x:427.125,y:-30.7591}).wait(37).to({graphics:null,x:0,y:0}).wait(93));

	// txt_twoYears
	this.instance_12 = new lib.txt_twoYears();
	this.instance_12.setTransform(251.7,32.45,1,1,0,0,0,128.1,46);
	this.instance_12._off = true;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(119).to({_off:false},0).wait(55).to({y:52.45,alpha:0},9,cjs.Ease.quadIn).to({_off:true},1).wait(93));

	// txt_theAssets
	this.instance_13 = new lib.txt_theAssets();
	this.instance_13.setTransform(147.6,104.1);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(47).to({_off:false},0).to({y:124.1,alpha:1},7,cjs.Ease.quadOut).wait(28).to({y:148.1,alpha:0},7,cjs.Ease.quadIn).to({_off:true},1).wait(187));

	// Layer_94
	this.instance_14 = new lib.cartridge_mc();
	this.instance_14.setTransform(-778.4,-70.65);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(40).to({_off:false},0).to({x:-319.4},14,cjs.Ease.quadInOut).wait(28).to({alpha:0},7).to({_off:true},1).wait(187));

	// txt_isYour
	this.instance_15 = new lib.txt_lets();
	this.instance_15.setTransform(56.3,82.95);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({y:100.95,alpha:1},8,cjs.Ease.quadOut).wait(32).to({y:116.95,alpha:0},6,cjs.Ease.quadIn).to({_off:true},1).wait(230));

	// background_color
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("EhKBAFKQhwAAAAgJIAAqBQAAgJBwAAMCUDAAAQBwAAAAAJIAAKBQAAAJhwAAg");
	this.shape_17.setTransform(485,33);

	this.timeline.addTween(cjs.Tween.get(this.shape_17).wait(277));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-567.2,-305.5,2066.1000000000004,601.2);
// library properties:
lib.properties = {
	id: 'D13842C17BB34EAD8425AF1A57942765',
	width: 970,
	height: 66,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"cartridges_01.jpg", id:"cartridges_01"},
		{src:"ecoTank_logo.png", id:"ecoTank_logo"},
		{src:"paintColors.jpg", id:"paintColors"},
		{src:"printer.jpg", id:"printer"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D13842C17BB34EAD8425AF1A57942765'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;