(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Epson_Logo = function() {
	this.initialize(img.Epson_Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,51);


(lib.moneySign = function() {
	this.initialize(img.moneySign);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,218,358);


(lib.printerFullFrame = function() {
	this.initialize(img.printerFullFrame);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,415,372);


(lib.shirtStack = function() {
	this.initialize(img.shirtStack);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,164,168);


(lib.timer = function() {
	this.initialize(img.timer);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,203,203);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_sureColor_f3070_endFrame = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ApHBRQgJgEgGgIQgFgIgCgMQgDgNAAgQQAAgPADgMQACgMAGgIQAGgIAJgEQAJgFAOAAQAOAAAKAEQAJAEAGAIQAFAJACAMQADALAAAQQAAAQgDAMQgCANgGAIQgGAIgJAEQgKAEgNAAIgDAAQgMAAgJgEgAo4gTQgEADgBAGQgCAGgBAHIAAAjQABAIACAGQABAFAEAEQADADAGAAQAKAAADgKQAEgKAAgYQAAgWgEgKQgDgKgKAAQgGAAgDADgArnBRQgJgEgGgIQgFgIgCgMQgDgNAAgQQAAgPADgMQACgMAGgIQAGgIAJgEQAJgFAOAAQAOAAAKAEQAJAEAGAIQAFAJACAMQADALAAAQQAAAQgDAMQgCANgGAIQgGAIgJAEQgKAEgNAAIgDAAQgMAAgJgEgArYgTQgEADgBAGQgCAGgBAHIAAAjQABAIACAGQABAFAEAEQADADAGAAQAKAAADgKQAEgKAAgYQAAgWgEgKQgDgKgKAAQgGAAgDADgAR6BPQgKgGgFgJQgEgKgBgLIgBgYQAAgMABgLQACgLAFgJQAGgJAJgFQAKgGAQAAQAOAAAJAFQAIAEAGAIQAFAJABALQACALAAAOIAAAHIg/AAIABAVIADAJQACAEADACQADADAEAAQAIAAAEgGQADgGACgLIAcAAQgBAVgKALQgLAMgWAAQgSAAgJgGgASNgUQgDACgCAEIgDAIIgBAIIAAAEIAhAAIgBgLIgCgJQgCgEgDgCQgDgCgFAAQgFAAgDACgAIqBPQgJgFgGgLQgFgLgCgQQgCgQAAgVQAAgUADgQQACgQAHgKQAGgLALgFQAKgFAQAAQAbAAAMANQAMAOAAAZIgfAAIgBgKIgEgJQgCgEgEgCQgDgDgFAAQgMAAgFAOQgGANAAAfIABAZQABAMADAJQACAIAEAFQAFAEAHAAIAHgCQADgBADgDIAFgIQADgFAAgHIAAgRIgWAAIAAgXIA1AAIAABXIgYAAIAAgPIgBAAQgGAKgIAEQgIAEgMAAQgPAAgKgGgACaBRQgKgEgGgJQgGgKgCgPQgDgPAAgWIACgfQABgQAFgMQAFgMAKgHQAKgIATAAQAOAAAKAFQAKAEAGAJQAGAKACAPQACAPAAAWIgBAfQgBAQgFAMQgFAMgKAHQgKAHgSAAQgPAAgKgEgACqg3QgEACgCAHQgCAGgBAKIAABFQABAJACAGQACAGAEACQADACAGAAQAFAAADgDQAEgCACgHQACgGABgLIAAhEQgBgKgCgFQgCgGgEgCQgDgCgFAAQgGAAgDADgAg8BRQgKgEgGgJQgGgKgCgPQgDgPAAgWIACgfQABgQAFgMQAFgMAKgHQAKgIATAAQAOAAAKAFQAKAEAFAJQAGAKACAPQACAPAAAWIgBAfQgBAQgFAMQgFAMgJAHQgKAHgSAAQgPAAgKgEgAgsg3QgEACgCAHQgCAGgBAKIAABFQABAJACAGQACAGAEACQADACAGAAQAFAAADgDQAEgCACgHQACgGABgLIAAhEQgBgKgCgFQgCgGgEgCQgDgCgFAAQgGAAgDADgAi2BIQgMgNAAgYIAAAAIAgAAQAAAOAEAHQADAIALAAQAGAAAEgCQADgCACgEQACgDABgFIAAgVQgBgFgDgEQgCgEgEgCQgEgCgHAAIgLAAIAAgVIALAAQAFAAAEgCQADgCACgEQADgDABgFIABgKQAAgLgEgFQgEgFgIAAQgGAAgDACQgDACgCADIgCAJIgBAKIgeAAQAAgYAMgMQAMgMAXAAQAXAAAMALQAMAKAAAVQAAAPgGAJQgHAKgLACIAAABQAPABAHAKQAHALAAAPQAAAIgCAJQgDAJgGAHQgGAHgKAEQgLAFgQAAQgYAAgMgNgAtdBPQgLgGgGgLQgGgMgBgPQgCgQAAgTQAAgRACgQQABgQAGgLQAGgMALgGQALgGATAAQARAAALAGQAKAFAFAJQAFAJABAKIACATIgiAAQAAgRgEgJQgEgIgLAAQgHAAgEAEQgEADgCAHQgCAIgBAMIgBAcQAAATABAMQABALADAGQADAHAEACQAEACAFAAIAIgBQAEgCADgEQADgFABgIQACgIAAgOIAhAAQAAAOgCAMQgCAMgGAJQgGAJgKAFQgKAFgQAAQgTAAgLgGgAvMBPQgJgGgFgJQgFgKgBgLIgBgYQAAgMACgLQACgLAFgJQAFgJAKgFQAJgGARAAQANAAAJAFQAJAEAFAIQAFAJACALQACALAAAOIAAAHIg/AAIABAVIACAJQACAEADACQADADAFAAQAIAAADgGQAEgGABgLIAdAAQgBAVgLALQgKAMgXAAQgRAAgKgGgAu5gUQgDACgCAEIgCAIIgBAIIAAAEIAgAAIgBgLIgCgJQgCgEgDgCQgDgCgFAAQgFAAgDACgAyOBNQgJgIAAgTIAAhbIAgAAIAABVQAAAKADADQADAEAIAAQAQAAAAgUIAAhSIAgAAIAAB7IgeAAIAAgOIgBAAQgFAJgIAEQgIAEgKAAQgPAAgIgIgA0FBJQgMgNAAgWIAAgHIAhAAIAAAFIABAKQABAFADADQACADAFACQAEACAGAAQAIAAAGgFQAGgFAAgKQAAgGgBgEQgCgEgDgDQgEgDgGgDIgNgFQgLgEgIgEQgJgFgFgEQgFgGgDgIQgCgIAAgKQAAgYANgMQAOgMAXAAQALAAAKACQAJADAHAFQAHAFADAJQAEAIAAAMIAAAFIgfAAQAAgMgFgHQgEgGgJAAQgGAAgEACQgDABgDADQgCADAAADIgBAHQAAAIADAFQADAFALAFIAZALQAKAEAGADQAGAFADAFQAEAFABAGQACAHAAAHQAAAagPAMQgQAMgaAAQgdAAgMgMgAQ9BSQgGgCgDgDQgDgEgBgGIgBgQIAAhGIgQAAIAAgWIAQAAIAAgjIAfAAIAAAjIATAAIAAAWIgTAAIAABCQAAAHADAEQACADAHAAIADgBIAEAAIAAAWIgVABIgPgBgATRBSIAAh7IAeAAIAAARIABAAQAFgJAGgFQAHgGAKAAIADAAIADABIAAAeIgKAAIgIABQgEABgEADQgDACgCAEQgCAEAAAGIAABKgAP1BSIAAhUQAAgKgDgEQgDgDgHAAQgRAAAAATIAABSIggAAIAAh7IAfAAIAAAPIAAAAQAFgJAIgEQAIgFALAAQAPAAAIAJQAIAIAAASIAABbgAOEBSIAAh7IAgAAIAAB7gAM5BSIAAh7IAeAAIAAARIABAAQAFgJAGgFQAHgGAKAAIADAAIADABIAAAeIgKAAIgIABQgEABgEADQgDACgCAEQgCAEAAAGIAABKgALFBSIAAijIA6AAQANAAAIAEQAJAFAFAGQAGAHACAJQACAJAAAJQAAANgEAJQgDAKgHAFQgHAGgKADQgJADgMAAIgSAAIAABBgALmgHIAPAAQAKAAAGgGQAGgGAAgMQAAgNgFgGQgFgHgNAAIgOAAgAHDBSIAAiIIgjAAIAAgbIBoAAIAAAbIgjAAIAACIgAEoBSIAAijIA3AAQARAAAKAGQALAFAGALQAGAKACAPQACAPAAASQAAAUgDAQQgCAQgHALQgGAKgLAFQgLAFgQAAgAFKA6IAOAAQAJAAAFgDQAGgDADgHQADgHABgLIAAg0QgBgKgDgHQgDgHgFgEQgGgEgJAAIgOAAgAAnBSQABgOAEgRQAEgQAGgRQAGgQAJgQQAIgSAMgQIhEAAIAAgcIBkAAIAAAZQgKAOgIAQQgIARgGAQQgGARgEASQgEASgCARgAkiBSIAAijIBcAAIAAAbIg7AAIAAAnIA3AAIAAAaIg3AAIAABHgAnwBSIAAh7IAeAAIAAARIABAAQAFgJAGgFQAHgGAKAAIADAAIADABIAAAeIgKAAIgIABQgEABgEADQgDACgCAEQgCAEAAAGIAABKgAqPBSIAAijIAgAAIAACjgAwmBSIAAh7IAeAAIAAARIABAAQAFgJAGgFQAHgGAKAAIADAAIADABIAAAeIgKAAIgIABQgEABgEADQgDACgCAEQgCAEAAAGIAABKgAmNAEQgHgDgGgEQgFgGgDgHQgEgIAAgIQAAgIAEgIQADgHAFgGQAGgFAHgEQAIgDAIAAQAJAAAHADQAIAEAFAFQAGAGADAHQADAIAAAIQAAAIgDAIQgDAHgGAGQgFAEgIADQgHADgJAAQgIAAgIgDgAmIg7QgFACgEAEQgEAEgCAGQgCAFAAAGQAAAGACAFQACAGAEAEQAEAEAFACQAFACAGAAQAGAAAGgCQAFgCAEgEQADgEADgGQACgFAAgGQAAgGgCgFQgDgGgDgEQgEgEgFgCQgGgCgGAAQgGAAgFACgAl1gKIgKgSIgEAAIAAASIgKAAIAAgsIARAAQAJAAAEAEQAEADAAAHQAAAFgDADQgDADgFABIALASgAmDgjIAHAAIAGgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAgBAAgBIgBgDIgCgBIgDgBIgJAAgAOEg4IAAgbIAgAAIAAAbg");
	this.shape.setTransform(-3.425,-143.3972);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f3070_endFrame, new cjs.Rectangle(-133.2,-151.9,259.6,17), null);


(lib.txt_sureColor_f3070 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ApMBRQgKgEgGgIQgFgIgCgMQgCgNgBgQQABgPACgMQADgMAFgIQAGgIAKgEQAJgFANAAQAOAAAKAEQAJAEAGAIQAFAJADAMQACALAAAQQAAAQgCAMQgDANgGAIQgFAIgKAEQgJAEgOAAIgDAAQgMAAgIgEgAo+gTQgEADgBAGQgCAGAAAHIAAAjQAAAIACAGQABAFAEAEQADADAGAAQAKAAAEgKQADgKAAgYQAAgWgDgKQgEgKgKAAQgGAAgDADgArtBRQgJgEgGgIQgFgIgCgMQgCgNgBgQQABgPACgMQACgMAGgIQAGgIAJgEQAKgFAOAAQAOAAAJAEQAJAEAGAIQAGAJACAMQACALAAAQQAAAQgCAMQgDANgGAIQgGAIgJAEQgJAEgNAAIgEAAQgMAAgJgEgAregTQgDADgCAGQgCAGAAAHIAAAjQAAAIACAGQACAFADAEQADADAHAAQAJAAADgKQAEgKAAgYQAAgWgEgKQgDgKgJAAQgHAAgDADgAR/BPQgJgGgFgJQgEgKgCgLIAAgYQgBgMACgLQACgLAFgJQAGgJAJgFQAKgGAQAAQANAAAKAFQAIAEAFAIQAGAJABALQACALAAAOIAAAHIg/AAIABAVIADAJQACAEACACQAEADAEAAQAIAAADgGQAEgGACgLIAcAAQgBAVgKALQgLAMgXAAQgRAAgKgGgASSgUQgCACgCAEIgDAIIgBAIIAAAEIAhAAIgBgLIgCgJQgCgEgEgCQgCgCgGAAQgEAAgEACgAIwBPQgJgFgGgLQgFgLgDgQQgBgQAAgVQAAgUACgQQADgQAGgKQAHgLALgFQAKgFAQAAQAbAAAMANQAMAOAAAZIggAAIAAgKIgEgJQgCgEgEgCQgEgDgEAAQgNAAgFAOQgFANAAAfIABAZQABAMACAJQADAIAEAFQAFAEAHAAIAHgCQADgBADgDIAFgIQACgFAAgHIAAgRIgVAAIAAgXIA1AAIAABXIgZAAIAAgPIAAAAQgGAKgJAEQgHAEgNAAQgOAAgKgGgACgBRQgLgEgFgJQgGgKgDgPQgCgPAAgWIABgfQACgQAFgMQAEgMALgHQAKgIATAAQAOAAAKAFQAKAEAFAJQAGAKADAPQACAPAAAWIgBAfQgBAQgFAMQgFAMgKAHQgLAHgRAAQgPAAgKgEgACwg3QgEACgCAHQgCAGgBAKIAABFQABAJACAGQACAGAEACQADACAGAAQAFAAADgDQADgCACgHQACgGACgLIAAhEQgCgKgCgFQgCgGgDgCQgEgCgEAAQgHAAgCADgAg3BRQgKgEgFgJQgGgKgDgPQgCgPAAgWIABgfQACgQAEgMQAFgMALgHQAKgIATAAQAOAAAKAFQAJAEAFAJQAHAKACAPQACAPAAAWIgBAfQgBAQgFAMQgFAMgKAHQgKAHgRAAQgPAAgLgEgAgmg3QgEACgCAHQgCAGgBAKIAABFQABAJACAGQACAGAEACQADACAGAAQAFAAADgDQAEgCABgHQADgGABgLIAAhEQgBgKgDgFQgBgGgEgCQgEgCgEAAQgHAAgCADgAiwBIQgMgNAAgYIAAAAIAgAAQAAAOADAHQAEAIALAAQAGAAAEgCQADgCACgEQACgDABgFIAAgVQgBgFgDgEQgCgEgEgCQgFgCgGAAIgMAAIAAgVIALAAQAGAAADgCQAEgCACgEQACgDABgFIACgKQgBgLgEgFQgEgFgHAAQgGAAgDACQgEACgCADIgCAJIAAAKIgeAAQAAgYAMgMQAMgMAXAAQAWAAANALQAMAKAAAVQAAAPgHAJQgGAKgMACIAAABQAQABAHAKQAHALAAAPQgBAIgCAJQgCAJgGAHQgGAHgKAEQgLAFgQAAQgYAAgMgNgAtiBPQgMgGgGgLQgFgMgCgPQgCgQAAgTQAAgRACgQQACgQAFgLQAGgMAMgGQAKgGATAAQARAAALAGQAKAFAFAJQAFAJACAKIABATIgiAAQAAgRgDgJQgFgIgLAAQgGAAgEAEQgFADgCAHQgCAIgBAMIgBAcQAAATACAMQABALACAGQADAHAEACQAEACAFAAIAJgBQADgCADgEQADgFABgIQACgIAAgOIAhAAQAAAOgCAMQgCAMgFAJQgHAJgKAFQgKAFgQAAQgTAAgKgGgAvRBPQgKgGgFgJQgFgKgBgLIgBgYQABgMABgLQACgLAFgJQAGgJAJgFQAKgGAQAAQAOAAAIAFQAJAEAGAIQAEAJACALQACALAAAOIAAAHIg/AAIABAVIACAJQACAEAEACQADADAEAAQAIAAAEgGQADgGABgLIAdAAQgBAVgLALQgKAMgWAAQgSAAgJgGgAu+gUQgEACgCAEIgCAIIgBAIIAAAEIAgAAIgBgLIgCgJQgBgEgEgCQgDgCgEAAQgGAAgCACgAyUBNQgIgIgBgTIAAhbIAhAAIAABVQAAAKADADQACAEAIAAQARAAAAgUIAAhSIAfAAIAAB7IgeAAIAAgOIgBAAQgEAJgIAEQgIAEgLAAQgPAAgIgIgA0KBJQgNgNAAgWIAAgHIAhAAIAAAFIABAKQABAFADADQADADAEACQAEACAHAAQAHAAAGgFQAGgFABgKQgBgGgBgEQgBgEgEgDQgEgDgGgDIgNgFQgLgEgIgEQgJgFgEgEQgGgGgDgIQgCgIAAgKQAAgYANgMQAOgMAXAAQALAAAKACQAJADAHAFQAHAFAEAJQADAIAAAMIAAAFIgfAAQAAgMgFgHQgDgGgKAAQgFAAgFACQgDABgCADQgCADgBADIgBAHQAAAIADAFQADAFALAFIAZALQAKAEAGADQAGAFAEAFQADAFABAGQACAHAAAHQAAAagPAMQgPAMgbAAQgcAAgMgMgARDBSQgGgCgDgDQgDgEgCgGIAAgQIAAhGIgRAAIAAgWIARAAIAAgjIAfAAIAAAjIASAAIAAAWIgSAAIAABCQAAAHADAEQABADAIAAIADgBIADAAIAAAWIgUABIgPgBgATXBSIAAh7IAeAAIAAARIAAAAQAGgJAGgFQAHgGAKAAIADAAIACABIAAAeIgJAAIgJABQgDABgEADQgDACgCAEQgCAEgBAGIAABKgAP7BSIAAhUQAAgKgDgEQgDgDgIAAQgQAAAAATIAABSIggAAIAAh7IAeAAIAAAPIABAAQAFgJAIgEQAIgFALAAQAPAAAHAJQAJAIAAASIAABbgAOKBSIAAh7IAfAAIAAB7gAM/BSIAAh7IAeAAIAAARIAAAAQAFgJAHgFQAHgGAKAAIADAAIADABIAAAeIgKAAIgIABQgFABgDADQgEACgCAEQgCAEAAAGIAABKgALLBSIAAijIA6AAQAMAAAJAEQAJAFAFAGQAGAHACAJQACAJAAAJQAAANgEAJQgEAKgGAFQgHAGgKADQgJADgMAAIgSAAIAABBgALsgHIAPAAQAJAAAHgGQAGgGAAgMQAAgNgFgGQgFgHgNAAIgOAAgAHJBSIAAiIIgkAAIAAgbIBpAAIAAAbIgjAAIAACIgAEuBSIAAijIA3AAQARAAAKAGQALAFAGALQAGAKACAPQACAPAAASQgBAUgCAQQgCAQgHALQgHAKgKAFQgLAFgQAAgAFQA6IAOAAQAIAAAGgDQAFgDAEgHQADgHAAgLIAAg0QgBgKgCgHQgDgHgFgEQgHgEgJAAIgNAAgAAsBSQACgOAEgRQAEgQAGgRQAFgQAKgQQAIgSAMgQIhFAAIAAgcIBlAAIAAAZQgLAOgHAQQgIARgGAQQgGARgEASQgEASgCARgAkcBSIAAijIBcAAIAAAbIg8AAIAAAnIA4AAIAAAaIg4AAIAABHgAn2BSIAAh7IAfAAIAAARIAAAAQAFgJAGgFQAIgGAJAAIADAAIADABIAAAeIgJAAIgJABQgEABgDADQgEACgCAEQgCAEAAAGIAABKgAqVBSIAAijIAgAAIAACjgAwsBSIAAh7IAfAAIAAARIAAAAQAFgJAGgFQAHgGAKAAIADAAIADABIAAAeIgJAAIgJABQgEABgDADQgEACgCAEQgCAEAAAGIAABKgAmQAOQgIgDgHgGQgGgFgDgIQgEgIABgJQgBgKAEgIQADgIAGgGQAHgGAIgEQAIgDAJAAQAJAAAIADQAIAEAGAGQAGAGAEAIQAEAIAAAKQAAAJgEAIQgEAIgGAFQgGAGgIADQgIAEgJAAQgJAAgIgEgAmMg3IgKAHQgDAFgDAFQgCAGAAAHQAAAGACAGQADAFADAFQAFADAFADQAGACAHAAQAHAAAFgCQAGgDAEgDQAFgFACgFQACgGAAgGQAAgHgCgGQgCgFgFgFQgEgEgGgDQgFgCgHAAQgHAAgGACgAl3gCIgLgTIgEAAIAAATIgKAAIAAgvIASAAQAJAAAFADQAEAEABAIQgBAGgDADQgDADgGABIANATgAmGgdIAIAAIAFgBQADgBAAgEIAAgDIgDgCIgDgBIgKAAgAOKg4IAAgbIAfAAIAAAbg");
	this.shape.setTransform(-4.7,-152.8972);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f3070, new cjs.Rectangle(-188.7,-168.7,369,159.39999999999998), null);


(lib.txt_purposeBuilt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AL+DJIAAgUIAIAAQAHAAAEgEQADgEAAgGIgehsIAdAAIAQBLIAOhLIAcAAIgaBlIgHAVQgDAJgFAEQgEAFgGABQgHABgJAAgAnZDJIAAiOIAbAAIAAAMIAAAAQAFgIAGgDQAFgEAJAAQARAAAIAOQAIANAAAeQAAAegIANQgIANgRAAQgIAAgGgDQgFgDgFgGIAAAsgAm6BWQgDAJAAASQAAASADAIQACAJAKAAQAJAAACgJQADgIAAgSQAAgSgDgJQgCgIgJAAQgKAAgCAIgAj5CmQgIgDgFgIQgFgHgCgKQgCgLAAgOQAAgOADgKQACgLAFgHQAFgHAIgEQAIgEAMAAQAMAAAIAEQAJADAEAHQAFAIACAKQACALAAAOQAAAOgCAKQgCALgFAHQgFAHgIAEQgIADgMAAIgDAAQgLAAgHgDgAjsBOQgDADgCAFIgCAMIAAAeIACAMQACAFADADQADADAFAAQAIAAADgJQAEgJAAgUQAAgUgEgJQgDgJgIAAQgFAAgDADgAH3CmQgGgDgEgIIgBAAIAAAMIgaAAIAAiPIAcAAIAAAtQAEgGAGgDQAFgEAIAAQARAAAIAOQAIANAAAeQAAAegIANQgIANgRAAQgIAAgGgDgAHwBWQgCAJAAASQAAASACAIQADAJAJAAQAJAAADgJQADgIAAgSQAAgSgDgJQgDgIgJAAQgJAAgDAIgAF9CmQgFgCgDgEQgDgFgCgFIgBgLQAAgIABgFQACgGADgEQAEgEAFgCIAMgFIAQgEQAGgCACgCQADgDAAgGQAAgGgDgDQgDgEgHAAQgHAAgDAEQgDAEAAAGIAAADIgZAAIAAgCQAAgKADgGQADgGAFgEQAFgEAHgCQAHgCAIAAQAMAAAIADQAIACAEAFQAEAEACAGQABAGAAAHIABBFIACAJIgaAAIgCgGIgBgFIgBAAQgFAIgGACQgGADgKAAQgHAAgFgDgAGfB0IgGACQgJACgDAEQgEAFAAAHQAAAGADAEQACAFAGAAIAFgBIAGgDIAEgFQACgDAAgFIAAgVgADGCkQgJgFgEgIQgEgIgBgLIgBgUQAAgLACgKQABgKAFgIQAEgHAJgFQAIgFAOAAQAMAAAIAEQAIAEAEAHQAEAHACAKQACALAAAMIAAAGIg3AAIABASIACAIQACAEACACQADACAEAAQAHAAADgFQADgFABgKIAZAAQgBASgJAKQgJAKgUAAQgPAAgIgFgADWBNQgCACgCADIgCAHIgBAMIAcAAIgBgLIgCgIIgEgFQgDgCgEAAQgEAAgDACgAg+CmQgFgCgDgEQgDgFgBgFIgCgLQAAgIACgFQACgGADgEQADgEAFgCIANgFIAPgEQAGgCADgCQACgDAAgGQAAgGgDgDQgDgEgHAAQgGAAgDAEQgDAEAAAGIAAADIgZAAIAAgCQAAgKADgGQADgGAFgEQAFgEAHgCQAHgCAIAAQAMAAAIADQAHACAEAFQAEAEABAGQACAGAAAHIAABFIADAJIgZAAIgDgGIgBgFIAAAAQgFAIgGACQgHADgKAAQgHAAgFgDgAgcB0IgGACQgIACgEAEQgDAFAAAHQAAAGACAEQADAFAFAAIAGgBIAFgDIAFgFQABgDAAgFIAAgVgAomCkQgJgFgEgIQgEgIgBgLIgBgUQAAgLACgKQABgKAFgIQAEgHAJgFQAIgFAOAAQAMAAAIAEQAIAEAEAHQAEAHACAKQACALAAAMIAAAGIg3AAIABASIACAIQACAEACACQADACAEAAQAHAAADgFQADgFABgKIAZAAQgBASgJAKQgJAKgUAAQgPAAgIgFgAoWBNQgCACgCADIgCAHIgBAMIAcAAIgBgLIgCgIIgEgFQgDgCgEAAQgEAAgDACgAp9CmQgIgCgFgHQgFgGgDgLQgDgLAAgQQAAgRAEgLQADgKAGgHQAFgGAIgDQAIgDAKAAQATAAAKAMQAKALAAATIgbAAIAAgIIgCgHQgBgDgDgCQgCgCgEAAQgFAAgDADQgEACgBAEIgCAMIAAAhIACAMQABAFADACQADACAFAAQAHAAADgGQADgGAAgNIAbAAQAAAVgKALQgJALgWAAQgLAAgHgDgAs6CkQgIgFgEgIQgEgIgBgLIgBgUQAAgLABgKQACgKAEgIQAFgHAIgFQAJgFAOAAQAMAAAHAEQAIAEAFAHQAEAHACAKQABALAAAMIAAAGIg2AAIAAASIADAIQABAEADACQACACAEAAQAHAAADgFQAEgFABgKIAZAAQgBASgJAKQgKAKgTAAQgPAAgJgFgAspBNQgDACgBADIgDAHIAAAMIAcAAIgBgLIgCgIIgEgFQgDgCgEAAQgEAAgDACgALWCmQgFgBgCgDQgDgDgBgGIgBgNIAAg+IgOAAIAAgTIAOAAIAAgfIAcAAIAAAfIAQAAIAAATIgQAAIAAA6QAAAHABACQACADAGAAIAHAAIAAATIgSAAIgOgBgAljCmQgFgBgCgDQgDgDgBgGIgBgNIAAg+IgOAAIAAgTIAOAAIAAgfIAcAAIAAAfIAQAAIAAATIgQAAIAAA6QAAAHABACQACADAGAAIAHAAIAAATIgSAAIgOgBgAKVCnIAAhsIAcAAIAABsgAJmCnIAAiPIAcAAIAACPgAI2CnIAAhsIAcAAIAABsgAFECnIAAhsIAcAAIAABsgAEUCnIAAiPIAcAAIAACPgAB1CnIAAhsIAbAAIAAAPIAAAAQAEgIAGgFQAGgFAJAAIADAAIACABIAAAaIgJAAIgHABQgDABgDACQgDACgCAEQgCAEAAAFIAABBgAAXCnIAAiPIAcAAIAACPgAh2CnIAAhKQAAgJgCgDQgDgDgGAAQgPAAAAARIAABIIgcAAIAAhsIAbAAIAAANIAAAAQAFgIAHgEQAHgEAJAAQANAAAHAIQAHAHAAAQIAABQgAk6CnIAAhsIAcAAIAABsgAq3CnIgQgjIgQAjIgdAAIAdg4Igcg0IAdAAIAPAhIAPghIAdAAIgcA0IAdA4gAKVAuIAAgYIAcAAIAAAYgAI2AuIAAgYIAcAAIAAAYgAFEAuIAAgYIAcAAIAAAYgAk6AuIAAgYIAcAAIAAAYgAmagUIAAiOIAbAAIAAALIAAAAQAFgIAGgDQAFgDAJAAQARAAAIANQAIANAAAeQAAAegIANQgIANgRAAQgIAAgGgCQgFgDgFgHIAAAtgAl7iHQgDAJAAARQAAASADAJQACAJAKAAQAJAAACgJQADgJAAgSQAAgRgDgJQgCgJgJAAQgKAAgCAJgAIDg4QgJgDgEgHQgFgHgCgLQgCgLAAgOQAAgNACgLQACgLAFgHQAFgHAIgDQAIgEAMAAQANAAAIADQAIAEAFAHQAFAHACALQACAKAAAOQAAAOgDALQgCALgFAHQgFAHgIADQgIADgMAAIgDAAQgKAAgHgDgAIPiQQgDADgBAFIgCAMIAAAfIACAMQABAFADACQADADAFAAQAJAAADgJQADgIAAgVQAAgUgDgJQgDgIgJAAQgFAAgDACgAkkg4QgIgDgFgHQgFgHgCgLQgCgLAAgOQAAgNADgLQACgLAFgHQAFgHAIgDQAIgEAMAAQAMAAAIADQAJAEAEAHQAFAHACALQACAKAAAOQAAAOgCALQgCALgFAHQgFAHgIADQgIADgMAAIgDAAQgLAAgHgDgAkXiQQgDADgCAFIgCAMIAAAfIACAMQACAFADACQADADAFAAQAIAAADgJQAEgIAAgVQAAgUgEgJQgDgIgIAAQgFAAgDACgACRg7QgIgHAAgRIAAhPIAcAAIAABKQAAAIADAEQADADAGAAQAOAAAAgSIAAhHIAcAAIAABrIgaAAIAAgMIgBAAQgEAIgHADQgHADgJAAQgNAAgHgGgABLg4QgGgDgEgHIgBAAIAAALIgaAAIAAiPIAcAAIAAAuQAEgHAGgDQAFgDAIAAQARAAAIANQAIANAAAeQAAAegIANQgIANgRAAQgIAAgGgDgABEiHQgCAJAAARQAAASACAJQADAJAJAAQAJAAADgJQADgJAAgSQAAgRgDgJQgDgJgJAAQgJAAgDAJgAhwg6QgJgFgEgIQgEgIgBgKIgBgVQAAgKACgKQABgKAFgIQAEgIAJgFQAIgEAOAAQAMAAAIAEQAIAEAEAHQAEAHACAKQACAKAAAMIAAAHIg3AAIABASIACAIQACADACACQADACAEAAQAHAAADgFQADgFABgKIAZAAQgBATgJAKQgJAJgUAAQgPAAgIgFgAhgiQQgCABgCAEIgCAGIgBAMIAcAAIgBgLIgCgIIgEgFQgDgBgEAAQgEAAgDACgAjHg3QgIgCgEgEQgFgFgBgGQgCgGAAgIIAAgEIAZAAIAAAEQAAAHADAEQAEAEAHAAQAGAAAEgDQAEgDAAgHQAAgFgDgCQgDgDgEgCIgTgHQgMgEgGgHQgFgHAAgMQAAgGACgGQACgGAFgFQAFgEAHgDQAIgCAKAAQATAAAJAIQAJAIAAAOIAAAFIgZAAQAAgJgCgDQgDgEgHAAQgFAAgEADQgEACAAAGQAAAEADADQACAEAHACIARAFQANAFAFAHQAFAHAAAMQAAAJgDAGQgDAGgFAFQgFAEgHACQgIABgJAAQgLAAgIgCgAo4g7QgHgHAAgRIAAhPIAcAAIAABKQAAAIACAEQADADAGAAQAPAAAAgSIAAhHIAcAAIAABrIgbAAIAAgMIAAAAQgFAIgHADQgHADgJAAQgNAAgHgGgAFeg3QgFgBgCgEQgDgDgBgFIgBgOIAAg+IgOAAIAAgSIAOAAIAAgfIAcAAIAAAfIAQAAIAAASIgQAAIAAA7QAAAGABADQACACAGAAIAHAAIAAATIgSABIgOgBgAJQg3IAAhrIAaAAIAAAOIABAAQAEgIAGgEQAGgFAJAAIACAAIADAAIAAAbIgJgBIgHABQgEABgDADQgDACgCAEQgBADAAAGIAABAgAG8g3IAAhZIgOAAIAAgSIAOAAIAAgNQAAgHACgFQACgFAEgDQADgDAGgBIAMgBIAPAAIAAAUIgGAAQgGAAgCACQgCACAAAEIAAAKIAQAAIAAASIgQAAIAABZgAEdg3IAAiPIAcAAIAACPgADug3IAAhrIAcAAIAABrgAncg3IAAhrIAbAAIAAAOIAAAAQAEgIAGgEQAGgFAJAAIADAAIACAAIAAAbIgJgBIgHABQgDABgDADQgDACgCAEQgCADAAAGIAABAgAqlg3IAAiPIAyAAQALAAAIAEQAHAEAFAGQAEAGACAIQACAHAAAIQAAALgDAIQgDAJgGAFQgGAFgIADQgJACgKAAIgPAAIAAA5gAqIiFIAMAAQAJAAAFgFQAGgFAAgLQAAgLgFgGQgFgFgKAAIgMAAgAgjhlIAAgXIA3AAIAAAXgADuiwIAAgXIAcAAIAAAXg");
	this.shape.setTransform(7.175,16.325);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_purposeBuilt, new cjs.Rectangle(-77.3,-3.8,169,40.3), null);


(lib.txt_OperatingCosts = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgWBBQgKgCgFgGQgFgFgDgIQgCgHAAgKIAAgEIAeAAIAAAEQAAAIAEAGQAFAFAIAAQAHAAAFgEQAEgEAAgHQAAgHgEgDIgIgFIgWgJQgOgEgHgIQgHgJAAgOQAAgHADgIQACgGAGgGQAGgFAJgEQAJgCAMAAQAWAAALAJQALAKAAASIAAAEIgeAAQAAgJgDgFQgDgFgIAAQgGAAgEAEQgFADAAAHQAAAFADAEQADAEAIACIATAHQAQAFAGAIQAHAIAAAPQAAAKgEAHQgDAIgHAGQgGAEgJADQgJACgKAAQgNgBgJgCg");
	this.shape.setTransform(103.175,30.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AANBTIgPgBQgGgBgDgEQgEgEAAgHIgBgQIAAhJIgRAAIAAgWIARAAIAAglIAfAAIAAAlIATAAIAAAWIgTAAIAABFQAAAIACADQADADAHAAIAEAAIADAAIAAAXIgKAAg");
	this.shape_1.setTransform(94.5,28.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgWBBQgKgCgFgGQgFgFgDgIQgCgHAAgKIAAgEIAeAAIAAAEQAAAIAEAGQAFAFAIAAQAHAAAFgEQAEgEAAgHQAAgHgEgDIgIgFIgWgJQgOgEgHgIQgHgJAAgOQAAgHADgIQACgGAGgGQAGgFAJgEQAJgCAMAAQAWAAALAJQALAKAAASIAAAEIgeAAQAAgJgDgFQgDgFgIAAQgGAAgEAEQgFADAAAHQAAAFADAEQADAEAIACIATAHQAQAFAGAIQAHAIAAAPQAAAKgEAHQgDAIgHAGQgGAEgJADQgJACgKAAQgNgBgJgCg");
	this.shape_2.setTransform(85.725,30.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgXBAQgKgEgHgJQgFgIgDgNQgCgNAAgRQAAgPADgNQADgMAFgJQAHgJAJgEQAKgFANAAQAPAAAKAEQAKAFAFAJQAGAIADAMQACANAAAQQAAARgCANQgEANgGAIQgGAIgJAEQgKAFgOgBIgCABQgNAAgIgEgAgIgoQgEADgCAGIgCAOIAAARIAAASIACAPQACAGAEADQADAEAFAAQAKAAAEgLQAEgLAAgYQAAgXgEgLQgEgKgKAAQgFAAgDAEg");
	this.shape_3.setTransform(74.8,30.4003);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgVBAQgJgDgGgHQgGgIgDgNQgDgNgBgUQAAgSAFgNQADgNAIgJQAHgHAJgEQAKgCAKAAQAXAAAMANQALAOAAAWIgfAAIgBgJIgCgIQgBgEgDgCQgDgDgFAAQgFABgEADQgEACgCAGQgCAFgBAIIAAASIAAAVQABAIACAGQACAFAEADQADADAFAAQAIAAAEgHQAEgIAAgPIAfAAQAAAZgLANQgLANgbABQgMAAgJgEg");
	this.shape_4.setTransform(63.65,30.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgkBPQgLgJAAgRIAfAAQAAAGAGAEIAFADIAFABQAKAAAEgGQAEgHAAgKIAAgRIgBAAQgFAIgHAEQgGAEgIAAQgUAAgKgPQgKgPAAgiIABgYQACgLAEgJQAEgKAIgGQAIgGAOAAQAHAAAGAEQAIADAEALIABAAIAAgOIAgAAIAAB5QAAAZgNAMQgMANgcAAQgVAAgMgJgAgHg7QgEADgCAEIgCAPIgBAWIABANQAAAFACAFQACAEADADQAEACAEABQAFgBAEgCQADgDACgEQACgFABgGIABgPQAAgYgEgKQgEgKgJAAQgFABgDACg");
	this.shape_5.setTransform(46.475,32.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAQBCIAAhYQAAgKgDgEQgEgEgIAAQgQAAAAAWIAABUIghAAIAAiAIAgAAIAAAPQAGgJAIgFQAIgEAKAAQAQAAAJAIQAIAJAAAUIAABeg");
	this.shape_6.setTransform(34.8,30.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgQBXIAAiAIAhAAIAACAgAgQg5IAAgdIAhAAIAAAdg");
	this.shape_7.setTransform(26.075,28.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AANBTIgOgBQgHgBgDgEQgEgEgBgHIgBgQIAAhJIgRAAIAAgWIARAAIAAglIAhAAIAAAlIATAAIAAAWIgTAAIAABFQAAAIACADQACADAHAAIAEAAIAEAAIAAAXIgLAAg");
	this.shape_8.setTransform(19.85,28.625);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AggBAQgHgDgDgEQgEgGgBgHQgCgGAAgGQAAgKACgGQACgHAEgEQAEgFAGgCQAGgDAJgDIARgFQAIgCADgEQADgDAAgGQAAgIgEgDQgDgFgIAAQgHAAgEAFQgEAEAAAIIAAAEIgeAAIAAgEQAAgLAEgIQADgHAGgEQAGgGAJgBQAIgCAJAAQAOAAAJACQAKAEAFAFQAFAFABAHQACAHAAAJIAABDIABAOIADALIgfAAIgDgGIgBgIIgBAAQgGALgHACQgHAEgMAAQgIAAgGgEgAAHAFIgHACQgJACgEAFQgEAFAAAJQAAAHADAGQACAFAHAAIAGgCQAEAAADgDQADgCACgEQACgEAAgFIAAgag");
	this.shape_9.setTransform(10.575,30.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AghBCIAAiAIAgAAIAAARQAFgJAGgGQAIgFAKAAIADAAIADAAIAAAgIgFAAIgFgBIgJACQgEABgEADQgDACgDAFQgBAEAAAHIAABMg");
	this.shape_10.setTransform(1.6,30.275);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgbA9QgKgFgEgKQgFgKgBgMIgBgYQAAgNABgMQACgMAGgJQAFgKAKgFQALgGAPABQAOgBAJAFQAKAFAFAJQAFAIADAMQACAMAAAPIAAAHIhBAAIAAAKIABALIADAJIAEAHQADADAEAAQAIAAAFgGQADgGABgMIAfAAQgCAWgLAMQgLAMgYAAQgQAAgLgHgAgHgpQgDACgBADIgDAIIgBAJIAAAGIAgAAIgBgNQAAgGgCgEQgCgEgDgCQgDgCgFAAQgEAAgEADg");
	this.shape_11.setTransform(-8.3,30.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgxBXIAAipIAfAAIAAANQAHgJAGgEQAGgEAKAAQAVAAAJAQQAKAQAAAkQAAAjgKAQQgJAPgVAAQgJAAgGgDQgHgEgFgHIgBAAIAAA1gAgNgyQgEALAAAVQAAAUAEAKQADAMAKAAQALAAADgMQAEgKgBgUQABgVgEgLQgDgLgLAAQgKAAgDALg");
	this.shape_12.setTransform(-19.55,32.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgYBAQgJgEgHgJQgFgIgDgNQgCgNAAgRQAAgPADgNQADgMAFgJQAGgJAKgEQAKgFANAAQAPAAAKAEQAKAFAFAJQAGAIACAMQADANAAAQQAAARgDANQgCANgHAIQgFAIgKAEQgKAFgOgBIgCABQgNAAgJgEgAgIgoQgEADgCAGIgCAOIAAARIAAASIACAPQACAGAEADQADAEAFAAQAKAAAEgLQAEgLAAgYQAAgXgEgLQgEgKgKAAQgFAAgDAEg");
	this.shape_13.setTransform(-31.3,30.4003);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AARBAIgRhaIgPBaIgmAAIgdh/IAiAAIAPBaIAAAAIAQhaIAjAAIARBaIABAAIAPhaIAgAAIgcB/g");
	this.shape_14.setTransform(-50.925,30.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgYBAQgKgEgGgJQgFgIgDgNQgCgNAAgRQAAgPADgNQACgMAGgJQAGgJAKgEQAKgFANAAQAPAAAKAEQAKAFAFAJQAGAIACAMQADANAAAQQAAARgDANQgCANgHAIQgFAIgKAEQgKAFgOgBIgCABQgNAAgJgEgAgIgoQgEADgCAGIgCAOIAAARIAAASIACAPQACAGAEADQADAEAFAAQAKAAAEgLQAEgLAAgYQAAgXgEgLQgEgKgKAAQgFAAgDAEg");
	this.shape_15.setTransform(-64.95,30.4003);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgvBWIAAirIAiAAIAACOIA9AAIAAAdg");
	this.shape_16.setTransform(-75.65,28.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_OperatingCosts, new cjs.Rectangle(-171.1,11.9,369,32.300000000000004), null);


(lib.txt_moreSellable = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgPATIAAglIAfAAIAAAlg");
	this.shape.setTransform(108.575,20.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgPATIAAglIAfAAIAAAlg");
	this.shape_1.setTransform(103.325,20.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgPATIAAglIAfAAIAAAlg");
	this.shape_2.setTransform(98.075,20.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AghBCIAAiAIAgAAIAAARQAEgJAIgGQAGgFALAAIADAAIADAAIAAAgIgFAAIgGgBIgIACQgFABgDADQgDACgCAFQgCAEAAAHIAABMg");
	this.shape_3.setTransform(92.25,15.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgYBAQgJgEgGgJQgGgIgCgNQgDgNAAgRQAAgPADgNQADgMAGgJQAFgJALgEQAJgFANAAQAPAAAKAEQAJAFAHAJQAFAIADAMQACANAAAQQAAARgCANQgEANgFAIQgHAIgJAEQgKAFgOgBIgCABQgNAAgJgEgAgJgoQgDADgCAGIgCAOIgBARIABASIACAPQACAGADADQAEAEAFAAQAKAAAEgLQAEgLAAgYQAAgXgEgLQgEgKgKAAQgFAAgEAEg");
	this.shape_4.setTransform(82.5,15.5503);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgYBAQgKgEgGgJQgFgIgCgNQgDgNAAgRQAAgPADgNQACgMAHgJQAGgJAJgEQAKgFANAAQAPAAAKAEQAKAFAFAJQAGAIACAMQADANAAAQQAAARgDANQgCANgHAIQgFAIgKAEQgKAFgOgBIgCABQgNAAgJgEgAgIgoQgEADgCAGIgCAOIgBARIABASIACAPQACAGAEADQADAEAFAAQAKAAAEgLQAEgLAAgYQAAgXgEgLQgEgKgKAAQgFAAgDAEg");
	this.shape_5.setTransform(71.5,15.5503);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgoBIQgJgQAAgkQAAgjAJgQQAJgQAVAAQAJAAAGAEQAGADAGAIIAAAAIAAg2IAiAAIAACqIghAAIAAgNQgFAJgHAEQgGADgKAAQgVAAgJgPgAgNgLQgEALAAAUQAAAVAEAKQADAMAKAAQALAAADgMQAEgKgBgVQABgUgEgLQgDgLgLAAQgKAAgDALg");
	this.shape_6.setTransform(60.1,13.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgaA9QgLgFgFgKQgEgKgBgMIgCgYQAAgNADgMQACgMAEgJQAGgKAKgFQAKgGAQABQAPgBAJAFQAJAFAFAJQAFAIACAMQACAMAAAPIAAAHIhAAAIAAAKIAAALIADAJIAGAHQACADAEAAQAJAAADgGQAEgGACgMIAdAAQAAAWgLAMQgLAMgYAAQgRAAgKgHgAgGgpQgDACgDADIgDAIIAAAJIAAAGIAhAAIgBgNQgBgGgCgEQgBgEgEgCQgDgCgFAAQgEAAgDADg");
	this.shape_7.setTransform(43.95,15.55);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AAQBWIAAhYQAAgKgEgEQgDgEgIAAQgQAAAAAUIAABWIghAAIAAirIAhAAIAAA4IAAAAQALgRAUAAQAQAAAJAJQAIAJAAATIAABfg");
	this.shape_8.setTransform(32.9,13.475);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AANBTIgOgBQgHgBgDgEQgEgEgBgHIgBgQIAAhJIgRAAIAAgWIARAAIAAglIAhAAIAAAlIATAAIAAAWIgTAAIAABFQAAAIABADQADADAHAAIAEAAIAEAAIAAAXIgLAAg");
	this.shape_9.setTransform(23.9,13.775);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AANBTIgPgBQgGgBgDgEQgEgEAAgHIgCgQIAAhJIgQAAIAAgWIAQAAIAAglIAgAAIAAAlIATAAIAAAWIgTAAIAABFQAAAIACADQADADAHAAIAEAAIADAAIAAAXIgKAAg");
	this.shape_10.setTransform(12.05,13.775);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgnA6QgJgJAAgTIAAhfIAhAAIAABYQAAAKAEAEQADAEAHAAQARAAAAgVIAAhVIAhAAIAACAIggAAIAAgPQgGAKgIAEQgIAEgKAAQgQAAgIgIg");
	this.shape_11.setTransform(2.95,15.725);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgXBAQgLgEgFgJQgGgIgCgNQgDgNAAgRQAAgPADgNQADgMAGgJQAFgJALgEQAJgFANAAQAPAAAKAEQAJAFAHAJQAFAIADAMQACANAAAQQAAARgCANQgEANgFAIQgHAIgJAEQgKAFgOgBIgCABQgNAAgIgEgAgJgoQgDADgCAGIgCAOIgBARIABASIACAPQACAGADADQAEAEAFAAQAKAAAEgLQAEgLAAgYQAAgXgEgLQgEgKgKAAQgFAAgEAEg");
	this.shape_12.setTransform(-8.3,15.5503);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgWBBQgKgCgFgGQgFgFgDgIQgCgHAAgKIAAgEIAeAAIAAAEQAAAIAEAGQAFAFAIAAQAHAAAFgEQAEgEAAgHQAAgHgEgDIgIgFIgWgJQgOgEgHgIQgHgJAAgOQAAgHADgIQACgGAGgGQAGgFAJgEQAJgCAMAAQAWAAALAJQALAKAAASIAAAEIgeAAQAAgJgDgFQgDgFgIAAQgGAAgEAEQgFADAAAHQAAAFADAEQADAEAIACIATAHQAQAFAGAIQAHAIAAAPQAAAKgEAHQgDAIgHAGQgGAEgJADQgJACgKAAQgNgBgJgCg");
	this.shape_13.setTransform(-24.125,15.55);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AANBTIgOgBQgHgBgDgEQgDgEgCgHIgBgQIAAhJIgRAAIAAgWIARAAIAAglIAhAAIAAAlIATAAIAAAWIgTAAIAABFQAAAIACADQACADAHAAIAEAAIAEAAIAAAXIgLAAg");
	this.shape_14.setTransform(-32.45,13.775);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AAQBCIAAhYQAAgKgEgEQgDgEgIAAQgQAAAAAWIAABUIghAAIAAiAIAgAAIAAAPQAFgJAJgFQAIgEAKAAQAQAAAIAIQAJAJAAAUIAABeg");
	this.shape_15.setTransform(-41.55,15.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgbA9QgJgFgGgKQgEgKgBgMIgBgYQAAgNACgMQABgMAGgJQAFgKAKgFQALgGAPABQAOgBAKAFQAJAFAFAJQAFAIACAMQACAMABAPIAAAHIhBAAIAAAKIAAALIAEAJIAEAHQADADAEAAQAIAAAEgGQAEgGABgMIAeAAQAAAWgMAMQgLAMgYAAQgQAAgLgHgAgHgpQgCACgCADIgEAIIAAAJIAAAGIAgAAIAAgNQgBgGgCgEQgBgEgEgCQgDgCgFAAQgEAAgEADg");
	this.shape_16.setTransform(-52.6,15.55);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AAvBCIAAhZQAAgIgDgFQgDgEgHAAQgIAAgFAGQgEAFgBALIAABUIgfAAIAAhZQgBgIgDgFQgCgEgIAAQgHAAgFAGQgFAFAAALIAABUIghAAIAAiAIAgAAIAAANQAHgJAHgDQAIgEALAAQAMAAAGAFQAIAFACAKIABAAQAEgKAIgFQAJgFAMAAQAQAAAIAKQAIAKAAASIAABdg");
	this.shape_17.setTransform(-66.7,15.425);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AghBCIAAiAIAgAAIAAARQAEgJAIgGQAGgFALAAIADAAIADAAIAAAgIgFAAIgGgBIgIACQgFABgDADQgDACgCAFQgCAEAAAHIAABMg");
	this.shape_18.setTransform(-78.75,15.425);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AggBAQgHgDgDgEQgEgGgBgHQgCgGAAgGQAAgKACgGQACgHAEgEQAEgFAGgCQAGgDAJgDIARgFQAIgCADgEQADgDAAgGQAAgIgEgDQgDgFgIAAQgHAAgEAFQgEAEAAAIIAAAEIgeAAIAAgEQAAgLAEgIQADgHAGgEQAGgGAJgCQAIgBAJAAQAOAAAJACQAKAEAFAEQAFAGABAHQACAHAAAJIAABDIABAOIADALIgfAAIgDgGIgBgIIgBAAQgGALgHACQgHAEgMAAQgIAAgGgEgAAHAFIgHACQgJACgEAFQgEAFAAAJQAAAHADAGQACAFAHAAIAGgCQAEAAADgDQADgCACgEQACgEAAgFIAAgag");
	this.shape_19.setTransform(-88.575,15.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgkBPQgLgJAAgRIAfAAQAAAGAGAEIAFADIAFABQAKAAAEgGQAEgHAAgKIAAgRIgBAAQgFAIgHAEQgGAEgIAAQgUAAgKgPQgKgPAAgiIABgXQACgMAEgJQAEgKAIgGQAIgGAOAAQAHAAAGAEQAIADAEALIABAAIAAgOIAgAAIAAB5QAAAZgNAMQgMANgcAAQgVAAgMgJgAgHg7QgEADgCAEIgCAPIgBAWIABANQAAAFACAFQACAEADADQAEACAEABQAFgBAEgCQADgDACgEQACgFABgGIABgPQAAgYgEgKQgEgKgJAAQgFABgDACg");
	this.shape_20.setTransform(-99.925,17.6);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgaA9QgLgFgEgKQgFgKgBgMIgCgYQAAgNACgLQADgNAEgJQAGgJAKgGQAKgFAQgBQAPABAJAEQAJAFAFAIQAFAJADAMQABAMAAAPIAAAGIhAAAIAAALIAAALIADAKIAGAGQADADADAAQAJAAADgGQAEgGACgMIAeAAQgCAWgKAMQgLALgYAAQgSABgJgHgAgGgpQgEABgCAEIgDAIIAAAJIAAAGIAhAAIgBgNQgBgGgCgEQgCgEgDgCQgDgCgFAAQgEAAgDADg");
	this.shape_21.setTransform(74.9,-10.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AgQBWIAAirIAhAAIAACrg");
	this.shape_22.setTransform(66.975,-12.875);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AgFBTQgGgDgHgJIAAANIgfAAIAAiqIAgAAIAAA2IABAAQAGgHAGgEQAGgEAJAAQAVAAAJAQQAKAQAAAjQAAAkgKAQQgJAPgVAAQgKAAgGgEgAgNgLQgEALAAAUQAAAVAEALQADAKAKABQALgBADgKQAEgLgBgVQABgUgEgLQgDgLgLAAQgKAAgDALg");
	this.shape_23.setTransform(58.75,-12.75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AggBBQgHgEgDgEQgEgGgBgHQgCgGAAgHQAAgJACgHQACgGAEgFQAEgEAGgDQAGgDAJgCIARgFQAIgCADgEQADgDAAgGQAAgIgEgEQgDgEgIAAQgHAAgEAEQgEAFAAAIIAAAEIgeAAIAAgEQAAgLAEgIQADgHAGgFQAGgEAJgDQAIgCAJAAQAOAAAJADQAKAEAFAEQAFAGABAHQACAIAAAIIAABDIABAOIADALIgfAAIgDgHIgBgHIgBAAQgGAKgHAEQgHACgMAAQgIAAgGgCgAAHAEIgHADQgJACgEAFQgEAFAAAJQAAAHADAFQACAGAHAAIAGgCQAEgBADgCQADgCACgEQACgEAAgFIAAgZg");
	this.shape_24.setTransform(47.275,-10.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgQBWIAAirIAhAAIAACrg");
	this.shape_25.setTransform(39.225,-12.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgQBWIAAirIAhAAIAACrg");
	this.shape_26.setTransform(33.975,-12.875);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgaA9QgKgFgGgKQgEgKgBgMIgCgYQABgNACgLQACgNAEgJQAGgJAKgGQAKgFAQgBQAOABAKAEQAJAFAFAIQAFAJACAMQACAMAAAPIAAAGIhAAAIAAALIAAALIAEAKIAEAGQADADAEAAQAJAAADgGQAEgGACgMIAdAAQAAAWgLAMQgLALgYAAQgRABgKgHgAgHgpQgCABgCAEIgEAIIAAAJIAAAGIAhAAIgBgNQgBgGgCgEQgBgEgEgCQgDgCgFAAQgEAAgEADg");
	this.shape_27.setTransform(26.05,-10.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AgWBBQgKgCgFgGQgFgFgDgIQgCgIAAgIIAAgFIAeAAIAAAEQAAAJAEAEQAFAGAIAAQAHAAAFgEQAEgEAAgHQAAgHgEgDIgIgFIgWgJQgOgEgHgIQgHgJAAgOQAAgHADgHQACgIAGgFQAGgFAJgEQAJgDAMAAQAWAAALAKQALAJAAASIAAAGIgeAAQAAgLgDgEQgDgFgIAAQgGAAgEAEQgFADAAAHQAAAFADADQADAEAIADIATAHQAQAFAGAHQAHAJAAAPQAAAKgEAIQgDAIgHAEQgGAFgJADQgJABgKAAQgNAAgJgCg");
	this.shape_28.setTransform(15.675,-10.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AgbA9QgJgFgGgKQgEgKgBgMIgBgYQAAgNACgLQABgNAGgJQAFgJAKgGQALgFAPgBQAOABAKAEQAJAFAFAIQAFAJACAMQACAMABAPIAAAGIhBAAIAAALIAAALIAEAKIAEAGQADADAEAAQAIAAAEgGQAEgGABgMIAeAAQAAAWgMAMQgLALgYAAQgQABgLgHgAgHgpQgCABgCAEIgEAIIAAAJIAAAGIAgAAIAAgNQgBgGgCgEQgBgEgEgCQgDgCgFAAQgEAAgEADg");
	this.shape_29.setTransform(0.05,-10.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AghBCIAAiAIAgAAIAAARQAEgJAIgGQAGgFALAAIADAAIADAAIAAAgIgFAAIgGgBIgIACQgFABgDADQgDACgCAFQgCAEAAAHIAABMg");
	this.shape_30.setTransform(-8.45,-10.925);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgXBAQgLgEgFgJQgGgIgCgNQgDgNAAgQQAAgQADgNQADgNAGgIQAFgJALgEQAJgFANAAQAPAAAKAEQAJAEAHAJQAFAJADAMQACANAAARQAAAQgCAMQgEANgFAJQgHAIgJAFQgKADgOAAIgCABQgNAAgIgEgAgJgpQgDAEgCAGIgCAOIgBASIABASIACAOQACAGADADQAEAEAFAAQAKAAAEgLQAEgLAAgXQAAgYgEgKQgEgLgKAAQgFAAgEADg");
	this.shape_31.setTransform(-18.2,-10.7997);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#353535").s().p("AAvBCIAAhZQAAgIgDgFQgDgEgHAAQgIAAgFAGQgEAFgBALIAABUIgfAAIAAhZQgBgIgDgFQgCgEgIAAQgHAAgFAGQgFAFAAALIAABUIghAAIAAiAIAgAAIAAANQAHgJAHgDQAIgEALAAQAMAAAGAFQAIAFACAKIABAAQAEgKAIgFQAJgFAMAAQAQAAAIAKQAIAKAAASIAABdg");
	this.shape_32.setTransform(-32.5,-10.925);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#353535").s().p("AgaA9QgLgFgFgKQgEgKgBgMIgCgYQAAgNADgLQACgNAEgJQAGgJAKgGQAKgFAQgBQAPABAJAEQAJAFAFAIQAFAJACAMQACAMAAAPIAAAGIhAAAIAAALIAAALIADAKIAFAGQADADAEAAQAJAAADgGQAEgGACgMIAdAAQAAAWgLAMQgLALgYAAQgRABgKgHgAgHgpQgCABgDAEIgDAIIAAAJIAAAGIAhAAIgBgNQgBgGgCgEQgBgEgEgCQgDgCgFAAQgEAAgEADg");
	this.shape_33.setTransform(-51.9,-10.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#353535").s().p("AAQBWIAAhYQAAgKgEgEQgDgEgIAAQgQAAAAAUIAABWIghAAIAAirIAhAAIAAA4IAAAAQALgRAUAAQAQAAAJAJQAIAJAAATIAABfg");
	this.shape_34.setTransform(-62.95,-12.875);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#353535").s().p("AgQBWIAAiOIgmAAIAAgdIBtAAIAAAdIgmAAIAACOg");
	this.shape_35.setTransform(-74.175,-12.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_moreSellable, new cjs.Rectangle(-184.5,-29.3,369,58.7), null);


(lib.txt_moreCustomers = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AGgBTQgKgEgGgIQgGgJgCgNQgDgNAAgQQAAgRADgMQADgMAGgJQAGgIAKgFQAJgEAOAAQAPgBAKAFQAKAEAGAJQAFAIADANQACAMAAARQAAAQgCANQgDANgGAIQgGAJgKAEQgKAEgOAAIgDAAQgNAAgIgEgAGvgVQgEADgCAGIgCANIAAAlIACAOQACAGAEAEQADADAGAAQAKAAAEgLQAEgKAAgYQAAgYgEgKQgEgLgKAAQgGAAgDAEgAljBTQgKgEgGgIQgFgJgDgNQgCgNAAgQQAAgRADgMQACgMAGgJQAGgIAKgFQAKgEAOAAQAPgBAKAFQAJAEAGAJQAGAIACANQADAMAAARQAAAQgDANQgDANgGAIQgGAJgJAEQgKAEgOAAIgEAAQgMAAgJgEgAlUgVQgDADgCAGIgCANIAAAlIACAOQACAGADAEQAEADAGAAQAKAAAEgLQAEgKAAgYQAAgYgEgKQgEgLgKAAQgGAAgEAEgAOEBUQgKgCgFgGQgFgFgDgHQgCgIAAgJIAAgFIAeAAIAAAEQAAAJAEAFQAFAFAIAAQAIAAAFgEQAEgEAAgHQAAgHgEgDIgIgFIgXgIQgOgFgHgJQgHgJAAgMQAAgIADgHQACgHAGgGQAGgFAJgDQAJgDANAAQAWAAALAJQALAKAAASIAAAFIgeAAQAAgKgDgFQgDgFgIAAQgHAAgEAEQgFADAAAHQAAAFADAEQADADAIACIAUAHQAQAFAGAJQAHAIAAAPQAAAKgEAIQgDAIgHAFQgGAFgJACQgJACgKAAQgOAAgJgDgALDBRQgKgGgFgKQgEgKgBgMIgCgYQAAgNACgLQACgNAFgJQAGgJAKgGQAKgFARAAQAOAAAJAEQAKAFAFAJQAFAIACAMQACALAAAPIAAAIIhBAAIAAAVIADAKIAFAHQADACAFAAQAIAAAEgGQAEgGABgMIAeAAQgBAWgLAMQgLAMgYAAQgSAAgKgGgALXgWQgDACgCAEIgDAIIAAANIAhAAIgBgMQAAgGgCgEQgCgEgDgCQgDgCgFAAQgFAAgEADgADrBUQgJgCgGgGQgFgFgCgHQgCgIAAgJIAAgFIAeAAIAAAEQAAAJAEAFQAEAFAJAAQAHAAAFgEQAFgEAAgHQAAgHgEgDIgIgFIgYgIQgNgFgHgJQgHgJAAgMQAAgIACgHQADgHAGgGQAGgFAIgDQAKgDAMAAQAXAAALAJQAKAKAAASIAAAFIgdAAQAAgKgEgFQgDgFgIAAQgGAAgFAEQgFADAAAHQAAAFADAEQADADAJACIAUAHQAPAFAHAJQAGAIAAAPQAAAKgDAIQgEAIgGAFQgHAFgIACQgJACgLAAQgOAAgJgDgABpBPQgJgJAAgTIAAhfIAhAAIAABYQAAAKAEAEQADAEAIAAQARAAAAgVIAAhVIAhAAIAACAIggAAIAAgPQgFAKgJAEQgIAEgLAAQgQAAgIgIgAAIBUQgIgDgGgIQgGgIgDgNQgEgNAAgTQAAgUAEgMQAEgNAHgIQAGgIAKgDQAJgDAMAAQAXAAAMANQALAOAAAWIggAAIAAgJIgCgIQgCgEgDgCQgDgCgEAAQgGAAgEADQgEACgCAGQgCAFgBAHIAAAoQABAJACAFQACAGADADQAEACAFAAQAJAAAEgHQADgHAAgQIAgAAQAAAZgLAOQgMANgaAAQgNAAgJgDgAilBRQgKgGgFgKQgFgKgBgMIgBgYQAAgNACgLQACgNAFgJQAFgJAKgGQALgFAQAAQAPAAAJAEQAJAFAFAJQAGAIACAMQACALAAAPIAAAIIhCAAIABAVIADAKIAFAHQADACAEAAQAJAAAEgGQADgGACgMIAeAAQgBAWgLAMQgLAMgYAAQgSAAgKgGgAiRgWQgDACgCAEIgDAIIgBANIAiAAIgBgMQgBgGgCgEQgBgEgEgCQgDgCgFAAQgFAAgDADgArGBRQgKgGgFgKQgEgKgBgMIgCgYQAAgNACgLQACgNAFgJQAGgJAKgGQAKgFARAAQAOAAAJAEQAKAFAFAJQAFAIACAMQACALAAAPIAAAIIhBAAIAAAVIADAKIAFAHQADACAFAAQAIAAAEgGQAEgGABgMIAeAAQgBAWgLAMQgLAMgYAAQgSAAgKgGgAqygWQgDACgCAEIgDAIIAAANIAhAAIgBgMQAAgGgCgEQgCgEgDgCQgDgCgFAAQgFAAgEADgAFZBUQgGgCgDgEQgEgEgBgGIgBgQIAAhJIgRAAIAAgXIARAAIAAglIAhAAIAAAlIATAAIAAAXIgTAAIAABFQAAAHACADQADAEAHAAIAEAAIADgBIAAAXIgVABIgQgBgAMhBUIAAiAIAgAAIAAARQAGgJAHgGQAHgFAKAAIADAAIADAAIAAAgIgKgBIgJACQgEABgEADQgDACgCAFQgDADAAAHIAABNgAJ8BUIAAhZQAAgIgDgFQgEgEgGAAQgIAAgFAGQgFAFAAALIAABUIghAAIAAhZQAAgIgDgFQgDgEgHAAQgIAAgEAGQgFAFAAALIAABUIghAAIAAiAIAgAAIAAANQAGgJAIgDQAIgEALAAQALAAAIAFQAIAFACAKIABAAQAEgKAIgFQAJgFAMAAQAQAAAIAKQAIAKAAASIAABdgAkGBUIAAiAIAgAAIAAARQAGgJAHgGQAHgFAKAAIADAAIADAAIAAAgIgKgBIgJACQgEABgEADQgDACgCAFQgDADAAAHIAABNgAmvBUIAAhZQAAgIgDgFQgEgEgGAAQgIAAgFAGQgFAFAAALIAABUIghAAIAAhZQAAgIgDgFQgDgEgHAAQgIAAgEAGQgFAFAAALIAABUIghAAIAAiAIAgAAIAAANQAGgJAIgDQAIgEALAAQALAAAIAFQAIAFACAKIABAAQAEgKAIgFQAJgFAMAAQAQAAAIAKQAIAKAAASIAABdgAsOBUIAAhYQAAgKgDgEQgEgEgHAAQgSAAAAAWIAABUIghAAIAAiqIAhAAIAAA3IABAAQAKgQAVAAQAQAAAJAIQAIAJAAAUIAABegAukBUIAAiOIgmAAIAAgcIBuAAIAAAcIgmAAIAACOg");
	this.shape.setTransform(-11.675,-119.8472);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AFCBUQgKgEgGgIQgFgJgDgNQgCgNAAgQQAAgRADgMQACgMAGgJQAGgIAKgFQAKgEAOAAQAPgBAKAFQAJAEAGAJQAGAIACANQADAMAAARQAAAQgDANQgDANgGAIQgGAJgJAEQgKAEgOAAIgEAAQgMAAgJgEgAFRgUQgDADgCAGIgCANIAAAlIACAOQACAGADAEQAEADAGAAQAKAAAEgLQAEgKAAgYQAAgYgEgKQgEgLgKAAQgGAAgEAEgADPBUQgKgEgGgIQgFgJgDgNQgCgNAAgQQAAgRADgMQACgMAGgJQAGgIAKgFQAKgEAOAAQAPgBAKAFQAJAEAGAJQAGAIACANQADAMAAARQAAAQgDANQgDANgGAIQgGAJgJAEQgKAEgOAAIgEAAQgMAAgJgEgADegUQgDADgCAGIgCANIAAAlIACAOQACAGADAEQAEADAGAAQAKAAAEgLQAEgKAAgYQAAgYgEgKQgEgLgKAAQgGAAgEAEgABIBIQgKgPAAgkQAAgjAKgQQAJgQAVAAQAJAAAHAEQAGADAGAIIAAAAIAAg2IAhAAIAACqIggAAIAAgNQgFAJgHADQgHAEgKAAQgVAAgJgQgABjgKQgEAKAAAVQAAAVAEAKQADALALAAQALAAADgLQADgKAAgVQAAgVgDgKQgDgLgLAAQgLAAgDALgAhVBSQgKgGgFgKQgFgKgBgMIgBgYQAAgNACgLQACgNAFgJQAFgJAKgGQALgFAQAAQAPAAAJAEQAJAFAFAJQAGAIACAMQACALAAAPIAAAIIhCAAIABAVIADAKIAFAHQADACAEAAQAJAAAEgGQADgGACgMIAeAAQgBAWgLAMQgLAMgYAAQgSAAgKgGgAhBgVQgDACgCAEIgDAIIgBANIAiAAIgBgMQgBgGgCgEQgBgEgEgCQgDgCgFAAQgFAAgDADgAkPBVQgGgCgDgEQgEgEgBgGIgBgQIAAhJIgRAAIAAgXIARAAIAAglIAhAAIAAAlIATAAIAAAXIgTAAIAABFQAAAHACADQADAEAHAAIAEAAIADgBIAAAXIgVABIgQgBgAHxBVIAAglIAfAAIAAAlgAGfBVIAAiAIAgAAIAAARQAGgJAHgGQAHgFAKAAIADAAIADAAIAAAgIgKgBIgJACQgEABgEADQgDACgCAFQgDADAAAHIAABNgAidBVIAAhYQAAgKgEgEQgDgEgIAAQgRAAAAAVIAABVIghAAIAAiqIAhAAIAAA3IAAAAQAKgQAWAAQAQAAAIAIQAJAJAAAUIAABegAmWBVIAAhYQAAgKgDgEQgEgEgHAAQgSAAAAAVIAABVIghAAIAAiAIAgAAIAAAPQAGgJAIgFQAJgEAKAAQAQAAAJAIQAIAJAAAUIAABegAoPBVIAAiAIAhAAIAACAgAoPg7IAAgcIAhAAIAAAcg");
	this.shape_1.setTransform(-10.375,-92.5972);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_moreCustomers, new cjs.Rectangle(-108.7,-128.5,194.10000000000002,44.7), null);


(lib.txt_automated = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AOIBIQgJgGgFgJQgDgIgBgKIgCgWQAAgMACgJQABgKAFgJQAFgIAJgEQAIgGAPABQANgBAIAEQAIAFAFAHQAEAIACALQACAJAAANIAAAGIg5AAIAAATIACAIQADAEACADQACACAEgBQAIABADgGQAEgFABgKIAaAAQgBATgJAKQgKALgVAAQgQAAgIgFgAOZgTIgFAFIgCAIIAAALIAdAAIgBgKIgCgJQgCgDgDgCQgCgBgFgBQgEAAgDACgAMwBKQgIgCgFgHQgGgHgDgLQgCgMAAgRQAAgRAEgLQADgMAGgGQAGgHAIgDQAIgDALABQAUgBAKAMQALAMAAATIgcAAIgBgHIgCgHQgBgEgDgBQgCgDgFAAQgFAAgDADQgDADgCAEQgCAFgBAGIAAAjQABAIACAEQABAFADADQADACAFgBQAIABADgHQAEgGAAgOIAcAAQgBAWgJAMQgLAMgXAAQgKAAgJgDgAJiBKQgGgDgDgEQgCgFgCgFQgCgGAAgGQAAgIACgGQABgFAEgFQADgEAGgDIANgEIAQgFQAHgCACgCQADgCAAgGQAAgGgDgEQgDgDgIgBQgGAAgDAFQgEAEAAAGIAAADIgaAAIAAgCQAAgLADgGQAEgGAFgFQAFgEAHgCQAIgCAHABQAOAAAHACQAJADAEAEQAFAFABAGQACAGAAAIIAAA6IABANIACAKIgcAAIgBgGIgCgGIAAAAQgGAIgHADQgGADgLAAQgHAAgFgDgAKGAVIgHACQgIACgEAFQgEAFAAAHQAAAGADAFQACAEAGAAIAGAAIAGgDIAEgGQACgDAAgFIAAgWgAGlBIQgJgGgEgJQgEgIgBgKIgBgWQAAgMACgJQABgKAFgJQAFgIAIgEQAJgGAPABQANgBAHAEQAIAFAGAHQAEAIABALQACAJAAANIAAAGIg5AAIAAATIADAIQACAEADADQACACAEgBQAIABADgGQAEgFAAgKIAaAAQgBATgJAKQgKALgUAAQgQAAgJgFgAG3gTIgFAFIgDAIIAAALIAdAAIgBgKIgCgJQgBgDgDgCQgDgBgEgBQgEAAgDACgAB1BKQgGgDgDgEQgDgFgBgFQgBgGAAgGQAAgIABgGQACgFADgFQADgEAGgDIANgEIARgFQAGgCADgCQACgCAAgGQAAgGgDgEQgDgDgIgBQgHAAgDAFQgDAEAAAGIAAADIgaAAIAAgCQAAgLADgGQAEgGAEgFQAGgEAHgCQAIgCAHABQANAAAJACQAHADAFAEQAEAFACAGQABAGABAIIAAA6IAAANIADAKIgcAAIgCgGIgBgGIAAAAQgGAIgHADQgGADgKAAQgIAAgFgDgACYAVIgGACQgIACgEAFQgEAFAAAHQAAAGADAFQACAEAGAAIAGAAIAGgDIAEgGQACgDAAgFIAAgWgAi8A/QgIgOAAgfQAAgeAIgOQAJgOARAAQAIAAAHADQAFAEAFAGIABAAIAAgwIAcAAIAACWIgcAAIAAgMIAAAAQgFAIgFADQgHADgJAAQgRAAgJgOgAikgJQgDAJAAASQAAATADAJQADAJAJAAQAJAAAEgJQADgJAAgTQAAgSgDgJQgEgJgJAAQgJAAgDAJgAkPBIQgJgGgEgJQgEgIgBgKIgBgWQAAgMABgJQACgKAFgJQAFgIAIgEQAJgGAPABQANgBAHAEQAIAFAGAHQAEAIABALQACAJAAANIAAAGIg5AAIAAATIADAIQACAEADADQACACAEgBQAIABADgGQAEgFAAgKIAaAAQgBATgJAKQgKALgUAAQgQAAgJgFgAj9gTIgFAFIgDAIIAAALIAdAAIgBgKIgCgJQgBgDgDgCQgDgBgEgBQgEAAgDACgAmtBKQgGgDgDgEQgCgFgCgFQgCgGABgGQgBgIACgGQACgFADgFQAEgEAFgDIANgEIARgFQAGgCADgCQACgCAAgGQAAgGgDgEQgDgDgHgBQgHAAgEAFQgDAEAAAGIAAADIgaAAIAAgCQAAgLADgGQADgGAFgFQAGgEAHgCQAIgCAIABQAMAAAJACQAHADAFAEQAEAFACAGQACAGgBAIIAAA6IABANIADAKIgcAAIgCgGIgBgGIgBAAQgEAIgHADQgHADgKAAQgIAAgFgDgAmKAVIgFACQgKACgDAFQgEAFAAAHQAAAGACAFQADAEAGAAIAGAAIAGgDIAEgGQACgDAAgFIAAgWgAqfBKQgJgEgFgHQgFgIgCgLQgCgMAAgOQAAgOACgKQACgLAGgIQAFgHAJgFQAIgEANABQAMAAAJADQAIADAGAJQAEAHADALQACAKAAAPQAAAPgCAKQgDAMgFAHQgFAHgJAFQgIADgMAAQgNAAgJgDgAqSgRQgDACgCAFQgCAGAAAGIAAAgQAAAHACAGQACAFADADQADACAGAAQAJABACgKQAEgJAAgVQAAgUgEgKQgCgIgJgBQgGAAgDAEgAtJBFQgHgGAAgRIAAhUIAcAAIAABNQAAAKADACQAEAEAGAAQAPAAAAgSIAAhLIAdAAIAABxIgcAAIAAgOIAAAAQgFAIgGAFQgIADgKAAQgNAAgIgIgAFwBKQgGgBgCgEQgDgDgBgGIgBgOIAAg/IgPAAIAAgVIAPAAIAAggIAdAAIAAAgIARAAIAAAVIgRAAIAAA7QAAAHACADQACADAGAAIAHAAIAAAUIgTAAIgOgBgAlEBKQgGgBgCgEQgDgDgBgGIgBgOIAAg/IgPAAIAAgVIAPAAIAAggIAdAAIAAAgIARAAIAAAVIgRAAIAAA7QAAAHACADQACADAGAAIAHAAIAAAUIgTAAIgOgBgArZBKQgFgBgDgEQgCgDgBgGIgBgOIAAg/IgQAAIAAgVIAQAAIAAggIAdAAIAAAgIAQAAIAAAVIgQAAIAAA7QAAAHABADQACADAHAAIAGAAIAAAUIgSAAIgPgBgALxBLIAAhOQAAgIgEgDQgDgEgGAAQgPAAAAASIAABLIgeAAIAAhxIAdAAIAAAOIAAAAQAEgIAIgFQAHgEAKABQANAAAIAHQAHAHAAASIAABTgAIsBLIAAhOQAAgIgDgDQgEgEgGAAQgPAAAAASIAABLIgdAAIAAhxIAcAAIAAAOIAAAAQAFgIAHgFQAHgEAKABQANAAAIAHQAHAHAAASIAABTgAExBLIAAhOQAAgIgDgDQgDgEgGAAQgQAAAAASIAABLIgdAAIAAhxIAcAAIAAAOIABAAQAEgIAHgFQAHgEAKABQAOAAAHAHQAIAHAAASIAABTgADMBLIAAhxIAcAAIAABxgAA+BLIAAhPQABgGgDgEQgCgEgHAAQgHAAgEAEQgEAFAAAJIAABLIgdAAIAAhPQAAgGgCgEQgDgEgFAAQgHAAgEAEQgEAFgBAJIAABLIgcAAIAAhxIAcAAIAAAMIAAAAQAFgHAHgEQAHgDAIAAQAKAAAHAEQAHAFACAIIABAAQADgJAHgEQAIgEAKAAQAPAAAHAIQAGAJAAARIAABRgAnkBLIAAhPQAAgGgCgEQgDgEgGAAQgHAAgEAEQgEAFAAAJIAABLIgdAAIAAhPQAAgGgCgEQgDgEgGAAQgHAAgEAEQgEAFgBAJIAABLIgdAAIAAhxIAcAAIAAAMIABAAQAGgHAGgEQAHgDAJAAQALAAAGAEQAHAFACAIIABAAQADgJAHgEQAIgEAKAAQAPAAAHAIQAGAJABARIAABRgAt1BLIgHggIgnAAIgHAgIggAAIAoiWIAlAAIAoCWgAufASIAeAAIgOhDIgBAAgADMgzIAAgZIAcAAIAAAZg");
	this.shape.setTransform(2.05,11.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_automated, new cjs.Rectangle(-95,3.8,194.2,15.399999999999999), null);


(lib.stack_img = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shirtStack();
	this.instance.setTransform(-94.65,-96.95,1.1544,1.1544);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.stack_img, new cjs.Rectangle(-94.6,-96.9,189.3,193.9), null);


(lib.printer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.instance = new lib.printerFullFrame();
	this.instance.setTransform(-132.05,-109.7,0.672,0.672);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_mc, new cjs.Rectangle(-132,-109.7,278.9,250), null);


(lib.Epson_Logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoWCSIAAkjIQtAAIAAEjg");
	mask.setTransform(-42.875,-28.85);

	// Layer_1
	this.instance = new lib.Epson_Logo();
	this.instance.setTransform(-91.75,-38.4,0.6375,0.6375);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Epson_Logo_1, new cjs.Rectangle(-91.7,-38.4,98.2,24.2), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape.setTransform(61.025,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_1.setTransform(47.475,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag1A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAfABAWAVQAXAXAAAeQAAAggXAVQgWAXgfAAQgfAAgWgXgAghghQgOAOAAATQAAAUAOAOQAOAPATAAQAUAAAOgPQAOgOAAgUQAAgTgOgOQgOgPgUAAQgTAAgOAPg");
	this.shape_2.setTransform(31.275,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBBMQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIglhSIgBAAIgMBOQAAADgEABIgSAAQgFgBABgEIAZiNQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAuBiIAAAAIAuhiQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAIADAAQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIAZCNQABAEgFABIgTAAQgDgBgBgDIgMhOIgBAAIglBSQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(13.1508,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BMQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIhUheIgBAAIAABZQAAAEgEABIgTAAQgEgBAAgEIAAiMQAAgDAEgBIADAAQABABAAAAQAAAAABAAQAAAAABAAQAAABABAAIBUBaIAAAAIAAhVQAAgFAFAAIATAAQAEAAAAAFIAACMQAAADgEABg");
	this.shape_4.setTransform(-10,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_5.setTransform(-25.075,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAwBLQgEgBgCgEIgLgWIg+AAIgKAWQgBAEgFABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIBBiNQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIACAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIBACNQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAVAYIgVgtIAAAAIgUAtIApAAg");
	this.shape_6.setTransform(-39.85,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_7.setTransform(-52.925,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBKQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAB1IA0AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_8.setTransform(-64.475,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_9.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,162.5,51.5), null);


(lib.time_lines = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AD/FpQgbgyABhRQAChVgrhLQg1hYh9hdQhwhTiHgJQhEgFgsAMIgRgJQgTgQgRghQgRghAKgmQAGgTAJgMQCshjDwBiQB4AyBXBEQBjA0AxBvQApBbAAB3QAABlgaBVQgaBQgbAFIgPACQgoAAgZgug");
	mask.setTransform(19.55,-22.529);

	// Layer_1
	this.instance = new lib.timer();
	this.instance.setTransform(-57.75,-58.25,0.5616,0.5616);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.time_lines, new cjs.Rectangle(-21.8,-58.2,78.1,76.4), null);


(lib.minuteHand = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AAyCOQgygxgyg1QhmhogCgQQgHguAwgPQAVgGAaAJQAMAFAJAGIBYBNQBaBQAIASIAOAhQAEAPgLAXQgLAWgsADg");
	mask.setTransform(11.4281,11.068);

	// Layer_1
	this.instance = new lib.timer();
	this.instance.setTransform(-57,-57,0.5616,0.5616);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.minuteHand, new cjs.Rectangle(-4.2,-3.3,31.3,28.8), null);


(lib.hourHand = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AgiDJQgxgVAMi8QAGhfAPhaQAWgJAZgEQAxgHAPAXQAYAlgSExQgGAUgPAQQgTAVgaAAQgQAAgTgIg");
	mask.setTransform(-0.7814,-18.2745);

	// Layer_1
	this.instance = new lib.timer();
	this.instance.setTransform(-57,-57,0.5616,0.5616);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.hourHand, new cjs.Rectangle(-8.2,-39.1,14.899999999999999,41.7), null);


(lib.arrow_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AixGqQiOhDh5h/Qjzj+BnkuIA7iIIAVgBQASgBAugKQAbgFAOAFQAJADAQAMIABAAIAGAJIALAMIAGATQgBAqAOAXIALAQQAGAJABAIQACAGgCAKIgCAPQgGAkASAiQAPAaAWAOQgBAbACAcQAOC0CLA/QCVBECjhAQCEg0BHhiIAigFQAqgEAiAFQBsARgIBoQgNAigbAwQg4BfhNBFQiaCKjLAAQh4AAiKgxg");
	mask.setTransform(-0.1451,12.5247);

	// timer_png
	this.instance = new lib.timer();
	this.instance.setTransform(-52.65,-60,0.5616,0.5616);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.arrow_mc, new cjs.Rectangle(-52.6,-35,113.6,89), null);


(lib.arrow_LG = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ApcAgQAAgCFuAFIAAqFIHjAAIAAKFIFoAAIpdJAg");
	this.shape.setTransform(0.025,-0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.arrow_LG, new cjs.Rectangle(-60.5,-61.1,121.1,122.2), null);


(lib.arrow_icon = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AiOguQABABEchsIgxEzg");
	mask.setTransform(-40.125,-33.725);

	// timer_png
	this.instance = new lib.timer();
	this.instance.setTransform(-57,-57,0.5616,0.5616);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.arrow_icon, new cjs.Rectangle(-54.4,-49.1,28.599999999999998,30.8), null);


(lib.money_sign = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.moneySign();
	this.instance.setTransform(-19.35,-31.85,0.1778,0.1778);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.money_sign, new cjs.Rectangle(-19.3,-31.8,38.7,63.6), null);


(lib.circle_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#04529D").s().p("AnzH0QjOjPAAklQAAkkDOjPQDPjOEkAAQElAADPDOQDODPAAEkQAAEljODPQjPDOklAAQkkAAjPjOg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.circle_mc, new cjs.Rectangle(-70.6,-70.6,141.2,141.2), null);


(lib.checkMark_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(14).p("AgwgMQAgARAdAX");
	this.shape.setTransform(30.8836,-45.505);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(14).p("AiSgqQCCAUBnBQ");
	this.shape_1.setTransform(23.5006,-48.4675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(14).p("Ai6grQAZgCAbAAQC2AACLBq");
	this.shape_2.setTransform(13.5125,-48.805);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(14).p("AkvAjQB+hQCfAAQC2AACMBq");
	this.shape_3.setTransform(1.8625,-48.805);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(14).p("AmdDIQAnhtBYhYQCdibDcAAQC3AACMBr");
	this.shape_4.setTransform(-9.1375,-38.1235);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(14).p("AmLFqQghhYAAhlQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_5.setTransform(-10.6375,-17.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(14).p("AhnICQhcgnhMhMQididAAjdQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_6.setTransform(-10.6375,-2.0625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(14).p("AG9GQQiWCHjNAAQjdAAicidQidicAAjeQAAjdCdicQCcidDdAAQC3AACLBs");
	this.shape_7.setTransform(-9,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(14).p("AIWgeQABAPAAAPQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_8.setTransform(-0.025,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#06539E").ss(14).p("AHjjoQA0BqAAB+QAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_9.setTransform(-0.025,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#06539E").ss(14).p("AGdlTQB6CRAADCQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACLBs");
	this.shape_10.setTransform(-0.025,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#06539E").ss(14).p("AIXAAQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQDdAACdCdQCdCcAADdg");
	this.shape_11.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).wait(133));

	// Layer_3
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#06539E").ss(14,2,1).p("AgJgKIATAV");
	this.shape_12.setTransform(-19.3125,1.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#06539E").ss(14,2,1).p("AgkgmIBJBN");
	this.shape_13.setTransform(-16.6125,4.1875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#06539E").ss(14).p("AAZgYIgyAx");
	this.shape_14.setTransform(-4.4,11.7375);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#06539E").ss(14,1,1).p("AAXAYIgtgv");
	this.shape_15.setTransform(-9.275,11.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#06539E").ss(14,2,1).p("AgrgtIBXBb");
	this.shape_16.setTransform(-15.975,4.85);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#06539E").ss(14).p("ABEhCIiHCF");
	this.shape_17.setTransform(-0.125,7.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#06539E").ss(14).p("ACAh9Ij/D7");
	this.shape_18.setTransform(5.8875,1.6125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#06539E").ss(14).p("AChieIlBE9");
	this.shape_19.setTransform(9.175,-1.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#06539E").ss(14).p("ACtioIlZFR");
	this.shape_20.setTransform(10.3,-2.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#06539E").ss(14).p("ACoijIlPFH");
	this.shape_21.setTransform(9.8,-2.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_12}]},8).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_17}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_18}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_20}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_21}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).wait(129));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-60.4,152.7,152.6);


(lib.stack_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// stack_img
	this.instance = new lib.stack_img();
	this.instance.setTransform(-23,-458);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(48).to({_off:false},0).to({alpha:1},4).wait(16).to({_off:true},1).wait(101));

	// stack_img
	this.instance_1 = new lib.stack_img();
	this.instance_1.setTransform(-19,-363.95);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(41).to({_off:false},0).to({alpha:1},4).wait(23).to({_off:true},1).wait(101));

	// stack_img
	this.instance_2 = new lib.stack_img();
	this.instance_2.setTransform(-14,-273.95);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:1},5).wait(22).to({_off:true},1).wait(12).to({_off:false},0).wait(28).to({_off:true},1).wait(101));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-117.6,-554.9,198.3,378);


(lib.timer_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// lines_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_1 = new cjs.Graphics().p("AhOAVQgMg3AWgwQAMgZB5ADQgHAPgCASQgFAnATAfIAHAKQAEAHABAGQABAFgDAQQgDAWAGAUQg5AGgtAPQgugXgNg+g");
	var mask_graphics_2 = new cjs.Graphics().p("AisAVQgMg3AWgwQARglD+AYIBEAHQgRAbgCArQgBAQABAXIABApIgBAmQg7gVhQAEQhKAEg7ATQgugXgMg+g");
	var mask_graphics_3 = new cjs.Graphics().p("AheBAQhLADg7ATQgugWgNg+QgMg4AWgwQARgkEAAYQCAAMCDATQAIAAAdAUQgSALgTASQgLALgQATIgaAeQgkAlgQATQgSAWgKAVQhNhEiLAHg");
	var mask_graphics_4 = new cjs.Graphics().p("ABABOQhNhNiVAHQhLADg7ATQgugWgMg9QgMg5AWgwQARgkD/AYQCAAMCEATQAPAABWBHQApAhAeAeQgyAPgyA2IgsA0QgcAhgSASIgPAOQgmgyg1g1g");
	var mask_graphics_5 = new cjs.Graphics().p("ACXDCQgthThghfQhMhNiVAHQhLAEg7ATQgugXgNg+QgMg4AWgwQARglEAAYQCAAMCDAUQAPAABXBGQBkBSAlBBQAZArAPBUQhMAFg2AiIgeAUQgTANgLAHIgxAWQgJgZgOgZg");
	var mask_graphics_6 = new cjs.Graphics().p("ACOCWQguhThfheQhNhOiVAHQhLAEg7ATQgugXgMg+QgMg4AWgwQARglD/AYQCBAMCDAUQAPAABWBGQBkBSAmBCQAsBMANDOIABARIgBAAIg7AFIhGABQgrABgbADIgiAFQgIhEgmhFg");
	var mask_graphics_7 = new cjs.Graphics().p("AFWGDQgjgHgigWQhVg3AAhSQAAhWgwhYQgthShfhfQhNhOiVAHQhLAEg7ATQgugXgNg+QgMg4AWgwQARglEAAYQCBAMCCAUQAPAABXBGQBkBSAlBCQAsBNAODNQAODPgmAYQgMAHgRAAQgLAAgOgDg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(1).to({graphics:mask_graphics_1,x:-17.2493,y:-84.1547}).wait(1).to({graphics:mask_graphics_2,x:-7.7868,y:-84.151}).wait(1).to({graphics:mask_graphics_3,x:3.6507,y:-82.2135}).wait(1).to({graphics:mask_graphics_4,x:10.4382,y:-76.6135}).wait(1).to({graphics:mask_graphics_5,x:15.7757,y:-70.351}).wait(1).to({graphics:mask_graphics_6,x:16.7132,y:-65.9635}).wait(1).to({graphics:mask_graphics_7,x:16.8517,y:-55.6818}).wait(74));

	// time_lines
	this.instance = new lib.time_lines();
	this.instance.setTransform(-1.75,-37.85,1,1,0,0,0,1.6,-3.8);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(80));

	// arrow_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_1 = new cjs.Graphics().p("AgEgCIgPgMQgIgIgFgHIgHgNQBAgWALAgQAEAZAAA7QgVghgXgVg");
	var mask_1_graphics_2 = new cjs.Graphics().p("AgeCKQgKgdgLguIgShLQgKgkgOgaIBPgrQBagpAOAoQAEAZAAA/QAAAfhIBTQgZAdgbAaIAAgBg");
	var mask_1_graphics_3 = new cjs.Graphics().p("Ai7DCQAAhTglh6IgBgCQCJgXB1h2IBYgxQBbgoAOAnQAEAZAAA/QAAAghIBTQhXBjhvBAQhIAphIAVIABgeg");
	var mask_1_graphics_4 = new cjs.Graphics().p("AmdCrQAMgKAMgMIAngoQAYgXAUgNIAegQQATgKAKgJQAbgWAJgjIADgMQAYAGAbADQDOAYCoinIBZgxQBbgoANAnQAEAZAAA/QAAAghIBTQhWBjhwBAQiSBUiVAAQiCAAiEhAg");
	var mask_1_graphics_5 = new cjs.Graphics().p("AmSBnQhNg4g9haIAPgGQBQgfBCgBIAyAAQAdAAAUgHQANgEAMgIQAXAMAcAHQBGAuBoANQDOAYCoinIBZgxQBbgoANAnQAEAZAAA/QAAAghIBTQhWBjhwBAQiTBUiUAAQi7AAi/iEg");
	var mask_1_graphics_6 = new cjs.Graphics().p("AleCQQhjhHhHiAQg8hrgMhxIBEABQA5ABBvAQIAhAFQASCsCYAoQBHAtBmANQDQAZCoinIBYgxQBbgoAOAnQAEAZAAA/QAAAghIBSQhXBkhwBAQiTBUiUAAQi7AAi+iEg");
	var mask_1_graphics_7 = new cjs.Graphics().p("AldEjQhihHhIiAQiJj0BzkPIBxAxQBJAfAzAZQgVBRABBYQACDTCrAtQBGAuBnAMQDPAaCoioIBZgwQBbgoANAnQAEAZAAA+QAAAghIBTQhWBjhwBBQiTBUiVAAQi6AAi/iFg");
	var mask_1_graphics_8 = new cjs.Graphics().p("AldF1QhihHhIiBQiPkACFkeQAkgsAqgmQBVhLAiAfQAqAnAPAwQAQAygSAsQgxByACCFQACDSCrAtQBGAuBnANQDPAZCoioIBZgxQBbgoANAnQAEAZAAA/QAAAghIBTQhWBkhwBAQiTBUiVAAQi6AAi/iEg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(1).to({graphics:mask_1_graphics_1,x:46.375,y:-13.8985}).wait(1).to({graphics:mask_1_graphics_2,x:40.9875,y:-5.2127}).wait(1).to({graphics:mask_1_graphics_3,x:27.7875,y:3.3123}).wait(1).to({graphics:mask_1_graphics_4,x:8.9125,y:4.412}).wait(1).to({graphics:mask_1_graphics_5,x:-3.7625,y:4.4125}).wait(1).to({graphics:mask_1_graphics_6,x:-8.9375,y:0.3127}).wait(1).to({graphics:mask_1_graphics_7,x:-9.0658,y:-14.4498}).wait(1).to({graphics:mask_1_graphics_8,x:-9.067,y:-22.576}).wait(73));

	// arrow_mc
	this.instance_1 = new lib.arrow_mc();
	this.instance_1.setTransform(-8.3,-31.9);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(80));

	// arrowHead
	this.instance_2 = new lib.arrow_icon();
	this.instance_2.setTransform(43.4,-13.2,1,1,176.8038,0,0,-42.7,-28.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).wait(1).to({rotation:187.2866,x:37.2,y:-3.5},0).wait(1).to({rotation:225.7753,x:10.45,y:14.45},0).wait(1).to({regX:-42.6,regY:-28.8,rotation:267.0934,x:-21.75,y:13.95},0).wait(1).to({regX:-42.5,scaleX:0.9999,scaleY:0.9999,rotation:293.531,x:-43.15,y:-1.5},0).wait(1).to({rotation:322.9715,x:-54.8,y:-25.65},0).wait(1).to({rotation:349.4348,x:-52.9,y:-50.8},0).wait(1).to({regX:-42.6,regY:-28.9,rotation:359.3355,x:-46.55,y:-63.9},0).wait(73));

	// hourHand
	this.instance_3 = new lib.hourHand();
	this.instance_3.setTransform(-3.75,-35.25);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1).to({_off:false},0).to({alpha:1},2).wait(78));

	// arrow
	this.instance_4 = new lib.minuteHand();
	this.instance_4.setTransform(-3.8,-35.3,1,1,-105.9883);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1).to({_off:false},0).to({rotation:-75.834,y:-35.25,alpha:1},2,cjs.Ease.quadOut).to({rotation:-0.4468,x:-3.75},5).wait(73));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.3,-116.9,165.3,168.5);


(lib.money_icon = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// money_sign
	this.instance = new lib.money_sign();
	this.instance.setTransform(1.9,-1.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).wait(114));

	// arrow_LG
	this.instance_1 = new lib.arrow_LG();
	this.instance_1.setTransform(1.85,-133.6);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({y:-6.4},9,cjs.Ease.quadInOut).wait(105));

	// circle_mc
	this.instance_2 = new lib.circle_mc();
	this.instance_2.setTransform(2.05,3.5,0.0637,0.0637);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({_off:false},0).to({scaleX:1.063,scaleY:1.063},3,cjs.Ease.quadOut).to({scaleX:1,scaleY:1},6,cjs.Ease.quadOut).wait(108));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-73,-194.7,150.1,273.29999999999995);


(lib.checkMark_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// checkMark_anim
	this.instance = new lib.checkMark_anim("synched",0,false);
	this.instance.setTransform(19.95,-28.55,1,1,0,0,0,15.8,15.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(54).to({startPosition:54},0).to({_off:true},1).wait(305));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_purposeBuilt();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(46).to({_off:true},1).wait(305));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.3,-104.8,173.7,190.6);


(lib.Timer_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_10
	this.instance = new lib.timer_anim("synched",0,false);
	this.instance.setTransform(2.05,-47.4,1,1,0,0,0,0,-38.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(58).to({startPosition:58},0).to({_off:true},1).wait(301));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_automated();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(50).to({_off:true},1).wait(301));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-95,-100.9,194.2,169.4);


(lib.shield_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.money_icon("synched",0,false);
	this.instance.setTransform(4,-42.45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(75).to({startPosition:75},0).to({_off:true},1).wait(284));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_OperatingCosts();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(67).to({_off:true},1).wait(284));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-171.1,-237.2,369,330.79999999999995);


// stage content:
(lib.Epson_DTG_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,125.0015,1,0.4167);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// Epson_Logo
	this.instance = new lib.Epson_Logo_1();
	this.instance.setTransform(80.75,40.55,0.8039,0.8039);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},7).wait(67).to({alpha:0},5).wait(15).to({alpha:1},8).wait(258));

	// ctaBtn_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_351 = new cjs.Graphics().p("AmvCUQgiAAAAgjIAAAAIAAjiQAAgiAiAAIAAAAINfAAQAiAAAAAiIAAAAIAADiQAAAjgiAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(351).to({graphics:mask_graphics_351,x:55.5642,y:226.8144}).wait(9));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-10.7,-8.3,10.8,8.2).s().p("AmOEqIJFr4IDYClIpGL4g");
	this.shape_1.setTransform(0.825,197.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-10.8,-8.3,10.8,8.2).s().p("AmPErIJGr6IDZCmIpHL5g");
	this.shape_2.setTransform(4.55,198.85);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-10.8,-8.3,10.9,8.3).s().p("AmSEsIJLr+IDaCmIpLL/g");
	this.shape_3.setTransform(15.725,203.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-11,-8.4,11,8.4).s().p("AmWEwIJRsHIDcCoIpRMHg");
	this.shape_4.setTransform(34.375,210.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-11.1,-8.6,11.2,8.5).s().p("AmcE0IJasSIDfCrIpaMSg");
	this.shape_5.setTransform(60.475,220.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-11.3,-8.7,11.3,8.6).s().p("AmiE5IJjsfIDiCuIpjMeg");
	this.shape_6.setTransform(86.55,231);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-11.5,-8.8,11.4,8.7).s().p("AmnE8IJqsnIDkCwIppMng");
	this.shape_7.setTransform(105.2,238.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-11.5,-8.8,11.5,8.8).s().p("AmpE+IJtssIDmCxIptMsg");
	this.shape_8.setTransform(116.375,242.675);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.5,-11.1,14.4,11).s().p("AoWGPIMLv7IEiDeIsMP7g");
	this.shape_9.setTransform(120.0985,244.1444,0.7986,0.7986);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},351).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).wait(1));

	// ctaBtn
	this.instance_1 = new lib.ctaBtn();
	this.instance_1.setTransform(56,227.25,0.574,0.574,0,0,0,0.8,0.8);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(346).to({_off:false},0).to({alpha:1},5).wait(9));

	// txt_sureColor_F3070DTG
	this.instance_2 = new lib.txt_sureColor_f3070_endFrame();
	this.instance_2.setTransform(149.05,215.45);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(345).to({_off:false},0).to({y:204.45,alpha:1},6,cjs.Ease.quadOut).wait(9));

	// Layer_12
	this.instance_3 = new lib.stack_img();
	this.instance_3.setTransform(-59.45,163.1,0.6369,0.6369,0,0,0,0.1,0.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(342).to({_off:false},0).to({x:22.05},6,cjs.Ease.quadOut).wait(12));

	// printer_mc
	this.instance_4 = new lib.printer_mc();
	this.instance_4.setTransform(253,174.85,0.9245,0.9245,0,0,0,0.3,0.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(342).to({_off:false},0).to({x:192,alpha:1},6,cjs.Ease.quadOut).wait(12));

	// white_fade
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_10.setTransform(154.05,131.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.169)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_11.setTransform(154.05,131.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(255,255,255,0.333)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_12.setTransform(154.05,131.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(255,255,255,0.502)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_13.setTransform(154.05,131.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(255,255,255,0.667)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_14.setTransform(154.05,131.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(255,255,255,0.831)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_15.setTransform(154.05,131.075);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_16.setTransform(154.05,131.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_10}]},339).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).wait(15));

	// money
	this.instance_5 = new lib.shield_animation("synched",0,false);
	this.instance_5.setTransform(137.5,188.35,1.0065,1.0065,0,0,0,-1.9,42.7);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(284).to({_off:false},0).wait(76));

	// timer
	this.instance_6 = new lib.Timer_animation("synched",0,false);
	this.instance_6.setTransform(142.1,208.25,1.1921,1.1921,0,0,0,-1.9,42.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(220).to({_off:false},0).wait(59).to({mode:"single",startPosition:27},0).to({x:-127.9},5,cjs.Ease.quadOut).to({_off:true},1).wait(75));

	// CheckMark
	this.instance_7 = new lib.checkMark_animation("synched",0,false);
	this.instance_7.setTransform(142.1,208.25,1.1921,1.1921,0,0,0,-1.9,42.6);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(160).to({_off:false},0).wait(55).to({mode:"single",startPosition:24},0).to({x:-117.9,startPosition:29},5,cjs.Ease.quadOut).to({_off:true},1).wait(139));

	// txt_theMoreCustomers
	this.instance_8 = new lib.txt_moreCustomers();
	this.instance_8.setTransform(157.25,190.4,1,1,0,0,0,-2,6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(97).to({_off:false},0).to({y:179.35,alpha:1},8,cjs.Ease.quadOut).wait(49).to({alpha:0},5).to({_off:true},1).wait(200));

	// printer_mc
	this.instance_9 = new lib.printer_mc();
	this.instance_9.setTransform(205.35,239.15,1.3149,1.3149,0,0,0,0.1,0.1);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(94).to({_off:false},0).to({x:170.35,alpha:1},11,cjs.Ease.quadOut).wait(49).to({alpha:0},5).to({_off:true},1).wait(200));

	// white_fade
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(255,255,255,0)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_17.setTransform(154.05,131.075);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(255,255,255,0.082)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_18.setTransform(154.05,131.075);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(255,255,255,0.169)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_19.setTransform(154.05,131.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("rgba(255,255,255,0.251)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_20.setTransform(154.05,131.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("rgba(255,255,255,0.333)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_21.setTransform(154.05,131.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(255,255,255,0.416)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_22.setTransform(154.05,131.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(255,255,255,0.502)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_23.setTransform(154.05,131.075);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("rgba(255,255,255,0.584)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_24.setTransform(154.05,131.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(255,255,255,0.667)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_25.setTransform(154.05,131.075);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("rgba(255,255,255,0.749)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_26.setTransform(154.05,131.075);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("rgba(255,255,255,0.831)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_27.setTransform(154.05,131.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("rgba(255,255,255,0.918)").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_28.setTransform(154.05,131.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("A57W+MAAAgt7MAz4AAAMAAAAt7g");
	this.shape_29.setTransform(154.05,131.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_17}]},82).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).wait(266));

	// shirt_stack
	this.instance_10 = new lib.stack_animation("synched",0,false);
	this.instance_10.setTransform(229.05,557);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(39).to({_off:false},0).wait(26).to({startPosition:40},0).to({_off:true},29).wait(266));

	// shirt_stack
	this.instance_11 = new lib.stack_animation("synched",0,false);
	this.instance_11.setTransform(107.05,559);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(40).to({_off:false},0).wait(28).to({startPosition:41},0).to({_off:true},26).wait(266));

	// txt_theMoreSellable
	this.instance_12 = new lib.txt_moreSellable();
	this.instance_12.setTransform(139.5,86.35);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(39).to({_off:false},0).to({y:70.85,alpha:1},7,cjs.Ease.quadOut).to({_off:true},48).wait(266));

	// txt_sureColor_f10070
	this.instance_13 = new lib.txt_sureColor_f3070();
	this.instance_13.setTransform(149.05,222.95);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({y:208.95,alpha:1},10,cjs.Ease.quadOut).wait(23).to({alpha:0},5).to({_off:true},1).wait(321));

	// printer_mc
	this.instance_14 = new lib.printer_mc();
	this.instance_14.setTransform(214.2,183.6,1,1,0,0,0,0.1,0.1);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({x:149.2,alpha:1},10,cjs.Ease.quadOut).wait(23).to({alpha:0},5).to({_off:true},1).wait(321));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-88.9,31.6,487.20000000000005,391.9);
// library properties:
lib.properties = {
	id: '3E1D9D289AAA471FB8DD4F28FE5CF1AF',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Epson_Logo.png", id:"Epson_Logo"},
		{src:"moneySign.png", id:"moneySign"},
		{src:"printerFullFrame.jpg", id:"printerFullFrame"},
		{src:"shirtStack.png", id:"shirtStack"},
		{src:"timer.png", id:"timer"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3E1D9D289AAA471FB8DD4F28FE5CF1AF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;