(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.BG_image = function() {
	this.initialize(img.BG_image);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,50);


(lib.Epson_Logo = function() {
	this.initialize(img.Epson_Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,51);


(lib.projector_image = function() {
	this.initialize(img.projector_image);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,143);


(lib.shield_icon = function() {
	this.initialize(img.shield_icon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,108,126);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.BG_Image = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.BG_image();
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BG_Image, new cjs.Rectangle(-150,-300,320,50), null);


(lib.txt_Tolerant = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgmBsQgPgEgJgKQgJgIgEgMQgEgNAAgQIAAgHIAyAAIAAAGQAAAPAHAIQAIAJAOAAQAMAAAHgHQAIgFAAgOQAAgKgGgGQgGgFgIgDIgmgOQgXgIgLgOQgMgOAAgXQAAgNAEgMQAFgMAKgJQAJgJAPgEQAPgGAUAAQAmAAASAQQASAQAAAeIAAAIIgyAAQAAgQgFgJQgGgHgNAAQgJAAgIAGQgIAFAAAMQAAAIAFAGQAFAHAOAEIAgAMQAaAIALANQALAOAAAZQAAASgGAMQgGAMgLAJQgLAIgOAEQgPADgRAAQgXAAgPgEg");
	this.shape.setTransform(624.175,-98.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgECJQgKgCgFgHQgFgHgDgKQgCgLAAgRIAAh5IgcAAIAAgmIAcAAIAAg+IA2AAIAAA+IAhAAIAAAmIghAAIAABzQAAANAFAFQADAGANgBIAFAAIAHgBIAAAnIgSABIgSAAQgQAAgKgCg");
	this.shape_1.setTransform(609.75,-101.55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AAaBuIAAiTQAAgRgFgHQgGgGgMAAQgcAAAAAjIAACOIg4AAIAAjWIA1AAIAAAZIABAAQAJgQAOgHQANgHASAAQAaAAAPAOQAOAOAAAhIAACeg");
	this.shape_2.setTransform(594,-98.775);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgtBnQgRgKgIgRQgIgRgCgTIgBgpQAAgVADgUQADgUAJgPQAJgQAQgKQARgJAbAAQAYABAQAHQAPAIAJAOQAJAOADAUQADAVAAAYIAAAMIhsAAIAAARIABASIAFAQQADAIAFAEQAFAEAHAAQAOAAAHgKQAGgKACgVIAyAAQgCAmgSAUQgTAUgngBQgdABgRgKgAgLhGQgGADgDAHIgFANIgBAQIAAAIIA3AAIgBgWQgCgJgDgGQgCgIgGgDQgFgDgJAAQgHAAgFAEg");
	this.shape_3.setTransform(575.025,-98.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("ABOBuIAAiVQAAgOgFgHQgFgHgMAAQgNAAgIAJQgHAJAAATIAACMIg3AAIAAiVQAAgOgFgHQgFgHgLAAQgNAAgIAJQgIAJAAATIAACMIg3AAIAAjWIA1AAIAAAWIAAAAQALgPANgGQANgGASAAQATAAAMAIQANAJAEARIABAAQAGgRAPgJQAOgIAUAAQAbAAANAQQANARAAAfIAACbg");
	this.shape_4.setTransform(550.875,-98.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AAaBuIAAiTQAAgRgFgHQgGgGgMAAQgdAAAAAjIAACOIg3AAIAAjWIA1AAIAAAZIABAAQAJgQAOgHQANgHASAAQAaAAAPAOQANAOAAAhIAACeg");
	this.shape_5.setTransform(525.95,-98.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgoBqQgQgGgKgOQgKgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOAQgHQAQgHAXAAQAZgBAQAHQARAHAKAOQAJAPAEAVQAEAVAAAcQAAAbgFAVQgEAWgKAOQgKAOgQAHQgQAHgYAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIgBAeIABAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAHgSAAgoQAAgogHgRQgGgSgRAAQgJAAgGAGg");
	this.shape_6.setTransform(506.6,-98.5546);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("Ag3BuIAAjWIA1AAIAAAdIAAAAQAIgQALgJQANgJAQAAIAGAAIAEAAIAAA1IgIgBIgJAAIgOACQgHACgHAFQgFAEgEAIQgDAHABALIAACAg");
	this.shape_7.setTransform(491.45,-98.775);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgbCQIAAjWIA2AAIAADWgAgbhgIAAgvIA2AAIAAAvg");
	this.shape_8.setTransform(479.4,-102.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgeBrIg4jWIA6AAIAeCZIAAAAIAeiZIA3AAIg2DWg");
	this.shape_9.setTransform(465.975,-98.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AAaBuIAAiTQABgRgHgHQgFgGgNAAQgcAAAAAjIAACOIg3AAIAAjWIA2AAIAAAZIAAAAQAJgQANgHQAOgHASAAQAaAAAPAOQAOAOgBAhIAACeg");
	this.shape_10.setTransform(447.35,-98.775);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgtBnQgRgKgIgRQgIgRgCgTIgBgpQAAgVADgUQADgUAJgPQAJgQAQgKQARgJAbAAQAYABAQAHQAPAIAJAOQAJAOADAUQADAVAAAYIAAAMIhsAAIAAARIABASIAFAQQADAIAFAEQAFAEAHAAQAOAAAHgKQAGgKACgVIAyAAQgCAmgSAUQgTAUgngBQgdABgRgKgAgLhGQgGADgDAHIgFANIgBAQIAAAIIA3AAIgBgWQgCgJgDgGQgCgIgGgDQgFgDgJAAQgHAAgFAEg");
	this.shape_11.setTransform(428.375,-98.55);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhFCOIAAgpIAOACQAPgBAHgHQAGgJACgNIg9jWIA6AAIAfCTIABAAIAciTIA3AAIg0DIQgHAbgHAQQgHAQgJAKQgIAIgMAEQgNACgTAAg");
	this.shape_12.setTransform(401.125,-95.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("Ag3BuIAAjWIA1AAIAAAdIAAAAQAHgQAMgJQANgJAQAAIAGAAIAEAAIAAA1IgIgBIgIAAIgPACQgHACgHAFQgFAEgEAIQgCAHgBALIAACAg");
	this.shape_13.setTransform(386.7,-98.775);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgoBqQgQgGgLgOQgJgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOARgHQAQgHAWAAQAZgBAQAHQARAHAJAOQAKAPAEAVQAEAVAAAcQAAAbgEAVQgFAWgKAOQgKAOgRAHQgQAHgXAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIAAAeIAAAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAGgSAAgoQAAgogGgRQgGgSgRAAQgJAAgGAGg");
	this.shape_14.setTransform(369.85,-98.5546);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgECJQgKgCgFgHQgGgHgBgKQgDgLAAgRIAAh5IgcAAIAAgmIAcAAIAAg+IA2AAIAAA+IAgAAIAAAmIggAAIAABzQABANAEAFQADAGANgBIAFAAIAGgBIAAAnIgRABIgSAAQgQAAgKgCg");
	this.shape_15.setTransform(354.7,-101.55);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgjBrQgQgFgKgNQgKgNgFgVQgFgWAAggQAAghAGgWQAGgVAMgNQAMgNAQgFQAQgGASAAQAmABAUAVQATAXAAAmIg1AAIgBgPIgDgOQgDgGgFgEQgEgEgIAAQgKAAgGAFQgGAFgDAIQgEAJgBAOIgBAgIABAiQABAOAEAJQADAKAGAEQAFAEAIAAQAOAAAHgMQAGgMAAgbIA1AAQAAArgTAWQgTAXgsgBQgUABgPgGg");
	this.shape_16.setTransform(339.725,-98.55);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("Ag3BrQgKgEgGgJQgGgJgDgLQgDgLAAgLQAAgPAEgLQADgLAGgIQAHgHAKgFQAKgFAPgEIAegIQAMgEAFgFQAFgGAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAHQgGAIAAAMIAAAHIgyAAIAAgGQAAgSAGgMQAGgNAKgIQALgIAOgEQANgDAQAAQAYABAPAEQAPAFAIAIQAJAJADAMQADANAAAOIAABxIABAXIAGASIg1AAIgEgLIgDgMIgBAAQgJARgNAFQgMAGgTgBQgPABgKgGgAAMAHIgMAEQgPAEgHAIQgIAIAAAPQAAANAFAIQAFAJALAAIALgCQAGgCAFgEQAFgDADgHQADgHAAgIIAAgqg");
	this.shape_17.setTransform(320.975,-98.55);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgcCRIAAiwIgcAAIAAgmIAcAAIAAgYQAAgPADgJQAEgLAHgFQAIgGAKgDQALgCANAAIAdABIAAAmIgFAAIgFAAQgMABgFADQgEAEAAAJIAAATIAfAAIAAAmIgfAAIAACwg");
	this.shape_18.setTransform(305.95,-102.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgdCRIAAiwIgcAAIAAgmIAcAAIAAgYQABgPAEgJQAEgLAGgFQAIgGAKgDQALgCANAAIAdABIAAAmIgFAAIgFAAQgMABgFADQgEAEAAAJIAAATIAfAAIAAAmIgfAAIAACwg");
	this.shape_19.setTransform(285.05,-102.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgoBqQgRgGgJgOQgKgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOARgHQAPgHAXAAQAYgBARAHQAQAHALAOQAJAPAEAVQAEAVAAAcQAAAbgFAVQgEAWgKAOQgKAOgQAHQgRAHgXAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIAAAeIAAAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAHgSgBgoQABgogHgRQgGgSgRAAQgJAAgGAGg");
	this.shape_20.setTransform(269.7,-98.5546);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgECJQgKgCgFgHQgFgHgCgKQgCgLAAgRIAAh5IgcAAIAAgmIAcAAIAAg+IA2AAIAAA+IAfAAIAAAmIgfAAIAABzQAAANADAFQAEAGANgBIAGAAIAFgBIAAAnIgRABIgTAAQgQAAgJgCg");
	this.shape_21.setTransform(245.2,-101.55);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AAbBuIAAiTQAAgRgHgHQgFgGgNAAQgbAAAAAjIAACOIg3AAIAAjWIA1AAIAAAZIAAAAQAJgQANgHQAOgHASAAQAaAAAOAOQAOAOAAAhIAACeg");
	this.shape_22.setTransform(229.45,-98.775);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("Ag3BrQgKgEgGgJQgGgJgDgLQgDgLAAgLQAAgPAEgLQADgLAGgIQAHgHAKgFQAKgFAPgEIAegIQAMgEAFgFQAFgGAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAHQgGAIAAAMIAAAHIgyAAIAAgGQAAgSAGgMQAGgNAKgIQALgIAOgEQANgDAQAAQAYABAPAEQAPAFAIAIQAJAJADAMQADANAAAOIAABxIABAXIAGASIg1AAIgEgLIgDgMIgBAAQgJARgNAFQgMAGgTgBQgPABgKgGgAAMAHIgMAEQgPAEgHAIQgIAIAAAPQAAANAFAIQAFAJALAAIALgCQAGgCAFgEQAFgDADgHQADgHAAgIIAAgqg");
	this.shape_23.setTransform(209.975,-98.55);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("Ag4BuIAAjWIA1AAIAAAdIABAAQAHgQANgJQALgJASAAIAEAAIAGAAIAAA1IgJgBIgJAAIgOACQgHACgGAFQgGAEgEAIQgDAHAAALIAACAg");
	this.shape_24.setTransform(194.95,-98.775);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgtBnQgRgKgIgRQgIgRgCgTIgBgpQAAgVADgUQADgUAJgPQAJgQAQgKQARgJAbAAQAYABAQAHQAPAIAJAOQAJAOADAUQADAVAAAYIAAAMIhsAAIAAARIABASIAFAQQADAIAFAEQAFAEAHAAQAOAAAHgKQAGgKACgVIAyAAQgCAmgSAUQgTAUgngBQgdABgRgKgAgLhGQgGADgDAHIgFANIgBAQIAAAIIA3AAIgBgWQgCgJgDgGQgCgIgGgDQgFgDgJAAQgHAAgFAEg");
	this.shape_25.setTransform(178.475,-98.55);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgaCPIAAkdIA1AAIAAEdg");
	this.shape_26.setTransform(164.65,-102.025);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgoBqQgRgGgKgOQgJgOgEgWQgEgVAAgcQAAgbAFgVQAEgVAKgPQAKgOAQgHQARgHAWAAQAZgBAQAHQAQAHAKAOQAKAPAEAVQAEAVAAAcQAAAbgEAVQgFAWgKAOQgKAOgRAHQgPAHgYAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIgBAeIABAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAGgSAAgoQAAgogGgRQgGgSgRAAQgJAAgGAGg");
	this.shape_27.setTransform(150.5,-98.5546);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AgcCPIAAjuIg+AAIAAgvIC1AAIAAAvIg+AAIAADug");
	this.shape_28.setTransform(131.55,-102.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_Tolerant, new cjs.Rectangle(-74.6,-128.2,904,51.29999999999998), null);


(lib.txt_sureColor_f10070_endFrame = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AvPD6IAAgZIAJAAQAJABAFgGQAEgEAAgJIgliHIAkAAIAUBdIARhdIAjAAIggB+QgEARgFAKQgEALgGAFQgFAGgIACQgIABgMAAgAO0DMQgKgHgGgKQgEgLgCgMIgBgaQAAgNACgNQACgMAFgKQAGgKAKgFQALgGARAAQAQAAAJAFQAKAEAFAKQAGAIACANQACANAAAPIAAAIIhFAAIABAXIAEAKIAEAGQAEADAEAAQAKAAADgGQAEgHACgMIAfAAQgCAYgLAMQgLAMgZAAQgTAAgKgGgAPIBfIgEAGIgEAIIgBAKIAAAGIAkAAIgBgOQgBgGgCgEQgBgEgEgDQgEgCgFAAQgFABgEACgADZDOQgLgEgGgJQgGgJgCgNQgDgOAAgSQAAgQADgOQADgNAGgJQAGgJAKgFQALgEAOAAQAPgBAKAFQALAEAGAKQAGAIACANQADAOAAARQAAASgDAOQgCANgHAIQgGAJgKAFQgLAEgOAAQgQAAgJgEgADoBgQgDADgCAHQgCAGgBAIIAAAnQABAIACAHQACAGADADQADAEAHAAQALAAADgLQAEgLAAgaQAAgYgEgMQgDgKgLgBQgHABgDADgAgfDPQgHgDgDgGQgFgGgBgGQgCgHAAgHQAAgJACgIQACgGAEgFQAFgFAFgEIAQgFIATgFQAHgCADgEQADgEAAgGQAAgHgDgFQgEgEgJgBQgGAAgFAGQgEAEAAAIIAAAEIgfAAIAAgEQAAgMAEgHQAEgIAGgFQAGgFAJgCQAJgCAJAAQAPAAAJADQAKADAFAGQAFAFADAHQABAJAAAIIABBWIAEALIghAAIgFgOIgBAAQgFALgIADQgHADgMAAQgKAAgFgDgAAKCQIgHACQgKADgFAFQgEAFAAAKQAAAHADAFQADAGAHAAIAHgBQADgBADgDQADgCACgEQACgFAAgFIAAgbgAmcDOQgHgEgHgKIAAAAIAAAPIghAAIAAizIAiAAIAAA5IABAAQAFgIAIgEQAGgEAKAAQAWAAAJAQQAKASAAAkQAAAmgKAQQgJARgWAAQgLAAgGgEgAmlBrQgDALgBAVQABAXADALQADALALAAQAMAAAEgLQADgLAAgXQAAgVgDgLQgEgLgMAAQgLAAgDALgAo6DJQgJgJAAgUIAAhkIAjAAIAABdQAAALADAEQADAEAJAAQASAAAAgWIAAhaIAiAAIAACHIghAAIAAgQIAAAAQgGAKgJAFQgJAEgKAAQgRAAgJgJgAq4DFQgNgOAAgYIAAgIIAkAAIABARQABAFACAEQADADAFACQAEACAHAAQAJAAAGgFQAHgGAAgLQAAgGgCgEQgBgFgEgDQgEgEgGgDIgPgFQgMgFgJgEQgIgFgHgHQgFgGgEgIQgCgJAAgKQAAgbAOgNQAQgNAZAAQAMAAAKACQAKADAIAGQAHAGAFAJQADAKAAAMIAAAFIgiAAQAAgMgEgIQgFgGgLAAQgFAAgFABQgDACgDADIgDAGIgBAIQAAAJADAFQAEAGAMAFIAbALQALAFAGAFQAHAFADAFQAEAGACAHQABAHABAHQAAAdgRANQgRANgcAAQgfAAgNgNgAtTDMQgKgHgGgKQgEgLgCgMIgBgaQAAgNACgNQACgMAFgKQAGgKAKgFQALgGARAAQAQAAAJAFQAKAEAFAKQAGAIACANQACANAAAPIAAAIIhFAAIABAXIAEAKIAEAGQAEADAEAAQAKAAADgGQAEgHACgMIAfAAQgCAYgLAMQgLAMgZAAQgTAAgKgGgAs/BfIgEAGIgEAIIgBAKIAAAGIAkAAIgBgOQgBgGgCgEQgBgEgEgDQgEgCgFAAQgFABgEACgAN0DPQgGgCgDgEQgEgFgBgGQgBgHAAgKIAAhNIgSAAIAAgYIASAAIAAgmIAiAAIAAAmIAUAAIAAAYIgUAAIAABJQAAAIACADQADAEAHgBIAEAAIAEAAIAAAYIgWAAIgRAAgABdDPQgHgCgDgEQgEgFgBgGQgBgHAAgKIAAhNIgSAAIAAgYIASAAIAAgmIAjAAIAAAmIATAAIAAAYIgTAAIAABJQgBAIADADQACAEAIgBIAEAAIADAAIAAAYIgWAAIgQAAgAQQDPIAAiHIAiAAIAAASIAAAAQAGgJAGgGQAJgGAKAAIADAAIADABIAAAgIgKAAIgJABQgFACgEADQgDACgDAFQgCAFAAAGIAABRgAMoDPIAAhdQABgLgEgEQgEgDgHAAQgTAAABAWIAABZIgjAAIAAiHIAhAAIAAAQIABAAQAFgKAIgFQAKgEAKAAQARAAAJAJQAJAJAAAVIAABjgAKvDPIAAiHIAjAAIAACHgAJgDPIAAiHIAhAAIAAASIABAAQAFgJAHgGQAIgGAKAAIAEAAIADABIAAAgIgLAAIgJABQgEACgEADQgEACgDAFQgBAFAAAGIAABRgAHkDPIAAizIA/AAQAOABAKAEQAJAFAGAHQAGAIACAKQACAJABAKQAAAOgFAKQgEALgHAGQgIAGgKAEQgLACgNAAIgTAAIAABIgAIIBtIAQAAQALAAAHgGQAGgHABgOQgBgNgFgHQgGgHgNAAIgQAAgAF4DPIAAhdQAAgLgDgEQgEgDgIAAQgSAAAAAWIAABZIgiAAIAAiHIAgAAIAAAQIABAAQAFgKAJgFQAJgEALAAQAQAAAJAJQAKAJgBAVIAABjgACLDPIAAiHIAjAAIAACHgAhhDPIAAheQAAgJgDgEQgDgFgIABQgIgBgEAGQgGAFAAAMIAABZIgiAAIAAheQAAgJgDgEQgDgFgHABQgIgBgGAGQgEAFAAAMIAABZIgjAAIAAiHIAhAAIAAAPIABAAQAGgKAIgEQAIgEALAAQAMAAAJAFQAIAGADAKIAAAAQAEgKAJgGQAJgFAMAAQARAAAJALQAHAKAAATIAABigAkbDPIAAiHIAjAAIAACHgAlSDPIAAizIAjAAIAACzgAxWDPIAAizIA6AAQATAAAMAHQALAFAHAMQAGAMACAQQACAQAAATQAAAYgCARQgDARgHAMQgIALgLAFQgMAGgSAAgAwzC0IARAAQAJAAAFgDQAHgDACgIQAEgHABgNIAAg4QgBgMgDgHQgDgJgGgDQgGgEgKAAIgQAAgAKvA4IAAgdIAjAAIAAAdgACLA4IAAgdIAjAAIAAAdgAkbA4IAAgdIAjAAIAAAdgALjhFQgLgDgGgLQgHgKgCgQQgDgRAAgYIABgjQABgRAGgNQAFgNALgIQAMgIAUAAQAQAAALAEQAKAGAGAKQAHAKACAQQADARAAAXIgBAjQgBARgGAOQgFANgMAHQgLAIgTAAQgRAAgKgFgAL0jZQgEADgCAGQgDAHAAAMIAABKQAAAMADAFQADAGADADQADACAHAAQAGAAADgDQAEgDACgGQACgIABgLIAAhLQgBgLgCgGQgDgGgDgCQgDgDgGAAQgHAAgDAEgAH3hFQgKgDgGgLQgHgKgCgQQgDgRAAgYIABgjQABgRAGgNQAFgNALgIQAMgIATAAQARAAAKAEQALAGAGAKQAHAKACAQQADARAAAXIgBAjQgBARgGAOQgFANgLAHQgMAIgUAAQgQAAgLgFgAIJjZQgEADgCAGQgCAHgBAMIAABKQABAMACAFQADAGADADQADACAGAAQAHAAADgDQAEgDACgGQADgIAAgLIAAhLQAAgLgDgGQgDgGgDgCQgDgDgHAAQgGAAgDAEgAGChFQgLgDgGgLQgGgKgDgQQgCgRgBgYIABgjQACgRAFgNQAGgNALgIQALgIAUAAQAQAAALAEQAKAGAHAKQAGAKADAQQADARAAAXIgCAjQgBARgFAOQgGANgLAHQgMAIgTAAQgQAAgLgFgAGTjZQgDADgCAGQgDAHgBAMIAABKQABAMADAFQACAGADADQAEACAGAAQAGAAADgDQAFgDABgGQADgIAAgLIAAhLQAAgLgDgGQgCgGgEgCQgDgDgGAAQgGAAgEAEgAhhhEQgLgEgGgJQgGgJgCgOQgDgNAAgRQAAgRADgOQADgNAGgJQAGgJAKgEQALgFAOAAQAPAAAKAEQALAEAGAJQAGAJACANQADAOAAASQAAARgDANQgCANgHAKQgGAIgKAEQgLAFgOAAQgQAAgJgEgAhSiyQgDADgCAHQgCAGgBAJIAAAmQABAIACAHQACAGADAEQADADAHAAQALAAADgLQAEgLAAgZQAAgZgEgLQgDgLgLAAQgHgBgDAEgAkRhEQgKgEgGgJQgGgJgDgOQgCgNAAgRQAAgRADgOQACgNAHgJQAGgJAKgEQAKgFAPAAQAQAAAKAEQAKAEAGAJQAGAJADANQACAOAAASQAAARgDANQgDANgGAKQgGAIgKAEQgKAFgPAAQgPAAgLgEgAkBiyQgEADgCAHQgCAGAAAJIAAAmQAAAIACAHQACAGAEAEQAEADAGAAQAKAAAFgLQADgLAAgZQAAgZgDgLQgFgLgKAAQgGgBgEAEgAmRhHQgMgGgGgMQgHgNgCgRQgBgQAAgVQAAgUABgSQACgRAHgMQAGgMAMgHQALgHAVAAQATAAAMAGQALAGAFAKQAGAKABALIACAUIglAAQAAgSgEgKQgFgJgMAAQgHABgEADQgEAEgEAIQgBAIgBANIgBAgIABAhQABAMADAIQACAGAFADQAEACAGAAQAFAAAEgBQAEgCADgFQAEgFABgJQACgJAAgOIAkAAQAAAOgDANQgCANgGAKQgGAKgLAFQgLAGgSAAQgVAAgLgHgAoKhHQgLgGgEgKQgFgLgCgMIgBgZQAAgOACgMQACgNAGgKQAFgJALgGQAKgGASAAQAOAAAKAFQAJAEAGAJQAFAKADAMQACANAAAQIAAAHIhEAAIABAWIACAKIAGAIQACACAGAAQAIAAAEgGQAEgGACgOIAfAAQgCAYgLAMQgLANgZAAQgSAAgLgHgAn1izIgGAGIgCAJIgBAJIAAAFIAjAAIgCgNQAAgGgCgEQgCgEgDgCQgDgCgGAAQgFAAgDACgArehJQgJgIAAgVIAAhkIAjAAIAABeQgBAKAEAEQAEAEAHAAQATAAgBgXIAAhZIAjAAIAACHIghAAIAAgPIgBAAQgFAJgIAEQgKAFgKAAQgRAAgJgJgAtfhOQgNgNAAgZIAAgHIAkAAIABARQABAFADADQADAEAEACQAFACAHAAQAIAAAGgGQAIgEgBgMQAAgGgBgFQgCgEgEgDQgDgEgHgCIgOgHQgNgDgJgFQgIgFgGgGQgGgHgDgIQgDgIAAgMQAAgaAPgNQAPgNAZAAQANAAAKACQAKADAIAGQAGAGAFAJQAEAJAAANIAAAFIgiAAQgBgNgEgGQgFgIgKAAQgGABgEABQgEACgCADIgEAHIgBAHQAAAJAEAFQADAGAMAEIAbAMQALAFAGAFQAHAFAEAGQADAFACAGQACAIAAAIQAAAcgRANQgQANgdAAQgfAAgNgOgAJlhDQABgQAFgRQAEgTAGgRQAHgTAJgSQAKgTANgRIhLAAIAAggIBuAAIAAAcQgLAQgJARQgJASgGATQgHASgEAUQgEATgCATgAEZhDIAAh9IgjAAIAAgXIADAAQASAAAKgIQALgGADgPIAaAAIAACxgACHhDIAAiyIBkAAIAAAdIhAAAIAAAqIA8AAIAAAeIg8AAIAABNgAgDhDIAAiHIAgAAIAAASIABAAQAFgJAHgGQAIgGAKAAIAEAAIADAAIAAAiIgLgBIgJABQgEABgEADQgEADgDAFQgBAEAAAHIAABRgAixhDIAAiyIAjAAIAACygApthDIAAiHIAhAAIAAASIABAAQAFgJAIgGQAHgGALAAIADAAIADAAIAAAiIgLgBIgJABQgEABgEADQgEADgCAFQgCAEAAAHIAABRg");
	this.shape.setTransform(-12.5268,-191.1542,0.4873,0.4873);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070_endFrame, new cjs.Rectangle(-66.7,-203.3,108.4,24.400000000000006), null);


(lib.txt_sureColor_f10070 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("ApgCWIAAgQIAFABQAHAAACgDQACgDABgGIgYhTIAWAAIANA6IABAAIAKg6IAWAAIgVBOIgEAQQgDAHgEAEQgDADgFABIgMABgAJSB5QgGgEgEgGQgDgHAAgHIAAgQIAAgQQACgIADgGQAEgGAGgEQAHgDALAAQAIAAAGADQAHADADAFQADAGACAIIABARIAAAFIgrAAIABAOIACAGIADAEQACACADAAQAGAAACgEQADgEABgIIATAAQgBAPgHAHQgHAIgQAAQgLAAgHgEgAJfA2IgDAEIgCAFIgBAJIAXAAIgBgIQAAgEgCgCQgBgDgCgCIgGgBQgDAAgCACgACJB7QgHgDgEgFQgEgGgBgIQgBgJAAgKQAAgLABgIQACgJAEgFQAEgFAGgDQAHgDAIAAQAKgBAGADQAHADADAGQAEAFACAIQABAJAAALQAAAKgBAJQgCAIgEAFQgEAGgGACQgHADgJAAQgJAAgGgCgACTA2QgDADgCAEIgBAJIAAAXIABAKQACADADACQACADADAAQAHAAACgHQADgHAAgPQAAgQgDgHQgCgHgHAAQgDAAgCACgAgTB7QgDgCgCgDQgDgEgBgEIgBgIQAAgGABgFQABgEADgDQACgDAEgCIAKgDIALgEQAFgBABgCQADgCAAgEQAAgFgDgDQgCgDgFAAQgFAAgCADQgDADAAAFIAAACIgTAAIAAgCQAAgHADgFQACgFAEgCQAEgEAFgBIALgBQAJAAAGABQAGACADAEQAEADABAFIABAKIAAA1IACAHIgUAAIgBgEIgBgEQgFAGgEACQgEACgIAAQgFAAgFgCgAAHBUIgEACQgHABgCADQgDAEAAAFQAAAFACADQACAEAEAAIAEgBQABAAAAAAQABAAAAgBQABAAAAAAQABgBAAAAIADgEQACgDAAgDIAAgQgAkBB7QgEgDgDgFIgBAAIAAAIIgUAAIAAhuIAVAAIAAAjIAAAAQADgFAFgDQAFgCAFAAQAOAAAFAKQAHALAAAXQAAAXgHAKQgFAKgOAAQgGAAgFgCgAkGA9QgCAHAAAOQAAANACAHQACAHAHAAQAHAAACgHQACgHAAgNQAAgOgCgHQgCgHgHAAQgHAAgCAHgAljB4QgFgGAAgMIAAg+IAVAAIAAA6QAAAGADACQACADAEAAQAMAAAAgOIAAg3IAUAAIAABTIgUAAIAAgJIAAAAQgDAGgGACQgFADgHAAQgKAAgGgFgAmyB1QgIgJAAgPIAAgEIAXAAIAAAKQAAADACACIAFAEIAHABQAFAAAEgDQAEgEABgHIgBgGQgBgDgDgCQgCgCgEgCIgJgDIgNgGIgKgHQgDgEgBgFQgDgFAAgHQABgQAIgIQAKgJAQAAQAHAAAHACQAGACAFADQAEAEADAGQACAFAAAIIAAADIgVAAQAAgIgDgEQgDgEgHAAIgFABIgFADIgBAEIgBAFQgBAFADADQACAEAHADIASAHIAKAGIAHAGIADAIIAAAJQAAASgKAIQgKAIgSAAQgTAAgIgIgAoTB5QgHgEgDgGQgCgHgBgHIgBgQIABgQQABgIADgGQAFgGAGgEQAGgDALAAQAKAAAFADQAHADACAFQAEAGACAIIABARIAAAFIgrAAIABAOIACAGIADAEQACACADAAQAFAAADgEQACgEABgIIAUAAQgBAPgHAHQgHAIgQAAQgLAAgHgEgAoGA2IgDAEIgCAFIgBAJIAWAAIgBgIIgBgGQgBgDgCgCIgGgBQgDAAgCACgAIqB7QgEgBgCgDQgCgCAAgEIgBgLIAAgwIgLAAIAAgOIALAAIAAgYIAVAAIAAAYIANAAIAAAOIgNAAIAAAuQAAAEABADQACABAFAAIAFAAIAAAPIgPABIgKgBgAA7B7QgEgBgCgDQgCgCgBgEIgBgLIAAgwIgKAAIAAgOIAKAAIAAgYIAVAAIAAAYIANAAIAAAOIgNAAIAAAuQABAEABADQACABAEAAIAFAAIAAAPIgOABIgKgBgAKNB7IAAhTIAUAAIAAALQADgGAFgEQAFgDAGAAIAEAAIAAAVIgHgBIgFABQgDABgCACIgEAEQgBADgBAEIAAAygAH7B7IAAg5QAAgHgDgCQgBgDgFAAQgMAAAAAOIAAA3IgVAAIAAhTIAUAAIAAAKIABAAQADgGAGgDQAFgDAHAAQALAAAFAFQAFAGAAANIAAA9gAGvB7IAAhTIAWAAIAABTgAF+B7IAAhTIAUAAIAAALIAAAAQAEgGAEgEQAFgDAHAAIAEAAIAAAVIgHgBIgGABQgDABgCACIgEAEQgBADAAAEIAAAygAEwB7IAAhuIAoAAQAIAAAGADQAFACAEAFQAEAFACAGQABAFAAAHQAAAIgCAHQgEAGgEAEQgEAEgHACQgGACgIAAIgMAAIAAAsgAFHA/IAKAAQAGAAAEgEQAEgFAAgIQAAgIgDgFQgEgEgIAAIgJAAgADsB7IAAg5QAAgHgCgCQgCgDgFAAQgMAAAAAOIAAA3IgVAAIAAhTIAVAAIAAAKQAEgGAEgDQAGgDAHAAQAKAAAGAFQAFAGAAANIAAA9gABYB7IAAhTIAWAAIAABTgAg7B7IAAg6QAAgFgCgDQgCgDgEAAQgGAAgDAEQgCADAAAHIAAA3IgXAAIAAg6QAAgFgBgDQgCgDgFAAQgEAAgEAEQgDADAAAHIAAA3IgVAAIAAhTIAVAAIAAAIQAEgFAFgDQAFgCAHAAQAHAAAFADQAGAEABAGIAAAAQADgGAFgEQAFgDAJAAQAKAAAFAGQAFAHAAAMIAAA8gAivB7IAAhTIAVAAIAABTgAjSB7IAAhuIAVAAIAABugAq1B7IAAhuIAlAAQAMAAAGADQAIAEAEAHQAEAHABAKQABAKAAAMQAAAPgBALQgCALgEAHQgFAHgHADQgIADgLAAgAqeBrIAKAAQAFAAAEgCQADgCADgFQACgEABgIIAAgkQgBgHgCgFQgCgEgEgCQgDgDgHAAIgJAAgAGvAeIAAgTIAWAAIAAATgABYAeIAAgTIAWAAIAAATgAivAeIAAgTIAVAAIAAATgAJkglQgHgDgDgGQgFgGgBgLQgCgKAAgOIACgXQAAgKADgIQAEgIAGgFQAIgFAMAAQAKAAAGADQAHACAEAHQAEAGACALQABAKAAAOIgBAWQAAALgDAIQgEAIgHAFQgHAFgMAAQgKAAgHgDgAJviCQgDACgBAEIgCAMIAAAuQABAHABADQABAFADABIAGABQADAAADgBQACgCABgFQACgEABgHIAAgvIgDgKQgBgEgCgBIgGgBQgEAAgCABgAHUglQgGgDgEgGQgEgGgCgLQgCgKAAgOIACgXQAAgKAEgIQADgIAHgFQAHgFAMAAQALAAAGADQAGACAEAHQAFAGABALQACAKgBAOIAAAWQgBALgDAIQgEAIgHAFQgHAFgMAAQgKAAgHgDgAHgiCQgDACgCAEIgBAMIAAAuQAAAHABADQACAFADABIAFABQADAAADgBQADgCABgFQABgEABgHIAAgvIgCgKQgBgEgDgBIgGgBQgDAAgCABgAGMglQgGgDgEgGQgEgGgBgLQgCgKAAgOIABgXQABgKADgIQADgIAHgFQAHgFAMAAQAKAAAHADQAGACAEAHQAFAGABALQACAKgBAOIAAAWQgBALgDAIQgDAIgIAFQgGAFgNAAQgKAAgHgDgAGYiCQgDACgCAEIgCAMIAAAuQABAHABADQACAFADABIAFABQAEAAACgBQADgCABgFQABgEABgHIAAgvIgCgKQgBgEgDgBIgGgBQgDAAgCABgAAgglQgHgDgDgFQgEgFgCgJQgBgIAAgLQAAgLABgIQACgIAEgGQAEgFAGgDQAHgDAJAAQAJAAAGADQAHACAEAGQADAGACAIQABAIAAALQAAALgBAIQgCAIgEAGQgEAFgGADQgGADgJAAQgKAAgGgDgAAphpIgDAGQgCAEAAAFIAAAYQAAAFACAEQABAEACACQADACAEAAQAGAAADgHQACgGAAgQQAAgQgCgGQgDgHgGAAQgEAAgDACgAhKglQgGgDgEgFQgEgFgBgJQgBgIgBgLQABgLABgIQACgIADgGQAFgFAFgDQAHgDAJAAQAJAAAIADQAFACAEAGQAEAGABAIQACAIAAALQAAALgCAIQgBAIgEAGQgEAFgGADQgHADgJAAQgJAAgHgDgAhAhpQgDACAAAEIgCAJIAAAYIACAJQAAAEADACQADACADAAQAHAAACgHQADgGgBgQQABgQgDgGQgCgHgHAAQgDAAgDACgAiZgnQgHgEgEgHQgEgIgCgKIgBgYIABgXQACgLAEgHQAEgIAHgEQAIgEANAAQALAAAIAEQAGADAEAGQADAGABAHIAAANIgVAAQAAgMgDgFQgEgGgHAAQgEAAgDADQgCACgCAFIgCANIAAAUIAAAUIACAMQACAEADACQACACAEAAIAGgBQADgBABgEQACgDABgFQABgGAAgJIAWAAIgBARQgCAIgDAHQgEAFgGAEQgIAEgKAAQgNAAgIgFgAjjgmQgGgEgDgHQgEgGAAgIIAAgQIABgQQABgIADgGQADgGAHgDQAGgEALAAQAKAAAGADQAGADADAFQAEAGABAIIABASIAAAEIgqAAIAAAOIACAGIAEAFQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAQAGAAACgDQACgFABgHIAUAAQgBAOgHAIQgHAIgQAAQgLAAgHgEgAjVhqIgEAEIgCAFIAAAKIAVAAIAAgJIgCgGIgCgEIgHgBQgCAAgCABgAlkgoQgFgFgBgNIAAg+IAWAAIAAA6QAAAGACADQACADAFAAQAMAAAAgOIAAg4IAUAAIAABUIgTAAIAAgKIgBAAQgDAGgGADQgFADgHAAQgKAAgGgGgAmzgrQgIgIAAgPIAAgFIAXAAIAAAKIACAGQACACADABQADACAEAAQAFAAAEgEQAFgDAAgHIgBgHIgEgFIgGgDIgJgEQgIgDgFgDQgGgDgEgEQgDgDgCgFQgCgGAAgHQABgQAIgIQAKgIAQAAQAHAAAHACQAGABAFAEQAEADADAGQACAGAAAIIAAADIgVAAQAAgIgDgFQgDgEgHAAIgGABIgEADIgBAEIgBAFQAAAFACAEQACADAHADIASAIIAKAFIAHAHQACADABAFIAAAJQABASgLAHQgKAJgSAAQgSAAgJgJgAoUgmQgHgEgDgHQgCgGgBgIIgBgQIABgQQABgIADgGQAFgGAGgDQAGgEALAAQAJAAAGADQAGADADAFQAEAGACAIQABAIAAAKIAAAEIgrAAIABAOIACAGQABADACACQACABADAAQAFAAADgDQACgFABgHIAUAAQgBAOgHAIQgIAIgPAAQgMAAgGgEgAoHhqIgDAEIgCAFIgBAKIAWAAIgBgJIgBgGIgDgEIgGgBQgDAAgCABgAIXgkIAEgVQACgLAFgLQAEgMAFgLQAHgMAIgLIgvAAIAAgTIBEAAIAAARQgHAKgFALIgKAWIgGAYIgFAYgAFMgkIAAhOIgVAAIAAgPIABAAQAMAAAGgEQAGgEADgJIAQAAIAABugADzgkIAAhvIA+AAIAAASIgnAAIAAAaIAkAAIAAATIgkAAIAAAwgABZgkIAAhUIAVAAIAAALIABAAQACgGAGgDQAEgEAHAAIADAAIAAAVIgMAAIgFADQgCACgBADQgCACAAAFIAAAygAgPgkIAAhvIAUAAIAABvgAkfgkIAAhUIAVAAIAAALIABAAQADgGAEgDQAFgEAHAAIADAAIAAAVIgMAAIgFADQgCACgCADQgBACAAAFIAAAygApAgkIAAg6QAAgGgCgDQgDgCgEAAQgMAAAAANIAAA4IgUAAIAAhvIAUAAIAAAkIABAAQAGgLAOAAQALAAAFAGQAFAFAAANIAAA+gAqegkIAAhdIgZAAIAAgSIBHAAIAAASIgZAAIAABdgACdhUQgFgCgDgEQgEgDgDgFQgCgFABgGQgBgFACgFQADgFAEgEQADgDAFgCQAFgDAGAAQAFAAAFADQAFACADADQAEAEACAFQACAFAAAFQAAAGgCAFQgCAFgEADQgDAEgFACQgFACgFAAQgGAAgFgCgACgh+IgGAEIgEAGIgBAHIABAIIAEAGQACADAEABQAEABAEAAQADAAAEgBQAEgBACgDIAEgGQACgEgBgEQABgEgCgDIgEgGIgGgEQgEgCgDAAQgEAAgEACgACtheIgHgMIgCAAIAAAMIgHAAIAAgdIALAAQAGAAACACQADADAAAEQAAADgCACQgCACgDABIAHAMgACkhvIAEAAIADgBQABAAAAAAQAAAAABgBQAAAAAAgBQAAAAAAgBIAAgBIgCgBIgCgBIgFAAg");
	this.shape.setTransform(-11.35,-183.775);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070, new cjs.Rectangle(-80.9,-198.8,139.2,30.100000000000023), null);


(lib.txt_purposeBuilt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AhFCOIAAgpIAOABQAPAAAHgIQAGgHACgOIg9jWIA6AAIAfCUIABAAIAciUIA3AAIg0DHQgHAcgHAQQgHAQgJAJQgIAKgMACQgNADgTAAg");
	this.shape.setTransform(678.925,-95.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgECJQgKgCgFgHQgFgHgCgKQgCgLAAgRIAAh6IgdAAIAAglIAdAAIAAg+IA2AAIAAA+IAfAAIAAAlIgfAAIAAB0QAAAMADAGQAEAFANABIAGgBIAFAAIAAAmIgRAAIgTABQgPAAgKgCg");
	this.shape_1.setTransform(664.5,-101.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgaCRIAAjWIA2AAIAADWgAgahgIAAgwIA2AAIAAAwg");
	this.shape_2.setTransform(653.95,-102.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgaCPIAAkdIA2AAIAAEdg");
	this.shape_3.setTransform(644.6,-102.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgaCRIAAjWIA2AAIAADWgAgahgIAAgwIA2AAIAAAwg");
	this.shape_4.setTransform(635.25,-102.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgJCLQgLgGgJgQIgBAAIAAAYIg1AAIAAkdIA3AAIAABbIABAAQAIgNALgHQALgGAPAAQAjAAAPAaQAQAbAAA7QAAA8gQAaQgPAagjAAQgRAAgKgGgAgXgTQgFASAAAiQAAAjAFASQAGASARAAQASAAAGgSQAFgSAAgjQAAgigFgSQgGgSgSAAQgRAAgGASg");
	this.shape_5.setTransform(620.95,-102.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("Ag3BrQgKgEgGgKQgGgIgDgLQgDgLAAgLQAAgQAEgKQADgLAGgIQAHgHAKgFQAKgFAPgEIAegJQAMgDAFgGQAFgFAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAIQgGAHAAANIAAAGIgyAAIAAgFQAAgTAGgNQAGgNAKgHQALgIAOgDQANgDAQAAQAYgBAPAFQAPAFAIAJQAJAIADANQADAMAAAOIAABwIABAYIAGASIg1AAIgEgLIgDgLIgBAAQgJARgNAEQgMAFgTABQgPgBgKgFgAAMAIIgMADQgPAEgHAIQgIAJAAAOQAAAMAFAJQAFAJALAAIALgCQAGgBAFgEQAFgFADgGQADgGAAgJIAAgrg");
	this.shape_6.setTransform(601.225,-98.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgaCRIAAjWIA2AAIAADWgAgahgIAAgwIA2AAIAAAwg");
	this.shape_7.setTransform(587.2,-102.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgbCPIAAkdIA2AAIAAEdg");
	this.shape_8.setTransform(577.85,-102.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgQAQgIQARgJAbAAQAYgBAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABASIAFARQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgVIAyAAQgCAmgSAUQgTATgnABQgdAAgRgLgAgLhHQgGAEgDAGIgFAPIgBAOIAAAJIA3AAIgBgWQgCgJgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_9.setTransform(564.075,-98.95);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("Ag4BuIAAjWIA2AAIAAAdIAAAAQAHgQAMgJQAMgJARAAIAFAAIAGAAIAAA1IgJgBIgIAAIgPACQgHACgGAFQgGAEgEAIQgCAHgBALIAACAg");
	this.shape_10.setTransform(549.25,-99.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgbCPIAAkdIA3AAIAAEdg");
	this.shape_11.setTransform(527.85,-102.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("Ag3BrQgKgEgGgKQgGgIgDgLQgDgLAAgLQAAgQAEgKQADgLAGgIQAHgHAKgFQAKgFAPgEIAegJQAMgDAFgGQAFgFAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAIQgGAHAAANIAAAGIgyAAIAAgFQAAgTAGgNQAGgNAKgHQALgIAOgDQANgDAQAAQAYgBAPAFQAPAFAIAJQAJAIADANQADAMAAAOIAABwIABAYIAGASIg1AAIgEgLIgDgLIgBAAQgJARgNAEQgMAFgTABQgPgBgKgFgAAMAIIgMADQgPAEgHAIQgIAJAAAOQAAAMAFAJQAFAJALAAIALgCQAGgBAFgEQAFgFADgGQADgGAAgJIAAgrg");
	this.shape_12.setTransform(513.575,-98.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AAaBuIAAiTQAAgRgFgHQgGgGgMAAQgdAAAAAjIAACOIg3AAIAAjWIA1AAIAAAZIABAAQAJgQAOgHQANgHASAAQAaAAAPAOQANAOAAAhIAACeg");
	this.shape_13.setTransform(494.35,-99.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgoBqQgRgGgJgOQgKgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOARgHQAPgHAXAAQAZgBAQAHQARAHAKAOQAJAPAEAVQAEAVAAAcQAAAbgFAVQgEAWgKAOQgKAOgQAHQgRAHgXAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIgBAeIABAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAHgSAAgoQAAgogHgRQgGgSgRAAQgJAAgGAGg");
	this.shape_14.setTransform(475,-98.9546);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgaCRIAAjWIA1AAIAADWgAgahgIAAgwIA1AAIAAAwg");
	this.shape_15.setTransform(460.85,-102.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgDCJQgLgCgFgHQgFgHgDgKQgBgLAAgRIAAh6IgcAAIAAglIAcAAIAAg+IA2AAIAAA+IAfAAIAAAlIgfAAIAAB0QAAAMADAGQAEAFAMABIAHgBIAFAAIAAAmIgRAAIgTABQgQAAgIgCg");
	this.shape_16.setTransform(450.5,-101.95);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AhTCRIAAkbIA1AAIAAAWIAAAAQAKgPALgHQALgGAQAAQAjAAAPAbQAQAaAAA8QAAA7gQAaQgPAagjAAQgPAAgKgGQgLgFgJgNIgBAAIAABZgAgXhUQgFASAAAjQAAAiAFASQAGASARAAQASAAAFgSQAGgSAAgiQAAgjgGgSQgFgSgSAAQgRAAgGASg");
	this.shape_17.setTransform(435,-95.725);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgQAQgIQARgJAbAAQAYgBAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABASIAFARQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgVIAyAAQgCAmgSAUQgTATgnABQgdAAgRgLgAgLhHQgGAEgDAGIgFAPIgBAOIAAAJIA3AAIgBgWQgCgJgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_18.setTransform(415.775,-98.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgjBrQgQgEgKgOQgKgMgFgXQgFgVAAghQAAggAGgWQAGgWAMgNQAMgNAQgFQAQgEASAAQAmgBAUAWQATAXAAAnIg1AAIgBgQIgDgOQgDgGgFgEQgEgEgIAAQgKAAgGAFQgGAEgDAJQgEAKgBANIgBAgIABAiQABAOAEAKQADAIAGAFQAFAEAIAAQAOAAAHgMQAGgMAAgaIA1AAQAAAqgTAWQgTAWgsABQgUgBgPgFg");
	this.shape_19.setTransform(397.525,-98.95);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AAgBsIgghHIgfBHIg6AAIA7huIg4hoIA6AAIAcBAIAehAIA5AAIg4BoIA7Bug");
	this.shape_20.setTransform(379.275,-98.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgQAQgIQARgJAbAAQAYgBAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABASIAFARQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgVIAyAAQgCAmgSAUQgTATgnABQgdAAgRgLgAgLhHQgGAEgDAGIgFAPIgBAOIAAAJIA3AAIgBgWQgCgJgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_21.setTransform(361.075,-98.95);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("Ag3BuIAAjWIA0AAIAAAdIABAAQAIgQAMgJQAMgJAQAAIAGAAIAEAAIAAA1IgIgBIgJAAIgOACQgHACgHAFQgFAEgEAIQgDAHABALIAACAg");
	this.shape_22.setTransform(336.9,-99.175);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AgoBqQgRgGgKgOQgJgOgEgWQgEgVAAgcQAAgbAFgVQAEgVAKgPQAKgOAQgHQAQgHAXAAQAYgBARAHQAQAHAKAOQAKAPAEAVQAEAVAAAcQAAAbgEAVQgFAWgKAOQgKAOgRAHQgPAHgYAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIgBAeIABAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAGgSABgoQgBgogGgRQgGgSgRAAQgJAAgGAGg");
	this.shape_23.setTransform(320.05,-98.9546);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgdCSIAAixIgbAAIAAglIAbAAIAAgZQAAgPAEgKQAFgKAHgGQAHgGAKgCQALgCANgBIAeABIAAAoIgGAAIgFAAQgMgBgEAEQgGAEAAAKIAAATIAhAAIAAAlIghAAIAACxg");
	this.shape_24.setTransform(304.9,-102.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgDCJQgLgCgFgHQgFgHgDgKQgBgLAAgRIAAh6IgcAAIAAglIAcAAIAAg+IA2AAIAAA+IAfAAIAAAlIgfAAIAAB0QAAAMADAGQAEAFAMABIAHgBIAFAAIAAAmIgRAAIgTABQgQAAgIgCg");
	this.shape_25.setTransform(284,-101.95);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgaCPIAAkdIA2AAIAAEdg");
	this.shape_26.setTransform(273.45,-102.425);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgaCRIAAjWIA2AAIAADWgAgahgIAAgwIA2AAIAAAwg");
	this.shape_27.setTransform(264.1,-102.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AhCBgQgOgOgBggIAAifIA3AAIAACTQABARAFAHQAGAHANAAQAbAAAAgkIAAiOIA3AAIAADWIg1AAIAAgZIAAAAQgJAQgNAHQgOAHgSAAQgaAAgOgOg");
	this.shape_28.setTransform(249.55,-98.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AgJCLQgLgGgKgQIAAAAIAAAYIg1AAIAAkdIA3AAIAABbIABAAQAJgNALgHQAKgGAPAAQAjAAAPAaQAQAbAAA7QAAA8gQAaQgPAagjAAQgQAAgLgGgAgXgTQgFASAAAiQAAAjAFASQAGASARAAQASAAAFgSQAGgSAAgjQAAgigGgSQgFgSgSAAQgRAAgGASg");
	this.shape_29.setTransform(230.05,-102.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("Ag4AYIAAgvIBxAAIAAAvg");
	this.shape_30.setTransform(212.65,-99.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgQAQgIQARgJAbAAQAYgBAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABASIAFARQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgVIAyAAQgCAmgSAUQgTATgnABQgdAAgRgLgAgLhHQgGAEgDAGIgFAPIgBAOIAAAJIA3AAIgBgWQgCgJgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_31.setTransform(196.275,-98.95);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#353535").s().p("AgmBsQgPgFgJgIQgJgJgEgNQgEgNAAgPIAAgIIAyAAIAAAHQAAAPAHAJQAIAIAOAAQAMAAAHgGQAIgHAAgMQAAgLgGgFQgGgFgIgEIgmgOQgXgIgLgNQgMgPAAgXQAAgNAEgMQAFgMAKgIQAJgKAPgFQAPgEAUAAQAmAAASAPQASAQAAAdIAAAJIgyAAQAAgQgFgIQgGgIgNAAQgJAAgIAFQgIAHAAALQAAAIAFAHQAFAFAOAFIAgALQAaAJALAOQALAOAAAYQAAARgGANQgGANgLAIQgLAIgOAEQgPAEgRAAQgXAAgPgFg");
	this.shape_32.setTransform(178.375,-98.95);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#353535").s().p("AgoBqQgQgGgLgOQgJgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOARgHQAQgHAWAAQAZgBAQAHQARAHAJAOQAKAPAEAVQAEAVAAAcQAAAbgEAVQgFAWgKAOQgKAOgRAHQgQAHgXAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIAAAeIAAAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAGgSAAgoQAAgogGgRQgGgSgRAAQgJAAgGAGg");
	this.shape_33.setTransform(160.15,-98.9546);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#353535").s().p("AhTCRIAAkbIA1AAIAAAWIAAAAQAKgPALgHQALgGAQAAQAjAAAPAbQAQAaAAA8QAAA7gQAaQgPAagjAAQgPAAgKgGQgLgFgJgNIgBAAIAABZgAgXhUQgFASAAAjQAAAiAFASQAGASARAAQASAAAFgSQAGgSAAgiQAAgjgGgSQgFgSgSAAQgRAAgGASg");
	this.shape_34.setTransform(141.05,-95.725);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#353535").s().p("Ag3BuIAAjWIA1AAIAAAdIAAAAQAHgQAMgJQANgJAQAAIAGAAIAEAAIAAA1IgIgBIgIAAIgPACQgHACgHAFQgFAEgEAIQgCAHgBALIAACAg");
	this.shape_35.setTransform(125.25,-99.175);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#353535").s().p("AhDBgQgOgOAAggIAAifIA4AAIAACTQAAARAFAHQAGAHAMAAQAcAAAAgkIAAiOIA4AAIAADWIg1AAIAAgZIgBAAQgJAQgOAHQgNAHgSAAQgaAAgPgOg");
	this.shape_36.setTransform(108,-98.675);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#353535").s().p("AhZCPIAAkdIBkAAQAXAAAPAIQAPAHAIAMQAJAMAFAPQADAQAAAQQAAAWgGAQQgGARgNAJQgLAKgRAGQgRAFgTAAIgfAAIAABygAgfgNIAaAAQAQAAALgKQAKgKAAgWQAAgWgJgLQgKgLgUAAIgYAAg");
	this.shape_37.setTransform(88.45,-102.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_purposeBuilt, new cjs.Rectangle(-116.3,-128.6,997.8,51.3), null);


(lib.txt_industrialLevel = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgmBsQgPgEgJgKQgJgIgEgNQgEgMAAgQIAAgIIAyAAIAAAIQAAAOAHAIQAIAJAOAAQAMAAAHgGQAIgHAAgMQAAgLgGgFQgGgFgIgEIgmgOQgXgIgLgNQgMgPAAgXQAAgNAEgMQAFgMAKgIQAJgKAPgFQAPgEAUgBQAmABASAPQASAQAAAdIAAAJIgyAAQAAgRgFgIQgGgHgNAAQgJAAgIAFQgIAHAAALQAAAIAFAHQAFAFAOAFIAgALQAaAJALAOQALAOAAAYQAAARgGANQgGANgLAIQgLAIgOAEQgPADgRAAQgXABgPgFg");
	this.shape.setTransform(662.225,-105.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AhDB3QgQgaAAg8QAAg7AQgaQAQgbAiAAQAPAAALAGQALAHAIANIABAAIAAhbIA3AAIAAEcIg1AAIAAgWIgBAAQgIAPgMAGQgKAGgRAAQgiAAgQgagAgXgTQgFARAAAjQAAAjAFASQAGASARAAQASAAAFgSQAGgSAAgjQAAgjgGgRQgFgSgSAAQgRAAgGASg");
	this.shape_1.setTransform(643.35,-108.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgPAQgKQARgIAbgBQAYAAAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABATIAFAQQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgUIAyAAQgCAlgSAUQgTATgnAAQgdAAgRgKgAgLhHQgGAFgDAFIgFAPIgBAOIAAAJIA3AAIgBgVQgCgKgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_2.setTransform(624.625,-105.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgPAQgKQARgIAbgBQAYAAAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABATIAFAQQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgUIAyAAQgCAlgSAUQgTATgnAAQgdAAgRgKgAgLhHQgGAFgDAFIgFAPIgBAOIAAAJIA3AAIgBgVQgCgKgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_3.setTransform(606.375,-105.35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AhTCRIAAkbIA1AAIAAAWIAAAAQAKgPALgHQALgGAQAAQAiAAAQAbQAQAaAAA8QAAA7gQAaQgQAagiAAQgPAAgLgGQgLgFgIgNIgBAAIAABZgAgWhUQgGASAAAjQAAAiAGASQAFASARAAQASAAAGgSQAFgSAAgiQAAgjgFgSQgGgSgSAAQgRAAgFASg");
	this.shape_4.setTransform(587.6,-102.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgmBsQgPgEgJgKQgJgIgEgNQgEgMAAgQIAAgIIAyAAIAAAIQAAAOAHAIQAIAJAOAAQAMAAAHgGQAIgHAAgMQAAgLgGgFQgGgFgIgEIgmgOQgXgIgLgNQgMgPAAgXQAAgNAEgMQAFgMAKgIQAJgKAPgFQAPgEAUgBQAmABASAPQASAQAAAdIAAAJIgyAAQAAgRgFgIQgGgHgNAAQgJAAgIAFQgIAHAAALQAAAIAFAHQAFAFAOAFIAgALQAaAJALAOQALAOAAAYQAAARgGANQgGANgLAIQgLAIgOAEQgPADgRAAQgXABgPgFg");
	this.shape_5.setTransform(568.725,-105.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAbBuIAAiTQAAgRgHgHQgFgGgNAAQgbAAAAAjIAACOIg3AAIAAjWIA1AAIAAAZIAAAAQAJgQANgHQAOgHASAAQAaAAAOAOQAOAOABAhIAACeg");
	this.shape_6.setTransform(540.75,-105.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgoBqQgQgGgLgOQgJgOgEgWQgEgVAAgcQAAgbAFgVQAEgVAKgPQAKgOAQgHQARgHAWAAQAZgBAQAHQARAHAJAOQAKAPAEAVQAEAVAAAcQAAAbgEAVQgFAWgKAOQgKAOgRAHQgPAHgYAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIAAAeIAAAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAGgSAAgoQAAgogGgRQgGgSgRAAQgJAAgGAGg");
	this.shape_7.setTransform(521.4,-105.3546);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgaCQIAAjVIA2AAIAADVgAgahgIAAgwIA2AAIAAAwg");
	this.shape_8.setTransform(507.25,-109);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgECJQgKgCgFgHQgGgGgBgLQgDgLAAgQIAAh7IgcAAIAAglIAcAAIAAg+IA2AAIAAA+IAgAAIAAAlIggAAIAAB0QABAMAEAGQADAFANABIAFgBIAGAAIAAAmIgRAAIgTABQgPAAgKgCg");
	this.shape_9.setTransform(496.9,-108.35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgjBsQgQgFgKgNQgKgNgFgXQgFgVAAghQAAggAGgVQAGgXAMgNQAMgNAQgFQAQgEASgBQAmAAAUAXQATAWAAAnIg1AAIgBgQIgDgOQgDgGgFgEQgEgEgIAAQgKAAgGAFQgGAEgDAKQgEAJgBANIgBAgIABAiQABAOAEAJQADAKAGAEQAFAEAIAAQAOAAAHgMQAGgMAAgaIA1AAQAAAqgTAWQgTAWgsAAQgUAAgPgEg");
	this.shape_10.setTransform(481.925,-105.35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AhDBgQgOgOABggIAAifIA3AAIAACTQgBARAHAHQAFAHANAAQAcAAAAgkIAAiOIA3AAIAADWIg1AAIAAgZIgBAAQgJAQgOAHQgNAHgSAAQgaAAgPgOg");
	this.shape_11.setTransform(462.9,-105.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AhDB3QgQgaAAg8QAAg7AQgaQAQgbAiAAQAPAAALAGQAKAHAJANIABAAIAAhbIA3AAIAAEcIg1AAIAAgWIgBAAQgJAPgLAGQgLAGgQAAQgiAAgQgagAgXgTQgFARAAAjQAAAjAFASQAGASARAAQASAAAFgSQAGgSAAgjQAAgjgGgRQgFgSgSAAQgRAAgGASg");
	this.shape_12.setTransform(442.9,-108.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgoBqQgQgGgKgOQgKgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOARgHQAPgHAXAAQAZgBAQAHQARAHAKAOQAJAPAEAVQAEAVAAAcQAAAbgFAVQgEAWgKAOQgKAOgQAHQgQAHgYAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIgBAeIABAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAHgSAAgoQAAgogHgRQgGgSgRAAQgJAAgGAGg");
	this.shape_13.setTransform(423.8,-105.3546);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("Ag3BuIAAjWIA1AAIAAAdIAAAAQAIgQALgJQANgJAQAAIAGAAIAEAAIAAA1IgIgBIgJAAIgOACQgHACgHAFQgFAEgEAIQgCAHAAALIAACAg");
	this.shape_14.setTransform(408.65,-105.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AhTCRIAAkbIA1AAIAAAWIABAAQAJgPALgHQAKgGARAAQAiAAAQAbQAQAaAAA8QAAA7gQAaQgQAagiAAQgPAAgLgGQgLgFgIgNIgBAAIAABZgAgWhUQgGASAAAjQAAAiAGASQAFASARAAQASAAAGgSQAFgSAAgiQAAgjgFgSQgGgSgSAAQgRAAgFASg");
	this.shape_15.setTransform(391.65,-102.125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgaCPIAAkdIA2AAIAAEdg");
	this.shape_16.setTransform(367.5,-108.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgPAQgKQARgIAbgBQAYAAAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABATIAFAQQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgUIAyAAQgCAlgSAUQgTATgnAAQgdAAgRgKgAgLhHQgGAFgDAFIgFAPIgBAOIAAAJIA3AAIgBgVQgCgKgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_17.setTransform(353.725,-105.35);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgeBrIg4jVIA6AAIAeCZIAAAAIAeiZIA3AAIg2DVg");
	this.shape_18.setTransform(335.825,-105.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgPAQgKQARgIAbgBQAYAAAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABATIAFAQQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgUIAyAAQgCAlgSAUQgTATgnAAQgdAAgRgKgAgLhHQgGAFgDAFIgFAPIgBAOIAAAJIA3AAIgBgVQgCgKgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_19.setTransform(317.975,-105.35);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgaCPIAAkdIA1AAIAAEdg");
	this.shape_20.setTransform(304.15,-108.825);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("Ag3AYIAAgvIBvAAIAAAvg");
	this.shape_21.setTransform(292.2,-106.125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AgbCPIAAkdIA2AAIAAEdg");
	this.shape_22.setTransform(280.25,-108.825);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("Ag3BsQgKgFgGgKQgGgIgDgLQgDgLAAgLQAAgQAEgKQADgLAGgIQAHgHAKgFQAKgFAPgEIAegJQAMgDAFgGQAFgFAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAHQgGAIAAANIAAAGIgyAAIAAgFQAAgTAGgNQAGgNAKgHQALgIAOgDQANgDAQgBQAYAAAPAFQAPAFAIAIQAJAKADAMQADAMAAAOIAABwIABAYIAGASIg1AAIgEgLIgDgMIgBAAQgJASgNAFQgMAEgTAAQgPAAgKgEgAAMAIIgMADQgPAEgHAIQgIAIAAAPQAAAMAFAJQAFAJALAAIALgCQAGgBAFgEQAFgFADgGQADgHAAgIIAAgrg");
	this.shape_23.setTransform(265.975,-105.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgaCQIAAjVIA1AAIAADVgAgahgIAAgwIA1AAIAAAwg");
	this.shape_24.setTransform(251.95,-109);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("Ag3BuIAAjWIA1AAIAAAdIAAAAQAIgQAMgJQAMgJAQAAIAGAAIAEAAIAAA1IgIgBIgJAAIgOACQgHACgHAFQgFAEgEAIQgDAHABALIAACAg");
	this.shape_25.setTransform(241.6,-105.575);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgECJQgKgCgFgHQgFgGgCgLQgCgLAAgQIAAh7IgcAAIAAglIAcAAIAAg+IA2AAIAAA+IAfAAIAAAlIgfAAIAAB0QAAAMADAGQAEAFAMABIAHgBIAFAAIAAAmIgRAAIgTABQgQAAgJgCg");
	this.shape_26.setTransform(228.55,-108.35);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgmBsQgPgEgJgKQgJgIgEgNQgEgMAAgQIAAgIIAyAAIAAAIQAAAOAHAIQAIAJAOAAQAMAAAHgGQAIgHAAgMQAAgLgGgFQgGgFgIgEIgmgOQgXgIgLgNQgMgPAAgXQAAgNAEgMQAFgMAKgIQAJgKAPgFQAPgEAUgBQAmABASAPQASAQAAAdIAAAJIgyAAQAAgRgFgIQgGgHgNAAQgJAAgIAFQgIAHAAALQAAAIAFAHQAFAFAOAFIAgALQAaAJALAOQALAOAAAYQAAARgGANQgGANgLAIQgLAIgOAEQgPADgRAAQgXABgPgFg");
	this.shape_27.setTransform(213.925,-105.35);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AhCBgQgPgOAAggIAAifIA4AAIAACTQAAARAFAHQAGAHAMAAQAcAAAAgkIAAiOIA4AAIAADWIg1AAIAAgZIgBAAQgJAQgOAHQgNAHgSAAQgaAAgOgOg");
	this.shape_28.setTransform(195.3,-105.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AhDB3QgQgaAAg8QAAg7AQgaQAPgbAjAAQAPAAAKAGQALAHAJANIABAAIAAhbIA3AAIAAEcIg1AAIAAgWIAAAAQgJAPgMAGQgLAGgQAAQgjAAgPgagAgWgTQgGARAAAjQAAAjAGASQAFASARAAQASAAAGgSQAFgSAAgjQAAgjgFgRQgGgSgSAAQgRAAgFASg");
	this.shape_29.setTransform(175.3,-108.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AAbBuIAAiTQgBgRgFgHQgGgGgMAAQgcAAAAAjIAACOIg3AAIAAjWIA0AAIAAAZIABAAQAJgQANgHQAOgHASAAQAaAAAOAOQAPAOAAAhIAACeg");
	this.shape_30.setTransform(155.8,-105.575);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgcCPIAAkdIA5AAIAAEdg");
	this.shape_31.setTransform(140.925,-108.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_industrialLevel, new cjs.Rectangle(-40.6,-135,887.8000000000001,51.3), null);


(lib.printer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.projector_image();
	this.instance.setTransform(-393.95,-153.15,1.2254,1.2254);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_mc, new cjs.Rectangle(-393.9,-153.1,392.09999999999997,175.2), null);


(lib.Epson_Logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Epson_Logo();
	this.instance.setTransform(-90.7,-39.4,0.3973,0.3973);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Epson_Logo_1, new cjs.Rectangle(-90.7,-39.4,61.2,20.299999999999997), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape.setTransform(61.025,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_1.setTransform(47.475,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag1A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAfABAWAVQAXAXAAAeQAAAggXAVQgWAXgfAAQgfAAgWgXgAghghQgOAOAAATQAAAUAOAOQAOAPATAAQAUAAAOgPQAOgOAAgUQAAgTgOgOQgOgPgUAAQgTAAgOAPg");
	this.shape_2.setTransform(31.275,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBBMQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIglhSIgBAAIgMBOQAAADgEABIgSAAQgFgBABgEIAZiNQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAuBiIAAAAIAuhiQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAIADAAQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIAZCNQABAEgFABIgTAAQgDgBgBgDIgMhOIgBAAIglBSQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(13.1508,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BMQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIhUheIgBAAIAABZQAAAEgEABIgTAAQgEgBAAgEIAAiMQAAgDAEgBIADAAQABABAAAAQAAAAABAAQAAAAABAAQAAABABAAIBUBaIAAAAIAAhVQAAgFAFAAIATAAQAEAAAAAFIAACMQAAADgEABg");
	this.shape_4.setTransform(-10,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_5.setTransform(-25.075,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAwBLQgEgBgCgEIgLgWIg+AAIgKAWQgBAEgFABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIBBiNQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIACAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIBACNQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAVAYIgVgtIAAAAIgUAtIApAAg");
	this.shape_6.setTransform(-39.85,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_7.setTransform(-52.925,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBKQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAB1IA0AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_8.setTransform(-64.475,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_9.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,162.5,51.5), null);


(lib.shield_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon();
	this.instance.setTransform(-54,-63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shield_mc, new cjs.Rectangle(-54,-63,108,126), null);


(lib.gauge_needle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#06539E").s().p("AhYBiIgCgCIgDgDQgmgmAAg3QAAg2AmgnQAngmA2AAQA3AAAmAmIADADIACACQAiAmAAAyQAAA3gnAmQgmAng3AAQgyAAgmgig");
	this.shape.setTransform(-1.125,0.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_1.setTransform(33.9503,-32.507);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(6).p("AkNFzIKfryIgDgKQgJgDgBABQgBACsMKWQgKALgCASQgFAlAlAnQAeAfAmgMQAbgIAIgOg");
	this.shape_2.setTransform(34.1373,-32.507);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_3.setTransform(33.9503,-32.507);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.gauge_needle, new cjs.Rectangle(-16.3,-75.1,94.1,89.3), null);


(lib.checkMark_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(14).p("AgwgMQAgARAdAX");
	this.shape.setTransform(30.8836,-45.505);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(14).p("AiSgqQCCAUBnBQ");
	this.shape_1.setTransform(23.5006,-48.4675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(14).p("Ai6grQAZgCAbAAQC2AACLBq");
	this.shape_2.setTransform(13.5125,-48.805);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(14).p("AkvAjQB+hQCfAAQC2AACMBq");
	this.shape_3.setTransform(1.8625,-48.805);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(14).p("AmdDIQAnhtBYhYQCdibDcAAQC3AACMBr");
	this.shape_4.setTransform(-9.1375,-38.1235);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(14).p("AmLFqQghhYAAhlQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_5.setTransform(-10.6375,-17.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(14).p("AhnICQhcgnhMhMQididAAjdQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_6.setTransform(-10.6375,-2.0625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(14).p("AG9GQQiWCHjNAAQjdAAicidQidicAAjeQAAjdCdicQCcidDdAAQC3AACLBs");
	this.shape_7.setTransform(-9,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(14).p("AIWgeQABAPAAAPQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_8.setTransform(-0.025,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#06539E").ss(14).p("AHjjoQA0BqAAB+QAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_9.setTransform(-0.025,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#06539E").ss(14).p("AGdlTQB6CRAADCQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACLBs");
	this.shape_10.setTransform(-0.025,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#06539E").ss(14).p("AIXAAQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQDdAACdCdQCdCcAADdg");
	this.shape_11.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).wait(133));

	// Layer_3
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#06539E").ss(14,2,1).p("AgJgKIATAV");
	this.shape_12.setTransform(-19.3125,1.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#06539E").ss(14,2,1).p("AgkgmIBJBN");
	this.shape_13.setTransform(-16.6125,4.1875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#06539E").ss(14).p("AAZgYIgyAx");
	this.shape_14.setTransform(-4.4,11.7375);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#06539E").ss(14,1,1).p("AAXAYIgtgv");
	this.shape_15.setTransform(-9.275,11.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#06539E").ss(14,2,1).p("AgrgtIBXBb");
	this.shape_16.setTransform(-15.975,4.85);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#06539E").ss(14).p("ABEhCIiHCF");
	this.shape_17.setTransform(-0.125,7.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#06539E").ss(14).p("ACAh9Ij/D7");
	this.shape_18.setTransform(5.8875,1.6125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#06539E").ss(14).p("AChieIlBE9");
	this.shape_19.setTransform(9.175,-1.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#06539E").ss(14).p("ACtioIlZFR");
	this.shape_20.setTransform(10.3,-2.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#06539E").ss(14).p("ACoijIlPFH");
	this.shape_21.setTransform(9.8,-2.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_12}]},8).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_17}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_18}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_20}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_21}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).wait(129));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-60.4,152.7,152.6);


(lib.shield_icon_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// shield_mc (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_5 = new cjs.Graphics().p("Aobp1IQ3AAIAATrIw3AAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(5).to({graphics:mask_graphics_5,x:0,y:0}).wait(113));

	// shine
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(0.1).p("ADQjAIAAAdAjPDBIAAlm");
	this.shape.setTransform(-106.25,31.8125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGDHBMgiKAdaIpJH4g");
	this.shape_1.setTransform(-66.2,-76.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAOIAAgb");
	this.shape_2.setTransform(-84.35,15.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGDHBMgrTAlSg");
	this.shape_3.setTransform(-65.05,-75.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4qPKMArTglTIGDHBMgrTAlSg");
	this.shape_4.setTransform(-61.6,-71.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArUglTIGDHBMgrUAlSg");
	this.shape_5.setTransform(-55.8,-64.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAPIAAgd");
	this.shape_6.setTransform(-67,34);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGEHBMgrUAlSg");
	this.shape_7.setTransform(-47.7,-56.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAPIAAgc");
	this.shape_8.setTransform(-56.6,45.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(0.1).p("AjPDBIAAlmADQjAIAAAd");
	this.shape_9.setTransform(23.75,172.825);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4qPKMArTglTIGDHBMgiLAdbIpIH3g");
	this.shape_10.setTransform(63.8,64.725);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[{t:this.shape_3,p:{x:-65.05,y:-75.025}},{t:this.shape_2,p:{x:-84.35,y:15.2}}]},1).to({state:[{t:this.shape_4,p:{x:-61.6,y:-71.275}},{t:this.shape_2,p:{x:-80.9,y:18.95}}]},1).to({state:[{t:this.shape_5},{t:this.shape_2,p:{x:-75.1,y:25.25}}]},1).to({state:[{t:this.shape_7},{t:this.shape_6,p:{x:-67,y:34}}]},1).to({state:[{t:this.shape_4,p:{x:-37.3,y:-44.925}},{t:this.shape_8,p:{x:-56.6,y:45.3}}]},1).to({state:[{t:this.shape_4,p:{x:-24.6,y:-31.175}},{t:this.shape_8,p:{x:-43.9,y:59.05}}]},1).to({state:[{t:this.shape_3,p:{x:-9.6,y:-14.875}},{t:this.shape_8,p:{x:-28.9,y:75.35}}]},1).to({state:[{t:this.shape_3,p:{x:7.2,y:3.325}},{t:this.shape_6,p:{x:-12.1,y:93.55}}]},1).to({state:[{t:this.shape_4,p:{x:22.2,y:19.625}},{t:this.shape_8,p:{x:2.9,y:109.85}}]},1).to({state:[{t:this.shape_4,p:{x:34.9,y:33.375}},{t:this.shape_8,p:{x:15.6,y:123.6}}]},1).to({state:[{t:this.shape_3,p:{x:45.3,y:44.675}},{t:this.shape_8,p:{x:26,y:134.9}}]},1).to({state:[{t:this.shape_3,p:{x:53.4,y:53.425}},{t:this.shape_8,p:{x:34.1,y:143.65}}]},1).to({state:[{t:this.shape_4,p:{x:59.2,y:59.725}},{t:this.shape_8,p:{x:39.9,y:149.95}}]},1).to({state:[{t:this.shape_3,p:{x:62.65,y:63.475}},{t:this.shape_8,p:{x:43.35,y:153.7}}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).wait(98));

	// shield_mc
	this.instance = new lib.shield_mc();
	this.instance.setTransform(0,0,0.7857,0.7857);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.7921,scaleY:0.7921,alpha:0.121},0).wait(1).to({scaleX:0.8091,scaleY:0.8091,alpha:0.4415},0).wait(1).to({scaleX:0.8386,scaleY:0.8386,alpha:1},0).wait(1).to({scaleX:0.9035,scaleY:0.9035},0).wait(1).to({scaleX:0.977,scaleY:0.977},0).wait(1).to({scaleX:1.0343,scaleY:1.0343},0).wait(1).to({scaleX:1.0671,scaleY:1.0671},0).wait(1).to({scaleX:1.0794,scaleY:1.0794},0).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).wait(106));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.3,-68,116.6,136);


(lib.shield_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon_1("synched",0,false);
	this.instance.setTransform(4,-68.55);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(78).to({startPosition:78},0).to({_off:true},1).wait(281));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_Tolerant();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(70).to({_off:true},1).wait(281));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-74.6,-136.5,904,136);


(lib.gauge_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// gauge_needle
	this.instance = new lib.gauge_needle();
	this.instance.setTransform(0.15,-0.95,0.0838,0.0838,-132.9925,0,0,0.1,0.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({regX:-0.3,regY:0.5,scaleX:1,scaleY:1,rotation:-132.9917,y:-0.9},5).wait(1).to({regX:31.7,regY:-30.5,rotation:-133.4994,x:-44.25,y:-2.75},0).wait(1).to({rotation:-134.6077,x:-44.3,y:-1.95},0).wait(1).to({regX:-0.1,regY:0.5,scaleX:0.9999,scaleY:0.9999,rotation:-136.3899,x:0.15,y:-1.05},0).to({regX:-0.2,scaleX:1,scaleY:1,rotation:6.0191,x:0.25,y:-0.75},11,cjs.Ease.quadInOut).to({regY:0.4,rotation:-1.643,x:0.2,y:-0.85},3).to({regY:0.3,rotation:3.7245,x:0.3,y:-0.95},3).to({rotation:-1.0125,x:0.25},3).to({rotation:3.7245,x:0.3},3).to({rotation:-0.2544},3).to({rotation:3.7245},3).to({rotation:-1.4769,x:0.25},3).to({rotation:3.7245,x:0.3},3).wait(37));

	// gauge_dial
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(15).p("AgmDdQAAjJBVil");
	this.shape.setTransform(-76.2611,-24.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(15).p("AhcEyQAAk2DNji");
	this.shape_1.setTransform(-70.8283,-33.4625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(15).p("Aj1GiQAAlMDqjqQCJiKCsg4");
	this.shape_2.setTransform(-55.508,-44.6875);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(15).p("AoDG2QAAlMDqjqQDrjqFLAAQB6AABtAf");
	this.shape_3.setTransform(-28.5375,-46.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(15).p("AqrG2QAAlMDqjqQDrjqFLAAQFNAADqDq");
	this.shape_4.setTransform(-11.75,-46.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(15).p("AsFG2QAAlMDqjqQDrjqFLAAQFMAADrDqQB5B6A7CS");
	this.shape_5.setTransform(-2.7375,-46.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(15).p("AsbG2QAAlMDrjqQDrjqFKAAQFNAADqDqQC3C2ApDx");
	this.shape_6.setTransform(-0.5875,-46.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(15).p("AsgG2QAAlMDrjqQDrjqFKAAQFNAADqDqQDXDWATEo");
	this.shape_7.setTransform(-0.0875,-46.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(15).p("AshG2QAAlMDrjqQDrjqFLAAQFMAADrDqQDrDqAAFM");
	this.shape_8.setTransform(0,-46.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).wait(71));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-108.4,-117.8,196.10000000000002,182.7);


(lib.checkMark_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// checkMark_anim
	this.instance = new lib.checkMark_anim("synched",0,false);
	this.instance.setTransform(9.8,-51.75,1,1,0,0,0,15.8,15.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(74).to({startPosition:74},0).to({_off:true},1).wait(285));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_purposeBuilt();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(66).to({_off:true},1).wait(285));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.3,-128,997.8,152.7);


(lib.gauge_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_10
	this.instance = new lib.gauge_anim("synched",0,false);
	this.instance.setTransform(2.05,-64.8,1,1,0,0,0,0,-38.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(46).to({startPosition:20},0).wait(18).to({startPosition:20},0).wait(5).to({startPosition:25},0).to({_off:true},1).wait(290));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_industrialLevel();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(61).to({_off:true},1).wait(290));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-104.9,-143.8,952.1,146.20000000000002);


// stage content:
(lib.Epson_DyeSub_V4_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// Epson_Logo
	this.instance = new lib.Epson_Logo_1();
	this.instance.setTransform(80.75,40.55,0.8039,0.8039);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},8).wait(352));

	// ctaBtn_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_345 = new cjs.Graphics().p("AjHBFQgQAAAAgQIAAAAIAAhpQAAgQAQAAIAAAAIGPAAQAQAAAAAQIAAAAIAABpQAAAQgQAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(345).to({graphics:mask_graphics_345,x:136.8068,y:39.4065}).wait(15));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-4.8,-3.7,4.9,3.7).s().p("AiyCFIEElUIBhBLIkEFTg");
	this.shape_1.setTransform(107.85,32.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-4.8,-3.7,4.9,3.7).s().p("AiyCGIEElVIBhBKIkFFVg");
	this.shape_2.setTransform(108.45,32.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-4.8,-3.7,4.9,3.7).s().p("Ai0CHIEHlYIBiBLIkHFYg");
	this.shape_3.setTransform(110.2,33.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-4.9,-3.8,5,3.8).s().p("Ai3CJIELldIBkBMIkLFdg");
	this.shape_4.setTransform(113.175,33.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-5,-3.9,5.1,3.8).s().p("Ai7CMIERlkIBmBNIkRFkg");
	this.shape_5.setTransform(117.3,35.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-5.1,-4,5.2,3.9).s().p("Ai/CPIEXltIBoBQIkXFtg");
	this.shape_6.setTransform(122.6,36.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-5.3,-4.1,5.4,4.1).s().p("AjFCTIEgl3IBrBRIkgF4g");
	this.shape_7.setTransform(129.125,38.975);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-5.5,-4.2,5.6,4.2).s().p("AjLCYIEpmEIBuBUIkpGFg");
	this.shape_8.setTransform(136.8,41.375);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-5.7,-4.4,5.7,4.3).s().p("AjSCdIEzmRIByBXIkzGSg");
	this.shape_9.setTransform(144.475,43.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-5.9,-4.5,5.8,4.5).s().p("AjYChIE7mcIB2BaIk8Gcg");
	this.shape_10.setTransform(151,45.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-6,-4.6,6,4.6).s().p("AjcClIFBmlIB5BbIlCGmg");
	this.shape_11.setTransform(156.3,47.45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-6.1,-4.7,6.1,4.6).s().p("AjgCoIFHmsIB6BdIlHGsg");
	this.shape_12.setTransform(160.425,48.775);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-6.2,-4.7,6.1,4.7).s().p("AjjCqIFMmxIB7BeIlMGxg");
	this.shape_13.setTransform(163.4,49.675);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-6.2,-4.8,6.2,4.7).s().p("AjlCrIFOm0IB8BfIlNG0g");
	this.shape_14.setTransform(165.15,50.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-6.2,-4.8,6.2,4.7).s().p("AjlCrIFPm1IB8BfIlPG2g");
	this.shape_15.setTransform(165.75,50.425);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},345).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).wait(1));

	// ctaBtn
	this.instance_1 = new lib.ctaBtn();
	this.instance_1.setTransform(136.85,39.45,0.2659,0.2659,0,0,0,0.2,0.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(335).to({_off:false},0).to({alpha:1},10).wait(15));

	// txt_sureColor_f10070
	this.instance_2 = new lib.txt_sureColor_f10070_endFrame();
	this.instance_2.setTransform(149.05,196.95);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(330).to({_off:false},0).to({y:208.95,alpha:1},12,cjs.Ease.quadOut).wait(18));

	// printer_mc
	this.instance_3 = new lib.printer_mc();
	this.instance_3.setTransform(403.65,50.6,0.3583,0.3583,0,0,0,0.7,0.8);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(322).to({_off:false},0).to({x:353.65,alpha:1},13,cjs.Ease.quadOut).wait(25));

	// shield_animation
	this.instance_4 = new lib.shield_animation("synched",0,false);
	this.instance_4.setTransform(91.05,63.55,0.315,0.315,0,0,0,0,49.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(233).to({_off:false},0).wait(79).to({mode:"single",startPosition:49},0).to({y:14.05},9,cjs.Ease.quadInOut).to({_off:true},1).wait(38));

	// checkMark_animation
	this.instance_5 = new lib.checkMark_animation("synched",0,false);
	this.instance_5.setTransform(92.05,63.55,0.315,0.315,0,0,0,0.1,49.4);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(152).to({_off:false},0).wait(75).to({mode:"single",startPosition:49},0).to({y:13.55},8,cjs.Ease.quadInOut).to({_off:true},1).wait(124));

	// gauge_animation
	this.instance_6 = new lib.gauge_animation("synched",0,false);
	this.instance_6.setTransform(90.8,62.65,0.3149,0.3149,0,0,0,0,49.7);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(74).to({_off:false},0).wait(70).to({y:64.65,mode:"single",startPosition:49},0).to({y:17.65},10,cjs.Ease.quadInOut).to({_off:true},1).wait(205));

	// txt_sureColor_f10070
	this.instance_7 = new lib.txt_sureColor_f10070();
	this.instance_7.setTransform(149.05,193.95);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(16).to({_off:false},0).to({y:208.95,alpha:1},9,cjs.Ease.quadOut).wait(40).to({alpha:0},8).to({_off:true},1).wait(286));

	// printer_mc
	this.instance_8 = new lib.printer_mc();
	this.instance_8.setTransform(398.65,51.4,0.3587,0.3587,0,0,0,0.6,0.8);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:353.65,alpha:1},16,cjs.Ease.quadOut).wait(49).to({alpha:0},8).to({_off:true},1).wait(286));

	// White_mask
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(255,255,255,0)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_16.setTransform(112.05,332.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(255,255,255,0.047)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_17.setTransform(112.05,332.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(255,255,255,0.094)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_18.setTransform(112.05,332.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(255,255,255,0.137)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_19.setTransform(112.05,332.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("rgba(255,255,255,0.184)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_20.setTransform(112.05,332.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("rgba(255,255,255,0.231)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_21.setTransform(112.05,332.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(255,255,255,0.278)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_22.setTransform(112.05,332.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(255,255,255,0.322)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_23.setTransform(112.05,332.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("rgba(255,255,255,0.369)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_24.setTransform(112.05,332.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(255,255,255,0.416)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_25.setTransform(112.05,332.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("rgba(255,255,255,0.463)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_26.setTransform(112.05,332.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("rgba(255,255,255,0.506)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_27.setTransform(112.05,332.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("rgba(255,255,255,0.553)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_28.setTransform(112.05,332.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("rgba(255,255,255,0.6)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_29.setTransform(112.05,332.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("rgba(255,255,255,0.533)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_30.setTransform(112.05,332.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("rgba(255,255,255,0.467)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_31.setTransform(112.05,332.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("rgba(255,255,255,0.4)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_32.setTransform(112.05,332.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("rgba(255,255,255,0.333)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_33.setTransform(112.05,332.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("rgba(255,255,255,0.267)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_34.setTransform(112.05,332.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("rgba(255,255,255,0.2)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_35.setTransform(112.05,332.1);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("rgba(255,255,255,0.133)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_36.setTransform(112.05,332.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("rgba(255,255,255,0.067)").s().p("EgggA9RMAAAh6hMBBBAAAMAAAB6hg");
	this.shape_37.setTransform(112.05,332.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_16}]},69).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_29}]},230).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_16}]},1).to({state:[]},1).wait(38));

	// BG_Image
	this.instance_9 = new lib.BG_Image();
	this.instance_9.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(69).to({regX:0.1,regY:0.1,scaleX:2.1138,scaleY:2.1138,x:186.2,y:588.3},13,cjs.Ease.quadOut).wait(230).to({regX:0,regY:0,scaleX:1,scaleY:1,x:150,y:300},9,cjs.Ease.quadOut).wait(39));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(28.9,-35,516.5,759.2);
// library properties:
lib.properties = {
	id: '3E1D9D289AAA471FB8DD4F28FE5CF1AF',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"BG_image.jpg", id:"BG_image"},
		{src:"Epson_Logo.png", id:"Epson_Logo"},
		{src:"projector_image.png", id:"projector_image"},
		{src:"shield_icon.png", id:"shield_icon"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3E1D9D289AAA471FB8DD4F28FE5CF1AF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;