(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,40);


(lib.head_img = function() {
	this.initialize(img.head_img);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,125,103);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.will_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ADZBtIAAjaIA0AAIAACpIBgAAIAAAxgAArBtIAAjaIA0AAIAACpIBgAAIAAAxgAgoBtIAAjaIA0AAIAADagAivBtIgmiJIgmCJIg0AAIg9jaIA1AAIAjCHIAmiHIAyAAIAmCHIAiiHIA1AAIg9Dag");
	this.shape.setTransform(-36.475,10.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.will_txt, new cjs.Rectangle(-72.9,0,72.9,21.9), null);


(lib.we_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ABWBtIAAjaICXAAIAAAxIhjAAIAAAkIBjAAIAAAwIhjAAIAAAlIBjAAIAAAwgAgvBtIgmiJIgnCJIgzAAIg9jaIA1AAIAjCHIAmiHIAxAAIAnCHIAhiHIA0AAIg9Dag");
	this.shape.setTransform(-23.7,10.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.we_txt, new cjs.Rectangle(-47.4,0,47.4,21.9), null);


(lib.txt_yourGut = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape.setTransform(-8.825,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_1.setTransform(-17.325,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaA+QgKgFgIgJIATgPQAFAGAGADQAFAEAJgBQAFAAAEgBQAFgCADgEQAEgDACgEQACgFAAgFIAAgHQgFAHgIAEQgHADgIAAQgJABgIgEQgIgDgGgGQgGgHgEgJQgDgHAAgLQAAgLADgJQAEgIAGgHQAGgGAIgEQAIgCAJAAQAIgBAIAEQAHAEAFAGIAAgMIAXAAIAABUQAAAKgDAIQgEAJgGAGQgHAGgJAEQgJAEgKAAQgPAAgLgFgAgJgqQgEACgEADQgDAEgCAFQgCAEAAAGQAAAFACAFQACAEADAEQAEADAEACQAFACAEAAQAGAAAEgCQAFgCAEgDIAFgIQACgFAAgFQAAgGgCgEIgFgJQgEgDgFgCQgEgCgGAAQgEAAgFACg");
	this.shape_2.setTransform(-27.675,3.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAvIAAhbIAXAAIAAAOQADgIAGgEQAHgEAIAAIAJABIAHADIgIAXIgGgCIgHgBQgIAAgFAFQgFAFgBALIAAAwg");
	this.shape_3.setTransform(-39.45,1.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_4.setTransform(-48.175,1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTAsQgJgEgGgGQgHgHgDgJQgDgIAAgKQAAgJADgJQADgJAHgGQAGgGAJgEQAJgEAKAAQAKAAAJAEQAJAEAGAGQAHAGADAJQAFAJAAAJQAAAKgFAIQgDAJgHAHQgGAGgJAEQgJAEgKAAQgKAAgJgEgAgJgXQgFACgDAEQgDADgCAFQgCAEgBAFQABAFACAFQACAEADAEQADADAFACQAEACAFAAQAFAAAEgCQAGgCADgDIAFgIQACgFAAgFQAAgFgCgEQgCgFgDgDQgDgEgGgCQgEgCgFAAQgFAAgEACg");
	this.shape_5.setTransform(-58.25,1.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnA+QgHgDgFgDIANgTIAGAEQADABAEAAQAGAAAEgDQAEgDAEgIIABgEIglhXIAZAAIAXA7IAXg7IAYAAIgnBgQgEAJgEAGQgDAGgEADQgEAEgGACQgGABgHAAQgHAAgHgCg");
	this.shape_6.setTransform(-68.625,3.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgYAqQgKgGgGgLIAWgIQAGAMAPgBQAGAAAFgCQADgEAAgEQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgEIgHgBIgHgCIgMgDQgGgCgFgDQgEgBgDgGQgDgEAAgHQAAgGACgFQAEgGAEgDQAFgFAHgCQAHgCAHAAQAPAAAJAFQAKAFAGAKIgWAIQgDgEgDgDQgFgDgHABQgGgBgDADQgDACAAAFQAAADAFACIAPAFIALACQAHACAEAEQAFABADAGQADAEAAAHQAAAGgCAFQgDAGgEAEQgGAEgHADQgHADgLAAQgPAAgKgGg");
	this.shape_7.setTransform(-80.75,1.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLASQAHgFAEgFQADgFAAgFQgCAEgFAAQgFAAgDgDQgDgEAAgFQAAgHAEgEQAEgEAHAAQAHAAAFAFQAEAGAAAIQAAAJgGAIQgFAIgJAHg");
	this.shape_8.setTransform(-86.825,-3.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape_9.setTransform(-92.225,-0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjAoQgIgIAAgMQAAgOALgHQALgJATAAIAXAAIAAgBQAAgHgEgFQgGgEgKAAQgGAAgFADQgGADgDAGIgWgLQAHgJAKgGQALgGAOAAQAVAAALAKQALAKAAARIAAA4IgXAAIAAgOQgFAHgIAEQgIAFgLAAQgPAAgJgIgAgOAKQgFADABAFQgBAKAOAAIAIgBIAHgDIAHgGQADgDABgDIAAgFIgVAAQgJAAgFADg");
	this.shape_10.setTransform(-100.85,1.425);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AASBDIAAg0QABgKgFgFQgFgFgJAAQgHAAgGAFQgFAGgBALIAAAyIgXAAIAAiFIAXAAIAAA1QAFgFAHgEQAGgEAIABQAIgBAHADQAHADAEAFQAFAFADAGQACAGAAAJIAAA4g");
	this.shape_11.setTransform(-110.45,-0.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAaA+IgahXIgZBXIgYAAIgjh7IAZAAIAXBVIAahVIAWAAIAZBWIAYhWIAYAAIgkB7g");
	this.shape_12.setTransform(-123.975,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_yourGut, new cjs.Rectangle(-134.9,-13.1,269.9,26.299999999999997), null);


(lib.txt_tellingYou = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AgMA8QgFgEAAgHQAAgGAFgFQAEgEAGAAQAGAAAEAEQAEAFAAAGQAAAHgEAEQgEAEgGAAQgGAAgEgEgAgMAYIAAgCQAAgJACgGQADgHADgDIAGgHIAHgFIAFgFQACgDAAgFQAAgGgEgEQgFgFgHAAQgHAAgEAEQgFAEgCAGIgVgJQAFgLAKgHQAKgHAOAAQAJAAAHACQAIADAFAFQAFAEADAHQADAGAAAIQAAAIgDAFQgCAFgEADIgHAGIgIAFQgEADgCAFQgCAEAAAGIAAACg");
	this.shape.setTransform(-46.625,-0.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFB71B").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_1.setTransform(-55.975,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFB71B").s().p("AgTAsQgIgEgHgGQgHgHgDgJQgDgIgBgKQABgJADgJQADgJAHgGQAHgGAIgEQAKgEAJAAQAKAAAJAEQAJAEAGAGQAHAGAEAJQADAJAAAJQAAAKgDAIQgEAJgHAHQgGAGgJAEQgJAEgKAAQgJAAgKgEgAgJgXQgFACgDAEQgDADgDAFQgBAEAAAFQAAAFABAFQADAEADAEQADADAFACQAEACAFAAQAFAAAFgCQAFgCADgDIAFgIQACgFAAgFQAAgFgCgEQgCgFgDgDQgDgEgFgCQgFgCgFAAQgFAAgEACg");
	this.shape_2.setTransform(-66.05,1.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFB71B").s().p("AgnA+QgHgDgFgDIANgTIAGAEQADABAEAAQAGAAAEgDQAEgDAEgIIABgEIglhXIAZAAIAXA7IAXg7IAYAAIgnBgQgEAJgEAGQgDAGgEADQgEAEgGACQgGABgHAAQgHAAgHgCg");
	this.shape_3.setTransform(-76.425,3.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFB71B").s().p("AgaA+QgKgFgIgJIATgPQAFAGAGADQAFAEAJgBQAFAAAEgBQAFgCADgEQAEgDACgEQACgFAAgFIAAgHQgFAHgIAEQgHADgIAAQgJABgIgEQgIgDgGgGQgGgHgEgJQgDgHAAgLQAAgLADgJQAEgIAGgHQAGgGAIgEQAIgCAJAAQAIgBAIAEQAHAEAFAGIAAgMIAXAAIAABUQAAAKgDAIQgEAJgGAGQgHAGgJAEQgJAEgKAAQgPAAgLgFgAgJgqQgEACgEADQgDAEgCAFQgCAEAAAGQAAAFACAFQACAEADAEQAEADAEACQAFACAEAAQAGAAAEgCQAFgCAEgDIAFgIQACgFAAgFQAAgGgCgEIgFgJQgEgDgFgCQgEgCgGAAQgEAAgFACg");
	this.shape_4.setTransform(-89.625,3.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFB71B").s().p("AATAvIAAgzQAAgKgFgGQgFgFgIAAQgIAAgGAGQgFAFAAALIAAAyIgYAAIAAhbIAYAAIAAALQAEgGAHgDQAHgEAIAAQAQAAAJAKQAKAKAAASIAAA3g");
	this.shape_5.setTransform(-99.7,1.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFB71B").s().p("AgLBDIAAhcIAXAAIAABcgAgJgnQgFgFAAgGQAAgHAFgEQAEgEAFAAQAHAAAEAEQAEAEAAAHQAAAGgEAFQgEAEgHAAQgFAAgEgEg");
	this.shape_6.setTransform(-106.45,-0.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFB71B").s().p("AgLBDIAAiFIAXAAIAACFg");
	this.shape_7.setTransform(-110.075,-0.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFB71B").s().p("AgLBDIAAiFIAXAAIAACFg");
	this.shape_8.setTransform(-113.675,-0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFB71B").s().p("AgSAsQgJgEgHgGQgGgHgEgIQgDgJAAgKQAAgJAEgJQADgJAHgGQAGgGAJgEQAJgEAJAAQAKAAAJAEQAJADAGAGQAGAHAEAIQAEAJAAAKIAAAIIhIAAQACAJAHAFQAHAFAJAAQAIAAAGgDQAFgDAEgGIATALQgHAKgKAGQgKAGgPAAQgKAAgJgEgAAYgJQgCgJgGgFQgHgEgJAAQgIAAgGAFQgHAFgDAIIAwAAIAAAAg");
	this.shape_9.setTransform(-120.575,1.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFB71B").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape_10.setTransform(-129.025,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_tellingYou, new cjs.Rectangle(-134.9,-13.1,269.9,26.299999999999997), null);


(lib.to_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AArBoQgVgJgPgQQgOgPgIgUQgJgVAAgXQAAgWAJgVQAIgUAOgPQAPgQAVgJQAUgJAYAAQAXAAAVAJQAUAJAPAQQAPAPAKAUQAIAVAAAWQAAAXgIAVQgKAUgOAPQgPAQgVAJQgVAJgXAAQgYAAgUgJgAA/g4QgKAGgJAIQgHAIgFAMQgFALAAALQAAAMAFALQAFALAHAJQAJAIAKAFQALAFANAAQAMAAAMgFQAKgFAJgIQAHgJAFgLQAFgLAAgMQAAgLgFgLQgFgMgHgIQgJgIgKgGQgMgEgMAAQgNAAgLAEgAiKBuIAAiqIg8AAIAAgxICpAAIAAAxIg6AAIAACqg");
	this.shape.setTransform(-19.9,11.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.to_txt, new cjs.Rectangle(-39.8,0,39.8,22.5), null);


(lib.the_01_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AB+BtIAAjaICYAAIAAAxIhkAAIAAAkIBkAAIAAAwIhkAAIAAAlIBkAAIAAAwgAArBtIAAhTIhHAAIAABTIg0AAIAAjaIA0AAIAABTIBHAAIAAhTIA1AAIAADagAjZBtIAAipIg8AAIAAgxICqAAIAAAxIg7AAIAACpg");
	this.shape.setTransform(-27.75,10.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.the_01_txt, new cjs.Rectangle(-55.5,0,55.5,21.9), null);


(lib.talk_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AE5BtIgvhnIgdAlIAABCIg0AAIAAjaIA0AAIAABaIBGhaIA9AAIhABRIBBCJgAALBtIAAjaIA0AAIAACpIBgAAIAAAxgAg7BtIgLggIhTAAIgMAgIg0AAIBRjaIAxAAIBRDagAhWAfIgZhJIgaBJIAzAAgAk0BtIAAipIg8AAIAAgxICqAAIAAAxIg7AAIAACpg");
	this.shape.setTransform(-36.85,10.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.talk_txt, new cjs.Rectangle(-73.7,0,73.7,21.9), null);


(lib.someone_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ALcBpQgIgJAAgNQAAgNAIgIQAIgIANgBQAOABAIAIQAIAIAAANQAAANgIAJQgIAIgOAAQgNAAgIgIgABvBoQgVgJgPgPQgPgPgJgVQgIgVAAgXQAAgXAIgUQAJgUAPgQQAPgPAVgIQAUgJAYAAQAXAAAUAJQAVAIAPAPQAPAQAJAUQAJAUAAAXQAAAXgJAVQgJAVgPAPQgPAPgUAJQgVAIgXABQgYgBgUgIgACDg3QgLAEgIAJQgIAIgEALQgFAMAAALQAAAMAFAMQAEAKAIAJQAIAIALAFQALAFANAAQAMAAALgFQALgFAIgIQAIgJAFgKQAEgMAAgMQAAgLgEgMQgFgLgIgIQgIgJgLgEQgLgFgMAAQgNAAgLAFgAoxBoQgVgJgPgPQgPgPgJgVQgIgVAAgXQAAgXAIgUQAJgUAPgQQAPgPAVgIQAUgJAYAAQAXAAAUAJQAVAIAPAPQAPAQAJAUQAJAUAAAXQAAAXgJAVQgJAVgPAPQgPAPgUAJQgVAIgXABQgYgBgUgIgAodg3QgLAEgIAJQgIAIgEALQgFAMAAALQAAAMAFAMQAEAKAIAJQAIAIALAFQALAFANAAQAMAAALgFQALgFAIgIQAIgJAFgKQAEgMAAgMQAAgLgEgMQgFgLgIgIQgIgJgLgEQgLgFgMAAQgNAAgLAFgAr+BtQgPgDgLgGQgMgGgKgIQgJgIgIgJIAtgkQAKAPANAHQANAJATgBQANAAAHgFQAHgGAAgJQAAgFgDgEQgCgDgGgDIg7gRQgMgDgKgIQgKgGgGgLQgGgLAAgRQAAgPAGgMQAGgMAKgJQALgJAOgFQAPgFASAAQAPAAAMADQAMACALAFQAKAFAJAHIASARIgqAgQgIgLgLgIQgLgGgRAAQgNAAgGAGQgHAGAAAIQAAAEAEAEQADADAGACIA5APQAMAEALAIQAKAHAHAKQAGAMAAASQAAAPgGAOQgGANgLAJQgMAJgPAGQgPAGgSAAQgSAAgPgEgAH+BtIAAjZICXAAIAAAwIhjAAIAAAkIBjAAIAAAwIhjAAIAAAlIBjAAIAAAwgAGtBtIhWiIIAACIIgyAAIAAjZIA2AAIBTCCIAAiCIAxAAIAADZgAiDBtIAAjZICWAAIAAAwIhiAAIAAAkIBiAAIAAAwIhiAAIAAAlIBiAAIAAAwgAjVBtIAAiJIg6BMIg5hMIAACJIgzAAIAAjZIAxAAIA7BSIA9hSIAwAAIAADZgALcAnIAAgBQAAgQAEgMQAEgKAFgHQAFgHAGgEIAMgIIAJgJQADgEAAgHQAAgKgGgFQgGgGgLAAQgKAAgHAGQgIAHgCAIIgtgUQAJgVASgMQASgMAeAAQAQAAANAEQAOAFAJAJQAJAIAFAMQAGAMAAAOQAAAOgFAIQgEAJgGAGQgGAGgIAEIgNAIQgHAFgEAHQgEAHAAALIAAABg");
	this.shape.setTransform(-83.175,11.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.someone_txt, new cjs.Rectangle(-166.3,0,166.3,22.6), null);


(lib.should_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ABeBrQgQgGgMgMQgLgLgGgRQgHgQAAgVIAAiEIA1AAIAACEQAAASAKAKQAJAKARAAQAPAAAKgKQALgKgBgSIAAiEIA1AAIAACEQABAVgHAQQgGARgMALQgLAMgRAGQgQAGgUAAQgVAAgQgGgAiKBoQgUgJgPgPQgPgPgJgVQgJgUABgYQgBgWAJgVQAJgUAPgPQAPgQAUgIQAVgJAXAAQAYAAAUAJQAVAIAPAQQAOAPAJAUQAJAVAAAWQAAAYgJAUQgJAVgOAPQgPAPgVAJQgUAJgYAAQgXAAgVgJgAh1g3QgLAFgIAIQgIAIgFAMQgEALAAALQAAANAEALQAFALAIAIQAIAJAKAEQALAFANAAQANAAALgFQALgEAIgJQAIgIAEgLQAFgLAAgNQAAgLgFgLQgEgMgIgIQgIgIgLgFQgLgFgNAAQgMAAgLAFgAomBtQgOgDgMgGQgMgFgKgJQgJgIgIgJIAtgkQAKAPANAIQANAIATAAQANAAAIgGQAGgGAAgJQAAgFgDgEQgCgDgGgDIg6gRQgMgDgLgIQgKgGgGgLQgGgLAAgRQAAgOAGgMQAGgNAKgJQALgJAPgFQAPgFARAAQAPAAANADQALACALAFQALAFAIAIIASAQIgpAhQgJgMgLgHQgKgHgSAAQgNAAgGAGQgHAGAAAIQAAAFAEADQADADAGACIA5AQQAMAEALAHQALAHAGALQAHALgBASQABAQgHANQgGANgLAJQgMAKgOAFQgQAGgSAAQgSAAgPgEgAGoBuIAAjaIBNAAQAaAAAVAIQAVAJAPAOQAPAPAIAUQAIAUABAWQgBAYgIAUQgIAUgQAOQgPAPgVAIQgUAJgZAAgAHcA9IAYAAQAPAAALgFQALgEAIgJQAJgIAEgLQAEgLAAgNQAAgMgDgLQgFgLgIgIQgIgIgMgFQgLgFgQAAIgXAAgAD6BuIAAjaIA0AAIAACoIBgAAIAAAygAkcBuIAAhUIhIAAIAABUIg0AAIAAjaIA0AAIAABTIBIAAIAAhTIA1AAIAADag");
	this.shape.setTransform(-61.55,11.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.should_txt, new cjs.Rectangle(-123.1,0,123.1,22.6), null);


(lib.pass_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AFlBpQgIgJAAgNQAAgNAIgIQAJgIANgBQANABAIAIQAIAIAAANQAAANgIAJQgIAIgNAAQgOAAgIgIgADTBtQgOgDgMgGQgMgGgJgIQgKgIgHgJIAtgkQAJAPANAHQAOAJASgBQAOAAAHgFQAGgGAAgJQAAgFgCgEQgDgDgGgDIg6gRQgMgDgKgIQgKgGgHgLQgGgLAAgRQAAgPAGgMQAGgMALgJQAKgJAPgFQAPgFARAAQAPAAANADQAMACAKAFQALAFAJAHIASARIgqAgQgIgLgLgIQgLgGgRAAQgNAAgHAGQgGAGAAAIQAAAEADAEQADADAGACIA5APQANAEAKAIQALAHAGAKQAHAMAAASQAAAPgHAOQgGANgLAJQgLAJgPAGQgQAGgSAAQgSAAgPgEgAAWBtQgOgDgLgGQgMgGgJgIQgKgIgHgJIAsgkQAJAPANAHQAOAJASgBQAOAAAHgFQAGgGAAgJQAAgFgCgEQgDgDgGgDIg6gRQgMgDgJgIQgKgGgHgLQgGgLAAgRQAAgPAGgMQAGgMALgJQAJgJAPgFQAPgFARAAQAPAAANADQAMACAKAFQALAFAJAHIASARIgqAgQgIgLgLgIQgLgGgRAAQgNAAgHAGQgGAGAAAIQAAAEADAEQADADAGACIA5APQANAEAKAIQALAHAGAKQAHAMAAASQAAAPgHAOQgGANgLAJQgLAJgPAGQgQAGgSAAQgSAAgPgEgAheBtIgLggIhUAAIgMAgIg0AAIBRjZIAyAAIBRDZgAh5AfIgahJIgaBJIA0AAgAmXBtIAAjZIBXAAQATAAAQAGQAPAHALALQAMAKAGAPQAGAQAAAQQAAARgGANQgGAQgLALQgLALgQAHQgQAGgTAAIgjAAIAAA3gAljAGIAgAAQAPAAAKgIQAKgJAAgQQAAgPgKgKQgKgJgPAAIggAAg");
	this.shape.setTransform(-40.825,11.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.pass_txt, new cjs.Rectangle(-81.6,0,81.6,22.6), null);


(lib.deep_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ADHBtIAAjaIBXAAQAUABAPAGQAQAHALALQALAKAGAQQAGAOAAARQAAAQgGAPQgGAPgLALQgLALgQAHQgQAGgTAAIgjAAIAAA3gAD7AGIAhAAQAOAAAKgIQAKgKAAgPQAAgPgKgKQgKgJgOAAIghAAgAAWBtIAAjaICWAAIAAAxIhjAAIAAAkIBjAAIAAAwIhjAAIAAAlIBjAAIAAAwgAibBtIAAjaICXAAIAAAxIhjAAIAAAkIBjAAIAAAwIhjAAIAAAlIBjAAIAAAwgAlyBtIAAjaIBOAAQAZABAVAIQAVAJAPAOQAPAPAIATQAJAVgBAWQABAXgJAVQgJATgOAPQgQAOgUAJQgVAJgYgBgAk+A9IAYAAQAOgBAMgEQAMgEAIgJQAIgIAEgLQAFgLgBgNQAAgMgEgLQgEgLgIgJQgIgHgMgFQgMgFgPAAIgXAAg");
	this.shape.setTransform(-37.1,10.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.deep_txt, new cjs.Rectangle(-74.2,0,74.2,21.9), null);


(lib.cramping_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AKOBoQgWgKgPgPQgOgQgIgUQgIgUAAgXQAAgXAJgUQAIgVAOgPQAQgPAUgJQAVgIAYgBQAhAAAXAMQAWAMARAVIgtAeQgHgMgMgHQgNgGgRAAQgMAAgLAFQgMAEgIAJQgIAJgFALQgFALAAANQAAAOAEALQAFAMAJAJQAHAHAMAFQALAFAOAAQATAAAMgKQAOgIAFgQIg9AAIAAgwIB2AAIAAAYQAAAWgHATQgJAUgNAOQgOAPgUAJQgTAIgYABQgbAAgVgJgArlBoQgVgJgOgQQgPgPgIgUQgIgVAAgXQAAgXAJgUQAIgVAOgPQAQgPAUgJQAVgIAYgBQAQAAAPAEQAOAFANAHQAMAGAKALQALAJAGANIguAcQgHgOgMgIQgNgJgTAAQgNAAgKAEQgLAGgIAIQgIAIgFALQgEALAAAMQAAAMAEALQAFAMAIAHQAHAJALAFQALAEANAAQATABAOgLQANgKAHgPIAwAaQgGANgLAMQgKALgNAIQgMAJgQAEQgQAEgRABQgZAAgVgJgAH+BuIhViJIAACJIgzAAIAAjbIA3AAIBTCDIAAiDIAxAAIAADbgAEiBuIAAjbIA1AAIAADbgABcBuIAAjbIBXAAQATAAAPAHQAQAGALAMQAMALAFAPQAHAPgBAQQABARgHAOQgFAOgMAMQgKALgRAHQgPAHgTAAIgjAAIAAA3gACQAGIAgAAQAPAAAJgJQALgJgBgPQABgPgLgJQgJgKgPAAIggAAgAAKBuIAAiLIg5BOIg6hNIAACKIgzAAIAAjbIAyAAIA7BSIA8hSIAvAAIAADbgAjiBuIgLghIhUAAIgLAhIg1AAIBRjbIAyAAIBRDbgAj9AfIgahIIgZBIIAzAAgAnABuIgghDIgoAAIAABDIg1AAIAAjbIBeAAQAUABAPAFQAQAHAKAKQALAKAFANQAGAOAAAQQAAAVgKAQQgKAQgQALIApBPgAoIgDIAlAAQARAAAJgIQAHgJAAgMQAAgNgIgIQgIgIgRABIglAAg");
	this.shape.setTransform(-80.8,11.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.cramping_txt, new cjs.Rectangle(-161.6,0,161.6,22.5), null);


(lib.breath_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AI2BnQgIgIAAgNQAAgOAIgIQAIgIANAAQANAAAJAIQAIAIAAAOQAAANgIAIQgJAIgNAAQgNAAgIgIgAHhBsIAAhUIhIAAIAABUIg0AAIAAjaIA0AAIAABTIBIAAIAAhTIA0AAIAADagADeBsIAAiqIg7AAIAAgwICpAAIAAAwIg7AAIAACqgABjBsIgLghIhUAAIgLAhIg0AAIBQjaIAyAAIBRDagABIAdIgahIIgaBIIA0AAgAjfBsIAAjaICXAAIAAAwIhjAAIAAAkIBjAAIAAAwIhjAAIAAAlIBjAAIAAAxgAkqBsIgfhCIgpAAIAABCIg0AAIAAjaIBeAAQAUAAAPAGQAQAGAKAKQALAKAFAOQAFAOAAAPQAAAVgJAQQgKARgQAKIApBPgAlygEIAmAAQARAAAIgJQAIgIAAgNQAAgNgIgIQgIgHgRAAIgmAAgApoBsIAAjaIBXAAQAoAAATAQQAUAQAAAeQAAAPgFALQgGAKgLAHQANAHAHALQAHAMAAAQQAAAjgXAQQgWAQgnAAgAo1A+IAlAAQAPAAAHgGQAHgFAAgLQAAgKgGgFQgHgGgRAAIgkAAgAo1gaIAmAAQAOAAAGgFQAGgGAAgJQAAgJgGgFQgGgFgOAAIgmAAg");
	this.shape.setTransform(-61.675,11.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.breath_txt, new cjs.Rectangle(-123.3,0,123.3,22.3), null);


(lib.safeCare_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8A9A7").s().p("EgROA1vQoEitm8lHQm1lClFm5QlIm9i2oMIAAAAIgGgSIgBAAQg5iogoirIC2AAQCJIqEzHfQEuHYGxFeQG0FhIJC9QIcDEJBAAQJBAAIbjEQIJi9G1lhQGwleEunYQEznfCKoqIC2AAQglCdhAC9IgBAAIgLAhQi3IHlJG6QlEG1m1E/Qm5FDoCCsQoUCyoyAAQo2AAoVi0gEgRCAxlQn7i3mqlWQmmlTknnJQktnRiJoZIArAAQCIIQEpHKQElHBGgFNQGkFRH0C0QIFC6IpAAQIoAAIGi6QH0i0GklRQGglNEknBQEpnJCIoRIAsAAQiJIZktHRQkoHJmlFTQmqFWn8C3QoNC+oxAAQoxAAoOi+gEgBPAsbIhnkmIA7ABIBIDbIBRjYIA5ACIhwEigEACGAn3IDAgSIAEA1IiIANIAGBBICIgNIAEA1IiIANIAGBCICIgMIAFA1Ii/ASgEgHFAr4IAlkiIC+AaIgGA1IiIgTIgIBBICHATIgGA0IiIgSIgIBCICHASIgHA2gEAF+AneIA5gMIChCqIgmjDIA0gLIA4EeIg1AMIimiwIAnDKIg0ALgEgJJArdIgXhkIg+gPIgVBZIg2gNIBCkcIBxAbQAuAMAWAiQAVAhgKAqQgGAcgSATQgSATgaAHIAfB1gEgKTAo3IA3AOQAaAGAQgLQAQgKAFgVQAFgVgKgPQgLgQgZgGIg3gOgEALzAm5IhMAZIgPgyIDKhCIAPAxIhKAZIBHDlIg0ARgEgP0ApaIBdkUIBqAmQAtAQATAoQASAmgOArQgOAqgmASQgoAUgsgQIg1gTIgaBLgEgOWAnwIAzASQAXAIAUgJQATgJAHgWQAIgXgKgTQgJgUgXgIIgzgSgEAPxAoRQgRgHgHgRQgHgSAHgRQAHgRARgHQARgHARAHQARAHAHARQAHARgHASQgIARgQAHQgIAEgJAAQgJAAgIgEgEARNAj2IBjg3QApgXAqAMQAnAMAWAoQAUAngLApQgNArgpAXIgyAcIAlBGIgwAbgEATFAjuIgvAbIAzBfIAvgaQAVgMAHgVQAFgVgLgVQgLgVgUgGQgHgCgHAAQgOAAgOAIgEgR5AngQgQgIgGgRQgHgSAIgRQAIgRARgGQARgHAQAIQARAIAHASQAFARgHARQgIARgRAHQgIADgHAAQgKAAgJgFgEgXRAlhICRj7IClBkIgaAtIh2hHIggA5IB2BHIgbAuIh2hHIghA5IB2BHIgbAugEAUqAh4IBghDQAogcAoAHQAlAHAYAjQAQAXACAbQABAbgNAYIBqA3IgzAkIhYgxIg1AlIAyBMIgtAggEAWkAhjIgvAgIA1BQIAvghQAVgPAEgUQADgTgMgRQgMgSgSgDIgFAAQgQAAgSANgEgY/AkUIARhmIg0gnIg1BKIgtghICqjrIBcBGQAnAeAHAoQAGAngZAiQgQAXgXALQgZAKgagEIgRB4gEgZEAheIAtAiQAVAQAUgDQATgDALgRQANgSgEgSQgDgTgVgQIgtgigEAazAiQQg9gFgngvQgngvADg9QAFg+AugpQAtgpA9AFQA8AEAoAvQAoAwgFA9QgDA/gvAoQgpAlg1AAIgMgBgAaAezQgcAZgCAnQgCAmAZAeQAZAeAlADQAmAEAdgaQAdgaACgmQACgngZgdQgZgeglgDIgJgBQghAAgaAXgEgcXAhoIAVg0IhYhTIgwAbIgqgoIEQiNIAoAmIhxEigA8qfIIA8A5IAvhygAxbbFQntlNjyomIAuAAQDvIUHgFCQHtFKJNAAQJNAAHslKQHhlCDvoUIAtAAQjxImntFNQn5FWpfAAQpfAAn5lWgAcxcJIg3A8IglgkICRifIAlAkIg2A7ICrCkIglApgAv+ZnQnFkojsntIG3AAIAOAWIAbgWIAbAAIgyAdQAqA+AqA1ICXiQIA8AAIjNCXQAxA7AvAvIDckBIBNAAIkjEHQAwAyA4AuID8lnIBXAAIlMFtQA5AvA4AmID/nCIBbAAIlTHHQA9AoA7AhIDsoQIBdAAIlAIUQA8AhBCAcIDGpRIMFAAIDDJIQBBgcA7giIk6oKIBdAAIDnIFQA7giA6gnIlLm8IBbAAID5G1QA5gpA0grIlBlhIBWAAIDzFaQA5gxAsguIkWj7IBNAAIDQDzQAugvAug5Ii8iLIA7AAICICCQAngyAqg/IgcgRIAZAAIAJAIIAFgIIG3AAQjsHtnGEoQnREwopAAQopAAnSkwgAhSc+IAwABIAGjIIgvgBgACwZuIhFAIIAYDHIBFgIQArgFAZggQAZgggEgrQgGgrgegYQgagVgjAAIgQABgAlccdIAsAIIBqi3IgvgJIhGB8IgViNIgvgKgAqIYKQglARgPAoQgQAoARAnQAQAnAoAPQAnAQAlgSQAmgRAPgoQAPgogRgnQgQgngngPQgTgHgSAAQgUAAgUAJgAGuaTIAKAmIBfgcIgKgmgALqaaIArgTIhSi2IgoATQASAqgqAUIgBAAIATArIAEgDQAcgMABgagAuYVuQgnAKgYAlQgWAlAIAnQAIApAmAYQAaARAcAAQAbgBAYgOIgYgsQgdAUgcgSQgTgMgEgWQgEgWAMgTQAMgUAVgGQAVgFAUAMQAZARgCAhIAxAAQAAgbgMgXQgNgYgXgPQgbgRgcAAQgKAAgLACgAOTY2QAZgBAbgSQBLgyg5haQgbgqgbgJQgegKgdATQgaARgGAcQgGAcAQAZQAQAZAZAGQAYAGAWgPQAXgQgCgXQALAWgEAPQgDAOgTAMQgPALgRgBgAANYWQBBAABJgIIhjp1gAiHYQQBCAGBCAAIAGAAIglp8gAkaX8QBLAOA/AFIAWp+gAChYNQBKgJA/gNIifpngAmrXYQBBAUBHAOIBTp6gAE0X1QBJgQA9gTIjZpTgAo3WmQBGAdA9ASICQpvgAHDXPQBAgVBBgcIkPo6gA9yd3QgsgBgggkIgmgrIg5A2IgmgqIDSjFIBMBUQAgAkgBAsQgDArggAeQgeAcgmAAIgFAAgA+/cEIAkAoQARASAVACQAVABASgQQARgQAAgWQABgWgQgSIgkgpgAeFZdIB0icIAqAgIhTBvIAyAoIBUhvIApAhIhTBvIAzAoIBUhvIApAhIh1CcgACfadIAUgDQAagDASAOQARAOACAYQACAYgNARQgNARgZADIgVADgEgjlAZcIDlivIBzCdIgqAgIhShwIgzAnIBSBwIgpAgIhThwIgzAoIBSBwIgrAggApzacQgVgIgJgVQgHgVAHgVQAIgWAVgKQAUgJAUAIQAWAIAIAVQAJAVgJAWQgIAVgUAKQgKAFgLAAQgKAAgKgEgEgkoAXyIA1hYIgig4IhMAvIgegwID0iYIA8BmQAaAqgJAoQgJAmgkAXQgXAOgaABQgaAAgXgOIg8BpgEgjqAVHIAdAxQAOAXAUAFQASAEARgLQASgLAEgSQAEgTgOgXIgdgxgEAiMAXtQg2ghgOg7QgPg7Ahg3QAVgjAigTQAigTAmAAIAAA7Qg2gDgbAuQgUAiAJAlQAKAkAiAVQAgAVAkgIQAlgJAUghQAPgZgCgbQgCgZgPgWIAygeQAWAkAAAoQABArgWAmQghA4g7AOQgRAEgQAAQgnAAglgYgAOIXBQgKgCgHgJQgFgKACgKQACgLAJgGQAJgGAKADQAKACAGAJQAGAJgCAKQgCALgJAGQgGAEgIAAIgFAAgEglIATdQgpgPgTgsIgZg0IhGAiIgYg0IECh9IAwBoQAVAsgPAqQgOAogoATQgWALgWAAQgRAAgSgGgEglvARXIAYAyQAKAWAUAIQATAHAWgKQAUgKAIgUQAHgVgLgXIgXgxgEAj5ARoIgiBKIgugXIBbjFIAtAXIghBIIDVBnIgYAygEA1NAS3ITPllIABAAIAAxUINfAAIrHLYILHLhgEhV7AS3ILHrhIrHrYINtAAIAARUIABAAITPFlgEA2HANSIQkAAIyDFPQA3ikAoirgEhGeANSIQQAAQAoCsA1CcgEhHvAMzIAA5DMCPtAAAIAAZDgAi/DqIAAFVIC1AAIAAocgAOtlXQiMCQABDWQAADWCGCPQCKCTDaAAQCUAAB3hOQBvhIBAh/IjTh0QgfBKg5ApQg+AthSAAQhwAAhJhPQhHhOAAhyQAAhzBJhOQBJhQBwAAQBNAAA7AmQA4AlAgBDIDJiCQhBhvhuhBQhzhCiIAAQjTAAiMCRgEhC4AFDQBLBcBdAwQBuA4CVAAQCeAABohbQBnhbAAiLQAAiNhnhJQhBgviQgiQh2gdgWgJQg2gXAAgoQAAgkAcgYQAfgbA3AAQBFAAA0AeQAvAdAjA4IC3iSQhRhahSgoQhcgth+AAQiZAAhiBXQhjBVAACBQAACHBjBHQBBAwCJAgQB4AdAeAPQAwAXAAAtQAAAqgeAYQggAag5AAQhOAAg8glQg4gigshEgEA3uAH5IKVAAIAAjZImxAAIAAinIGxAAIAAjZImxAAIAAihIGxAAIAAjaIqVAAgEAwXADTICHEmID8AAIiyliQBIgsAphMQAqhLAAhdQgBiRhdheQhihjioAAImcAAIAAPUIDkAAIAAkmgEAkeAFnIAyCSIDoAAIlivUIjdAAIlhPUIDnAAIAxiSgA4NH5IKWAAIAAjZImxAAIAAinIGxAAIAAjZImxAAIAAihIGxAAIAAjaIqWAAgEglMAH5IDkAAIAAlxIGuAAIAAjXImuAAIAAivIGuAAIAAjdIqSAAgEgrcAFnIAyCSIDoAAIlivUIjdAAIlhPUIDmAAIAyiSgAAQGSIC1AAIAAioIi1jHgADbDYIFDAAIAAi8In/AAgAlwDYICdAAIC7i8IlYAAgAAfADIFXAAIABi8IicAAgAoXADIH/AAIi/i8IlAAAgAAQgDIC1jIIAAlVIi1AAgAi/jLIC1DIIAAlvIi1AAgAf3CbIBxlJIBwFJgEgwDACbIBxlJIBxFJgEAtjAAAIAAkFICnAAQBHAAAlAiQAjAiAAA9QAAA6gjAjQgmAnhGAAgEAy6gMvQiFowkynmQktndmyljQm2lmoNjAQogjHpEAAQpFAAogDHQoNDAm2FmQmyFjktHdQkxHmiFIwIi1AAQCGpUFBoGQE7n+HLl7QHQl+IsjNQJAjVJpAAQJpAAJADVQItDNHOF+QHMF7E7H+QFBIGCGJUgEAxBgMvQiEoXkonPQkjnImhlSQmmlVn4i3QoKi9osAAQotAAoJC9Qn4C3mmFVQmiFSkiHIQkoHPiFIXIgrAAQCFofErnXQEnnPGnlYQGslbH/i6QISjAI1AAQI1AAISDAQH/C6GrFbQGoFYEmHPQEsHXCEIfgAcVsvQjqoinmlLQnylUpWAAQpXAAnyFUQnlFLjrIiIgtAAQDso0HzlXQH+lgJpAAQJoAAH/FgQHzFXDrI0gAUHsvIgWgkIguAkIgiAAIBLgsQgqhBgogyIinCfIhBAAIDiinQgrg1gyg1IjrERIhRAAIE2kYQgzg2g0grIkJF5IhaAAIFcl/QgugphCguIkKHWIhfAAIFinbQg2gnhCglIj0InIu4AAIj5otQhDAmg2AmIFmHhIhfAAIkOndQg7Aqg3AuIFiGFIhZAAIkPmAQg2AtgzA1IE8EeIhQAAIjykYQgxA0gtA4IDoCsIhAAAIiuilQgwA9gkA4IBRAwIggAAIg1gpIgZApImyAAQDnn7HKkyQHXk6I0AAQIzAAHXE6QHMEyDmH7gArK1fIFRIuIjQptQhBAchAAjgAGBszIFMonQg8ghhDgegApC2hIEZJNIiTp+QhEAVhCAcgAEwtWIEWpGQhGgeg+gUgAm03VIDgJnIhWqKQhBANhJAWgADctvIDepiQhLgXg+gNgAkj35ICkJ5IgWqOQhHAHhHAOgACGuBICjp2QhHgPhFgHgAiN4PIBlKGIAoqMIgDgBQhEAAhGAHgAAvuJIBmqFQhNgHhBAAgAM12VQAJAWAcASQBMAyA4haQAagqgDgeQgEgggcgTQgagRgbAFQgbAGgQAZQgQAaAFAZQAEAZAXAOQAXAQAUgLQgPASgPADQgOADgSgMQgPgKgHgRgAuL4tQgbABgYAPQgkAXgJApQgJApAXAlQAXAkAmAKQAoAKAlgYQAagQAMgbQAMgZgDgdIgwAEQAEAjgcASQgTANgVgGQgUgGgNgTQgLgUADgWQAEgWAUgMQAagSAcARIAUgtQgUgKgWAAIgGAAgAKW3bIArATIBQi2IgpgTQgTApgrgTIgBgBIgTArIAGACQAcANASgQgAqO64QgnAPgQAnQgRAnAPAnQAPAoAlASQAmARAngQQAogPAQgnQAQgmgPgpQgPgngmgRQgUgKgUAAQgSAAgSAIgAmy8AIBsC3IAsgJIAjjSIgwAJIgVCOIhFh8gABl5qIBFAIQAsAFAfgaQAggZAEgqQAFgrgZgfQgZgggtgFIhFgIgAGj6CIBgAcIALgmIhggcgAhd8xIAIDIIAvgCIgIjIgEgoZgSlIBNiYQAihFAtgVQAtgVA0AcQAyAaAEA0QAxghA3AdQA5AeAJA2QAIA0gjBHIhMCXgEgjPgTsQgQAIgPAcIgfA/IBIAnIAhhBQAZgzgkgUQgKgFgKAAQgGAAgGADgEgl9gUXIghBCIBCAjIAihDQAXgsgjgSQgJgFgIAAQgVAAgRAhgEAiZgQeQghgYgXguQgihEAVg/QAUg+A+ggQA8ggA/AVQA/AVAhBAQAgBAgVA/QgTA/g+AgIgdAQIhqjTQgRASgDAXQgDAWANAZQAUAoAmADIgFBdQgpgHgdgXgEAj1gT/IA8B5QAfgigXgtQgKgVgSgLQgSgKgUAAIgCAAgAfr04QgfgvAIglQAJgpA3gnIBag9IgeguIBHgxIAdAuIA4gnIBhA0IhjBEIArBBIhHAxIgrhBIhUA6QgTANgEAMQgCAKAHALQAIAMAPADIglBQQgrgQgZgngEghHgVRQgngdgCgxQgBgxAmg1IApg8IgBgBQgRgMgRAFQgRAEgPAVQgYAjAQAiIhXA0QgZhYA3hQQApg6AxgMQAygMAwAkICbBxIg1BOIgigZQAIAagFAfQgGAfgVAdQgcAoglAJQgKADgJAAQgcAAgZgTgEggNgXoQgeArAZASQATAPAWgfQAOgUABgbQABgagMgSIgFgDgAOj3AQgJgGgCgKQgDgKAGgKQAGgJAKgCQAKgCAJAFQAJAGACALQACAKgFAJQgGAJgKADIgFAAQgHAAgHgEgA8j4vQAbAAAQgRQAagbgTgpIgFgMIkth5IBHhNICuBKIhUirIBFhKICVFIQAdA/gDApQgDAogkAnQgmApg3AJgAc447IDyjIIA+BPIjyDJgAqA4mQgTgKgJgVQgHgWAIgUQAIgVAVgJQAVgIAUAKQAUAJAIAWQAIAVgIAVQgJAVgUAIQgKAEgKAAQgLAAgLgFgAbP6xIB9h/QAogoghgjQgQgQgTACQgWABgVAWIh5B7IhEhFIFClIIBDBGIh+CAQAzgHAlAlQAkAmgBAtQgBAvgpApIiKCNgACt6PIgWgCIANhvIAUADQAaADAOARQANARgCAYQgDAYgRAOQgOALgTAAIgJAAgEAiDgbUQgYgDgQgUQgQgVADgXQACgXAUgQQAVgRAWACQAXADAQAUQAQAUgCAYQgDAXgUARQgRAOgTAAIgGAAgEgdvgiRIBIhAIEpFfIhJBAgAWd/HIBakKIjSC1IhSg7ICQmlIBUA7IhdEBIDPiwIBOA5IhXEFIDKi0IBSA7IlQEdgA3Y/LQhAgMgng4Qgng5AMhDQALhDA8grQA6gpBCALQBCAMAnA4QAnA5gMBDQgMBDg8ArQgtAggzAAQgOAAgPgCgEgXfgitQgXARgGAeQgFAdARAYQAQAZAdAFQAdAFAXgRQAYgRAGgdQAFgdgRgZQgRgYgdgGIgMgBQgVAAgTANgEgVEgl7IBVgtIAUAoQgDg5A5geQAXgMAegCIAPBoQgVgEgYANQg3AdAfA/IBHCKIhVAugEAPdgjUIgbhBQgqARgfAAQgdABgjgOQg4gXgWgtQgVgrATgyQAOgjAigUQAagPAsgIQgKgfAAgXQABgXALgbQAQgqArgQQAsgRAuASQAvATAUAqQAVAqgSArQgMAfgdATQgXAOglAKIAWA2IBZgxIBqArIidBWIBECdgEANKgmSQgHAPAHAPQAGANAQAHQAOAGAOgBQAPgBATgJIghhOQgrAKgIAXgEAPDgpWQgLAEgEAMQgFAMAAALQACAMAGATQAqgJAJgXQAFgMgFgKQgGgLgLgEQgGgDgGAAQgFAAgFACgEgNBgknQgtgHgsgdIA+heQA3AuA/gVQAYgHAKgPQAJgOgFgSQgGgTgXgDQgPgCg2AEQg9AFgigLQgzgRgRg4QgRg2AfgxQAegyBAgVQA1gRAsAGQAoAGAtAbIg6BWQgsgng3ASQgYAHgJAQQgJAOAFAPQAFARAZACQAMABA0gEQBBgFAhALQA0ARATA6QASA7gfA0QggA0hCAVQgsAOgnAAQgRAAgQgCgEAIAgltQg1gKgUghQgXgjANhDIAVhtIg0gKIAPhWIA1ALIANhEIBogiIgXB4IBLAPIgRBWIhKgPIgUBnQgEAWAFALQAFAJANADQANADAOgJIAdBSQgcAOgfAAQgNAAgPgDgEgH8gmfQg1gngLhFQgMhGAng3QAng3BFgLQA2gJAuAVQAsAVAaAsIhUAyQgKgUgTgKQgTgJgVAEQgcAEgRAZQgQAYAEAeQAFAcAYASQAXARAbgEQAWgEAOgPQAOgPAFgWIBhAVQgOAzghAgQglAkg2AJQgRADgPAAQgyAAgqgfgEAELgmVQg2gFgXgfQgaghAFhEIAKhuIg1gEIAHhXIA2AEIAGhEIBkgtIgLB6IBMAHIgIBXIhMgHIgJBoQgBAXAGAKQAFAJAOABQANACANgLIAlBPQghAVgmAAIgOAAgEgC+gnPQgwgugChFQgChGAugxQAtgyBJgCQBGgCAxAvQAxAuACBFQACBGgtAxQguAyhIACIgGAAQhEAAgvgtgEgBLgqQQgeABgTAVQgUAWAAAeQACAeAVAVQAVAUAdgBQAdgBAUgWQAUgVgBgeQAAgegWgVQgUgTgdAAIgBAAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.safeCare_Logo, new cjs.Rectangle(-550,-361.8,1100,723.7), null);


(lib.BSWH_Logo_Dallas = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqdFPQgIgMAAgOQAAgPAIgKQALgLAPAAQAJAAAKAHQAJAHAAALIgPAAQABgGgFgCQgCgDgHAAQgHAAgEADQgEADgBAFQgDAFAAAGQAAAJAEAIQAGAHAJAAQAHAAAEgFQAEgDABgHIgPAAIAAgMIAcAAIAAAlIgKAAIAAgIQgIAKgLgBQgPABgLgKgArEFXIgdgtIAAAtIgOAAIAAhEIAOAAIAdAtIABAAIAAgtIANAAIAABEgAsSFXIAAhEIAOAAIAABEgAtIFXIgVhEIAPAAIAOAwIAQgwIAPAAIgWBEgAt4FXIgCgDIAAgOQAAgEgEgEQgCgCgGAAIgOAAIAAAbIgQAAIAAhEIAlAAQAHABAHAEQAHAGAAAHQAAANgLAFQAIAEABALIACALIAAADIABADgAuUEyIAPAAQALAAAAgJQAAgKgLAAIgPAAgAvHFXIAAhEIANAAIAABEgA2pDvIAAiyIBghnIAAEZgA00DBQgFgGAAgHQAAgHAFgFQAEgFAIAAQAHAAAFAFQAFAFAAAHQAAAHgFAGQgFAEgHAAQgIAAgEgEgA0xCrQgFADAAAGQAAAGAFAEQADAEAGAAQAGAAAEgEQADgEAAgGQAAgGgDgDQgEgFgGAAQgGAAgDAFgA0jC+IgFgIIgFAAIAAAIIgBAAIAAgTIAHAAQAGAAAAAEQAAAEgFADIAGAIgA0tCzIAFAAQAFAAAAgEQAAgCgFAAIgFAAgAjLCQQgNgQAAgVQAAgVANgNQAOgQAUAAQAPAAAOAJQALAKAAAQIgTAAQgBgHgFgFQgHgFgIAAQgJAAgFAFQgGAFgDAHQgCAIAAAHQgBAOAIAJQAFAJANAAQAKAAAFgEQAFgHACgKIATAAQAAASgLAKQgMAKgSAAQgUAAgOgMgAowCQQgNgOAAgXQAAgVANgNQAMgQAWAAQAQAAAMAJQAKAKACAQIgUAAQAAgHgHgFQgEgFgJAAQgJAAgGAFQgGAFgCAHQgDAIAAAHQAAAQAGAHQAIAJAMAAQAMAAADgEQAFgHACgKIAVAAQgEASgKAKQgLAKgSAAQgVAAgNgMgAFtCaQgCAAgBgGIgBgPQgBgJgFgDQgDgDgHAAIgVAAIAAAkIgUAAIAAhdIAzAAQAMAAAHAHQAHAIABAJQAAATgPAGQAMADABAUIACAJIAAADIABAGIAAADgAFEBnIAXAAQAOAAAAgNQAAgOgOAAIgXAAgADLCaIAAhdIBIAAIAAARIgzAAIAAAWIAuAAIAAANIguAAIAAAXIA1AAIAAASgACCCaIAAhMIgbAAIAAgRIBNAAIAAARIgdAAIAABMgAA6CaIgog/IAAA/IgTAAIAAhdIAUAAIAnA+IAAg+IAVAAIAABdgAhkCaIAAhdIBHAAIAAARIgyAAIAAAWIAuAAIAAANIguAAIAAAXIAyAAIAAASgAlhCaIAAhdIAWAAIAABLIAtAAIAAASgAmMCaIgIgUIghAAIgJAUIgWAAIAkhdIAXAAIAjBdgAmxB2IAZAAIgMgjgAptCaIAAhdIAUAAIAABdgArdCaIAAhdIAqAAQAUAAAKAMQANAKAAAYQAAAVgLAOQgLAMgVAAgArICIIATAAQAKAAAHgGQAHgHAAgPQAAgOgHgJQgFgHgPAAIgQAAgAtACaIAAhdIBHAAIAAARIgyAAIAAAWIAuAAIAAANIguAAIAAAXIA0AAIAAASgAtzCaIAAhCIgWBCIgQAAIgYhBIAABBIgVAAIAAhdIAfAAIAXBAIAThAIAgAAIAABdgA05CVIAAi/IBfBnIAABYgAzOA1IhjhiIEPAAIAABigA4IA1IAAhiIC4AAIhkBigAp6AOQgEgDAAgIQAAgGAEgEQAFgDAFAAIAIAAQAHAAAGgIQANgVAFgNQADgKABgGQgBgIgFgRIgehRQgGgQgCgFQgHgGgIgDIgIgBQgBgBAAAAQgBAAAAgBQAAAAAAgBQAAgBAAgBQAAgDADgBIAiABIAigBQACABAAADQAAAEgCABIgIABQgJACAAAEQAAAEALAfIAMAjIALAaQADgDAKgZIANgcQAMggAAgGQABgHgJgBIgLgBQgBgBAAAAQgBAAAAgBQAAAAABgBQAAgBABgBQAAgBAAAAQAAgBABAAQAAgBAAAAQABgBAAAAIA8AAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAFIgHABQgJACgHAHIgPAgIgVArQggBCgbA3QgJASgOAAQgIAAgFgFgA0xg6IBjhjIBTAAIAABjgA5hg6IAAhjICrAAIBmBjgAYHhEQgNgGgJgLQgPgWAAgbQAAgjAUgaQAWgXAgAAQAYAAAQANQAOAOAAARIgBALQgCACgUAAIhFAAIgKAAIAAAKQAAAcAPAVQASAVAdAAQAJAAAIgEQAJgFAIgKQAGgCAAAFQgJATgRAKQgRAIgPAAQgSAAgPgIgAYLjEQgLAMgBAJQAAABABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAdAAQAhAAAFgEQADgCAAgGQAAgKgGgGQgIgGgQAAQgPAAgOALgAWUhJQgIgIAAgVIAAhUQAAgKgBAAIgIAAIgKAAQgBgCAAgEIAAgEQAQgEAIgIQAJgHAIgPIADAAQAAAAABABQABAAAAAAQABAAAAABQAAAAAAAAIAAARQAAAHABAAQACABAEAAIArAAQACACAAAGQAAAGgCADIgsAAIgFAAQgBAAAAAHIAABHQAAAUAFAJQAGALARAAIAJgBIALgFQAAAAAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQgPASgZAAQgWAAgIgNgAP/g9IguhrQghBEgNAnQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAIgag7IhJidIgKgTQgGgIgLgBIgKAAIgBgFQAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABAAIAmAAIAsAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABQAAADgDACIgHAAQgMABAAAGQAAAFASAsQALAVA3B4IAcg9QAHgMgBgEIgBgKQgUgngXgzQgGgJgFgEQgEgGgIgBIgKAAQgCgCAAgDQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAAAIAqAAIApAAQAAAAAAAAQAAAAABABQAAAAAAABQAAAAABABQAAADgCACIgJAAQgMABgBADQgBAFAFALIAcBDQAQgcAGgWQAMgWAAgIQAAgGgMgBIgKAAQgDgCACgEQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAjAAIAjAAQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIgBAFIgLAAQgJABgJAKIgNAWQgOAbgPAiIgCAIIACAIQAMAgAaA3QARgmAQgpIAfhLQAKgeABgDQAAgJgNgBIgLAAQgCgCAAgDQAAgDAEAAIAnAAQARAAALgJQAIgDALgIQAAgBABAAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABQgCAWAAAYIAABPQAAAGACACQAagUAYAAQAaAAAMANQAKAOAAAVIAAA+QAAAUACAGQAEAGAKABIAIABQAEABAAAFQAAABgBAAQAAABgBAAQAAABgBAAQAAAAgBAAIgkgBIgkABQAAAAgBAAQAAAAAAgBQAAAAgBgBQAAAAAAgBQAAgFACgBIAIgBQAJgBACgGQACgGAAgUIAAg1QAAgTgJgJQgJgNgRAAQgTABgKAJQgGAFgBACQgCAFAAAKIAAA+QAAAUACAGQADAGAKABIAIABQACABgBAFQAAABgBAAQAAABAAAAQAAABAAAAQAAAAAAAAIgkgBIglABQgBAAAAAAQAAAAgBgBQAAAAAAgBQgBAAAAgBQAAgFADgBIAIgBQAMgBAAgGQADgEAAgWIAAipQAAgQgCgHQgCgCgCAAQgIADgFAIIgWAzIgdA/QgWA2gYA+QgBABgEAAQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAgAH+hJQgHgJAAgUIAAhUQAAgKgCAAIgFAAIgMAAIgBgGQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQARgEAJgIQAHgHAHgPIAEAAQABAAABABQAAAAABAAQAAAAABABQAAAAABAAIAAARQAAAHABAAQAAABAEAAIArAAQACACAAAGQAAAGgCADIgrAAIgFAAQgCAAAAAHIAABHQABAUAEAJQAHALARAAIAKgBIAJgFQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAAAQAAABAAAAQAAABgBAAQgPASgXAAQgWAAgLgNgAGPhJQgJgJABgUIAAhUQAAgKgBAAIgIAAIgKAAQgDgCAAgEQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAABgBQARgFAGgHQAIgHAIgPIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAAARQAAAFACACIAHABIApAAQADACAAAGQAAAGgDADIgpAAIgHAAQgCAAAAAHIAABHQAAAUAGAJQAFALARAAIAJgBQAFgBAGgEQABAAAAAAQAAAAABABQAAAAAAABQABAAAAABQAAAAABABQAAAAAAAAQAAABAAAAQgBABAAAAQgOASgaAAQgWAAgHgNgADchRQgWgWgBgkQABgiAWgXQAXgWAiAAQAfAAAWAWQAYAVAAAhQAAAkgYAWQgWAZgigBQghABgVgWgADxi9QgMAQAAAfQAAAcALATQAPAYAXAAQAXAAAKgUQALgTAAgZQAAgcgMgWQgMgWgZAAQgTAAgNASgABPhQQgWgVABgiQgBgiAWgXQAagaArAAQATAAAOAGQAFAFAAALQABAFgDAEQgDACgCAAQgEAAgBgBQgRgUgVAAQgWAAgQAOQgNASAAAdQAAAZANASQARAVAeAAQAOAAALgHQAJgEAHgOQABAAAAABQABAAAAAAQABAAAAABQAAAAABAAQACADAAADQgIASgTAMQgQAIgTAAQggABgTgVgAhohKQgDgGgDgRQgDgQAAgMQAAgBABAAQAAgBAAAAQABgBAAAAQAAAAABAAIAFAAQAQA5AxAAQAWAAAMgOQAMgLgBgSQAAgQgDgLQgIgQgSgKIglgWQgpgdAAglQAAgbAXgTQAUgRAjAAQARAAASAFIAMAAIAEAVQADAOAAALQgDADgCAAQgEAAgBgCQgEgRgJgLQgOgNgWAAQgaAAgLANQgIALAAARQAAAaAhAUIAdASQAsAeAAAqQAAAfgTAUQgWAUglgBQghAAgZgOgAmAhRQgYgWAAgkQAAgiAZgXQAWgWAiAAQAgAAAWAWQAWAVAAAhQAAAkgWAWQgWAZgjgBQggABgWgWgAlqi9QgMAQAAAfQAAAcAMATQANAYAWAAQAXAAAMgUQAKgTAAgZQAAgcgMgWQgMgWgZAAQgUAAgLASgAq2hJQgEgFgCAAQgCAAgEADIgIAFIgOAHQgHADgGAAQgRAAgLgIQgKgMAAgRQAAgLAFgFQAHgHASgIIAtgOQAEgCAAgEQACgCAAgDIACgTQAAgMgGgIQgHgLgPgBQgJAAgHADQgHAGgCAIQAAAKgDADQgKAGgMAAQgEAAAAgFQAAgPAagPQAXgPAVAAQATAAAKALQAKAKAAAWIgEBCQgCAfAVAAIAIgBIAFgDQADAAAAAEQAAAEgJAGQgLAIgLAAQgQAAgJgNgArNiAQgTAIgGAEQgJAHAAAJQAAAIAFAGQAGAIAMAAQAGAAAIgCIAKgGIAEgJIAAgLIAAgWQAAAAAAgBQAAAAgBAAQAAgBgBAAQAAAAgBAAIgOACgA05lXIBfAAIAACxIhfBpgA2pimIAAhXIBgAAIAADAgAMMhCQgKgFgLgKQgUAKgOAFQgMADgQAAQgkAAgVgSQgYgUAAgdQAAgqArgRQgPgRAAgRQAAgSAOgOQAMgNAVAAQANAAALAIQALAHgBAMQABAMgLAIQgHAIgJAAQgHAAAFgHQACgDAAgEQADgDgDgIQAAgDgGgGQgFgEgIAAQgKAAgGAFQgJAGAAAJQAAAIAJAJQAGAHASALQAgARAOAMQAZAUARAiQALgPAAgWQAAgNgIgLQgEgGgJgBQgLgCgIAIIgFABQgDgBAAgIQACgIAIgHQAKgIANABQAJAAALACIAPABQAFAAADgDIAAAAIACgBQABAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAAUgZAHQAFALAAAPQAAAagUAVQAIAQAKAHQAJAGANAAIALgBIAFgCQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABQAAAFgKAEQgMADgOAAQgPAAgJgDgAKEiXQAAAcAVAVQAWAXAbAAQAJAAAIgCIAUgIIgRgWIgIgMQgNgUgOgOQgJgJgOgJIgLgIQgVAFAAAbgAVHhCIgkABIgEgDQAAgFAEgBIAHgBQALgBACgGQABgEAAgWIAAhBQAAgMgBgCQgCgEgHgFIgEgCIgBgFQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAABAAQAHgBAMgGIATgKIAEAAQgCAbAAAVIAABDQAAAUACAGQACAGAKABIAJABQABABAAAFQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgjgBgAjEhCIgjABQgBAAAAAAQAAAAAAgBQgBAAAAgBQAAAAgBgBQABgFACgBIAFgBQAKgBAEgGQACgGAAgUIAAhBQAAgMgBgCQgDgEgHgFIgCgCQgBgBAAAAQgBgBAAAAQAAgBAAgBQgBAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBQAAAAABAAQAGgBAMgGIAUgKQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAUQAAABABABQAAABAAABQAAAAAAAAQAAABAAAAQAOgLAHgEQALgHAKAAQAHAAAEAEQAFAEAAAGQAAAIgFAHQgEADgGAAQgEAAgFgDQgJgHgIAAQgIAAgEAJQgGAHAAAWIAAAyQAAAUACAHQAEAFAJABIAOABQACABAAAFIgCADIgqgBgAnJhCIgjABQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgFABgBIAHgBQAMgBACgGQACgEAAgWIAAipQAAgRgBgEQgEgGgHgFIgFgBIgBgDQAAgFABAAQAegKALgFQADAAACACIgCAuIAACxQAAAUACAGQADAGALABIAIABQACABgBAFQAAABgBAAQAAABAAAAQAAABgBAAQAAAAAAAAIglgBgAu1hCIgrABQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgFABgBIAFgBQAQgDAEgHQABgGAAggIAAiNQAAgWgBgIQgEgFgMgCIgLgBQgDgCAAgDQAAgBAAAAQAAgBAAAAQABgBAAAAQABgBABAAQAcgCA0AAQAqAAAWAJQAbAPAAAhQAAARgLAOQgJAMgSAHQAAAFAGAAQAUAFANANQARAUABAYQAAAjgYATQgaAUgxAAIgugBgAumi3IAAA3QAAAfAHALQAJAKAWAAQAaAAAPgNQARgMAAgbQAAgdgNgPQgVgTgogBIgUAAQgCADAAAGgAuhktIgEADIgBAHIAABNQAAAIACABQADABAPAAQAdgBAOgJQAPgOgBgXQAAgbgQgOQgPgKgYAAQgLAAgGABgAU1j/QgFgFAAgIQAAgJAHgFQAFgGAIAAQAJAAAFAGQAEAFAAAJQAAAKgEAFQgHAEgHAAQgIAAgHgGg");
	this.shape.setTransform(593.55,119.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BSWH_Logo_Dallas, new cjs.Rectangle(430.1,84.7,326.9,68.89999999999999), null);


(lib.head_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.head_img();
	this.instance.setTransform(-51,-43.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.head_mc, new cjs.Rectangle(-51,-43.5,125,103), null);


(lib.ClipGroup = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AjECBIECkBICHAAIAAEBg");
	mask.setTransform(19.65,12.925);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0.004,0.608],-19.6,0,19.7,0).s().p("AjECBIECkBICHAAIAAEBg");
	this.shape.setTransform(19.65,12.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,39.3,25.9), null);


(lib.txt_deepBreath_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// deep_txt
	this.instance = new lib.deep_txt();
	this.instance.setTransform(-105.55,20.4,1,1,0,0,0,-37.1,11);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-2.55,alpha:1},21,cjs.Ease.quadOut).wait(46).to({_off:true},1).wait(64).to({_off:false},0).to({_off:true},1).wait(48));

	// breath_txt
	this.instance_1 = new lib.breath_txt();
	this.instance_1.setTransform(1.95,19.95,1,1,0,0,0,-61.7,11.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({y:-2.45,alpha:1},21,cjs.Ease.quadOut).wait(42).to({_off:true},1).wait(64).to({_off:false},0).to({_off:true},1).wait(48));

	// the_01_txt
	this.instance_2 = new lib.the_01_txt();
	this.instance_2.setTransform(104.4,19.95,1,1,0,0,0,-27.8,11);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(27).to({_off:false},0).to({y:-2.45,alpha:1},21,cjs.Ease.quadOut).wait(19).to({_off:true},1).wait(64).to({_off:false},0).to({_off:true},1).wait(48));

	// cramping_txt
	this.instance_3 = new lib.cramping_txt();
	this.instance_3.setTransform(222.05,20.4,1,1,0,0,0,-80.8,11.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(31).to({_off:false},0).to({y:-2.55,alpha:1},21,cjs.Ease.quadOut).wait(15).to({_off:true},1).wait(64).to({_off:false},0).to({_off:true},1).wait(48));

	// will_txt
	this.instance_4 = new lib.will_txt();
	this.instance_4.setTransform(347.8,20.15,1,1,0,0,0,-36.5,11);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(35).to({_off:false},0).to({y:-2.25,alpha:1},21,cjs.Ease.quadOut).wait(11).to({_off:true},1).wait(64).to({_off:false},0).to({_off:true},1).wait(48));

	// pass_txt
	this.instance_5 = new lib.pass_txt();
	this.instance_5.setTransform(434.35,20.65,1,1,0,0,0,-40.9,11.3);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(40).to({_off:false},0).to({y:-2.3,alpha:1},21,cjs.Ease.quadOut).wait(6).to({_off:true},1).wait(64).to({_off:false},0).to({_off:true},1).wait(48));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142.6,-13.7,617.9,45.7);


(lib.txt_deepBreath = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// should_txt
	this.instance = new lib.should_txt();
	this.instance.setTransform(550.1,20.3,1,1,0,0,0,-61.6,11.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:-2.65,alpha:1},21,cjs.Ease.quadOut).wait(15).to({_off:true},1).wait(166));

	// we_txt
	this.instance_1 = new lib.we_txt();
	this.instance_1.setTransform(643.8,19.9,1,1,0,0,0,-23.7,11);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({y:-2.5,alpha:1},21,cjs.Ease.quadOut).wait(11).to({_off:true},1).wait(166));

	// talk_txt
	this.instance_2 = new lib.talk_txt();
	this.instance_2.setTransform(716.4,20,1,1,0,0,0,-36.9,11);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(8).to({_off:false},0).to({y:-2.4,alpha:1},21,cjs.Ease.quadOut).wait(7).to({_off:true},1).wait(166));

	// to_txt
	this.instance_3 = new lib.to_txt();
	this.instance_3.setTransform(780.55,20.45,1,1,0,0,0,-19.9,11.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(12).to({_off:false},0).to({y:-2.5,alpha:1},21,cjs.Ease.quadOut).wait(3).to({_off:true},1).wait(166));

	// someone_txt
	this.instance_4 = new lib.someone_txt();
	this.instance_4.setTransform(892,20.35,1,1,0,0,0,-83.2,11.3);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(16).to({_off:false},0).wait(1).to({y:18.35,alpha:0.0889},0).wait(1).to({y:16.3,alpha:0.1788},0).wait(1).to({y:14.3,alpha:0.2676},0).wait(1).to({y:12.4,alpha:0.3535},0).wait(1).to({y:10.6,alpha:0.435},0).wait(1).to({y:8.9,alpha:0.5108},0).wait(1).to({y:7.35,alpha:0.5804},0).wait(1).to({y:5.95,alpha:0.6435},0).wait(1).to({y:4.65,alpha:0.7},0).wait(1).to({y:3.55,alpha:0.7503},0).wait(1).to({y:2.55,alpha:0.7947},0).wait(1).to({y:1.65,alpha:0.8337},0).wait(1).to({y:0.9,alpha:0.8676},0).wait(1).to({y:0.25,alpha:0.897},0).wait(1).to({y:-0.3,alpha:0.9221},0).wait(1).to({y:-0.8,alpha:0.9434},0).wait(1).to({y:-1.2,alpha:0.9611},0).wait(1).to({y:-1.5,alpha:0.9756},0).wait(1).to({y:-1.8,alpha:0.9872},0).wait(1).to({y:-2,alpha:0.9961},0).to({_off:true},1).wait(166));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(488.6,-13.8,486.6,45.6);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// TAKE_QUIZ
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3EDE8").s().p("AgfArIAAgQIArg1IgpAAIAAgQIA8AAIAAAPIgqA2IAqAAIAAAQg");
	this.shape.setTransform(28.65,-0.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F3EDE8").s().p("AgIArIAAhVIARAAIAABVg");
	this.shape_1.setTransform(23,-0.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F3EDE8").s().p("AgNApQgGgCgFgFQgEgEgDgGQgCgHAAgIIAAgzIARAAIAAA0QAAAIAEAFQAFAFAHAAQAHAAAFgFQAFgFAAgIIAAg0IARAAIAAAzQAAAIgDAHQgCAGgFAEQgEAFgHACQgGACgHAAQgHAAgGgCg");
	this.shape_2.setTransform(16.975,-0.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F3EDE8").s().p("AgRAoQgIgDgGgGQgGgGgDgIQgEgIAAgJQAAgIAEgIQADgIAGgGQAGgGAIgDQAIgEAJAAQAIAAAIAEQAIADAGAGQAGAGADAIQAEAIAAAIQAAAIgDAHQgDAHgEAFIAMAQIgTAAIgFgGIgLAFQgFACgFAAQgJAAgIgEgAgLgZQgFACgEAEQgDAEgCAFQgDAFAAAFQAAAGADAFQACAFADAEQAEAEAFACQAFACAGAAIAGgBIAGgCIgSgYIASAAIALANIACgGIABgIQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgGAAgFACg");
	this.shape_3.setTransform(7.775,-0.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F3EDE8").s().p("AgcArIAAhVIA5AAIAAAQIgoAAIAAATIAoAAIAAAPIgoAAIAAATIAoAAIAAAQg");
	this.shape_4.setTransform(-4.025,-0.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F3EDE8").s().p("AAQArIgTgqIgOAQIAAAaIgRAAIAAhVIARAAIAAAoIAfgoIAUAAIgbAgIAbA1g");
	this.shape_5.setTransform(-11.55,-0.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F3EDE8").s().p("AAXArIgFgQIgjAAIgGAQIgQAAIAghVIAPAAIAgBVgAAMAMIgMghIgLAhIAXAAg");
	this.shape_6.setTransform(-20.225,-0.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F3EDE8").s().p("AgHArIAAhFIgYAAIAAgQIA/AAIAAAQIgYAAIAABFg");
	this.shape_7.setTransform(-28.425,-0.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},9).to({state:[]},1).wait(40));

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AmWCBIAAkBIMtAAIAAEBg");
	var mask_graphics_9 = new cjs.Graphics().p("AmWCBIAAkBIMtAAIAAEBg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:0,y:0.025}).wait(9).to({graphics:mask_graphics_9,x:0,y:0.025}).wait(1).to({graphics:null,x:0,y:0}).wait(40));

	// _Clip_Group_
	this.instance = new lib.ClipGroup();
	this.instance.setTransform(60.7,0,1,1,0,0,0,19.7,12.9);
	this.instance.alpha = 0;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:21.15,alpha:1},9,cjs.Ease.quadOut).to({_off:true},1).wait(40));

	// Layer_2
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#01A882").s().p("AmWCBIAAkBIMtAAIAAEBg");
	this.shape_8.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(9).to({_off:true},1).wait(40));

	// _Path_
	this.instance_1 = new lib.Bitmap1();
	this.instance_1.setTransform(-46.75,-18.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:true},1).wait(40));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.7,-18.9,96,40);


// stage content:
(lib.BSWH_DigestiveHealth_01_Irving_970x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EhLxATiMAAAgnDMCXjAAAMAAAAnD");
	this.shape.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(338));

	// BSWH_Logo
	this.instance = new lib.BSWH_Logo_Dallas();
	this.instance.setTransform(166.6,61.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11).to({_off:false},0).to({alpha:1},9).wait(318));

	// txt_tellingYou
	this.instance_1 = new lib.txt_tellingYou();
	this.instance_1.setTransform(268.1,191.85,1.8328,1.8328);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({alpha:1},10).wait(317));

	// txt_yourGut
	this.instance_2 = new lib.txt_yourGut();
	this.instance_2.setTransform(268.05,161.4,1.8328,1.8328,0,0,0,0.1,0.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(11).to({_off:false},0).to({alpha:1},10).wait(317));

	// ctaBtn
	this.instance_3 = new lib.ctaBtn("single",0);
	this.instance_3.setTransform(357.45,279.95,1.805,1.805,0,0,0,0.4,0.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({y:177.95,mode:"synched",loop:false},11,cjs.Ease.quadOut).wait(9).to({mode:"single",startPosition:9},0).wait(303));

	// txt_deepBreath
	this.txt_deepBreath = new lib.txt_deepBreath_02("synched",0,false);
	this.txt_deepBreath.name = "txt_deepBreath";
	this.txt_deepBreath.setTransform(790.55,53.8,1.3423,1.3423,0,0,0,416.4,-0.7);
	this.txt_deepBreath._off = true;

	this.timeline.addTween(cjs.Tween.get(this.txt_deepBreath).wait(11).to({_off:false},0).wait(68).to({mode:"single",startPosition:132},0).to({alpha:0},12).wait(247));

	// txt_deepBreath
	this.txt_deepBreath_1 = new lib.txt_deepBreath("synched",0,false);
	this.txt_deepBreath_1.name = "txt_deepBreath_1";
	this.txt_deepBreath_1.setTransform(-57.55,53.8,1.3423,1.3423,0,0,0,416.3,-0.7);
	this.txt_deepBreath_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.txt_deepBreath_1).wait(91).to({_off:false},0).wait(36).to({mode:"single",startPosition:36},0).wait(211));

	// safeCare_Logo
	this.instance_4 = new lib.safeCare_Logo();
	this.instance_4.setTransform(887.65,54.8,0.1922,0.1922,15.7398,0,0,2.4,2.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(127).to({_off:false},0).to({regX:2.1,regY:2.7,scaleX:0.1102,scaleY:0.1102,rotation:15.7416,x:887.55,y:54.7,alpha:1},7,cjs.Ease.quadOut).to({regX:2,regY:3,scaleX:0.1299,scaleY:0.1299,rotation:15.7429,x:887.6},4,cjs.Ease.quadOut).wait(200));

	// head_mc
	this.instance_5 = new lib.head_mc();
	this.instance_5.setTransform(512.45,337.5,1,1,0,0,0,0,44.1);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(11).to({_off:false},0).to({y:234},14,cjs.Ease.quadOut).wait(313));

	// BlueBox
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003DA6").s().p("EgpwALJIAAyfIDsjyMBP2AAFIAAWMg");
	this.shape_1.setTransform(793.1,323.675);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1).to({y:298.525},0).wait(1).to({y:275.775},0).wait(1).to({y:255.425},0).wait(1).to({y:237.475},0).wait(1).to({y:221.875},0).wait(1).to({y:208.725},0).wait(1).to({y:197.925},0).wait(1).to({y:189.575},0).wait(1).to({y:183.575},0).wait(1).to({y:179.975},0).wait(1).to({y:178.775},0).wait(327));

	// GreenBox
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00A881").s().p("EgpwALJIAA2MMBP1gAFIDtDyIAASfg");
	this.shape_2.setTransform(258.15,323.675);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1).to({y:298.525},0).wait(1).to({y:275.775},0).wait(1).to({y:255.425},0).wait(1).to({y:237.475},0).wait(1).to({y:221.875},0).wait(1).to({y:208.725},0).wait(1).to({y:197.925},0).wait(1).to({y:189.575},0).wait(1).to({y:183.575},0).wait(1).to({y:179.975},0).wait(1).to({y:178.775},0).wait(327));

	// Background_color
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F4EDE7").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_3.setTransform(484.9982,124.9997,1.3324,2.7778);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(338));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(475.8,83.5,584.7,311.5);
// library properties:
lib.properties = {
	id: 'BD94237A628B41D499830A95CE062363',
	width: 970,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Bitmap1.png", id:"Bitmap1"},
		{src:"head_img.png", id:"head_img"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['BD94237A628B41D499830A95CE062363'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;