(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,258,96);


(lib.Image_01 = function() {
	this.initialize(img.Image_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,590,250);


(lib.Image_02 = function() {
	this.initialize(img.Image_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,590,250);


(lib.Image_03 = function() {
	this.initialize(img.Image_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,590,250);


(lib.Image_04 = function() {
	this.initialize(img.Image_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,590,250);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_celebratingTenYears = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3FA1C7").s().p("AP6A+QgIgCgHgDQgHgDgFgFIgKgKIAagUQAFAIAIAFQAHAEALAAQAHAAAEgDQAEgDAAgFQAAgDgCgCIgEgEIghgJQgHgDgGgEQgGgDgDgGQgEgGAAgKQAAgIAEgHQADgHAGgFQAGgFAIgDQAJgDAKAAQAIAAAHACQAHABAGADIALAHIAKAJIgYATQgEgHgGgEQgHgEgJAAQgIAAgDAEQgEADAAAEQAAABAAABQAAAAABABQAAAAAAABQAAAAABABIAFADIAgAJQAIACAFAEQAGADAEAHQAEAGAAAKQAAAJgEAIQgDAHgHAFQgGAGgJADQgIADgLAAQgKAAgIgCgAFtA9QgJgEgGgHQgHgHgDgMQgEgMAAgRIAAgEQAAgRAEgLQAEgLAGgIQAHgHAJgDQAJgEAKAAQAKAAAJAEQAJADAHAIQAGAHAEALQAEAMAAAQIAAAEQAAASgEALQgDAMgHAHQgGAIgJADQgJADgLAAQgLAAgJgDgAF5ghQgEABgCAEQgDAEgBAGQgBAHAAAKIAAADIABARQABAGADAEQACAEAEABQADACAFAAQAEAAAEgCQAEgBACgEQADgEABgGQABgHAAgKIAAgDQAAgKgBgHQgCgGgCgEQgDgEgDgBQgEgCgEAAQgEAAgEACgABiA7QgMgFgIgJQgJgJgEgLQgFgMAAgNQAAgMAFgMQAFgMAIgIQAJgJALgFQAMgFAOAAQASAAANAHQANAHAJALIgZASQgEgHgHgEQgHgEgKAAQgHAAgGADQgGADgFAFQgFAEgCAHQgDAHAAAGQAAAIACAHQADAGAFAFQAEAFAHACQAGADAIAAQALAAAHgFQAHgFADgKIgiAAIAAgaIBCAAIAAANQAAAMgEALQgEALgIAJQgIAIgLAFQgLAFgOAAQgPAAgMgFgAwVA7QgMgFgIgJQgJgIgEgMQgFgMAAgNQAAgMAFgMQAFgMAIgIQAJgJALgFQAMgFAOAAQAJAAAIADQAIACAHAEQAHAEAGAGQAGAFAEAHIgaARQgEgJgIgFQgHgEgKAAQgHAAgHACQgGADgEAFQgFAEgCAHQgDAGAAAGQAAAHADAHQACAGAFAEQAEAFAGADQAGADAIAAQALAAAHgGQAIgGAEgJIAbAPQgEAIgGAGQgFAGgIAFQgHAFgJACQgIADgKAAQgOAAgMgFgAOrA+IgSglIgXAAIAAAlIgeAAIAAh7IA2AAQALAAAJAEQAIADAGAGQAGAFADAIQADAIAAAJQAAAMgFAIQgFAKgKAFIAXAtgAOCgBIAWAAQAJAAAFgFQAEgFAAgHQAAgHgEgEQgFgFgJAAIgWAAgAM0A+IgGgSIgvAAIgHASIgeAAIAuh7IAdAAIAtB7gAMlASIgPgpIgOApIAdAAgAJzA+IAAh7IBWAAIAAAcIg4AAIAAAUIA4AAIAAAbIg4AAIAAAVIA4AAIAAAbgAIaA+IAAg0IgphHIAgAAIAYAtIAYgtIAfAAIgoBIIAAAzgAEaA+IAAhPQgDAHgHADQgIAEgIAAIgEAAIAAgdIABAAQAPAAAIgHQAHgHAAgPIAdAAIAAB7gAAJA+IgwhNIAABNIgdAAIAAh7IAfAAIAuBKIAAhKIAcAAIAAB7gAh8A+IAAh7IAeAAIAAB7gAjSA+IAAhfIgiAAIAAgcIBgAAIAAAcIghAAIAABfgAkiA+IgGgSIgvAAIgHASIgeAAIAuh7IAdAAIAtB7gAkxASIgPgpIgOApIAdAAgAmoA+IgSglIgXAAIAAAlIgeAAIAAh7IA2AAQALAAAJAEQAIADAGAGQAGAFADAIQADAIAAAJQAAAMgFAIQgFAKgKAFIAXAtgAnRgBIAWAAQAJAAAFgFQAEgFAAgHQAAgHgEgEQgFgFgJAAIgWAAgApmA+IAAh7IAxAAQAXAAALAJQALAJAAASQAAAIgDAGQgDAGgGAEQAHADAEAHQAEAGAAAKQAAATgNAJQgNAJgWAAgApJAkIAVAAQAIAAAEgDQAEgDAAgGQAAgGgDgDQgEgDgKAAIgUAAgApJgNIAVAAQAIAAAEgDQADgDAAgFQAAgFgEgDQgDgDgIAAIgVAAgArVA+IAAh7IBWAAIAAAcIg4AAIAAAUIA4AAIAAAbIg4AAIAAAVIA4AAIAAAbgAs/A+IAAh7IAeAAIAABfIA2AAIAAAcgAuuA+IAAh7IBWAAIAAAcIg4AAIAAAUIA4AAIAAAbIg4AAIAAAVIA4AAIAAAbg");
	this.shape.setTransform(630.325,-369.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_celebratingTenYears, new cjs.Rectangle(522,-375.4,216.70000000000005,12.699999999999989), null);


(lib.txt_qualityCare = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiJDKQgYgJgQgOQgRgPgJgVQgJgVAAgYQABgUAGgQQAHgRALgOQALgNAOgLIAdgVIgRgWIgKgVIgHgXIgBgZQgBgVAKgTQAJgTAPgPQAPgNAWgJQAUgIAZAAQAXAAAWAIQATAIARAOQAPANAIATQAJASAAAWQABASgGAPQgFAOgKANQgIALgMALIgZAUIAnAnIBAhLIBvAAIhxCEIB0ByIh+AAIgwgwIgeAZQgOAKgPAHQgOAGgPADIghACQgeAAgYgIgAhoBBQgKAMAAANQAAARAKAKQALAKARAAQAPgBAMgFQANgGAPgPIg5g5QgQALgKALgAhJh9QgJAHABAMQAAANAEAKQAFAKANAOQAQgLAJgLQAKgKAAgPQAAgMgJgHQgIgHgMAAQgLAAgJAHg");
	this.shape.setTransform(-96.5,17.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A36GpQgmgRgcgcQgcgcgQgmQgQgngBgsQABgrAQgnQAQgmAcgcQAcgdAmgQQAmgRAsAAQArAAAnARQAmAQAdAdQAcAcARAmQAPAnAAArQAAAsgPAnQgRAmgcAcQgcAcgnARQglAQgtAAQgsAAgmgQgA3UB+QgVAJgOAQQgOAPgJAVQgIAVAAAXQAAAYAIAUQAIAVAPAPQAOAQAVAJQAUAJAYAAQAYAAAVgJQAUgJAPgQQAPgPAJgVQAHgUABgYQgBgXgHgVQgJgVgPgPQgQgQgUgJQgUgJgYAAQgYAAgUAJgAsiG0IAAmZIEZAAIAABbIi4AAIAABDIC4AAIAABbIi4AAIAABFIC4AAIAABbgAu5G0Ig5h7IhOAAIAAB7IhhAAIAAmZICwAAQAlAAAcALQAdALAUAUQATASALAaQAKAagBAdQAAAngRAfQgSAggeASIBLCUgAxADhIBIAAQAfAAAPgQQAPgQAAgXQAAgZgQgPQgPgOgeAAIhIAAgA8OG0IAAkDIhsCQIhqiQIAAEDIhgAAIAAmZIBdAAIBuCZIByiZIBYAAIAAGZgEAmvgAZQgcgHgWgLQgWgKgRgPQgSgQgPgRIBUhDQATAbAYAPQAYAQAkAAQAZAAANgLQAMgLAAgRQAAgJgFgHQgFgHgLgFIhtgfQgWgIgUgNQgRgNgMgVQgMgUAAggQAAgbALgXQAMgXASgRQAVgQAbgKQAcgJAgAAQAcAAAYAFQAWAEAUAJQATAKARANIAhAgIhOA9QgPgXgUgNQgVgNgfAAQgZAAgMAMQgLALAAAOQAAAJAFAGQAGAHALAEIBqAdQAYAHAUAOQATAOAMAVQANAVAAAhQAAAdgMAZQgMAYgUASQgWASgcAKQgcAKgjAAQghAAgbgGgAbzgZQgbgHgXgLQgVgKgSgPQgRgQgPgRIBUhDQASAbAYAPQAZAQAjAAQAZAAANgLQANgLAAgRQgBgJgFgHQgEgHgLgFIhugfQgWgIgTgNQgSgNgMgVQgMgUABggQgBgbALgXQAMgXATgRQAUgQAbgKQAcgJAhAAQAcAAAXAFQAWAEAUAJQAUAKAQANIAiAgIhPA9QgOgXgVgNQgUgNggAAQgZAAgMAMQgLALAAAOQAAAJAGAGQAGAHAKAEIBrAdQAYAHATAOQATAOANAVQAMAVAAAhQAAAdgLAZQgNAYgUASQgVASgcAKQgdAKgiAAQghAAgcgGgAWNgZQgbgHgWgLQgXgKgRgPQgSgQgOgRIBUhDQASAbAZAPQAYAQAjAAQAZAAANgLQANgLAAgRQAAgJgGgHQgEgHgLgFIhugfQgWgIgTgNQgSgNgMgVQgMgUAAggQABgbAKgXQAMgXATgRQAUgQAbgKQAcgJAhAAQAcAAAXAFQAWAEAUAJQATAKARANIAiAgIhPA9QgOgXgVgNQgVgNgeAAQgaAAgMAMQgLALAAAOQAAAJAGAGQAGAHALAEIBqAdQAXAHAUAOQATAOANAVQAMAVAAAhQAAAdgLAZQgNAYgUASQgVASgcAKQgdAKgiAAQghAAgcgGgAEYgkQgmgQgbgdQgcgcgPgmQgPgnAAgrQAAgtAPgmQARgnAbgcQAcgcAngQQAmgQAuAAQAdAAAbAHQAaAHAYAOQAYANATATQASASAOAXIhVA2QgOgcgZgPQgXgQgiAAQgZAAgUAIQgUAJgPAQQgOAPgIAVQgIAVAAAYQAAAYAIAUQAHAUAPAQQAOAPAUAJQAUAJAZAAQAlAAAZgTQAYgTANgdIBaAxQgNAZgTAVQgTAVgXAQQgZAPgcAJQgdAIggAAQgwAAgngRgAo0gZQgbgHgWgLQgWgKgRgPQgSgQgPgRIBUhDQATAbAYAPQAYAQAkAAQAZAAANgLQAMgLAAgRQAAgJgFgHQgFgHgKgFIhugfQgWgIgUgNQgRgNgMgVQgMgUAAggQAAgbALgXQAMgXASgRQAVgQAagKQAdgJAgAAQAcAAAYAFQAWAEAUAJQATAKARANIAhAgIhOA9QgPgXgUgNQgVgNgfAAQgZAAgMAMQgMALABAOQAAAJAFAGQAGAHALAEIBrAdQAXAHAUAOQATAOAMAVQANAVAAAhQAAAdgMAZQgMAYgUASQgWASgcAKQgcAKgjAAQghAAgcgGgAxvgkQgngQgbgdQgcgcgPgmQgPgnAAgrQAAgtAQgmQAPgnAcgcQAcgcAmgQQAngQAtAAQAeAAAbAHQAaAHAYAOQAYANATATQASASAOAXIhWA2QgNgcgYgPQgZgQghAAQgZAAgUAIQgUAJgOAQQgPAPgJAVQgHAVgBAYQABAYAHAUQAIAUAPAQQAOAPAUAJQAUAJAYAAQAlAAAZgTQAZgTAMgdIBbAxQgNAZgTAVQgTAVgYAQQgYAPgdAJQgcAIghAAQguAAgngRgEAgBgAZIAAmZIEZAAIAABbIi4AAIAABEIC4AAIAABaIi4AAIAABFIC4AAIAABbgASogZIgWg9IicAAIgWA9IhiAAICXmZIBeAAICYGZgAR0irIgwiJIgwCJIBgAAgAJYgZIAAmZIBiAAIAAE8ICyAAIAABdgAkmgZIAAmZIEaAAIAABbIi5AAIAABEIC5AAIAABaIi5AAIAABFIC5AAIAABbgAsugZIAAmZIBiAAIAAGZgA10gZIg5h7IhNAAIAAB7IhhAAIAAmZICwAAQAkAAAdAMQAcALAUATQAUATAKAZQAKAaAAAdQAAAngRAgQgSAggfARIBMCUgA36jsIBIAAQAeAAAPgQQAPgQABgXQAAgZgQgOQgPgOgeAAIhIAAgA+1gZIAAmZIEZAAIAABbIi4AAIAABEIC4AAIAABaIi4AAIAABFIC4AAIAABbgEghOgAZIhGh/IhHB/IhsAAIB8jTIh0jGIBqAAIBCB3IBEh3IBrAAIh4DJIB7DQgEgqGgAZIAAmZIEZAAIAABbIi5AAIAABEIC5AAIAABaIi5AAIAABFIC5AAIAABbg");
	this.shape_1.setTransform(151.35,-5.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_qualityCare, new cjs.Rectangle(-118.2,-49.3,539.1,88.3), null);


(lib.txt_earlyDetection = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxDMIAAirIiFjsIBqAAIBOCSIBMiSIBpAAIiGDtIAACqg");
	this.shape.setTransform(222,-28.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AOKKcQgbgHgWgLQgWgKgSgPQgRgQgPgRIBUhDQASAbAZAPQAYAQAjAAQAZAAANgLQANgLAAgRQAAgJgFgHQgFgHgLgFIhtgfQgXgIgTgNQgSgNgMgVQgLgUAAggQAAgbALgXQALgXATgRQAUgQAbgKQAcgJAhAAQAcAAAXAFQAXAEATAJQAUAKARANIAhAgIhOA9QgPgXgVgNQgUgNgfAAQgZAAgMAMQgMALAAAOQAAAJAGAGQAGAHALAEIBqAdQAYAHATAOQAUAOAMAVQAMAVAAAhQAAAdgLAZQgMAYgVASQgVASgcAKQgdAKgiAAQghAAgcgGgACiKRQgngQgbgdQgcgcgPgmQgPgnAAgrQAAgtAQgmQAQgnAbgcQAcgcAngQQAmgQAuAAQAdAAAbAHQAbAHAXAOQAYANATATQATASANAXIhVA2QgOgcgYgPQgYgQgiAAQgZAAgUAIQgUAJgOAQQgPAPgIAVQgIAVAAAYQAAAYAIAUQAHAUAPAQQAOAPAUAJQAUAJAZAAQAlAAAZgTQAYgTANgdIBaAxQgNAZgTAVQgTAVgXAQQgZAPgcAJQgdAIggAAQgvAAgngRgA3gKcQgbgHgWgLQgWgKgSgPQgRgQgPgRIBUhDQASAbAZAPQAYAQAjAAQAZAAANgLQANgLAAgRQAAgJgFgHQgFgHgLgFIhtgfQgXgIgTgNQgSgNgMgVQgLgUAAggQAAgbALgXQALgXATgRQAUgQAbgKQAcgJAhAAQAcAAAXAFQAXAEATAJQAUAKARANIAhAgIhOA9QgPgXgVgNQgUgNgfAAQgZAAgMAMQgMALAAAOQAAAJAGAGQAGAHALAEIBqAdQAYAHATAOQAUAOAMAVQAMAVAAAhQAAAdgLAZQgMAYgVASQgVASgcAKQgdAKgiAAQghAAgcgGgAHfKcIAAmZIEaAAIAABbIi5AAIAABEIC5AAIAABaIi5AAIAABFIC5AAIAABbgAhwKcIAAmZIBjAAIAAGZgAmJKcIiXmZIBmAAIBgEVIBhkVIBlAAIiXGZgAqaKcIg6h7IhNAAIAAB7IhhAAIAAmZICwAAQAlAAAcAMQAdALATATQAUATAKAZQAKAaAAAdQAAAngRAgQgSAggfARIBMCUgAshHJIBIAAQAfAAAPgQQAPgQAAgXQAAgZgQgOQgPgOgeAAIhIAAgAzVKcIAAmZIEaAAIAABbIi5AAIAABEIC5AAIAABaIi5AAIAABFIC5AAIAABbgAAOC/QgmgRgcgcQgcgcgQgmQgQgnAAgrQAAgrAQgnQAQgmAcgcQAcgdAmgQQAmgRArAAQAsAAAmARQAmAQAdAdQAcAcARAmQAQAnAAArQAAArgQAnQgRAmgcAcQgcAcgmARQgmAQgtAAQgrAAgmgQgAAzhrQgUAJgPAQQgOAPgIAVQgIAVAAAXQAAAXAIAUQAHAVAPAPQAPAQAUAJQAUAJAYAAQAZAAAUgJQAUgJAPgQQAPgPAJgVQAIgUAAgXQAAgXgIgVQgJgVgPgPQgPgQgVgJQgUgJgYAAQgXAAgVAJgAx1DEQgfgLgVgVQgVgWgMgeQgMgfAAgoIAAj3IBjAAIAAD3QAAAiARATQASASAfAAQAdAAATgSQASgTAAgiIAAj3IBjAAIAAD3QAAAogLAfQgMAegWAWQgVAVgfALQgeALgmAAQgmAAgegLgA3gDJQgbgGgWgLQgWgLgSgPQgRgPgPgSIBUhDQASAcAZAPQAYAPAjAAQAZAAANgKQANgLAAgRQAAgKgFgHQgFgHgLgFIhtgfQgXgHgTgMQgSgOgMgUQgLgVAAgfQAAgbALgXQALgXATgRQAUgRAbgJQAcgKAhAAQAcAAAXAFQAXAFATAJQAUAJARAOIAhAfIhOA9QgPgXgVgMQgUgNgfAAQgZAAgMALQgMALAAAOQAAAKAGAGQAGAGALAEIBqAdQAYAHATAOQAUAOAMAUQAMAVAAAiQAAAdgLAYQgMAYgVASQgVASgcAKQgdAKgiAAQghAAgcgGgANIDKIAAk+IhvAAIAAhaIE8AAIAABaIhuAAIAAE+gAJMDKIg6h7IhNAAIAAB7IhhAAIAAmYICwAAQAlAAAcALQAdALATAUQAUASAKAaQAKAaAAAdQAAAngRAeQgSAggfASIBMCUgAHFgIIBIAAQAfAAAPgQQAPgQAAgXQAAgZgQgPQgPgOgeAAIhIAAgAncDKIAAmYICkAAQAjAAAdAMQAeAMAUAVQAVAVALAbQALAcAAAfQAAAfgLAbQgLAcgVAVQgUAVgdANQgeAMgkAAIhBAAIAABngAl6AIIA8AAQAcAAASgQQASgRAAgdQAAgcgSgSQgSgRgcAAIg8AAgAtQDKIAAmYICjAAQAkAAAdAMQAdAMAVAVQAUAVAMAbQALAcAAAfQAAAfgLAbQgMAcgUAVQgUAVgeANQgdAMgkAAIhCAAIAABngArvAIIA9AAQAcAAASgQQASgRAAgdQAAgcgSgSQgSgRgcAAIg9AAgAVGkIIAAmZIBhAAIAAE8ICzAAIAABdgASXkIIAAmZIBiAAIAAGZgAP6kIIAAkDIhsCRIhriQIAAECIhgAAIAAmZIBdAAIBuCZIByiZIBZAAIAAGZgAJDkIIgWg9IicAAIgVA9IhjAAICXmZIBeAAICYGZgAIPmaIgwiJIgwCJIBgAAgAgGkIIAAmZIEYAAIAABcIi4AAIAABJIC4AAIAABaIi4AAIAACagAkZkIIAAidIiGAAIAACdIhiAAIAAmZIBiAAIAACcICGAAIAAicIBiAAIAAGZgAr0kIIAAk+IhvAAIAAhbIE8AAIAABbIhuAAIAAE+gAvokIIAAmZIBiAAIAAGZgAzokIIhHkBIhHEBIhhAAIhxmZIBkAAIBAD9IBGj9IBeAAIBGD9IBBj9IBiAAIhyGZg");
	this.shape_1.setTransform(45.175,18.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_earlyDetection, new cjs.Rectangle(-117.4,-48.7,357.70000000000005,134.8), null);


(lib.txt_cancerHatesUs = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aq0KbQgagHgXgKQgVgMgSgPQgSgPgOgRIBThDQASAcAZAPQAYAQAiAAQAaAAANgMQANgKgBgRQAAgKgFgHQgEgGgLgFIgagKIhTgVQgWgHgUgOQgRgMgMgVQgMgVAAgfQAAgbAMgXQALgXASgQQAUgRAbgKQAcgJAgAAQAcAAAYAFQAWAEATAKQAUAJAQAOIAiAeIhOA+QgOgYgWgMQgUgMgeAAQgagBgLAMQgMALAAAOQAAAJAGAGQAGAGALAEIBqAdQAXAHATAOQAUAOAMAVQAMAVAAAhQAAAcgMAZQgLAYgVARQgUATgdAKQgdAKghAAQgigBgbgFgAwwKVQgfgKgVgWQgUgVgMgeQgNgfAAgoIAAj2IBjAAIAAD2QAAAiARATQASASAfAAQAdAAASgSQATgTAAgiIAAj2IBjAAIAAD2QgBAogLAfQgMAegVAVQgVAWggAKQgeAMgkAAQgmAAgfgMgAFmDPQgagHgWgKQgXgMgRgPQgSgPgOgRIBThDQASAcAZAPQAYAPAjAAQAZAAANgLQANgLAAgQQAAgKgGgHQgFgHgKgFIgagJIhTgVQgXgIgSgNQgSgMgMgUQgMgVAAgfQAAgbAMgXQAKgXAUgQQATgRAbgKQAdgJAgAAQAbAAAYAFQAWAEAUAJQATAKARAOIAhAeIhOA+QgOgYgVgMQgVgNgeAAQgZAAgMAMQgMAKAAAOQAAAKAGAGQAGAGALAEIBqAcQAXAIATAOQAUANAMAVQAMAVAAAhQAAAcgLAZQgMAYgVARQgVATgcAKQgdAKgggBQgjAAgbgFgAhUDPIAAmVIEYAAIAABaIi4AAIAABDIC4AAIAABYIi4AAIAABGIC4AAIAABagAlJDPIAAk7IhvAAIAAhaIE7AAIAABaIhuAAIAAE7gAn/DPIgVg9IibAAIgWA9IhiAAICWmVIBfAAICVGVgAoyA+IgwiHIgwCHIBgAAgAupDPIAAicIiFAAIAACcIhhAAIAAmVIBhAAIAACaICFAAIAAiaIBiAAIAAGVgACxkOQgmgRgbgcQgcgcgPgmQgPgmgBgsQAAgsAQgnQAQgmAcgcQAbgcAmgPQAngQAtgBQAdABAcAHQAaAHAXANQAXANAUATQASATANAWIhUA1QgOgbgYgPQgYgQgiAAQgYAAgUAJQgVAJgOAOQgOARgIAUQgJAVAAAXQAAAXAJAVQAHAUAPAPQAOAQAUAJQAUAIAYABQAlAAAYgTQAZgTAMgdIBaAwQgNAZgSAWQgTAVgYAPQgYAQgcAIQgdAIggAAQgvAAgmgQgAwikOQgmgRgcgcQgbgcgPgmQgPgmAAgsQAAgsAQgnQAQgmAbgcQAcgcAmgPQAmgQAtgBQAdABAbAHQAbAHAXANQAYANATATQATATANAWIhVA1QgOgbgYgPQgYgQghAAQgYAAgVAJQgUAJgPAOQgOARgHAUQgJAVAAAXQAAAXAJAVQAGAUAPAPQAPAQATAJQAVAIAXABQAmAAAYgTQAYgTANgdIBaAwQgNAZgTAWQgTAVgXAPQgYAQgcAIQgdAIghAAQguAAgngQgAQ0kDIg7h7IhLAAIAAB7IhiAAIAAmXICwAAQAlAAAcALQAcAMATASQAUAUAKAYQALAaAAAcQgBAogSAfQgRAfgfASIBMCUgAOunVIBHAAQAfgBAPgPQANgQAAgYQAAgXgOgPQgPgOgeAAIhHAAgAHxkDIAAmXIEZAAIAABaIi4AAIAABDIC4AAIAABaIi4AAIAABFIC4AAIAABbgAhekDIigkAIAAEAIhcAAIAAmXIBlAAICZD0IAAj0IBcAAIAAGXgAndkDIgVg9IibAAIgWA9IhiAAICWmXIBeAAICWGXgAoQmVIgwiIIgwCIIBgAAg");
	this.shape.setTransform(2.5,3.45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_cancerHatesUs, new cjs.Rectangle(-115.7,-63.8,236.4,134.5), null);


(lib.txt_cancerHatesFighters = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ATbKwQgcgHgWgLQgXgLgRgPQgTgQgOgRIBVhFQATAcAYAQQAZAPAkAAQAZAAANgLQAOgLAAgRQAAgKgFgHQgGgHgKgFIgbgJIhVgXQgXgHgSgNQgUgOgMgVQgMgVABggQAAgbALgYQALgXAVgRQATgRAcgKQAdgKAhAAQAdAAAWAFQAYAFAUAJQAUAKARAOIAiAgIhQA+QgPgYgVgNQgVgMggAAQgZAAgMALQgMALAAAPQAAAJAGAGQAGAHALAEIBtAdQAXAIAUAOQAUAOANAVQAMAWAAAiQAAAdgMAZQgMAZgVASQgVASgdALQgeAKghAAQgjAAgcgGgAGsKlQgngRgcgdQgdgcgRgnQgQgnAAgtQAAgsAQgnQARgnAdgdQAcgdAngRQAngRAtAAQAsAAAnARQAnARAcAdQAeAdAQAnQAQAnAAAsQAAAtgQAnQgRAngdAcQgcAdgnARQgnARgsAAQgtAAgngRgAHTF1QgWAJgOAQQgPAQgJAVQgIAVAAAYQAAAYAIAVQAIAVAQAQQAPAQAVAJQAUAJAZAAQAYAAAVgJQAUgJAQgQQAPgQAIgVQAJgVgBgYQABgYgJgVQgIgVgPgQQgQgQgVgJQgVgJgXAAQgZAAgUAJgAPwKwIg7h9IhOAAIAAB9IhjAAIAAmgICzAAQAmAAAdAMQAdALATATQAVAUAKAaQAKAaAAAdQAAAogSAgQgSAhggASIBPCWgANnHZIBJAAQAgAAAPgQQAOgQAAgYQAAgZgPgPQgPgOgfAAIhJAAgACWKwIAAmgIBlAAIAAGggAADKwIg5h9IhOAAIAAB9IhjAAIAAmgICzAAQAlAAAcAMQAdALAUATQAUAUAKAaQAKAaAAAdQAAAogSAgQgSAhgfASIBOCWgAiEHZIBIAAQAgAAAPgQQAOgQAAgYQAAgZgPgPQgOgOggAAIhIAAgAmDKwIg7h9IhOAAIAAB9IhjAAIAAmgICzAAQAmAAAdAMQAdALAUATQAUAUAKAaQALAaAAAdQAAAogSAgQgTAhgfASIBOCWgAoMHZIBJAAQAgAAAPgQQAPgQAAgYQAAgZgPgPQgQgOgfAAIhJAAgAroKwIgVg+IifAAIgWA+IhlAAICamgIBgAAICaGggAscIbIgxiLIgxCLIBiAAgAzbKwIhJkGIhIEGIhjAAIhymgIBlAAIBAEBIBIkBIBgAAIBIEBIBBkBIBkAAIh0GggAjYDGQgngRgdgdQgcgdgPgnQgPgnAAgsQAAgtAPgnQARgnAcgdQAdgdAngQQAmgQAvAAQAeAAAcAHQAbAIAXANQAXAOAUATQATATAOAXIhWA3QgOgcgZgQQgYgQgjAAQgZAAgUAIQgVAKgPAPQgPAQgHAVQgJAWAAAXQAAAYAIAUQAIAVAPAQQAOAQAVAJQAUAJAZAAQAmAAAZgTQAZgTANgeIBbAxQgNAagUAVQgTAWgXAQQgYAPgeAJQgdAIghAAQgwAAgngQgA2+DGQgngRgbgdQgcgdgQgnQgQgnAAgsQAAgtAQgnQAQgnAdgdQAdgdAngQQAmgQAvAAQAeAAAbAHQAcAIAXANQAZAOATATQAUATANAXIhXA3QgPgcgYgQQgYgQgjAAQgZAAgUAIQgVAKgPAPQgPAQgHAVQgJAWAAAXQAAAYAIAUQAIAVAPAQQAPAQAUAJQAVAJAYAAQAmAAAZgTQAZgTANgeIBcAxQgNAagTAVQgUAWgYAQQgYAPgeAJQgdAIghAAQgwAAgogQgAKkDRIg7h9IhOAAIAAB9IhjAAIAAmfICzAAQAmAAAdALQAdALATAUQAVATAKAaQAKAaAAAeQAAAogSAfQgSAgggASIBPCXgAIbgFIBJAAQAgAAAPgQQAPgRAAgXQgBgagPgOQgPgPgfAAIhJAAgABkDRIAAmfIEfAAIAABcIi8AAIAABFIC8AAIAABbIi8AAIAABGIC8AAIAABdgAnmDRIikkFIAAEFIheAAIAAmfIBnAAICdD4IAAj4IBeAAIAAGfgAtsDRIgVg+IigAAIgVA+IhkAAICamfIBfAAICaGfgAugA8IgxiLIgwCLIBhAAgACGkOQgcgHgWgLQgXgLgRgPQgSgQgPgRIBVhFQASAcAZAQQAaAPAjAAQAZAAANgLQAOgLAAgRQAAgKgFgHQgGgHgLgFIhvggQgXgHgTgNQgSgOgMgVQgMgVAAggQgBgbAMgYQAMgXATgRQAVgRAbgKQAdgKAhAAQAdAAAWAFQAYAFAUAJQATAKASAOIAiAgIhQA+QgPgYgVgNQgVgMggAAQgZAAgMALQgMALAAAPQAAAJAGAGQAGAHALAEIBsAdQAYAIAUAOQAUAOANAVQAMAWAAAiQAAAdgMAZQgMAZgVASQgVASgdALQgeAKghAAQgjAAgcgGgAUkkOIAAmgIEfAAIAABdIi8AAIAABEIC8AAIAABcIi8AAIAABHIC8AAIAABcgASSkOIg7h9IhNAAIAAB9IhjAAIAAmgICyAAQAmAAAdAMQAdALAUATQAUAUAKAaQALAaAAAdQgBAogRAgQgTAhgfASIBOCWgAQKnlIBIAAQAgAAAPgQQAPgQAAgYQAAgZgPgPQgQgOgfAAIhIAAgAMJkOIAAmgIBkAAIAAGggAGQkOIAAmgICnAAQAkAAAeAMQAdANAWAVQAUAVAMAcQAMAcAAAgQAAAggMAcQgMAcgUAWQgVAVgeANQgeANgkAAIhDAAIAABogAH0nTIA9AAQAcAAATgRQASgSAAgdQAAgdgSgSQgTgSgcAAIg9AAgAhskOIikkFIAAEFIheAAIAAmgIBnAAICdD6IAAj6IBeAAIAAGggAoNkOIAAmgIBlAAIAAGggAvekOIAAmgIEfAAIAABdIi8AAIAABEIC8AAIAABcIi8AAIAABHIC8AAIAABcgAzbkOIhJkGIhIEGIhjAAIhymgIBlAAIBAEBIBIkBIBgAAIBIEBIBBkBIBkAAIh0Ggg");
	this.shape.setTransform(41.6,17.725);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_cancerHatesFighters, new cjs.Rectangle(-118.6,-51.6,320.5,138.7), null);


(lib.txt_advancedTreatment = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADzKYQgbgGgVgLQgWgKgSgPQgRgPgOgRIBShCQASAbAYAPQAZAPAhAAQAZAAANgLQANgKAAgRQAAgKgGgGQgEgHgLgFIhrgeQgXgIgSgNQgSgNgLgUQgMgUAAgfQAAgbALgWQALgXATgQQAUgRAagJQAcgJAgAAQAbAAAXAEQAXAFASAJQATAJARAOIAhAeIhNA8QgPgWgUgNQgUgMgeAAQgZAAgMALQgMALAAAOQAAAJAHAGQAFAGALAEIBoAcQAXAIAUANQATAOAMAUQAMAVAAAhQAAAdgLAXQgMAYgUASQgVASgcAJQgcAKghAAQghAAgbgGgAixKZIAAmSIBgAAIAAE2ICuAAIAABcgAk3KZIgVg8IiaAAIgUA8IhhAAICVmSIBcAAICUGSgAlpIJIgviGIgwCGIBfAAgArhKZIAAmSIBhAAIAAGSgAuAKZIg5h5IhLAAIAAB5IhgAAIAAmSICtAAQAkAAAcALQAcALAUATQATATAJAZQALAZgBAcQAAAngRAfQgRAfgeARIBKCSgAwEHJIBGAAQAeAAAPgPQAOgQAAgXQAAgYgOgOQgPgOgeAAIhGAAgA1fKZIAAk5IhtAAIAAhZIE3AAIAABZIhsAAIAAE5gANLC/QgmgRgbgcQgbgbgPgmQgPgmAAgrQAAgqAPgmQAQgmAbgcQAbgbAmgQQAmgQAsAAQAdAAAbAHQAaAIAYANQAXAMASATQATASANAWIhUA2QgNgbgYgQQgYgQghAAQgYAAgUAJQgUAJgOAPQgOAPgIAVQgJAUAAAWQAAAYAIAUQAJAUANAPQAPAPATAJQAUAJAYAAQAkAAAZgTQAYgSANgdIBYAwQgMAYgUAVQgSAVgXAPQgYAPgcAJQgdAIggAAQgtAAgmgQgAqTDJQgcgGgVgLQgWgLgRgPQgSgOgNgSIBShBQASAaAXAPQAZAPAiAAQAYAAANgKQANgLAAgQQAAgKgFgHQgFgHgLgEIhrgfQgWgHgSgNQgTgMgLgUQgMgVAAgfQABgaAKgXQALgWAUgRQATgQAbgKQAbgJAgAAQAbAAAXAFQAXAEATAKQASAJASANIAgAfIhMA8QgPgXgUgMQgVgNgeAAQgZAAgMALQgLALAAAOQAAAJAGAGQAGAHAKAEIBpAcQAXAHAUANQASANAMAVQAMAVAAAgQABAdgMAYQgLAYgVARQgUASgdAKQgbAKgiAAQghAAgagGgAVtDJIAAiaIiDAAIAACaIhhAAIAAmQIBhAAIAACYICDAAIAAiYIBgAAIAAGQgAJHDJIg5h4IhMAAIAAB4IhfAAIAAmQICtAAQAjAAAdALQAcALATATQATASAKAZQAKAZAAAdQAAAmgRAeQgSAggeARIBLCRgAHCgFIBGAAQAfAAAOgQQAPgPAAgXQAAgZgPgOQgOgOgfAAIhGAAgADdDJIgVg8IiaAAIgUA8IhgAAICUmQIBbAAICVGQgACrA6IgviGIgwCGIBfAAgAmGDJIAAmQIEVAAIAABZIi2AAIAABCIC2AAIAABYIi2AAIAABEIC2AAIAABZgAxEDJIAAmQIEVAAIAABZIi2AAIAABCIC2AAIAABYIi2AAIAABEIC2AAIAABZgAzcDJIg5h4IhMAAIAAB4IhfAAIAAmQICtAAQAjAAAdALQAcALATATQATASAKAZQAKAZAAAdQAAAmgSAeQgRAggeARIBLCRgA1hgFIBGAAQAfAAAPgQQAOgPAAgXQAAgZgOgOQgPgOgfAAIhGAAgARxkIQgYgIgQgPQgQgPgJgUQgIgUAAgYQAAgUAGgPQAHgRAKgNQALgNAOgLIAdgVIgRgWIgKgVIgGgWIgCgZQAAgVAJgTQAJgSAPgOQAPgOAVgIQAUgIAYAAQAXAAAVAHQAVAIAPAOQAPANAJATQAIASAAAVQAAASgEAOQgGAOgJAMQgJAMgLALIgZAUIAnAmIA+hKIBtAAIhuCCIByBwIh8AAIgvgvIgeAZQgPAKgOAGQgOAGgPADIggACQgdAAgYgIgASRmOQgKALAAANQAAARALAJQAKAKARAAQAOAAAMgFQAMgGAQgPIg5g4QgPALgKALgASwpKQgJAHABAMQgBAMAFAKQAFAKANAOQAPgKAJgLQAKgLAAgOQAAgMgJgHQgIgHgLAAQgMAAgIAHgAJikQQgngRgbgcQgbgcgPgmQgPglAAgqQAAgrAQgnQAQglAbgcQAagbAmgQQAmgQAuAAQA6AAArAWQAqAWAdAlIhRA4QgOgWgXgNQgWgMgfAAQgYAAgTAJQgVAJgPAPQgPAQgJAVQgJAVAAAZQAAAaAJAVQAHAVAPAPQAQAPAUAJQAWAIAZAAQAiAAAXgRQAZgQAKgeIhwAAIAAhZIDXAAIAAAuQAAAngNAkQgOAkgaAbQgZAbgkAQQglAQgrAAQgxAAgngQgAq4kGQgbgGgWgLQgVgKgSgPQgRgPgOgRIBThCQARAbAYAPQAYAPAjAAQAYAAANgLQAMgKAAgRQAAgKgEgGQgGgHgKgFIhrgeQgXgIgSgNQgSgNgMgUQgLgUAAgfQAAgbALgWQALgXATgQQAUgRAagJQAbgJAhAAQAbAAAXAEQAWAFAUAJQASAJARAOIAhAeIhNA8QgOgWgVgNQgUgMgfAAQgZAAgLALQgLALAAAOQAAAJAFAGQAGAGALAEIBpAcQAXAIATANQATAOAMAUQAMAVAAAhQAAAdgMAXQgLAYgUASQgVASgcAJQgcAKghAAQgiAAgagGgAFLkFIiej9IAAD9IhbAAIAAmSIBjAAICYDxIAAjxIBbAAIAAGSgAhSkFIAAmSIBgAAIAAGSgAlOkFIAAk5IhtAAIAAhZIE2AAIAABZIhsAAIAAE5gAxokFIAAmSIEUAAIAABZIi1AAIAABCIC1AAIAABZIi1AAIAABFIC1AAIAABZgA1VkFIAAk5IhtAAIAAhZIE3AAIAABZIhsAAIAAE5g");
	this.shape.setTransform(31.65,18.575);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_advancedTreatment, new cjs.Rectangle(-116.8,-48.4,297,134), null);


(lib.safeCare_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.749)").s().p("AhYFIQhmgZhGhOIgCgDIhyANIBtgtIAAABIAHAIIAAABQBCBSBlAcQBlAcBigoQBigpA1heQAzhcgNhoIgBgJIBuguIhaBJIAAAEQAEBYgnBQQgoBQhKAwQgbARgaALQg8AZg9AAQgnAAgogKgAhgEtQhmgdg/hVIAEgBQA/BTBjAcQBkAeBggoQBhgoAyhcQAyhbgOhmIADgBQANBZgkBTQglBThLAxQgcARgVAJQg4AXg5AAQgrAAgrgNgAmdDUIhYgmIBMgfIAnBfIABABIB3gNIi2BLgAgJEJIgCgbIALAAQAJgBABAKQAAAKgKAAIgEABIAAAHgAgFDzIAAAKIAFgBQAEAAAAgFQAAgFgEAAgAAMDtIALgCQAEAAADACQADACABAEQABAFgEADIAHAJIgGABIgGgIIgGABIACAJIgFABgAAXDwIgFABIABAJIAGgBQAFgBgBgFQgBgDgDAAIgCAAgAg7EFIADgbIASADIAAAFIgNgCIgBAGIANACIgBAEIgMgBIgBAGIAMACIAAAFgAhHECIgDgJIgFgCIgCAIIgFgBIAGgaIAKADQAKACgCAJQgBAFgGACIADALgAhODzIAFABQAFABABgEQABgFgFgBIgFgBgAgZEDQgEAAAAgEQAAgFAFABQAEAAAAAEQgBAEgDAAIgBAAgAAlDpIARgFIACAFIgNADIACAGIAMgDIACAEIgNAEIACAGIAMgEIABAFIgRAFgAhgD7IAAgFIgLgEIgDAEIgFgCIASgWIAFACIABAdgAhoDuIAIADIAAgMgAA6DjIAFgCIAOAQIAAgVIAFgCIAAAdIgEACgABWDYIAQgJIACAFIgLAGIACAFIAMgGIACAEIgLAGIADAGIALgGIACAEIgQAJgAiFDrIALgZIAKAFQAIAEgDAJQgFAKgJgFIgEgCIgDAGgAh7DiIAEACQAFADACgFQACgEgFgDIgEgCgAm5BgIFaiOIACgBIAJgDIAAgBIAdgMIACAAIAHgDIAEgCIAOgGIACAAIAFgDIACAAIAGgDIABAAIAIgEIAAAAIB1gwIAEgCIDshiIA5CLIh0AwIgBAAIgBABIgBAAIiuBHIgDACIg8AYIAAABIgJADIAAAAIgHADIgBAAIgGADIgCABIgFACIgCABIgFACIgCAAIgLAFIgCABIgFACIgBABIgOAGIgBAAIgIADIgBAAIg7AZIgDABIixBKIgBAAIgBABIhzAvgAl3C1QAWALAWgJQAVgJABgTQABgHgDgGQgDgIgHgEQgIgFgTADIgOABQgFAAgCgDQgBgDACgDQABgDAFgDQAFgCAGAAQAFABAGAEIAKgTIgDgCQgSgIgSAIQgLAFgGAJQgGAJACAJIACAHQAEALAMADQAHACANgCIAOgCQAGAAABAEQAEAIgLAFQgNAFgNgJgAkrBFIAEBeIABADIAIgDIABgBIAFgCIABAAIACgBIAAAAIACgBIABAAIgBgOIAfgOIAKALIAUgIIhChIgAjvAsIAjBVIAUgIIgNggIAlgQIgIgSIglAPIgGgPIAlgQIgIgTgAinAOIALAdIABAAIAXA4IA5gYIgIgSIglAPIgBgCIgEgJIgBgDIAAAAIAlgQIgCgFIAAgBIgGgNIglAQIgFgNIgBgBIAmgQIgIgRgAgXAXIAAAAIgBAEIAAABIABADIABABIABADIAJAVIACAAIAFgCIABgBIADgBIADgCIgSgvgAAAAiIAEgCIABAAIADgCIAAAAIADgBIABgBIACAAIAAgCIgBgCIgCgEIgDgHIgBgBIgVgKgAgvAPIABACIAAABIABACIAAABIABADIAAAAIAEAIIAJgEIADgBIABgBIAKgXIgSAIIgCAAIgGADIAAAAgAg3gCIgDABIgIACIgDACIABACIABAEIABACIADAIIABAAIAXgKIADAAIASgIIgWgIIgCAAIAAAAIgCABIgBAAgAgNABIAWAKIACgBIAEgBIACgBIABgBIALgEIAAAAIAIgDIgBgDIgBgCIgBgDIgBgCIgCgGgABNhYIgIAEQgLAIgFAMIgCAEQgCAHAAAFIAAAKIACAIIACADIAAACIABACIADAFIABACIAFAFIABABIAKAIQAQAIAUgGIADgBQAGgCAFgEIAGgFQALgNAAgPIgWgDIAAAEQgCAJgGAFIgGAEIAAAAIgHACQgHABgGgDIgFgEIgFgFIgCgFIgCgHIAAgHIACgHQAEgIAIgEIAFgBQAKgCAHAFIABABIAAAAIACABIADgEIAAgBIAJgNQgMgJgPAAIgEAAQgIABgGACgAgRAAIgJgUIAAgBIgEgKIgFACIgBAAIgGADIgBAAIgDABIAAABIABABIADAIIABADIABACIACABIACABIATAIgAAHgcIgFACIgCABIgCABIgBABIgBAAIgBACIgIAVIAVgJIAAAAIAHgDIAAgBIgCgFIAAgBIgCgDIAAAAIgBgDIAAgBIgBgDgAgUg1IgCABIgDABIgJAEIAHASIABACIACAFIAAABIAJAVIAJgYIgBgCIgBgDIgBAAIgKgYgACOhxIAFBhIAUgIIgBgPIACAAIAdgNIAKALIAUgIIhChIgADziaIgJADIgkAPIAjBUIAUgIIgLgZIAQgHIAVAUIABABIABAAIAAgBIABAAIAUgIIgcgYIADgFQADgIgBgIIgCgKQgCgFgEgFIgCgBQgFgGgIgBIgJgBgAESioIAjBVIA5gYIgHgTIgmAQIgGgPIAmgPIgIgTIgmAQIgFgOIAlgQIgIgTgAibDeIAOgXIAPAJIgCAFIgLgHIgDAFIALAHIgDAEIgLgHIgDAGIALAGIgCAFgABqDNIAFgEIAUAJIgKgPIAEgDIAPAXIgEADIgVgJIALAQIgFACgAilDXIACgJIgFgEIgFAHIgEgDIAQgWIAIAHQAIAGgFAHQgDAFgFgBIgCALgAilDGIAEAEQAEADADgEQACgEgEgDIgEgDgACJC8IgFAFIgEgEIAQgNIADAEIgGAFIAOARIgDADgAhYCyQghgOgZgYIAEgCQAZAYAfANQAiAOAlABQAkAAAigOQAjgOAagbQAZgaAOgjQANgfABgiIAEgCQgBAkgNAhQgWA4gyAfQgLAIgTAIQgjAPglAAQglgBgkgPgAi4C+IgEgEIgFAGIgEgEIASgUIAIAHQAHAHgGAHQgDADgEABQgEAAgDgDgAi5C2IAEAEQADAEAEgEQADgDgEgFIgEgDgACfC5QgDgDADgDQADgDADADQADAEgDACIgDACIgDgCgAhUCnQgbgMgXgUIAmgQIACABIACgDIACAAIgDAEIALAHIAIgSIAFgCIgMAUIALAGIABAAIAKgeIAGgDIgPAhIAMAFIAJgoIAIgDIgQArIANADIAGgwIAIgDIgNAzIANADIABg3IAIgDIgJA6IAOAAIgEg6IAHgDIABAAIAUgJIABgBIAGgCIABgBIANgFIABAAIAHgDIABgBIAHgDIAmAsIAJgKIgugiIAIgDIAmAkIAIgKIgtgbIAIgDIAlAdIAHgLIgpgTIAIgEIAhAWIAGgMIghgMIAGgDIAbAOIAEgMIgVgGIAFgCIAQAHQADgHAAgGIgDgBIACAAIACAAIAAgBIAmgQQgCArgWAlQgVAmgkAXQgNAJgPAGQghAOghAAQgjAAgjgPgAgRCdQgDADABAEQAAAEADACQADADADAAQAKgBgBgJQAAgEgDgDQgCgCgEAAQgEAAgDADgAgyCfQgBAKAJABQAGACADgFIgDgDQgDACgCAAQgFgBABgFQABgFAEABQADABABACIAEgBQgBgFgGgBIgDAAQgGAAgCAHgAAHCZIALARIAEgBIADgUIgFABIgBANIgHgLgAAjCSIAHARIAEgBIgGgSgAA5CIIgGADIAJAQIAGgDQAIgEgEgJQgDgFgFAAIgFACgAgOCRIAOAAIgKg7gAAACRIAMgCIgOg6gAANCOIANgDIgVg4gAAbCLIALgEIABgBIgag1gAAoCGIALgGIgfgygABQCCIADADIAHgGIgDgDgAA0CAIALgHIgkgvgABAB5IAKgIIgogsgABsB3IADgDIgOgNIgDADQAEADgDAEIgBAAIAEADIAAgBQAAAAABAAQAAgBAAgBQABAAAAgBQAAAAgBgBgABLBwIAJgJIgrgngAB3BjIgCACIACAEIAEgEQAEgHgIgGQgDgCgDAAQgEABgBACQgEAFAFAEQAGAEADgFQAAgBAAAAQABgBAAAAQAAgBAAAAQAAgBgBAAQADACgCAEgACgCfIAHgJQAGgHAIAGQAHAGgGAIIgDAEIAFAFIgDAEgACqCaIgDAEIAIAGIADgEQADgEgEgDIgDgBQgBAAAAAAQAAAAgBAAQAAAAgBABQAAAAgBABgAgPCkQAAgGAFAAQAFAAAAAFQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQgEAAgBgFgACvCMIAGgJQAFgJAIAGQAFADgBAFIALABIgDAFIgKgBIgDAFIAHAFIgDAEgAC4CGIgCAEIAHAFIADgEQADgEgEgDIgDgBQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABgAA5CNIACgBQAFgEACAGQADAEgFADIgCABgADHB/QgFgCgCgGQgCgGADgFQACgFAGgCQAFgBAFACQAFADACAFQACAGgDAFQgCAFgFACIgEABQgEAAgDgCgADKBqQgDABgCAEQgBADABADQABAEADABQAIAFAEgIQAEgIgIgEIgEgBIgDAAgAkXBbIAWAYIgUAIgADOBaIgCAHIgFgCIAHgTIAFACIgDAHIAVAIIgCAFgABwBeQgBAAAAAAQgBgBAAAAQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAQABAAABAAQAAABAAAAQABABAAAAQAAAAAAABQgBAAAAABIgCABIgBgBgADQBIIAEgSIAFABIgDANIAFACIAEgNIAEABIgDANIAGACIADgNIAFABIgFASgADiA1QgGgBgDgFQgDgFABgFQAAgIAIgDIACAFQgEABgBAFQgBAEACADQACADAEAAQAEABACgCQADgCABgEQABgFgFgDIADgEQAHAFgBAIQgBAGgFADQgDADgEAAIgDAAgAk1ijQA3hoBsgtQBrgsBwAiQBvAiBDBfIgQAHQhAhZhoggQhpgghmAqQgdANgVANQhOAzglBXQgmBXAPBcIgPAHQgUhyA2hmgAkfiaQA0hfBigpQA5gXA9AAQA8ABA5AYQBPAiA0BGIgEACQgyhEhPgiQg4gYg7gBQg8AAg4AXQgaAKgXAPQhKAxglBTQgkBSAOBZIgEABQgQhoAyhdgADZAWIAAgUIAFAAIAAAIIAWABIAAAFIgWgBIgBAIgAjBhLQAPgkAagaQAagbAjgOQAjgPAmAAQAkABAkAPQAiAPAaAaIgEABQgagZgggOQgigOgkgBQglAAgiAOQgRAIgNAIQgwAfgWA3QgOAiAAAjIgEABQAAglAOgjgAkagJIABgQQABgPALABQAGABACAEQACgEAGAAQAMABgBAPIgBAQgAkCgXIAAAGIAHABIABgHQABgFgFAAIAAAAQgDAAgBAFgAkRgZIgBAHIAIABIAAgHQAAgFgDAAQgEAAAAAEgAikhnQAdgsAxgUQAwgUA0AKQAyAKAmAkIglAPIgDgCIgDAFIgDABIAFgHIgLgHIgJAUIgGACIAOgWIgMgGIgKAgIgHADIAQgjQgGgDgGgCIgKAqIgHADIAQgtIgNgEIgGAyIgHAEIANg2IgNgCIgBA4IgQAHIgBAAIgGADIgBAAIgUAIIgBABIgVAIIAAABIgIADIgoguIgJAKIAxAkIgIADIgqgnIgHALIAwAdIgJADIgogfIgHALIAtAVIgIADIglgXIgGAMIAmAOIgHACIgfgPIgEANIAaAGIgGACIgUgIIgDANIAIACIgDABIgGgCIAAAFIgmAPQACg0AdgrgAhIg+IgkgyIgKAJIAuApgAhChDIgfg2IgKAIIApAugAg7hIIgag4IgKAGIgBABIAlAxgAg0hMIgUg6IgMAGIAgA0gAgthPIgOg8IgMAFIAaA3gAglhSIgIg8IgNADIAVA5gAgdhTIgCg9IgNACIAPA7gAgMhUIAJg7IgOgBgAgfiQIAKA8IAEg8gAibhkQgFAHAHAGQADADAEgBQAEAAACgEQADgEgCgGIgEACQAAABAAABQAAAAAAABQAAAAAAABQAAABAAAAQgDAFgEgEQgEgCACgFQACgCADAAIAAgEQgGAAgCAEgAiHh8QgCACAAAEQAAAEACADQADADAEAAQAEAAADgDQACgCAAgEQAAgEgCgDQgDgDgEAAQgEAAgDADgAh2iLIAQAMIADgCIgEgTIgEACIADANIgKgIgAhaibIAIARIAEgCIgIgRgAhBilIgHACIAGASIAGgCQAJgCgDgJQgCgHgGAAIgDAAgAACiYIAFACQAJACABgKQABgEgBgDQgCgDgDgBQgHgBgBAHQgBAGAGABQAAAAABAAQAAAAABAAQAAAAABgBQAAAAABAAQgBADgEAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBAAAAgBgAgNiZIAFABIAAgTIgEAAQAAAFgFgBIAAAEIABAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAABgBgAgoiiIAAAEIAKgBIgBgEgAGehcIAAAAIgohgIBLgeIgjBYIBYAmIi2BLgAj4gpQgKgCADgNIABgHQgEgBgBAFQAAAEACACIgGAIQgFgHACgJQADgNAMACIARAFIgCAIIgEgBQAEAFgCAGQgBAJgGAAIgDgBgAj5g4QAAAFACAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAgBQABgGgEgCIAAgBgAhOg4gACjhbIAVAYIgTAIgAjnhHQABAAAAAAQABgBAAAAQABAAAAgBQAAAAAAgBQABgDgDgDIgBgBIgeABIADgJIASAAIgNgMIADgJIAZAXQAIAHgDAJQgCAFgEADgAkDh5IAEgIIAmAUIgEAIgADhh+IAPgGQAMgFAFALQAEALgMAFIgOAGgAiDhyQgEgEADgDQAFgEADAEQADAEgDADQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAgBAAAAgAjkh4QgGgEgBgGQgCgGAEgGQADgGAHgBQAGgCAFAEQAGAEABAGQABAGgDAGQgEAGgGABIgDAAQgEAAgEgCgAjiiJQgDAFAFAEQAGAEADgGQAEgGgGgDIgEgCQgDAAgCAEgAjcihIAGgHIADADQgDgFAFgEIAEgEIAFAJIgEACQgEAFAFAEIAMAKIgGAHgAhCigIACAAQAFgCABAFQABAGgEAAIgCABgAAJijQAAAAAAgBQAAAAAAAAQABAAAAgBQABAAAAAAQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBgACAitQgFgFgBgGQAAgGAEgFQAEgFAGAAQAGgBAFAEQAFAFABAGQAAAGgEAFIgCADIgQgPQgCAFAEADQADACAEAAIACAIIgEAAQgFAAgFgEgACHjAIAKAIQABgDgDgEQgBAAAAAAQgBgBgBAAQAAAAgBAAQAAAAgBAAIgDAAgAi1isIACgKQAGACAFgEQAEgEgDgCQgCgCgHADQgLAHgGgIQgDgEABgFQAAgFAFgEQAHgGAKABIgCAJQgFgBgFADQgEAEADACQACABAHgDQALgGAGAHQAEAEgBAGQgBAGgFAEQgGAGgIAAIgEgBgABui7QgIgGAGgKIAFgIIgEgDIAFgHIAEADIADgGIAKABIgGAKIAGAEIgEAHIgGgEIgFAIQgBABAAAAQAAABAAAAQAAABAAABQAAAAABAAIACABIAAAIIgBAAQgDAAgEgCgAiUjCQgGgCgEgFQgDgFABgHQABgGAGgDQAJgGAIAGIgFAIQgDgDgEACQgCABgBADQgBADACACQADAGAGgEQADgCgBgEIAKgCQABALgJAFQgEADgEAAIgDgBgABVjLIAOgaIAIAEIgNAagABIjSIAGgPQADgFgFgCQgEgBgCAFIgGAPIgJgEIARgoIAIAEIgGAPQADgCAFACQAKAEgEALIgHARgAh7jRQgGgDgCgGQgDgGACgGQACgGAHgCQAGgDAGACQAGADACAFQADAGgCAGQgCAGgHADIgGACIgGgBgAh4jmQgFADACAGQADAGAGgDQAGgCgDgHQgCgEgDAAIgEABgAhejlIgDgKIgFABIgDgHIAFgCIgCgGIAHgHIAEAKIAGgCIADAIIgHACIADAKQAAABABAAQAAABAAAAQABABAAAAQABAAABgBQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAIAGAFQgDAEgEABIgEABQgGAAgDgJgAAkjfIgCgaIgMAXIgJgCIgDgqIAKADIABAZIAMgXIAIACIACAaIALgXIAJADIgSAkgAhHjsIgCgKIgFABIgBgIIAEgBIgBgGIAIgHIACALIAHgBIACAIIgHABIACAKQAAABAAAAQABABAAAAQABABAAAAQABAAAAAAIACgBIAGAGQgEADgDABIgDAAQgHAAgDgKgABojlQgEgDACgEQADgFAEACQAGADgDAFQgCADgDAAIgDgBgAgljoQgEgEAAgEQAAgGAIgGQgEgEAAgEQAAgFADgDQADgDAFAAQALAAAAAKQAAAFgGAFIAEAEIAGgHIALAAIgLANIALALIgMAAIgEgFQgGAGgGAAQgGAAgDgDgAgfjxQAAABAAAAQAAABABAAQAAABABAAQAAAAABAAQADAAADgCIgGgGQgDADAAACgAgdkFQABADACACQADgCAAgDQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQAAABgBAAQAAABAAAAg");
	this.shape.setTransform(0.025,0.0143);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.safeCare_logo, new cjs.Rectangle(-50.1,-33.7,100.30000000000001,67.5), null);


(lib.BSWH_Icon = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// blue_bottom
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1B449D").s().p("AgFAQIAAgUIALgLIAAAfg");
	this.shape.setTransform(-0.625,1.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1B449D").s().p("AgWBBIAAhUIAtgtIAACBg");
	this.shape_1.setTransform(-2.525,6.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1B449D").s().p("AgkBsIAAiMIBJhLIAADXg");
	this.shape_2.setTransform(-4.175,11.275);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1B449D").s().p("AgxCQIAAi8IBihjIAAEfg");
	this.shape_3.setTransform(-5.55,15.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1B449D").s().p("Ag7CtIAAjiIB3h3IAAFZg");
	this.shape_4.setTransform(-6.675,18.15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1B449D").s().p("AhDDEIAAkAICHiHIAAGHg");
	this.shape_5.setTransform(-7.575,20.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1B449D").s().p("AhIDUIAAkVICRiTIAAGog");
	this.shape_6.setTransform(-8.225,22.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1B449D").s().p("AhMDeIAAkiICYiZIAAG7g");
	this.shape_7.setTransform(-8.6,23.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1B449D").s().p("AhNDiIAAknICbicIAAHDg");
	this.shape_8.setTransform(-8.725,23.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},5).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_8}]},6).to({state:[]},1).wait(352));

	// blue_Rt
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1B449D").s().p("AgEAFIgLgKIAfAAIAAAKg");
	this.shape_9.setTransform(1.7,0.65);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1B449D").s().p("AgTAWIgtgsICBAAIAAAsg");
	this.shape_10.setTransform(6.825,2.55);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#1B449D").s().p("AggAlIhLhJIDXAAIAABJg");
	this.shape_11.setTransform(11.275,4.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#1B449D").s().p("AgsAyIhjhiIEfAAIAABig");
	this.shape_12.setTransform(15.075,5.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1B449D").s().p("Ag1A8Ih3h3IFZAAIAAB3g");
	this.shape_13.setTransform(18.15,6.775);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#1B449D").s().p("Ag8BEIiHiHIGHAAIAACHg");
	this.shape_14.setTransform(20.525,7.675);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#1B449D").s().p("AhBBJIiTiRIGoAAIAACRg");
	this.shape_15.setTransform(22.25,8.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#1B449D").s().p("AhEBNIiZiYIG7AAIAACYg");
	this.shape_16.setTransform(23.3,8.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#1B449D").s().p("AhFBOIicibIHDAAIAACbg");
	this.shape_17.setTransform(23.625,8.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_9}]},9).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_17}]},2).to({state:[]},1).wait(352));

	// lt_blue_lt
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#1690BF").s().p("AgKAFIAAgKIAVAAIgLAKg");
	this.shape_18.setTransform(-1.15,0.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#1690BF").s().p("AgsAWIAAgsIBZAAIgtAsg");
	this.shape_19.setTransform(-4.725,2.55);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#1690BF").s().p("AhJAlIAAhJICTAAIhKBJg");
	this.shape_20.setTransform(-7.825,4.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#1690BF").s().p("AhhAyIAAhiIDDAAIhiBig");
	this.shape_21.setTransform(-10.425,5.65);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#1690BF").s().p("Ah1A8IAAh3IDrAAIh2B3g");
	this.shape_22.setTransform(-12.55,6.775);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#1690BF").s().p("AiFBEIAAiHIELAAIiHCHg");
	this.shape_23.setTransform(-14.225,7.675);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#1690BF").s().p("AiQBJIAAiRIEhAAIiSCRg");
	this.shape_24.setTransform(-15.425,8.325);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#1690BF").s().p("AiXBNIAAiYIEvAAIiYCYg");
	this.shape_25.setTransform(-16.15,8.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#1690BF").s().p("AiZBOIAAibIEzAAIibCbg");
	this.shape_26.setTransform(-16.375,8.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18}]}).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_26}]},11).to({state:[]},1).wait(352));

	// blue_lt
	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#1B449D").s().p("AgPAGIAAgLIAUAAIALALg");
	this.shape_27.setTransform(-1.675,-0.625);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#1B449D").s().p("AhAAXIAAgtIBUAAIAtAtg");
	this.shape_28.setTransform(-6.8,-2.525);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#1B449D").s().p("AhrAlIAAhJICMAAIBLBJg");
	this.shape_29.setTransform(-11.25,-4.175);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#1B449D").s().p("AiPAyIAAhiIC8AAIBjBig");
	this.shape_30.setTransform(-15,-5.6);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#1B449D").s().p("AitA8IAAh3IDjAAIB4B3g");
	this.shape_31.setTransform(-18.075,-6.725);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#1B449D").s().p("AjEBEIAAiHIEAAAICICHg");
	this.shape_32.setTransform(-20.45,-7.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#1B449D").s().p("AjUBJIAAiRIEWAAICTCRg");
	this.shape_33.setTransform(-22.175,-8.275);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#1B449D").s().p("AjeBNIAAiYIEjAAICaCYg");
	this.shape_34.setTransform(-23.225,-8.65);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#1B449D").s().p("AjhBOIAAibIEnAAICcCbg");
	this.shape_35.setTransform(-23.55,-8.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_27}]},7).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_35}]},4).to({state:[]},1).wait(352));

	// yellow_top
	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FDB61B").s().p("AgFAAIAAgKIALAAIAAAVg");
	this.shape_36.setTransform(-0.625,-1.15);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FDB61B").s().p("AgWAAIAAgsIAtAAIAABZg");
	this.shape_37.setTransform(-2.525,-4.725);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FDB61B").s().p("AgkAAIAAhJIBJAAIAACTg");
	this.shape_38.setTransform(-4.175,-7.825);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FDB61B").s().p("AgxAAIAAhhIBiAAIAADDg");
	this.shape_39.setTransform(-5.55,-10.45);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FDB61B").s().p("Ag7AAIAAh1IB3AAIAADrg");
	this.shape_40.setTransform(-6.675,-12.575);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FDB61B").s().p("AhDgBIAAiEICHAAIAAELg");
	this.shape_41.setTransform(-7.575,-14.25);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FDB61B").s().p("AhIAAIAAiQICRAAIAAEhg");
	this.shape_42.setTransform(-8.225,-15.45);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FDB61B").s().p("AhMAAIAAiXICYAAIAAEvg");
	this.shape_43.setTransform(-8.6,-16.175);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FDB61B").s().p("AhNgBIAAiYICbAAIAAEzg");
	this.shape_44.setTransform(-8.725,-16.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_36}]}).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_44}]},11).to({state:[]},1).wait(352));

	// blue_top
	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#1B449D").s().p("AgFgPIAKAAIAAAUIgKALg");
	this.shape_45.setTransform(0.65,-1.675);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#1B449D").s().p("AgWhAIAsAAIAABUIgsAtg");
	this.shape_46.setTransform(2.55,-6.8);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#1B449D").s().p("AgkhrIBJAAIAACMIhJBLg");
	this.shape_47.setTransform(4.225,-11.25);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#1B449D").s().p("AgwiPIBiAAIAAC8IhiBjg");
	this.shape_48.setTransform(5.65,-15.025);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#1B449D").s().p("Ag7itIB3AAIAADjIh3B4g");
	this.shape_49.setTransform(6.775,-18.1);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#1B449D").s().p("AhDjDICHAAIAAEAIiHCHg");
	this.shape_50.setTransform(7.675,-20.475);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#1B449D").s().p("AhIjUICRAAIAAEWIiRCSg");
	this.shape_51.setTransform(8.325,-22.2);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#1B449D").s().p("AhLjeICYAAIAAEkIiYCZg");
	this.shape_52.setTransform(8.7,-23.25);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#1B449D").s().p("AhNjhICbAAIAAEnIibCcg");
	this.shape_53.setTransform(8.825,-23.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_45}]},5).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_53}]},6).to({state:[]},1).wait(352));

	// lt_blue_rt
	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#1690BF").s().p("AgKAGIAKgLIALAAIAAALg");
	this.shape_54.setTransform(1.2,-0.625);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#1690BF").s().p("AgsAXIAsgtIAtAAIAAAtg");
	this.shape_55.setTransform(4.775,-2.525);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#1690BF").s().p("AhJAlIBKhJIBJAAIAABJg");
	this.shape_56.setTransform(7.875,-4.175);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#1690BF").s().p("AhhAyIBihiIBhAAIAABig");
	this.shape_57.setTransform(10.525,-5.6);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#1690BF").s().p("Ah1A8IB2h3IB1AAIAAB3g");
	this.shape_58.setTransform(12.65,-6.725);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#1690BF").s().p("AiFBEICGiHICFAAIAACHg");
	this.shape_59.setTransform(14.325,-7.625);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#1690BF").s().p("AiQBJICRiRICQAAIAACRg");
	this.shape_60.setTransform(15.525,-8.275);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#1690BF").s().p("AiXBNICYiYICXAAIAACYg");
	this.shape_61.setTransform(16.25,-8.65);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#1690BF").s().p("AiZBOICaibICZAAIAACbg");
	this.shape_62.setTransform(16.475,-8.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_54}]},3).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.shape_58}]},1).to({state:[{t:this.shape_59}]},1).to({state:[{t:this.shape_60}]},1).to({state:[{t:this.shape_61}]},1).to({state:[{t:this.shape_62}]},1).to({state:[{t:this.shape_62}]},8).to({state:[]},1).wait(352));

	// yellow_bottom
	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FDB61B").s().p("AgFALIAAgVIAKAKIAAALg");
	this.shape_63.setTransform(0.65,1.2);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FDB61B").s().p("AgWAtIAAhZIAsAsIAAAtg");
	this.shape_64.setTransform(2.55,4.775);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FDB61B").s().p("AgkBKIAAiTIBJBKIAABJg");
	this.shape_65.setTransform(4.225,7.875);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FDB61B").s().p("AgwBiIAAjDIBiBiIAABhg");
	this.shape_66.setTransform(5.65,10.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FDB61B").s().p("Ag7B2IAAjrIB3B2IAAB1g");
	this.shape_67.setTransform(6.775,12.625);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FDB61B").s().p("AhDCGIAAkLICHCHIAACEg");
	this.shape_68.setTransform(7.675,14.3);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FDB61B").s().p("AhICRIAAkhICRCSIAACPg");
	this.shape_69.setTransform(8.325,15.5);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FDB61B").s().p("AhLCYIAAkvICYCYIAACXg");
	this.shape_70.setTransform(8.7,16.225);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FDB61B").s().p("AhNCaIAAkzICbCaIAACZg");
	this.shape_71.setTransform(8.825,16.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_63}]},2).to({state:[{t:this.shape_64}]},1).to({state:[{t:this.shape_65}]},1).to({state:[{t:this.shape_66}]},1).to({state:[{t:this.shape_67}]},1).to({state:[{t:this.shape_68}]},1).to({state:[{t:this.shape_69}]},1).to({state:[{t:this.shape_70}]},1).to({state:[{t:this.shape_71}]},1).to({state:[{t:this.shape_71}]},9).to({state:[]},1).wait(352));

	// Registration
	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("rgba(27,68,157,0.667)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFgEgSQgCgCgGAAQgFAAgKACgAAAABIgDAKIgEAAIAAgVIAIAAIAJAVg");
	this.shape_72.setTransform(3.075,35.85);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("rgba(27,68,157,0.722)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQADgEgDgTQgCgBgGAAIgPABgAgGALIgBgBIAAgUIAHAAIAAAAIgGAAIAAAQIAAAEIADAAIAAABIgDAAgAgDAKgAgCAFIACgCIAAgBIgBADIgCAFg");
	this.shape_73.setTransform(3.075,35.85);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("rgba(27,68,157,0.776)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQADgEgEgTQgBgBgGAAIgPABgAgGALIgBgBIAAgUIAIAAIAEAKIgFgJIgGAAIAAANIABADIADAAIgBADIgCABgAAGAJIgGgHIgBACIgBADIAAgCIABgBIACgDIAGADIACAHgAgCAHg");
	this.shape_74.setTransform(3.075,35.85);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("rgba(27,68,157,0.835)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQADgEgEgTQgBgCgGAAIgPACgAgFALIgCgBIAAgUIAIAAIADAHIgEgGIgFAAIAAAMIABACIACAAIgBAFIgCABgAAGAKIgGgIIAAAAIgBABIABgBIACgCIAEACIADAIg");
	this.shape_75.setTransform(3.075,35.85);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("rgba(27,68,157,0.89)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFgFgTQgBgBgFAAQgFAAgLACgAgFALIgCAAIAAgVIAIAAIACAGIgDgEIgEAAIAAAJIABACIAAAAIAAAGIgBACgAAGAKIgGgHIAAgBIgBAAIABgBIACgBIADAAIAEAKg");
	this.shape_76.setTransform(3.075,35.85);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("rgba(27,68,157,0.945)").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFgFgTQgCgBgFAAQgFAAgKACgAgEALIgDAAIAAgVIAIAAIADAFIgEgDIgEAAIAAAIIACABIABAAIABgBIADAAIACAAIAEAKIgDABIgFgIIgBgBIgDAAIgBAJg");
	this.shape_77.setTransform(3.075,35.85);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#1B449D").s().p("AgNAOQgGgFAAgJQAAgHAGgHQAGgFAHAAQAIAAAGAFQAGAHAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGgAgLgLQgEAFAAAGQAAAHAEAFQAFAFAGAAQAHAAAFgFQAEgFAAgHQAAgGgEgFQgFgEgHAAQgGAAgFAEgAAGALIgGgKIgDAAIAAAKIgEAAIAAgVIAIAAQAIgBAAAHQAAAEgGABIAHAKgAgDAAIADAAQAGAAAAgEQAAgDgFAAIgEAAg");
	this.shape_78.setTransform(3.075,35.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_72}]},13).to({state:[{t:this.shape_73}]},1).to({state:[{t:this.shape_74}]},1).to({state:[{t:this.shape_75}]},1).to({state:[{t:this.shape_76}]},1).to({state:[{t:this.shape_77}]},1).to({state:[{t:this.shape_78}]},1).to({state:[]},1).wait(352));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.4,-46.1,106.5,92.30000000000001);


(lib.image_05 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#008FBE").s().p("EgvBATsMAAAgnXMBeDAAAMAAAAnXg");
	this.shape.setTransform(151,-70.975);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_05, new cjs.Rectangle(-150,-196.9,602,251.9), null);


(lib.image_04 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.instance = new lib.Image_04();
	this.instance.setTransform(-149,-195);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_04, new cjs.Rectangle(-149,-195,590,250), null);


(lib.image_03 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image_03();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_03, new cjs.Rectangle(-150,-196.5,590,250), null);


(lib.image_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image_02();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_02, new cjs.Rectangle(-150,-196.5,590,250), null);


(lib.image_01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Image_01();
	this.instance.setTransform(-150,-196.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_01, new cjs.Rectangle(-150,-196.5,590,250), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// TALK_TO_US_TODAY
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8A8A8").s().p("AgDAyQgHgDgGgFQgGgGgCgHQgEgIAAgKIAAg9IAZAAIAAA9QABAIADAFQAEAFAIAAQAHAAAFgFQAEgFABgIIAAg9IAZAAIAAA9QgBAKgDAIQgDAHgFAGQgFAFgIADQgHACgKAAQgJAAgHgCgAiDAxQgKgFgHgHQgHgHgEgJQgEgKAAgLQAAgKAEgKQAEgJAHgHQAHgIAKgEQAJgDALAAQALAAAJADQAKAEAHAIQAHAHAEAJQAFAKAAAKQAAALgFAKQgEAJgHAHQgHAHgKAFQgJADgLAAQgLAAgJgDgAh6gaQgFADgDAEQgEADgDAGQgCAFAAAFQAAAGACAFQACAFAEAEQAEAEAFACQAFADAGAAQAGAAAFgDQAGgCADgEIAGgJQACgFAAgGQAAgFgCgFQgDgGgDgDQgEgEgFgDQgFgCgGAAQgGAAgFACgAIvAzIAAgrIghg6IAaAAIATAlIAUglIAaAAIgiA6IAAArgAHYAzIAAgnIghAAIAAAnIgYAAIAAhlIAYAAIAAAmIAhAAIAAgmIAZAAIAABlgAFMAzIgSg/IgRA/IgYAAIgchlIAYAAIAQA+IASg+IAXAAIASA+IAQg+IAYAAIgcBlgAByAzIAAhPIgcAAIAAgWIBQAAIAAAWIgcAAIAABPgAlNAzIAAhlIAlAAQALAAALADQAJAEAIAHQAGAHAEAJQAEAKAAAKQAAALgEAJQgEAKgHAGQgHAHgJAEQgLAEgLAAgAk0AcIALAAQAHAAAFgCQAFgCAFgEQADgEACgFQADgFAAgGQAAgFgDgGQgCgFgDgEQgEgDgFgDQgGgCgIAAIgKAAgAmGAzIgog/IAAA/IgYAAIAAhlIAaAAIAmA8IAAg8IAYAAIAABlgAoAAzIAAhlIAYAAIAABlgApoAzIAAhlIBHAAIAAAXIguAAIAAASIAuAAIAAAWIguAAIAAAmg");
	this.shape.setTransform(3.15,0.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(201,201,198,0.298)","rgba(201,201,198,0)"],[0,0.608],-53.5,0,68.2,0).s().p("AnICpIFLlRIJGAAIAAFRg");
	this.shape_1.setTransform(33.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	// _Path__1
	this.instance = new lib.Bitmap1();
	this.instance.setTransform(-89,-33,0.7554,0.8156);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-89,-33,194.9,78.3), null);


(lib.bswh_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.BSWH_Icon("synched",0,false);
	this.instance.setTransform(-142.75,19.25,0.6529,0.6529,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({mode:"single",startPosition:19},0).wait(1).to({startPosition:19},0).to({_off:true},1).wait(99));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#3C8EBA").s().p("ALcAcQgKgMAAgQQAAgPAKgMQAJgKARAAQAMAAAKAGQAIAHACANIgQAAQgBgGgEgDQgEgEgHAAQgHAAgEAEQgFADgCAGQgBAGgBAFQABAKAEAHQAFAIAKAAQAIAAADgFQAGgFAAgHIAQAAQgCAOgIAIQgJAIgOAAQgRAAgJgKgAIYAcQgKgMAAgQQAAgPAKgMQAKgKAQAAQANAAAJAGQAIAHACANIgQAAQAAgGgFgDQgEgEgHAAQgHAAgEAEQgEADgDAGQgCAGAAAFQAAAKAGAHQAEAIAKAAQAHAAAFgFQAEgEABgIIAPAAQAAAOgJAIQgJAIgOAAQgPAAgLgKgAFyAfQgHgHgBgPIAAgtIAQAAIAAAtQAAAHADAEQAEAFAJAAQAIAAADgEQAEgEAAgIIAAgtIAQAAIAAAtQAAAOgJAIQgHAHgPAAQgPAAgJgHgAEZAcQgKgLAAgRQAAgQAKgLQAJgKARAAQARAAAKAKQAJAMAAAPQAAAQgJAMQgKAKgRAAQgQAAgKgKgAEogUQgFADgCAGQgBAGAAAFQAAAKAEAHQAFAIAKAAQAKAAAGgIQAEgHAAgKQAAgFgCgGQgCgGgEgDQgEgEgIAAQgHAAgEAEgADMAgQgJgHAAgNIAPAAQABAHAFAEQAEADAHAAIAGgBQADAAACgDQADgCAAgEIAAgDIgCgCIgDgCIgZgHIgGgDQgEgCgCgEQgCgEABgFQAAgHAEgFQAEgFAGgCQAGgCAHAAQAIAAAHACQAGADAEAEQAFAGgBAIIgPAAQgBgLgNAAQgFAAgEACQgCACAAAEQAAAEACACQADACAQADQAJADAGADQAGAFAAAKQAAAKgHAHQgIAGgPAAQgNAAgJgGgAjlAcQgJgMAAgQQAAgPAJgMQAKgKARAAQAMAAAKAGQAIAIACAMIgQAAQAAgGgFgDQgFgEgGAAQgIAAgEAEQgEADgCAGQgCAGAAAFQAAAKAFAHQAFAIAKAAQAHAAAFgFQAEgEABgIIAPAAQAAAOgKAIQgIAIgOAAQgQAAgLgKgAncAcQgKgMABgQQgBgPAKgMQAKgKARAAQAMAAAJAGQAJAHABANIgPAAQgBgGgFgDQgEgEgGAAQgIAAgDAEQgFADgCAGQgCAGAAAFQAAAKAFAHQAFAIAKAAQAHAAAEgFQAFgEABgIIAPAAQgBAOgJAIQgJAIgNAAQgQAAgLgKgAxLAcQgKgMAAgQQAAgPAKgMQAJgKARAAQARAAAKAKQAJALAAAQQAAARgKALQgKAKgQAAQgQAAgKgKgAw9gUQgEADgCAGQgCAGAAAFQAAAKAFAHQAFAIAKAAQAKAAAFgIQAFgHAAgKQAAgFgCgGQgCgGgEgDQgFgEgHAAQgHAAgFAEgAyRAhQgIgGAAgMIAAgGIAPAAIAAADQAAAGACADQACAEAFAAIAEgBIADgCIABgDIABgDIAAg0IAPAAIAAAxQABAZgYAAQgLAAgGgFgASKAlIgBgFIgCgNQgBgGgDgDQgDgCgFAAIgQAAIAAAdIgQAAIAAhJIAnAAQAJAAAHAGQAGAGAAAIQAAAOgMAEQAJACABAPIACALIABAEIABADgARrgDIASAAQAKAAABgKQgBgKgKAAIgSAAgAQQAlIAAhJIA3AAIAAAOIgnAAIAAAQIAjAAIAAALIgjAAIAAASIAoAAIAAAOgAPZAlIAAg7IgWAAIAAgOIA9AAIAAAOIgXAAIAAA7gAOiAlIgegxIAAAxIgQAAIAAhJIAQAAIAfAwIAAAAIAAgwIAPAAIAABJgAMqAlIAAhJIA2AAIAAAOIgmAAIAAAQIAkAAIAAALIgkAAIAAASIAnAAIAAAOgAJmAlIAAhJIA2AAIAAAOIgmAAIAAAQIAkAAIAAALIgkAAIAAASIAnAAIAAAOgAHuAlIgCgSQgBgGgDgDQgDgCgGAAIgQAAIAAAdIgQAAIAAhJIAoAAQAJAAAHAGQAFAGAAAIQAAAOgMAEQALADAAAOIABALIABAEIACADgAHPgDIASAAQALAAAAgKQAAgKgLAAIgSAAgAB9AlIAAhJIA3AAIAAAOIgnAAIAAAQIAkAAIAAALIgkAAIAAASIAnAAIAAAOgABaAlIgDgSQgBgGgDgDQgDgCgFAAIgRAAIAAAdIgPAAIAAhJIAnAAQAJAAAHAGQAFAGAAAIQABAOgMAEQAJACACAPIAAALIACAEIABADgAA6gDIASAAQAMAAAAgKQAAgKgMAAIgSAAgAgcAlIgCgFIgCgNQAAgGgDgDQgDgCgFAAIgRAAIAAAdIgQAAIAAhJIAoAAQAJAAAHAGQAFAGAAAIQAAAOgLAEQAJADABAOIABALIABAEIABADgAg8gDIASAAQALAAAAgKQAAgKgLAAIgSAAgAiXAlIAAhJIA3AAIAAAOIgmAAIAAAQIAkAAIAAALIgkAAIAAASIAnAAIAAAOgAkSAlIgegxIAAAxIgQAAIAAhJIARAAIAfAwIAAgwIAOAAIAABJgAleAlIgGgRIgcAAIgFARIgQAAIAchJIAQAAIAcBJgAl7AIIATAAIgJgaIgBAAgApXAlIAAgNIAoguIgkAAIAAgOIA5AAIAAANIgnAuIAoAAIAAAOgAqIAlIAAg7IgWAAIAAgOIA7AAIAAAOIgVAAIAAA7gAqxAlIgFgRIgbAAIgGARIgRAAIAchJIARAAIAbBJgArNAIIATAAIgKgagAsDAlIgVghIgKAJIAAAYIgQAAIAAhJIAQAAIAAAfIAdgfIAUAAIgdAdIAfAsgAt9AlIgfgxIAAAxIgPAAIAAhJIAQAAIAfAwIAAAAIAAgwIAPAAIAABJgAvLAlIgFgRIgcAAIgFARIgQAAIAbhJIARAAIAbBJgAvnAIIATAAIgJgag");
	this.shape.setTransform(13,58.425);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1140A0").s().p("AHND7QgOgPAAgXQAAgYAOgPQANgPAXAAQASAAAMAKQANAJACASIgWAAQgBgIgGgFQgHgFgJAAQgJAAgGAFQgHAFgDAIQgCAHAAAKQAAAOAHAKQAHAKANAAQALAAAGgGQAFgGACgLIAWAAQgCATgNAMQgMALgTAAQgXAAgNgPgABLD7QgNgPAAgXQAAgYANgPQANgPAXAAQASAAAMAKQANAJACASIgWAAQgBgIgGgFQgHgFgJAAQgJAAgHAFQgFAFgEAIQgCAIAAAJQAAAOAHAKQAHAKANAAQALAAAGgGQAFgGACgLIAVAAQgBATgMAMQgNALgTAAQgXAAgNgPgAoFEBQgNgKABgRIAVAAQABAJAGAFQAHAFAJAAIAJgBQAEgBAEgDQADgDAAgFIAAgEIgDgDIgEgDIgXgHIgMgEQgFgBgEgEQgFgDgDgFQgCgFAAgHQABgKAFgHQAGgHAIgEQAJgDAJAAQAMAAAJADQAIADAGAIQAHAIgBALIgVAAQAAgPgVAAQgGAAgFACQgEADAAAGQAAAGAFACQAGADATAFQAOADAHAFQAKAIAAANQAAAPgLAJQgMAJgTAAQgTAAgNgJgAv3EBQgNgJAAgSIAXAAQAAAKAGAEQAGAFAKAAIAIgBQAFgBADgDQAEgDAAgFIgBgEIgDgDIgDgDIgGgCIgSgFIgLgEQgFgBgEgEQgFgDgDgFQgCgFAAgHQAAgKAGgHQAFgHAJgEQAJgDAJAAQAMAAAIADQAJADAGAIQAGAHAAAMIgWAAQgBgPgTAAQgGAAgEACQgFADAAAGQAAAGAFACQAFADAVAFQAMADAIAFQAKAIgBANQABAPgLAJQgMAJgUAAQgTAAgMgJgAQyEIIgBgHIgCgSQgCgIgEgEQgDgDgIAAIgXAAIAAAoIgWAAIAAhnIA3AAQAOAAAHAJQAJAIgBAMQABATgRAGIAAABQAOADABAVIABAJIACALIACAEgAQHDQIAZAAQAQAAAAgPQAAgOgQAAIgZAAgAOGEIIAAhnIBMAAIAAATIg2AAIAAAWIAyAAIAAASIgyAAIAAAZIA3AAIAAATgAM2EIIAAhUIgeAAIAAgTIBUAAIAAATIgfAAIAABUgALnEIIgqhFIAAAAIAABFIgWAAIAAhnIAXAAIAqBFIAAAAIAAhFIAWAAIAABngAI8EIIAAhnIBNAAIAAATIg2AAIAAAWIAxAAIAAASIgxAAIAAAZIA3AAIAAATgAErEIIAAhnIAWAAIAABUIAyAAIAAATgAD8EIIgHgXIgnAAIgIAXIgXAAIAnhnIAXAAIAmBngADUDgIAaAAIgMglIgBAAgAAKEIIAAhnIAWAAIAABngAhuEIIAAhnIAsAAQAVAAANAOQAMAMAAAZQAAAXgMAOQgMAPgWAAgAhYD1IAUAAQALAAAHgIQAIgHAAgQQAAgQgHgJQgHgJgPAAIgRAAgAjZEIIAAhnIBMAAIAAATIg2AAIAAAWIAyAAIAAASIgyAAIAAAZIA3AAIAAATgAkREIIAAhJIgYBJIgSAAIgZhIIAAAAIAABIIgWAAIAAhnIAgAAIAZBHIAWhHIAgAAIAABngApZEIIAAhUIggAAIAAgTIBUAAIAAATIgfAAIAABUgAqpEIIgrhFIAABFIgVAAIAAhnIAWAAIArBFIAAAAIAAhFIAVAAIAABngAshEIIAAhnIAWAAIAABngAtQEIIgHgXIgnAAIgIAXIgXAAIAnhnIAXAAIAmBngAt4DgIAbAAIgNglIgBAAgAyXEIIAAhnIAXAAIAABUIAyAAIAAATgAz6EIIAAhnIAXAAIAABUIAxAAIAAATgA0oEIIgIgXIgmAAIgIAXIgXAAIAnhnIAXAAIAnBngA1QDgIAaAAIgNglIAAAAgAwFBwQgEgEAAgIQAAgIAEgFQAFgEAHAAIAHAAQAJAAAFgHQANgVAHgQQAEgNAAgEQAAgJgHgSIgghXQgFgRgEgFQgFgIgJgBIgKgDQgDgBABgEQABgEACgBIAmABIAkgBQACABAAAEQABAEgDABIgKADQgIABAAAEQAAADAEAPIAHAUIANAlIAMAdQADgCAMgcIANggQAPghAAgIQAAgFgKgBIgNgDQgCgBAAgEQABgEACgBIAkABIAfgBQACABAAAEQAAADgCACIgHACQgJABgIAKQgGAIgLAYIgXAuQgjBIgbA9QgJATgRAAQgJAAgFgFgAL5AdQgHgWgRglIgYg3QgjBHgQArIgEABIgHgBIgchAIhNipQgIgPgEgFQgGgIgMgBIgJgBQgDgCABgDQAAgDADgBIAqABIAugBQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABQAAADgBACIgKABQgNABAAAGQAAAGAVAwQAWAyAwBlIAfhBQAGgNABgEQAAgDgEgHIgshiQgFgKgFgFQgHgGgJgBIgKgBQgCgCAAgDQAAgBAAgBQABAAAAgBQAAAAABgBQAAAAABAAIArABIAtgBQABAAAAAAQAAAAABABQAAAAAAABQAAABABABQAAADgCACIgLABQgMABgBAEQgBADAFAOIAgBHIAYg1QALgZgBgIQAAgGgLgBIgMgBQgCgDABgDQAAgBAAAAQAAgBAAAAQAAgBABAAQAAAAABAAIAmABIAngBQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABQAAADgBACIgMABQgLABgJAMIgNAXQgSAggOAgQgDAHAAADQAAAEACAGIAqBcQAVguAPgnQAXg2AJgbQAMggABgFQAAgIgOgBIgLgBQgDgCABgDQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABAAIAnABIABAAIADAAQATgBAMgHQAHgFANgKIADAAIABADIgBAyIAABVQAAAHACABQAbgVAbAAQAcAAANAPQAMAOAAAXIAABEQAAAVABAGQADAGALABIALABQACACAAAEQgBADgCABIgpgBIgmABQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAgBAAAAQgBgEACgCIAIgBQALgCACgFQACgGABgVIAAg6QAAgUgKgMQgLgLgSAAQgTAAgNAKIgGAIQgCAEAAALIAABEQAAAVACAGQADAGALABIAHABQADABAAAEQgBAEgCABIgmgBIgoABQgCgBgBgDQAAgEACgCIALgBQALgBACgGQACgGAAgVIAAi3QAAgTgCgFQgBgEgDAAQgIAEgGAJQgFAIgVAvIgdBFQgZA5gaBCQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAgBAAIgGgBgAnIAQQgEgHgDgRQgEgRAAgPQACgCADgBQABAAABAAQAAAAABABQAAAAABAAQAAAAABABQARA7A1AAQAXAAAPgOQAMgMAAgTQAAgRgFgLQgIgQgUgNIgngZQgsgeAAgoQABgeAVgTQAXgVAnAAQASAAATAGQAHACAHAAQADAHACAPQADAPgBAMQAAACgEABQgEAAgCgCQgFgTgKgKQgOgQgZAAQgbAAgNAPQgJAMAAASQAAAcAiAWIAhAUQAzAfAAAvQAAAhgYAUQgXAUgoAAQgmAAgZgOgAUsAWQgOgHgKgMQgRgVAAgfQAAgmAXgaQAXgbAjAAQAaAAARAPQAPAOAAATQAAAHgBAEQgCACgWAAIhLAAQgIAAgCACQgCACAAAHQAAAgASAWQATAVAfAAQALAAAIgEQAKgEAIgLQADgBACACQACABABADQgKASgTAKQgRAJgSAAQgTAAgQgIgAUxhzQgOALAAALQAAABAAAAQAAAAABABQAAAAABAAQAAAAABAAIAdAAQAkAAAGgEQACgBAAgHQAAgKgGgGQgJgJgPAAQgRAAgPANgASvARQgJgKAAgUIAAhdQAAgIgBgCQgBgBgGAAIgLAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQgBgDACgCQARgFAIgIQAKgIAHgQQAHgCACAEIAAATQAAAFABABQABABAFAAIAtAAQAEADAAAGQgBAHgDACIguAAQgEAAgCABQgBACAAAGIAABMQAAAWAFAJQAHANASAAQAGAAAFgCQAEgBAGgFQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQgQATgaAAQgYAAgKgNgADRARQgJgKAAgUIAAhdQAAgIgBgCQgCgBgFAAIgLAAQgBgBAAAAQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgDABgCQASgFAIgIQAJgHAIgRIAEAAQABAAABAAQAAABABAAQAAAAABAAQAAABAAAAIAAATQAAAFABABQACABAEAAIAuAAQADADAAAGQAAAHgDACIguAAQgFAAgBABQgBACAAAGIAABMQAAAVAFAKQAGANATAAQAFAAAGgCQADgBAHgFQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAABAAAAQAAABAAAAQgQATgaAAQgZAAgJgNgABVARQgHgKgBgUIAAhdQAAgIgBgCQgBgBgGAAIgLAAQAAgBgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQgBgDACgCQARgFAJgIQAJgIAIgQIAEAAQABAAAAAAQABABAAAAQABAAAAAAQABABAAAAIAAATQAAAFACABQAAABAGAAIAtAAQADADAAAGQAAAHgDACIguAAQgFAAgBABQgBACAAAGIAABMQAAAVAEAKQAHANASAAQAGAAAFgCIAKgGQABAAAAAAQABAAAAABQABAAAAABQABAAAAABIABAEQgQATgcAAQgXAAgLgNgAhpAHQgZgWAAgmQAAglAZgaQAZgYAlAAQAiAAAXAXQAYAYAAAlQAAAmgYAXQgWAZgnAAQgjAAgXgXgAhRhuQgOAUAAAgQAAAfANAVQAPAYAZAAQAZAAAMgWQAIgSAAgcQAAgegKgWQgOgagbAAQgVAAgMASgAkBAJQgYgWAAglQAAgkAYgZQAbgdAvAAQAVAAAPAHQAGAEAAAMQAAAGgCAEQgEAFgDAAQgDAAgDgDQgHgJgKgGQgLgHgMAAQgXAAgPARQgSASAAAfQAAAaAQAUQATAWAeAAQARAAALgHQAJgFAJgLQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABABQACACABACQgJAUgWALQgRAKgUAAQgiAAgVgVgAr4AHQgYgWABgmQAAglAZgaQAZgYAkAAQAiAAAYAXQAYAYAAAlQAAAmgXAXQgZAZglAAQgkAAgYgXgArfhuQgOATAAAhQAAAfAOAVQAOAYAZAAQAYAAAMgWQAKgSAAgcQAAgegMgWQgOgagaAAQgUAAgNASgAxGARQgDgFgDAAIgGACIgJAGIgPAGQgHAEgIAAQgSAAgLgKQgMgKAAgRQAAgMAIgHQAGgIAUgHIAwgSQAFgBABgDIABgIIAAgSQAAgPgFgIQgHgMgSAAQgJAAgHAEQgJAFAAAJQgBALgEACQgJAIgNAAQgGAAAAgFQAAgQAbgRQAagRAWAAQAWAAALAMQAKAMgBAXIgCBHQgCAiAVAAQAFAAAFgCIAFgDQADAAAAAFQAAADgJAHQgNAIgMAAQgRAAgKgNgAxfgqQgUAHgHAFQgJAHAAALQAAAIAFAGQAIAKANAAQAFAAAJgEQAHgDAEgEQADgCABgFIABgLIABgYQgBgFgEAAQgFAAgLAEgAFaAHQgZgUAAgfQAAgtAvgTQgQgSAAgSQAAgVAPgOQAOgPAWAAQAPAAALAIQAMAJAAANQAAAOgMAIQgIAHgIAAQgJAAAFgHQADgCABgDQACgGgCgHQgCgGgFgEQgHgFgIAAQgLgBgIAGQgHAHAAAKQAAAKAHAHQAIAIAUAMQAkATAPANQAZAVASAlQAOgQgBgXQABgPgKgMQgEgGgLgCQgKgBgKAHQgCADgDgCQgDAAAAgJQACgKAKgGQAKgIAOAAQAJAAAMADIAPACQAIAAACgEIADgCQADAAABAEQAAALgHAHQgGAHgPADQAGAMAAAPQAAAcgWAZQAJAPAKAHQALAHAOAAQAGAAAEgBIAHgCQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAGgMADQgLAEgQAAQgQAAgKgEQgKgEgNgMQgUAMgPAEQgPAFgSAAQglAAgZgVgAFhhEQAAAgAWAXQAWAXAeAAQAKAAAJgDQAJgCANgGIgSgXIgIgMQgPgWgQgPQgKgJgPgMIgJgHQgYAGAAAbgARcAYIgnABQgBgBgBgDQAAgEABgCIAJgBQALgBADgGQABgGAAgVIAAhHQAAgNgBgDQgCgEgHgFIgFgDIgBgDQABgBAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAIAWgJQANgGAHgFQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIgCAyIAABJQAAAVADAGQACAGAKABIAKABQACACgBAEQAAADgCABIgmgBgAosAYIglABQgBAAAAgBQgBAAAAgBQAAAAAAgBQgBgBAAAAQAAgEACgCIAHgBQALgCADgFQACgGAAgVIAAhHQAAgNgCgDQgBgEgIgFIgDgDQgBAAAAgBQAAAAgBgBQAAAAAAAAQAAgBAAAAQAAgBAAgBQABAAAAgBQAAAAAAgBQABAAAAAAQASgGAXgOQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIAAAYIABADIAWgRQANgHAKAAQAIAAAEAEQAGAFAAAHQAAAJgGAFQgFAFgGAAQgEAAgFgDQgKgHgIAAQgIAAgHAIQgFAIAAAYIAAA3QAAAVACAGQADAGALABIAPABQACACgBAEQAAADgCABIgtgBgAtFAYIgnABQgCgBgBgDQAAgEACgCIAKgBQALgBADgGQABgGAAgVIAAi3QAAgTgBgEQgCgGgJgFIgEgCQAAgBgBAAQAAAAAAgBQAAAAAAgBQgBgBAAAAQAAgBABgBQAAgBAAAAQAAgBAAAAQABAAAAAAQAegLANgHQABAAABAAQAAAAABABQAAAAABABQAAAAAAABIgBAyIAADAQAAAVADAGQACAGALABIAJABQADACgBAEQAAADgDABIgngBgA1YAYIgvABQgCgBgBgDQAAgEACgCIAHgBQAQgDADgIQADgGABghIAAiaQgBgXgDgHQgEgIgNgBIgMgBQgCgCAAgEQAAgDACgBQAhgDA3AAQAtAAAWALQAfAPAAAkQAAAUgMAOQgJAMgVAJQAAAFAJABQATAEAQAPQASATABAeQgBAkgaAUQgcAVg1AAIgwgBgA1FhuQgEACAAAGIAAA8QAAAjAIAIQAKAMAWAAQAdAAARgNQASgOAAgdQAAgdgRgSQgUgWgrAAQgQAAgEACgA1DjlQgDABgCACIgBAIIAABSQAAAJADABQACACAQAAQAggCAPgLQARgMAAgbQgBgcgSgOQgRgNgZAAQgOAAgEACgARKizQgGgFAAgJQAAgKAGgGQAHgGAIAAQAKAAAFAHQAGAGAAAIQAAALgHAFQgFAFgKAAQgIAAgGgGg");
	this.shape_1.setTransform(34.85,15.2375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_1},{t:this.shape}]},20).to({state:[]},1).wait(99));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-172.9,-11.4,350,73.7);


// stage content:
(lib.BSWH_CancerHatesUs_V4_970x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("EhLxgThMCXjAAAMAAAAnDMiXjAAAg");
	this.shape.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(425));

	// BSWH_Logo
	this.instance = new lib.bswh_logo("synched",0,false);
	this.instance.setTransform(775.35,103.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1,mode:"single",startPosition:20},20).wait(405));

	// txt_Celebrating_TenYears
	this.instance_1 = new lib.txt_celebratingTenYears();
	this.instance_1.setTransform(150.05,563.25);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},9).wait(378).to({alpha:0},8).wait(30));

	// cta_btn
	this.instance_2 = new lib.ctaBtn();
	this.instance_2.setTransform(774,249.45,1.3562,1.3562);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(395).to({_off:false},0).to({y:205.45,alpha:1},7,cjs.Ease.quadOut).to({y:207.95},6,cjs.Ease.quadOut).wait(17));

	// txt_cancerHatesUs
	this.instance_3 = new lib.txt_cancerHatesUs();
	this.instance_3.setTransform(126.2,-116.7);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(358).to({_off:false},0).to({y:75.8},29,cjs.Ease.quadOut).wait(38));

	// image_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_338 = new cjs.Graphics().p("EgtJARRMAAAgihMBaTAAAMAAAAihg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(338).to({graphics:mask_graphics_338,x:302,y:124.55}).wait(87));

	// safeCare_logo
	this.instance_4 = new lib.safeCare_logo();
	this.instance_4.setTransform(474.55,164.35,3.0926,3.0926,5.6903,0,0,0.1,0.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(387).to({_off:false},0).to({scaleX:1.3836,scaleY:1.3836,rotation:0,y:164.6,alpha:1},9,cjs.Ease.quadOut).to({scaleX:1.4725,scaleY:1.4725,x:474.5,y:164.55},15,cjs.Ease.quadOut).wait(14));

	// image_05
	this.instance_5 = new lib.image_05();
	this.instance_5.setTransform(150.2,-131.9);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(340).to({_off:false},0).to({y:197.1},34,cjs.Ease.quadOut).wait(51));

	// txt_qualityCare
	this.instance_6 = new lib.txt_qualityCare();
	this.instance_6.setTransform(127.2,-40.85);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(280).to({_off:false},0).to({y:60.65},26,cjs.Ease.quadOut).wait(119));

	// image_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_255 = new cjs.Graphics().p("EgtJARRMAAAgihMBaTAAAMAAAAihg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(255).to({graphics:mask_1_graphics_255,x:302,y:124.55}).wait(170));

	// image_04
	this.instance_7 = new lib.image_04();
	this.instance_7.setTransform(150.2,-129.3);
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(257).to({_off:false},0).to({y:197.1},34,cjs.Ease.quadOut).wait(134));

	// txt_advancedTreatment
	this.instance_8 = new lib.txt_advancedTreatment();
	this.instance_8.setTransform(126.2,-106.85);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(197).to({_off:false},0).to({x:126.7,y:60.15},26,cjs.Ease.quadOut).wait(202));

	// image_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_175 = new cjs.Graphics().p("EgtJARRMAAAgihMBaTAAAMAAAAihg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(175).to({graphics:mask_2_graphics_175,x:302,y:124.55}).wait(250));

	// image_03
	this.instance_9 = new lib.image_03();
	this.instance_9.setTransform(150.2,-129.3);
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(177).to({_off:false},0).to({y:197.1},34,cjs.Ease.quadOut).wait(214));

	// txt_earlyDetection
	this.instance_10 = new lib.txt_earlyDetection();
	this.instance_10.setTransform(125.2,-103.85);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(115).to({_off:false},0).to({y:60.65},26,cjs.Ease.quadOut).wait(284));

	// image_mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_95 = new cjs.Graphics().p("EgtJARRMAAAgihMBaTAAAMAAAAihg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:null,x:0,y:0}).wait(95).to({graphics:mask_3_graphics_95,x:302,y:124.55}).wait(330));

	// image_02
	this.instance_11 = new lib.image_02();
	this.instance_11.setTransform(150.2,-127.3);
	this.instance_11._off = true;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(97).to({_off:false},0).to({y:197.1},34,cjs.Ease.quadOut).wait(294));

	// txt_cancerHatesFighters
	this.instance_12 = new lib.txt_cancerHatesFighters();
	this.instance_12.setTransform(126.7,-106.85);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(35).to({_off:false},0).to({y:61.65},26,cjs.Ease.quadOut).wait(364));

	// image_mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("EgtJARRMAAAgihMBaTAAAMAAAAihg");
	mask_4.setTransform(302,124.55);

	// image_01
	this.instance_13 = new lib.image_01();
	this.instance_13.setTransform(150.2,-185.3);

	var maskedShapeInstanceList = [this.instance_13];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(14).to({y:-131.3},0).to({y:197.1},34,cjs.Ease.quadOut).wait(377));

	// background
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EhLxATiMAAAgnDMCXjAAAMAAAAnDg");
	this.shape_1.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(425));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(484,-55.5,487,366.4);
// library properties:
lib.properties = {
	id: 'FC95E511C6C24CD7B72756EF013CB206',
	width: 970,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Bitmap1.png", id:"Bitmap1"},
		{src:"Image_01.jpg", id:"Image_01"},
		{src:"Image_02.jpg", id:"Image_02"},
		{src:"Image_03.jpg", id:"Image_03"},
		{src:"Image_04.jpg", id:"Image_04"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['FC95E511C6C24CD7B72756EF013CB206'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;