(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,40);


(lib.head_img = function() {
	this.initialize(img.head_img);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,125,103);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.working_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AHwBGQgEgFAAgJQgBgJAGgGQAFgFAJAAQAJAAAFAFQAFAGABAJQgBAJgFAFQgFAFgJAAQgJAAgGgFgAFyBFQgOgGgJgKQgLgKgEgOQgGgOAAgPQAAgPAGgNQAFgOAKgKQAKgLAOgFQANgGASAAQAUAAAQAIQAPAIALAOIgeAUQgEgIgJgEQgJgFgKAAQgJAAgHADQgIAEgFAFQgFAFgEAIQgDAIAAAIQAAAKADAHQADAHAFAGQAGAGAIADQAHADAJAAQAMAAAJgGQAJgGADgLIgoAAIAAggIBPAAIAAAQQgBAOgFANQgEAOgKAKQgKAKgNAFQgNAGgPAAQgSAAgPgGgAkQBFQgOgGgKgKQgLgKgFgOQgGgOAAgPQAAgPAGgNQAFgOALgKQAKgKAOgGQANgGAQAAQAQAAANAGQAOAGAKAKQAKAKAGAOQAFANAAAPQAAAPgFAOQgGAOgKAKQgKAKgOAGQgNAGgQAAQgQAAgNgGgAkDgkQgIADgEAFQgGAGgCAHQgDAIAAAHQAAAIACAIQADAHAGAFQAEAGAIAEQAHACAJAAQAJAAAHgCQAHgEAFgGQAGgFACgHQADgIAAgIQAAgHgDgIQgCgHgGgGQgGgFgGgDQgIgEgIAAQgJAAgHAEgAEQBJIg5hbIAABbIghAAIAAiRIAkAAIA3BWIAAhWIAhAAIAACRgAB8BJIAAiRIAjAAIAACRgABIBJIgehFIgTAYIAAAtIgiAAIAAiRIAiAAIAAA7IAug7IAoAAIgrA2IAsBbgAhFBJIgUgsIgcAAIAAAsIgiAAIAAiRIA+AAQAOAAAKAEQAKAEAHAHQAHAGAEAJQAEAKgBAKQAAAOgGAKQgGAMgLAGIAbA1gAh1gBIAaAAQALAAAGgGQAFgGAAgIQAAgJgFgFQgGgFgLAAIgaAAgAmUBJIgahbIgZBbIgiAAIgpiRIAkAAIAXBZIAZhZIAhAAIAaBZIAWhZIAjAAIgoCRg");
	this.shape.setTransform(-53.05,7.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.working_txt, new cjs.Rectangle(-106.1,0,106.1,15), null);


(lib.we_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AA5BJIAAiRIBlAAIAAAgIhCAAIAAAZIBCAAIAAAfIhCAAIAAAYIBCAAIAAAhgAgfBJIgahbIgZBbIgjAAIgoiRIAkAAIAXBZIAZhZIAhAAIAZBZIAWhZIAjAAIgoCRg");
	this.shape.setTransform(-15.775,7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.we_txt, new cjs.Rectangle(-31.5,0,31.5,14.6), null);


(lib.txt_yourGut = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape.setTransform(-8.825,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_1.setTransform(-17.325,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaA+QgKgFgIgJIATgPQAFAGAGADQAFAEAJgBQAFAAAEgBQAFgCADgEQAEgDACgEQACgFAAgFIAAgHQgFAHgIAEQgHADgIAAQgJABgIgEQgIgDgGgGQgGgHgEgJQgDgHAAgLQAAgLADgJQAEgIAGgHQAGgGAIgEQAIgCAJAAQAIgBAIAEQAHAEAFAGIAAgMIAXAAIAABUQAAAKgDAIQgEAJgGAGQgHAGgJAEQgJAEgKAAQgPAAgLgFgAgJgqQgEACgEADQgDAEgCAFQgCAEAAAGQAAAFACAFQACAEADAEQAEADAEACQAFACAEAAQAGAAAEgCQAFgCAEgDIAFgIQACgFAAgFQAAgGgCgEIgFgJQgEgDgFgCQgEgCgGAAQgEAAgFACg");
	this.shape_2.setTransform(-27.675,3.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAvIAAhbIAXAAIAAAOQADgIAGgEQAHgEAIAAIAJABIAHADIgIAXIgGgCIgHgBQgIAAgFAFQgFAFgBALIAAAwg");
	this.shape_3.setTransform(-39.45,1.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_4.setTransform(-48.175,1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTAsQgJgEgGgGQgHgHgDgJQgDgIAAgKQAAgJADgJQADgJAHgGQAGgGAJgEQAJgEAKAAQAKAAAJAEQAJAEAGAGQAHAGADAJQAFAJAAAJQAAAKgFAIQgDAJgHAHQgGAGgJAEQgJAEgKAAQgKAAgJgEgAgJgXQgFACgDAEQgDADgCAFQgCAEgBAFQABAFACAFQACAEADAEQADADAFACQAEACAFAAQAFAAAEgCQAGgCADgDIAFgIQACgFAAgFQAAgFgCgEQgCgFgDgDQgDgEgGgCQgEgCgFAAQgFAAgEACg");
	this.shape_5.setTransform(-58.25,1.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnA+QgHgDgFgDIANgTIAGAEQADABAEAAQAGAAAEgDQAEgDAEgIIABgEIglhXIAZAAIAXA7IAXg7IAYAAIgnBgQgEAJgEAGQgDAGgEADQgEAEgGACQgGABgHAAQgHAAgHgCg");
	this.shape_6.setTransform(-68.625,3.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgYAqQgKgGgGgLIAWgIQAGAMAPgBQAGAAAFgCQADgEAAgEQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgEIgHgBIgHgCIgMgDQgGgCgFgDQgEgBgDgGQgDgEAAgHQAAgGACgFQAEgGAEgDQAFgFAHgCQAHgCAHAAQAPAAAJAFQAKAFAGAKIgWAIQgDgEgDgDQgFgDgHABQgGgBgDADQgDACAAAFQAAADAFACIAPAFIALACQAHACAEAEQAFABADAGQADAEAAAHQAAAGgCAFQgDAGgEAEQgGAEgHADQgHADgLAAQgPAAgKgGg");
	this.shape_7.setTransform(-80.75,1.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLASQAHgFAEgFQADgFAAgFQgCAEgFAAQgFAAgDgDQgDgEAAgFQAAgHAEgEQAEgEAHAAQAHAAAFAFQAEAGAAAIQAAAJgGAIQgFAIgJAHg");
	this.shape_8.setTransform(-86.825,-3.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape_9.setTransform(-92.225,-0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjAoQgIgIAAgMQAAgOALgHQALgJATAAIAXAAIAAgBQAAgHgEgFQgGgEgKAAQgGAAgFADQgGADgDAGIgWgLQAHgJAKgGQALgGAOAAQAVAAALAKQALAKAAARIAAA4IgXAAIAAgOQgFAHgIAEQgIAFgLAAQgPAAgJgIgAgOAKQgFADABAFQgBAKAOAAIAIgBIAHgDIAHgGQADgDABgDIAAgFIgVAAQgJAAgFADg");
	this.shape_10.setTransform(-100.85,1.425);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AASBDIAAg0QABgKgFgFQgFgFgJAAQgHAAgGAFQgFAGgBALIAAAyIgXAAIAAiFIAXAAIAAA1QAFgFAHgEQAGgEAIABQAIgBAHADQAHADAEAFQAFAFADAGQACAGAAAJIAAA4g");
	this.shape_11.setTransform(-110.45,-0.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAaA+IgahXIgZBXIgYAAIgjh7IAZAAIAXBVIAahVIAWAAIAZBWIAYhWIAYAAIgkB7g");
	this.shape_12.setTransform(-123.975,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_yourGut, new cjs.Rectangle(-134.9,-13.1,269.9,26.299999999999997), null);


(lib.txt_tellingYou = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AgMA8QgFgEAAgHQAAgGAFgFQAEgEAGAAQAGAAAEAEQAEAFAAAGQAAAHgEAEQgEAEgGAAQgGAAgEgEgAgMAYIAAgCQAAgJACgGQADgHADgDIAGgHIAHgFIAFgFQACgDAAgFQAAgGgEgEQgFgFgHAAQgHAAgEAEQgFAEgCAGIgVgJQAFgLAKgHQAKgHAOAAQAJAAAHACQAIADAFAFQAFAEADAHQADAGAAAIQAAAIgDAFQgCAFgEADIgHAGIgIAFQgEADgCAFQgCAEAAAGIAAACg");
	this.shape.setTransform(-46.625,-0.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFB71B").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_1.setTransform(-55.975,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFB71B").s().p("AgTAsQgIgEgHgGQgHgHgDgJQgDgIgBgKQABgJADgJQADgJAHgGQAHgGAIgEQAKgEAJAAQAKAAAJAEQAJAEAGAGQAHAGAEAJQADAJAAAJQAAAKgDAIQgEAJgHAHQgGAGgJAEQgJAEgKAAQgJAAgKgEgAgJgXQgFACgDAEQgDADgDAFQgBAEAAAFQAAAFABAFQADAEADAEQADADAFACQAEACAFAAQAFAAAFgCQAFgCADgDIAFgIQACgFAAgFQAAgFgCgEQgCgFgDgDQgDgEgFgCQgFgCgFAAQgFAAgEACg");
	this.shape_2.setTransform(-66.05,1.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFB71B").s().p("AgnA+QgHgDgFgDIANgTIAGAEQADABAEAAQAGAAAEgDQAEgDAEgIIABgEIglhXIAZAAIAXA7IAXg7IAYAAIgnBgQgEAJgEAGQgDAGgEADQgEAEgGACQgGABgHAAQgHAAgHgCg");
	this.shape_3.setTransform(-76.425,3.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFB71B").s().p("AgaA+QgKgFgIgJIATgPQAFAGAGADQAFAEAJgBQAFAAAEgBQAFgCADgEQAEgDACgEQACgFAAgFIAAgHQgFAHgIAEQgHADgIAAQgJABgIgEQgIgDgGgGQgGgHgEgJQgDgHAAgLQAAgLADgJQAEgIAGgHQAGgGAIgEQAIgCAJAAQAIgBAIAEQAHAEAFAGIAAgMIAXAAIAABUQAAAKgDAIQgEAJgGAGQgHAGgJAEQgJAEgKAAQgPAAgLgFgAgJgqQgEACgEADQgDAEgCAFQgCAEAAAGQAAAFACAFQACAEADAEQAEADAEACQAFACAEAAQAGAAAEgCQAFgCAEgDIAFgIQACgFAAgFQAAgGgCgEIgFgJQgEgDgFgCQgEgCgGAAQgEAAgFACg");
	this.shape_4.setTransform(-89.625,3.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFB71B").s().p("AATAvIAAgzQAAgKgFgGQgFgFgIAAQgIAAgGAGQgFAFAAALIAAAyIgYAAIAAhbIAYAAIAAALQAEgGAHgDQAHgEAIAAQAQAAAJAKQAKAKAAASIAAA3g");
	this.shape_5.setTransform(-99.7,1.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFB71B").s().p("AgLBDIAAhcIAXAAIAABcgAgJgnQgFgFAAgGQAAgHAFgEQAEgEAFAAQAHAAAEAEQAEAEAAAHQAAAGgEAFQgEAEgHAAQgFAAgEgEg");
	this.shape_6.setTransform(-106.45,-0.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFB71B").s().p("AgLBDIAAiFIAXAAIAACFg");
	this.shape_7.setTransform(-110.075,-0.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFB71B").s().p("AgLBDIAAiFIAXAAIAACFg");
	this.shape_8.setTransform(-113.675,-0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFB71B").s().p("AgSAsQgJgEgHgGQgGgHgEgIQgDgJAAgKQAAgJAEgJQADgJAHgGQAGgGAJgEQAJgEAJAAQAKAAAJAEQAJADAGAGQAGAHAEAIQAEAJAAAKIAAAIIhIAAQACAJAHAFQAHAFAJAAQAIAAAGgDQAFgDAEgGIATALQgHAKgKAGQgKAGgPAAQgKAAgJgEgAAYgJQgCgJgGgFQgHgEgJAAQgIAAgGAFQgHAFgDAIIAwAAIAAAAg");
	this.shape_9.setTransform(-120.575,1.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFB71B").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape_10.setTransform(-129.025,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_tellingYou, new cjs.Rectangle(-134.9,-13.1,269.9,26.299999999999997), null);


(lib.those_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ACDBJQgKgCgIgEQgIgEgGgFIgMgMIAegYQAHAKAJAFQAIAGANAAQAJAAAEgEQAFgEAAgGQAAgEgCgCIgFgEIgngLQgJgDgGgFQgHgDgEgIQgEgHAAgLQAAgKAEgIQAEgIAHgGQAHgGAKgEQAJgDAMAAQAKAAAIACQAJABAHAEQAGADAHAFIALALIgcAWQgFgJgHgEQgIgFgLAAQgJAAgEAEQgEAEAAAFQAAAEACACIAGAEIAmAKQAJADAHAFQAGADAFAIQAEAIAAALQAAALgEAJQgEAIgIAHQgHAGgKAEQgKADgMAAQgNAAgJgCgAgVBFQgOgGgKgKQgKgKgGgNQgGgOAAgQQAAgOAGgOQAGgOAKgKQAKgKAOgGQANgGAPAAQAQAAANAGQAOAGAKAKQAKAKAGAOQAGAOAAAOQAAAQgGAOQgGANgKAKQgKAKgOAGQgNAGgQAAQgPAAgNgGgAgIgkQgHADgFAFQgFAGgDAHQgDAIAAAHQAAAJACAHQADAHAGAGQAFAFAHAEQAHADAIAAQAJAAAHgDQAHgEAFgFQAGgGADgHQADgHAAgJQAAgHgDgIQgDgHgGgGQgFgFgHgDQgIgEgIAAQgHAAgIAEgADpBJIAAiRIBkAAIAAAhIhCAAIAAAYIBCAAIAAAfIhCAAIAAAZIBCAAIAAAggAh3BJIAAg4IgvAAIAAA4IgjAAIAAiRIAjAAIAAA4IAvAAIAAg4IAjAAIAACRgAklBJIAAhxIgnAAIAAggIBwAAIAAAgIgnAAIAABxg");
	this.shape.setTransform(-33.325,7.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.those_txt, new cjs.Rectangle(-66.6,0,66.6,15.1), null);


(lib.the_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ABUBJIAAiRIBlAAIAAAgIhCAAIAAAZIBCAAIAAAfIhCAAIAAAYIBCAAIAAAhgAAdBJIAAg4IgvAAIAAA4IgjAAIAAiRIAjAAIAAA4IAvAAIAAg4IAjAAIAACRgAiQBJIAAhxIgoAAIAAggIBxAAIAAAgIgnAAIAABxg");
	this.shape.setTransform(-18.475,7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.the_txt, new cjs.Rectangle(-36.9,0,36.9,14.6), null);


(lib.real_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ADxBFQgFgGAAgIQAAgJAGgGQAFgFAIAAQAKAAAFAFQAFAGAAAJQAAAIgFAGQgFAFgKAAQgIAAgGgFgAB7BIIAAiRIAjAAIAABwIBAAAIAAAhgABMBIIgHgWIg4AAIgHAWIgjAAIA1iRIAhAAIA2CRgAA6AUIgRgwIgRAwIAiAAgAiMBIIAAiRIBlAAIAAAgIhCAAIAAAZIBCAAIAAAfIhCAAIAAAYIBCAAIAAAhgAi/BIIgVgsIgcAAIAAAsIgiAAIAAiRIA+AAQAOAAAKAEQAKAEAHAHQAHAGAEAKQADAJAAAKQABAOgHALQgGALgLAGIAbA1gAjwgDIAaAAQALABAGgGQAFgGAAgIQAAgJgFgFQgGgFgLAAIgaAAg");
	this.shape.setTransform(-27.5,7.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.real_txt, new cjs.Rectangle(-55,0,55,14.8), null);


(lib.pain_Txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AD0BJQgKgCgIgEQgHgEgHgFIgLgMIAegYQAGAKAJAFQAJAGAMAAQAJAAAEgEQAGgEgBgGQAAgEgBgCIgGgEIgngLQgIgDgHgFQgHgDgEgIQgEgHAAgLQAAgKAEgIQAEgIAHgGQAHgGAKgEQAKgDALAAQALAAAHACQAJABAHAEQAHADAGAFIAMALIgcAWQgGgJgHgEQgIgFgLAAQgIAAgEAEQgEAEgBAFQABAEACACIAFAEIAnAKQAIADAHAFQAGADAFAIQAEAIABALQAAALgEAJQgFAIgIAHQgGAGgLAEQgKADgMAAQgMAAgKgCgABlBJIg6hbIAABbIghAAIAAiRIAkAAIA4BXIAAhXIAhAAIAACRgAgtBJIAAiRIAjAAIAACRgAhcBJIgIgWIg3AAIgIAWIgjAAIA2iRIAiAAIA2CRgAhuAVIgRgwIgSAwIAjAAgAlABJIAAiRIA5AAQANAAALAFQAKAEAIAHQAHAIAEAKQAEAJAAAMQAAALgEAJQgEAKgHAHQgHAIgLAEQgLAFgNAAIgXAAIAAAkgAkeAEIAWAAQAKAAAGgFQAHgGgBgKQABgLgHgGQgGgGgKAAIgWAAgACfgQQAKgHAEgHQAEgGABgHQgDAFgHAAQgHAAgDgEQgFgFAAgIQAAgIAGgGQAFgFAJAAQALAAAFAHQAHAHgBAKQABAOgIAKQgGAKgNAKg");
	this.shape.setTransform(-32.15,7.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.pain_Txt, new cjs.Rectangle(-64.3,0,64.3,15.1), null);


(lib.oh_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AhgBFQgNgGgKgKQgLgKgFgOQgGgOAAgPQAAgPAGgNQAFgOALgKQAKgKANgGQAOgGAPAAQAQAAAOAGQANAGAKAKQALAKAEAOQAGANAAAPQAAAPgGAOQgEAOgKAKQgLAKgNAGQgOAGgQAAQgPAAgOgGgAhSgkQgIADgFAFQgFAGgDAHQgDAIAAAHQAAAIADAIQADAHAFAFQAFAGAIAEQAHACAIAAQAJAAAHgCQAIgEAFgGQAFgFADgHQADgIAAgIQAAgHgDgIQgDgHgFgGQgGgFgHgDQgHgEgJAAQgIAAgHAEgABrBJIAAg4IgvAAIAAA4IgjAAIAAiRIAjAAIAAA4IAvAAIAAg4IAjAAIAACRg");
	this.shape.setTransform(-14.225,7.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.oh_txt, new cjs.Rectangle(-28.4,0,28.4,15), null);


(lib.need_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ACCBJIAAiRIA0AAQARAAANAFQAOAGALAKQAJAKAGANQAFAOABAOQgBAPgFAOQgGANgKAKQgKAKgOAFQgOAGgQAAgAClAoIAPAAQAKAAAIgCQAHgEAGgFQAGgGADgHQACgIAAgIQAAgIgCgHQgDgHgFgGQgGgGgIgDQgIgDgKAAIgPAAgAAHBJIAAiRIBlAAIAAAgIhCAAIAAAZIBCAAIAAAfIhCAAIAAAYIBCAAIAAAhgAhvBJIAAiRIBkAAIAAAgIhCAAIAAAZIBCAAIAAAfIhCAAIAAAYIBCAAIAAAhgAimBJIg6hbIAABbIggAAIAAiRIAkAAIA3BWIAAhWIAhAAIAACRg");
	this.shape.setTransform(-25.75,7.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.need_txt, new cjs.Rectangle(-51.5,0,51.5,14.6), null);


(lib.help_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ADvBFQgEgGAAgIQgBgJAGgGQAFgFAJAAQAJAAAFAFQAFAGABAJQgBAIgFAGQgFAFgJAAQgJAAgGgFgABmBIIAAiRIA6AAQANAAALAEQAKAEAHAIQAIAHAEAKQAEAKAAAMQAAAKgEAKQgEAKgHAHQgIAHgKAFQgLAFgNAAIgWAAIAAAkgACKADIAVAAQAJAAAHgFQAGgHABgJQgBgLgGgGQgHgGgJgBIgVAAgAgOBIIAAiRIAiAAIAABwIA/AAIAAAhgAiGBIIAAiRIBkAAIAAAgIhCAAIAAAZIBCAAIAAAfIhCAAIAAAYIBCAAIAAAhgAi+BIIAAg4IgwAAIAAA4IgjAAIAAiRIAjAAIAAA4IAwAAIAAg4IAjAAIAACRg");
	this.shape.setTransform(-27.35,7.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.help_txt, new cjs.Rectangle(-54.7,0,54.7,14.8), null);


(lib.boy_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ADHBGQgFgFAAgJQAAgJAGgGQAFgFAJAAQAJAAAFAFQAFAGAAAJQAAAJgFAFQgFAFgJAAQgJAAgGgFgAg7BFQgOgGgKgKQgKgKgGgOQgGgOAAgPQAAgPAGgNQAGgOAKgKQAKgKAOgGQANgGAQAAQAQAAANAGQANAGAKAKQAKAKAGAOQAGANAAAPQAAAPgGAOQgGAOgKAKQgKAKgNAGQgNAGgQAAQgQAAgNgGgAgugkQgHADgFAFQgFAGgDAHQgDAIAAAHQAAAIACAIQADAHAGAFQAFAGAHAEQAHACAJAAQAJAAAHgCQAHgEAFgGQAFgFADgHQADgIAAgIQAAgHgDgIQgDgHgFgGQgFgFgHgDQgIgEgIAAQgIAAgIAEgABlBJIAAg9IgwhUIAmAAIAcA1IAbg1IAmAAIgwBUIAAA9gAjoBJIAAiRIA5AAQAbAAANALQAOAKAAAVQAAAKgEAHQgEAHgHAFQAIADAFAIQAEAIAAALQAAAWgPAMQgOAKgbAAgAjGArIAYAAQAKgBAFgEQAFgDAAgHQAAgHgFgDQgEgEgLAAIgYAAgAjGgQIAZAAQAJAAAEgDQAEgEAAgGQAAgGgEgEQgEgDgJAAIgZAAg");
	this.shape.setTransform(-23.325,7.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.boy_txt, new cjs.Rectangle(-46.6,0,46.6,15), null);


(lib.safeCare_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8A9A7").s().p("EgROA1vQoEitm8lHQm1lClFm5QlIm9i2oMIAAAAIgGgSIgBAAQg5iogoirIC2AAQCJIqEzHfQEuHYGxFeQG0FhIJC9QIcDEJBAAQJBAAIbjEQIJi9G1lhQGwleEunYQEznfCKoqIC2AAQglCdhAC9IgBAAIgLAhQi3IHlJG6QlEG1m1E/Qm5FDoCCsQoUCyoyAAQo2AAoVi0gEgRCAxlQn7i3mqlWQmmlTknnJQktnRiJoZIArAAQCIIQEpHKQElHBGgFNQGkFRH0C0QIFC6IpAAQIoAAIGi6QH0i0GklRQGglNEknBQEpnJCIoRIAsAAQiJIZktHRQkoHJmlFTQmqFWn8C3QoNC+oxAAQoxAAoOi+gEgBPAsbIhnkmIA7ABIBIDbIBRjYIA5ACIhwEigEACGAn3IDAgSIAEA1IiIANIAGBBICIgNIAEA1IiIANIAGBCICIgMIAFA1Ii/ASgEgHFAr4IAlkiIC+AaIgGA1IiIgTIgIBBICHATIgGA0IiIgSIgIBCICHASIgHA2gEAF+AneIA5gMIChCqIgmjDIA0gLIA4EeIg1AMIimiwIAnDKIg0ALgEgJJArdIgXhkIg+gPIgVBZIg2gNIBCkcIBxAbQAuAMAWAiQAVAhgKAqQgGAcgSATQgSATgaAHIAfB1gEgKTAo3IA3AOQAaAGAQgLQAQgKAFgVQAFgVgKgPQgLgQgZgGIg3gOgEALzAm5IhMAZIgPgyIDKhCIAPAxIhKAZIBHDlIg0ARgEgP0ApaIBdkUIBqAmQAtAQATAoQASAmgOArQgOAqgmASQgoAUgsgQIg1gTIgaBLgEgOWAnwIAzASQAXAIAUgJQATgJAHgWQAIgXgKgTQgJgUgXgIIgzgSgEAPxAoRQgRgHgHgRQgHgSAHgRQAHgRARgHQARgHARAHQARAHAHARQAHARgHASQgIARgQAHQgIAEgJAAQgJAAgIgEgEARNAj2IBjg3QApgXAqAMQAnAMAWAoQAUAngLApQgNArgpAXIgyAcIAlBGIgwAbgEATFAjuIgvAbIAzBfIAvgaQAVgMAHgVQAFgVgLgVQgLgVgUgGQgHgCgHAAQgOAAgOAIgEgR5AngQgQgIgGgRQgHgSAIgRQAIgRARgGQARgHAQAIQARAIAHASQAFARgHARQgIARgRAHQgIADgHAAQgKAAgJgFgEgXRAlhICRj7IClBkIgaAtIh2hHIggA5IB2BHIgbAuIh2hHIghA5IB2BHIgbAugEAUqAh4IBghDQAogcAoAHQAlAHAYAjQAQAXACAbQABAbgNAYIBqA3IgzAkIhYgxIg1AlIAyBMIgtAggEAWkAhjIgvAgIA1BQIAvghQAVgPAEgUQADgTgMgRQgMgSgSgDIgFAAQgQAAgSANgEgY/AkUIARhmIg0gnIg1BKIgtghICqjrIBcBGQAnAeAHAoQAGAngZAiQgQAXgXALQgZAKgagEIgRB4gEgZEAheIAtAiQAVAQAUgDQATgDALgRQANgSgEgSQgDgTgVgQIgtgigEAazAiQQg9gFgngvQgngvADg9QAFg+AugpQAtgpA9AFQA8AEAoAvQAoAwgFA9QgDA/gvAoQgpAlg1AAIgMgBgAaAezQgcAZgCAnQgCAmAZAeQAZAeAlADQAmAEAdgaQAdgaACgmQACgngZgdQgZgeglgDIgJgBQghAAgaAXgEgcXAhoIAVg0IhYhTIgwAbIgqgoIEQiNIAoAmIhxEigA8qfIIA8A5IAvhygAxbbFQntlNjyomIAuAAQDvIUHgFCQHtFKJNAAQJNAAHslKQHhlCDvoUIAtAAQjxImntFNQn5FWpfAAQpfAAn5lWgAcxcJIg3A8IglgkICRifIAlAkIg2A7ICrCkIglApgAv+ZnQnFkojsntIG3AAIAOAWIAbgWIAbAAIgyAdQAqA+AqA1ICXiQIA8AAIjNCXQAxA7AvAvIDckBIBNAAIkjEHQAwAyA4AuID8lnIBXAAIlMFtQA5AvA4AmID/nCIBbAAIlTHHQA9AoA7AhIDsoQIBdAAIlAIUQA8AhBCAcIDGpRIMFAAIDDJIQBBgcA7giIk6oKIBdAAIDnIFQA7giA6gnIlLm8IBbAAID5G1QA5gpA0grIlBlhIBWAAIDzFaQA5gxAsguIkWj7IBNAAIDQDzQAugvAug5Ii8iLIA7AAICICCQAngyAqg/IgcgRIAZAAIAJAIIAFgIIG3AAQjsHtnGEoQnREwopAAQopAAnSkwgAhSc+IAwABIAGjIIgvgBgACwZuIhFAIIAYDHIBFgIQArgFAZggQAZgggEgrQgGgrgegYQgagVgjAAIgQABgAlccdIAsAIIBqi3IgvgJIhGB8IgViNIgvgKgAqIYKQglARgPAoQgQAoARAnQAQAnAoAPQAnAQAlgSQAmgRAPgoQAPgogRgnQgQgngngPQgTgHgSAAQgUAAgUAJgAGuaTIAKAmIBfgcIgKgmgALqaaIArgTIhSi2IgoATQASAqgqAUIgBAAIATArIAEgDQAcgMABgagAuYVuQgnAKgYAlQgWAlAIAnQAIApAmAYQAaARAcAAQAbgBAYgOIgYgsQgdAUgcgSQgTgMgEgWQgEgWAMgTQAMgUAVgGQAVgFAUAMQAZARgCAhIAxAAQAAgbgMgXQgNgYgXgPQgbgRgcAAQgKAAgLACgAOTY2QAZgBAbgSQBLgyg5haQgbgqgbgJQgegKgdATQgaARgGAcQgGAcAQAZQAQAZAZAGQAYAGAWgPQAXgQgCgXQALAWgEAPQgDAOgTAMQgPALgRgBgAANYWQBBAABJgIIhjp1gAiHYQQBCAGBCAAIAGAAIglp8gAkaX8QBLAOA/AFIAWp+gAChYNQBKgJA/gNIifpngAmrXYQBBAUBHAOIBTp6gAE0X1QBJgQA9gTIjZpTgAo3WmQBGAdA9ASICQpvgAHDXPQBAgVBBgcIkPo6gA9yd3QgsgBgggkIgmgrIg5A2IgmgqIDSjFIBMBUQAgAkgBAsQgDArggAeQgeAcgmAAIgFAAgA+/cEIAkAoQARASAVACQAVABASgQQARgQAAgWQABgWgQgSIgkgpgAeFZdIB0icIAqAgIhTBvIAyAoIBUhvIApAhIhTBvIAzAoIBUhvIApAhIh1CcgACfadIAUgDQAagDASAOQARAOACAYQACAYgNARQgNARgZADIgVADgEgjlAZcIDlivIBzCdIgqAgIhShwIgzAnIBSBwIgpAgIhThwIgzAoIBSBwIgrAggApzacQgVgIgJgVQgHgVAHgVQAIgWAVgKQAUgJAUAIQAWAIAIAVQAJAVgJAWQgIAVgUAKQgKAFgLAAQgKAAgKgEgEgkoAXyIA1hYIgig4IhMAvIgegwID0iYIA8BmQAaAqgJAoQgJAmgkAXQgXAOgaABQgaAAgXgOIg8BpgEgjqAVHIAdAxQAOAXAUAFQASAEARgLQASgLAEgSQAEgTgOgXIgdgxgEAiMAXtQg2ghgOg7QgPg7Ahg3QAVgjAigTQAigTAmAAIAAA7Qg2gDgbAuQgUAiAJAlQAKAkAiAVQAgAVAkgIQAlgJAUghQAPgZgCgbQgCgZgPgWIAygeQAWAkAAAoQABArgWAmQghA4g7AOQgRAEgQAAQgnAAglgYgAOIXBQgKgCgHgJQgFgKACgKQACgLAJgGQAJgGAKADQAKACAGAJQAGAJgCAKQgCALgJAGQgGAEgIAAIgFAAgEglIATdQgpgPgTgsIgZg0IhGAiIgYg0IECh9IAwBoQAVAsgPAqQgOAogoATQgWALgWAAQgRAAgSgGgEglvARXIAYAyQAKAWAUAIQATAHAWgKQAUgKAIgUQAHgVgLgXIgXgxgEAj5ARoIgiBKIgugXIBbjFIAtAXIghBIIDVBnIgYAygEA1NAS3ITPllIABAAIAAxUINfAAIrHLYILHLhgEhV7AS3ILHrhIrHrYINtAAIAARUIABAAITPFlgEA2HANSIQkAAIyDFPQA3ikAoirgEhGeANSIQQAAQAoCsA1CcgEhHvAMzIAA5DMCPtAAAIAAZDgAi/DqIAAFVIC1AAIAAocgAOtlXQiMCQABDWQAADWCGCPQCKCTDaAAQCUAAB3hOQBvhIBAh/IjTh0QgfBKg5ApQg+AthSAAQhwAAhJhPQhHhOAAhyQAAhzBJhOQBJhQBwAAQBNAAA7AmQA4AlAgBDIDJiCQhBhvhuhBQhzhCiIAAQjTAAiMCRgEhC4AFDQBLBcBdAwQBuA4CVAAQCeAABohbQBnhbAAiLQAAiNhnhJQhBgviQgiQh2gdgWgJQg2gXAAgoQAAgkAcgYQAfgbA3AAQBFAAA0AeQAvAdAjA4IC3iSQhRhahSgoQhcgth+AAQiZAAhiBXQhjBVAACBQAACHBjBHQBBAwCJAgQB4AdAeAPQAwAXAAAtQAAAqgeAYQggAag5AAQhOAAg8glQg4gigshEgEA3uAH5IKVAAIAAjZImxAAIAAinIGxAAIAAjZImxAAIAAihIGxAAIAAjaIqVAAgEAwXADTICHEmID8AAIiyliQBIgsAphMQAqhLAAhdQgBiRhdheQhihjioAAImcAAIAAPUIDkAAIAAkmgEAkeAFnIAyCSIDoAAIlivUIjdAAIlhPUIDnAAIAxiSgA4NH5IKWAAIAAjZImxAAIAAinIGxAAIAAjZImxAAIAAihIGxAAIAAjaIqWAAgEglMAH5IDkAAIAAlxIGuAAIAAjXImuAAIAAivIGuAAIAAjdIqSAAgEgrcAFnIAyCSIDoAAIlivUIjdAAIlhPUIDmAAIAyiSgAAQGSIC1AAIAAioIi1jHgADbDYIFDAAIAAi8In/AAgAlwDYICdAAIC7i8IlYAAgAAfADIFXAAIABi8IicAAgAoXADIH/AAIi/i8IlAAAgAAQgDIC1jIIAAlVIi1AAgAi/jLIC1DIIAAlvIi1AAgAf3CbIBxlJIBwFJgEgwDACbIBxlJIBxFJgEAtjAAAIAAkFICnAAQBHAAAlAiQAjAiAAA9QAAA6gjAjQgmAnhGAAgEAy6gMvQiFowkynmQktndmyljQm2lmoNjAQogjHpEAAQpFAAogDHQoNDAm2FmQmyFjktHdQkxHmiFIwIi1AAQCGpUFBoGQE7n+HLl7QHQl+IsjNQJAjVJpAAQJpAAJADVQItDNHOF+QHMF7E7H+QFBIGCGJUgEAxBgMvQiEoXkonPQkjnImhlSQmmlVn4i3QoKi9osAAQotAAoJC9Qn4C3mmFVQmiFSkiHIQkoHPiFIXIgrAAQCFofErnXQEnnPGnlYQGslbH/i6QISjAI1AAQI1AAISDAQH/C6GrFbQGoFYEmHPQEsHXCEIfgAcVsvQjqoinmlLQnylUpWAAQpXAAnyFUQnlFLjrIiIgtAAQDso0HzlXQH+lgJpAAQJoAAH/FgQHzFXDrI0gAUHsvIgWgkIguAkIgiAAIBLgsQgqhBgogyIinCfIhBAAIDiinQgrg1gyg1IjrERIhRAAIE2kYQgzg2g0grIkJF5IhaAAIFcl/QgugphCguIkKHWIhfAAIFinbQg2gnhCglIj0InIu4AAIj5otQhDAmg2AmIFmHhIhfAAIkOndQg7Aqg3AuIFiGFIhZAAIkPmAQg2AtgzA1IE8EeIhQAAIjykYQgxA0gtA4IDoCsIhAAAIiuilQgwA9gkA4IBRAwIggAAIg1gpIgZApImyAAQDnn7HKkyQHXk6I0AAQIzAAHXE6QHMEyDmH7gArK1fIFRIuIjQptQhBAchAAjgAGBszIFMonQg8ghhDgegApC2hIEZJNIiTp+QhEAVhCAcgAEwtWIEWpGQhGgeg+gUgAm03VIDgJnIhWqKQhBANhJAWgADctvIDepiQhLgXg+gNgAkj35ICkJ5IgWqOQhHAHhHAOgACGuBICjp2QhHgPhFgHgAiN4PIBlKGIAoqMIgDgBQhEAAhGAHgAAvuJIBmqFQhNgHhBAAgAM12VQAJAWAcASQBMAyA4haQAagqgDgeQgEgggcgTQgagRgbAFQgbAGgQAZQgQAaAFAZQAEAZAXAOQAXAQAUgLQgPASgPADQgOADgSgMQgPgKgHgRgAuL4tQgbABgYAPQgkAXgJApQgJApAXAlQAXAkAmAKQAoAKAlgYQAagQAMgbQAMgZgDgdIgwAEQAEAjgcASQgTANgVgGQgUgGgNgTQgLgUADgWQAEgWAUgMQAagSAcARIAUgtQgUgKgWAAIgGAAgAKW3bIArATIBQi2IgpgTQgTApgrgTIgBgBIgTArIAGACQAcANASgQgAqO64QgnAPgQAnQgRAnAPAnQAPAoAlASQAmARAngQQAogPAQgnQAQgmgPgpQgPgngmgRQgUgKgUAAQgSAAgSAIgAmy8AIBsC3IAsgJIAjjSIgwAJIgVCOIhFh8gABl5qIBFAIQAsAFAfgaQAggZAEgqQAFgrgZgfQgZgggtgFIhFgIgAGj6CIBgAcIALgmIhggcgAhd8xIAIDIIAvgCIgIjIgEgoZgSlIBNiYQAihFAtgVQAtgVA0AcQAyAaAEA0QAxghA3AdQA5AeAJA2QAIA0gjBHIhMCXgEgjPgTsQgQAIgPAcIgfA/IBIAnIAhhBQAZgzgkgUQgKgFgKAAQgGAAgGADgEgl9gUXIghBCIBCAjIAihDQAXgsgjgSQgJgFgIAAQgVAAgRAhgEAiZgQeQghgYgXguQgihEAVg/QAUg+A+ggQA8ggA/AVQA/AVAhBAQAgBAgVA/QgTA/g+AgIgdAQIhqjTQgRASgDAXQgDAWANAZQAUAoAmADIgFBdQgpgHgdgXgEAj1gT/IA8B5QAfgigXgtQgKgVgSgLQgSgKgUAAIgCAAgAfr04QgfgvAIglQAJgpA3gnIBag9IgeguIBHgxIAdAuIA4gnIBhA0IhjBEIArBBIhHAxIgrhBIhUA6QgTANgEAMQgCAKAHALQAIAMAPADIglBQQgrgQgZgngEghHgVRQgngdgCgxQgBgxAmg1IApg8IgBgBQgRgMgRAFQgRAEgPAVQgYAjAQAiIhXA0QgZhYA3hQQApg6AxgMQAygMAwAkICbBxIg1BOIgigZQAIAagFAfQgGAfgVAdQgcAoglAJQgKADgJAAQgcAAgZgTgEggNgXoQgeArAZASQATAPAWgfQAOgUABgbQABgagMgSIgFgDgAOj3AQgJgGgCgKQgDgKAGgKQAGgJAKgCQAKgCAJAFQAJAGACALQACAKgFAJQgGAJgKADIgFAAQgHAAgHgEgA8j4vQAbAAAQgRQAagbgTgpIgFgMIkth5IBHhNICuBKIhUirIBFhKICVFIQAdA/gDApQgDAogkAnQgmApg3AJgAc447IDyjIIA+BPIjyDJgAqA4mQgTgKgJgVQgHgWAIgUQAIgVAVgJQAVgIAUAKQAUAJAIAWQAIAVgIAVQgJAVgUAIQgKAEgKAAQgLAAgLgFgAbP6xIB9h/QAogoghgjQgQgQgTACQgWABgVAWIh5B7IhEhFIFClIIBDBGIh+CAQAzgHAlAlQAkAmgBAtQgBAvgpApIiKCNgACt6PIgWgCIANhvIAUADQAaADAOARQANARgCAYQgDAYgRAOQgOALgTAAIgJAAgEAiDgbUQgYgDgQgUQgQgVADgXQACgXAUgQQAVgRAWACQAXADAQAUQAQAUgCAYQgDAXgUARQgRAOgTAAIgGAAgEgdvgiRIBIhAIEpFfIhJBAgAWd/HIBakKIjSC1IhSg7ICQmlIBUA7IhdEBIDPiwIBOA5IhXEFIDKi0IBSA7IlQEdgA3Y/LQhAgMgng4Qgng5AMhDQALhDA8grQA6gpBCALQBCAMAnA4QAnA5gMBDQgMBDg8ArQgtAggzAAQgOAAgPgCgEgXfgitQgXARgGAeQgFAdARAYQAQAZAdAFQAdAFAXgRQAYgRAGgdQAFgdgRgZQgRgYgdgGIgMgBQgVAAgTANgEgVEgl7IBVgtIAUAoQgDg5A5geQAXgMAegCIAPBoQgVgEgYANQg3AdAfA/IBHCKIhVAugEAPdgjUIgbhBQgqARgfAAQgdABgjgOQg4gXgWgtQgVgrATgyQAOgjAigUQAagPAsgIQgKgfAAgXQABgXALgbQAQgqArgQQAsgRAuASQAvATAUAqQAVAqgSArQgMAfgdATQgXAOglAKIAWA2IBZgxIBqArIidBWIBECdgEANKgmSQgHAPAHAPQAGANAQAHQAOAGAOgBQAPgBATgJIghhOQgrAKgIAXgEAPDgpWQgLAEgEAMQgFAMAAALQACAMAGATQAqgJAJgXQAFgMgFgKQgGgLgLgEQgGgDgGAAQgFAAgFACgEgNBgknQgtgHgsgdIA+heQA3AuA/gVQAYgHAKgPQAJgOgFgSQgGgTgXgDQgPgCg2AEQg9AFgigLQgzgRgRg4QgRg2AfgxQAegyBAgVQA1gRAsAGQAoAGAtAbIg6BWQgsgng3ASQgYAHgJAQQgJAOAFAPQAFARAZACQAMABA0gEQBBgFAhALQA0ARATA6QASA7gfA0QggA0hCAVQgsAOgnAAQgRAAgQgCgEAIAgltQg1gKgUghQgXgjANhDIAVhtIg0gKIAPhWIA1ALIANhEIBogiIgXB4IBLAPIgRBWIhKgPIgUBnQgEAWAFALQAFAJANADQANADAOgJIAdBSQgcAOgfAAQgNAAgPgDgEgH8gmfQg1gngLhFQgMhGAng3QAng3BFgLQA2gJAuAVQAsAVAaAsIhUAyQgKgUgTgKQgTgJgVAEQgcAEgRAZQgQAYAEAeQAFAcAYASQAXARAbgEQAWgEAOgPQAOgPAFgWIBhAVQgOAzghAgQglAkg2AJQgRADgPAAQgyAAgqgfgEAELgmVQg2gFgXgfQgaghAFhEIAKhuIg1gEIAHhXIA2AEIAGhEIBkgtIgLB6IBMAHIgIBXIhMgHIgJBoQgBAXAGAKQAFAJAOABQANACANgLIAlBPQghAVgmAAIgOAAgEgC+gnPQgwgugChFQgChGAugxQAtgyBJgCQBGgCAxAvQAxAuACBFQACBGgtAxQguAyhIACIgGAAQhEAAgvgtgEgBLgqQQgeABgTAVQgUAWAAAeQACAeAVAVQAVAUAdgBQAdgBAUgWQAUgVgBgeQAAgegWgVQgUgTgdAAIgBAAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.safeCare_Logo, new cjs.Rectangle(-550,-361.8,1100,723.7), null);


(lib.BSWH_Logo_Dallas = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjkCMQgEgEAAgGQAAgHAEgEQAEgEAGAAQAHAAAEAEQADAEAAAHQAAAGgDAEQgEAEgHAAQgGAAgEgEgAjeB5QgBABAAAAQgBABAAAAQAAABAAAAQAAAAAAABIgBAFQAAAEACACQACADADAAQAEAAACgDQACgCAAgEIgBgFIgCgEIgFgBQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAgAl4CMQgEgEAAgGQAAgHAEgEQADgEAHAAQAGAAAEAEQAFAEAAAHQAAAGgFAEQgEAEgGAAQgHAAgDgEgAlyB5IgDAEIgBAFQABAEABACQACADAEAAQAEAAACgDQABgCABgEIAAgFIgDgEQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAgAh4CQIAAgMIgMAAIAAAMIgGAAIAAgcIAGAAIAAAKIAMAAIAAgKIAGAAIAAAcgAifCQIAAgXIgJAAIAAgFIAYAAIAAAFIgJAAIAAAXgAiyCQIgBgHQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIgEgBIgGAAIAAALIgGAAIAAgcIAPAAQADAAADACQACACAAADQAAAGgFACQAFABAAAFIAAAEIABACIABABgAi+CAIAHAAQAEAAAAgEQAAgEgEAAIgHAAgAj6CQIgGgUIgEAUIgHAAIgHgcIAGAAIAFATIAFgTIAGAAIAEATIAGgTIAFAAIgHAcgAkzCQIAAgXIgIAAIAAgFIAXAAIAAAFIgJAAIAAAXgAlGCQIgBgCIAAgFIgCgDIgDgBIgHAAIAAALIgFAAIAAgcIAPAAQADAAADACQACACAAADQAAAGgEACQAEABAAAFIAAAEIAAACIABABgAlTCAIAIAAQAEAAAAgEQAAgEgEAAIgIAAgAmVCQIAAgcIAUAAIAAAFIgOAAIAAAGIAMAAIAAAFIgMAAIAAAMgApfBlIAAhLIApgqIAAB1gAouBRQgCgCAAgDQAAgDACgCIAFgCQAEAAACACQABACAAADQAAADgBACQgCACgEAAIgFgCgAotBIIgBAEIABAEQAAABABAAQABAAAAAAQABABAAAAQABAAAAAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAABgBIABgEQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABQgBAAAAABgAomBQIgDgDIgCAAIAAADIAAAAIAAgIIACAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAIADAEgAorBLIACAAQABAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAgBAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgCAAgAE3A9QgEgGAAgJQAAgKAEgFQAGgGAJAAQAGAAAFAEQAFADABAHIgJAAQAAgDgCgCQgCgCgEAAQgEAAgDACIgDAFIAAAHQgBAGADADQACAEAGAAQAEAAACgCQACgCABgFIAIAAQgBAIgEAEQgFAEgHAAQgJAAgGgFgACiA9QgFgGgBgJQABgKAFgFQAGgGAIAAQAGAAAGAEQAFADAAAHIgIAAQAAgDgDgCQgDgCgDAAQgEAAgCACIgEAFIgBAHQAAAGADADQACAEAGAAQAEAAACgCQADgCAAgFIAIAAQAAAIgFAEQgFAEgHAAQgIAAgGgFgAhEA/QgEgEAAgHIAJAAQAAAEACACQADACAEAAIADgBIADgBIABgDIgBgCIAAgBIgCgBIgJgDIgEgBIgEgCIgDgDIAAgFQgBgEADgDQACgCAEgCQACgBAFAAQAEAAADABQAEABACADQACADAAAFIgIAAQAAgHgIAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAQABABAAAAIAJADQAGABADACQADADAAAFQAAAGgEAEQgEADgIAAQgHAAgGgDgAkEA/QgFgEAAgHIAIAAQABAEACACQACACAEAAIAEgBIADgBQAAAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIgBgCIAAgBIgBgBIgCgBIgIgCIgFgBIgDgCIgCgDIgCgFQAAgEADgDQACgDADgBIAHgBQAFAAADABQADABADADQACADAAAFIgIAAQAAgHgJAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAABABQAAAAAAAAQAAABABAAQAAABABAAIAJADQAGABACACQAEAEAAAEQAAAGgEAEQgFADgHAAQgHAAgFgDgAImBBIgBgCIAAgHIgCgEQgDgCgDAAIgJAAIAAAPIgIAAIAAgnIAVAAQAGAAADADQADADAAAEQAAAIgGADQAFABABAIIAAAGIACADgAIUArIAKAAQAHAAAAgFQAAgGgHAAIgKAAgAHiBBIAAgnIAfAAIAAAHIgWAAIAAAJIAUAAIAAAGIgUAAIAAAKIAWAAIAAAHgAHDBBIAAggIgLAAIAAgHIAhAAIAAAHIgNAAIAAAggAGmBBIgRgbIAAAbIgJAAIAAgnIAJAAIARAaIAAgaIAIAAIAAAngAFjBBIAAgnIAeAAIAAAHIgVAAIAAAJIASAAIAAAGIgSAAIAAAKIAVAAIAAAHgAD4BBIAAgnIAJAAIAAAgIAUAAIAAAHgADmBBIgDgIIgPAAIgDAIIgJAAIARgnIAIAAIAOAngADXAyIAKAAIgFgPgACIBBIAAgnIAJAAIAAAngABaBBIAAgnIARAAQAHAAAGAFQAFAFAAAJQAAAJgFAGQgFAFgIAAgABjA6IAHAAQAEAAADgDQADgDAAgGQAAgGgDgEQgCgDgHAAIgFAAgAAwBBIAAgnIAdAAIAAAHIgVAAIAAAJIAUAAIAAAGIgUAAIAAAKIAXAAIAAAHgAAbBBIAAgbIgKAbIgHAAIgJgbIAAAbIgIAAIAAgnIAMAAIAJAbIAIgbIANAAIAAAngAhkBBIAAggIgMAAIAAgHIAhAAIAAAHIgMAAIAAAggAiDBBIgRgbIAAAbIgIAAIAAgnIAJAAIARAaIAAgaIAIAAIAAAngAiyBBIAAgnIAJAAIAAAngAjEBBIgCgIIgPAAIgDAIIgJAAIAOgnIAKAAIAOAngAjTAyIAKAAIgEgPgAlCBBIAAgnIAJAAIAAAgIATAAIAAAHgAloBBIAAgnIAJAAIAAAgIASAAIAAAHgAl6BBIgEgIIgOAAIgEAIIgIAAIAPgnIAIAAIAPAngAmKAyIAKAAIgEgPIgCAAgAowA/IAAhPIAoAqIAAAlgAoDAWIgqgoIBzAAIAAAogAqGAWIAAgoIBMAAIgpAogAkKAGQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBgBAAQABgCACgCQAAgBABAAQAAAAAAAAQABgBAAAAQABAAABAAIADAAQAEAAABgCIAIgPIABgGIAAgFIgDgGIgMgiIgDgIQgDgEgDAAIgEgBIgBgCIACgCIAOAAIAPAAIABACIgBACIgFABQAAAAgBAAQgBAAAAABQgBAAAAAAQAAAAAAABIAFAPIAFAOIAFALIAFgMIAGgMQAFgNAAgCQAAgBAAAAQAAgBgBAAQAAgBgBAAQgBAAgBAAIgFgBIAAgCIAAgCIAPAAIALAAIABACIAAACIgDABQgDAAgEAEIgGAMIgJASIgYAzQgEAIgGAAQgEAAgCgDgAotgXIAqgpIAjAAIAAApgAqrgXIAAgpIBHAAIAqApgAKHgbQgGgDgDgFQgIgIABgMQgBgPAKgKQAJgLANAAQAKAAAGAGQAGAGABAHIgBAEQAAABgJAAIgdAAIgEABIgBAEQAAAMAHAIQAIAJALAAQAFAAADgCIAHgGQAAAAABAAQAAAAABAAQAAAAAAABQAAAAABABQgEAHgIAEQgGAEgHAAQgIAAgFgDgAKIhRQgFAEAAAFIABAAIAMAAQAOAAACgBIABgDQgBgEgDgDQgCgDgHAAQgGAAgGAFgAJWgeQgDgDAAgIIAAgkIgBgEIgCgBIgFAAIgBgCIAAgBQAIgCACgDQAEgDADgGIACAAIABABIAAAGIABADIACAAIARAAQABABAAAAQAAAAABABQAAAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAAAIgSAAIgCABIgBADIAAAdQABAJABADQACAFAIAAIAEAAIAEgCIABABIABABQgHAIgKAAQgJAAgEgGgAGsgZIgTgsQgNAcgGAQIgCABIgDgBIgLgZIgehBIgEgIQgCgDgFgBIgEAAIgBgCIACgCIAQABIASgBIAAACIAAACIgDAAQgFABgBACQAAADAJASQAEALAXAwIAMgaIADgGIgBgEIgSgmIgFgGQgCgCgDgBIgEAAIgBgCIABgCIARABIARgBIABACIAAACIgEAAQgFABgBACIACAGIANAbQAFgLAEgJQAEgKAAgDQAAgCgEgBIgGAAIAAgCIABgCIAPABIAPgBIABACIAAACIgFAAQgFABgDAEQgCABgDAIQgGAMgGAOIgCADIABAEIAQAkIAPghIAMggIAFgOQAAgDgGgBIgEAAIgBgCIABgCIAPABIABAAQAJAAAEgDIAIgGIABAAIAAABIAAAUIAAAhIAAADQALgJAKAAQALAAAFAHQAFAFAAAJIAAAaQAAAJABACQABACAEABIAEAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgOAAIgQAAIgBgCQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAIADAAQAFgCABgBIAAgLIAAgXQAAgIgDgEQgFgFgHAAQgHAAgFAFIgDADIAAAGIAAAaIABALQABACAEABIADAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgBACIgPAAIgQAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIABgCIAFAAQADgBABgCIABgLIAAhHIgBgJQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgFAFIgKAWIgLAbQgKAWgJAZIgCABIgDgBgADWgeQgEgDAAgIIAAgkIAAgEIgCgBIgGAAIAAgCIAAgBQAHgCADgDQAEgEADgFIACAAIABABIAAAGIABADIACAAIARAAQAAABABAAQAAAAAAABQABAAAAABQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAAAIgSAAIgCABIgBADIAAAdQAAAJACADQACAFAIAAIADAAIAFgCIABABIABABQgIAIgJAAQgKAAgDgGgACmgeQgDgDAAgIIAAgkIAAgEIgDgBIgFAAIgBgCIABgBQAHgCADgDQADgEADgFIACAAIACABIAAAGIAAADIADAAIARAAQAAABABAAQAAAAAAABQAAAAAAABQABABAAAAQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAAAIgRAAIgDABIgBADIAAAdQAAAJACADQADAFAIAAIADAAIAEgCIACABIAAABQgGAIgLAAQgJAAgEgGgABbghQgJgJAAgPQAAgPAKgJQAJgKAPAAQANAAAJAJQAKAKAAAOQAAAPgKAJQgJAKgPAAQgNAAgKgJgABlhPQgFAHAAANQAAAMAEAJQAHAJAJAAQAKAAAEgJQAEgHAAgKQAAgMgEgJQgGgKgLAAQgHAAgFAHgAAgghQgJgIAAgOQAAgPAJgKQALgLATAAQAHAAAGADQACACAAAEIgBAEQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgCgBQgDgDgEgDQgEgCgFAAQgJAAgGAGQgGAHAAAMQAAAKAGAIQAIAJAKAAQAIAAAEgDIAGgHIADABIAAACQgDAHgJAFQgGAEgIAAQgOAAgIgJgAgrgeIgDgJIgCgNIADgBIABABQAHAXAVAAQAIAAAGgGQAEgEAAgIQAAgHgCgEQgCgGgIgFIgPgKQgHgFgEgGQgGgHAAgJQAAgLAIgIQAJgIAQAAQAGAAAGACIAHACIABAIIABAKIgCACQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAAAQgCgIgEgEQgEgGgLAAQgJAAgGAGQgDAFAAAGQAAAHAFAFQADAFAGADIAMAHQASAMAAATQAAANgJAIQgIAIgPAAQgOAAgKgGgAihghQgJgJAAgPQgBgPALgJQAJgKAPAAQANAAAJAJQAJAKAAAOQAAAPgJAJQgKAKgPAAQgNAAgJgJgAiXhPQgFAHgBANQAAAMAFAJQAGAJAKAAQAJAAAFgJQADgHAAgKQAAgMgFgJQgEgKgLAAQgIAAgEAHgAkjgeIgDgCIgCACIgDACIgFACIgHACQgHAAgEgEQgEgFgBgGQAAgFADgDQADgDAIgCIASgHIACgCIABgDIAAgGQAAgGgCgEQgDgEgHAAQgDAAgDABQgDACAAAEQAAAEgCABQgBAAAAABQAAAAgBAAQgBABAAAAQgBAAgBAAIgEABQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBAAAAgBQAAgFALgHQAKgHAJAAQAJAAADAFQAFAFgBAJIgBAbQAAANAHAAIAFgBIACAAQAAAAAAAAQAAAAAAAAQAAAAAAABQAAAAAAAAQAAACgDADQgFADgFAAQgGAAgEgGgAktg0QgIACgCACQgEADABAEQgBADACADQADADAGAAIAFgBIAEgCIABgDIABgFIAAgJQAAgBAAAAQAAgBAAAAQAAAAAAAAQgBAAAAAAIgHACgAowiPIAoAAIAABKIgoAsgApfhFIAAgkIApAAIAABQgAFHgbQgFgBgFgFQgHAFgGABQgGACgHAAQgOAAgKgIQgKgIAAgMQAAgRATgIQgGgHAAgHQAAgJAFgFQAGgGAIAAQAGAAAEAEQAFADAAAFQAAAFgFAEQgDACgDAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBAAAAIACgCIAAgFIgDgEIgGgCQgEAAgDACQgDACAAAEQAAAEADADIALAIQAOAHAFAFQAKAJAIANQAFgGAAgIQAAgGgEgFQgCgDgEAAQgEgBgDAEIgDAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAgEAEgCQAEgDAGAAIAHABIAGABQABAAABAAQAAAAABAAQAAAAAAgBQABAAAAAAIABgBIACABQAAAEgDADQgCACgGACQADAEgBAGQABALgJAKQADAHAEACQAEADAFAAIAEgBIAEgBQAAAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABQAAACgFABQgEACgHAAQgFAAgEgCgAEOg+QgBAMAKAJQAIAJALAAIAIgBIAJgEIgIgIIgDgFQgFgJgHgGIgKgHIgDgDQgJACAAALgAI1gaIgOAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgCIAEAAQAEgBABgCIAAgLIAAgcIAAgGIgDgDIgCgBIgBgCIABgBIAIgEIAIgDIACAAIgBAUIAAAcIABALQABACAEABIAEAAIAAACIgBACIgPAAgAhSgaIgPAAQAAAAAAAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgCIADAAQAEgCABgBQABgCAAgJIAAgcIAAgGIgFgDIgBgBIAAgCIAAgBIAQgHIABAAIAAAJIABACQAFgFADgBQAGgEADAAQADAAADACIABAFQAAADgBACIgFACIgEgBQgDgDgEAAQgDAAgDADQgCADAAAKIAAAVQAAAJABACQACACAEABIAGAAQAAAAAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAgAi/gaIgPAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgCIAEAAQAEgBABgCQABgCAAgJIAAhHIAAgJQgBgCgEgCIgCgBIAAgCIAAgBIARgHQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAAUIAABKIAAALQABACAFABIADAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgBACIgPAAgAmNgaIgSAAQgBAAAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIABgCIAEAAQAFgCACgDQABgDAAgMIAAg7QAAgKgBgCQgCgDgFgBIgFgBIgBgCQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAQAOgCAUAAQARAAAJAFQAMAFAAAOQAAAIgEAGQgEAEgIAEQAAAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAIACAGAGQAIAHgBALQAAAPgKAHQgLAJgUAAIgTAAgAmGhPQAAAAgBABQAAAAAAAAQAAABAAAAQgBABAAAAIAAAYQABANADAEQADAEAJAAQALAAAHgFQAHgGAAgLQAAgLgHgHQgIgJgRAAQgFAAgCABgAmGh9IgBABQAAAAAAABQAAAAAAAAQAAABAAAAQgBABAAAAIAAAgQAAABABABQAAAAAAABQAAAAAAABQABAAAAAAIAGABQANgBAGgEQAGgFABgKQgBgLgHgGQgHgFgJAAIgIABgAIvhqQgCgBAAgEQAAgEACgCQACgCAEAAQADAAACACQACACAAADQAAAFgCACIgGABQgDAAgCgCg");
	this.shape.setTransform(-87.45,-26.675);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BSWH_Logo_Dallas, new cjs.Rectangle(-155.9,-41.1,136.9,28.900000000000002), null);


(lib.head_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.head_img();
	this.instance.setTransform(-50.8,-43.6,0.841,0.841);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.head_mc, new cjs.Rectangle(-50.8,-43.6,105.19999999999999,86.6), null);


(lib.ClipGroup = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AjECBIECkBICHAAIAAEBg");
	mask.setTransform(19.65,12.925);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0.004,0.608],-19.6,0,19.7,0).s().p("AjECBIECkBICHAAIAAEBg");
	this.shape.setTransform(19.65,12.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,39.3,25.9), null);


(lib.arent_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AEhBKIAAhxIgnAAIAAggIBwAAIAAAgIgnAAIAABxgACPBKIg5hbIAABbIghAAIAAiRIAkAAIA3BXIAAhXIAhAAIAACRgAhHBKIAAiRIBjAAIAAAhIhBAAIAAAYIBBAAIAAAfIhBAAIAAAZIBBAAIAAAggAh+BKIgUgsIgcAAIAAAsIgiAAIAAiRIA+AAQAOAAAKAEQAKAEAHAHQAHAHAEAJQADAJAAAKQAAAOgGALQgGALgLAGIAbA1gAiuAAIAaAAQALAAAFgGQAGgGAAgIQAAgJgGgFQgFgFgLAAIgaAAgAj/BKIgIgWIg3AAIgIAWIgjAAIA2iRIAhAAIA2CRgAkRAWIgRgwIgSAwIAjAAgADHgPQAJgHAFgHQAEgGABgHQgDAFgHAAQgHAAgEgEQgEgFAAgIQAAgIAFgGQAGgFAJAAQALAAAFAHQAGAHAAAKQAAAOgHAKQgHAKgMAKg");
	this.shape.setTransform(-36.225,7.425);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.arent_txt, new cjs.Rectangle(-72.4,0,72.4,14.9), null);


(lib.antacids_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AGxBJQgKgCgIgEQgHgEgHgFIgLgMIAegYQAGAKAJAFQAJAGAMAAQAJAAAEgEQAGgEgBgGQAAgEgBgCIgGgEIgngLQgIgDgHgFQgHgDgEgIQgEgHAAgLQAAgKAEgIQAEgIAHgGQAHgGAKgEQAKgDALAAQALAAAHACQAJABAHAEQAHADAGAFIAMALIgcAWQgGgJgHgEQgIgFgLAAQgIAAgEAEQgEAEgBAFQABAEACACIAFAEIAnAKQAIADAHAFQAGADAFAIQAEAIABALQAAALgEAJQgFAIgIAHQgGAGgLAEQgKADgMAAQgMAAgKgCgABTBFQgOgGgKgKQgJgKgGgNQgGgOABgQQgBgPAGgNQAGgOAKgKQAKgKAOgGQANgGARAAQAKAAAJADQAKACAIAFQAJAFAHAHQAHAGAEAIIgeAUQgFgKgJgGQgIgGgMAAQgJAAgIAEQgGADgGAFQgFAGgDAHQgDAIAAAHQAAAJADAHQADAHAFAGQAFAFAHADQAIAEAIAAQANAAAJgHQAJgHAFgKIAgARQgFAJgHAIQgGAHgJAGQgJAFgKADQgKADgLAAQgRAAgOgGgAD+BJIAAiRIAzAAQARAAAPAGQAOAFAJAKQAKAKAGANQAGAOAAAOQAAAQgGANQgGAOgKAJQgKAKgNAGQgOAFgRAAgAEgApIAQAAQAKAAAIgDQAIgEAFgFQAFgGADgHQAEgHAAgJQAAgHgEgIQgCgHgFgGQgGgFgIgDQgIgDgKAAIgQAAgADGBJIAAiRIAjAAIAACRgAAABJIgHgWIg3AAIgIAWIgjAAIA2iRIAhAAIA1CRgAgRAVIgRgwIgSAwIAjAAgAiqBJIAAhxIgnAAIAAggIBwAAIAAAgIgnAAIAABxgAkHBJIg6hbIAABbIghAAIAAiRIAkAAIA3BXIAAhXIAiAAIAACRgAmTBJIgIgWIg4AAIgHAWIgjAAIA2iRIAhAAIA2CRgAmmAVIgRgwIgRAwIAiAAg");
	this.shape.setTransform(-51.05,7.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.antacids_txt, new cjs.Rectangle(-102.1,0,102.1,15.1), null);


(lib.txt_deepBreath = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// help_txt
	this.instance = new lib.help_txt();
	this.instance.setTransform(-138.15,119.1,1,1,0,0,0,-27.4,7.4);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(89).to({_off:false},0).to({y:104.1,alpha:1},17,cjs.Ease.quadOut).wait(115));

	// need_txt
	this.instance_1 = new lib.need_txt();
	this.instance_1.setTransform(-101.65,98.45,1,1,0,0,0,-25.8,7.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(85).to({_off:false},0).to({y:83.45,alpha:1},17,cjs.Ease.quadOut).wait(119));

	// we_txt
	this.instance_2 = new lib.we_txt();
	this.instance_2.setTransform(-150.5,98.45,1,1,0,0,0,-15.8,7.3);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(81).to({_off:false},0).to({y:83.45,alpha:1},17,cjs.Ease.quadOut).wait(123));

	// working_txt
	this.instance_3 = new lib.working_txt();
	this.instance_3.setTransform(-114,77.15,1,1,0,0,0,-53.1,7.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(62).to({_off:false},0).to({y:62.15,alpha:1},17,cjs.Ease.quadOut).wait(142));

	// arent_txt
	this.instance_4 = new lib.arent_txt();
	this.instance_4.setTransform(-130.9,55.95,1,1,0,0,0,-36.2,7.4);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(58).to({_off:false},0).to({y:40.95,alpha:1},17,cjs.Ease.quadOut).wait(146));

	// antacids_txt
	this.instance_5 = new lib.antacids_txt();
	this.instance_5.setTransform(-116.4,35.75,1,1,0,0,0,-51.1,7.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(54).to({_off:false},0).to({y:20.75,alpha:1},17,cjs.Ease.quadOut).wait(150));

	// those_txt
	this.instance_6 = new lib.those_txt();
	this.instance_6.setTransform(-132.95,14.95,1,1,0,0,0,-33.4,7.5);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(50).to({_off:false},0).to({y:-0.05,alpha:1},17,cjs.Ease.quadOut).wait(154));

	// real_txt
	this.instance_7 = new lib.real_txt();
	this.instance_7.setTransform(-138.95,-6.7,1,1,0,0,0,-27.5,7.4);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(31).to({_off:false},0).to({y:-21.7,alpha:1},17,cjs.Ease.quadOut).wait(173));

	// pain_Txt
	this.instance_8 = new lib.pain_Txt();
	this.instance_8.setTransform(-91.2,-27.15,1,1,0,0,0,-32.1,7.5);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(27).to({_off:false},0).to({y:-42.15,alpha:1},17,cjs.Ease.quadOut).wait(177));

	// the_txt
	this.instance_9 = new lib.the_txt();
	this.instance_9.setTransform(-148.25,-27.1,1,1,0,0,0,-18.5,7.3);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(23).to({_off:false},0).to({y:-42.1,alpha:1},17,cjs.Ease.quadOut).wait(181));

	// boy_txt
	this.instance_10 = new lib.boy_txt();
	this.instance_10.setTransform(-108.65,-47.4,1,1,0,0,0,-23.4,7.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(4).to({_off:false},0).to({y:-62.4,alpha:1},17,cjs.Ease.quadOut).wait(200));

	// oh_txt
	this.instance_11 = new lib.oh_txt();
	this.instance_11.setTransform(-152.55,-47.4,1,1,0,0,0,-14.2,7.5);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({y:-62.4,alpha:1},17,cjs.Ease.quadOut).wait(204));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-167.4,-69.9,108.30000000000001,196.4);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// TAKE_QUIZ
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3EDE8").s().p("AgfArIAAgQIArg1IgpAAIAAgQIA8AAIAAAPIgqA2IAqAAIAAAQg");
	this.shape.setTransform(28.65,-0.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F3EDE8").s().p("AgIArIAAhVIARAAIAABVg");
	this.shape_1.setTransform(23,-0.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F3EDE8").s().p("AgNApQgGgCgFgFQgEgEgDgGQgCgHAAgIIAAgzIARAAIAAA0QAAAIAEAFQAFAFAHAAQAHAAAFgFQAFgFAAgIIAAg0IARAAIAAAzQAAAIgDAHQgCAGgFAEQgEAFgHACQgGACgHAAQgHAAgGgCg");
	this.shape_2.setTransform(16.975,-0.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F3EDE8").s().p("AgRAoQgIgDgGgGQgGgGgDgIQgEgIAAgJQAAgIAEgIQADgIAGgGQAGgGAIgDQAIgEAJAAQAIAAAIAEQAIADAGAGQAGAGADAIQAEAIAAAIQAAAIgDAHQgDAHgEAFIAMAQIgTAAIgFgGIgLAFQgFACgFAAQgJAAgIgEgAgLgZQgFACgEAEQgDAEgCAFQgDAFAAAFQAAAGADAFQACAFADAEQAEAEAFACQAFACAGAAIAGgBIAGgCIgSgYIASAAIALANIACgGIABgIQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgGAAgFACg");
	this.shape_3.setTransform(7.775,-0.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F3EDE8").s().p("AgcArIAAhVIA5AAIAAAQIgoAAIAAATIAoAAIAAAPIgoAAIAAATIAoAAIAAAQg");
	this.shape_4.setTransform(-4.025,-0.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F3EDE8").s().p("AAQArIgTgqIgOAQIAAAaIgRAAIAAhVIARAAIAAAoIAfgoIAUAAIgbAgIAbA1g");
	this.shape_5.setTransform(-11.55,-0.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F3EDE8").s().p("AAXArIgFgQIgjAAIgGAQIgQAAIAghVIAPAAIAgBVgAAMAMIgMghIgLAhIAXAAg");
	this.shape_6.setTransform(-20.225,-0.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F3EDE8").s().p("AgHArIAAhFIgYAAIAAgQIA/AAIAAAQIgYAAIAABFg");
	this.shape_7.setTransform(-28.425,-0.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(50));

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AmWCBIAAkBIMtAAIAAEBg");
	mask.setTransform(0,0.025);

	// _Clip_Group_
	this.instance = new lib.ClipGroup();
	this.instance.setTransform(60.7,0,1,1,0,0,0,19.7,12.9);
	this.instance.alpha = 0;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:21.15,alpha:1},9,cjs.Ease.quadOut).wait(41));

	// Layer_2
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#01A882").s().p("AmWCBIAAkBIMtAAIAAEBg");
	this.shape_8.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(50));

	// _Path_
	this.instance_1 = new lib.Bitmap1();
	this.instance_1.setTransform(-46.75,-18.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(50));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.7,-18.9,96,40);


// stage content:
(lib.BSWH_DigestiveHealth_05_AllSaints_160x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgMfgu3IY/AAMAAABdvI4/AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(255));

	// BSWH_Logo
	this.instance = new lib.BSWH_Logo_Dallas();
	this.instance.setTransform(166.6,61.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11).to({_off:false},0).to({alpha:1},9).wait(235));

	// topBlue
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003DA6").s().p("A4SIhIAAxBMAwlAAAIAARBg");
	this.shape_1.setTransform(150.5,-56.45);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1).to({y:-44.15},0).wait(1).to({y:-33},0).wait(1).to({y:-23},0).wait(1).to({y:-14.2},0).wait(1).to({y:-6.55},0).wait(1).to({y:-0.1},0).wait(1).to({y:5.15},0).wait(1).to({y:9.25},0).wait(1).to({y:12.2},0).wait(1).to({y:13.95},0).wait(1).to({y:14.55},0).wait(244));

	// txt_tellingYou
	this.instance_1 = new lib.txt_tellingYou();
	this.instance_1.setTransform(139.3,449.05,0.994,0.994,0,0,0,0.1,0);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({alpha:1},10).wait(235));

	// txt_yourGut
	this.instance_2 = new lib.txt_yourGut();
	this.instance_2.setTransform(139.3,431.9,0.994,0.994,0,0,0,0.1,0);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(10).to({_off:false},0).to({alpha:1},10).wait(235));

	// ctaBtn
	this.instance_3 = new lib.ctaBtn("single",0);
	this.instance_3.setTransform(47.65,508.2,1.0084,1.0084,0,0,0,0.2,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({y:483.6,alpha:1,mode:"synched",loop:false},11,cjs.Ease.quadOut).wait(229).to({mode:"single",startPosition:31},0).wait(1));

	// txt_deepBreath
	this.instance_4 = new lib.txt_deepBreath("synched",0,false);
	this.instance_4.setTransform(173.8,168.65);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(20).to({_off:false},0).wait(105).to({startPosition:105},0).wait(130));

	// safeCare_Logo
	this.instance_5 = new lib.safeCare_Logo();
	this.instance_5.setTransform(47.55,352.6,0.1121,0.1121,-14.2444,0,0,1,3.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(125).to({_off:false},0).to({regX:1.1,scaleX:0.0794,scaleY:0.0794,rotation:-14.2392,alpha:1},7,cjs.Ease.quadOut).to({regX:1,regY:3.2,scaleX:0.0869,scaleY:0.0869,rotation:-14.2437},4,cjs.Ease.quadOut).wait(119));

	// head_mc
	this.instance_6 = new lib.head_mc();
	this.instance_6.setTransform(132.2,684.7,1,1,0,0,0,0,43.8);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(11).to({_off:false},0).to({y:600.2},14,cjs.Ease.quadOut).wait(230));

	// BlueBox
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003DA6").s().p("AolTdIqUAAMAAAgksIBHhFIBGhIIIHAAIbfAAMAAAAm5g");
	this.shape_2.setTransform(267.05,726.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003DA6").s().p("Ay5TdMAAAgksICNiNMAjmAAAMAAAAm5g");
	this.shape_3.setTransform(267.05,690.15);
	this.shape_3._off = true;

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#003DA6").s().p("Ay5TdMAAAgkrICNiOMAjmAAAMAAAAm5g");
	this.shape_4.setTransform(267.05,545.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2,p:{y:726.25}}]}).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4,p:{y:545.75}}]},1).to({state:[{t:this.shape_4,p:{y:533.7}}]},1).to({state:[{t:this.shape_4,p:{y:525.15}}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_2,p:{y:518.25}}]},1).wait(244));
	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1).to({_off:false},0).wait(1).to({y:657.5},0).wait(1).to({y:628.25},0).wait(1).to({y:602.5},0).wait(1).to({y:580.15},0).wait(1).to({y:561.25},0).to({_off:true},1).wait(3).to({_off:false,y:519.95},0).to({_off:true},1).wait(244));

	// GreenBox
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#00A881").s().p("Ay5TJMAAAgmRMAjmAAAIBGBIIBHBFMAAAAkEg");
	this.shape_5.setTransform(25.05,724.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00A881").s().p("Ay5TJMAAAgmRMAjmAAAICNCNMAAAAkEg");
	this.shape_6.setTransform(25.05,688.15);
	this.shape_6._off = true;

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#00A881").s().p("Ay5TJMAAAgmRMAjmAAAICNCOMAAAAkDg");
	this.shape_7.setTransform(25.05,543.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5,p:{y:724.25}}]}).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7,p:{y:543.75}}]},1).to({state:[{t:this.shape_7,p:{y:531.7}}]},1).to({state:[{t:this.shape_7,p:{y:523.15}}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5,p:{y:516.25}}]},1).wait(244));
	this.timeline.addTween(cjs.Tween.get(this.shape_6).wait(1).to({_off:false},0).wait(1).to({y:655.5},0).wait(1).to({y:626.25},0).wait(1).to({y:600.5},0).wait(1).to({y:578.15},0).wait(1).to({y:559.25},0).to({_off:true},1).wait(3).to({_off:false,y:517.95},0).to({_off:true},1).wait(244));

	// Background_color
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F4EDE7").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_8.setTransform(80.0011,300,0.5333,1);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(255));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-16,189.1,404.1,661.6999999999999);
// library properties:
lib.properties = {
	id: 'BD94237A628B41D499830A95CE062363',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Bitmap1.png", id:"Bitmap1"},
		{src:"head_img.png", id:"head_img"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['BD94237A628B41D499830A95CE062363'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;