(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,40);


(lib.head_img = function() {
	this.initialize(img.head_img);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,87);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.will_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ACIBFIAAiJIAiAAIAABqIA8AAIAAAfgAAbBFIAAiJIAhAAIAABqIA8AAIAAAfgAgZBFIAAiJIAhAAIAACJgAhtBFIgZhWIgYBWIggAAIgniJIAiAAIAWBUIAXhUIAgAAIAYBUIAWhUIAiAAIgoCJg");
	this.shape.setTransform(-23,6.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.will_txt, new cjs.Rectangle(-46,0,46,13.9), null);


(lib.we_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AA2BFIAAiJIBgAAIAAAeIg/AAIAAAXIA/AAIAAAeIg/AAIAAAXIA/AAIAAAfgAgdBFIgYhWIgYBWIghAAIgniJIAiAAIAWBUIAYhUIAfAAIAYBUIAVhUIAiAAIgnCJg");
	this.shape.setTransform(-14.975,6.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.we_txt, new cjs.Rectangle(-29.9,0,29.9,13.9), null);


(lib.txt_yourGut = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape.setTransform(-8.825,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_1.setTransform(-17.325,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgaA+QgKgFgIgJIATgPQAFAGAGADQAFAEAJgBQAFAAAEgBQAFgCADgEQAEgDACgEQACgFAAgFIAAgHQgFAHgIAEQgHADgIAAQgJABgIgEQgIgDgGgGQgGgHgEgJQgDgHAAgLQAAgLADgJQAEgIAGgHQAGgGAIgEQAIgCAJAAQAIgBAIAEQAHAEAFAGIAAgMIAXAAIAABUQAAAKgDAIQgEAJgGAGQgHAGgJAEQgJAEgKAAQgPAAgLgFgAgJgqQgEACgEADQgDAEgCAFQgCAEAAAGQAAAFACAFQACAEADAEQAEADAEACQAFACAEAAQAGAAAEgCQAFgCAEgDIAFgIQACgFAAgFQAAgGgCgEIgFgJQgEgDgFgCQgEgCgGAAQgEAAgFACg");
	this.shape_2.setTransform(-27.675,3.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfAvIAAhbIAXAAIAAAOQADgIAGgEQAHgEAIAAIAJABIAHADIgIAXIgGgCIgHgBQgIAAgFAFQgFAFgBALIAAAwg");
	this.shape_3.setTransform(-39.45,1.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_4.setTransform(-48.175,1.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTAsQgJgEgGgGQgHgHgDgJQgDgIAAgKQAAgJADgJQADgJAHgGQAGgGAJgEQAJgEAKAAQAKAAAJAEQAJAEAGAGQAHAGADAJQAFAJAAAJQAAAKgFAIQgDAJgHAHQgGAGgJAEQgJAEgKAAQgKAAgJgEgAgJgXQgFACgDAEQgDADgCAFQgCAEgBAFQABAFACAFQACAEADAEQADADAFACQAEACAFAAQAFAAAEgCQAGgCADgDIAFgIQACgFAAgFQAAgFgCgEQgCgFgDgDQgDgEgGgCQgEgCgFAAQgFAAgEACg");
	this.shape_5.setTransform(-58.25,1.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnA+QgHgDgFgDIANgTIAGAEQADABAEAAQAGAAAEgDQAEgDAEgIIABgEIglhXIAZAAIAXA7IAXg7IAYAAIgnBgQgEAJgEAGQgDAGgEADQgEAEgGACQgGABgHAAQgHAAgHgCg");
	this.shape_6.setTransform(-68.625,3.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgYAqQgKgGgGgLIAWgIQAGAMAPgBQAGAAAFgCQADgEAAgEQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIgEgEIgHgBIgHgCIgMgDQgGgCgFgDQgEgBgDgGQgDgEAAgHQAAgGACgFQAEgGAEgDQAFgFAHgCQAHgCAHAAQAPAAAJAFQAKAFAGAKIgWAIQgDgEgDgDQgFgDgHABQgGgBgDADQgDACAAAFQAAADAFACIAPAFIALACQAHACAEAEQAFABADAGQADAEAAAHQAAAGgCAFQgDAGgEAEQgGAEgHADQgHADgLAAQgPAAgKgGg");
	this.shape_7.setTransform(-80.75,1.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLASQAHgFAEgFQADgFAAgFQgCAEgFAAQgFAAgDgDQgDgEAAgFQAAgHAEgEQAEgEAHAAQAHAAAFAFQAEAGAAAIQAAAJgGAIQgFAIgJAHg");
	this.shape_8.setTransform(-86.825,-3.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape_9.setTransform(-92.225,-0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjAoQgIgIAAgMQAAgOALgHQALgJATAAIAXAAIAAgBQAAgHgEgFQgGgEgKAAQgGAAgFADQgGADgDAGIgWgLQAHgJAKgGQALgGAOAAQAVAAALAKQALAKAAARIAAA4IgXAAIAAgOQgFAHgIAEQgIAFgLAAQgPAAgJgIgAgOAKQgFADABAFQgBAKAOAAIAIgBIAHgDIAHgGQADgDABgDIAAgFIgVAAQgJAAgFADg");
	this.shape_10.setTransform(-100.85,1.425);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AASBDIAAg0QABgKgFgFQgFgFgJAAQgHAAgGAFQgFAGgBALIAAAyIgXAAIAAiFIAXAAIAAA1QAFgFAHgEQAGgEAIABQAIgBAHADQAHADAEAFQAFAFADAGQACAGAAAJIAAA4g");
	this.shape_11.setTransform(-110.45,-0.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAaA+IgahXIgZBXIgYAAIgjh7IAZAAIAXBVIAahVIAWAAIAZBWIAYhWIAYAAIgkB7g");
	this.shape_12.setTransform(-123.975,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_yourGut, new cjs.Rectangle(-134.9,-13.1,269.9,26.299999999999997), null);


(lib.txt_tellingYou = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AgMA8QgFgEAAgHQAAgGAFgFQAEgEAGAAQAGAAAEAEQAEAFAAAGQAAAHgEAEQgEAEgGAAQgGAAgEgEgAgMAYIAAgCQAAgJACgGQADgHADgDIAGgHIAHgFIAFgFQACgDAAgFQAAgGgEgEQgFgFgHAAQgHAAgEAEQgFAEgCAGIgVgJQAFgLAKgHQAKgHAOAAQAJAAAHACQAIADAFAFQAFAEADAHQADAGAAAIQAAAIgDAFQgCAFgEADIgHAGIgIAFQgEADgCAFQgCAEAAAGIAAACg");
	this.shape.setTransform(-46.625,-0.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFB71B").s().p("AggAkQgKgKAAgSIAAg2IAYAAIAAAzQAAAKAFAFQAEAGAJAAQAIAAAGgGQAFgGAAgKIAAgyIAYAAIAABbIgYAAIAAgLQgEAGgHADQgHAEgHAAQgRAAgJgLg");
	this.shape_1.setTransform(-55.975,1.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFB71B").s().p("AgTAsQgIgEgHgGQgHgHgDgJQgDgIgBgKQABgJADgJQADgJAHgGQAHgGAIgEQAKgEAJAAQAKAAAJAEQAJAEAGAGQAHAGAEAJQADAJAAAJQAAAKgDAIQgEAJgHAHQgGAGgJAEQgJAEgKAAQgJAAgKgEgAgJgXQgFACgDAEQgDADgDAFQgBAEAAAFQAAAFABAFQADAEADAEQADADAFACQAEACAFAAQAFAAAFgCQAFgCADgDIAFgIQACgFAAgFQAAgFgCgEQgCgFgDgDQgDgEgFgCQgFgCgFAAQgFAAgEACg");
	this.shape_2.setTransform(-66.05,1.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFB71B").s().p("AgnA+QgHgDgFgDIANgTIAGAEQADABAEAAQAGAAAEgDQAEgDAEgIIABgEIglhXIAZAAIAXA7IAXg7IAYAAIgnBgQgEAJgEAGQgDAGgEADQgEAEgGACQgGABgHAAQgHAAgHgCg");
	this.shape_3.setTransform(-76.425,3.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFB71B").s().p("AgaA+QgKgFgIgJIATgPQAFAGAGADQAFAEAJgBQAFAAAEgBQAFgCADgEQAEgDACgEQACgFAAgFIAAgHQgFAHgIAEQgHADgIAAQgJABgIgEQgIgDgGgGQgGgHgEgJQgDgHAAgLQAAgLADgJQAEgIAGgHQAGgGAIgEQAIgCAJAAQAIgBAIAEQAHAEAFAGIAAgMIAXAAIAABUQAAAKgDAIQgEAJgGAGQgHAGgJAEQgJAEgKAAQgPAAgLgFgAgJgqQgEACgEADQgDAEgCAFQgCAEAAAGQAAAFACAFQACAEADAEQAEADAEACQAFACAEAAQAGAAAEgCQAFgCAEgDIAFgIQACgFAAgFQAAgGgCgEIgFgJQgEgDgFgCQgEgCgGAAQgEAAgFACg");
	this.shape_4.setTransform(-89.625,3.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFB71B").s().p("AATAvIAAgzQAAgKgFgGQgFgFgIAAQgIAAgGAGQgFAFAAALIAAAyIgYAAIAAhbIAYAAIAAALQAEgGAHgDQAHgEAIAAQAQAAAJAKQAKAKAAASIAAA3g");
	this.shape_5.setTransform(-99.7,1.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFB71B").s().p("AgLBDIAAhcIAXAAIAABcgAgJgnQgFgFAAgGQAAgHAFgEQAEgEAFAAQAHAAAEAEQAEAEAAAHQAAAGgEAFQgEAEgHAAQgFAAgEgEg");
	this.shape_6.setTransform(-106.45,-0.65);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFB71B").s().p("AgLBDIAAiFIAXAAIAACFg");
	this.shape_7.setTransform(-110.075,-0.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFB71B").s().p("AgLBDIAAiFIAXAAIAACFg");
	this.shape_8.setTransform(-113.675,-0.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFB71B").s().p("AgSAsQgJgEgHgGQgGgHgEgIQgDgJAAgKQAAgJAEgJQADgJAHgGQAGgGAJgEQAJgEAJAAQAKAAAJAEQAJADAGAGQAGAHAEAIQAEAJAAAKIAAAIIhIAAQACAJAHAFQAHAFAJAAQAIAAAGgDQAFgDAEgGIATALQgHAKgKAGQgKAGgPAAQgKAAgJgEgAAYgJQgCgJgGgFQgHgEgJAAQgIAAgGAFQgHAFgDAIIAwAAIAAAAg");
	this.shape_9.setTransform(-120.575,1.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFB71B").s().p("AgJA4QgIgIAAgSIAAgmIgRAAIAAgVIARAAIAAgTIAWgPIAAAiIAZAAIAAAVIgZAAIAAAkQAAAIADADQADACAEABQAFAAAEgDIALASIgKAFQgGABgGAAQgOABgIgIg");
	this.shape_10.setTransform(-129.025,-0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_tellingYou, new cjs.Rectangle(-134.9,-13.1,269.9,26.299999999999997), null);


(lib.to_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AAhBCQgNgGgKgKQgJgJgFgNQgGgNAAgPQAAgOAGgNQAFgNAJgJQAKgKANgGQANgFAOAAQAPAAANAFQANAGAKAKQAJAJAGANQAFANAAAOQAAAPgFANQgGANgJAJQgKAKgNAGQgNAFgPAAQgOAAgNgFgAAtgjQgHADgEAGQgFAFgDAHQgDAHAAAHQAAAIADAHQACAHAFAFQAFAFAHADQAHADAIAAQAJAAAGgDQAHgDAFgFQAFgFADgHQADgHAAgIQAAgHgDgHQgDgHgFgFQgFgGgHgDQgHgDgIAAQgIAAgHADgAhdBFIAAhrIglAAIAAgeIBrAAIAAAeIglAAIAABrg");
	this.shape.setTransform(-13.125,7.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.to_txt, new cjs.Rectangle(-26.2,0,26.2,14.3), null);


(lib.the_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ABQBFIAAiJIBfAAIAAAeIg+AAIAAAXIA+AAIAAAeIg+AAIAAAXIA+AAIAAAfgAAbBFIAAg1IgsAAIAAA1IghAAIAAiJIAhAAIAAA0IAsAAIAAg0IAiAAIAACJgAiIBFIAAhrIgmAAIAAgeIBrAAIAAAeIglAAIAABrg");
	this.shape.setTransform(-17.5,6.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.the_txt, new cjs.Rectangle(-35,0,35,13.9), null);


(lib.talk_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ADQBFIgehBIgSAXIAAAqIghAAIAAiJIAhAAIAAA4IAsg4IAnAAIgpAyIApBXgAARBFIAAiJIAhAAIAABqIA9AAIAAAfgAgaBFIgHgUIg1AAIgHAUIgiAAIA0iJIAfAAIAzCJgAgrAUIgRguIgQAuIAhAAgAjMBFIAAhrIgmAAIAAgeIBrAAIAAAeIglAAIAABrg");
	this.shape.setTransform(-24.275,6.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.talk_txt, new cjs.Rectangle(-48.5,0,48.5,13.9), null);


(lib.someone_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AHNBCQgFgEAAgJQAAgIAFgGQAFgFAJAAQAJAAAEAFQAFAGABAIQgBAJgFAEQgEAGgJAAQgJAAgFgGgABGBCQgNgGgKgJQgJgKgGgNQgGgNABgPQgBgOAGgMQAGgNAJgKQAKgKANgFQANgGAPAAQAPAAANAGQANAFAJAKQAJAKAGANQAGAMgBAOQABAPgGANQgGANgJAKQgJAJgNAGQgNAFgPABQgPgBgNgFgABTgjQgIADgEAGQgFAFgDAHQgDAHAAAHQAAAIADAHQACAHAGAFQAEAFAIAEQAGACAJAAQAIAAAGgCQAHgEAGgFQAEgFADgHQAEgHAAgIQAAgHgEgHQgDgHgEgFQgGgGgHgDQgGgCgIAAQgJAAgGACgAliBCQgNgGgJgJQgJgKgHgNQgFgNAAgPQAAgOAFgMQAHgNAJgKQAJgKANgFQANgGAPAAQAPAAANAGQANAFAJAKQAKAKAGANQAFAMAAAOQAAAPgFANQgGANgKAKQgJAJgNAGQgNAFgPABQgPgBgNgFgAlVgjQgHADgFAGQgEAFgDAHQgEAHAAAHQAAAIAEAHQACAHAFAFQAFAFAHAEQAHACAIAAQAJAAAGgCQAHgEAFgFQAFgFADgHQADgHAAgIQAAgHgDgHQgDgHgFgFQgFgGgHgDQgHgCgIAAQgIAAgHACgAnjBGQgJgDgIgDQgHgEgGgGQgGgEgFgGIAdgXQAGAJAIAGQAJAEALAAQAJAAAEgDQAFgEgBgGQAAgDgBgCQgCgCgDgCIgJgDIgdgIQgIgDgFgEQgHgDgEgHQgEgHAAgLQAAgJAEgIQAEgHAHgHQAGgFAKgEQAJgCALgBQAKABAHABQAIACAGADQAHADAGAFIALALIgbAUQgFgIgGgEQgIgEgKgBQgIAAgFAFQgEADAAAFQAAADACACQADADAEABIAkAKQAHACAHAEQAGAEAFAIQAEAHAAALQAAAKgEAIQgEAJgHAFQgHAHgJADQgKADgMABQgLAAgKgCgAFBBGIAAiKIBgAAIAAAfIg/AAIAAAWIA/AAIAAAeIg/AAIAAAXIA/AAIAAAggAEPBGIg3hWIAABWIggAAIAAiKIAjAAIA0BSIAAhSIAfAAIAACKgAhTBGIAAiKIBfAAIAAAfIg+AAIAAAWIA+AAIAAAeIg+AAIAAAXIA+AAIAAAggAiGBGIAAhXIgkAvIgkgvIAABXIghAAIAAiKIAgAAIAlA0IAmg0IAeAAIAACKgAHNAZIAAAAQABgMACgGQACgHAEgEQACgEAFgDIAMgLQADgDAAgEQAAgFgEgEQgEgEgGAAQgHAAgFAEQgFAEgBAGIgcgOQAFgNAMgHQALgIATAAQAKAAAIADQAJADAGAFQAGAGADAIQADAHABAJQgBAIgCAGQgDAFgEAEIgJAGIgIAGQgEADgDAEQgCAEgBAIIAAAAg");
	this.shape.setTransform(-52.45,7.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.someone_txt, new cjs.Rectangle(-104.9,0,104.9,14.3), null);


(lib.should_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AA7BDQgKgDgHgIQgHgGgEgLQgEgLAAgNIAAhTIAhAAIAABTQAAAMAGAGQAGAGALAAQAKAAAGgGQAGgGAAgMIAAhTIAiAAIAABTQAAANgEALQgEALgHAGQgIAIgKADQgLAFgMAAQgNAAgLgFgAhWBCQgNgGgKgJQgJgKgGgNQgGgNAAgPQAAgOAGgMQAGgNAJgKQAKgKANgFQANgGAOAAQAPAAANAGQANAFAKAKQAIAKAGANQAFAMAAAOQAAAPgFANQgGANgIAKQgKAJgNAGQgNAFgPABQgOgBgNgFgAhKgjQgHADgEAGQgFAFgDAHQgDAHAAAHQAAAIADAHQACAHAFAFQAFAFAHAEQAHACAIAAQAJAAAGgCQAHgEAFgFQAFgFADgHQADgHAAgIQAAgHgDgHQgDgHgFgFQgFgGgHgDQgHgCgIAAQgIAAgHACgAlaBGQgJgDgIgDQgHgEgGgGQgGgEgFgGIAcgXQAHAJAIAGQAIAEAMAAQAJAAAEgDQAEgEAAgGQAAgDgBgCQgCgCgEgCIgJgDIgcgIQgIgDgGgEQgGgDgEgHQgEgHAAgLQAAgJAEgIQAEgHAGgHQAHgFAJgEQAKgCALgBQAJABAIABQAIACAGADQAHADAGAFIALALIgbAUQgFgIgHgEQgHgEgKgBQgJAAgEAFQgEADAAAFQAAADACACQACADAEABIAkAKQAIACAHAEQAGAEAFAIQAEAHAAALQAAAKgEAIQgEAJgHAFQgHAHgKADQgKADgLABQgMAAgJgCgAELBGIAAiKIAxAAQAQAAANAFQANAGAKAJQAKAJAFANQAFAMAAAOQAAAPgFAMQgGAOgJAIQgKAKgNAFQgNAGgQAAgAEsAmIAPAAQAJAAAHgCQAIgEAFgFQAFgFADgHQACgHAAgIQAAgHgCgHQgDgHgFgFQgFgFgIgEQgHgCgKAAIgOAAgACdBGIAAiKIAhAAIAABqIA9AAIAAAggAiyBGIAAg2IguAAIAAA2IghAAIAAiKIAhAAIAAA0IAuAAIAAg0IAhAAIAACKg");
	this.shape.setTransform(-38.775,7.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.should_txt, new cjs.Rectangle(-77.5,0,77.5,14.3), null);


(lib.pass_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ADrBCQgFgEAAgJQAAgIAFgGQAFgFAIAAQAJAAAFAFQAFAGAAAIQAAAJgFAEQgFAGgJAAQgIAAgFgGgACPBGQgJgDgIgDQgHgEgGgGQgGgEgFgGIAcgXQAHAJAIAGQAIAEAMAAQAJAAAEgDQAEgEAAgGQAAgDgBgCQgCgCgEgCIgJgDIgcgIQgIgDgGgEQgGgDgEgHQgEgHAAgLQAAgJAEgIQAEgHAGgHQAHgFAJgEQAKgCALgBQAJABAIABQAIACAGADQAHADAGAFIALALIgbAUQgFgIgHgEQgHgEgKgBQgJAAgEAFQgEADAAAFQAAADACACQACADAEABIAkAKQAIACAHAEQAGAEAFAIQAEAHAAALQAAAKgEAIQgEAJgHAFQgHAHgKADQgKADgLABQgMAAgJgCgAAYBGQgJgDgIgDQgHgEgFgGQgGgEgFgGIAbgXQAHAJAIAGQAIAEAMAAQAJAAAEgDQAEgEAAgGQAAgDgBgCQgCgCgEgCIgJgDIgcgIQgIgDgGgEQgFgDgEgHQgEgHAAgLQAAgJAEgIQAEgHAFgHQAHgFAJgEQAKgCALgBQAJABAIABQAIACAGADQAHADAGAFIALALIgbAUQgFgIgHgEQgHgEgKgBQgJAAgEAFQgEADAAAFQAAADACACQACADAEABIAkAKQAIACAHAEQAGAEAFAIQAEAHAAALQAAAKgEAIQgEAJgHAFQgHAHgKADQgKADgLABQgMAAgJgCgAgxBGIgHgVIg1AAIgHAVIgiAAIA0iKIAfAAIA0CKgAhCAUIgRguIgQAuIAhAAgAkKBGIAAiKIA4AAQAMAAAKAEQAJAEAHAHQAHAHAEAKQAEAJAAALQAAAKgEAIQgEAKgHAHQgGAHgKAEQgKAFgNAAIgWAAIAAAjgAjpAEIAVAAQAJAAAGgFQAGgGAAgJQAAgKgGgGQgGgGgJAAIgVAAg");
	this.shape.setTransform(-26.675,7.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.pass_txt, new cjs.Rectangle(-53.3,0,53.3,14.3), null);


(lib.deep_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("ACABFIAAiJIA3AAQAMAAAKAEQAKAEAGAHQAHAHAFAJQAEAKAAAKQAAALgEAIQgFAKgHAHQgGAHgKAEQgKAEgNAAIgVAAIAAAjgAChAEIAUAAQAJAAAHgFQAFgGAAgKQAAgJgFgGQgHgGgJAAIgUAAgAAOBFIAAiJIBgAAIAAAeIg/AAIAAAXIA/AAIAAAeIg/AAIAAAXIA/AAIAAAfgAhiBFIAAiJIBfAAIAAAeIg/AAIAAAXIA/AAIAAAeIg/AAIAAAXIA/AAIAAAfgAjsBFIAAiJIAyAAQAQAAANAFQANAFAKAKQAJAJAFAMQAGANAAAOQAAAPgGAMQgFANgJAJQgKAKgOAFQgMAFgQAAgAjLAmIAQAAQAIAAAIgDQAIgDAEgFQAFgFAEgHQACgHAAgIQAAgHgCgHQgDgHgFgGQgFgFgIgDQgHgDgKAAIgPAAg");
	this.shape.setTransform(-23.65,6.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.deep_txt, new cjs.Rectangle(-47.3,0,47.3,13.9), null);


(lib.cramping_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AGcBBQgNgFgKgKQgJgKgGgNQgEgNgBgOQAAgOAGgNQAGgNAJgKQAJgJANgGQAOgFAPAAQAUAAAPAHQAOAIAKANIgbATQgFgIgIgEQgIgEgLAAQgIAAgGADQgIADgFAFQgFAGgDAHQgDAHAAAIQAAAJACAHQAEAHAEAGQAGAFAHADQAHADAJAAQAMAAAIgGQAIgGAEgKIgnAAIAAgeIBLAAIAAAPQgBAOgEAMQgFANgJAJQgJAJgMAGQgMAFgPAAQgSAAgNgGgAnTBCQgNgGgJgKQgJgJgFgNQgGgNABgPQgBgOAGgNQAFgNAKgKQAJgKAOgFQANgFAPAAQAKAAAJACQAJADAIAEQAIAFAGAGQAHAGAFAIIgeASQgFgJgHgFQgJgGgLAAQgIAAgHADQgHADgFAFQgFAGgCAHQgDAHAAAHQAAAIACAHQADAHAFAFQAFAFAGADQAIADAIAAQAMAAAIgGQAJgGAEgKIAfAQQgEAJgHAHQgGAHgJAFQgIAFgKADQgJADgLAAQgQAAgOgFgAFCBFIg3hWIAABWIgfAAIAAiJIAiAAIA0BSIAAhSIAgAAIAACJgAC4BFIAAiJIAhAAIAACJgAA6BFIAAiJIA3AAQANAAAJAEQAKAEAHAHQAHAHAEAJQAEAKAAAKQAAALgEAIQgEAKgHAHQgHAHgKAEQgJAEgNAAIgWAAIAAAjgABbAEIAVAAQAJAAAGgFQAGgGAAgKQAAgJgGgGQgGgGgJAAIgVAAgAAGBFIAAhXIgjAwIgkgwIAABXIghAAIAAiJIAgAAIAlAzIAmgzIAeAAIAACJgAiNBFIgIgUIg1AAIgHAUIgiAAIA0iJIAgAAIAzCJgAifAUIgQguIgRAuIAhAAgAkaBFIgTgpIgaAAIAAApIgiAAIAAiJIA8AAQAMAAAKADQAKAEAGAHQAHAGADAJQAEAIAAAKQAAAOgGAJQgGALgLAGIAaAygAlHgBIAYAAQAKAAAFgGQAFgFAAgIQAAgJgFgEQgFgFgKAAIgYAAg");
	this.shape.setTransform(-50.95,7.125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.cramping_txt, new cjs.Rectangle(-101.9,0,101.9,14.3), null);


(lib.breath_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFB71B").s().p("AFpBBQgEgFAAgIQAAgJAEgFQAGgFAIAAQAJAAAEAFQAGAFAAAJQAAAIgGAFQgEAFgJAAQgIAAgGgFgAEzBEIAAg1IguAAIAAA1IggAAIAAiJIAgAAIAAA0IAuAAIAAg0IAhAAIAACJgACOBEIAAhrIglAAIAAgeIBrAAIAAAeIglAAIAABrgAA/BEIgIgUIg0AAIgGAUIgiAAIAziJIAfAAIAzCJgAAtATIgQguIgQAuIAgAAgAiOBEIAAiJIBgAAIAAAeIg/AAIAAAXIA/AAIAAAeIg/AAIAAAXIA/AAIAAAfgAi+BEIgTgpIgbAAIAAApIghAAIAAiJIA8AAQAMAAAKADQAKAEAGAHQAHAGADAJQAEAIAAAKQAAAOgGAJQgGALgLAGIAaAygAjsgCIAZAAQAKAAAFgGQAFgFAAgIQAAgJgFgEQgFgFgKAAIgZAAgAmIBEIAAiJIA2AAQAZAAANAKQAMAKAAATQABAKgEAGQgEAHgGAEQAHAEAFAHQAFAIAAAKQAAAWgPAKQgOAKgZAAgAlpAnIAYAAQAJAAAFgDQAEgEABgHQAAgGgFgDQgEgEgKAAIgYAAgAlpgQIAZAAQAIAAAEgDQAEgEAAgGQAAgFgEgDQgEgEgIAAIgZAAg");
	this.shape.setTransform(-39.35,7.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.breath_txt, new cjs.Rectangle(-78.7,0,78.7,14.1), null);


(lib.safeCare_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#A8A9A7").s().p("EgROA1vQoEitm8lHQm1lClFm5QlIm9i2oMIAAAAIgGgSIgBAAQg5iogoirIC2AAQCJIqEzHfQEuHYGxFeQG0FhIJC9QIcDEJBAAQJBAAIbjEQIJi9G1lhQGwleEunYQEznfCKoqIC2AAQglCdhAC9IgBAAIgLAhQi3IHlJG6QlEG1m1E/Qm5FDoCCsQoUCyoyAAQo2AAoVi0gEgRCAxlQn7i3mqlWQmmlTknnJQktnRiJoZIArAAQCIIQEpHKQElHBGgFNQGkFRH0C0QIFC6IpAAQIoAAIGi6QH0i0GklRQGglNEknBQEpnJCIoRIAsAAQiJIZktHRQkoHJmlFTQmqFWn8C3QoNC+oxAAQoxAAoOi+gEgBPAsbIhnkmIA7ABIBIDbIBRjYIA5ACIhwEigEACGAn3IDAgSIAEA1IiIANIAGBBICIgNIAEA1IiIANIAGBCICIgMIAFA1Ii/ASgEgHFAr4IAlkiIC+AaIgGA1IiIgTIgIBBICHATIgGA0IiIgSIgIBCICHASIgHA2gEAF+AneIA5gMIChCqIgmjDIA0gLIA4EeIg1AMIimiwIAnDKIg0ALgEgJJArdIgXhkIg+gPIgVBZIg2gNIBCkcIBxAbQAuAMAWAiQAVAhgKAqQgGAcgSATQgSATgaAHIAfB1gEgKTAo3IA3AOQAaAGAQgLQAQgKAFgVQAFgVgKgPQgLgQgZgGIg3gOgEALzAm5IhMAZIgPgyIDKhCIAPAxIhKAZIBHDlIg0ARgEgP0ApaIBdkUIBqAmQAtAQATAoQASAmgOArQgOAqgmASQgoAUgsgQIg1gTIgaBLgEgOWAnwIAzASQAXAIAUgJQATgJAHgWQAIgXgKgTQgJgUgXgIIgzgSgEAPxAoRQgRgHgHgRQgHgSAHgRQAHgRARgHQARgHARAHQARAHAHARQAHARgHASQgIARgQAHQgIAEgJAAQgJAAgIgEgEARNAj2IBjg3QApgXAqAMQAnAMAWAoQAUAngLApQgNArgpAXIgyAcIAlBGIgwAbgEATFAjuIgvAbIAzBfIAvgaQAVgMAHgVQAFgVgLgVQgLgVgUgGQgHgCgHAAQgOAAgOAIgEgR5AngQgQgIgGgRQgHgSAIgRQAIgRARgGQARgHAQAIQARAIAHASQAFARgHARQgIARgRAHQgIADgHAAQgKAAgJgFgEgXRAlhICRj7IClBkIgaAtIh2hHIggA5IB2BHIgbAuIh2hHIghA5IB2BHIgbAugEAUqAh4IBghDQAogcAoAHQAlAHAYAjQAQAXACAbQABAbgNAYIBqA3IgzAkIhYgxIg1AlIAyBMIgtAggEAWkAhjIgvAgIA1BQIAvghQAVgPAEgUQADgTgMgRQgMgSgSgDIgFAAQgQAAgSANgEgY/AkUIARhmIg0gnIg1BKIgtghICqjrIBcBGQAnAeAHAoQAGAngZAiQgQAXgXALQgZAKgagEIgRB4gEgZEAheIAtAiQAVAQAUgDQATgDALgRQANgSgEgSQgDgTgVgQIgtgigEAazAiQQg9gFgngvQgngvADg9QAFg+AugpQAtgpA9AFQA8AEAoAvQAoAwgFA9QgDA/gvAoQgpAlg1AAIgMgBgAaAezQgcAZgCAnQgCAmAZAeQAZAeAlADQAmAEAdgaQAdgaACgmQACgngZgdQgZgeglgDIgJgBQghAAgaAXgEgcXAhoIAVg0IhYhTIgwAbIgqgoIEQiNIAoAmIhxEigA8qfIIA8A5IAvhygAxbbFQntlNjyomIAuAAQDvIUHgFCQHtFKJNAAQJNAAHslKQHhlCDvoUIAtAAQjxImntFNQn5FWpfAAQpfAAn5lWgAcxcJIg3A8IglgkICRifIAlAkIg2A7ICrCkIglApgAv+ZnQnFkojsntIG3AAIAOAWIAbgWIAbAAIgyAdQAqA+AqA1ICXiQIA8AAIjNCXQAxA7AvAvIDckBIBNAAIkjEHQAwAyA4AuID8lnIBXAAIlMFtQA5AvA4AmID/nCIBbAAIlTHHQA9AoA7AhIDsoQIBdAAIlAIUQA8AhBCAcIDGpRIMFAAIDDJIQBBgcA7giIk6oKIBdAAIDnIFQA7giA6gnIlLm8IBbAAID5G1QA5gpA0grIlBlhIBWAAIDzFaQA5gxAsguIkWj7IBNAAIDQDzQAugvAug5Ii8iLIA7AAICICCQAngyAqg/IgcgRIAZAAIAJAIIAFgIIG3AAQjsHtnGEoQnREwopAAQopAAnSkwgAhSc+IAwABIAGjIIgvgBgACwZuIhFAIIAYDHIBFgIQArgFAZggQAZgggEgrQgGgrgegYQgagVgjAAIgQABgAlccdIAsAIIBqi3IgvgJIhGB8IgViNIgvgKgAqIYKQglARgPAoQgQAoARAnQAQAnAoAPQAnAQAlgSQAmgRAPgoQAPgogRgnQgQgngngPQgTgHgSAAQgUAAgUAJgAGuaTIAKAmIBfgcIgKgmgALqaaIArgTIhSi2IgoATQASAqgqAUIgBAAIATArIAEgDQAcgMABgagAuYVuQgnAKgYAlQgWAlAIAnQAIApAmAYQAaARAcAAQAbgBAYgOIgYgsQgdAUgcgSQgTgMgEgWQgEgWAMgTQAMgUAVgGQAVgFAUAMQAZARgCAhIAxAAQAAgbgMgXQgNgYgXgPQgbgRgcAAQgKAAgLACgAOTY2QAZgBAbgSQBLgyg5haQgbgqgbgJQgegKgdATQgaARgGAcQgGAcAQAZQAQAZAZAGQAYAGAWgPQAXgQgCgXQALAWgEAPQgDAOgTAMQgPALgRgBgAANYWQBBAABJgIIhjp1gAiHYQQBCAGBCAAIAGAAIglp8gAkaX8QBLAOA/AFIAWp+gAChYNQBKgJA/gNIifpngAmrXYQBBAUBHAOIBTp6gAE0X1QBJgQA9gTIjZpTgAo3WmQBGAdA9ASICQpvgAHDXPQBAgVBBgcIkPo6gA9yd3QgsgBgggkIgmgrIg5A2IgmgqIDSjFIBMBUQAgAkgBAsQgDArggAeQgeAcgmAAIgFAAgA+/cEIAkAoQARASAVACQAVABASgQQARgQAAgWQABgWgQgSIgkgpgAeFZdIB0icIAqAgIhTBvIAyAoIBUhvIApAhIhTBvIAzAoIBUhvIApAhIh1CcgACfadIAUgDQAagDASAOQARAOACAYQACAYgNARQgNARgZADIgVADgEgjlAZcIDlivIBzCdIgqAgIhShwIgzAnIBSBwIgpAgIhThwIgzAoIBSBwIgrAggApzacQgVgIgJgVQgHgVAHgVQAIgWAVgKQAUgJAUAIQAWAIAIAVQAJAVgJAWQgIAVgUAKQgKAFgLAAQgKAAgKgEgEgkoAXyIA1hYIgig4IhMAvIgegwID0iYIA8BmQAaAqgJAoQgJAmgkAXQgXAOgaABQgaAAgXgOIg8BpgEgjqAVHIAdAxQAOAXAUAFQASAEARgLQASgLAEgSQAEgTgOgXIgdgxgEAiMAXtQg2ghgOg7QgPg7Ahg3QAVgjAigTQAigTAmAAIAAA7Qg2gDgbAuQgUAiAJAlQAKAkAiAVQAgAVAkgIQAlgJAUghQAPgZgCgbQgCgZgPgWIAygeQAWAkAAAoQABArgWAmQghA4g7AOQgRAEgQAAQgnAAglgYgAOIXBQgKgCgHgJQgFgKACgKQACgLAJgGQAJgGAKADQAKACAGAJQAGAJgCAKQgCALgJAGQgGAEgIAAIgFAAgEglIATdQgpgPgTgsIgZg0IhGAiIgYg0IECh9IAwBoQAVAsgPAqQgOAogoATQgWALgWAAQgRAAgSgGgEglvARXIAYAyQAKAWAUAIQATAHAWgKQAUgKAIgUQAHgVgLgXIgXgxgEAj5ARoIgiBKIgugXIBbjFIAtAXIghBIIDVBnIgYAygEA1NAS3ITPllIABAAIAAxUINfAAIrHLYILHLhgEhV7AS3ILHrhIrHrYINtAAIAARUIABAAITPFlgEA2HANSIQkAAIyDFPQA3ikAoirgEhGeANSIQQAAQAoCsA1CcgEhHvAMzIAA5DMCPtAAAIAAZDgAi/DqIAAFVIC1AAIAAocgAOtlXQiMCQABDWQAADWCGCPQCKCTDaAAQCUAAB3hOQBvhIBAh/IjTh0QgfBKg5ApQg+AthSAAQhwAAhJhPQhHhOAAhyQAAhzBJhOQBJhQBwAAQBNAAA7AmQA4AlAgBDIDJiCQhBhvhuhBQhzhCiIAAQjTAAiMCRgEhC4AFDQBLBcBdAwQBuA4CVAAQCeAABohbQBnhbAAiLQAAiNhnhJQhBgviQgiQh2gdgWgJQg2gXAAgoQAAgkAcgYQAfgbA3AAQBFAAA0AeQAvAdAjA4IC3iSQhRhahSgoQhcgth+AAQiZAAhiBXQhjBVAACBQAACHBjBHQBBAwCJAgQB4AdAeAPQAwAXAAAtQAAAqgeAYQggAag5AAQhOAAg8glQg4gigshEgEA3uAH5IKVAAIAAjZImxAAIAAinIGxAAIAAjZImxAAIAAihIGxAAIAAjaIqVAAgEAwXADTICHEmID8AAIiyliQBIgsAphMQAqhLAAhdQgBiRhdheQhihjioAAImcAAIAAPUIDkAAIAAkmgEAkeAFnIAyCSIDoAAIlivUIjdAAIlhPUIDnAAIAxiSgA4NH5IKWAAIAAjZImxAAIAAinIGxAAIAAjZImxAAIAAihIGxAAIAAjaIqWAAgEglMAH5IDkAAIAAlxIGuAAIAAjXImuAAIAAivIGuAAIAAjdIqSAAgEgrcAFnIAyCSIDoAAIlivUIjdAAIlhPUIDmAAIAyiSgAAQGSIC1AAIAAioIi1jHgADbDYIFDAAIAAi8In/AAgAlwDYICdAAIC7i8IlYAAgAAfADIFXAAIABi8IicAAgAoXADIH/AAIi/i8IlAAAgAAQgDIC1jIIAAlVIi1AAgAi/jLIC1DIIAAlvIi1AAgAf3CbIBxlJIBwFJgEgwDACbIBxlJIBxFJgEAtjAAAIAAkFICnAAQBHAAAlAiQAjAiAAA9QAAA6gjAjQgmAnhGAAgEAy6gMvQiFowkynmQktndmyljQm2lmoNjAQogjHpEAAQpFAAogDHQoNDAm2FmQmyFjktHdQkxHmiFIwIi1AAQCGpUFBoGQE7n+HLl7QHQl+IsjNQJAjVJpAAQJpAAJADVQItDNHOF+QHMF7E7H+QFBIGCGJUgEAxBgMvQiEoXkonPQkjnImhlSQmmlVn4i3QoKi9osAAQotAAoJC9Qn4C3mmFVQmiFSkiHIQkoHPiFIXIgrAAQCFofErnXQEnnPGnlYQGslbH/i6QISjAI1AAQI1AAISDAQH/C6GrFbQGoFYEmHPQEsHXCEIfgAcVsvQjqoinmlLQnylUpWAAQpXAAnyFUQnlFLjrIiIgtAAQDso0HzlXQH+lgJpAAQJoAAH/FgQHzFXDrI0gAUHsvIgWgkIguAkIgiAAIBLgsQgqhBgogyIinCfIhBAAIDiinQgrg1gyg1IjrERIhRAAIE2kYQgzg2g0grIkJF5IhaAAIFcl/QgugphCguIkKHWIhfAAIFinbQg2gnhCglIj0InIu4AAIj5otQhDAmg2AmIFmHhIhfAAIkOndQg7Aqg3AuIFiGFIhZAAIkPmAQg2AtgzA1IE8EeIhQAAIjykYQgxA0gtA4IDoCsIhAAAIiuilQgwA9gkA4IBRAwIggAAIg1gpIgZApImyAAQDnn7HKkyQHXk6I0AAQIzAAHXE6QHMEyDmH7gArK1fIFRIuIjQptQhBAchAAjgAGBszIFMonQg8ghhDgegApC2hIEZJNIiTp+QhEAVhCAcgAEwtWIEWpGQhGgeg+gUgAm03VIDgJnIhWqKQhBANhJAWgADctvIDepiQhLgXg+gNgAkj35ICkJ5IgWqOQhHAHhHAOgACGuBICjp2QhHgPhFgHgAiN4PIBlKGIAoqMIgDgBQhEAAhGAHgAAvuJIBmqFQhNgHhBAAgAM12VQAJAWAcASQBMAyA4haQAagqgDgeQgEgggcgTQgagRgbAFQgbAGgQAZQgQAaAFAZQAEAZAXAOQAXAQAUgLQgPASgPADQgOADgSgMQgPgKgHgRgAuL4tQgbABgYAPQgkAXgJApQgJApAXAlQAXAkAmAKQAoAKAlgYQAagQAMgbQAMgZgDgdIgwAEQAEAjgcASQgTANgVgGQgUgGgNgTQgLgUADgWQAEgWAUgMQAagSAcARIAUgtQgUgKgWAAIgGAAgAKW3bIArATIBQi2IgpgTQgTApgrgTIgBgBIgTArIAGACQAcANASgQgAqO64QgnAPgQAnQgRAnAPAnQAPAoAlASQAmARAngQQAogPAQgnQAQgmgPgpQgPgngmgRQgUgKgUAAQgSAAgSAIgAmy8AIBsC3IAsgJIAjjSIgwAJIgVCOIhFh8gABl5qIBFAIQAsAFAfgaQAggZAEgqQAFgrgZgfQgZgggtgFIhFgIgAGj6CIBgAcIALgmIhggcgAhd8xIAIDIIAvgCIgIjIgEgoZgSlIBNiYQAihFAtgVQAtgVA0AcQAyAaAEA0QAxghA3AdQA5AeAJA2QAIA0gjBHIhMCXgEgjPgTsQgQAIgPAcIgfA/IBIAnIAhhBQAZgzgkgUQgKgFgKAAQgGAAgGADgEgl9gUXIghBCIBCAjIAihDQAXgsgjgSQgJgFgIAAQgVAAgRAhgEAiZgQeQghgYgXguQgihEAVg/QAUg+A+ggQA8ggA/AVQA/AVAhBAQAgBAgVA/QgTA/g+AgIgdAQIhqjTQgRASgDAXQgDAWANAZQAUAoAmADIgFBdQgpgHgdgXgEAj1gT/IA8B5QAfgigXgtQgKgVgSgLQgSgKgUAAIgCAAgAfr04QgfgvAIglQAJgpA3gnIBag9IgeguIBHgxIAdAuIA4gnIBhA0IhjBEIArBBIhHAxIgrhBIhUA6QgTANgEAMQgCAKAHALQAIAMAPADIglBQQgrgQgZgngEghHgVRQgngdgCgxQgBgxAmg1IApg8IgBgBQgRgMgRAFQgRAEgPAVQgYAjAQAiIhXA0QgZhYA3hQQApg6AxgMQAygMAwAkICbBxIg1BOIgigZQAIAagFAfQgGAfgVAdQgcAoglAJQgKADgJAAQgcAAgZgTgEggNgXoQgeArAZASQATAPAWgfQAOgUABgbQABgagMgSIgFgDgAOj3AQgJgGgCgKQgDgKAGgKQAGgJAKgCQAKgCAJAFQAJAGACALQACAKgFAJQgGAJgKADIgFAAQgHAAgHgEgA8j4vQAbAAAQgRQAagbgTgpIgFgMIkth5IBHhNICuBKIhUirIBFhKICVFIQAdA/gDApQgDAogkAnQgmApg3AJgAc447IDyjIIA+BPIjyDJgAqA4mQgTgKgJgVQgHgWAIgUQAIgVAVgJQAVgIAUAKQAUAJAIAWQAIAVgIAVQgJAVgUAIQgKAEgKAAQgLAAgLgFgAbP6xIB9h/QAogoghgjQgQgQgTACQgWABgVAWIh5B7IhEhFIFClIIBDBGIh+CAQAzgHAlAlQAkAmgBAtQgBAvgpApIiKCNgACt6PIgWgCIANhvIAUADQAaADAOARQANARgCAYQgDAYgRAOQgOALgTAAIgJAAgEAiDgbUQgYgDgQgUQgQgVADgXQACgXAUgQQAVgRAWACQAXADAQAUQAQAUgCAYQgDAXgUARQgRAOgTAAIgGAAgEgdvgiRIBIhAIEpFfIhJBAgAWd/HIBakKIjSC1IhSg7ICQmlIBUA7IhdEBIDPiwIBOA5IhXEFIDKi0IBSA7IlQEdgA3Y/LQhAgMgng4Qgng5AMhDQALhDA8grQA6gpBCALQBCAMAnA4QAnA5gMBDQgMBDg8ArQgtAggzAAQgOAAgPgCgEgXfgitQgXARgGAeQgFAdARAYQAQAZAdAFQAdAFAXgRQAYgRAGgdQAFgdgRgZQgRgYgdgGIgMgBQgVAAgTANgEgVEgl7IBVgtIAUAoQgDg5A5geQAXgMAegCIAPBoQgVgEgYANQg3AdAfA/IBHCKIhVAugEAPdgjUIgbhBQgqARgfAAQgdABgjgOQg4gXgWgtQgVgrATgyQAOgjAigUQAagPAsgIQgKgfAAgXQABgXALgbQAQgqArgQQAsgRAuASQAvATAUAqQAVAqgSArQgMAfgdATQgXAOglAKIAWA2IBZgxIBqArIidBWIBECdgEANKgmSQgHAPAHAPQAGANAQAHQAOAGAOgBQAPgBATgJIghhOQgrAKgIAXgEAPDgpWQgLAEgEAMQgFAMAAALQACAMAGATQAqgJAJgXQAFgMgFgKQgGgLgLgEQgGgDgGAAQgFAAgFACgEgNBgknQgtgHgsgdIA+heQA3AuA/gVQAYgHAKgPQAJgOgFgSQgGgTgXgDQgPgCg2AEQg9AFgigLQgzgRgRg4QgRg2AfgxQAegyBAgVQA1gRAsAGQAoAGAtAbIg6BWQgsgng3ASQgYAHgJAQQgJAOAFAPQAFARAZACQAMABA0gEQBBgFAhALQA0ARATA6QASA7gfA0QggA0hCAVQgsAOgnAAQgRAAgQgCgEAIAgltQg1gKgUghQgXgjANhDIAVhtIg0gKIAPhWIA1ALIANhEIBogiIgXB4IBLAPIgRBWIhKgPIgUBnQgEAWAFALQAFAJANADQANADAOgJIAdBSQgcAOgfAAQgNAAgPgDgEgH8gmfQg1gngLhFQgMhGAng3QAng3BFgLQA2gJAuAVQAsAVAaAsIhUAyQgKgUgTgKQgTgJgVAEQgcAEgRAZQgQAYAEAeQAFAcAYASQAXARAbgEQAWgEAOgPQAOgPAFgWIBhAVQgOAzghAgQglAkg2AJQgRADgPAAQgyAAgqgfgEAELgmVQg2gFgXgfQgaghAFhEIAKhuIg1gEIAHhXIA2AEIAGhEIBkgtIgLB6IBMAHIgIBXIhMgHIgJBoQgBAXAGAKQAFAJAOABQANACANgLIAlBPQghAVgmAAIgOAAgEgC+gnPQgwgugChFQgChGAugxQAtgyBJgCQBGgCAxAvQAxAuACBFQACBGgtAxQguAyhIACIgGAAQhEAAgvgtgEgBLgqQQgeABgTAVQgUAWAAAeQACAeAVAVQAVAUAdgBQAdgBAUgWQAUgVgBgeQAAgegWgVQgUgTgdAAIgBAAg");
	this.shape.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.safeCare_Logo, new cjs.Rectangle(-550,-361.8,1100,723.7), null);


(lib.BSWH_Logo_Dallas = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnXCoQgEgFAAgIQAAgHAEgFQAFgFAHAAQAGAAAEADQAEADABAGIgHAAQgBgDgCgCQgCgBgDAAQgDAAgCABIgDAFIgBAFQAAAFACADQADADAEAAQADAAADgCQACgBAAgEIAHAAQgBAGgEAEQgDAEgHAAQgHAAgFgFgAinCsIAAgiIAHAAIAAAbIARAAIAAAHgAi1CsIgDgIIgMAAIgDAIIgHAAIAMgiIAIAAIAMAigAjDCfIAJAAIgEgNgAjcCsIAAgiIAHAAIAAAigAjuCsIgOgXIAAAXIgGAAIAAgiIAHAAIANAXIAAgXIAIAAIAAAigAkUCsIgOgXIAAAXIgHAAIAAgiIAHAAIAOAXIAAgXIAHAAIAAAigAlLCsIAAgiIAZAAIAAAGIgSAAIAAAIIARAAIAAAFIgRAAIAAAIIASAAIAAAHgAlkCsIAAgcIgKAAIAAgGIAcAAIAAAGIgKAAIAAAcgAl9CsIgNgXIgBAAIAAAXIgHAAIAAgiIAIAAIAOAXIAAgXIAHAAIAAAigAmzCsIAAgiIAYAAIAAAGIgRAAIAAAIIAQAAIAAAFIgQAAIAAAIIASAAIAAAHgArHByIAAhXIAvgyIAACJgAqOBbQgCgDAAgDQAAgEACgCQACgCAEAAQAEAAACACQACACAAAEQAAADgCADQgCADgEAAQgEAAgCgDgAqNBQQgBACAAADQAAABAAAAQAAABAAABQAAAAABABQAAAAAAABQACACADAAQABAAABAAQAAgBABAAQAAAAABAAQAAgBABAAQAAgBABAAQAAgBAAAAQAAgBABgBQAAAAAAgBQAAgDgCgCQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAgBAAQgDAAgCACgAqFBaIgDgEIgCAAIAAAEIgBAAIAAgKIAEAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIACAEgAqKBUIACAAQABAAAAAAQABAAAAAAQAAAAABgBQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAQAAAAgBAAIgCAAgAhjBIQgGgHAAgLQAAgKAGgHQAGgHALAAQAIAAAGAFQAFAEABAIIgKAAQAAgEgDgCQgDgDgEAAQgEAAgDADQgDACgBAEIgBAHQAAAHACAFQAEAEAGAAQAFAAADgDQACgDABgFIAKAAQgBAJgGAGQgFAFgJAAQgKAAgHgHgAkSBIQgGgHAAgLQAAgKAGgHQAGgHALAAQAIAAAFAFQAGAEAAAIIgJAAQgBgEgCgCQgDgDgEAAQgFAAgDADQgCACgBAEQgCADAAAEQAAAHADAFQADAEAHAAQAEAAADgDQACgCABgGIAKAAQgBAJgFAGQgFAFgJAAQgLAAgGgHgACzBNIgBgDIgBgHQAAgEgCgCQgBgCgEAAIgLAAIAAASIgKAAIAAguIAaAAQAFAAAEAEQAEADAAAGQAAAJgIADQAGABABAKIAAAEIABACIAAADIABABgACfA0IAMAAQAGAAAAgHQAAgGgGAAIgMAAgABkBNIAAguIAjAAIAAAIIgYAAIAAALIAWAAIAAAHIgWAAIAAAMIAZAAIAAAIgABBBNIAAgmIgPAAIAAgIIAmAAIAAAIIgNAAIAAAmgAAdBNIgTgeIgBAAIAAAeIgJAAIAAguIAKAAIATAfIAAgfIAKAAIAAAugAgwBNIAAguIAjAAIAAAIIgZAAIAAALIAWAAIAAAHIgWAAIAAAMIAZAAIAAAIgAisBNIAAguIAKAAIAAAmIAXAAIAAAIgAjBBNIgEgKIgRAAIgEAKIgKAAIARguIALAAIARAugAjTA7IALAAIgGgQgAkwBNIAAguIAKAAIAAAugAlmBNIAAguIAUAAQAJAAAGAGQAGAGAAALQAAALgGAGQgFAGgKAAgAlcBFIAJAAQAFAAADgDQAEgEAAgHQAAgHgEgEQgDgFgHAAIgHAAgAmXBNIAAguIAiAAIAAAIIgYAAIAAALIAXAAIAAAHIgXAAIAAAMIAZAAIAAAIgAmwBNIAAggIgLAgIgIAAIgMggIAAAgIgJAAIAAguIAOAAIALAgIAKggIAPAAIAAAugAqRBGIAAhdIAwAyIAAArgApcAWIgxgvICGAAIAAAvgAr2AWIAAgvIBbAAIgyAvgAk2AJQgDgCAAgEQAAgDADgBQACgCADAAIAEAAQADAAADgEIAJgQIABgIQAAgEgCgJIgPgoIgEgJQgCgEgFgBIgEAAQgBgBAAAAQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQAAAAAAAAIASAAIAPAAQABAAAAAAQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAABIgEAAQgBABgBAAQgBAAgBAAQAAABAAAAQgBAAAAAAQAAADAGAPIAGARQAEANABAAQABgBAGgNIAGgOQAGgPAAgEQAAgCgEgBIgGAAIgBgDQAAAAAAgBQAAAAABgBQAAAAAAAAQAAAAABAAIAQAAIAOAAIABACIgBADIgDAAQgEABgEAEIgIAPIgKAVIgdA7QgDAJgIAAQgEAAgCgCgAL2gfQgHgDgEgFQgIgLAAgOQAAgRAKgMQALgMAQAAQAMAAAHAHQAHAGAAAIIAAAGQgBABgKAAIgjAAIgDAAQgBAAAAABQAAAAAAABQAAAAAAABQAAABAAABQAAAOAIAKQAIAKAOAAIAJgBQAEgDAEgFQABAAAAAAQABAAAAAAQABAAAAABQAAABAAAAQgEAJgIAFQgIADgIAAQgJAAgHgDgAL4heQgGAFAAAFIABABIANAAQAQAAADgCIABgDQAAgFgDgDQgDgEgIAAQgIAAgGAGgAK9ghQgEgFAAgKIAAgqQAAgBAAAAQAAgBAAgBQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgFAAIgBgCIAAgCQAJgCADgEQAEgDAEgHIACAAIACAAIAAAJIAAADIADAAIAVAAQAAAAAAABQABAAAAABQAAAAAAABQAAABAAABQAAAAAAABQAAAAAAABQAAAAgBAAQAAABAAAAIgVAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBABAAAAIAAAEIAAAhQAAAKACAFQADAGAIAAIAFgBIAFgCIABABIAAACQgHAIgMAAQgLAAgEgFgAH3gcIgXg0QgQAhgHATIgCAAIgDAAIgNgdIgjhNQgDgHgCgCQgDgEgFAAIgEgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIABgCIATAAIAVAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIgBACIgEABQgGAAAAADQAAACAJAWIAgBFIAPgeIACgHIgBgFIgUgsQgCgFgDgCQgDgDgEAAIgEgBIgBgCIABgCIAUAAIAUAAIABACQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAIgEABQgGAAgBACIADAIIAOAgQAHgOADgKQAGgMgBgDQAAgDgFAAIgFgBIgBgDIACgBIARAAIARAAIABACQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAgBAAIgEABQgGAAgDAFQgCACgFAJQgHANgHAQIgCAFIACAEIASAqIARgnIAPgkIAFgRQAAgEgGAAIgFgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIABgCIATAAQAIAAAGgDIAKgHIABAAIABABIgBAXIAAAnIABADQAMgJAMAAQANAAAGAHQAFAGAAAKIAAAfQAAALABACQABACAFABIAFABIABACQAAABAAAAQAAABAAAAQgBAAAAAAQAAABAAAAIgTgBIgRABIgBgDQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAIAEgBQAEgBABgCQABgCAAgLIAAgaQAAgJgEgFQgEgGgJAAQgIAAgHAFIgCAEIgBAGIAAAfQAAAKABADQABACAFABIAEABIABACIgBADIgSgBIgSABIgBgDQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIAFgBQAFgBABgCQABgCAAgLIAAhTQAAgJgBgCQAAAAAAgBQAAAAgBAAQAAAAAAAAQgBAAAAAAIgGAFIgMAaIgNAfIgXA4IgCAAIgCAAgAD7ghQgEgFAAgKIAAgqIAAgEQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAgBAAIgFAAIgBgCIABgCQAIgCAEgEQADgDAEgHIACAAIACAAIAAAJIABADIACAAIAVAAQAAAAABABQAAAAAAABQAAAAABABQAAABAAABQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAIgVAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAABIAAAhQAAAKACAFQADAGAIAAIAGgBIAEgCIABABIABACQgHAIgNAAQgLAAgEgFgADDghQgDgFAAgKIAAgqIgBgEQAAAAAAgBQAAAAgBAAQAAAAgBAAQgBAAAAAAIgFAAIgBgCIAAgCQAJgDADgDQAEgDAEgHIACAAIABAAIAAAJIABADIADAAIAUAAQABAAAAABQAAAAAAABQABAAAAABQAAABAAABQAAAAAAABQAAAAgBABQAAAAAAAAQAAABAAAAIgVAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAABAAAAIgBAEIAAAhQAAAKACAFQADAGAJAAIAEgBIAFgCIACABIAAACQgHAIgMAAQgLAAgFgFgABsgmQgLgKAAgSQAAgRALgLQAMgLARAAQAPAAALAKQALALAAARQAAARgLALQgLALgRAAQgRAAgKgKgAB3hbQgGAIAAAPQAAAOAFAKQAIALALAAQALAAAFgKQAFgJAAgMQAAgOgFgKQgHgMgMAAQgJAAgGAJgAAnglQgLgLAAgQQAAgRALgLQAMgNAWAAQAJAAAHADQADACAAAFQAAADgCACQAAAAAAABQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgJgKgKAAQgKAAgHAHQgJAJAAAOQAAAMAIAJQAJAKANAAQAIAAAFgDQAEgDAEgFIACABIABABQgFAKgJAFQgIAEgJAAQgPAAgKgJgAgygiIgDgLQgCgIAAgHIACgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAABQAIAbAYAAQALAAAGgGQAFgGAAgJQAAgIgCgFQgDgHgJgGIgSgLQgTgOAAgSQAAgNAJgJQALgJARAAQAJAAAHACIAGABIADAKIABANIgDABIgBgBQgDgJgFgFQgFgHgMAAQgMAAgFAHQgFAGAAAIQAAANAQAJIAOAKQAXAOAAAVQAAAPgLAJQgKAJgSAAQgQAAgMgGgAi8gmQgLgKAAgSQAAgRAMgLQALgLAQAAQAQAAALAKQALALAAARQAAARgLALQgLALgRAAQgQAAgLgKgAixhbQgGAIAAAPQAAAOAGAKQAGALAMAAQALAAAGgKQAEgJAAgMQAAgOgFgKQgHgMgLAAQgKAAgGAJgAlUghQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBAAAAAAIgCABIgFADIgGADIgHABQgIAAgFgEQgGgFAAgIQAAgFAEgEQADgDAJgDIAWgIIACgCIABgEIAAgIQAAgHgDgEQgDgFgHAAQgFAAgDACQgEACAAAEQgBAFgBABQgFAEgGAAQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAgHANgHQAMgIAKAAQAKAAAFAFQAEAGAAAKIgBAgQgBAQAJAAIAFgBIACgBQAAAAABAAQAAAAAAAAQAAABAAAAQAAABAAAAIgDAFQgGADgGAAQgHAAgFgFgAlfg8IgNAFQgEADAAAFQAAAEADADQADAEAGAAIAGgCIAFgCIACgEIAAgFIABgLQAAAAAAgBQAAAAAAgBQgBAAAAAAQgBAAAAAAIgHACgAE6gmQgMgKAAgOQAAgUAWgJQgIgIAAgIQAAgJAHgHQAGgHAKAAQAHAAAFAEQAGAEAAAGQAAAGgGAEQgDADgEAAQgBAAgBAAQAAgBAAAAQgBAAABgBQAAAAAAgBIACgCQABgDgBgDQgBgDgCgCQgDgCgEAAQgFgBgDADQgEAEAAAEQAAAFAEADQADAEAKAEQAPAJAHAGQALAKAIARQAHgIAAgKQAAgHgEgFQgDgDgEgBQgFAAgEADIgCAAQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQABgEAEgEQAFgCAHAAIAJABIAHABQABAAABAAQAAgBABAAQAAAAABAAQAAgBAAAAIACgBIACABQAAAKgNADQADAGAAAGQAAANgKAMQAEAHAEADQAFADAGAAIAFgBIADAAQABAAAAAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAADgGACQgFABgHAAQgIAAgEgCQgFgCgGgFQgIAFgHADQgHACgIAAQgRAAgLgKgAE9hIQAAAOAKAKQAKALANAAIAJgBQAEgBAGgDIgIgKIgEgGIgOgRQgEgEgIgFIgDgDQgLACAAANgAKXgeIgRABIgBgDIABgCIADgBQAFgBABgCQABgCAAgLIAAggIAAgHIgFgFIgCgBIAAgBIABgCIAJgEIAKgFQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAWIAAAhQAAALABACQABACAFABIAEABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAIgBADIgRgBgAhfgeIgSABIAAgDQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAIAEgBQAFgBABgCQABgCAAgLIAAggQAAgGgBgBQgBgCgDgDIgCgBQAAAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIABgCIAJgEQAGgCAEgDIABACIAAAKIABACIAKgIQAGgDAEAAQADAAADACQACACAAADQAAAEgDADQAAAAgBABQAAAAgBAAQAAAAgBABQgBAAAAAAIgFgCQgEgDgEAAQgEAAgCAEQgDAEAAAKIAAAZQAAALABACQACADAEAAIAHABIABACIgBADIgUgBgAjfgeIgSABIgBgDIABgCIAEgBQAFgBABgCQABgCAAgLIAAhTQAAgIgBgCQAAgDgFgCIgCgBIAAgCIAAgCQAPgFAFgDQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAAAXIAABXQAAALABACQABACAFABIAEABQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAAAIgBADIgSgBgAnRgeIgVABIgBgDIABgCIADgBQAHgBACgDQABgEAAgPIAAhGQAAgKgBgEQgCgDgGAAIgGgBIgBgDIABgCQAQgBAYAAQAVAAAKAFQAOAHAAAQQAAAJgFAHQgEAFgKAEQAAABAAAAQABABAAAAQABAAAAABQABAAABAAQAJABAHAIQAJAJAAAMQAAASgNAJQgNAKgYAAIgWgBgAnIhcQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAAAIAAAcQAAAPAEAFQAEAEAKAAQAOAAAHgFQAIgHAAgNQAAgNgHgIQgJgLgUAAIgJABgAnHiRIgCABIgBADIAAAmQAAAEABABIAJAAQAPgBAGgFQAIgFAAgNQAAgMgJgHQgHgFgMAAIgIABgAqNgfIAxgwIApAAIAAAwgAshgfIAAgwIBTAAIAzAwgAqRisIAwAAIAABYIgwAzgArHhUIAAgrIAvAAIAABegAKPh7QgDgCAAgEQAAgFADgCQADgDAEAAQAEAAADADQACACAAAFQAAAEgDADQgCACgEAAQgFAAgCgDg");
	this.shape.setTransform(-73.375,165.825);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BSWH_Logo_Dallas, new cjs.Rectangle(-153.6,148.6,160.5,34.5), null);


(lib.head_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.head_img();
	this.instance.setTransform(-51,-43.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.head_mc, new cjs.Rectangle(-51,-43.5,102,87), null);


(lib.ClipGroup = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AjECBIECkBICHAAIAAEBg");
	mask.setTransform(19.65,12.925);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0.004,0.608],-19.6,0,19.7,0).s().p("AjECBIECkBICHAAIAAEBg");
	this.shape.setTransform(19.65,12.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,39.3,25.9), null);


(lib.txt_deepBreath = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// someone_txt
	this.instance = new lib.someone_txt();
	this.instance.setTransform(-76.45,-45.2,1,1,0,0,0,-52.5,7.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(77).to({_off:false},0).to({y:-55.7,alpha:1},21,cjs.Ease.quadOut).to({_off:true},1).wait(194));

	// to_txt
	this.instance_1 = new lib.to_txt();
	this.instance_1.setTransform(-146.7,-45.25,1,1,0,0,0,-13.2,7.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(73).to({_off:false},0).to({y:-55.75,alpha:1},21,cjs.Ease.quadOut).wait(4).to({_off:true},1).wait(194));

	// talk_txt
	this.instance_2 = new lib.talk_txt();
	this.instance_2.setTransform(-17.95,-64.2,1,1,0,0,0,-24.3,6.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(69).to({_off:false},0).to({y:-74.7,alpha:1},21,cjs.Ease.quadOut).wait(8).to({_off:true},1).wait(194));

	// we_txt
	this.instance_3 = new lib.we_txt();
	this.instance_3.setTransform(-62.9,-64.2,1,1,0,0,0,-15,6.9);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(65).to({_off:false},0).to({y:-74.7,alpha:1},21,cjs.Ease.quadOut).wait(12).to({_off:true},1).wait(194));

	// should_txt
	this.instance_4 = new lib.should_txt();
	this.instance_4.setTransform(-121.85,-64.15,1,1,0,0,0,-38.8,7.2);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(62).to({_off:false},0).to({y:-74.65,alpha:1},21,cjs.Ease.quadOut).wait(15).to({_off:true},1).wait(194));

	// pass_txt
	this.instance_5 = new lib.pass_txt();
	this.instance_5.setTransform(-81.65,-84.1,1,1,0,0,0,-26.7,7.2);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(39).to({_off:false},0).to({y:-94.6,alpha:1},21,cjs.Ease.quadOut).wait(38).to({_off:true},1).wait(194));

	// will_txt
	this.instance_6 = new lib.will_txt();
	this.instance_6.setTransform(-137.05,-84.15,1,1,0,0,0,-23,6.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(35).to({_off:false},0).to({y:-94.65,alpha:1},21,cjs.Ease.quadOut).wait(42).to({_off:true},1).wait(194));

	// cramping_txt
	this.instance_7 = new lib.cramping_txt();
	this.instance_7.setTransform(-68.25,-103.1,1,1,0,0,0,-51,7.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(31).to({_off:false},0).to({y:-113.6,alpha:1},21,cjs.Ease.quadOut).wait(46).to({_off:true},1).wait(194));

	// the_txt
	this.instance_8 = new lib.the_txt();
	this.instance_8.setTransform(-142.25,-103.1,1,1,0,0,0,-17.5,6.9);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(27).to({_off:false},0).to({y:-113.6,alpha:1},21,cjs.Ease.quadOut).wait(50).to({_off:true},1).wait(194));

	// breath_txt
	this.instance_9 = new lib.breath_txt();
	this.instance_9.setTransform(-67.15,-121.95,1,1,0,0,0,-39.4,7);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(4).to({_off:false},0).to({y:-132.45,alpha:1},21,cjs.Ease.quadOut).wait(73).to({_off:true},1).wait(194));

	// deep_txt
	this.instance_10 = new lib.deep_txt();
	this.instance_10.setTransform(-135.9,-122.05,1,1,0,0,0,-23.7,6.9);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).to({y:-132.55,alpha:1},21,cjs.Ease.quadOut).wait(77).to({_off:true},1).wait(194));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160.6,-139.4,167,101.30000000000001);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// TAKE_QUIZ
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F3EDE8").s().p("AgfArIAAgQIArg1IgpAAIAAgQIA8AAIAAAPIgqA2IAqAAIAAAQg");
	this.shape.setTransform(28.65,-0.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F3EDE8").s().p("AgIArIAAhVIARAAIAABVg");
	this.shape_1.setTransform(23,-0.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F3EDE8").s().p("AgNApQgGgCgFgFQgEgEgDgGQgCgHAAgIIAAgzIARAAIAAA0QAAAIAEAFQAFAFAHAAQAHAAAFgFQAFgFAAgIIAAg0IARAAIAAAzQAAAIgDAHQgCAGgFAEQgEAFgHACQgGACgHAAQgHAAgGgCg");
	this.shape_2.setTransform(16.975,-0.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F3EDE8").s().p("AgRAoQgIgDgGgGQgGgGgDgIQgEgIAAgJQAAgIAEgIQADgIAGgGQAGgGAIgDQAIgEAJAAQAIAAAIAEQAIADAGAGQAGAGADAIQAEAIAAAIQAAAIgDAHQgDAHgEAFIAMAQIgTAAIgFgGIgLAFQgFACgFAAQgJAAgIgEgAgLgZQgFACgEAEQgDAEgCAFQgDAFAAAFQAAAGADAFQACAFADAEQAEAEAFACQAFACAGAAIAGgBIAGgCIgSgYIASAAIALANIACgGIABgIQAAgFgCgFQgCgFgEgEQgDgEgFgCQgFgCgFAAQgGAAgFACg");
	this.shape_3.setTransform(7.775,-0.225);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F3EDE8").s().p("AgcArIAAhVIA5AAIAAAQIgoAAIAAATIAoAAIAAAPIgoAAIAAATIAoAAIAAAQg");
	this.shape_4.setTransform(-4.025,-0.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F3EDE8").s().p("AAQArIgTgqIgOAQIAAAaIgRAAIAAhVIARAAIAAAoIAfgoIAUAAIgbAgIAbA1g");
	this.shape_5.setTransform(-11.55,-0.225);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#F3EDE8").s().p("AAXArIgFgQIgjAAIgGAQIgQAAIAghVIAPAAIAgBVgAAMAMIgMghIgLAhIAXAAg");
	this.shape_6.setTransform(-20.225,-0.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F3EDE8").s().p("AgHArIAAhFIgYAAIAAgQIA/AAIAAAQIgYAAIAABFg");
	this.shape_7.setTransform(-28.425,-0.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},19).to({state:[]},1).wait(30));

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AmWCBIAAkBIMtAAIAAEBg");
	var mask_graphics_19 = new cjs.Graphics().p("AmWCBIAAkBIMtAAIAAEBg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:0,y:0.025}).wait(19).to({graphics:mask_graphics_19,x:0,y:0.025}).wait(1).to({graphics:null,x:0,y:0}).wait(30));

	// _Clip_Group_
	this.instance = new lib.ClipGroup();
	this.instance.setTransform(60.7,0,1,1,0,0,0,19.7,12.9);
	this.instance.alpha = 0;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:21.15,alpha:1},9,cjs.Ease.quadOut).wait(10).to({_off:true},1).wait(30));

	// Layer_2
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#01A882").s().p("AmWCBIAAkBIMtAAIAAEBg");
	this.shape_8.setTransform(0,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_8).wait(19).to({_off:true},1).wait(30));

	// _Path_
	this.instance_1 = new lib.Bitmap1();
	this.instance_1.setTransform(-46.75,-18.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({_off:true},1).wait(30));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-46.7,-18.9,96,40);


// stage content:
(lib.BSWH_DigestiveHealth_01_Centennial_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(244));

	// BSWH_Logo
	this.instance = new lib.BSWH_Logo_Dallas();
	this.instance.setTransform(166.6,61.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(11).to({_off:false},0).to({alpha:1},9).wait(224));

	// txt_tellingYou
	this.instance_1 = new lib.txt_tellingYou();
	this.instance_1.setTransform(123,195.4,0.828,0.828);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({alpha:1},10).wait(223));

	// txt_yourGut
	this.instance_2 = new lib.txt_yourGut();
	this.instance_2.setTransform(123,181.1,0.828,0.828);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(11).to({_off:false},0).to({alpha:1},10).wait(223));

	// ctaBtn
	this.instance_3 = new lib.ctaBtn("single",0);
	this.instance_3.setTransform(190.7,199.85,0.832,0.832,0,0,0,0.2,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(15).to({_off:false},0).to({y:186.35,alpha:1,mode:"synched",loop:false},11,cjs.Ease.quadOut).wait(19).to({mode:"single",startPosition:19},0).wait(199));

	// txt_deepBreath
	this.instance_4 = new lib.txt_deepBreath("synched",0,false);
	this.instance_4.setTransform(173.8,168.65);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(20).to({_off:false},0).wait(98).to({mode:"single",startPosition:98},0).wait(126));

	// safeCare_Logo
	this.instance_5 = new lib.safeCare_Logo();
	this.instance_5.setTransform(257.6,119.65,0.0933,0.0933,16.6481,0,0,1.8,2.2);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(118).to({_off:false},0).to({regX:0.6,regY:1.9,scaleX:0.0521,scaleY:0.0521,rotation:16.6527,x:257.55,y:119.6,alpha:1},7,cjs.Ease.quadOut).to({regX:0.5,regY:1.6,scaleX:0.0615,scaleY:0.0615,rotation:16.6543},4,cjs.Ease.quadOut).wait(115));

	// head_mc
	this.instance_6 = new lib.head_mc();
	this.instance_6.setTransform(254.85,297.15,0.5294,0.5294,0,0,0,0.1,43.8);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(11).to({_off:false},0).to({y:254.15},14,cjs.Ease.quadOut).wait(219));

	// BlueBox
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003DA6").s().p("AolLCIqUAAIAA1DIBChAMAkxAAAIAAWDg");
	this.shape_1.setTransform(377.05,321.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#003DA6").s().p("Ay5LCIAA1DIBChAMAkxAAAIAAWDg");
	this.shape_2.setTransform(377.05,306.375);
	this.shape_2._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1,p:{y:321.625}}]}).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_1,p:{y:233.625}}]},1).wait(233));
	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(1).to({_off:false},0).wait(1).to({y:292.525},0).wait(1).to({y:280.175},0).wait(1).to({y:269.275},0).wait(1).to({y:259.825},0).wait(1).to({y:251.825},0).wait(1).to({y:245.275},0).wait(1).to({y:240.175},0).wait(1).to({y:236.525},0).wait(1).to({y:234.375},0).to({_off:true},1).wait(233));

	// GreenBox
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#00A881").s().p("A1FLCIAA2DMApJAAAIBCBAIAAVDg");
	this.shape_3.setTransform(121.05,321.625);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(1).to({y:306.375},0).wait(1).to({y:292.525},0).wait(1).to({y:280.175},0).wait(1).to({y:269.275},0).wait(1).to({y:259.825},0).wait(1).to({y:251.825},0).wait(1).to({y:245.275},0).wait(1).to({y:240.175},0).wait(1).to({y:236.525},0).wait(1).to({y:234.375},0).wait(1).to({y:233.625},0).wait(233));

	// Background_color
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F4EDE7").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_4.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(244));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(136.1,124,362,268.3);
// library properties:
lib.properties = {
	id: 'BD94237A628B41D499830A95CE062363',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Bitmap1.png", id:"Bitmap1"},
		{src:"head_img.png", id:"head_img"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['BD94237A628B41D499830A95CE062363'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;