(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.endFrame_screen_01 = function() {
	this.initialize(img.endFrame_screen_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,139,50);


(lib.endFrame_screen_02 = function() {
	this.initialize(img.endFrame_screen_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,139,50);


(lib.epson_logo = function() {
	this.initialize(img.epson_logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,43);


(lib.image_group = function() {
	this.initialize(img.image_group);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,217);


(lib.shaq_endFrame = function() {
	this.initialize(img.shaq_endFrame);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,46,166);


(lib.shaq_frame_01 = function() {
	this.initialize(img.shaq_frame_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,265);


(lib.shaq_frame_04 = function() {
	this.initialize(img.shaq_frame_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,265);


(lib.shaq_frame_05 = function() {
	this.initialize(img.shaq_frame_05);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,139,50);


(lib.shaq_frame_07 = function() {
	this.initialize(img.shaq_frame_07);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,139,50);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_firstTelevision = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("AgSAWIAAgrIAkAAIAAArg");
	this.shape.setTransform(-127.75,52.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353534").s().p("AATBNIAAhnQAAgLgFgFQgDgFgJAAQgTAAAAAZIAABjIgnAAIAAiVIAlAAIAAARIAAAAQAGgLAKgFQAJgFANAAQASAAAKAKQAKAKAAAXIAABug");
	this.shape_1.setTransform(-138.5,46.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353534").s().p("AgcBLQgLgFgHgKQgHgKgDgPQgCgPAAgUQAAgSADgPQADgPAHgKQAHgJALgGQALgFAQAAQARAAAMAFQALAFAHAKQAHAKACAPQADAPAAASQAAAUgDAPQgDAPgHAJQgHAKgLAFQgMAFgQAAIgCAAQgPAAgLgEgAgKgwQgEAEgCAHQgDAHAAAKIgBAUIABAWQAAAJADAIQACAHAEADQAEAEAGAAQAMAAAEgMQAFgMAAgdQAAgbgFgMQgEgMgMAAQgGAAgEADg");
	this.shape_2.setTransform(-152.575,47.0752);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353534").s().p("AgSBlIAAiWIAlAAIAACWgAgShDIAAghIAlAAIAAAhg");
	this.shape_3.setTransform(-163.05,44.55);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353534").s().p("AgaBMQgLgDgGgHQgHgGgCgIQgDgJAAgLIAAgFIAjAAIAAAEQAAAKAFAGQAFAGAKAAQAIAAAFgEQAGgFAAgJQAAgHgFgEQgEgDgFgDIgagKQgQgFgJgJQgIgKAAgQQAAgKADgIQADgIAHgGQAHgGAKgEQALgEAOAAQAaAAANALQAMAMAAAUIAAAGIgiAAQAAgMgEgFQgEgFgJAAQgHAAgFAEQgGAEAAAIQAAAFAEAFQADAEAKADIAWAIQATAGAHAJQAIAKAAARQAAAMgFAJQgEAJgHAGQgIAGgKACQgKADgMAAQgQAAgKgDg");
	this.shape_4.setTransform(-172.975,47.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353534").s().p("AgSBlIAAiWIAmAAIAACWgAgShDIAAghIAmAAIAAAhg");
	this.shape_5.setTransform(-182.95,44.55);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353534").s().p("AgVBLIgniVIAoAAIAVBqIABAAIAUhqIAnAAIgmCVg");
	this.shape_6.setTransform(-192.875,47.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353534").s().p("AgfBIQgMgHgFgMQgGgLgBgOIgCgcQAAgPADgOQACgOAGgLQAGgLAMgGQAMgHATAAQAQAAALAGQALAFAGAKQAGAKACAOQADAOAAASIAAAHIhMAAIAAAMIABANIADAMQADAEADADQAEADAEAAQAKAAAFgHQAEgHACgOIAiAAQgBAagNAOQgNAOgbAAQgUAAgMgHgAgIgxQgDADgDAEIgDAKIgBAKIAAAGIAnAAIgCgPQAAgHgCgEQgCgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_7.setTransform(-205.975,47.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353534").s().p("AgTBkIAAjHIAmAAIAADHg");
	this.shape_8.setTransform(-216.2,44.65);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353534").s().p("AgfBIQgMgHgFgMQgGgLgBgOIgCgcQAAgPADgOQACgOAGgLQAGgLAMgGQAMgHATAAQAQAAALAGQALAFAGAKQAGAKACAOQADAOAAASIAAAHIhMAAIAAAMIABANIADAMQADAEADADQAEADAEAAQAKAAAFgHQAEgHACgOIAiAAQgBAagNAOQgNAOgbAAQgUAAgMgHgAgIgxQgDADgDAEIgDAKIgBAKIAAAGIAnAAIgCgPQAAgHgCgEQgCgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_9.setTransform(-226.425,47.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353534").s().p("AgTBkIAAimIgsAAIAAghIB/AAIAAAhIgsAAIAACmg");
	this.shape_10.setTransform(-239.975,44.65);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353534").s().p("AgaBMQgLgDgGgHQgHgGgCgIQgDgJAAgLIAAgFIAjAAIAAAEQAAAKAFAGQAFAGAKAAQAIAAAFgEQAGgFAAgJQAAgHgFgEQgEgDgFgDIgagKQgQgFgJgJQgIgKAAgQQAAgKADgIQADgIAHgGQAHgGAKgEQALgEAOAAQAaAAANALQAMAMAAAUIAAAGIgiAAQAAgMgEgFQgEgFgJAAQgHAAgFAEQgGAEAAAIQAAAFAEAFQADAEAKADIAWAIQATAGAHAJQAIAKAAARQAAAMgFAJQgEAJgHAGQgIAGgKACQgKADgMAAQgQAAgKgDg");
	this.shape_11.setTransform(-260.375,47.075);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353534").s().p("AgmBLQgIgDgDgGQgFgHgCgHQgBgIAAgHQAAgLABgIQADgHAFgGQAEgFAHgDIARgHIAVgFQAJgDAEgEQACgEAAgHQAAgJgDgFQgFgEgJAAQgIAAgEAFQgFAFAAAJIAAAEIgjAAIAAgDQAAgOAFgIQADgJAHgGQAIgFAKgCQAJgDALAAQAQAAALAEQALADAFAGQAHAGABAJQACAIAAAKIAABPIABAQIAFANIglAAIgEgIIgCgIIAAAAQgHAMgJADQgHAEgOAAQgKAAgHgEgAAIAFIgIADQgKADgGAFQgEAGAAAKQAAAJACAGQAEAGAIAAIAHgBQAEgBADgDQAEgDADgEQABgFAAgGIAAgeg");
	this.shape_12.setTransform(-273.8,47.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353534").s().p("AAUBLIgThqIgBAAIgSBqIgtAAIggiVIAmAAIARBqIABAAIAThqIApAAIAUBqIAAAAIAShqIAlAAIggCVg");
	this.shape_13.setTransform(-290.7,47.125);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353534").s().p("AgfBIQgMgHgFgMQgGgLgBgOIgCgcQAAgPADgOQACgOAGgLQAGgLAMgGQAMgHATAAQAQAAALAGQALAFAGAKQAGAKACAOQADAOAAASIAAAHIhMAAIAAAMIABANIADAMQADAEADADQAEADAEAAQAKAAAFgHQAEgHACgOIAiAAQgBAagNAOQgNAOgbAAQgUAAgMgHgAgIgxQgDADgDAEIgDAKIgBAKIAAAGIAnAAIgCgPQAAgHgCgEQgCgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_14.setTransform(-314.525,47.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353534").s().p("AgnBNIAAiVIAlAAIAAAUIABAAQAFgLAIgHQAJgGALAAIAEAAIAEAAIAAAlIgHAAIgGAAIgKABQgFABgEAEQgEADgCAFQgCAFAAAIIAABZg");
	this.shape_15.setTransform(-325.45,46.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353534").s().p("AgfBIQgMgHgFgMQgGgLgBgOIgCgcQAAgPADgOQACgOAGgLQAGgLAMgGQAMgHATAAQAQAAALAGQALAFAGAKQAGAKACAOQADAOAAASIAAAHIhMAAIAAAMIABANIADAMQADAEADADQAEADAEAAQAKAAAFgHQAEgHACgOIAiAAQgBAagNAOQgNAOgbAAQgUAAgMgHgAgIgxQgDADgDAEIgDAKIgBAKIAAAGIAnAAIgCgPQAAgHgCgEQgCgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_16.setTransform(-337.575,47.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353534").s().p("AATBkIAAhnQgBgLgEgGQgDgEgJAAQgTAAgBAYIAABkIgmAAIAAjHIAmAAIAABBIABAAQAMgTAYAAQASAAAKAKQAKAJAAAXIAABvg");
	this.shape_17.setTransform(-351.45,44.65);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353534").s().p("AgCBgQgIgCgDgFQgEgEgCgIIgBgTIAAhVIgTAAIAAgaIATAAIAAgrIAmAAIAAArIAXAAIAAAaIgXAAIAABQQAAAJADAEQACAEAJAAIAEAAIAFgBIAAAbIgNABIgNAAQgLAAgGgBg");
	this.shape_18.setTransform(-362.9,45.025);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353534").s().p("AgCBgQgIgCgDgFQgEgEgCgIIgBgTIAAhVIgTAAIAAgaIATAAIAAgrIAmAAIAAArIAXAAIAAAaIgXAAIAABQQAAAJADAEQACAEAJAAIAEAAIAFgBIAAAbIgNABIgNAAQgLAAgGgBg");
	this.shape_19.setTransform(-378.65,45.025);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353534").s().p("AgaBMQgLgDgGgHQgHgGgCgIQgDgJAAgLIAAgFIAjAAIAAAEQAAAKAFAGQAFAGAKAAQAIAAAFgEQAGgFAAgJQAAgHgFgEQgEgDgFgDIgagKQgQgFgJgJQgIgKAAgQQAAgKADgIQADgIAHgGQAHgGAKgEQALgEAOAAQAaAAANALQAMAMAAAUIAAAGIgiAAQAAgMgEgFQgEgFgJAAQgHAAgFAEQgGAEAAAIQAAAFAEAFQADAEAKADIAWAIQATAGAHAJQAIAKAAARQAAAMgFAJQgEAJgHAGQgIAGgKACQgKADgMAAQgQAAgKgDg");
	this.shape_20.setTransform(-389.425,47.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353534").s().p("AgmBNIAAiVIAlAAIAAAUIAAAAQAFgLAIgHQAIgGANAAIADAAIADAAIAAAlIgFAAIgHAAIgJABQgFABgFAEQgEADgDAFQgBAFAAAIIAABZg");
	this.shape_21.setTransform(-400.1,46.925);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353534").s().p("AgSBlIAAiWIAlAAIAACWgAgShDIAAghIAlAAIAAAhg");
	this.shape_22.setTransform(-409.1,44.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353534").s().p("Ag3BkIAAjHIBvAAIAAAhIhHAAIAAAvIBDAAIAAAgIhDAAIAABXg");
	this.shape_23.setTransform(-418.8,44.65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_firstTelevision, new cjs.Rectangle(-485.5,25.8,421.2,37.099999999999994), null);


(lib.txt_epiqVision = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("AgSAWIAAgrIAkAAIAAArg");
	this.shape.setTransform(-138.55,46.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353534").s().p("AATBNIAAhnQAAgLgFgFQgDgFgJAAQgTAAAAAZIAABjIgnAAIAAiVIAlAAIAAARIAAAAQAGgLAKgFQAJgFANAAQASAAAKAKQAKAKAAAXIAABug");
	this.shape_1.setTransform(-149.3,41.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353534").s().p("AgcBLQgLgFgHgKQgHgKgDgPQgCgPAAgUQAAgSADgPQADgPAHgKQAHgJALgGQALgFAQAAQARAAAMAFQALAFAHAKQAHAKACAPQADAPAAASQAAAUgDAPQgDAPgHAJQgHAKgLAFQgMAFgQAAIgCAAQgPAAgLgEgAgKgwQgEAEgCAHQgDAHAAAKIgBAUIABAWQAAAJADAIQACAHAEADQAEAEAGAAQAMAAAEgMQAFgMAAgdQAAgbgFgMQgEgMgMAAQgGAAgEADg");
	this.shape_2.setTransform(-163.375,41.4252);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353534").s().p("AgSBlIAAiWIAlAAIAACWgAgShDIAAghIAlAAIAAAhg");
	this.shape_3.setTransform(-173.85,38.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353534").s().p("AgaBMQgLgDgGgHQgHgGgCgIQgDgJAAgLIAAgFIAjAAIAAAEQAAAKAFAGQAFAGAKAAQAIAAAFgEQAGgFAAgJQAAgHgFgEQgEgDgFgDIgagKQgQgFgJgJQgIgKAAgQQAAgKADgIQADgIAHgGQAHgGAKgEQALgEAOAAQAaAAANALQAMAMAAAUIAAAGIgiAAQAAgMgEgFQgEgFgJAAQgHAAgFAEQgGAEAAAIQAAAFAEAFQADAEAKADIAWAIQATAGAHAJQAIAKAAARQAAAMgFAJQgEAJgHAGQgIAGgKACQgKADgMAAQgQAAgKgDg");
	this.shape_4.setTransform(-183.775,41.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353534").s().p("AgSBlIAAiWIAmAAIAACWgAgShDIAAghIAmAAIAAAhg");
	this.shape_5.setTransform(-193.75,38.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353534").s().p("AgZBkIgujHIArAAIAcCTIAAAAIAeiTIAqAAIguDHg");
	this.shape_6.setTransform(-204.725,39);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353534").s().p("AAUBlIAAg+IAAAAQgGAJgIAEQgHAEgLAAQgYAAgLgSQgLgTAAgoQAAgrALgSQALgSAYAAQAMgBAHAFQAIAEAGALIABAAIAAgQIAlAAIAADGgAgQg7QgDANAAAZQAAAXADANQAEANAMgBQANABAEgNQADgNAAgXQAAgZgDgNQgEgMgNAAQgMAAgEAMg");
	this.shape_7.setTransform(-219.575,43.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353534").s().p("AgTBlIAAiWIAmAAIAACWgAgThDIAAghIAmAAIAAAhg");
	this.shape_8.setTransform(-230.15,38.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353534").s().p("Ag6BlIAAjGIAlAAIAAAQIABAAQAGgLAIgEQAHgFAMABQAYAAALASQALASAAArQAAAogLATQgLASgYAAQgLAAgHgEQgIgEgGgJIAAAAIAAA+gAgQg7QgDANAAAZQAAAXADANQAEANAMgBQANABAEgNQADgNAAgXQAAgZgDgNQgEgMgNAAQgMAAgEAMg");
	this.shape_9.setTransform(-240.725,43.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353534").s().p("Ag4BkIAAjHIBvAAIAAAhIhHAAIAAAvIBCAAIAAAgIhCAAIAAA2IBJAAIAAAhg");
	this.shape_10.setTransform(-254.625,39);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353534").s().p("AgaBMQgLgDgGgHQgHgGgCgIQgDgJAAgLIAAgFIAjAAIAAAEQAAAKAFAGQAFAGAKAAQAIAAAFgEQAGgFAAgJQAAgHgFgEQgEgDgFgDIgagKQgQgFgJgJQgIgKAAgQQAAgKADgIQADgIAHgGQAHgGAKgEQALgEAOAAQAaAAANALQAMAMAAAUIAAAGIgiAAQAAgMgEgFQgEgFgJAAQgHAAgFAEQgGAEAAAIQAAAFAEAFQADAEAKADIAWAIQATAGAHAJQAIAKAAARQAAAMgFAJQgEAJgHAGQgIAGgKACQgKADgMAAQgQAAgKgDg");
	this.shape_11.setTransform(-275.425,41.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353534").s().p("AgRAaQAHgCAEgGQADgHAAgIIAAgDIgOAAIAAgsIAkAAIAAAlQAAAKgCAJQgBAJgFAIQgEAGgHAEQgHAFgKABg");
	this.shape_12.setTransform(-285.65,33.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353534").s().p("AgfBIQgMgHgFgMQgGgLgBgOIgCgcQAAgPADgOQACgOAGgLQAGgLAMgGQAMgHATAAQAQAAALAGQALAFAGAKQAGAKACAOQADAOAAASIAAAHIhMAAIAAAMIABANIADAMQADAEADADQAEADAEAAQAKAAAFgHQAEgHACgOIAiAAQgBAagNAOQgNAOgbAAQgUAAgMgHgAgIgxQgDADgDAEIgDAKIgBAKIAAAGIAnAAIgCgPQAAgHgCgEQgCgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_13.setTransform(-296.175,41.425);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353534").s().p("AgmBNIAAiVIAkAAIAAAUIABAAQAFgLAIgHQAJgGAMAAIADAAIAEAAIAAAlIgHAAIgGAAIgKABQgEABgFAEQgEADgDAFQgBAFAAAIIAABZg");
	this.shape_14.setTransform(-307.1,41.275);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353534").s().p("AgfBIQgMgHgFgMQgGgLgBgOIgCgcQAAgPADgOQACgOAGgLQAGgLAMgGQAMgHATAAQAQAAALAGQALAFAGAKQAGAKACAOQADAOAAASIAAAHIhMAAIAAAMIABANIADAMQADAEADADQAEADAEAAQAKAAAFgHQAEgHACgOIAiAAQgBAagNAOQgNAOgbAAQgUAAgMgHgAgIgxQgDADgDAEIgDAKIgBAKIAAAGIAnAAIgCgPQAAgHgCgEQgCgFgEgCQgEgCgGAAQgFAAgEACg");
	this.shape_15.setTransform(-319.225,41.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353534").s().p("AASBkIAAhnQAAgMgEgEQgDgFgJAAQgTAAgBAYIAABkIgmAAIAAjHIAmAAIAABBIABAAQAMgTAXAAQATgBAKALQAKAKAAAXIAABug");
	this.shape_16.setTransform(-333.1,39);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353534").s().p("AgCBgQgIgCgDgFQgEgEgCgIIAAgTIAAhVIgUAAIAAgaIAUAAIAAgrIAlAAIAAArIAXAAIAAAaIgXAAIAABQQAAAJACAEQADAEAJAAIAEAAIAFgBIAAAbIgNABIgNAAQgLAAgGgBg");
	this.shape_17.setTransform(-344.55,39.375);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353534").s().p("AAUBLIgThqIgBAAIgSBqIgtAAIghiVIAnAAIARBqIABAAIAThqIApAAIAUBqIAAAAIAShqIAlAAIggCVg");
	this.shape_18.setTransform(-366.1,41.475);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353534").s().p("AgcBLQgLgFgHgKQgHgKgDgPQgCgPAAgUQAAgSADgPQADgPAHgKQAHgJALgGQALgFAQAAQARAAAMAFQALAFAHAKQAHAKACAPQADAPAAASQAAAUgDAPQgDAPgHAJQgHAKgLAFQgMAFgQAAIgCAAQgPAAgLgEgAgKgwQgEAEgCAHQgDAHAAAKIgBAUIABAWQAAAJADAIQACAHAEADQAEAEAGAAQAMAAAEgMQAFgMAAgdQAAgbgFgMQgEgMgMAAQgGAAgEADg");
	this.shape_19.setTransform(-383.025,41.4252);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353534").s().p("AAVBkIgxiLIAAAAIAACLIglAAIAAjHIAuAAIAwCIIABAAIAAiIIAkAAIAADHg");
	this.shape_20.setTransform(-398.175,39);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_epiqVision, new cjs.Rectangle(-481.1,20.1,421.20000000000005,37.1), null);


(lib.panel = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2B3481").s().p("AuWB6QgCgCAAgEIAEAAIABADQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAQAFAAADgDIAAgIIgDADIgFABQgEAAgEgDQgCgDAAgHQAAgGACgEQAEgEAEAAQADAAADACIADACIAAgDIADAAIAAAYQAAAFgBACQgDAGgIAAQgEAAgDgCgAuUBeIgBAGQAAAFACACQAAABABAAQAAAAABABQAAAAABAAQABAAAAAAQAFAAACgEQABgCABgDQAAgFgCgDQgCgCgEAAQgFAAgBAEgApNB7IAAgkIAEAAIAAADIADgDQACgBADAAQAEAAAEADQADAEAAAGQAAAJgEADQgDADgEAAQgDAAgCgCIgDgCIAAANgApIBeIgBAHIABAFQACAEAFAAQACAAADgDQACgCAAgFIgBgGQgCgEgEAAQgFAAgCAEgAt8B7IAAgEIACABIABAAIACgBIADgFIgKgbIAFAAIAHAVIAHgVIAFAAIgIAWIgGAMQgBACgEAAgASWBuQgEgDAAgHQAAgGAEgEQADgEAGAAIAFABIAFAEIABAEIAAAGIgSAAQAAAEABACQACADAEAAQADAAACgCIACgDIAEAAIgBADIgCADQgCACgDAAIgDABQgGAAgDgEgASmBiIgCgFQgBgDgEAAQgEAAgCACQgBACAAAEIAOAAIAAAAgAR5BuQgDgEAAgGQAAgFADgFQACgEAGAAIAFABIACADIAAgNIAFAAIAAAkIgEAAIAAgEIgDAEIgGABQgEAAgDgEgAR9BdQgCACAAAFQAAAEACADQABADAEAAQADAAACgDQACgCAAgFQAAgFgCgDQgCgCgDAAQgDAAgCADgARcBuQgDgEABgGQAAgGADgEQADgEAFAAQAFAAAEADQAEAEAAAGQAAAGgEAFQgDAEgGAAQgFAAgEgEgARgBdQgCADAAAEQAAAEACADQABADAEAAQAFAAABgDQACgEAAgEIgBgGQgCgDgFAAQgEAAgBADgAPiBuQgEgDAAgFIAGAAIAAAFQACADAFAAQADAAACgCQABgBAAAAQABgBAAAAQAAgBAAgBQABAAAAgBQAAgEgDgBQgCgBgEAAIgCAAIAAgEIADAAIADgBQADgBAAgEQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBAAQAAAAgBAAQgEAAgCADIgBAEIgFAAQAAgEACgCQADgFAHAAQAFAAADACQADADAAAEQAAADgCACIgDACQADABACACQABACAAADQAAAFgDAEQgEADgFAAQgHAAgCgEgALHBvQgCgDgBgDIAFAAIABADQABACAFAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIgEgBIgEgBIgFgCQgCgCgBgDQABgDACgDQADgCAEAAQAGAAADADIABAFIgDAAIgBgDQgCgBgEAAIgEABIgBACQAAABAAAAQAAAAAAABQABAAAAAAQAAABABAAIACABIADABIAHACQACACAAADQAAAEgCACQgDADgGAAQgFAAgDgDgAJ0BuQgDgEAAgGQAAgGADgEQADgEAGAAQAFAAAEADQADAEAAAGQAAAGgDAFQgDAEgHAAQgFAAgDgEgAJ3BdQgCADAAAEQAAAEACADQACADAEAAQAEAAACgDQABgEABgEIgBgGQgCgDgFAAQgEAAgCADgAIUBuQgDgEAAgGQABgGADgEQADgEAFAAQAGAAADADQADAEABAGQAAAGgEAFQgDAEgGAAQgGAAgDgEgAIYBdQgCADAAAEQAAAEACADQABADAEAAQAFAAABgDQACgEAAgEIgBgGQgCgDgFAAQgEAAgBADgAH6BvQgCgDgBgDIAFAAIABADQACACAEAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIgDgBIgEgBIgFgCQgDgCAAgDQAAgDADgDQADgCAEAAQAHAAACADIACAFIgFAAIgBgDQgBgBgEAAIgEABIgBACQAAABAAAAQAAAAAAABQABAAAAAAQAAABABAAIACABIAEABIAGACQADACAAADQAAAEgDACQgDADgGAAQgGAAgCgDgAHeBuQgDgDAAgHQAAgGADgEQAEgEAFAAIAGABIAEAEIACAEIAAAGIgTAAQAAAEACACQABADAEAAQADAAADgCIABgDIAFAAIgBADIgDADQgCACgCAAIgEABQgFAAgEgEgAHuBiIgBgFQgCgDgEAAQgDAAgCACQgCACAAAEIAOAAIAAAAgAFkBuQgEgDAAgHQAAgGAEgEQADgEAGAAIAFABIAEAEIACAEIAAAGIgTAAQAAAEACACQACADADAAQADAAACgCIADgDIAEAAIgBADIgCADQgCACgEAAIgDABQgFAAgDgEgAF0BiIgCgFQgBgDgFAAQgDAAgCACQgCACAAAEIAPAAIAAAAgAFHBuQgDgDgBgHQABgGADgEQADgEAGAAIAFABIAFAEIABAEIABAGIgTAAQAAAEACACQABADAEAAQADAAACgCIACgDIAEAAIgBADIgCADQgCACgDAAIgDABQgGAAgDgEgAFXBiIgCgFQgBgDgEAAQgEAAgBACQgCACAAAEIAOAAIAAAAgAEbBuQgDgEAAgGQAAgGAEgEQADgEAFAAQAEAAADACQADACABAFIgFAAIgCgEQAAAAAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAQgEAAgCAEQgCADABADQAAAEABADQACADAEAAQAAAAABAAQAAAAABgBQAAAAABAAQABAAAAgBIACgFIAFAAQgBAGgEACQgDADgEAAQgFAAgDgEgAEBBvQgCgDgBgDIAEAAIABADQACACAFAAQAAAAABAAQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIgDgBIgFgBIgEgCQgDgCAAgDQAAgDADgDQADgCAEAAQAGAAADADIABAFIgEAAIgBgDQgBgBgEAAIgFABIgBACQAAABABAAQAAAAAAABQAAAAAAAAQABABAAAAIADABIADABIAHACQACACAAADQAAAEgCACQgEADgFAAQgGAAgCgDgAC6BuQgDgEAAgGQAAgGADgEQADgEAGAAQAEAAAEADQAEAEgBAGQAAAGgCAFQgDAEgHAAQgFAAgDgEgAC9BdQgCADAAAEQAAAEACADQACADAEAAQAEAAACgDQABgEAAgEIgBgGQgCgDgEAAQgEAAgCADgAByBuQgDgEAAgGQAAgGADgEQADgEAGAAQAFAAAEADQADAEAAAGQAAAGgDAFQgDAEgGAAQgGAAgDgEgAB1BdQgCADAAAEQAAAEACADQACADAEAAQAFAAABgDQABgEABgEIgBgGQgCgDgFAAQgEAAgCADgAASBuQgCgEAAgGQAAgGADgEQADgEAFAAQAGAAADADQAEAEAAAGQAAAGgEAFQgDAEgGAAQgFAAgEgEgAAWBdQgCADAAAEQAAAEACADQABADAEAAQAFAAABgDQACgEAAgEIgBgGQgCgDgFAAQgEAAgBADgAgHBvQgCgDgBgDIAFAAIABADQACACADAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIgEgBIgDgBIgFgCQgCgCgBgDQABgDACgDQADgCADAAQAHAAACADIABAFIgEAAIAAgDQgCgBgEAAIgDABIgBACQAAABAAAAQAAAAAAABQABAAAAAAQAAABABAAIACABIADABIAGACQADACAAADQAAAEgDACQgDADgGAAQgEAAgDgDgAgjBuQgDgDAAgHQAAgGADgEQAEgEAFAAIAGABIAEAEIACAEIAAAGIgTAAQAAAEACACQACADADAAQAEAAACgCIABgDIAFAAIgCADIgCADQgBACgDAAIgEABQgFAAgEgEgAgTBiIgBgFQgCgDgEAAQgDAAgCACQgCACAAAEIAOAAIAAAAgAkaBuQgEgDAAgHQAAgGAEgEQAEgEAFAAIAFABIAFAEIABAEIAAAGIgTAAQAAAEACACQACADAEAAQADAAACgCIACgDIAEAAIgBADIgCADQgCACgDAAIgDABQgFAAgEgEgAkKBiIgCgFQgBgDgEAAQgDAAgDACQgCACAAAEIAPAAIAAAAgAk+BwIgCgDIAAAEIgFAAIAAgkIAFAAIAAANIADgDIAEgBQAGAAACADQAEAEAAAGQAAAGgEAEQgDAFgFAAQgDAAgCgCgAk+BcQgCACAAAFIABAGQABAFAFAAQADAAACgDQACgDAAgFQAAgEgCgCQgCgDgDAAQgDAAgCACgAl8BuQgDgEAAgGQAAgGADgEQADgEAGAAQAFAAAEADQADAEAAAGQAAAGgDAFQgDAEgGAAQgGAAgDgEgAl5BdQgCADAAAEQAAAEACADQACADAEAAQAFAAABgDQABgEABgEIgBgGQgCgDgFAAQgEAAgCADgAmYBuQgDgEgBgGQABgFADgFQACgEAGAAIAEABIADADIAAgNIAFAAIAAAkIgEAAIAAgEIgEAEIgFABQgEAAgDgEgAmVBdQgCACAAAFQAAAEACADQABADAFAAQACAAACgDQACgCABgFQgBgFgCgDQgCgCgCAAQgEAAgCADgAnEBuQgCgEAAgGQgBgGAEgEQADgEAGAAQAEAAAEADQAEAEgBAGQAAAGgDAFQgCAEgHAAQgGAAgDgEgAnABdQgCADAAAEQAAAEACADQACADAEAAQAEAAACgDQABgEAAgEIgBgGQgCgDgEAAQgEAAgCADgAoJBuQgDgDAAgHQAAgGADgEQAEgEAFAAIAGABIAEAEIACAEIAAAGIgTAAQAAAEACACQACADADAAQAEAAACgCIABgDIAFAAIgCADIgCADQgCACgCAAIgEABQgFAAgEgEgAn5BiIgBgFQgCgDgEAAQgDAAgCACQgCACAAAEIAOAAIAAAAgAqRBuQgCgEAAgGQAAgGADgEQADgEAFAAQAFAAACACQADACABAFIgEAAIgCgEQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAgBAAQgEAAgBAEQgCADAAADQAAAEACADQABADAEAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAABgBIACgFIAEAAQgBAGgDACQgDADgFAAQgFAAgDgEgAqtBvQgDgCABgDQgBgEADgCQACgCAEAAIAGgBIADgBIAAgCQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIgFgBQgEAAgBACIgBADIgEAAQAAgFADgCQADgCAEAAQAFAAADACQACABAAAEIAAAPIAAABIACABIABAAIAAADIgCAAIgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgDQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAQgCACgDAAQgEAAgCgDgAqgBkIgFABIgEABQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABAAAAIAEABIAEgBQAEgCAAgEIAAgEIgCABgArJBuQgDgDAAgHQAAgGADgEQAEgEAFAAIAGABIADAEIACAEIAAAGIgTAAQAAAEACACQACADAEAAQADAAACgCIACgDIAEAAIgBADIgCADQgCACgDAAIgDABQgFAAgEgEgAq5BiIgBgFQgCgDgEAAQgEAAgCACQgCACAAAEIAPAAIAAAAgArzBvQgBgDgBgDIAFAAIABADQABACAEAAQABAAABAAQAAAAABAAQAAAAABgBQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAAAAAQgBAAAAgBIgEgBIgEgBIgFgCQgCgCAAgDQAAgDACgDQADgCAFAAQAGAAACADIACAFIgEAAIgBgDQgBgBgFAAIgDABIgBACQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAIADABIADABIAGACQADACAAADQAAAEgDACQgDADgFAAQgGAAgDgDgAtSBvQgCgDgBgDIAFAAIABADQACACAEAAQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBgBIgDgBIgEgBIgFgCQgCgCAAgDQAAgDACgDQADgCAFAAQAFAAADADIACAFIgFAAIgBgDQgBgBgEAAIgEABIgBACQAAABAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAEABIADABIAGACQACACABADQgBAEgCACQgDADgFAAQgHAAgCgDgAuzBuQgDgEAAgGQAAgGADgEQADgEAGAAQAFAAAEADQADAEAAAGQAAAGgDAFQgDAEgGAAQgGAAgDgEgAuwBdQgCADAAAEQAAAEACADQACADAEAAQAFAAABgDQABgEABgEIgBgGQgCgDgFAAQgEAAgCADgAvcBuQgDgEAAgGQABgGADgEQADgEAFAAQAGAAADADQADAEABAGQAAAGgEAFQgDAEgGAAQgGAAgDgEgAvYBdQgCADAAAEQAAAEACADQABADAEAAQAFAAABgDQACgEAAgEIgBgGQgCgDgFAAQgEAAgBADgAwvBuQgCgEAAgGQAAgGADgEQADgEAFAAQAFAAADACQACACABAFIgEAAIgCgEQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBAAgBAAQgEAAgBAEQgCADAAADQAAAEACADQABADAEAAQABAAAAAAQABAAAAgBQABAAAAAAQABAAABgBIACgFIAEAAQgBAGgDACQgDADgFAAQgFAAgDgEgAxLBuQgDgDAAgHQAAgGADgEQAEgEAFAAIAGABIAEAEIABAEIABAGIgTAAQAAAEACACQABADAEAAQAEAAACgCIACgDIADAAIgBADIgCADQgBACgEAAIgDABQgFAAgEgEgAw6BiIgCgFQgCgDgEAAQgDAAgCACQgCACAAAEIAPAAIAAAAgAyQBuQgDgEAAgGQAAgFADgFQADgEAFAAIAGABIACADIAAgNIAFAAIAAAkIgFAAIAAgEIgDAEIgFABQgFAAgDgEgAyMBdQgCACAAAFQAAAEACADQABADAEAAQAEAAABgDQACgCAAgFQAAgFgCgDQgBgCgEAAQgDAAgCADgAysBuQgDgDAAgHQAAgGADgEQAEgEAFAAIAGABIAEAEIACAEIAAAGIgTAAQAAAEACACQACADADAAQAEAAACgCIABgDIAFAAIgCADIgCADQgCACgCAAIgEABQgFAAgEgEgAycBiIgBgFQgCgDgEAAQgDAAgCACQgCACAAAEIAOAAIAAAAgAzGBuQgDgEAAgGQAAgGADgEQADgEAGAAQAEAAADACQADACABAFIgFAAIgBgEQgBAAAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAQgEAAgCAEQgBADAAADQAAAEACADQABADADAAQABAAABAAQAAAAABgBQAAAAABAAQAAAAABgBIACgFIAFAAQgCAGgDACQgDADgEAAQgFAAgDgEgAz/BvQgDgCABgDQgBgEADgCQACgCAEAAIAGgBIADgBIAAgCQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAAAAAIgFgBQgEAAgBACIgBADIgEAAQAAgFADgCQADgCAEAAQAFAAADACQACABAAAEIAAAPIAAABIACABIABAAIAAADIgCAAIgBAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQgBAAAAAAIgBgDQAAABgBAAQAAABAAAAQgBAAAAABQgBAAgBAAQgCACgDAAQgEAAgCgDgAzyBkIgFABIgEABQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAQAAABAAAAIAEABIAEgBQAEgCAAgEIAAgEIgCABgAMPBuIgBgGIAAgRIAFAAIAAARIAAADQABADADAAQAFAAACgFIAAgGIAAgMIAFAAIAAAaIgFAAIABgEIgCACQgDACgEAAQgFAAgCgDgAJfBxQgBAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAIgBgEIAAgSIgDAAIAAgDIADAAIAAgIIAFAAIAAAIIADAAIAAADIgDAAIAAARIABACIABAAIABAAIAAAEIgBAAgAI9BuIgBgGIAAgRIAEAAIAAARIAAADQACADADAAQAFAAABgFIABgGIAAgMIAEAAIAAAaIgEAAIABgEIgDACQgDACgDAAQgFAAgCgDgABdBxQgBAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAIgBgEIAAgSIgDAAIAAgDIADAAIAAgIIAEAAIAAAIIAFAAIAAADIgFAAIAAARIACACIABAAIACAAIAAAEIgCAAgAA7BuIgBgGIAAgRIAEAAIAAARIAAADQACADADAAQAFAAABgFIABgGIAAgMIAEAAIAAAaIgEAAIABgEIgDACQgDACgDAAQgFAAgCgDgAjQBuIgBgGIAAgRIAEAAIAAARIAAADQACADADAAQAFAAABgFIABgGIAAgMIAEAAIAAAaIgEAAIABgEIgDACQgCACgEAAQgFAAgCgDgAlgBuIgBgGIAAgRIAEAAIAAARIABADQACADADAAQAEAAACgFIABgGIAAgMIAEAAIAAAaIgEAAIAAgEIgCACQgDACgDAAQgGAAgCgDgAnNBxQgBAAAAAAQgBAAgBAAQAAAAgBgBQAAAAgBAAIgBgEIAAgSIgDAAIAAgDIADAAIAAgIIAFAAIAAAIIAEAAIAAADIgEAAIAAARIABACIABAAIACAAIAAAEIgCAAgAr8BxQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAIgBgEIAAgSIgEAAIAAgDIAEAAIAAgIIAEAAIAAAIIAFAAIAAADIgFAAIAAARIABACIACAAIACAAIAAAEIgCAAgASyBxIAAgGIAFAAIAAAGgARPBxIAAgeIgKAeIgFAAIgKgeIAAABIAAAEIAAAZIgFAAIAAgkIAHAAIAKAeIALgeIAGAAIAAAkgAP+BxIAAgkIAOAAQAHAAAFAFQADAFAAAHQAAAGgCAFQgDAIgKAAgAQDBtIAIAAIAFgBQACgBACgDIACgFIABgEQgBgHgDgDQgCgEgGAAIgIAAgAPHBxIAAgRIgBgEQgCgCgDAAIgCAAIgDACIgCADIAAAEIAAAOIgEAAIAAgaIAEAAIAAADIAEgDIAEgBQAGAAACAEIABAGIAAARgAOpBxIAAgaIAFAAIAAAagAN3BxIAAgkIAOAAQAHAAAFAFQADAFAAAHQAAAGgCAFQgDAIgKAAgAN8BtIAIAAIAFgBQACgBACgDIACgFIABgEQgBgHgDgDQgCgEgGAAIgIAAgANpBxIAAgRIgSAAIAAARIgFAAIAAgkIAFAAIAAAPIASAAIAAgPIAFAAIAAAkgAM3BxIAAgkIAEAAIAAAkgAMrBxIAAgkIAEAAIAAAkgALwBxIAAgkIAZAAIAAAEIgVAAIAAALIASAAIAAAEIgSAAIAAARgAK6BxIAAgaIAEAAIAAAagAKgBxIAAgRIAAgEQgCgCgDAAIgDAAIgCACIgCADIAAAEIAAAOIgFAAIAAgaIAFAAIAAADIADgDIAFgBQAFAAACAEIABAGIAAARgAJnBxIAAgaIAEAAIAAAagAIwBxIAAgkIAEAAIAAAkgAHQBxIAAgBIAAgDIAAgGQgBgEgDgBIgEgBIgKAAIAAAQIgFAAIAAgkIAQAAQAEAAADABQAFACAAAHQAAADgCACIgDADQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIABAFIAAAFIAAADIACACIAAABgAG+BdIAKAAQAEAAACgBQAAgBABAAQAAAAAAgBQABAAAAgBQAAgBAAgBQAAgEgDgBIgEgBIgLAAgAGcBxIAAgGIAFAAIAAAGgAGPBxIAAgRIAAgEQgCgCgDAAIgCAAIgEACIgBADIgBAEIAAAOIgEAAIAAgaIAEAAIAAADIAFgDIAEgBQAFAAADAEIAAAGIAAARgAE0BxIAAgaIAEAAIAAAEIACgDQABgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIACAAIAAAFIgCAAQgDAAgCACQgCACAAADIAAAPgADmBxIAAgRIgBgEQgCgCgDAAIgCAAIgDACIgCADIAAAEIAAAOIgEAAIAAgaIAEAAIAAADIAEgDIAEgBQAGAAACAEIABAGIAAARgACeBxIAAgRIAAgEQgCgCgDAAIgCAAIgDACIgCADIgBAEIAAAOIgEAAIAAgaIAEAAIAAADIAFgDIAEgBQAFAAACAEIABAGIAAARgABkBxIAAgaIAFAAIAAAagAAuBxIAAgkIAEAAIAAAkgAg2BxIAAgaIAFAAIAAAEIACgDQAAgBABAAQABAAAAAAQABgBAAAAQABAAAAAAIACAAIAAAFIgCAAQgDAAgBACQgCACAAADIAAAPgAhoBxIAAgkIAOAAQAHAAAEAFQAEAFAAAHQAAAGgCAFQgEAIgJAAgAhkBtIAJAAIAEgBQACgBACgDIACgFIABgEQAAgHgDgDQgDgEgFAAIgJAAgAh2BxIAAgRIgTAAIAAARIgFAAIAAgkIAFAAIAAAPIATAAIAAgPIAFAAIAAAkgAipBxIAAgkIAFAAIAAAkgAi1BxIAAgkIAFAAIAAAkgAjvBxIAAgkIAYAAIAAAEIgUAAIAAALIARAAIAAAEIgRAAIAAARgAkoBxIAAgkIAFAAIAAAkgAnuBxIAAgkIAFAAIAAAkgAoVBxIgHgKIgFAKIgGAAIAJgOIgJgMIAGAAIAGAJIAGgJIAGAAIgJAMIAJAOgAowBxIAAgaIAEAAIAAAagApnBxIAAgRIAAgEQgCgCgDAAQgDAAgCACQgDACAAAFIAAAOIgEAAIAAgkIAEAAIAAANIAEgDQABgBADAAQAHAAABAEIABAGIAAARgAsPBxIAAgXIgEAAIAAgDIAEAAIAAgEIABgEQACgDAEAAIABAAIAAAEIgBAAIgCABIgBAGIAEAAIAAADIgEAAIAAAXgAscBxIAAgaIAEAAIAAAagAsoBxIAAgRIgBgEQgBgCgDAAQgDAAgCACQgCACgBAFIAAAOIgEAAIAAgkIAEAAIAAANIADgDQACgBAEAAQAFAAADAEIABAGIAAARgAvABxIAAgkIAEAAIAAAkgAvpBxIAAgRIAAgEQgBgCgEAAIgCAAIgDACIgBADIgBAEIAAAOIgFAAIAAgaIAFAAIAAADIAEgDIAFgBQAFAAACAEIABAGIAAARgAwFBxIAAgRIAAgEQgCgCgDAAQgDAAgCACQgDACAAAFIAAAOIgEAAIAAgkIAEAAIAAANIAEgDQABgBADAAQAHAAABAEIABAGIAAARgAxdBxIAAggIgLAAIAAgEIAdAAIAAAEIgMAAIAAAggAzTBxIAAgRIAAgEQgCgCgDAAIgDAAIgCACIgCADIAAAEIAAAOIgFAAIAAgaIAFAAIAAADIADgDIAFgBQAFAAACAEIABAGIAAARgA0MBxIAAgRIAAgEQgCgCgDAAQgDAAgCACQgCACgBAFIAAAOIgEAAIAAgkIAEAAIAAANIAEgDQACgBACAAQAHAAABAEIABAGIAAARgA0pBxIAAgRIAAgEQgBgCgDAAIgDAAIgDACIgCADIAAAEIAAAOIgEAAIAAgaIAEAAIAAADIAEgDIAFgBQAFAAACAEIABAGIAAARgA1aBxIAAgkIAaAAIAAAEIgWAAIAAALIAUAAIAAAEIgUAAIAAAMIAWAAIAAAFgA10BxIgMgSIgHAFIAAANIgEAAIAAgkIAEAAIAAARIASgRIAIAAIgQAOIAQAWgA2bBxIAAgJIgPAAIAAgEIAQgWIADAAIAAAWIAGAAIAAAEIgGAAIAAAJgA2mBkIALAAIAAgPgA22BWIgDAFIgDgBIAEgFIgFgCIAAgDIAGACIAAgFIADAAIAAAFIAFgCIABADIgGACIAEAFIgDABgAOpBSIAAgFIAFAAIAAAFgAK6BSIAAgFIAEAAIAAAFgAJnBSIAAgFIAEAAIAAAFgABkBSIAAgFIAFAAIAAAFgAowBSIAAgFIAEAAIAAAFgAscBSIAAgFIAEAAIAAAFgAWtg3IgNgXIgOAXIgQAAIAVgiIgUgiIARAAIAMAWIANgWIAPAAIgUAhIAXAjg");
	this.shape.setTransform(166.75,16.575);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A4/D6IAAnzMAx/AAAIAAHzg");
	this.shape_1.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,320,278.3);


(lib.exitBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape.setTransform(10.0158,-275.0171,0.4396,0.5556);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-300,320,50);


(lib.disclaimerBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9B120D").s().p("AhoBmIDPjLQACACAABkIgCBlgAAqAtIAHgFIgIgKIALgEIgCgHIgLADIAAgNIgJAAIAAANIgLgDIgCAHIALAEIgHAKIAGAFIAIgKg");
	this.shape.setTransform(-13.17,-414.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAAAIIgGAKIgHgFIAHgKIgLgDIADgHIAKADIAAgNIAJAAIAAANIAKgDIADAHIgLADIAHAKIgHAFg");
	this.shape_1.setTransform(-9.725,-411.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(4));

	// disclaimerBtn_BG
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.008)").s().p("A5WCTIAAklMAytAAAIAAElg");
	this.shape_2.setTransform(-164.225,-416.75);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-326.5,-431.5,324.6,29.5);


(lib.Shaq_image = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ACNNJQhhgFgBgYQgCgXgLgJIgLgEQgIgBgCgfIAAgeQgEgeglhaIglhUQgxgugbhRQgNgpgEgfQgchDAdhYQAPgsAUgeQARgYAFgdQABhGATgjQAJgSAJgDQADgRAVgVIgJgfQgWgKhPh4QgGgHgbgSQgVgNgSgiQgRggAGgdQAHgdgFgIQgPgZgPg4IgLgzQgOhMBMhRQAngoAogZQAwgdBCAMQAgAFAXAMQApAKAuBRIAmBPQAJgDAPANIAOAOQAAAEBPD3IgpTAIgwABIgwgBg");
	mask.setTransform(0.9982,-7.1528);

	// Layer_2
	this.instance = new lib.shaq_endFrame();
	this.instance.setTransform(-27.55,-92);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Shaq_image, new cjs.Rectangle(-26.7,-91.3,45.2,165.3), null);


(lib.shaq_frame_07_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("AnyFvQgVgRAAgfIA7AAQAAAMAJAHIAJAFIALACQATAAAIgMQAIgMAAgTIAAgfIgCAAQgJANgNAIQgPAIgOAAQgkAAgSgcQgTgbAAhCIADgqQABgWAJgRQAIgSAOgLQAPgLAZAAQAMAAAPAHQANAIAJARIACAAIAAgaIA6AAIAADjQAAAugXAXQgXAXg1AAQgoAAgVgQgAm9BtQgHAFgCALQgFAJgBARIAABAQABAKAEAKQADAIAGAFQAGAFAJAAQALAAAGgFQAGgFAEgJQADgJADgMIACgcQAAgrgIgTQgGgSgTAAQgKAAgGAEgAK2EpQgTgLgJgSQgIgTgDgWIgCgtQAAgZAEgWQACgWALgRQAKgRATgLQASgKAfAAQAaAAASAJQARAIAKAQQAJAQAFAWQACAXAAAbIAAAOIh5AAIACAoIAGARQACAIAGAFQAGAFAJAAQAQAAAHgMQAGgKADgXIA4AAQgDAqgVAVQgUAWgsAAQghAAgSgLgALbBoQgHAEgCAHIgGAQIgCAQIAAAKIA/AAIgCgYQgBgLgEgHQgCgHgHgFQgGgDgJAAQgKAAgFAEgAHmEpQgTgLgJgSQgJgTgCgWIgCgtQAAgZADgWQAEgWAKgRQAKgRASgLQATgKAgAAQAaAAAQAJQASAIAKAQQAJAQAEAWQAEAXAAAbIAAAOIh6AAIACAoIAFARQAEAIAGAFQAGAFAHAAQARAAAGgMQAHgKADgXIA3AAQgCAqgVAVQgUAWgsAAQghAAgSgLgAILBoQgGAEgEAHIgFAQIgCAQIAAAKIA/AAIgCgYIgEgSQgEgHgGgFQgGgDgJAAQgJAAgGAEgACWEuQgRgFgMgOQgLgPgGgYQgGgZAAgjQAAglAHgYQAIgYAMgPQAOgOARgGQASgGAWAAQAqAAAWAZQAUAZAAAqIg6AAIgBgRIgEgPQgDgHgFgEQgGgFgIAAQgLAAgHAGQgIAFgDAKQgEAKAAAPIAABKQAAAQAEAKQADAKAHAFQAGAFAKAAQAQAAAHgOQAHgNAAgdIA6AAQAAAvgUAYQgWAZgwAAQgXAAgRgGgAgzEvQgRgEgJgLQgKgKgFgNQgEgOAAgRIAAgJIA3AAIAAAIQAAAPAIAKQAJAKAPAAQAOAAAIgIQAJgHAAgOQAAgLgHgGQgHgGgIgEIgrgQQgZgIgNgQQgMgRAAgZQAAgPAEgNQAFgNAKgKQALgJARgGQARgGAXAAQAoAAAUASQAVASAAAgIAAAKIg3AAQAAgTgGgJQgGgIgOAAQgLAAgKAHQgIAGAAAMQAAAKAGAHQAFAHAPAFIAkAMQAeAKAMAPQALAQAAAbQAAATgHAOQgGAPgMAIQgMAKgQAEQgQAEgSAAQgbAAgRgFgAkXEuQgLgFgHgKQgGgKgDgMQgDgMAAgMQAAgRADgMQAEgMAHgJQAIgIALgGIAbgLIAigJQAOgDAGgHQAFgGAAgMQAAgOgHgHQgGgIgQAAQgOAAgGAIQgIAJAAAOIAAAGIg3AAIAAgGQAAgUAGgPQAIgNALgJQALgIAQgEQAPgEARAAQAbAAARAFQARAFAKALQAJAKAEANQADANAAAQIABCYIAGAUIg6AAIgIgZIgBAAQgKATgOAFQgOAGgWAAQgRAAgLgGgAjLC/IgNAEQgTAFgIAJQgHAJAAAQQAAAOAFAKQAFAKANAAIAMgDQAGgBAGgFQAGgFAEgGQADgHAAgLIAAgugAqzEpQgSgLgJgSQgJgTgCgWIgCgtQAAgZADgWQADgWAKgRQAKgRATgLQATgKAfAAQAaAAARAJQARAIALAQQAJAQAEAWQADAXAAAbIAAAOIh5AAIABAoIAGARQADAIAGAFQAGAFAIAAQAQAAAHgMQAHgKADgXIA3AAQgCAqgVAVQgUAWgsAAQghAAgTgLgAqNBoQgHAEgDAHIgGAQIgBAaIA/AAIgCgYQgCgLgDgHQgDgHgGgFQgGgDgJAAQgKAAgFAEgAPYEvIAAilQAAgTgGgGQgGgIgOAAQggAAAAAoIAACeIg+AAIAAjvIA7AAIAAAcIABAAQAKgSAPgHQAPgJAUAAQAdAAARAQQAPAQAAAkIAACxgAE1EvIAAjvIA7AAIAAAgIABAAQAJgRANgLQAOgKATAAIAMABIAAA7IgUgBIgQACQgIACgHAFQgGAFgEAIQgEAJAAAMIAACPgAs2EvIAAj9IAAAAIg5D9IgyAAIg4j9IAAD9Ig7AAIAAk8IBfAAIAtDfIABAAIAujfIBeAAIAAE8gAFlg+QgRgGgLgOQgMgPgFgYQgGgYAAgkQAAglAHgYQAHgYANgPQANgOARgGQASgFAWAAQAqAAAWAYQAWAYAAArIg7AAIgBgQIgEgQQgDgGgGgFQgEgFgKAAQgLAAgHAFQgGAFgFALQgDAKgBAPIAABLQABAPADAKQAFAKAGAFQAGAFAKAAQAPAAAIgNQAHgPAAgcIA7AAQAAAvgWAYQgVAZgxAAQgXAAgRgFgAlYhAQgUgIgKgSQgMgSgEgdQgGgdAAgqIADg/QADgfAJgWQAJgYAUgOQAUgOAjAAQAdAAATAIQATAJALASQALASAFAdQAFAdAAApIgDBAQgCAegKAXQgJAXgUAOQgUANgjAAQgdAAgSgHgAk6lJQgGAFgEANQgEAMgCATIAACGQACATAEALQAEAKAGAFQAGAEALAAQALAAAGgFQAHgFAEgMQAEgNACgVIAAiFQgCgTgEgLQgFgKgGgEQgGgEgLAAQgLAAgGAFgAKAg9IAAimQAAgTgGgHQgGgGgPAAQggAAAAAnIAACfIg9AAIAAk9IA9AAIAABmIABAAQASgeAoAAQAeAAAQAPQAPAQAAAkIAACygADYg9IAAimQAAgTgHgHQgGgGgNAAQghAAAAAnIAACfIg9AAIAAjvIA7AAIAAAbIABAAQAJgRAPgJQAQgHAUAAQAdAAARAPQAPAQAAAkIAACygAgEg9IAAjvIA9AAIAADvgApkg9QAAgWAFgSQAEgSAJgRQAIgQAOgPQANgQARgQIArgqIAKgQQAEgIABgJIAAgVQAAgngeAAQgMAAgIAFQgGAFgEAIQgEAIgBAMIgBAXIg+AAIAAgMQAAgsAYgXQAYgYAzAAQAvAAAXAWQAYAWAAAqQAAAOgEAOQgCANgGAMQgGAMgJAMIg6A3QgOAOgIAMQgIAMgCAIIB2AAIAAAzgArmg9IAAjeIg/AAIAAgrIAGAAQAfAAATgMQATgLAFgbIAuAAIAAE7gAiuikIAAg1IB9AAIAAA1gAgElKIAAg0IA9AAIAAA0g");
	this.shape.setTransform(-376.5649,-257.9985,1.0804,1.0804);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shaq_frame_07_txt, new cjs.Rectangle(-489.5,-299.4,605.8,222.29999999999998), null);


(lib.shaq_frame_07_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.shaq_frame_07();
	this.instance.setTransform(-214.75,-92.45,2.6385,2.6385);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shaq_frame_07_1, new cjs.Rectangle(-214.7,-92.4,366.7,131.9), null);


(lib.shaq_frame_06_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("AdoLWIAAg9IAxAAIAAA9gAIzBVIAAkNIAyAAIAAAWQAKgOAJgGQAMgHAPAAQAiAAAOAZQAPAaAAA5QAAA5gPAYQgOAYgiAAQgPAAgJgFQgLgHgJgLIAABUgAJtiEQgGASAAAhQAAAgAGASQADARASAAQARAAAFgRQAGgSAAggQAAghgGgSQgFgRgRAAQgSAAgDARgAbMAOQgPgJgIgPQgIgOgCgUIgCgnQAAgUAEgUQADgUAIgNQAIgQARgIQARgJAZAAQAWAAAPAHQAPAHAIAOQAKANACAVQACASAAAYIAAALIhnAAIAAAiIAGAQQADAFAFAFQAEAEAIAAQAOAAAGgJQAFgKACgUIAwAAQgCAlgRARQgRATgnAAQgcAAgQgKgAbsiVQgFADgDAGIgGANIAAAWIA1AAIgCgTQAAgLgDgGQgCgHgGgCQgEgDgIAAQgJAAgFAEgAYiATQgOgFgKgMQgJgMgFgUQgHgUAAgfQAAggAIgWQAFgUAMgLQALgMAPgGQAOgFATAAQAkAAASAVQAUAWAAAjIgzAAIAAgNIgEgNQgDgHgFgEQgEgEgHAAQgKAAgGAGQgFADgDAIQgEALgCALIAABAQACANAEAIQADAJAFAFQAFAEAJAAQANAAAGgMQAGgKAAgaIAzAAQAAAngUAVQgRAWgpAAQgUAAgPgFgASkAOQgRgJgIgPQgGgOgBgUIgDgnQAAgUADgUQADgUAIgNQAIgQARgIQAQgJAaAAQAXAAAPAHQAPAHAHAOQAJANADAVQADASAAAYIAAALIhoAAIACAiIAFAQQACAFAGAFQAEAEAHAAQANAAAHgJQAFgKACgUIAwAAQgCAlgRARQgSATgmAAQgbAAgQgKgATEiVQgGADgCAGIgFANIgCAWIA1AAIgBgTQgBgLgDgGQgCgHgGgCQgEgDgIAAQgIAAgFAEgAMQAOQgQgJgJgPQgGgOgDgUIgBgnQAAgUACgUQAEgUAHgNQAJgQARgIQAQgJAbAAQAWAAAOAHQAQAHAIAOQAIANACAVQAEASAAAYIAAALIhpAAIACAiIAEAQIAIAKQAGAEAGAAQAOAAAGgJQAGgKADgUIAuAAQgBAlgRARQgSATglAAQgdAAgPgKgAMuiVQgEADgEAGIgEANIgCAWIA3AAIgCgTIgDgRQgEgHgEgCQgGgDgIAAQgHAAgHAEgADnAOQgQgJgIgPQgHgOgBgUIgCgnQAAgUACgUQAEgUAIgNQAIgQAQgIQARgJAaAAQAXAAAPAHQAOAHAIAOQAJANADAVQADASAAAYIAAALIhnAAIAAAiIAFAQQADAFAFAFQAEAEAHAAQAPAAAFgJQAFgKADgUIAwAAQgDAlgRARQgRATgmAAQgcAAgQgKgAEHiVQgFADgDAGIgFANIAAAWIA0AAIgBgTIgEgRQgDgHgFgCQgFgDgIAAQgIAAgFAEgAjqATQgRgHgJgMQgIgOgEgWQgEgUAAgZQAAgaAEgUQAEgVAJgNQAJgOARgHQAOgHAXAAQAYAAAQAHQAPAGAJAOQAIANAFAUQAEAUAAAcQAAAZgEAUQgFAUgJAOQgKANgPAGQgPAHgXAAQgXAAgPgFgAjSiUQgGAFgDAKQgCAJgBANIAAA6QABANACAKQADAKAGAEQAEAGAKAAQAQAAAHgSQAFgPAAgmQAAgmgFgSQgHgQgQAAQgKAAgEAFgAn6AUQgQgEgIgKQgIgGgFgLQgCgNAAgQIAAgGIAvAAIAAAGQAAAOAGAHQAIAJAMAAQANAAAIgGQAGgGAAgMQAAgKgGgFQgEgFgIgDIgmgNQgVgIgLgOQgLgOAAgVQAAgNAFgMQAEgKAJgIQAJgIAOgGQAOgFAUAAQAlAAARAOQAQARAAAbIAAAIIgvAAQAAgPgFgHQgEgIgOAAQgLAAgGAFQgIAFAAALQAAAIAFAGQAFAGAMAFIAhAKQAYAIAKAOQALANAAAYQAAAQgHAMQgFALgJAIQgLAIgNADQgPAEgQAAQgXAAgNgEgAu9AOQgQgJgIgPQgGgOgCgUIgDgnQAAgUAFgUQACgUAIgNQAIgQAQgIQASgJAZAAQAWAAAQAHQAOAHAIAOQAKANACAVQADASAAAYIAAALIhnAAIAAAiIAEAQIAJAKQAEAEAIAAQANAAAGgJQAGgKACgUIAwAAQgCAlgRARQgRATgnAAQgcAAgQgKgAudiVQgFADgEAGIgEANIAAAWIA0AAIgCgTQAAgLgEgGQgCgHgGgCQgDgDgJAAQgIAAgFAEgAzPAOQgQgJgIgPQgHgOgBgUIgDgnQAAgUADgUQAEgUAIgNQAIgQAPgIQARgJAbAAQAWAAAQAHQANAHAJAOQAIANADAVQAEASAAAYIAAALIhnAAIAAAiIAEAQIAJAKQADAEAJAAQANAAAGgJQAFgKADgUIAvAAQAAAlgUARQgRATglAAQgcAAgQgKgAyviVQgFADgEAGIgEANIAAAWIA0AAIgCgTQgBgLgDgGQgCgHgGgCQgDgDgJAAQgIAAgFAEgAWjAUIAAiLQAAgRgFgHQgGgGgMAAQgcAAAAAjIAACGIg0AAIAAjMIAzAAIAAAYQAIgPANgHQAOgHARAAQAaAAANANQANAPAAAeIAACXgAQrAUIAAjMIA2AAIAADMgAOoAUIAAjMIA0AAIAAAcQAHgOALgKQAMgJAPAAIAGAAIAEACIAAAxIgQgCIgOADQgHABgHAFQgEAFgDAHQgEAGAAAKIAAB7gAHkAUIgdhCIgfBCIg4AAIA4hpIg0hjIA1AAIAeA9IAag9IA4AAIg1BjIA2BpgAASAUIAAiLQAAgRgFgHQgFgGgLAAQgcAAAAAjIAACGIg0AAIAAjMIAzAAIAAAYQAHgPAOgHQAMgHARAAQAZAAAOANQAOAPAAAeIAACXgAlsAUIAAjMIA3AAIAADMgAp2AUIAAjMIA1AAIAADMgAr/AUIg1jMIA2AAIAfCTIAbiTIA1AAIgyDMgAw1AUIAAkOIA1AAIAAEOgA11AUIAAjiIg9AAIAAgsICvAAIAAAsIg7AAIAADigA5OAUIg4hwIgVAfIAABRIg2AAIAAkOIA2AAIAABrIACAAIBFhrIA6AAIhJBzIBSCbgA84AUIAAg4IhgAAIAAgsIBaipIA4AAIAACrIAaAAIAAAqIgaAAIAAA4gA9uhOIA2AAIAAhmIgBAAgAQrjRIAAgsIA2AAIAAAsgAlsjRIAAgsIA3AAIAAAsgAp2jRIAAgsIA1AAIAAAsgAjokyIAAhoIgBAAQgKAPgMAHQgOAFgRAAQgpAAgSgdQgSgfAAhGQAAhGASgfQASgfApAAQAUAAAMAIQAOAIALARIAAAAIAAgbIA+AAIAAFNgAklo/QgGAVAAApQAAApAGAVQAHAVAVAAQAWAAAGgVQAFgVAAgpQAAgpgFgVQgGgUgWAAQgVAAgHAUgAq/kyIAAlNIA+AAIAAAbIABAAQALgRANgIQANgIATAAQAoAAASAfQAUAfAABGQAABGgUAfQgSAdgoAAQgSAAgNgFQgMgHgKgPIgCAAIAABogAp5o/QgGAVAAApQAAApAGAVQAHAVAVAAQAVAAAHgVQAHgVAAgpQAAgpgHgVQgHgUgVAAQgVAAgHAUgAJPmFQgTgIgLgRQgLgQgFgZQgFgZAAghQAAggAFgZQAFgZAMgQQAMgRATgIQATgJAbAAQAdgBATAJQATAIALARQAMARAFAYQAEAYAAAiQAAAhgFAYQgFAZgLAQQgNASgSAHQgTAHgcAAIgJAAQgXAAgQgGgAJspTQgGAHgEALQgDANgCAQIAABHQACAQADAMQAEAMAGAGQAHAGAMAAQAUAAAHgUQAIgUAAgwQAAgvgIgVQgHgUgUAAQgMAAgHAGgAEKmDQgSgGgKgJQgLgKgEgPQgFgQAAgRIAAgJIA7AAIAAAIQAAAQAJAKQAIAKAQAAQAPAAAJgHQAJgIAAgOQAAgNgHgGQgHgGgJgEIgtgQQgbgJgOgRQgOgRAAgcQAAgPAGgOQAEgNAMgKQALgLASgHQARgFAaAAQArAAAVATQAVATAAAhIAAALIg5AAQAAgUgHgKQgHgIgPAAQgNAAgJAGQgJAHAAANQAAALAGAHQAGAHAQAFIAoANQAeAKAMARQANARAAAcQAAAUgHAPQgHAPgMAKQgNAKgSAEQgQADgVAAQgbAAgSgEgAODmDIAAitQAAgUgHgIQgGgHgPAAQgiAAAAApIAACnIhBAAIAAj8IA+AAIAAAdIABAAQAKgSARgIQAQgJAVAAQAfAAARARQAQAQAAAmIAAC7gAG3mDIAAj8IBBAAIAAD8gAB4mDIAAj8IBBAAIAAD8gAhDmDIhNlOIBIAAIAvD2IACAAIAwj2IBGAAIhNFOgAnTmDIAAj8IBBAAIAAD8gAudmDIAAlOIC6AAIAAA3Ih3AAIAABOIBwAAIAAA4IhwAAIAABZIB7AAIAAA4gAG3qeIAAg3IBBAAIAAA3gAB4qeIAAg3IBBAAIAAA3gAnTqeIAAg3IBBAAIAAA3g");
	this.shape.setTransform(-402.575,-101.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shaq_frame_06_txt, new cjs.Rectangle(-597.1,-173.8,715.4,154.3), null);


(lib.Shaq_frame_06 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A9nNjIAA7FMA7PAAAIAAbFg");
	mask.setTransform(-20,19.475);

	// Layer_2
	this.instance = new lib.shaq_frame_05();
	this.instance.setTransform(-210.2,-50.65,2.6167,2.6167);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Shaq_frame_06, new cjs.Rectangle(-209.6,-50.6,363.1,130.8), null);


(lib.shaq_frame_05_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("ABeDLIAAk/IA8AAIAAAaIABAAQAKgSANgHQANgIATAAQAmAAASAeQASAeAABDQAABEgSAdQgSAdgmAAQgSAAgMgGQgMgHgKgOIgBAAIAABkgACjg3QgGAUAAAnQAAAoAGAUQAGAUAVAAQAUAAAGgUQAGgUAAgoQAAgngGgUQgGgUgUAAQgVAAgGAUgAmZB8QgTgIgLgQQgLgQgEgYQgFgZAAgfQAAgeAFgYQAFgYAMgQQALgQASgIQASgJAbAAQAcAAASAIQATAIALAQQALAQAEAYQAFAYAAAfQAAAfgFAYQgFAYgMAQQgLAQgSAIQgTAHgaAAIgDAAQgaAAgRgGgAl9hKQgHAGgDAMQgEALgBAQIAABDQABAQAEALQADAMAHAGQAHAGALAAQATAAAHgUQAHgTAAguQAAgsgHgVQgHgTgTAAQgLAAgHAGgAHaB9QgRgGgMgPQgLgOgGgZQgGgYAAglQAAgkAHgZQAIgZANgOQANgPASgGQASgGAWAAQArAAAWAaQAWAZAAArIg8AAIgBgRIgEgQQgDgHgGgEQgFgFgJAAQgLAAgHAGQgHAFgEAKQgEAKgBAQIAABKQABAQAEAKQAEALAGAFQAHAEAKAAQAQAAAHgNQAHgOAAgeIA8AAQAAAwgWAZQgVAZgyAAQgXAAgSgFgAqRB4QgSgKgLgWQgLgWgEgfQgDggAAgpQAAgpAFgfQAFgeANgVQANgUAUgLQAVgKAfAAQA1AAAYAbQAXAaAAAxIg+AAIgCgTQgCgJgEgIQgFgIgHgFQgHgFgKAAQgXAAgLAaQgKAaAAA9IACAzQABAXAFARQAFAQAJAJQAJAJAOAAQAFAAAHgDQAIgDAFgHQAHgGAEgKQAEgJAAgOIAAggIgrAAIAAgvIBpAAIAACsIgwAAIAAgdIgBAAQgMATgQAIQgQAHgXAAQgeAAgTgKgAKFB9IAAhGIA8AAIAABGgAFEB9IAAjxIA+AAIAADxgAh5B9IAAlBICzAAIAAA2IhyAAIAABLIBrAAIAAA1IhrAAIAABWIB2AAIAAA1gAFEiSIAAg1IA+AAIAAA1g");
	this.shape.setTransform(-190.7566,233.5756,1.8048,1.8048);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shaq_frame_05_txt, new cjs.Rectangle(-317.9,-64.6,444.59999999999997,334.9), null);


(lib.Shaq_frame_05 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// shaq_image
	this.instance = new lib.shaq_frame_04();
	this.instance.setTransform(-150,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(40).to({_off:true},1).wait(34));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-125,300,265);


(lib.shaq_frame_02_txt_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("AgZAfIAAg9IA0AAIAAA9g");
	this.shape.setTransform(-39.95,233.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353534").s().p("AgaCPIAAkdIA1AAIAAEdg");
	this.shape_1.setTransform(-50,222.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353534").s().p("AgbCPIAAkdIA2AAIAAEdg");
	this.shape_2.setTransform(-60.05,222.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353534").s().p("Ag3BrQgKgFgGgIQgGgJgDgLQgDgLAAgLQAAgPAEgLQADgLAGgIQAHgHAKgFQAKgFAPgEIAegIQAMgEAFgFQAFgGAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAIQgGAHAAAMIAAAHIgyAAIAAgGQAAgSAGgMQAGgNAKgIQALgIAOgEQANgCAQAAQAYAAAPAEQAPAFAIAJQAJAJADALQADANAAAOIAABxIABAXIAGASIg1AAIgEgLIgDgLIgBAAQgJAQgNAFQgMAGgTAAQgPAAgKgGgAAMAHIgMAEQgPAEgHAIQgIAJAAAOQAAANAFAIQAFAJALAAIALgCQAGgCAFgEQAFgDADgHQADgHAAgIIAAgrg");
	this.shape_3.setTransform(-75.025,225.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353534").s().p("ABOBuIAAiVQAAgOgFgHQgFgHgMAAQgNAAgIAJQgHAJAAATIAACMIg3AAIAAiVQAAgOgFgHQgFgHgLAAQgNAAgIAJQgIAJAAATIAACMIg3AAIAAjWIA1AAIAAAWIAAAAQALgPANgGQANgGASAAQATAAAMAIQANAJAEARIABAAQAGgRAPgJQAOgIAUAAQAbAAANAQQANARAAAfIAACbg");
	this.shape_4.setTransform(-100.075,225.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353534").s().p("AgmBsQgPgEgJgJQgJgJgEgMQgEgNAAgQIAAgHIAyAAIAAAGQAAAPAHAJQAIAIAOAAQAMAAAHgHQAIgFAAgOQAAgKgGgGQgGgEgIgEIgmgOQgXgIgLgOQgMgOAAgXQAAgNAEgMQAFgMAKgJQAJgIAPgGQAPgEAUAAQAmAAASAPQASAQAAAeIAAAIIgyAAQAAgRgFgHQgGgIgNAAQgJAAgIAGQgIAFAAAMQAAAIAFAGQAFAHAOAEIAgAMQAaAIALANQALAOAAAZQAAARgGANQgGAMgLAJQgLAIgOAEQgPADgRABQgXgBgPgEg");
	this.shape_5.setTransform(-124.575,225.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353534").s().p("AgoBqQgQgGgKgOQgKgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOAQgHQAQgHAXAAQAZgBAQAHQARAHAKAOQAJAPAEAVQAEAVAAAcQAAAbgFAVQgEAWgKAOQgKAOgQAHQgQAHgYAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIgBAeIABAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAHgSAAgoQAAgogHgRQgGgSgRAAQgJAAgGAGg");
	this.shape_6.setTransform(-153.55,225.7954);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353534").s().p("AgoBqQgRgGgJgOQgKgOgEgWQgEgVAAgcQAAgbAEgVQAFgVAKgPQAKgOARgHQAQgHAWAAQAYgBARAHQAQAHALAOQAJAPAEAVQAEAVAAAcQAAAbgFAVQgEAWgKAOQgKAOgRAHQgQAHgXAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIAAAeIAAAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAHgSgBgoQABgogHgRQgGgSgRAAQgJAAgGAGg");
	this.shape_7.setTransform(-173.2,225.7954);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353534").s().p("AgECJQgKgCgFgHQgFgHgCgKQgCgLAAgRIAAh5IgcAAIAAgmIAcAAIAAg+IA2AAIAAA+IAfAAIAAAmIgfAAIAABzQAAANADAFQAEAGAMgBIAHAAIAFgBIAAAnIgRAAIgTABQgQAAgJgCg");
	this.shape_8.setTransform(-189.05,222.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353534").s().p("AgDCJQgLgCgFgHQgGgHgCgKQgBgLAAgRIAAh5IgcAAIAAgmIAcAAIAAg+IA1AAIAAA+IAhAAIAAAmIghAAIAABzQAAANAEAFQAEAGAMgBIAHAAIAGgBIAAAnIgSAAIgSABQgRAAgIgCg");
	this.shape_9.setTransform(-211.35,222.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353534").s().p("AhCBgQgPgOAAggIAAifIA3AAIAACTQABARAFAHQAGAHAMAAQAcAAAAgkIAAiOIA3AAIAADWIg0AAIAAgZIgBAAQgJAQgOAHQgNAHgSAAQgaAAgOgOg");
	this.shape_10.setTransform(-227.8,226.075);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353534").s().p("AgoBqQgRgGgKgOQgJgOgEgWQgEgVAAgcQAAgbAFgVQAEgVAKgPQAKgOAQgHQAQgHAXAAQAYgBARAHQAQAHAKAOQAKAPAEAVQAEAVAAAcQAAAbgEAVQgFAWgKAOQgKAOgRAHQgPAHgYAAIgCAAQgXAAgPgHgAgPhEQgGAFgDAKQgDAKgBAOIgBAeIABAeQABAOADAKQADAKAGAGQAGAFAJAAQARAAAGgRQAGgSABgoQgBgogGgRQgGgSgRAAQgJAAgGAGg");
	this.shape_11.setTransform(-247.85,225.7954);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353534").s().p("AgECJQgKgCgFgHQgFgHgCgKQgCgLAAgRIAAh5IgdAAIAAgmIAdAAIAAg+IA2AAIAAA+IAfAAIAAAmIgfAAIAABzQAAANADAFQAEAGANgBIAGAAIAFgBIAAAnIgRAAIgTABQgPAAgKgCg");
	this.shape_12.setTransform(-273.75,222.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353534").s().p("Ag3BrQgKgFgGgIQgGgJgDgLQgDgLAAgLQAAgPAEgLQADgLAGgIQAHgHAKgFQAKgFAPgEIAegIQAMgEAFgFQAFgGAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAIQgGAHAAAMIAAAHIgyAAIAAgGQAAgSAGgMQAGgNAKgIQALgIAOgEQANgCAQAAQAYAAAPAEQAPAFAIAJQAJAJADALQADANAAAOIAABxIABAXIAGASIg1AAIgEgLIgDgLIgBAAQgJAQgNAFQgMAGgTAAQgPAAgKgGgAAMAHIgMAEQgPAEgHAIQgIAJAAAOQAAANAFAIQAFAJALAAIALgCQAGgCAFgEQAFgDADgHQADgHAAgIIAAgrg");
	this.shape_13.setTransform(-289.925,225.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353534").s().p("AgbCPIAAkdIA3AAIAAEdg");
	this.shape_14.setTransform(-304.65,222.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353534").s().p("AgdCSIAAixIgcAAIAAgmIAcAAIAAgYQABgPAEgJQAEgLAGgFQAIgGAKgDQALgCANAAIAdABIAAAmIgFAAIgFAAQgMABgFADQgEAEAAAKIAAASIAfAAIAAAmIgfAAIAACxg");
	this.shape_15.setTransform(-315.7,222.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353534").s().p("AgmBsQgPgEgJgJQgJgJgEgMQgEgNAAgQIAAgHIAyAAIAAAGQAAAPAHAJQAIAIAOAAQAMAAAHgHQAIgFAAgOQAAgKgGgGQgGgEgIgEIgmgOQgXgIgLgOQgMgOAAgXQAAgNAEgMQAFgMAKgJQAJgIAPgGQAPgEAUAAQAmAAASAPQASAQAAAeIAAAIIgyAAQAAgRgFgHQgGgIgNAAQgJAAgIAGQgIAFAAAMQAAAIAFAGQAFAHAOAEIAgAMQAaAIALANQALAOAAAZQAAARgGANQgGAMgLAJQgLAIgOAEQgPADgRABQgXgBgPgEg");
	this.shape_16.setTransform(-341.075,225.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353534").s().p("AgaCRIAAjXIA2AAIAADXgAgahgIAAgvIA2AAIAAAvg");
	this.shape_17.setTransform(-355.2,222.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shaq_frame_02_txt_02, new cjs.Rectangle(-362,196.2,329.5,51.30000000000001), null);


(lib.shaq_frame_01_txt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("AgkCPIhCkdIA+AAIAoDSIABAAIAqjSIA8AAIhCEdg");
	this.shape.setTransform(-66.375,210.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353534").s().p("AgcCPIAAjuIg+AAIAAgvIC1AAIAAAvIg+AAIAADug");
	this.shape_1.setTransform(-86.75,210.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353534").s().p("AgbCPIAAkdIA2AAIAAEdg");
	this.shape_2.setTransform(-111.55,210.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353534").s().p("AgtBmQgRgJgIgRQgIgQgCgVIgBgnQAAgWADgUQADgVAJgPQAJgPAQgKQARgIAbgBQAYAAAQAIQAPAHAJAPQAJAOADAVQADATAAAaIAAALIhsAAIAAARIABATIAFAQQADAGAFAFQAFAEAHAAQAOAAAHgKQAGgKACgUIAyAAQgCAlgSAUQgTATgnAAQgdAAgRgKgAgLhHQgGAFgDAFIgFAPIgBAOIAAAJIA3AAIgBgVQgCgKgDgHQgCgGgGgEQgFgDgJAAQgHAAgFADg");
	this.shape_3.setTransform(-125.975,214.15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353534").s().p("AAaBuIAAiTQABgRgHgHQgFgGgNAAQgcAAAAAjIAACOIg3AAIAAjWIA1AAIAAAZIABAAQAJgQAOgHQANgHASAAQAaAAAPAOQAOAOgBAhIAACeg");
	this.shape_4.setTransform(-145.65,213.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353534").s().p("Ag3BsQgKgFgGgKQgGgIgDgLQgDgLAAgLQAAgQAEgKQADgLAGgIQAHgHAKgFQAKgFAPgEIAegJQAMgDAFgGQAFgFAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAHQgGAIAAANIAAAGIgyAAIAAgFQAAgTAGgNQAGgNAKgHQALgIAOgDQANgDAQgBQAYAAAPAFQAPAFAIAIQAJAKADAMQADAMAAAOIAABwIABAYIAGASIg1AAIgEgLIgDgMIgBAAQgJASgNAFQgMAEgTAAQgPAAgKgEgAAMAIIgMADQgPAEgHAIQgIAIAAAPQAAAMAFAJQAFAJALAAIALgCQAGgBAFgEQAFgFADgGQADgHAAgIIAAgrg");
	this.shape_5.setTransform(-165.775,214.15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353534").s().p("AhTCRIAAkbIA1AAIAAAWIAAAAQAKgPALgHQALgGAQAAQAiAAAQAbQAQAaAAA8QAAA7gQAaQgQAagiAAQgPAAgKgGQgLgFgJgNIgBAAIAABZgAgWhUQgGASAAAjQAAAiAGASQAFASARAAQASAAAFgSQAGgSAAgiQAAgjgGgSQgFgSgSAAQgRAAgFASg");
	this.shape_6.setTransform(-185.4,217.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353534").s().p("AgECJQgKgCgFgHQgGgGgBgLQgDgLAAgQIAAh7IgcAAIAAglIAcAAIAAg+IA2AAIAAA+IAgAAIAAAlIggAAIAAB0QABAMAEAGQADAFANABIAFgBIAGAAIAAAmIgRAAIgTABQgPAAgKgCg");
	this.shape_7.setTransform(-211.85,211.15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353534").s().p("Ag3BsQgKgFgGgKQgGgIgDgLQgDgLAAgLQAAgQAEgKQADgLAGgIQAHgHAKgFQAKgFAPgEIAegJQAMgDAFgGQAFgFAAgLQAAgMgGgHQgGgHgNAAQgMAAgHAHQgGAIAAANIAAAGIgyAAIAAgFQAAgTAGgNQAGgNAKgHQALgIAOgDQANgDAQgBQAYAAAPAFQAPAFAIAIQAJAKADAMQADAMAAAOIAABwIABAYIAGASIg1AAIgEgLIgDgMIgBAAQgJASgNAFQgMAEgTAAQgPAAgKgEgAAMAIIgMADQgPAEgHAIQgIAIAAAPQAAAMAFAJQAFAJALAAIALgCQAGgBAFgEQAFgFADgGQADgHAAgIIAAgrg");
	this.shape_8.setTransform(-227.975,214.15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353534").s().p("AgbCPIAAkdIA2AAIAAEdg");
	this.shape_9.setTransform(-242.65,210.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353534").s().p("AgcCRIAAiwIgcAAIAAglIAcAAIAAgZQAAgOADgLQAFgJAHgHQAHgFAKgDQALgCANgBIAeABIAAAoIgGAAIgFAAQgMAAgEADQgGAFAAAIIAAAUIAhAAIAAAlIghAAIAACwg");
	this.shape_10.setTransform(-253.65,210.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353534").s().p("AgmBsQgPgEgJgKQgJgIgEgNQgEgMAAgQIAAgIIAyAAIAAAIQAAAOAHAIQAIAJAOAAQAMAAAHgGQAIgHAAgMQAAgLgGgFQgGgFgIgEIgmgOQgXgIgLgNQgMgPAAgXQAAgNAEgMQAFgMAKgIQAJgKAPgFQAPgEAUgBQAmABASAPQASAQAAAdIAAAJIgyAAQAAgRgFgIQgGgHgNAAQgJAAgIAFQgIAHAAALQAAAIAFAHQAFAFAOAFIAgALQAaAJALAOQALAOAAAYQAAARgGANQgGANgLAIQgLAIgOAEQgPADgRAAQgXABgPgFg");
	this.shape_11.setTransform(-278.925,214.15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353534").s().p("AgaCQIAAjVIA1AAIAADVgAgahgIAAgwIA1AAIAAAwg");
	this.shape_12.setTransform(-293,210.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353534").s().p("AAaCPIAAiUQABgQgHgHQgFgHgNAAQgcAAAAAjIAACPIg3AAIAAkdIA3AAIAABdIABAAQAQgcAkAAQAaAAAPAOQAOAPgBAgIAACfg");
	this.shape_13.setTransform(-308.2,210.675);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353534").s().p("AgcCPIAAjuIg+AAIAAgvIC1AAIAAAvIg+AAIAADug");
	this.shape_14.setTransform(-328.2,210.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shaq_frame_01_txt, new cjs.Rectangle(-339.8,184.5,286.40000000000003,51.30000000000001), null);


(lib.Shaq_frame_01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// shaq_image
	this.instance = new lib.shaq_frame_01();
	this.instance.setTransform(-150,-163);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(75));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-163,300,265);


(lib.image_group_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_group();
	this.instance.setTransform(-323,-242.3,1.8172,0.9037);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_group_1, new cjs.Rectangle(-323,-242.3,545.2,196.10000000000002), null);


(lib.Frame_10_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.endFrame_screen_02();
	this.instance.setTransform(-357.5,20.2,4.8619,4.8619);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Frame_10_02, new cjs.Rectangle(-357.5,20.2,675.8,243.10000000000002), null);


(lib.Frame_10_01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.endFrame_screen_01();
	this.instance.setTransform(-383.2,8.75,4.9249,4.9249);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Frame_10_01, new cjs.Rectangle(-383.2,8.8,684.5999999999999,246.2), null);


(lib.Epson_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AkIBHIAAiNIIRAAIAACNg");
	mask.setTransform(-44.725,-31.625);

	// Layer_2
	this.instance = new lib.epson_logo();
	this.instance.setTransform(-70.05,-37,0.4151,0.4151);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Epson_logo, new cjs.Rectangle(-70,-37,49.8,12.5), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHlA8QgRgRAAgXIAAhYQAAgFAEAAIAUAAQAEAAAAAFIAABWQAAAOAIAIQAIAJAOAAQAOAAAJgJQAIgIAAgOIAAhWQAAgFAEAAIAUAAQAEAAAAAFIAABYQAAAXgRARQgRAPgZABQgZgBgQgPgAE3A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAgABAWAVQAWAXABAeQgBAggWAVQgWAXggAAQgfAAgWgXgAFLghQgOAOgBATQABAUAOAOQAOAPATAAQAVAAANgPQAPgOAAgUQAAgTgPgOQgNgPgVAAQgTAAgOAPgAj/A1QgWgVAAggQAAgeAWgXQAXgVAfgBQAdAAAWAUQADADgDADIgMANQgDADgDgDQgOgMgTAAQgTAAgOAOQgNAPAAATQAAAUAOANQANAPAUAAQARAAAPgMQADgCADACIAMAOQADACgDADQgVAVgeAAQgfAAgXgXgAqtA1QgXgVAAggQAAgeAXgXQAWgVAggBQAdAAAVAUQADADgDADIgMANQgDADgDgDQgOgMgSAAQgTAAgOAOQgOAPAAATQAAAUAOANQANAPAVAAQARAAAOgMQADgCADACIANAOQACACgDADQgUAVgeAAQggAAgWgXgAKJBKQgEgBAAgEIAAh1IggAAQgEAAAAgDIAAgRQAAgFAEAAIBbAAQAEAAABAFIAAARQgBADgEAAIgfAAIAAB1QgBAEgEABgACgBKQgEgBAAgEIAAh1IggAAQgEAAAAgDIAAgRQAAgFAEAAIBcAAQADAAAAAFIAAARQAAADgDAAIghAAIAAB1QAAAEgDABgABHBKQgEgBAAgEIAAiJQAAgFAEAAIAUAAQADAAAAAFIAACJQAAAEgDABgAgiBKQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIg2hDIAABAQAAAEgFABIgSAAQgGgBAAgEIAAiIQAAgGAGAAIASAAQAFAAAAAGIAAA4IA1g8QAAAAABAAQAAgBABAAQAAAAABAAQAAgBABAAIAVAAQABAAAAABQABAAABAAQAAAAAAABQABAAAAABQABACgCADIg3A+IA7BFQACACgBADQgBABAAAAQAAABgBAAQAAAAgBAAQgBABgBAAgAmDBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAFAAAAAFIAAARQAAADgFAAIg+AAIAAAjIA0AAQAEAAAAAEIAAAQQAAAFgEAAIg0AAIAAAlIA+AAQAFAAAAADIAAARQAAAEgFABgAnEBKQgEgBAAgEIAAg5IhFAAIAAA5QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAA3IBFAAIAAg3QAAgFAEAAIATAAQAEAAAAAFIAACJQAAAEgEABg");
	this.shape.setTransform(0.75,0.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_1.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,191,51.5), null);


(lib._4x_text = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353534").s().p("AkLJAQgLgFgIgMQgHgLgDgSQgCgTAAgaIABgoQABgTAHgPQAGgOAMgJQANgJAWAAQASAAAMAFQAMAFAHAMQAHALADATQADASAAAaIgBAoQgCATgGAPQgGAPgNAIQgMAIgWAAQgTAAgMgEgAj3GZQgEADgCAHQgDAIgBANIAABUQABAMADAHQACAHAEACQAEADAHAAQAHAAADgDQAFgEADgHQABgIABgNIAAhUQgBgMgCgHQgDgHgEgCQgEgDgGAAQgHAAgEAEgAmZI9QgMgHgHgNQgGgNgCgQQgDgRAAgSIABgpQACgUAGgPQAGgQAOgJQANgJAZAAQAKAAAKACQALADAHAGQAIAGAEAKQAFAJABAOIgnAAQgBgLgEgGQgEgHgJAAQgJAAgFAEQgEAEgDAHQgCAGgBAKIgBAeIABAAQAEgIAJgFQAKgFANAAQANAAAKAFQAJAFAGAIQAFAIADAMQADALAAANQAAAjgPARQgQASghAAQgVAAgMgHgAmHHnQgFAIgBAVIABAPQABAIADAFQACAFAEADQAFADAHAAQAHAAAFgDQADgDADgFIADgNIABgPQAAgVgGgIQgEgJgMAAQgMAAgFAJgAUfJBIAAjIIAoAAIAACnIBIAAIAAAhgASTJBIAAjIIBxAAIAAAhIhIAAIAAAvIBDAAIAAAhIhDAAIAAA2IBKAAIAAAhgARFJBIgyiMIAAAAIAACMIglAAIAAjIIAuAAIAxCJIABAAIAAiJIAlAAIAADIgAOxJBIgJgqIg1AAIgKAqIgpAAIA0jIIAyAAIA1DIgAN5H2IAoAAIgUhaIAAAAgAK3JBIAAjIIBHAAQAPAAALAGQAKAFAHAIQAGAIADALQADALAAALQAAAQgEALQgFAMgJAHQgIAHgMAEQgMADgOAAIgVAAIAABQgALgHUIASAAQALAAAIgIQAHgHABgPQgBgPgGgIQgGgIgPAAIgRAAgAIGJBIAAinIgsAAIAAghIB/AAIAAAhIgrAAIAACngAGnJBIgJgqIg1AAIgJAqIgqAAIA1jIIAyAAIA1DIgAFwH2IAnAAIgThaIgBAAgAC9JBIAAjIIApAAIAACnIBIAAIAAAhgAA3JBIAAjIIBwAAIAAAhIhHAAIAAAvIBCAAIAAAhIhCAAIAABXgAoxJBIgJgqIg1AAIgKAqIgqAAIA1jIIAyAAIA0DIgAppH2IAoAAIgUhaIAAAAgAsrJBIgyiMIgBAAIAACMIglAAIAAjIIAvAAIAxCJIABAAIAAiJIAkAAIAADIgAvAJBIgJgqIg0AAIgKAqIgqAAIA1jIIAyAAIA0DIgAv3H2IAoAAIgUhaIgBAAgAxsJBIAAhYIgvAAIAABYIgoAAIAAjIIAoAAIAABNIAvAAIAAhNIAoAAIAADIgA0tJBIAAinIgsAAIAAghIB/AAIAAAhIgrAAIAACngAhaHTIAAhaIAjAAIAABagAiRHTIAAhaIAkAAIAABagAG0D3QgegQgRgiQgQgigGgyQgGgyAAhBQABg/AHgwQAJgwATghQAUggAhgQQAhgQAwAAQBTAAAmApQAkAqABBNIhiAAIgEgdQgCgPgIgNQgHgMgLgIQgLgIgPAAQglAAgRApQgPApAABeIACBSQADAkAHAaQAIAaANAOQAOAOAWAAQAKAAALgFQAKgFAKgKQAKgKAGgPQAHgPgBgVIAAg0IhDAAIAAhKIClAAIAAEQIhLAAIAAgvIgBAAQgTAegaAMQgaANgkAAQguAAgdgRgAAuD3QgdgQgRgiQgPgigGgyQgFgygBhBQAAg/AIgwQAJgwASghQAVggAggQQAggQAxAAQBUAAAkApQAlAqAABNIhhAAIgEgdQgCgPgIgNQgHgMgLgIQgKgIgQAAQglAAgRApQgQApAABeIADBSQADAkAIAaQAGAaAOAOQAPAOAVAAQAKAAAKgFQAMgFAJgKQAKgKAGgPQAGgPAAgVIAAg0IhDAAIAAhKIClAAIAAEQIhLAAIAAgvIgBAAQgTAegaAMQgaANgjAAQgwAAgdgRgAUjEAQgIgLgCgOIgFh9QgCgegNgRQgOgRgfAAIg3AAIAADWIhnAAIAAn4IC9AAQBAAAAjAgQAkAggBBCQAAAzgUAgQgVAggrAIIAAACQAmAGASATQASATAEAqIAICCQAEAVAPAIIAAAEgAShgcIAqAAQAlAAAUgRQAUgSgBgoQAAhGhGAAIgwAAgALrEAIAAn4IEbAAIAABTIi1AAIAAB3ICqAAIAABSIiqAAIAACIIC8AAIAABUgAi6EAIAAn4IBmAAIAAH4gApUEAIAAn4ICrAAQAfAAAaAGQAbAGASAPQAUAPALAZQAKAZAAAjQAAAqgTAdQgTAdgmALIAAABQAqAGAZAdQAYAfAAAzQABAegIAbQgIAagTAVQgTAUgeAMQgdAMgtAAgAnvC1IApAAQAkAAAXgQQAWgRABgsQgBgWgGgOQgGgPgKgIQgKgJgPgEIgfgDIgsAAgAnvgpIAdAAQArAAATgPQAUgPAAglQAAgkgSgPQgRgOgnAAIglAAgAs2EAIhJisIhICsIhxAAIB/kAIh1j4IByAAIBACjIBAijIBwAAIh2D4IB+EAgAzeEAIAAhoIiyAAIAAhUIClk4IBqAAIAAE9IAwAAIAABPIgwAAIAABogA1BBJIBjAAIAAi+IgCAAgATTlMQgTgUAAgjIAAgLIA0AAIABAYQABAIAFAFQADAFAHADQAHADAKAAQAMAAAJgIQAKgIAAgQQAAgJgDgGQgCgGgFgFQgGgFgIgEIgWgJQgSgGgMgHQgMgGgJgKQgJgJgEgMQgDgMAAgQQgBgmAVgTQAWgSAlAAQASAAAOAEQAPADAKAJQAKAIAHANQAFANAAATIAAAHIgxAAQAAgSgHgKQgGgKgPAAQgJAAgGACQgFADgEAEQgDAEgBAGIgCALQABAMAEAIQAFAIARAHIAoARQAOAGAKAHQAJAHAGAJQAFAIADAJQACAKAAAMQAAApgXASQgYATgrAAQgsAAgSgTgANylCQgPgIgIgRQgIgRgEgaQgDgZAAgiQAAggAEgZQAFgYAKgQQAKgRAQgIQARgIAZAAQArAAASAVQATAVAAAnIgyAAIgBgPQgCgHgEgHQgEgGgFgEQgGgEgHAAQgTAAgIAVQgJAVABAwIABAqQABASAEANQADAOAIAHQAHAHALAAQAFAAAFgDQAGgCAEgFQAFgFAEgIQADgIAAgKIAAgbIgjAAIAAgmIBVAAIAACLIgmAAIAAgYIgCAAQgIAPgOAGQgNAHgSAAQgYAAgPgJgAAKlMQgSgUAAgjIAAgLIAzAAIABAYQABAIAFAFQAEAFAGADQAHADAKAAQAMAAAJgIQAKgIAAgQQAAgJgCgGQgDgGgFgFQgGgFgJgEIgVgJQgSgGgMgHQgMgGgJgKQgJgJgDgMQgDgMAAgQQgBgmAVgTQAVgSAlAAQARAAAPAEQAPADAKAJQAKAIAHANQAFANAAATIAAAHIgxAAQAAgSgHgKQgGgKgPAAQgJAAgGACQgFADgEAEQgDAEgCAGIgBALQABAMAFAIQAEAIARAHIAoARQAOAGAKAHQAKAHAFAJQAFAIADAJQACAKAAAMQAAApgXASQgYATgrAAQgsAAgSgTgAlOlDQgRgJgKgSQgJgRgCgZQgDgYAAgeQAAgdADgZQACgYAJgSQAKgRARgKQASgKAcAAQAcAAAQAJQARAJAHANQAIAOACAQIACAeIg0AAQAAgcgHgMQgGgNgRAAQgLAAgGAFQgGAFgDAMQgEAMgCATIgBAuQAAAdACASQACASAEAKQAEAKAGADQAHAEAIAAQAHAAAGgDQAGgCAEgHQAFgHACgNQACgNAAgVIA0AAQABAVgEATQgDATgJAOQgJAOgQAIQgQAIgaAAQgcAAgSgKgAq2k/QgMgFgIgLQgIgKgCgOQgEgNAAgPIAAgMIAwAAIAAAIQAAAVAEAKQAFAKAOAAQAOAAAEgKQAFgKAAgVIAAi3IA0AAIAAC5QAAApgTARQgUASgmAAQgVAAgOgGgAtzlDQgRgJgJgSQgJgRgCgZQgEgYAAgeQAAgdAEgZQACgYAJgSQAJgRARgKQASgKAdAAQAdAAARAKQASAKAJARQAJASADAYQACAZABAdQgBAegCAYQgDAZgJARQgJASgSAJQgRAKgdAAQgdAAgSgKgAtXoYQgGAFgEAMQgEALgCASIAABYQACASAEAMQAEALAGAFQAIAGALAAQAMAAAGgGQAIgFADgLQAEgMABgSIAAhYQgBgSgEgLQgDgMgIgFQgGgFgMAAQgLAAgIAFgAQak9IAAkBICQAAIAAAqIhcAAIAAA9IBWAAIAAAqIhWAAIAABFIBfAAIAAArgAMEk9IgLg3IhFAAIgMA3Ig2AAIBEkBIBAAAIBEEBgAK9meIAzAAIgZh0IgBAAgAItk9IAAjNIgBAAIgtDNIgpAAIgujNIgBAAIAADNIgvAAIAAkBIBNAAIAlC1IABAAIAli1IBMAAIAAEBgAEak9IAAkBIA0AAIAAEBgAiDk9IAAjXIg4AAIAAgqICkAAIAAAqIg4AAIAADXgAoik9IAAkBICQAAIAAAqIhcAAIAAA9IBXAAIAAAqIhXAAIAABFIBgAAIAAArgAvrk9QgEgGgBgHIgDhAQgBgPgGgIQgHgJgRAAIgbAAIAABtIg0AAIAAkBIBfAAQAhAAASAQQASAQAAAiQAAAagKAQQgLARgWAEIAAABQATADAJAKQAKAJACAWIAEBCQACALAIAEIAAACgAwtnOIAWAAQASAAAKgJQAKgJAAgUQABgkglAAIgYAAgA0fk9IAAkBIBbAAQAUAAANAGQAOAHAJALQAHALAEANQAEAOAAAPQAAAUgGAOQgGAPgKAJQgMAKgPAFQgPAEgSAAIgcAAIAABngAzrnKIAYAAQAPAAAKgJQAJgKAAgUQAAgTgIgKQgIgKgUAAIgWAAg");
	this.shape.setTransform(-489.7808,179.699,1.1252,1.1252);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib._4x_text, new cjs.Rectangle(-910.1,114.4,771.3,137.79999999999998), null);


(lib.allFrames_group = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_5
	this.instance = new lib.txt_firstTelevision();
	this.instance.setTransform(-181.65,273.3,1,1,0,0,0,-210.6,23.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(242).to({_off:false},0).to({y:258.2,alpha:1},10,cjs.Ease.quadOut).wait(26));

	// Layer_8
	this.instance_1 = new lib.txt_epiqVision();
	this.instance_1.setTransform(-185.7,303.2,1,1,0,0,0,-210.6,23.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(262).to({_off:false},0).to({y:293.05,alpha:1},11,cjs.Ease.quadOut).wait(5));

	// Frame_10_02
	this.instance_2 = new lib.Frame_10_02();
	this.instance_2.setTransform(128.5,201.05,0.5468,0.5468);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(265).to({_off:false},0).to({alpha:1},11,cjs.Ease.quadOut).wait(2));

	// Frame_10_01
	this.instance_3 = new lib.Frame_10_01();
	this.instance_3.setTransform(140.15,209.05,0.5409,0.5409,0,0,0,0.3,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(235).to({_off:false},0).to({regX:0,regY:0,x:140,y:209,alpha:1},7).wait(36));

	// _x_text
	this.instance_4 = new lib._4x_text();
	this.instance_4.setTransform(141.95,152.1,0.7612,0.7612,0,0,0,0.1,0);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(187).to({_off:false},0).to({y:143.1,alpha:1},8).wait(35).to({alpha:0},7).to({_off:true},1).wait(40));

	// image_group
	this.instance_5 = new lib.image_group_1();
	this.instance_5.setTransform(154.05,378.05,0.6621,0.6621,0,0,0,0.1,0.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(180).to({_off:false},0).to({alpha:1},7).wait(43).to({alpha:0},7).to({_off:true},1).wait(40));

	// shaq_frame_07_txt
	this.instance_6 = new lib.shaq_frame_07_txt();
	this.instance_6.setTransform(149.95,558.2);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(148).to({_off:false},0).to({y:538.7,alpha:1},9,cjs.Ease.quadOut).wait(22).to({alpha:0},7).to({_off:true},1).wait(91));

	// shaq_frame_07
	this.instance_7 = new lib.shaq_frame_07_1();
	this.instance_7.setTransform(155.95,307,1,1,0,0,0,0.1,0.2);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(140).to({_off:false},0).to({regY:0.1,x:155.05,y:306,alpha:1},6).to({_off:true},41).wait(91));

	// shaq_frame_06_txt
	this.instance_8 = new lib.shaq_frame_06_txt();
	this.instance_8.setTransform(135.95,430.7);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(102).to({_off:false},0).to({y:419.2,alpha:1},8,cjs.Ease.quadOut).wait(26).to({alpha:0},6).to({_off:true},1).wait(135));

	// Shaq_frame_06
	this.instance_9 = new lib.Shaq_frame_06();
	this.instance_9.setTransform(150,268);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(94).to({_off:false},0).to({y:267,alpha:1},6).wait(36).to({alpha:0},6).to({_off:true},1).wait(135));

	// text
	this.instance_10 = new lib.shaq_frame_05_txt();
	this.instance_10.setTransform(-5.5,67.7);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(49).to({_off:false},0).to({y:47.7,alpha:1},10,cjs.Ease.quadOut).wait(29).to({alpha:0},7).to({_off:true},1).wait(182));

	// Shaq_frame_04
	this.instance_11 = new lib.Shaq_frame_05("single",0);
	this.instance_11.setTransform(150,268);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(49).to({_off:false},0).to({alpha:1,mode:"synched",loop:false},6).wait(33).to({startPosition:33},0).to({alpha:0,startPosition:40},7).to({_off:true},1).wait(182));

	// text
	this.instance_12 = new lib.shaq_frame_02_txt_02();
	this.instance_12.setTransform(-1.4,89.2);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(21).to({_off:false},0).to({y:77.7,alpha:1},10,cjs.Ease.quadOut).wait(14).to({alpha:0},3).to({_off:true},1).wait(229));

	// text
	this.instance_13 = new lib.shaq_frame_01_txt();
	this.instance_13.setTransform(-5.5,67.7);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({y:47.7,alpha:1},10,cjs.Ease.quadOut).wait(35).to({alpha:0},3).to({_off:true},1).wait(229));

	// Shaq_frame_01
	this.instance_14 = new lib.Shaq_frame_01("synched",0,false);
	this.instance_14.setTransform(150,306);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({alpha:1,startPosition:5},5).to({_off:true},83).wait(190));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-461.1,143,780.8,265);


// stage content:
(lib.Epson_EpiqVision_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		var root = this; //Declared variable for access to global scope.
		
		this.popUp_btn.addEventListener("click", popUpBtn.bind(this));
		this.panel.addEventListener("click", exitPanel.bind(this));
		
		
		this.on("click", function (e) {
			window.open(clickTag, "_blank");
			console.log("ClickTag pressed");
			
		});
		
		
		function popUpBtn(e) {
			e.stopPropagation();
			root.panel.y = 0;
			root.stop();
			console.log("PopUp button pressed");
		}
		
		
		function exitPanel(e) {
			e.stopPropagation();
			root.panel.y = 50;
			root.play();
			console.log("Panel Closed");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(360));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("A4/j5MAx/AAAIAAHzMgx/AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// panel
	this.panel = new lib.panel();
	this.panel.name = "panel";
	this.panel.setTransform(0,51);

	this.timeline.addTween(cjs.Tween.get(this.panel).wait(360));

	// popUp_btn
	this.popUp_btn = new lib.disclaimerBtn();
	this.popUp_btn.name = "popUp_btn";
	this.popUp_btn.setTransform(308.2,501.3,1,1,0,0,0,-15.6,15.2);
	new cjs.ButtonHelper(this.popUp_btn, 0, 1, 2, false, new lib.disclaimerBtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.popUp_btn).wait(94).to({y:470.3},6,cjs.Ease.quadOut).wait(132).to({y:500.3},8,cjs.Ease.quadOut).to({_off:true},1).wait(119));

	// exitBtn
	this.instance = new lib.exitBtn();
	this.instance.setTransform(150,300);
	this.instance.alpha = 0;
	new cjs.ButtonHelper(this.instance, 0, 1, 2, false, new lib.exitBtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(360));

	// Epson_logo
	this.instance_1 = new lib.Epson_logo();
	this.instance_1.setTransform(75.3,42.05);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:1},5).wait(355));

	// Shaq_image
	this.instance_2 = new lib.Shaq_image();
	this.instance_2.setTransform(328.15,39.45,0.2703,0.2703,0,0,0,0.2,0.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(239).to({_off:false},0).to({x:314.9},11,cjs.Ease.quadOut).wait(110));

	// cta_btn_Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_267 = new cjs.Graphics().p("AjjBOQgTAAAAgSIAAAAIAAh3QAAgSATAAIAAAAIHHAAQATAAAAASIAAAAIAAB3QAAASgTAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(267).to({graphics:mask_graphics_267,x:214.4074,y:37.0579}).wait(93));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.8,-3.8,5.9,3.8).s().p("AjkDeIFUoIIB1BNIlUIIg");
	this.shape_1.setTransform(173.875,24.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.8,-3.8,5.9,3.8).s().p("AjkDeIFUoHIB0BMIlTIHg");
	this.shape_2.setTransform(174.25,24.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.8,-3.8,5.8,3.8).s().p("AjjDdIFSoGIB1BNIlSIGg");
	this.shape_3.setTransform(175.45,25.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.8,-3.7,5.8,3.8).s().p("AjiDcIFSoDIBzBMIlRIDg");
	this.shape_4.setTransform(177.375,26.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.7,-3.7,5.8,3.8).s().p("AjhDbIFQoBIBzBMIlQIBg");
	this.shape_5.setTransform(180.1,26.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.7,-3.7,5.7,3.8).s().p("AjfDaIFNn+IByBLIlNH+g");
	this.shape_6.setTransform(183.625,28.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.6,-3.7,5.7,3.7).s().p("AjdDYIFKn5IBxBKIlKH5g");
	this.shape_7.setTransform(187.925,29.575);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.6,-3.7,5.6,3.6).s().p("AjbDVIFHnzIBwBJIlHH0g");
	this.shape_8.setTransform(193,31.275);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.5,-3.6,5.6,3.7).s().p("AjYDTIFDnuIBuBJIlCHug");
	this.shape_9.setTransform(198.825,33.225);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.4,-3.6,5.5,3.5).s().p("AjVDQIE+nnIBtBIIk+Hng");
	this.shape_10.setTransform(205.475,35.475);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.4,-3.5,5.4,3.5).s().p("AjSDNIE5nfIBsBGIk5Hfg");
	this.shape_11.setTransform(212.9,37.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.3,-3.4,5.3,3.5).s().p("AjPDKIE1nYIBqBGIk1HXg");
	this.shape_12.setTransform(220.275,40.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.2,-3.4,5.2,3.4).s().p("AjMDGIEwnQIBpBEIkwHRg");
	this.shape_13.setTransform(226.925,42.675);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.1,-3.3,5.2,3.4).s().p("AjJDEIEsnKIBnBDIksHKg");
	this.shape_14.setTransform(232.75,44.625);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.1,-3.3,5.1,3.4).s().p("AjHDCIEpnFIBmBCIkpHFg");
	this.shape_15.setTransform(237.825,46.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5,-3.2,5.1,3.3).s().p("AjFDAIEmnBIBlBCIkmHBg");
	this.shape_16.setTransform(242.125,47.775);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5,-3.3,5,3.2).s().p("AjDC+IEjm9IBkBCIkkG9g");
	this.shape_17.setTransform(245.65,48.975);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.9,-3.3,5,3.2).s().p("AjCC9IEhm6IBkBBIkiG6g");
	this.shape_18.setTransform(248.375,49.875);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.9,-3.2,5,3.3).s().p("AjBC8IEgm4IBjBBIkgG4g");
	this.shape_19.setTransform(250.3,50.525);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.9,-3.2,4.9,3.2).s().p("AjBC8IEfm3IBjBAIkfG3g");
	this.shape_20.setTransform(251.5,50.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-14.6,-9.6,14.7,9.5).s().p("Ao9ItINW0ZIElDAItWUYg");
	this.shape_21.setTransform(251.869,51.0562,0.3365,0.3365);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19,this.shape_20,this.shape_21];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},267).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).wait(73));

	// ctaBtn
	this.instance_3 = new lib.ctaBtn();
	this.instance_3.setTransform(214.85,37.45,0.3033,0.3033,0,0,0,1.5,1.3);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(261).to({_off:false},0).to({alpha:1},6).wait(93));

	// allFrames_group
	this.instance_4 = new lib.allFrames_group("synched",0,false);
	this.instance_4.setTransform(262.55,37.15,0.3865,0.3865,0,0,0,150.5,311.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(359).to({mode:"single",startPosition:277},0).wait(1));

	// background_color
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("A4/D6IAAnzMAx/AAAIAAHzg");
	this.shape_22.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape_22).wait(360));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(157.3,-3,178.59999999999997,104);
// library properties:
lib.properties = {
	id: 'DD94ED7BF2A34E56A40B38420D93FD29',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"endFrame_screen_01.jpg", id:"endFrame_screen_01"},
		{src:"endFrame_screen_02.jpg", id:"endFrame_screen_02"},
		{src:"epson_logo.png", id:"epson_logo"},
		{src:"image_group.jpg", id:"image_group"},
		{src:"shaq_endFrame.jpg", id:"shaq_endFrame"},
		{src:"shaq_frame_01.jpg", id:"shaq_frame_01"},
		{src:"shaq_frame_04.jpg", id:"shaq_frame_04"},
		{src:"shaq_frame_05.jpg", id:"shaq_frame_05"},
		{src:"shaq_frame_07.jpg", id:"shaq_frame_07"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['DD94ED7BF2A34E56A40B38420D93FD29'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;