(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.endFrame = function() {
	this.initialize(img.endFrame);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,183);


(lib.frame_06 = function() {
	this.initialize(img.frame_06);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,125,138);


(lib.paper = function() {
	this.initialize(img.paper);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,163,211);


(lib.printer_01 = function() {
	this.initialize(img.printer_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,320,320);


(lib.zoomIn = function() {
	this.initialize(img.zoomIn);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,91,91);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.zoomIn_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#666666").ss(1,1,1).p("AG2AAQAAC1iBCAQiACBi1AAQi0AAiAiBQiBiAAAi1QAAi0CBiBQCAiAC0AAQC1AACACAQCBCBAAC0g");
	this.shape.setTransform(-11.45,-12.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ak5E6QiCiCAAi4QAAi3CCiCQCCiCC3AAQC4AACCCCQCCCCAAC3QAAC4iCCCQiCCCi4AAQi3AAiCiCg");
	mask.setTransform(-11.6675,-12.9175);

	// Layer_1
	this.instance = new lib.zoomIn();
	this.instance.setTransform(-56.5,-58);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.zoomIn_1, new cjs.Rectangle(-56.2,-57.5,89.5,89.5), null);


(lib.txt_precisionCore = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AgIAWQgFgCgDgDQgDgDgCgEQgCgEAAgGQAAgEACgFQACgEADgDQADgDAFgCQAEgCAEAAQAFAAAEACQAFACADADQADADACAEQACAFAAAEQAAAGgCAEQgCAEgDADIgIAFIgJACQgEAAgEgCgAgGgQIgGAEIgDAGQgCADAAADQAAAEACAEIADAFIAGAEQADACADAAIAHgCIAGgEIAEgFIABgIIgBgGIgEgGIgGgEIgHgCQgDAAgDACgAAGANIgGgLIgDAAIAAALIgFAAIAAgZIAJAAQAFAAACACQADABAAAFIAAADIgCABIgCABIgDABIAHALgAgDgBIAEAAIADgBQABAAAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgBgCIgBgBIgCAAIgCAAIgDAAg");
	this.shape.setTransform(-0.175,-191.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A3283").s().p("AgVA9QgHgEgFgGQgGgIgCgIQgDgJAAgKQAAgNADgIQAEgJAFgFQAGgHAGgCQAIgDAHAAIAIABIAJADQADABAEADQADADADADIAAguIAVAAIAAB9IgTAAIAAgNIgBAAQgEAJgIADQgIADgIAAQgKAAgJgDgAgLgMQgEACgEAFQgDAFgBAFIgBAMQAAAGABAFQACAGADAFQADAEAFADQAFACAFAAQAHAAAFgDQAFgCADgFQADgEABgGIACgMQAAgPgHgIQgHgIgLAAQgGAAgGADg");
	this.shape_1.setTransform(80.65,-189.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2A3283").s().p("AAhAwQgGAAgEgCQgEgDgBgGQgHAGgIADQgIACgIAAQgGAAgGgBIgKgFQgEgEgDgFQgDgFAAgHQAAgIADgFQAEgGAFgCQAFgDAGgBIANgCIAJgCIAJgBQAEgBACgCQACgDAAgEQAAgEgCgCIgEgEIgGgCIgGAAQgIAAgGADQgFAEgBAHIgUAAQAAgJAEgGQAEgFAFgEQAGgEAIgBQAHgBAHAAQAGAAAHABQAGABAGAEQAFADADAFQADAFAAAHIAAAuIABAGQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIACAAIADAAIAAAOIgDABIgDAAIgEABgAAFAEIgNABIgGACIgFADIgEAEIgBAHQAAADACACIAEAEIAGACIAGAAIAGgBQAEAAAEgDIAGgFQACgDAAgFIAAgPQgFADgGABg");
	this.shape_2.setTransform(70.275,-187.875);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2A3283").s().p("AgRAtQgJgEgFgGQgGgHgDgIQgDgJAAgLQAAgJADgIQADgJAGgHQAGgGAIgEQAIgEAJAAQALAAAJAEQAIAFAGAHQAGAIACAJQADAKgCAJIhCAAQAAAGACAEQABAFADAEQADAEAFACQAEACAGAAQAJAAAFgEQAFgDADgIIATAAQgBAHgEAGQgEAGgGAEQgFAEgHACQgHACgHAAQgKAAgIgDgAAXgHIgCgJQgBgFgDgDIgHgFQgFgCgFAAQgEAAgEABQgFACgDAEQgDADgCAEQgCAFAAAFIAuAAIAAAAg");
	this.shape_3.setTransform(59.7531,-187.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2A3283").s().p("AAUA/IAAg5QAAgKgEgFQgFgFgJAAQgEAAgEACQgEACgDADQgDADgBAEQgCAEAAAFIAAA2IgUAAIAAh9IAUAAIAAAvQAEgGAHgFQAIgEAIAAQAPAAAJAIQAIAIAAAOIAAA/g");
	this.shape_4.setTransform(49.125,-189.625);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2A3283").s().p("AABA7QgEgCgDgDQgCgDgBgFIgCgKIAAg1IgPAAIAAgOIAPAAIAAgcIAUAAIAAAcIASAAIAAAOIgSAAIAAAxIAAAFIABAEQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAIAFABIAFAAIAEgBIAAAQIgHABIgGAAQgIAAgFgBg");
	this.shape_5.setTransform(40.475,-189.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2A3283").s().p("AAUAvIAAg5QAAgKgEgFQgFgFgJAAQgEAAgEABQgEACgDAEQgDADgBAFQgCAEAAAFIAAA1IgUAAIAAhaIATAAIAAANQAFgIAHgDQAIgFAIAAQAPAAAJAIQAIAHAAAQIAAA+g");
	this.shape_6.setTransform(32.025,-188);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2A3283").s().p("AgJA/IAAhaIATAAIAABagAgJgrIAAgTIATAAIAAATg");
	this.shape_7.setTransform(24.275,-189.625);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2A3283").s().p("AgaAvIAAhaIATAAIAAARIAAAAIAEgHIAFgHIAIgEQAFgCAEAAIAFAAIADAAIAAAUIgEAAIgFgBQgFAAgFACQgEACgEAEQgCAEgBAGQgCAGAAAGIAAAsg");
	this.shape_8.setTransform(19.15,-188);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2A3283").s().p("AgtBAIAAh8IAUAAIAAAMQAFgIAHgDQAIgEAIAAQAKAAAJAEQAHAEAGAGQAFAHACAJQADAIAAALQAAAJgCAIQgDAIgFAHQgEAGgHAFQgIADgKAAIgIgBIgIgCQgEgCgEgDQgEgCgCgEIAAAugAgTgnQgGAKAAAPQAAAGACAGQABAFAEAEQADAEAFADQAEACAGAAQAGAAAGgDQAEgCADgFQAEgEABgFIABgLQAAgHgBgGQgCgGgDgEQgEgFgEgDQgFgCgGAAQgMAAgHAIg");
	this.shape_9.setTransform(9.7,-186.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2A3283").s().p("AgRAtQgJgEgGgGQgGgHgDgIQgEgJAAgLQAAgJAEgJQADgJAGgGQAHgHAIgEQAJgDAJAAQAMAAAJAEQAIAFAGAHQAFAIADAKQACAJAAAKIhBAAQAAAMAGAGQAFAFAKAAQAIAAAFgDQAGgEABgFIAWAAQgFARgLAHQgLAHgQAAQgKAAgIgDgAgJgaQgEACgCADQgCADgBADIgBAGIAnAAQgBgJgFgFQgEgFgKAAQgFAAgEACg");
	this.shape_10.setTransform(-7.2708,-188.225);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2A3283").s().p("AgdAvIAAhaIAZAAIAAARIAAAAQACgFACgDIAGgHQAFgCAEgBIAJgCIAGABIAAAXIgFgBIgEAAQgIAAgEACQgFADgDAEQgCAEgBAFQgBAFgBAFIAAAqg");
	this.shape_11.setTransform(-15.3,-188.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2A3283").s().p("AgTAtQgIgEgGgGQgHgGgDgJQgEgJAAgLQAAgKAEgJQADgJAHgGQAGgGAIgEQAJgDAKAAQALAAAJADQAIAEAGAGQAHAGADAJQADAJABAKQgBALgDAJQgDAJgHAGQgGAGgIAEQgJADgLAAQgKAAgJgDgAgKgaQgEADgCAEQgDAEgBAFIgBAKIABALQABAFADAEQACAEAEADQAFACAFAAQAHAAAEgCQAEgDADgEIADgJIABgLIgBgKQgBgFgCgEQgDgEgEgDQgEgCgHAAQgFAAgFACg");
	this.shape_12.setTransform(-24.65,-188.225);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2A3283").s().p("AgWA9QgMgFgIgJQgHgJgEgMQgFgMAAgNQAAgOAFgMQAEgMAHgJQAIgJAMgFQAMgFANAAQALAAAJADQAKADAHAGQAHAFAFAJQAEAIACALIgbAAQAAgEgDgEQgCgEgFgDQgDgEgFgBQgFgCgFAAQgIAAgHAEQgGADgEAHQgFAGgBAHQgCAIAAAIQAAAHACAIQABAIAFAGQAEAGAGADQAHAEAIAAQANAAAHgIQAIgIABgMIAbAAQgBALgEAKQgFAKgHAGQgIAHgJAEQgKADgMAAQgNAAgMgFg");
	this.shape_13.setTransform(-36.6,-189.975);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2A3283").s().p("AASAvIAAgzQAAgLgDgGQgEgFgKAAQgIAAgFAGQgFAGAAAOIAAAvIgZAAIAAhaIAYAAIAAAMIAAAAQAGgIAHgDQAHgEAHAAQAKAAAHADQAHACADAGQAEAEACAHQABAHAAAJIAAA3g");
	this.shape_14.setTransform(-48.35,-188.35);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#2A3283").s().p("AgTAtQgIgEgGgGQgHgGgDgJQgDgJgBgLQABgKADgJQADgJAHgGQAGgGAIgEQAJgDAKAAQALAAAJADQAIAEAGAGQAHAGADAJQAEAJAAAKQAAALgEAJQgDAJgHAGQgGAGgIAEQgJADgLAAQgKAAgJgDgAgKgaQgEADgDAEQgCAEgBAFIgBAKIABALQABAFACAEQADAEAEADQAFACAFAAQAGAAAFgCQAEgDACgEIAFgJIABgLIgBgKQgCgFgDgEQgCgEgEgDQgFgCgGAAQgFAAgFACg");
	this.shape_15.setTransform(-59.05,-188.225);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#2A3283").s().p("AgLA/IAAhaIAXAAIAABagAgLgqIAAgUIAXAAIAAAUg");
	this.shape_16.setTransform(-66.65,-189.975);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#2A3283").s().p("AgOAuQgIgBgFgEQgGgEgEgGQgEgGgBgJIAYAAQABAEABADIAFAFIAFADIAHAAIAGAAIAEgCIAFgEQABgCAAgDQAAgGgHgDQgIgDgMgCIgLgDIgJgEQgEgDgCgEQgDgEAAgGQAAgJADgFQAEgGAFgDQAGgEAHgBQAHgBAHAAQAHAAAHABQAHABAFAEQAGADADAGQAEAFABAJIgYAAQAAgHgGgDQgEgCgGAAIgFAAIgEABIgDACQgBABAAAAQAAABgBAAQAAABAAABQAAAAAAABQAAADADADQACACAEABIAIACIALADIAKADQAFABAFADQAEACACAFQACAEABAGQgBAJgDAGQgEAHgGADQgFAEgIACQgHABgJAAQgGAAgIgCg");
	this.shape_17.setTransform(-73.75,-188.225);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#2A3283").s().p("AgLA/IAAhaIAYAAIAABagAgLgqIAAgUIAYAAIAAAUg");
	this.shape_18.setTransform(-80.75,-189.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#2A3283").s().p("AgRAtQgIgEgGgGQgGgGgEgJQgDgIAAgLQAAgJADgJQADgKAGgGQAGgHAJgEQAJgDAKAAQAIAAAHACQAIACAGAEQAGAFAEAGQADAHABAIIgZAAQgCgPgQAAQgFAAgFACQgEADgCAEQgDAFgBAFIgBAJIABAKQABAGADAEQACAEAEADQAEACAFAAQAJAAAFgFQAFgFABgIIAYAAQgCASgMAJQgMAKgSAAQgJAAgJgDg");
	this.shape_19.setTransform(-88.025,-188.225);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#2A3283").s().p("AgRAtQgJgEgGgGQgGgHgDgIQgEgJAAgLQAAgJAEgJQADgJAGgGQAHgHAIgEQAJgDAJAAQAMAAAJAEQAIAFAGAHQAFAIADAKQACAJAAAKIhBAAQAAAMAGAGQAFAFAKAAQAIAAAFgDQAGgEABgFIAWAAQgFARgLAHQgLAHgQAAQgKAAgIgDgAgJgaQgEACgCADQgCADgBADIgBAGIAnAAQgBgJgFgFQgEgFgKAAQgFAAgEACg");
	this.shape_20.setTransform(-98.2708,-188.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#2A3283").s().p("AgdAvIAAhaIAZAAIAAARIAAAAQABgFADgDIAGgHQAEgCAFgBIAJgCIAGABIAAAXIgFgBIgEAAQgIAAgEACQgFADgDAEQgCAEgBAFQgCAFABAFIAAAqg");
	this.shape_21.setTransform(-106.3,-188.35);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#2A3283").s().p("AgxA/IAAh9IA4AAQAMAAAIADQAIAEAGAFQAEAGADAHQACAIAAAHQAAAIgCAHQgDAHgEAFQgFAGgJADQgIAEgMAAIgcAAIAAAtgAgVgDIAVAAIAIAAIAIgDQAEgCACgEQABgEAAgGQAAgGgBgDQgCgEgEgCQgDgCgFgBIgIgBIgVAAg");
	this.shape_22.setTransform(-115.75,-189.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_precisionCore, new cjs.Rectangle(-123.5,-202.5,212.1,24.599999999999994), null);


(lib.txt_inkCartridges = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AJKCSQgOgDgKgGQgLgHgHgKQgGgKgCgPIAvAAQADANAJAFQAKAGANAAQATAAAJgMQAJgMAAgSIAAgXIgBAAQgHAOgOAGQgOAHgQAAQgSAAgOgHQgOgHgJgLQgJgNgFgPQgEgPAAgRQAAgQAFgQQAFgPAKgMQAJgMANgGQAOgIASAAQAQAAANAHQANAGAIAPIABAAIAAgXIAtAAIAACfQAAAKgDANQgDAOgJALQgJALgSAIQgRAIgeAAQgMAAgNgEgAJWgxQgHAEgFAHQgFAGgBAJQgDAJAAAKIACARQACAJAEAHQAFAHAIAFQAGAEALAAQAKAAAIgDQAIgEAEgHQAFgHADgIQACgIAAgJQAAgLgBgIQgDgKgEgIQgFgHgIgEQgHgEgMAAQgJAAgIAEgAPTBXQgPgDgKgHQgMgHgHgLQgHgMAAgRIAsAAQAAAIADAFQADAGAGADQAFAEAFABIAOACIALgBIAJgEQAEgCAEgFQADgEAAgGQAAgLgOgEQgOgGgagFIgTgGQgKgDgIgEQgHgFgFgIQgEgIAAgKQAAgSAGgKQAHgLAKgFQALgHANgCQANgDAOAAQANAAANAEQANACALAGQALAGAGALQAGAKACAQIgtAAQAAgNgKgFQgJgFgMAAIgJAAIgIACIgHAFQgDAEAAAEQAAAHAFAEQAFAEAHACIA4APQAKADAIAFQAHAFAFAIQAEAIAAAMQAAAQgGAMQgHALgLAHQgLAHgOADQgOADgOAAQgPAAgOgDgAMQBTQgQgGgLgMQgLgMgGgQQgGgQAAgVQAAgRAGgRQAGgRALgMQANgMAPgGQAQgIAUAAQAWAAAQAJQAQAIAKAOQAKAPAFASQAFASgCATIh7AAQACAWAKALQALAKATAAQAOAAALgHQAKgHADgIIAoAAQgKAfgUANQgUANgdAAQgVAAgQgHgAMggyQgHAEgEAGQgFAGgBAGIgDALIBMAAQgDgSgIgJQgJgJgRAAQgKAAgJADgAFyBSQgPgHgKgNQgJgMgEgRQgFgQAAgRQAAgRAFgQQAEgQAJgNQAKgLAOgIQAOgIATAAQAQAAANAHQAOAGAHANIABAAIAAhWIAvAAIAADrIgsAAIAAgWIgBAAQgIANgOAHQgNAGgRAAQgTAAgOgIgAGMgxQgIAFgFAHQgFAIgDAKQgBAKAAAJQAAAKACAKQACAKAFAIQAFAHAIAFQAIAFAKAAQAMAAAIgEQAIgFAFgIQAEgIACgKQACgKAAgKQAAgKgCgKQgCgJgFgIQgFgHgHgFQgIgEgMAAQgLAAgHAEgAklBXQgLgDgIgHQgIgFgFgKQgEgKAAgNQAAgOAFgKQAGgJAIgGQAHgEALgEIA8gJQAIgCAEgEQAFgEAAgHQAAgIgDgEQgCgFgEgCIgKgDIgMgBQgOAAgIAGQgHAGgCAOIgvAAQACgRAHgLQAGgLAMgGQALgHAPgCQAOgEANAAIAaADQAOABALAFQAKAGAIAJQAGAKAAAPIACBuQABAKAEAGIgwAAIgEgRQgLAMgPAFQgPAEgPAAQgNAAgKgDgAjfAGIgfAGIgUAHQgEADgBAEQgDAEAAAHQAAAGADAEQABAFAEADIAKADIALABQANAAAJgFQAHgEADgHQAEgGABgHIABgcgAnSBTQgPgGgMgMQgLgLgHgQQgGgQAAgTQAAgTAGgRQAGgRALgNQALgMAQgGQAQgIAWAAQAOAAAPAEQAOAEAKAJQALAIAIAMQAGAMABAQIgtAAQgFgdgeAAQgLAAgIAFQgHAFgFAIQgFAIgCAKQgCAJAAAJQAAAJACAKQACAKAFAHQAEAIAHAFQAIAFALAAQARAAAJgJQAJgKACgQIAuAAQgFAigWASQgWASgiAAQgTAAgQgHgAAwBWQgJgCgIgEQgHgEgEgIQgFgIAAgNIAAhjIgbAAIAAggIAbAAIAAgzIAvAAIAAAzIAiAAIAAAgIgiAAIAABTQAAAMAEAEQAEAEAMAAIAIAAIAGgCIAAAlIgNABgAD2BWIAAiqIAvAAIAACqgABzBWIAAiqIAtAAIAAAgIAAAAQAEgIAFgHQAFgGAHgFQAIgFAJgCQAIgEAJAAIAJACIAAAsIgRgCQgMAAgJAEQgJAEgFAIQgGAIgCAJQgCAKAAALIAABNgAiHBWIAAiqIAtAAIAAAgIABAAQADgIAFgHQAFgGAIgFQAHgFAJgCQAIgEAJAAIAKACIAAAsIgRgCQgNAAgIAEQgJAEgGAIQgGAIgBAJQgDAKAAALIAABNgAqpBWIgvhNIgSASIAAA7IgvAAIAAjrIAvAAIAAB+IA7g9IA4AAIhBA/IBIBrgAt0BWIAAhgQAAgVgGgLQgHgJgRAAQgSAAgJALQgIALAAAaIAABZIgwAAIAAiqIAtAAIAAAYIABAAQAJgPAOgHQAOgHAPAAQASAAANAFQAMAGAHAJQAHAJACANQADANAAAQIAABogAw8BWIAAiqIAuAAIAACqgAD2hvIAAgmIAvAAIAAAmgAw8hvIAAgmIAuAAIAAAmg");
	this.shape.setTransform(-38.2956,-24.8308,0.5773,0.5773);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_inkCartridges, new cjs.Rectangle(-169.1,-33.5,202.2,192.4), null);


(lib.txt_highCapacity = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AgmBDIAAgSIAFABIAFAAIAGAAIAFgEIACgDIACgHIADgHIglhgIAXAAIAZBIIAAAAIAZhIIAWAAIgmBlIgFANQgCAHgDAEQgEAEgFADQgGADgIAAIgPgBg");
	this.shape.setTransform(19.325,-15.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A3283").s().p("AABA+QgEgCgDgDQgDgDgBgEIgBgLIAAg5IgQAAIAAgQIAQAAIAAgdIAUAAIAAAdIATAAIAAAQIgTAAIAAAzIAAAGIACAEIADADIAFABIAFAAIAEgBIAAARIgHAAIgGABQgJAAgFgCg");
	this.shape_1.setTransform(11.2,-18.475);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2A3283").s().p("AgKBDIAAhgIAVAAIAABggAgKguIAAgUIAVAAIAAAUg");
	this.shape_2.setTransform(5.875,-18.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2A3283").s().p("AgSAwQgIgEgHgHQgGgHgDgJQgDgJAAgLQAAgKADgJQADgKAGgHQAGgHAJgEQAJgEALAAQAJAAAHACQAIACAGAEQAGAFAEAGQAEAHAAAJIgVAAQgBgJgHgFQgFgEgKAAIgIABQgEABgEAEQgEAEgCAHQgDAHgBAKIACAMQABAGADAFQAEAFAEADQAFACAGAAQAKAAAGgFQAGgGACgLIAVAAQgDATgLAKQgMAKgTAAQgKAAgJgDg");
	this.shape_3.setTransform(-1.65,-17.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2A3283").s().p("AAjAzQgHAAgEgCQgEgDgCgGQgGAGgJADQgJACgIAAQgHAAgGgBQgGgCgFgEQgEgDgDgGQgDgFAAgHQAAgJAEgGQADgFAFgDQAGgDAGgBIAOgCIAKgCIAJgCQAEgBADgCQACgDAAgEQAAgEgCgDIgFgEIgGgCIgGAAQgJAAgGADQgGAEgBAIIgVAAQAAgJAEgHQAEgGAGgEQAHgDAHgCIAQgBIANABQAHACAGADQAFADAEAGQADAFAAAIIAAAxIABAGQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIADAAIADAAIAAAPIgDABIgEABIgEAAgAAFAEIgOACIgGABIgGADIgEAFQgBADAAAEQAAAEACACIAFAEIAGACIAHAAIAGgBQAEAAAEgDQAEgCACgDQADgEAAgFIAAgQQgFADgHABg");
	this.shape_4.setTransform(-11.925,-17.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2A3283").s().p("AgvBEIAAiFIAUAAIAAAOIAAAAQAFgJAIgEQAIgDAJAAQALAAAJAEQAIAEAGAHQAGAHACAJQADAKAAALQAAAKgCAIQgDAJgFAHQgFAHgIAFQgIADgLAAIgIgBIgJgCIgIgFQgEgDgCgDIgBAAIAAAwgAgUgoQgHAIAAARQAAAHACAGQACAFAEAFQADAEAFADQAFACAGAAQAHAAAFgDQAFgCAEgFQADgFABgFIACgMIgCgOQgCgFgDgFQgDgFgGgDQgFgDgGAAQgNAAgHAKg");
	this.shape_5.setTransform(-22.925,-15.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2A3283").s().p("AAjAzQgHAAgEgCQgEgDgCgGQgGAGgJADQgJACgIAAQgHAAgGgBQgGgCgFgEQgEgDgDgGQgDgFAAgHQAAgJAEgGQADgFAFgDQAGgDAGgBIAOgCIAKgCIAJgCQAEgBADgCQACgDAAgEQAAgEgCgDIgFgEIgGgCIgGAAQgJAAgGADQgGAEgBAIIgVAAQAAgJAEgHQAEgGAGgEQAHgDAHgCIAQgBIANABQAHACAGADQAFADAEAGQADAFAAAIIAAAxIABAGQAAAAABAAQAAABABAAQAAAAABAAQABAAAAAAIADAAIADAAIAAAPIgDABIgEABIgEAAgAAFAEIgOACIgGABIgGADIgEAFQgBADAAAEQAAAEACACIAFAEIAGACIAHAAIAGgBQAEAAAEgDQAEgCACgDQADgEAAgFIAAgQQgFADgHABg");
	this.shape_6.setTransform(-33.975,-17.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2A3283").s().p("AgSAwQgIgEgHgHQgFgHgEgJQgDgJAAgLQAAgKADgJQADgKAGgHQAGgHAJgEQAJgEALAAQAIAAAJACQAHACAGAEQAGAFADAGQAFAHAAAJIgVAAQgCgJgFgFQgHgEgJAAIgIABQgEABgEAEQgEAEgDAHQgDAHAAAKIACAMQACAGADAFQACAFAGADQAEACAGAAQAKAAAGgFQAGgGACgLIAVAAQgDATgMAKQgLAKgTAAQgKAAgJgDg");
	this.shape_7.setTransform(-44.7,-17.075);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2A3283").s().p("AgbAKIAAgTIA2AAIAAATg");
	this.shape_8.setTransform(-53.65,-17.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2A3283").s().p("AAVBDIAAg9QAAgLgFgFQgEgFgKAAQgEAAgFACQgEACgDAEQgDADgCAEQgBAEAAAGIAAA5IgWAAIAAiFIAWAAIAAAyQAEgHAIgEQAIgFAIAAQAQAAAJAIQAKAJAAAPIAABDg");
	this.shape_9.setTransform(-62.725,-18.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2A3283").s().p("AgOBEQgHgCgHgDQgGgEgEgGQgEgFgBgJIAVAAQACAFACACIAFAFIAHACIAHAAQANAAAGgGQAGgGAAgNIAAgOIAAAAQgFAIgIAEQgIAFgIAAQgLAAgJgEQgHgEgGgHQgFgIgDgIQgCgJAAgLQAAgJADgJQACgJAHgHQAFgGAIgEQAJgEAJAAQAJAAAHADQAIAEAFAJIAAAAIAAgOIAVAAIAABcQAAAWgMALQgMAKgXAAQgHAAgHgBgAgMgwQgFADgCAEQgDAFgCAGIgBAMQAAAHABAFQACAGAEAEQADAEAEADQAFADAGAAQAHAAAFgDQAFgDADgFQADgEACgGQABgGAAgGIgBgMQgCgGgDgFQgEgEgFgDQgEgCgHAAQgGAAgGADg");
	this.shape_10.setTransform(-73.95,-15.275);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2A3283").s().p("AgKBDIAAhgIAVAAIAABggAgKguIAAgUIAVAAIAAAUg");
	this.shape_11.setTransform(-81.675,-18.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2A3283").s().p("AAfBDIAAg8Ig8AAIAAA8IgYAAIAAiFIAYAAIAAA1IA8AAIAAg1IAXAAIAACFg");
	this.shape_12.setTransform(-90.75,-18.925);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_highCapacity, new cjs.Rectangle(-98.9,-32,124.7,25.3), null);


(lib.txt_fastPrintSpeed = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AgRA1QgJgCgHgEQgFgFgEgHQgEgHAAgJIAXAAQABAKAHAEQAHAEAIAAIAIAAIAIgCIAFgEQADgDAAgFQgBgEgDgDIgIgFIgLgDIgLgCIgNgEQgFgCgFgCQgFgEgDgFQgCgFgBgIQABgJADgGQAFgGAGgDQAHgEAHgBIAPgCQAHAAAIACQAIACAFAEQAHAEADAGQAFAGABAJIgZAAQgCgJgGgCQgFgDgHAAIgGAAIgHACIgEADQgCACAAADQAAAFADACQACADAGACIAJADIANACIANAEIAKAFQAFADADAFQADAGAAAHQAAAKgEAGQgFAHgHAEQgHAEgHACQgJACgIAAQgJAAgIgDg");
	this.shape.setTransform(44.5,-20.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A3283").s().p("AgXBGQgKgFgGgHQgGgHgDgLQgDgKAAgMQAAgPAEgIQAEgLAGgHQAGgGAJgEQAIgDAJAAIAJABIAJADIAJAFIAHAHIAAAAIAAg2IAXAAIAACRIgWAAIAAgOIAAAAQgFAKgJADQgJAEgJABQgMAAgJgFgAgMgOQgGADgDAGQgEAFgBAGQgCAGAAAIIACANQACAGADAGQAEAFAFADQAGADAGAAQAIAAAGgDQAFgEAEgFQADgFACgHQACgGAAgIQAAgRgIgJQgIgKgNAAQgHABgGADg");
	this.shape_1.setTransform(32.725,-22.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2A3283").s().p("AgUA0QgKgFgGgHQgHgHgDgKQgEgLAAgMQAAgKAEgKQAEgKAGgIQAHgIAJgEQAKgFAKAAQANAAAKAGQAKAFAGAIQAHAJADALQADALgCALIhMAAQAAAGABAGQACAGAEAEQADAEAFADQAGACAGAAQAKAAAHgEQAGgFADgIIAWAAQgCAIgEAHQgFAHgGAEQgHAFgHACQgIADgJAAQgLAAgKgEgAAbgIQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgGAAQgFAAgFACQgFACgDAEQgEAEgCAFQgCAFAAAGIA1AAIAAAAg");
	this.shape_2.setTransform(21.375,-20.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2A3283").s().p("AgUA0QgKgFgGgHQgHgHgDgKQgEgLAAgMQAAgKAEgKQAEgKAGgIQAHgIAJgEQAKgFAKAAQANAAAKAGQAKAFAGAIQAHAJADALQADALgCALIhMAAQAAAGABAGQACAGAEAEQADAEAFADQAGACAGAAQAKAAAHgEQAGgFADgIIAWAAQgCAIgEAHQgFAHgGAEQgHAFgHACQgIADgJAAQgLAAgKgEgAAbgIQAAgGgCgFQgCgFgEgEQgDgEgFgCQgFgCgGAAQgFAAgFACQgFACgDAEQgEAEgCAFQgCAFAAAGIA1AAIAAAAg");
	this.shape_3.setTransform(10.175,-20.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2A3283").s().p("AgzBKIAAiQIAWAAIAAAPIAAAAQAFgKAJgEQAJgEAJAAQAMAAAJAFQAKAEAGAIQAGAHADALQADAKAAAMQAAAKgDAJQgCAKgGAIQgGAHgIAFQgJAFgLAAIgKgBIgJgDIgJgFIgHgIIAAAAIAAA1gAgVgsQgIAKAAARQAAAIACAHQACAGAEAFQAEAFAFACQAFADAHAAQAIAAAFgDQAGgDADgFQAEgGABgFIACgOQAAgHgCgHQgCgHgEgFQgDgFgGgDQgFgDgHAAQgOAAgHAKg");
	this.shape_4.setTransform(-1.375,-18.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2A3283").s().p("AgVBKQgLgDgIgHQgIgGgFgKQgFgKAAgOIAZAAQAAAJADAGQADAFAFAEQAFAEAHACQAGABAHABQAIAAAGgCQAGgCAEgEQAEgCABgFIACgIQAAgIgEgEQgEgEgEgCIgSgFIgZgHQgJgCgGgDQgHgEgDgFQgEgFgBgFQgCgGAAgFQAAgMAFgHQAEgJAIgFQAHgFAKgDQAJgDAKAAQALAAAKADQAKAEAIAFQAHAHAFAIQAEAJAAALIgZAAQgBgOgJgGQgIgFgNgBIgJACIgIADQgEABgDAFQgCADAAAGQAAAIAEAEQAFAEAIADIAGABIAMADIANAEIAKADQAHACAFADQAGADADAGQAEAEACAHIABAKQAAANgFAIQgFAKgIAFQgIAGgKACQgLADgLgBQgLAAgLgCg");
	this.shape_5.setTransform(-14.325,-22.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2A3283").s().p("AABBEQgFgCgDgEQgDgDgBgGIgCgLIAAg9IgRAAIAAgSIARAAIAAgfIAXAAIAAAfIAVAAIAAASIgVAAIAAA3IAAAHIABAEIAEADIAGABIAFAAIAFgBIAAASIgIABIgHAAQgKAAgFgBg");
	this.shape_6.setTransform(-29.85,-21.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2A3283").s().p("AAXA2IAAhBQAAgNgFgFQgFgGgLAAQgFAAgEACIgIAGQgEAEgBAFQgCAFAAAGIAAA9IgXAAIAAhoIAWAAIAAAPIAAABQAFgJAJgFQAIgFAKAAQARAAAKAJQAKAJAAASIAABHg");
	this.shape_7.setTransform(-38.775,-20.525);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2A3283").s().p("AgKBJIAAhpIAVAAIAABpgAgKgyIAAgWIAVAAIAAAWg");
	this.shape_8.setTransform(-46.95,-22.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2A3283").s().p("AgeA2IAAhoIAWAAIAAAUIAAAAQABgEADgEIAGgIQAFgDAFgCQAFgCAFAAIAGAAIADAAIAAAXIgFgBIgFAAQgGAAgFACQgFADgEAEQgDAFgCAHQgDAGAAAIIAAAyg");
	this.shape_9.setTransform(-52.125,-20.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2A3283").s().p("Ag4BJIAAiRIA/AAQAQAAAJAEQAKAFAGAHQAFAGACAJQACAHAAAIQAAAGgCAIQgCAIgFAGQgGAGgKAEQgJAFgQAAIglAAIAAA4gAgegDIAkAAIAIgBIAJgEQAEgDACgEQACgFABgHQAAgHgCgFQgCgEgEgDQgEgDgEgBIgKgBIgkAAg");
	this.shape_10.setTransform(-62.65,-22.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2A3283").s().p("AARBFIgNgBQgEgBgFgCQgFgDgDgFQgCgFAAgIIAAg9IgSAAIAAgUIASAAIAAgfIAcAAIAAAfIAVAAIAAAUIgVAAIAAAzQAAAHACADQACADAIAAIAFgBIAEAAIAAAWIgIABg");
	this.shape_11.setTransform(-79.65,-22.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2A3283").s().p("AgQA2QgJgCgHgFQgHgDgEgIQgEgGgBgMIAcAAQAAAFACAEIAFAGIAHACIAHABIAGAAIAHgCIAEgFQACgCAAgEQAAgHgJgDIgXgGIgMgEQgGgBgFgDQgFgDgCgFQgDgFAAgGQAAgLAEgGQAEgHAGgDQAHgFAIgBIAQgCQAIABAIABQAIACAHAEQAGAEAEAGQAEAHABAJIgbAAQgBgIgGgDQgGgDgGAAIgGAAIgFABIgEAEQgBACAAACQAAAFACACQADADAFABIAJADIANACIAMAEQAGACAFADQAEADADAFQADAEAAAIQAAALgEAGQgEAIgHAEQgHAEgJACQgIABgJAAIgRgBg");
	this.shape_12.setTransform(-88.475,-20.55);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2A3283").s().p("AgcA2QgHgCgFgEQgFgEgCgGQgDgFgBgJQABgJADgGQADgFAFgEQAFgDAGgBIANgDIANgCIAKgBQAFgCADgCQADgCAAgFQAAgEgCgDIgEgFIgGgCIgHAAQgIAAgEAEQgGAEAAAIIgdAAQABgKAEgHQAEgHAIgEQAGgEAJgCQAJgCAHAAIAQABQAJACAHADQAGADAEAGQAFAGAAAJIAAA2IABAOQABAGACAEIgeAAIgBgFIgBgFQgHAHgJADQgJACgKAAQgHAAgGgBgAAOAEIgGACIgHABIgFAAIgGACIgGADIgEAEQgBADAAAEQAAAEABACIAEAFIAGACIAHAAQAHAAAEgCQAFgDADgEQACgEAAgFIABgGIAAgLg");
	this.shape_13.setTransform(-99.75,-20.55);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#2A3283").s().p("AgyBJIAAiRIBlAAIAAAbIhFAAIAAAiIA8AAIAAAYIg8AAIAAA8g");
	this.shape_14.setTransform(-111.025,-22.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_fastPrintSpeed, new cjs.Rectangle(-119,-36.6,170.2,27.400000000000002), null);


(lib.txt_enhance = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AgIAJIAAgRIARAAIAAARg");
	this.shape.setTransform(93.225,-49.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A3283").s().p("AATA7IgcgtIgNAMIAAAhIgOAAIAAh1IAOAAIAABFIAmgkIATAAIgiAdIAkA3g");
	this.shape_1.setTransform(87.175,-54.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#2A3283").s().p("AgWAsIAAhVIAOAAIAAASQAFgKAGgFQAIgFALAAIAAAPQgIAAgGADQgGACgCAEQgEAFgCAGQgCAHABAHIAAAmg");
	this.shape_2.setTransform(79.95,-52.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2A3283").s().p("AgRApQgIgDgFgGQgFgGgDgIQgDgIABgKQgBgIADgIQADgJAFgGQAFgGAIgDQAIgEAJAAQAKAAAIAEQAHADAGAGQAFAGADAJQACAIAAAIQAAAKgCAIQgDAIgFAGQgGAGgHADQgIAEgKAAQgJAAgIgEgAgKgdQgEACgEAEQgDAEgCAGQgCAGgBAHQABAIACAGQACAGADAEQAEAEAEACQAFACAFAAQAFAAAGgCQAEgCADgEQAFgEABgGQACgGAAgIQAAgHgCgGQgBgGgFgEQgDgEgEgCQgGgCgFAAQgFAAgFACg");
	this.shape_3.setTransform(71.9,-52.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#2A3283").s().p("AASArIgShDIAAAAIgQBDIgPAAIgchVIAQAAIATBFIAAAAIARhFIAPAAIASBFIAAAAIAThFIAPAAIgcBVg");
	this.shape_4.setTransform(60.825,-52.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2A3283").s().p("AgTApQgFgCgEgEQgDgEgCgGQgCgGABgGIAAg4IANAAIAAA5QAAAIAFAFQAFAEAIAAQAGAAAEgCQAFgCADgDQADgEACgFQABgFAAgFIAAgwIAPAAIAABVIgOAAIAAgOQgFAIgGAEQgIAEgIAAQgJAAgFgDg");
	this.shape_5.setTransform(45.2,-52.725);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#2A3283").s().p("AgRApQgHgDgGgGQgGgGgCgIQgCgIgBgKQABgIACgIQACgJAGgGQAGgGAHgDQAIgEAJAAQAKAAAIAEQAHADAGAGQAFAGADAJQACAIAAAIQAAAKgCAIQgDAIgFAGQgGAGgHADQgIAEgKAAQgJAAgIgEgAgJgdQgGACgDAEQgDAEgDAGQgBAGAAAHQAAAIABAGQADAGADAEQADAEAGACQAFACAEAAQAGAAAFgCQAEgCAEgEQADgEACgGQADgGAAgIQAAgHgDgGQgCgGgDgEQgEgEgEgCQgFgCgGAAQgEAAgFACg");
	this.shape_6.setTransform(35.75,-52.825);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2A3283").s().p("AgaA8IgFgBIAAgNIAEABIAFABQADAAADgCQAEgDABgDIAGgPIgihUIAQAAIAXBFIABAAIAYhFIAPAAIglBgIgFALQgBAEgEADIgGAEIgIABg");
	this.shape_7.setTransform(26.8,-51.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#2A3283").s().p("AgbA5IgHAAIAAgTIAGAAIAHAAQAFAAACgDQACgDAAgEIgBgGIgehPIAZAAIATA6IAAAAIATg6IAYAAIgkBfQgDALgGAEQgHAFgMAAg");
	this.shape_8.setTransform(13.575,-51.375);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2A3283").s().p("AgXArQgFgBgFgDQgDgDgCgFQgDgFAAgHQAAgHADgFQACgEAEgDIAJgDIALgCIALgCIAIgBQAEgBACgCQACgCAAgEIgBgGIgEgDIgEgCIgGAAQgGAAgEADQgEADgBAHIgXAAQAAgJAEgFQAEgGAFgDQAGgDAHgCIANgBIANABQAHABAFACQAGADADAFQAEAFgBAHIAAAsIABALQABAFACADIgYAAIgBgEIgBgEQgGAFgHADQgHACgHAAQgHAAgFgCgAALADIgEABIgGABIgFABIgEABIgFACIgDAEQgCACABADQgBAEACACIADADIAFACIAFAAQAGAAAEgCIAFgFQACgEABgDIAAgFIAAgJg");
	this.shape_9.setTransform(4.45,-52.875);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#2A3283").s().p("AAPArIgPg5IAAAAIgOA5IgYAAIgbhVIAYAAIAQA5IABAAIAOg5IAWAAIAOA5IAQg5IAYAAIgbBVg");
	this.shape_10.setTransform(-7.075,-52.875);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2A3283").s().p("AgQAqQgJgEgFgFQgGgGgDgJQgDgIAAgKQAAgIADgJQADgIAGgGQAGgGAIgDQAIgEAJAAQALAAAIAEQAIAEAFAIQAFAHADAJQACAJgBAJIg9AAQABALAFAFQAGAFAIAAQAIAAAFgDQAFgEABgEIAVAAQgFAQgLAGQgKAHgOAAQgJAAgIgDgAgIgYQgEACgCACIgDAGIgCAGIAmAAQgCgJgEgFQgEgEgJAAQgFAAgDACg");
	this.shape_11.setTransform(-23.295,-52.875);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#2A3283").s().p("AAQA7IAAgxQAAgKgCgEQgEgFgJAAQgIAAgEAFQgEAFgBANIAAAtIgXAAIAAh1IAXAAIAAAsIABAAQAEgHAIgEQAFgCAHAAQAJgBAGADQAGADAEAEQADAFACAGQABAGAAAIIAAA0g");
	this.shape_12.setTransform(-33.05,-54.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2A3283").s().p("AADA3QgDAAgFgDQgDgCgCgEQgDgEAAgHIAAgwIgNAAIAAgRIANAAIAAgZIAXAAIAAAZIARAAIAAARIgRAAIAAAoQAAAHACABQACACAGABIAEAAIADgBIAAASIgHABIgHAAg");
	this.shape_13.setTransform(-41,-54.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_enhance, new cjs.Rectangle(-44.8,-65.7,141.6,21.700000000000003), null);


(lib.txt_engineered = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("A0ZCVQgNgCgLgHQgLgGgHgLQgHgKgCgPIAmAAQABAIAEAGQAEAFAGACQAFADAHABIAOAAQAXABAKgLQALgMAAgVIAAgaIgBAAQgIAOgOAIQgNAIgQAAQgVAAgOgHQgOgHgKgMQgJgNgEgQQgFgQAAgSQAAgRAGgQQAFgPAKgMQAKgLAOgHQAOgHATAAQAQAAANAHQAOAGAHAPIABAAIAAgXIAlAAIAACgQAAAngVASQgWATgoAAQgNABgNgDgA0Ug3QgJAFgFAJQgFAIgDALQgCAKAAALQAAAKADAJQACALAGAHQAFAIAJAGQAIAEAMAAQAMABAJgGQAJgFAFgJQAGgHACgMQADgKAAgKQAAgLgDgKQgDgKgFgJQgFgHgJgFQgJgFgMAAQgNAAgIAGgAZWBSQgQgHgLgMQgLgMgHgQQgGgRAAgSQAAgUAHgQQAGgRALgMQAMgLAQgHQAQgHATAAQAWAAAQAIQARAIAKAPQAKAOAFASQAFASgCATIh7AAQABAXALAKQAKAKAUAAQAOABALgIQAKgHACgIIApAAQgKAfgUANQgVANgdAAQgUAAgQgGgAZmgzQgHADgEAHQgFAFgCAGIgCALIBMAAQgDgRgIgKQgJgJgRAAQgLAAgIAEgAWeBSQgQgHgLgLQgLgLgGgRQgHgQAAgTQAAgSAGgSQAGgRALgMQALgMAQgHQARgHAUAAQAQAAAOAEQAOAEALAIQALAIAHAMQAHAMABAQIguAAQgFgdgeAAQgLAAgIAFQgHAGgFAHQgFAJgCAJQgCAKAAAJQAAAJACAJQACAKAFAHQAEAIAIAGQAHAEALAAQARAAAJgJQAJgJACgRIAuAAQgFAjgWARQgWASgiAAQgTAAgQgGgAQMBWQgKgDgIgHQgIgGgFgKQgEgKAAgNQAAgOAFgJQAFgKAIgFQAIgFALgDIA8gKQAHgCAFgEQAFgEgBgHQAAgHgCgFQgDgFgEgCQgEgDgFAAIgMgBQgOAAgIAGQgIAGgBAOIgvAAQABgQAHgMQAIgKALgHQALgGAOgEQAOgCAOAAIAaABQAOACAKAFQALAGAHAKQAHAIAAARIACBtQABALADAFIgvAAIgEgQQgLALgPAFQgPAEgQAAQgMAAgLgCgARTAFIgqAIIgJAEQgEADgCAEQgCAFAAAGQAAAHACAEQACAEAEACIAJAFIALABQAOgBAIgFQAHgEAEgGQAEgHABgHIAAgcgAHRBSQgRgHgLgMQgLgMgGgQQgGgRAAgSQAAgUAGgQQAGgRAMgMQAMgLAPgHQAQgHAUAAQAWAAAQAIQAQAIAKAPQALAOAFASQAEASgBATIh7AAQABAXAKAKQALAKAUAAQAOABAKgIQAKgHADgIIApAAQgKAfgVANQgUANgdAAQgUAAgQgGgAHhgzQgHADgFAHQgEAFgCAGIgCALIBMAAQgDgRgJgKQgIgJgRAAQgMAAgHAEgAC3BSQgQgHgLgMQgLgMgGgQQgGgRAAgTQAAgTAGgRQAGgQALgMQALgMAQgGQAQgHAUAAQAVAAAQAHQAQAGALAMQALAMAGAQQAFARAAATQAAATgFARQgGAQgLAMQgLAMgQAHQgQAGgVAAQgUAAgQgGgADFg3QgJAFgGAJQgGAIgCALQgDAKAAALQAAALADALQACAKAGAJQAGAJAJAEQAKAGAMAAQANAAAJgGQAJgEAGgJQAGgJADgKQADgLAAgLQAAgLgDgKQgDgLgGgIQgGgJgJgFQgJgGgNAAQgMAAgKAGgAjWBRQgPgGgKgNQgKgMgFgRQgFgRAAgSQAAgXAHgQQAGgRAKgLQALgLANgFQANgFAOAAIAQABIAQAFQAIAEAGAFQAHAFAEAGIABAAIAAhXIAlAAIAADrIgjAAIAAgXIgBAAQgIAPgOAGQgPAGgQAAQgUABgPgIgAjDg3QgKAFgFAJQgGAJgDALQgCALAAAKQAAALADALQADALAFAIQAGAIAJAFQAJAFAMAAQANAAAJgGQAJgEAGgJQAFgJADgKQADgLAAgLQAAgcgNgQQgMgQgWAAQgNAAgJAGgAmIBSQgPgHgLgMQgLgMgFgQQgGgRAAgSQAAgSAGgRQAGgQALgNQAKgMAQgHQAPgHATAAQAUAAAQAIQAQAIALAPQAKAOAFARQAFASgDASIh9AAQAAALADAIQADAKAFAGQAGAIAIAEQAJAEAMAAQAQAAAKgHQAKgHAFgOIAkAAQgDAOgHAKQgIALgKAHQgKAIgNAEQgMADgOAAQgUAAgQgGgAl3g5QgIAEgGAGQgGAFgDAJQgEAIAAAJIBYAAQgBgIgDgIQgDgIgGgHQgFgGgIgEQgIgEgJAAQgKAAgIAEgAqjBSQgPgHgLgMQgLgMgFgQQgGgRAAgSQAAgSAGgRQAGgQALgNQAKgMAQgHQAPgHATAAQAUAAAQAIQAQAIALAPQAKAOAFARQAFASgDASIh9AAQAAALADAIQADAKAFAGQAGAIAIAEQAJAEAMAAQAQAAAKgHQAKgHAFgOIAkAAQgDAOgHAKQgIALgKAHQgKAIgNAEQgMADgOAAQgUAAgQgGgAqSg5QgIAEgGAGQgGAFgDAJQgEAIAAAJIBYAAQgBgIgDgIQgDgIgGgHQgFgGgIgEQgIgEgJAAQgKAAgIAEgAtYBSQgPgHgLgMQgLgMgFgQQgGgRAAgSQAAgSAGgRQAGgQALgNQAKgMAQgHQAPgHATAAQAUAAAQAIQAQAIALAPQAKAOAFARQAFASgDASIh9AAQAAALADAIQADAKAFAGQAGAIAIAEQAJAEAMAAQAQAAAKgHQAKgHAFgOIAkAAQgDAOgHAKQgIALgKAHQgKAIgNAEQgMADgOAAQgUAAgQgGgAtHg5QgIAEgGAGQgGAFgDAJQgEAIAAAJIBYAAQgBgIgDgIQgDgIgGgHQgFgGgIgEQgIgEgJAAQgKAAgIAEgABEBTQgJgDgFgFQgFgGgCgIIgCgTIAAhjIgdAAIAAgcIAdAAIAAg0IAlAAIAAA0IAiAAIAAAcIgiAAIABBkIACAHQACADAEABIAKACIAHAAIAIgCIAAAeIgYACQgPgBgJgCgAUgBUIAAhfQAAgWgGgKQgHgLgRAAQgTAAgIAMQgJAMAAAaIAABYIgvAAIAAipIAtAAIAAAXIABAAQAJgPAOgGQAOgHAPAAQASAAANAFQAMAFAHAJQAHAJACAOQADANAAAPIAABogAOcBUIAAhfQAAgWgHgKQgGgLgRAAQgTAAgJAMQgJAMAAAaIAABYIguAAIAAjrIAuAAIAABZIABAAQAJgPAOgGQAOgHANAAQATAAAMAFQAMAFAHAJQAHAJADAOQADANAAAPIAABogALWBUIAAhfQAAgWgGgKQgHgLgRAAQgTAAgIAMQgJAMAAAaIAABYIgvAAIAAipIAtAAIAAAXIABAAQAJgPAOgGQAOgHAPAAQASAAANAFQAMAFAHAJQAHAJACAOQADANAAAPIAABogAodBUIAAipIAjAAIAAAgIABAAQABgGAFgHQAFgHAHgFQAGgFAJgEQAIgDAIAAIAJAAIAFABIAAAkIgQgCQgJABgJADQgIAEgGAIQgHAHgDALQgEAKAAAOIAABRgAvKBUIAAhqQgBgVgIgJQgIgIgRgBQgJAAgIAEQgHAEgGAGQgFAFgDAJQgDAIAAAJIAABkIglAAIAAipIAjAAIAAAYIABABQAIgOAOgIQAOgIARAAQAcAAAQAPQAQAOAAAdIAAB0gAyHBUIAAipIAmAAIAACpgA2UBUIAAhqQgBgVgIgJQgIgIgRgBQgJAAgIAEQgHAEgGAGQgFAFgDAJQgDAIAAAJIAABkIglAAIAAipIAjAAIAAAYIABABQAIgOAOgIQAOgIARAAQAcAAAQAPQAQAOAAAdIAAB0gA7NBUIAAjrICqAAIAAAkIiAAAIAAA9IB2AAIAAAiIh2AAIAABFICCAAIAAAjgAyHhzIAAgkIAmAAIAAAkg");
	this.shape.setTransform(41.4498,-49.7459,0.5018,0.5018);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_engineered, new cjs.Rectangle(-45.9,-65.1,426,43.3), null);


(lib.TSeries_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AwOC6QgkgRgYgaQgYgbgMgkQgNglAAgpQAAgqANglQAMgkAYgcQAYgbAkgQQAjgQAsAAQAgAAAcAJQAcAKAWARQAXASAOAaQAOAaAFAgIhTAAQgCgOgHgMQgHgMgMgKQgLgJgOgFQgPgFgPAAQgcAAgUALQgUAMgMASQgNATgFAXQgGAXAAAZQAAAYAGAXQAFAWANATQAMASAUALQAUAMAcAAQAmgBAWgYQAWgXAFgnIBSAAQgDAkgPAeQgNAbgVAWQgWAUgfALQgdALgjAAQgsAAgjgPgEgiHADBQgegIgXgRQgXgQgNgaQgOgZABgkIBRAAQAAASAHAOQAHANAMAJQAMAJAPAEQAPAEARAAIAZgCQAMgCAMgFQALgHAHgIQAIgJAAgPQAAgQgLgKQgJgJgRgHIh4gjQgTgIgQgLQgRgMgKgSQgJgUAAgZQAAgeAMgWQANgVAUgQQAUgOAagGQAagHAZgBQAeABAdAHQAcAGAVAOQAVAQANAXQAMAYAAAhIhSAAQgBgRgFgMQgGgKgLgIQgKgGgNgCIgdgDIgVACQgKACgJAFQgHAHgFAHQgGAIAAAMQAAAMAFAGQADAIAOAGIB6AiQATAGATAMQATAMANATQAOAWAAAgQAAAagJAXQgLAXgVAQQgTARgeAHQgeALgmAAQghgBgdgHgAjwC9QgagKgTgUQgSgSgKgbQgKgcAAggQAAgiAKgaQAKgbASgUQATgSAagLQAagKAjAAQAgAAAaAKQAaALAUASQATAUAKAbQAJAaAAAiQAAAggJAcQgKAbgTASQgUAUgaAKQgbALgfgBQgjABgagLgAjVgcQgMAKgIALQgIAMgDAQQgDAQAAARQAAAQADARQADAOAIANQAIANAMAHQAOAIAUAAQASAAANgIQANgHAJgNQAHgNADgOQADgRAAgQQAAgRgDgQQgDgQgHgMQgJgLgNgKQgNgHgSAAQgUAAgOAHgAqnC9QgagKgTgUQgSgSgLgbQgKgcAAggQAAgiAKgaQALgbASgUQATgSAagLQAagKAiAAQAhAAAaAKQAaALATASQATAUAKAbQALAaAAAiQAAAggLAcQgKAbgTASQgTAUgaAKQgbALgggBQgiABgagLgAqMgcQgNAKgHALQgJAMgDAQQgCAQAAARQAAAQACARQADAOAJANQAHANANAHQANAIAUAAQASAAAOgIQAMgHAJgNQAHgNADgOQAEgRAAgQQAAgRgEgQQgDgQgHgMQgJgLgMgKQgOgHgSAAQgUAAgNAHgA1VC8QgagKgRgTQgTgUgLgaQgJgcAAgfQAAghAKgZQAKgaAUgUQASgTAagMQAagLAgAAQAjAAAbANQAaAOARAYQARAXAHAcQAHAdgCAgIjIAAQACAmASARQARAQAfAAQAYAAAQgLQARgMADgNIBEAAQgRAyghAWQghAVgvAAQgiABgagMgA06gdQgLAGgIAKQgIAJgCAKIgEARIB8AAQgFgcgOgPQgNgPgcAAQgSAAgNAGgA9TC+QgUgHgLgPQgLgPgFgVQgFgWAAgZIAAipIBNAAIAACbQAAAiALASQAKAQAbABQAhgBAMgSQAPgTAAgqIAAiQIBMAAIAAEUIhJAAIAAgmIgBAAQgPAYgXAKQgXAMgYgBQgfAAgTgJgAN2C8QgdgHgXgRQgWgRgOgZQgMgZABgjIBPAAQAAATAIAOQAGANALAHQAMAJAPADQAPAFARAAIAYgCQAMgCAMgFQALgGAHgIQAIgKAAgOQAAgPgLgKQgJgJgRgHIh1giQgUgJgQgLQgQgLgJgSQgLgSAAgaQAAgdANgWQANgVATgQQAVgNAZgHQAZgGAZgBQAeABAcAGQAbAHAVANQAUAQAOAYQALAWAAAhIhQAAQAAgSgHgKQgFgLgLgHQgKgGgNgDIgcgCIgUACQgKACgJAFQgHAFgFAJQgGAIAAALQAAAMAFAGQADAHANAGIB5AiQASAGATAMQATALANAUQANAUAAAgQAAAagKAWQgKAWgUARQgTAPgeAJQgdAKglAAQghgBgdgHgEAhEAC9QgWgFgSgLQgSgLgLgSQgMgTgBgbIBIAAQAAANAEAIQAGAJAIAGQAHAFALACIAUADIARgCIAQgFQAIgEAEgHQAFgGAAgKQAAgRgWgIQgWgJgpgIIgfgJQgQgGgMgIQgNgIgHgNQgIgLAAgSQAAgaALgRQAKgRARgJQARgKAVgEQAVgEAWAAQAWAAAWAEQAUAFARAJQAQAKALARQAKARACAZIhHAAQgCgVgNgIQgPgJgVAAIgOABIgNAEIgKAIQgEAFAAAHQAAALAHAGQAHAGAMAEIBaAXQAQAFALAJQANAIAHAOQAHAMAAATQAAAbgKASQgKATgSALQgRALgXAEQgWAEgYABQgYgBgWgEgAckC4QgagLgSgTQgTgTgJgaQgLgaAAggQAAgfALgZQAKgaATgUQATgSAZgMQAZgLAfAAQAjAAAbANQAZAOAQAWQARAXAHAbQAIAegCAgIjEAAQABAkARARQAQARAfAAQAYAAAQgNQARgLADgNIBCAAQgPAxgiAWQghAVguAAQgggBgZgJgAc9gdQgMAFgHAKQgGAIgDAJIgDASIB4AAQgEgbgOgPQgNgPgcAAQgSAAgMAHgAS8C4QgagLgSgTQgSgTgKgaQgKgaAAggQAAgfAKgZQALgaATgUQARgSAagMQAZgLAgAAQAiAAAaANQAaAOARAWQAQAXAIAbQAHAegCAgIjFAAQABAkASARQAQARAgAAQAXAAAQgNQARgLADgNIBDAAQgQAxgiAWQghAVgtAAQghgBgZgJgATVgdQgLAFgHAKQgHAIgDAJIgEASIB6AAQgFgbgOgPQgNgPgcAAQgSAAgMAHgAgBDAIAAkUIBIAAIAAAzIABAAQAGgMAIgMIAVgTQAMgHANgFQAOgDAOgBIARADIAABGIgMgBIgQAAQgUAAgPAGQgOAGgJAMQgJAMgEARQgDAPAAATIAAB9gAm2DAIAAl/IBMAAIAAF/gA5VDAIAAkUIBJAAIAAAzIABAAQAFgMAIgMIAWgTQALgHAOgFQANgDAPgBIARADIAABGIgOgBIgOAAQgVAAgPAGQgNAGgKAMQgIAMgEARQgEAPAAATIAAB9gAZiC7IAAkPIBKAAIAAEPgAWbC7IAAkPIBHAAIAAAyIABAAQAFgNAJgKQAJgMALgHQANgHAMgFQAOgEANAAIARADIAABFIgbgDQgUAAgPAIQgNAGgJALQgJAMgEAQQgDAPAAATIAAB7gAG5C7IAAkyIhyAAIAAhGIE2AAIAABGIhyAAIAAEygAJcBLIAAhAICeAAIAABAgADvgIQgKgDgJgIQgHgHgFgLQgFgKAAgNQAAgNAFgKQAFgKAHgIQAJgIAKgDQAKgEANAAQALAAAJAEQAMADAHAIQAJAIAFAKQAEAKAAANQAAANgEAKQgFALgJAHQgIAIgLADQgJAEgLABQgNgBgKgEgAD1hlQgIAEgHAFQgFAGgDAIQgDAJAAAJQAAAJADAJQADAIAFAFQAHAIAIACQAHAEAKAAQAIAAAHgEQAJgCAFgIQAGgFADgIQADgJAAgJQAAgJgDgJQgDgIgGgGQgFgFgJgEQgHgDgIAAQgKAAgHADgAESgdIgQgbIgHAAIAAAbIgMAAIAAg/IAYAAQALABAHAEQAHADAAAKQAAAGgCADIgEAFIgFADIgGABIARAbgAD7hBIAMAAIAJgBQACgCAAgGIgBgEIgCgDIgFgBIgPAAgAZih/IAAg+IBKAAIAAA+g");
	this.shape.setTransform(40.6545,26.6087,0.6952,0.6952);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.TSeries_Logo, new cjs.Rectangle(-139.3,12.7,338.9,188.70000000000002), null);


(lib.speedometer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#2A3283").ss(3,1,1).p("AigDHIE/AAQAdgcAVgvQAqhegqhiQgSghghghQhEhBhRABQgpAAgwARQhgAhggBTQgpBsAoBZQAVAsAcAXg");
	this.shape.setTransform(3.4843,0.8684,0.7869,0.7869);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A3283").s().p("ACaBpQgEAAgDgEQgDgCAAgFIAAgBQAAgEADgDQADgDAEAAIAiAAQAEAAADADQADADAAAEIAAABQAAAFgDACQgDAEgEAAgAi7BpQgEAAgDgEQgDgCAAgFIAAgBQAAgEADgDQADgDAEAAIAiAAQAEAAADADQADADAAAEIAAABQAAAFgDACQgDAEgEAAgABugDQgDAAgDgDIgBgBQgDgDAAgEQgBgEADgDIAYgZQADgCAFAAQADAAADADIABABQADADAAAEQABAFgDACIgZAZQgCACgDAAIgCAAgAh1gHIgYgYQgDgDAAgFQABgDADgDIABgBQADgDADAAQAFgBADADIAYAZQADADgBAEQAAADgDADIgBABQgDADgEAAIgCAAQgDAAgCgCgAgBgyQgEAAgDgDQgDgDAAgEIAAgiQAAgEADgDQADgDAEAAIABAAQAEAAACADQAEADAAAEIAAAiQAAAEgEADQgCADgEAAg");
	this.shape_1.setTransform(3.509,-4.0484,0.7869,0.7869);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.speedometer_mc, new cjs.Rectangle(-16.1,-16.2,39.2,34.2), null);


(lib.printer_shdw = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0.314,1],0,-2.9,0,3).s().p("ApmAeIAAg7ITNAAIAAA7g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_shdw, new cjs.Rectangle(-61.5,-2.9,123,5.9), null);


(lib.printer_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.printer_01();
	this.instance.setTransform(-122.45,-68.35,0.7375,0.7375);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_01_1, new cjs.Rectangle(-122.4,-68.3,236,236), null);


(lib.paper_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.paper();
	this.instance.setTransform(-66.3,-74.95,0.7544,0.7544);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.paper_mc, new cjs.Rectangle(-66.3,-74.9,123,159.2), null);


(lib.needle_body = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#2A3283").ss(2,1,1).p("AAhAAQAAAOgKAJQgKAKgNAAQgNAAgJgKQgKgJAAgOQAAgMAKgKQAJgKANAAQANAAAKAKQAKAKAAAMg");
	this.shape.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.needle_body, new cjs.Rectangle(-4.3,-4.3,8.7,8.7), null);


(lib.needle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("Ag+AvIBvhnIAGgEQAFgEACACQADADgKALIhkBwg");
	this.shape.setTransform(-0.0654,-0.0583);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.needle, new cjs.Rectangle(-6.3,-6.4,12.5,12.8), null);


(lib.learnMore_CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdAnIAAhNIA6AAIAAAOIgoAAIAAARIAlAAIAAAMIglAAIAAAUIApAAIAAAOg");
	this.shape.setTransform(34.225,-0.275);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AARAnIgCgJIgBgKQgBgGgDgDQgDgCgGAAIgQAAIAAAeIgSAAIAAhNIAqAAQAFAAAEABIAHAFIAFAHQACAEAAAEQAAAHgDAFQgDAFgHACIAGADIADAEIACAGIABAGIAAAEIAAAFIABAFIACAEgAgPgDIASAAQAFAAADgCQADgDAAgGQAAgGgDgCQgDgDgFAAIgSAAg");
	this.shape_1.setTransform(26.625,-0.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgPAmQgHgDgFgGQgFgFgDgIQgDgHAAgJQAAgHADgIQADgIAFgFQAFgGAHgDQAHgDAIAAQAJAAAHADQAHADAFAGQAFAFADAIQADAIAAAHQAAAJgDAHQgDAIgFAFQgFAGgHADQgHADgJAAQgIAAgHgDgAgJgXQgEACgCAEQgDADgBAFIgBAJIABAKQABAFADADQACAEAEACQAEADAFAAQAGAAAEgDQAEgCADgEQACgDABgFIABgKIgBgJQgBgFgCgDQgDgEgEgCQgEgDgGAAQgFAAgEADg");
	this.shape_2.setTransform(18.125,-0.275);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAaAnIAAg2IgTA2IgNAAIgTg2IAAAAIAAA2IgQAAIAAhNIAYAAIASA1IARg1IAYAAIAABNg");
	this.shape_3.setTransform(8.775,-0.275);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAQAnIgggzIAAAAIAAAzIgQAAIAAhNIARAAIAgAzIAAgzIAQAAIAABNg");
	this.shape_4.setTransform(-3.525,-0.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AARAnIgCgJIgBgKQgBgGgDgDQgDgCgGAAIgQAAIAAAeIgSAAIAAhNIAqAAQAFAAAEABIAHAFIAFAHQACAEAAAEQAAAHgDAFQgDAFgHACIAGADIADAEIACAGIABAGIAAAEIAAAFIABAFIACAEgAgPgDIASAAQAFAAADgCQADgDAAgGQAAgGgDgCQgDgDgFAAIgSAAg");
	this.shape_5.setTransform(-11.475,-0.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUAnIgFgRIgdAAIgGARIgRAAIAdhNIARAAIAdBNgAgJAJIATAAIgKgcIAAAAg");
	this.shape_6.setTransform(-19.425,-0.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgdAnIAAhNIA6AAIAAAOIgoAAIAAARIAlAAIAAAMIglAAIAAAUIApAAIAAAOg");
	this.shape_7.setTransform(-26.675,-0.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgbAnIAAhNIASAAIAAA/IAlAAIAAAOg");
	this.shape_8.setTransform(-33.475,-0.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0044F0").s().p("AmTCUQg8AAAAg9IAAitQAAg9A8AAIMnAAQA8AAAAA9IAACtQAAA9g8AAg");
	this.shape_9.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.learnMore_CTA, new cjs.Rectangle(-46.3,-14.7,92.69999999999999,29.5), null);


(lib.ink_drop = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#2A3283").ss(2,1,1).p("AAAjLQAMANAMANQAPAQAPARQAYAbAUAgQAOAYANAYQARAfAEAgQACAPAAAOQAAANgCAOQgGAlgXAfQgWAegkANQgkAOgogDQgngDgggVQghgVgNghQgPgjACgoQACgdAKgaQAOgmAVgfQARgaASgYQAUgbAWgaQAMgOALgNg");
	this.shape.setTransform(-19.7321,-0.9727);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ink_drop, new cjs.Rectangle(-35.5,-22.4,31.6,42.9), null);


(lib.epson_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AA0AwQgKgDgGgHQgGgHgEgKQgDgJAAgLQAAgLADgJQAEgKAGgHQAGgIAKgDQAJgFALAAQAMAAAKAFQAJADAGAIQAGAHAEAKQADAJAAALQAAALgDAJQgEAKgGAHQgGAHgJADQgKAFgMAAQgLAAgJgFgAA8geQgFACgEAFQgDAFgCAHIgBAMIABALQACAHADAFQAEAFAFADQAFADAHAAQAIAAAGgDQAEgDAFgFIADgMIACgLIgCgMQgBgHgCgFQgFgFgEgCQgGgDgIgBQgHABgFADgAgqAzQgHgDgGgEQgGgEgEgHQgDgGAAgKIAVAAQAAAGACADQACADAEADQACACAEABIAIAAIAGAAQAEAAADgCQADgBACgDQACgCAAgDQAAgEgDgEIgGgEIgggJQgFgBgEgDQgEgEgDgEQgDgFAAgHQAAgIADgGQADgFAGgFQAGgDAHgCQAGgCAHAAQAIAAAHABIAMAGQAFAFAEAGQADAGAAAJIgVAAQABgEgCgEIgEgEQgDgCgDgBIgIgBIgGABQAAAAgBAAQgBABAAAAQgBAAAAAAQgBABAAAAIgEAEQgCACAAADQAAABABABQAAAAAAABQAAAAAAABQABAAAAABQABACAEABIAgAJQAEABAFAEQAFADADAEQAEAHAAAHQAAAIgDAFQgDAHgFAEQgFAEgIADQgHACgLAAQgHAAgJgCgADCAzIgqhDIAABDIgVAAIAAhkIAWAAIArBCIAAhCIAUAAIAABkgAihAzIAAhkIAtAAQALAAAFADQAHACAEAFQAFAEACAGQACAGAAAFQAAAHgCAGQgCAFgFAFQgEAEgHADQgFADgLAAIgWAAIAAAkgAiKgBIAYgBIAGgDQADgBACgDQABgDAAgGQAAgEgBgDIgFgEIgGgDIgYAAgAj8AzIAAhkIBMAAIAAATIg1AAIAAAVIAxAAIAAAQIgxAAIAAAZIA3AAIAAATgADugdIgEgDIgDgEIAAgEIAAgFIADgDQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABgBIAEAAIADAAQABABABAAQAAAAABAAQAAABABAAQAAAAAAABIADADIAAAFIAAAEIgDAEIgEADIgDAAIgEAAgADvgwIgEACIgBACIgBAEIABAEIABACIAEACIADABIADgBIADgCIABgCIABgEIgBgEIgBgCIgDgCIgDAAIgDAAgAD0giIgDgFIgBAAIAAAFIgCAAIAAgMIAEAAIADABQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAAAIAAACIgCABIAAABIgCAAIAEAFgADwgpIACAAIABAAIABgCIAAgBIgEAAg");
	this.shape.setTransform(-23.8871,-12.2356,0.6026,0.6026);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.epson_Logo, new cjs.Rectangle(-39.1,-15.4,30.5,6.4), null);


(lib.frame_06_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.frame_06();
	this.instance.setTransform(82.05,-142,0.5643,0.5643);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.frame_06_1, new cjs.Rectangle(82.1,-142,70.5,77.9), null);


(lib.endFrame_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.endFrame();
	this.instance.setTransform(18.95,-141.05,0.2974,0.2974);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.endFrame_mc, new cjs.Rectangle(19,-141,95.1,54.400000000000006), null);


(lib.speedometer_Needle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.needle();
	this.instance.setTransform(4.6,-2.4,0.7523,0.7523,0,0,0,0.2,-0.1);

	this.instance_1 = new lib.needle_body();
	this.instance_1.setTransform(-1.3,3.5,0.7523,0.7523,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.speedometer_Needle, new cjs.Rectangle(-4.5,-7.1,13.6,13.8), null);


(lib.Speedometer_Anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// speedometer_Needle
	this.instance = new lib.speedometer_Needle();
	this.instance.setTransform(45.5,56.4,1,1,-98.526,0,0,-1.4,3.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({regX:-1.3,regY:3.3,rotation:10.5663,x:45.45,y:56.35},17,cjs.Ease.quartInOut).wait(12).to({rotation:10.5663},0).to({_off:true},1).wait(269));

	// speedometer_mc
	this.instance_1 = new lib.speedometer_mc();
	this.instance_1.setTransform(41.85,47.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(33).to({_off:true},1).wait(269));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(25.8,30.9,39.10000000000001,34.199999999999996);


(lib.printer_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// paper_shdw
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],0,-4.1,0,3.9).s().p("Ap3AoIAAhQITvAAIAABQg");
	this.shape.setTransform(140.55,168.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(40).to({_off:true},1).wait(262));

	// paper_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("Aq9M0IAA5nIV7AAIAAZng");
	var mask_graphics_40 = new cjs.Graphics().p("Aq9M0IAA5nIV7AAIAAZng");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:147.275,y:249.45}).wait(40).to({graphics:mask_graphics_40,x:147.275,y:249.45}).wait(1).to({graphics:null,x:0,y:0}).wait(262));

	// paper
	this.instance = new lib.paper_mc();
	this.instance.setTransform(146,79.2);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:242.2},33,cjs.Ease.quadInOut).wait(7).to({_off:true},1).wait(262));

	// Layer_2
	this.instance_1 = new lib.printer_shdw();
	this.instance_1.setTransform(141.15,164.3,1,0.4068);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:327.5,alpha:0.5781},33,cjs.Ease.quadInOut).wait(7).to({_off:true},1).wait(262));

	// printer_01
	this.instance_2 = new lib.printer_01_1();
	this.instance_2.setTransform(153.55,168.05);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(40).to({_off:true},1).wait(262));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(31.1,99.7,236.00000000000003,236);


(lib.inkDrip_Anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// ink_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_6 = new cjs.Graphics().p("ABGFEQhHgnAAhhQABgjAUgxQAphiBdhFIBJBdQBJBpgCA1QgBAmgUAmQgoBNhfADQgkAAgkgUg");
	var mask_graphics_44 = new cjs.Graphics().p("ABGFEQhHgnAAhhQABgjAUgxQAphiBdhFIBJBdQBJBpgCA1QgBAmgUAmQgoBNhfADQgkAAgkgUg");
	var mask_graphics_106 = new cjs.Graphics().p("ABGFEQhHgnAAhhQABgjAUgxQAphiBdhFIBJBdQBJBpgCA1QgBAmgUAmQgoBNhfADQgkAAgkgUg");
	var mask_graphics_109 = new cjs.Graphics().p("ABGFEQhHgnAAhhQABgjAUgxQAphiBdhFIBJBdQBJBpgCA1QgBAmgUAmQgoBNhfADQgkAAgkgUg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(6).to({graphics:mask_graphics_6,x:29.7791,y:34.375}).wait(38).to({graphics:mask_graphics_44,x:29.7791,y:34.375}).wait(1).to({graphics:null,x:0,y:0}).wait(61).to({graphics:mask_graphics_106,x:29.7791,y:34.375}).wait(1).to({graphics:null,x:0,y:0}).wait(2).to({graphics:mask_graphics_109,x:29.7791,y:34.375}).wait(1).to({graphics:null,x:0,y:0}).wait(193));

	// Layer_27
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjUIAZgJQAggKAigEQBrgNBSA0QBWA4BdgcQBFgUAngwIgMHHIoLAUQgHhwgIhwQgPjggCgDg");
	this.shape.setTransform(44.15,94.896);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#2A3283").s().p("AkKAPQgPjggCgDIAZgJQAggKAigEQBqgNBTA0QBWA4BdgcQBFgUAngwIgMHHIoLAUIgPjgg");
	this.shape_1.setTransform(44.15,94.896);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjUIAZgKQAlgKAdgDQAMgCANAAQBbgFBJAuQARALASAIQBGAeBKgWQAegJAYgOQAegRAVgXQADAPgBASIgLGiIoLAUQgHh3gHhqQAAgDAAgEQgPjZgDgCg");
	this.shape_2.setTransform(44.1042,94.7298);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#2A3283").s().p("AkJAOIAAgHQgPjZgDgCIAZgKQAlgKAdgDIAZgCQBbgFBJAuQARALASAIQBGAeBKgWQAegJAYgOQAegRAVgXQADAPgBASIgLGiIoLAUIgOjhg");
	this.shape_3.setTransform(44.1042,94.7298);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjVIAZgJQAkgKAdgDQANgBAMAAQBbgEBJArQARALASAHQBGAcBKgWQAegIAYgOQAegQAVgXQAEAPgBASIgLGiIoKAVQgIh3gHhqQAAgDAAgEQgPjZgDgCg");
	this.shape_4.setTransform(44.1031,94.2368);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#2A3283").s().p("AkJANIAAgHQgPjZgDgCIAZgJQAkgKAdgDIAZgBQBbgEBJArQARALASAHQBGAcBKgWQAegIAYgOQAegQAVgXQAEAPgBASIgLGiIoKAVIgPjhg");
	this.shape_5.setTransform(44.1031,94.2368);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjXIAZgHQAkgIAcgDQANgBAMAAQBcgCBJAnQAQAKASAHQBFAXBKgVQAegIAZgNQAdgPAWgVQAFAPAAARIgMGiIoKAVQgIh2gHhqQAAgDAAgEQgPjZgDgDg");
	this.shape_6.setTransform(44.1,93.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#2A3283").s().p("AkJAMIAAgHQgPjZgDgDIAZgHQAkgIAdgDIAZgBQBbgCBJAnQAQAKASAHQBFAXBKgVQAegIAZgNQAdgPAXgVQADAPAAARIgKGiIoKAVIgQjgg");
	this.shape_7.setTransform(44.1,93.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjXIAZgGQAjgGAcgCQANAAAMAAQBbAABKAiQAPAJASAFQBGASBIgUQAfgIAZgLQAcgOAXgTQAGAPABAPIgMGiIgXAEInyATQgJh1gHhqQAAgEAAgDQgPjagDgDg");
	this.shape_8.setTransform(44.1,91.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#2A3283").s().p("AkJANIAAgHQgPjagDgDIAZgGQAkgGAcgCIAYAAQBbAABKAiQAQAJARAFQBFASBJgUQAfgIAZgLQAdgOAWgTQAGAPAAAPIgKGiIgYAEInyATIgQjfg");
	this.shape_9.setTransform(44.1,91.875);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjWIAYgFQAjgDAcgBQAMAAAMABQBbADBJAaQAQAHASAEQBEALBJgSQAegIAZgKQAdgMAYgRQAHAPACAOIgLGjIgWAGInzATQgKh1gHhrQAAgDAAgDQgPjagDgDg");
	this.shape_10.setTransform(44.125,90);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#2A3283").s().p("AkJANIAAgHQgPjZgDgDIAYgFQAjgEAcAAIAYABQBbADBJAaQAQAHASADQBEANBJgUQAegHAZgKQAdgNAYgQQAHAPACAOIgLGjIgWAGInzATIgRjgg");
	this.shape_11.setTransform(44.125,90);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjWIAXgCQAjgBAbABQAMAAAMABQBbAHBJASQAQAFARABQBEAEBHgSQAegHAbgIQAcgKAZgNQAKAPACALIgLGkIgUAIIn0ATQgLh0gHhrQAAgDAAgEQgPjagDgDg");
	this.shape_12.setTransform(44.15,87.725);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#2A3283").s().p("AkJAOIAAgHQgPjagCgDIAWgCQAjgBAbABIAZABQBaAHBJASQAQAFARABQBDAEBIgSIA4gPQAcgKAagNQAJAPADALIgMGkIgTAIIn1ATQgKh0gHhrg");
	this.shape_13.setTransform(44.15,87.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjWIAXABQAhACAbACQAMACAMACQBbALBIAHQAQADARgBQBCgHBHgQQAegHAbgFQAcgIAbgIQAMAOADAJIgLGlIgSAKIn1ATQgMhzgHhrQAAgEAAgDQgPjagDgEg");
	this.shape_14.setTransform(44.15,85.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#2A3283").s().p("AkJAOIAAgHQgPjZgCgEIAWABIA8AEIAYAEQBbALBJAHQAPADARgBQBCgHBHgQIA5gMIA3gQQALAPAEAIIgMGlIgRAKIn1ATQgMhzgHhsg");
	this.shape_15.setTransform(44.15,85.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjWIAWAEQAhAGAaAFQALACAMACQBaARBKgGQAPABAQgEQBBgRBGgPQAegGAbgDQAcgFAdgDQAOAOAFAFIgLGmIgPANIn3ATQgNhygHhrQAAgEAAgDQgPjagDgFg");
	this.shape_16.setTransform(44.175,81.925);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#2A3283").s().p("AkJAQIAAgHQgPjagDgFIAWAEIA7ALIAXAEQBaARBKgGQAPABAQgEQBBgRBGgPQAegGAbgDQAcgFAdgDIATATIgLGmIgPANIn3ATQgNhygHhrg");
	this.shape_17.setTransform(44.175,81.925);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjVIAVAHQAgAMAZAGQAMADALADQBaAWBJgTQAQgDAPgGQBAgeBEgNQAegGAdABQAbgCAfACQARAOAGACIgLGnIgMAQIn4ATQgPhxgHhrQAAgEAAgDQgPjbgDgFg");
	this.shape_18.setTransform(44.175,78.3306);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#2A3283").s().p("AkJASIAAgHQgPjbgDgFIAVAHQAgAMAZAGIAXAGQBaAWBJgTQAQgDAPgGQBAgeBEgNQAegGAdABQAbgCAfACQARAOAGACIgLGnIgMAQIn4ATQgPhxgHhrg");
	this.shape_19.setTransform(44.175,78.3306);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjPIAVALQAeAQAYAJQALAEAMAEQBZAcBKgiQAPgGAOgKQA+gsBEgLQAegFAdAEQAbABAhAJQAVAOAHgDIgLGpIgJATIn6AUQgQhwgHhsQAAgDAAgEQgPjbgDgFg");
	this.shape_20.setTransform(44.2,73.8611);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#2A3283").s().p("AkKAYIAAgHQgOjbgDgFIAUALQAfAQAYAJIAXAIQBZAcBJgiQAQgGAOgKQA+gsBEgLQAegFAdAEQAbABAhAJQAVAOAHgDIgLGpIgJATIn6AUQgQhwgIhsg");
	this.shape_21.setTransform(44.2,73.8611);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjIIATAPQAeAWAXALQALAGALAFQBZAjBJgzQAPgKAOgOQA8g7BCgJQAegEAfAIQAZAFAkAPQAaAOAIgHIgLGqIgFAXIn8AUQgShugHhtQAAgDAAgEQgPjbgDgGg");
	this.shape_22.setTransform(44.225,68.8083);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#2A3283").s().p("AkJAgIAAgHQgPjbgDgGIATAPQAeAWAXALIAWALQBZAjBJgzQAPgKAOgOQA8g7BCgJQAegEAfAIQAZAFAkAPQAaAOAIgHIgLGqIgFAXIn8AUQgShugHhtg");
	this.shape_23.setTransform(44.225,68.8083);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#2A3283").ss(2,1,1).p("Akbi/IAZAbQAfAfAhAQQBqA0BVhuQBUhwBjAmQAZAJAnAXQAdAPALgNIgMHHIoLAUQgHhwgIhxQgPjggCgCg");
	this.shape_24.setTransform(44.25,63.2187);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#2A3283").s().p("AkJAjQgQjggCgCIAZAbQAfAfAiAQQBpA0BVhuQBVhwBiAmQAZAJAnAXQAdAPALgNIgMHHIoLAUIgOjhg");
	this.shape_25.setTransform(44.25,63.2187);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjRIAWAQQAcATAfAKQBmAhBhg+QBmg+BbATQAYADAiAKQAYAGAMgQIgMHHIoLAUQgHhwgIhxQgPjggCgCg");
	this.shape_26.setTransform(44.25,59.8861);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#2A3283").s().p("AkJARQgQjggCgCIAWAQQAcATAgAKQBkAhBig+QBlg+BbATQAZADAiAKQAXAGANgQIgMHHIoLAUIgOjhg");
	this.shape_27.setTransform(44.25,59.8861);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjVIATAIQAZAIAfAGQBgAQBtgWQB0gSBUABQAYgBAdgCQAUAAAOgUIgMHHIoLAUQgHhwgIhwQgPjhgCgCg");
	this.shape_28.setTransform(44.25,55.85);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#2A3283").s().p("AkJAOQgQjhgCgCIAUAIQAZAIAeAGQBhAQBsgWQB0gSBUABIA1gCQAUgBAOgUIgMHHIoLAUIgOjgg");
	this.shape_29.setTransform(44.25,55.85);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjVIASAAQAXABAdABQBeAEB0AKQCBAQBOgLQAYgFAZgMQARgFAOgXIgMHHIoLAUQgHhwgHhwQgPjhgDgCg");
	this.shape_30.setTransform(44.2,52.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#2A3283").s().p("AkKANQgOjfgDgDIASAAIA0ACQBdADB1ALQCAARBPgMQAYgFAZgMQAQgGAPgWIgMHHIoLAUIgPjhg");
	this.shape_31.setTransform(44.2,52.3);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjVIAQgGQAWgGAcgCQBbgGB7AkQCKAsBKgXQAXgIAXgTQAOgKAPgYIgMHHIoLAUQgHhwgHhwQgPjhgDgCg");
	this.shape_32.setTransform(44.2,49.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#2A3283").s().p("AkKANQgOjggDgCIAQgGQAWgFAcgDQBbgGB7AkQCKAsBKgWQAXgJAXgSQAOgLAPgYIgMHHIoLAUIgPjhg");
	this.shape_33.setTransform(44.2,49.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjTIAPgKQAVgLAbgEQBZgOCAA3QCQA/BHgeQAYgKAUgYQAMgOAQgZIgMHHIoLAUQgHhwgHhxQgPjggDgCg");
	this.shape_34.setTransform(44.2,47.358);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#2A3283").s().p("AkKAPQgOjggDgCIAPgKQAVgLAbgEQBYgOCBA3QCQA/BHgeQAXgKAVgYQAMgOAQgZIgMHHIoLAUIgPjhg");
	this.shape_35.setTransform(44.2,47.358);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjPIAOgMQAUgOAbgGQBYgSCDBCQCUBLBGgjQAXgLATgcQALgPAQgaIgMHHIoLAUQgHhwgHhxQgPjggDgCg");
	this.shape_36.setTransform(44.2,45.7725);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#2A3283").s().p("AkKATQgOjggDgCIAOgMQAUgOAbgGQBYgSCDBCQCUBLBFgjQAYgLASgcQALgPARgaIgMHHIoLAUIgPjhg");
	this.shape_37.setTransform(44.2,45.7725);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("#2A3283").ss(2,1,1).p("AkbjOIAOgNQAUgPAbgGQBXgUCEBGQCWBPBEgkQAXgMATgdQALgPAQgbIgMHHIoLAUQgHhwgHhxQgPjggDgCg");
	this.shape_38.setTransform(44.2,45.2515);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#2A3283").s().p("AkKAUQgOjggDgCIAOgNQAUgPAbgGQBWgUCFBGQCWBPBEgkQAXgMATgdIAbgqIgMHHIoLAUIgPjhg");
	this.shape_39.setTransform(44.2,45.2515);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18,this.shape_19,this.shape_20,this.shape_21,this.shape_22,this.shape_23,this.shape_24,this.shape_25,this.shape_26,this.shape_27,this.shape_28,this.shape_29,this.shape_30,this.shape_31,this.shape_32,this.shape_33,this.shape_34,this.shape_35,this.shape_36,this.shape_37,this.shape_38,this.shape_39];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},6).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_19},{t:this.shape_18}]},1).to({state:[{t:this.shape_21},{t:this.shape_20}]},1).to({state:[{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_25},{t:this.shape_24}]},1).to({state:[{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_29},{t:this.shape_28}]},1).to({state:[{t:this.shape_31},{t:this.shape_30}]},1).to({state:[{t:this.shape_33},{t:this.shape_32}]},1).to({state:[{t:this.shape_35},{t:this.shape_34}]},1).to({state:[{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},19).to({state:[]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},61).to({state:[]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},2).to({state:[]},1).wait(193));

	// inkDrop
	this.instance = new lib.ink_drop();
	this.instance.setTransform(63.6,49.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(44).to({_off:true},1).wait(61).to({_off:false},0).to({_off:true},1).wait(2).to({_off:false},0).to({_off:true},1).wait(193));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(28.1,26.8,31.6,42.900000000000006);


// stage content:
(lib.Epson_TSeries_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(159.9998,25.0001,0.4396,0.5556);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(299));

	// epson_Logo
	this.instance = new lib.epson_Logo();
	this.instance.setTransform(40.45,18.35,0.9135,0.9135,0,0,0,0.1,0.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0.9609},7).wait(241).to({alpha:0},0).to({alpha:1},6).wait(45));

	// T_Series_Logo
	this.instance_1 = new lib.TSeries_Logo();
	this.instance_1.setTransform(80.9,22.95,0.4623,0.4623,0,0,0,40.5,28.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(248).to({_off:false},0).to({y:26.35,alpha:1},6,cjs.Ease.quadOut).wait(45));

	// cta_btn_Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_262 = new cjs.Graphics().p("AjJBKQgeAAAAgeIAAAAIAAhXQAAgeAeAAIAAAAIGTAAQAeAAAAAeIAAAAIAABXQAAAegeAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(262).to({graphics:mask_graphics_262,x:289.2622,y:25.5001}).wait(37));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.5,-3,4.5,2.9).s().p("AiyCtIEJmVIBcA8IkJGVg");
	this.shape_1.setTransform(259.525,15.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.6,-2.9,4.5,3).s().p("AiyCuIEJmXIBcA8IkJGXg");
	this.shape_2.setTransform(260.075,15.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.6,-3,4.6,3).s().p("Ai0CvIEMmZIBdA7IkMGag");
	this.shape_3.setTransform(261.725,16.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.7,-3.1,4.6,3).s().p("Ai2CyIEPmgIBeA9IkQGfg");
	this.shape_4.setTransform(264.5,16.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.8,-3.1,4.7,3.1).s().p("Ai6C1IEVmnIBgA+IkVGng");
	this.shape_5.setTransform(268.35,18.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-4.8,-3.2,4.8,3.1).s().p("Ai+C5IEbmxIBhBAIkaGxg");
	this.shape_6.setTransform(273.3,19.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5,-3.2,5,3.3).s().p("AjDC+IEjm8IBkBBIkjG8g");
	this.shape_7.setTransform(279.375,21.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.2,-3.4,5.1,3.3).s().p("AjJDEIErnKIBoBDIksHKg");
	this.shape_8.setTransform(286.55,23.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.3,-3.4,5.3,3.5).s().p("AjQDLIE2naIBrBFIk2Hag");
	this.shape_9.setTransform(294.525,26.525);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.5,-3.6,5.4,3.5).s().p("AjWDRIE/noIBuBHIlAHog");
	this.shape_10.setTransform(301.7,28.825);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.7,-3.7,5.5,3.6).s().p("AjbDWIFHn0IBwBJIlHH0g");
	this.shape_11.setTransform(307.775,30.75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.7,-3.7,5.7,3.8).s().p("AjfDaIFNn+IByBLIlNH+g");
	this.shape_12.setTransform(312.725,32.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.8,-3.8,5.8,3.8).s().p("AjjDeIFToGIB0BNIlTIEg");
	this.shape_13.setTransform(316.575,33.55);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.9,-3.8,5.8,3.8).s().p("AjlDfIFVoKIB2BNIlWIKg");
	this.shape_14.setTransform(319.35,34.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-6,-3.9,5.8,3.8).s().p("AjnDhIFYoOIB3BNIlZIOg");
	this.shape_15.setTransform(321,34.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-11,-7.2,11,7.2).s().p("AmvGjIKDvVIDcCQIqCPVg");
	this.shape_16.setTransform(321.5268,35.1618,0.537,0.537);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},262).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).wait(22));

	// learnMore_CTA
	this.instance_2 = new lib.learnMore_CTA();
	this.instance_2.setTransform(289.25,25.5,0.4995,0.4995);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(254).to({_off:false},0).to({alpha:1},8).wait(37));

	// endFrame_mc
	this.instance_3 = new lib.endFrame_mc();
	this.instance_3.setTransform(157.6,118.5,0.8206,0.8206,0,0,0,0,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(248).to({_off:false},0).to({regY:0,scaleX:0.9518,scaleY:0.9518,x:150.4,y:133.8,alpha:1},6,cjs.Ease.quadOut).wait(45));

	// Layer_35 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_207 = new cjs.Graphics().p("AVSDMQgDgCAAgEQAAgEADgDQADgDAEAAQAEAAACADQADADAAAEQAAAEgDACQgCADgEAAQgEAAgDgDg");
	var mask_1_graphics_208 = new cjs.Graphics().p("AgNAPQgGgHAAgIQAAgHAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAHQAAAIgGAHQgGAFgIAAQgHAAgGgFg");
	var mask_1_graphics_209 = new cjs.Graphics().p("AgUAVQgJgJAAgMQAAgMAJgIQAJgJALAAQAMAAAJAJQAJAIAAAMQAAAMgJAJQgJAJgMAAQgLAAgJgJg");
	var mask_1_graphics_210 = new cjs.Graphics().p("AgbAcQgLgMAAgQQAAgPALgMQAMgLAPAAQAQAAAMALQALAMAAAPQAAAQgLAMQgMALgQAAQgPAAgMgLg");
	var mask_1_graphics_211 = new cjs.Graphics().p("AggAhQgOgOAAgTQAAgTAOgOQAOgNASAAQAUAAAOANQANAOAAATQAAATgNAOQgOAOgUAAQgSAAgOgOg");
	var mask_1_graphics_212 = new cjs.Graphics().p("AgmAnQgQgQAAgXQAAgWAQgQQAQgQAWAAQAWAAARAQQAQAQAAAWQAAAXgQAQQgRAQgWAAQgWAAgQgQg");
	var mask_1_graphics_213 = new cjs.Graphics().p("AgqArQgSgRAAgaQAAgZASgRQARgTAZABQAZgBATATQASARAAAZQAAAagSARQgTATgZgBQgZABgRgTg");
	var mask_1_graphics_214 = new cjs.Graphics().p("AgvAwQgUgUAAgcQAAgbAUgUQAUgUAbABQAcgBAUAUQATAUAAAbQAAAcgTAUQgUATgcABQgbgBgUgTg");
	var mask_1_graphics_215 = new cjs.Graphics().p("AgyAzQgWgVAAgeQAAgdAWgVQAVgWAdAAQAeAAAWAWQAVAVAAAdQAAAegVAVQgWAWgeAAQgdAAgVgWg");
	var mask_1_graphics_216 = new cjs.Graphics().p("Ag1A3QgXgXAAggQAAgfAXgWQAWgXAfAAQAgAAAXAXQAWAWAAAfQAAAggWAXQgXAWggAAQgfAAgWgWg");
	var mask_1_graphics_217 = new cjs.Graphics().p("Ag4A5QgYgYABghQgBghAYgXQAYgYAgAAQAiAAAXAYQAXAXABAhQgBAhgXAYQgXAYgiAAQggAAgYgYg");
	var mask_1_graphics_218 = new cjs.Graphics().p("Ag6A7QgZgYAAgjQAAghAZgZQAYgYAiAAQAjAAAYAYQAZAZgBAhQABAjgZAYQgYAZgjgBQgiABgYgZg");
	var mask_1_graphics_219 = new cjs.Graphics().p("Ag8A9QgZgZAAgkQAAgiAZgaQAagZAiAAQAkAAAYAZQAZAaAAAiQAAAkgZAZQgYAYgkAAQgiAAgagYg");
	var mask_1_graphics_220 = new cjs.Graphics().p("Ag8A9QgZgZgBgkQABgjAZgZQAZgZAjgBQAkABAZAZQAZAZAAAjQAAAkgZAZQgZAZgkAAQgjAAgZgZg");
	var mask_1_graphics_221 = new cjs.Graphics().p("AT0DcQgZgaAAgkQAAgkAZgZQAagaAkAAQAkAAAaAaQAZAZAAAkQAAAkgZAaQgaAZgkAAQgkAAgagZg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(207).to({graphics:mask_1_graphics_207,x:137.8054,y:20.701}).wait(1).to({graphics:mask_1_graphics_208,x:274.675,y:40.45}).wait(1).to({graphics:mask_1_graphics_209,x:274.675,y:40.45}).wait(1).to({graphics:mask_1_graphics_210,x:274.7,y:40.45}).wait(1).to({graphics:mask_1_graphics_211,x:274.675,y:40.425}).wait(1).to({graphics:mask_1_graphics_212,x:274.7,y:40.4}).wait(1).to({graphics:mask_1_graphics_213,x:274.7,y:40.4}).wait(1).to({graphics:mask_1_graphics_214,x:274.7,y:40.4}).wait(1).to({graphics:mask_1_graphics_215,x:274.675,y:40.375}).wait(1).to({graphics:mask_1_graphics_216,x:274.7,y:40.35}).wait(1).to({graphics:mask_1_graphics_217,x:274.7,y:40.375}).wait(1).to({graphics:mask_1_graphics_218,x:274.7,y:40.35}).wait(1).to({graphics:mask_1_graphics_219,x:274.7,y:40.35}).wait(1).to({graphics:mask_1_graphics_220,x:274.7,y:40.35}).wait(1).to({graphics:mask_1_graphics_221,x:141.7073,y:24.5286}).wait(27).to({graphics:null,x:0,y:0}).wait(51));

	// zoomIn
	this.instance_4 = new lib.zoomIn_1();
	this.instance_4.setTransform(274.95,40.35,0.1924,0.1924,0,0,0,-10.2,-12.8);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(207).to({_off:false},0).wait(34).to({alpha:0},6).to({_off:true},1).wait(51));

	// txt_precisionCore
	this.instance_5 = new lib.txt_precisionCore();
	this.instance_5.setTransform(145.65,216.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(200).to({_off:false},0).to({alpha:1},7).wait(34).to({alpha:0},6).to({_off:true},1).wait(51));

	// Frame_06
	this.instance_6 = new lib.frame_06_1();
	this.instance_6.setTransform(150.4,110.4);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(191).to({_off:false},0).to({y:124.8,alpha:1},12,cjs.Ease.quadOut).wait(38).to({alpha:0},6).to({_off:true},1).wait(51));

	// inkDrip_Anim
	this.instance_7 = new lib.inkDrip_Anim("single",0);
	this.instance_7.setTransform(48.45,14.5,0.6122,0.6122,0,0,0,44,49.1);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(135).to({_off:false},0).to({y:24.5,alpha:1,mode:"synched",loop:false},5,cjs.Ease.quadOut).wait(45).to({mode:"single",startPosition:109},0).to({alpha:0,startPosition:106},6).to({_off:true},1).wait(107));

	// txt_inkCartridges
	this.instance_8 = new lib.txt_inkCartridges();
	this.instance_8.setTransform(172.6,61.05);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(146).to({_off:false},0).to({x:176.2,alpha:1},5,cjs.Ease.quadOut).wait(34).to({alpha:0},6).to({_off:true},1).wait(107));

	// txt_highCapacity
	this.instance_9 = new lib.txt_highCapacity();
	this.instance_9.setTransform(162.55,34.1);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(135).to({_off:false},0).to({x:174.55,alpha:1},5,cjs.Ease.quadOut).wait(45).to({alpha:0},6).to({_off:true},1).wait(107));

	// txt_fastPrintSpeed
	this.instance_10 = new lib.txt_fastPrintSpeed();
	this.instance_10.setTransform(166.25,48.55);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(90).to({_off:false},0).to({x:182.25,alpha:1},6,cjs.Ease.quadOut).wait(34).to({x:189.45,alpha:0},5,cjs.Ease.quadIn).to({_off:true},1).wait(163));

	// Speedometer_Anim
	this.instance_11 = new lib.Speedometer_Anim("synched",0,false);
	this.instance_11.setTransform(37.1,26.85,0.7416,0.7416,0,0,0,45.5,48);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(90).to({_off:false},0).to({x:43.5,alpha:1},6,cjs.Ease.quadOut).wait(34).to({startPosition:0},0).to({x:50.7,alpha:0},5,cjs.Ease.quadIn).to({_off:true},1).wait(163));

	// txt_engineered
	this.instance_12 = new lib.txt_engineered();
	this.instance_12.setTransform(74.4,70.2);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(42).to({_off:false},0).to({x:78.4,alpha:1},6,cjs.Ease.quadOut).wait(30).to({x:81.4,alpha:0},5,cjs.Ease.quadIn).to({_off:true},1).wait(215));

	// txt_enhance
	this.instance_13 = new lib.txt_enhance();
	this.instance_13.setTransform(90,90.2);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(44).to({_off:false},0).to({x:94,alpha:1},6,cjs.Ease.quadOut).wait(30).to({x:97,alpha:0},5,cjs.Ease.quadIn).to({_off:true},1).wait(213));

	// T_Series_Logo
	this.instance_14 = new lib.TSeries_Logo();
	this.instance_14.setTransform(124.75,21.3,0.5934,0.5934,0,0,0,40.2,28.8);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(2).to({_off:false},0).to({y:26.5,alpha:1},6).wait(25).to({alpha:0},6).to({_off:true},1).wait(259));

	// Layer_8
	this.instance_15 = new lib.printer_animation("single",0);
	this.instance_15.setTransform(269.5,20.65,0.2019,0.2019,0,0,0,149.3,169.9);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:263.5,alpha:1},8,cjs.Ease.quadOut).wait(82).to({mode:"synched",loop:false},0).wait(40).to({mode:"single",startPosition:40},0).wait(55).to({startPosition:40},0).to({alpha:0},6).to({_off:true},1).wait(107));

	// background
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_17.setTransform(159.9998,25.0001,0.4396,0.5556);

	this.timeline.addTween(cjs.Tween.get(this.shape_17).wait(299));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(159,-6.6,162,67.3);
// library properties:
lib.properties = {
	id: 'B61A9D64C8DF436F89671266C87EE568',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"endFrame.jpg", id:"endFrame"},
		{src:"frame_06.jpg", id:"frame_06"},
		{src:"paper.jpg", id:"paper"},
		{src:"printer_01.jpg", id:"printer_01"},
		{src:"zoomIn.jpg", id:"zoomIn"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['B61A9D64C8DF436F89671266C87EE568'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;