(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.cartridges_01 = function() {
	this.initialize(img.cartridges_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1020,250);


(lib.paintColors = function() {
	this.initialize(img.paintColors);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,513,600);


(lib.printer = function() {
	this.initialize(img.printer);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,373,292);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_twoYears = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A29BFQgJgEgGgGQgGgIgDgJQgDgLAAgLQAAgMADgJQAEgJAGgIQAGgHAJgEQAJgEAMAAQAIAAAIACQAHACAGAEQAFAEAEAHQAEAFABAJIgOAAQgCgLgIgGQgIgFgLAAQgJAAgHADQgGAEgFAGQgEAGgCAHQgCAHAAAIQAAAJACAHQACAIAEAHQAFAFAGAEQAHAEAJgBQAHAAAGgCQAFgCADgEQAFgEACgGQACgFAAgHIAOAAQgCAUgMALQgLALgUAAQgMAAgJgFgAHzBHQgMgDgIgGQgIgGgFgKQgGgJABgNIAeAAQAAAHADAFQACAFAEADIAKAFIAMABIAJAAIAJgDQAEgDADgDQADgEAAgFQAAgFgEgEQgDgEgGgCIgsgNQgIgDgGgDQgGgFgEgGQgDgIAAgJQAAgLAEgIQAFgIAHgGQAIgEAKgEQAJgCAKAAQALAAAKACQAKADAIAFQAIAGAFAJQAEAIAAAMIgeAAQAAgGgDgFQgCgDgEgDIgIgDIgLgBIgHABIgHACIgFAGQgCADAAAEQAAAEABACQACAEAFACIAtAMQAHACAHAFQAHAEAFAHQAFAIAAAMQAAAKgEAIQgDAIgIAGQgHAGgLADQgLADgPABQgLAAgLgDgAFXA8QgQgOAAgdIAAhWIAgAAIAABWIABAMQABAFADAFQADADAGADQAFADAKAAQARAAAGgHQAGgIAAgQIAAhWIAfAAIAABWQAAAdgPAOQgRAOgcAAQgdAAgQgOgADWBEQgOgFgIgLQgJgJgFgNQgEgOAAgQQAAgOAEgOQAFgNAJgKQAIgKAOgGQANgGAQAAQARAAAMAGQANAGAJAKQAJAKAEANQAGAOAAAOQAAAQgGAOQgEANgJAJQgJALgNAFQgMAGgRAAQgQAAgNgGgADhgrQgHAEgFAHQgFAHgBAIQgDAKAAAHQAAAJADAJQABAIAFAHQAFAGAHAFQAIAEAKAAQALAAAHgEQAHgFAFgGQAEgHACgIQACgJAAgJQAAgHgCgKQgCgIgEgHQgFgHgHgEQgHgDgLgBQgKABgIADgAg6A8QgQgOAAgdIAAhWIAfAAIAABWIABAMQABAFADAFQAEADAFADQAGADAKAAQAPAAAGgHQAHgIAAgQIAAhWIAfAAIAABWQAAAdgQAOQgQAOgbAAQgdAAgQgOgAi0BEQgNgFgKgLQgJgJgEgNQgFgOAAgQQAAgOAFgOQAEgNAJgKQAKgKANgGQAMgGAQAAQAMAAALAEQAKADAIAGQAJAHAFAJQAFAKABAMIgdAAQgBgFgDgFQgDgEgEgEIgJgGIgMgBQgKABgHADQgIAEgEAHQgEAHgDAIQgCAKAAAHQAAAJACAJQADAIAEAHQAEAGAIAFQAHAEAKAAQAPAAAIgJQAIgIACgPIAeAAQgCAOgEAKQgFALgIAIQgJAHgKAEQgMAEgNAAQgQAAgMgGgASHBGQgHgDgEgFQgFgGgCgGQgCgIAAgIQAAgIACgIQACgGAFgGQAEgFAHgDQAHgCAJAAQAJAAAHACQAGADAFAFQAFAGACAGQACAIAAAIQAAAIgCAIQgCAGgFAGQgFAFgGADQgHADgJAAQgJAAgHgDgASOAHQgEACgEAEQgDAEgCAFQgBAGAAAGQAAAHABAFQACAFADAEQAEADAEACQAEACAFAAQAFAAAEgCQAEgCAEgDQADgEABgFQACgFAAgHQAAgGgCgGQgBgFgDgEQgEgEgEgCQgEgCgFAAQgFAAgEACgAOUBHQgFgCgDgDQgDgEgBgFIgBgLIAAgwIAMAAIAAAyQAAAHAEAEQAEADAHAAQAGAAAEgCQAEgBADgDIAEgHQACgFAAgFIAAgpIAMAAIAABJIgMAAIAAgLQgEAGgGAEQgGADgIAAQgIAAgFgCgANJBGQgHgDgFgFQgEgGgDgGQgCgIAAgIQAAgIACgIQADgGAEgGQAFgFAHgDQAHgCAIAAQAJAAAHACQAHADAEAFQAFAGACAGQADAIAAAIQAAAIgDAIQgCAGgFAGQgEAFgHADQgHADgJAAQgIAAgHgDgANPAHQgEACgDAEQgDAEgCAFQgCAGAAAGQAAAHACAFQACAFADAEQADADAEACQAEACAFAAQAFAAAEgCQAFgCADgDQADgEACgFQACgFAAgHQAAgGgCgGQgCgFgDgEQgDgEgFgCQgEgCgFAAQgFAAgEACgAKpBGQgDgCAAgHQgFAHgGACQgHADgIAAIgKgBQgEgBgEgDQgDgCgCgEQgCgEAAgGQAAgGACgEQACgFAEgCQADgCAFgBIAbgGQAEgBACgCQACgCAAgDQAAgEgCgCQgBgDgDgBIgFgCIgGgBQgIAAgFADQgFAEgBAIIgMAAQAAgHADgFQADgFAEgDQAEgBAGgCIAMgBIAKABIAJACQAEABACAFQADAEAAAGIAAAtQAAABABAAQAAABAAAAQABAAAAAAQABAAABAAIAEgBIAAAKQgEACgFAAQgFAAgDgDgAKfAjIgQADIgHACQgEACgCACQgCACAAAFIABAGIAEADQAAAAABAAQAAAAABABQAAAAABAAQABAAAAAAIAGABQAGAAAEgCIAHgDQADgDABgDIABgGIAAgMQgCACgEAAgAqoBGQgDgCAAgHQgFAHgGACQgHADgIAAIgKgBQgEgBgDgDQgEgCgCgEQgCgEAAgGQAAgGACgEQADgFADgCQAEgCAEgBIAbgGQAEgBACgCQACgCAAgDQAAgEgCgCIgDgEIgGgCIgGgBQgIAAgFADQgFAEAAAIIgNAAQABgHACgFQADgFAEgDQAEgBAGgCIAMgBIAKABIAJACQAEABADAFQACAEAAAGIAAAnIABAGQAAABAAAAQAAABABAAQAAAAABAAQAAAAABAAIAEgBIAAAKQgDACgGAAQgFAAgDgDgAqxAjIgRADIgHACIgGAEQgCACAAAFQAAAEACACIADADIAEABIAGABQAGAAAEgCQAFgBACgCQADgDABgDIACgGIAAgMQgCACgEAAgAxRBIQgGgBgFgDQgEgEgDgEQgCgFAAgHIAMAAQAAAEACADIAEAEQADACAEAAIAHABIAGAAIAGgCIAFgDQABgCAAgEQAAgFgDgCQgEgCgFgCIgMgDIgMgDQgFgDgEgEQgEgEAAgHQAAgGADgEIAGgGIAJgDIAKgBIAMABQAGABAEACQAEADACAEQADAFAAAGIgMAAQgBgEgBgBIgEgFIgGgCIgGgBIgFABIgFABIgEAEQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAABQAAAEADACIAFADIAaAHQAEABAEACQADADACAEQACADAAAGQAAAGgCAFQgDAEgFADQgEADgGABIgLABIgMgBgAyaBGQgGgDgFgFQgEgFgDgHQgCgIAAgIQAAgJADgHQACgHAFgGQAEgEAHgDQAHgCAHAAQAKAAAHAEQAGADAEAGQAEAHACAHIABAPIg4AAQAAAFABAEQABAEADAEQADADAFACQAEACAGAAQAIAAAFgDQAFgEACgHIAMAAQgCAMgJAHQgIAGgNAAQgJAAgHgDgAyUAHQgEACgDADQgDACgBAEQgCAFAAAEIArAAIgCgJIgEgGQgDgDgEgCQgEgCgFAAQgEAAgEACgA1fBGQgHgDgFgFQgFgGgCgGQgCgIAAgIQAAgIACgIQACgGAFgGQAFgFAHgDQAGgCAJAAQAJAAAHACQAHADAEAFQAFAGACAGQADAIAAAIQAAAIgDAIQgCAGgFAGQgEAFgHADQgHADgJAAQgJAAgGgDgA1ZAHQgEACgDAEQgEAEgBAFQgCAGAAAGQAAAHACAFQABAFAEAEQADADAEACQAEACAFAAQAFAAAEgCQAEgCAEgDQADgEACgFQACgFAAgHQAAgGgCgGQgCgFgDgEQgEgEgEgCQgEgCgFAAQgFAAgEACgAXJBHIAAgPIAQAAIAAAPgAWyBHIgagnIgMALIAAAcIgMAAIAAhmIAMAAIAAA8IAjgfIAQAAIgeAaIAgAvgAVlBHIAAgyQAAgIgEgDQgEgEgHgBQgGAAgEACQgEACgDAEQgDADgBAEQgCAEAAAFIAAAqIgMAAIAAhJIAMAAIAAAKQAIgMAQAAQAIAAAFACQAFABADAEQADADABAFQABAFAAAGIAAAxgAUYBHIAAhJIAMAAIAABJgATKBHIAAhAIgMAAIAAgJIAMAAIAAgMQAAgJAGgFQAFgEAKAAIAEAAIAEABIAAAKIgHAAQgEAAgDABQgCACAAAFIAAALIAOAAIAAAJIgOAAIAABAgAQuBHQgEAAgCgDIgDgFIgBgIIAAgwIgNAAIAAgJIANAAIAAgXIAMAAIAAAXIAPAAIAAAJIgPAAIAAAvIABAEIABACIADAAIAKAAIAAALgAQFBHIAAgyQAAgIgEgDQgEgEgHgBQgGAAgEACQgEACgDAEQgDADgBAEQgCAEAAAFIAAAqIgMAAIAAhJIAMAAIAAAKIAAAAQAIgMAQAAQAIAAAFACQAFABADAEQADADABAFQABAFAAAGIAAAxgAMdBHIAAgwIAAgHIgCgFQgCgDgDgBQgCgBgFgBQgJABgFAFQgFAFAAAJIAAAuIgNAAIAAg4IgDgEQgBgDgDgBQgDgBgEgBQgFABgEACQgEACgDADIgDAHIgBAFIAAAuIgMAAIAAhJIALAAIAAAJIABAAQAIgLAQAAQAHAAAFACQAGADACAGQAEgFAGgDQAHgDAHAAIAKABIAIADQADADACADQACAFAAAFIAAA3gAsYBHIAAgyQAAgIgEgDQgEgEgHgBQgGAAgEACQgEACgDAEQgDADgBAEIgBAJIAAAqIgNAAIAAhmIANAAIAAAmIAAAAQABgDADgCIAGgEIAHgBIAGgBQAIAAAFACQAFABADAEQADADABAFIABALIAAAxgAtlBHQgDAAgCgDIgDgFIgBgIIAAgwIgNAAIAAgJIANAAIAAgXIAMAAIAAAXIAPAAIAAAJIgPAAIAAAvIAAAEIACACIADAAIAKAAIAAALgAuOBHIAAhJIAMAAIAABJgAu7BHIgPg7IgBAAIgPA7IgNAAIgYhJIANAAIARA8IABAAIAPg8IANAAIAQA8IAAAAIARg8IANAAIgYBJgAzFBHIAAgwIAAgHIgCgFQgCgDgDgBQgCgBgFgBQgJABgFAFQgFAFAAAJIAAAuIgNAAIAAg4IgDgEQgBgDgDgBQgDgBgEgBQgFABgEACQgEACgDADIgDAHIgBAFIAAAuIgMAAIAAhJIALAAIAAAJIABAAQAIgLAQAAQAHAAAFACQAGADACAGQAEgFAGgDQAHgDAHAAIAKABIAIADQADADACADQACAFAAAFIAAA3gABDBHIAAiMIAgAAIAABxIBEAAIAAAbgAkMBHIAAiMIAfAAIAACMgAmaBHIAAiMIA+AAQANAAAMADQALAFAJAIQAJAKAFANQAFAMAAASQAAAOgEANQgEANgIAKQgIAJgMAHQgMAFgQAAgAl7AsIAcAAQAHAAAGgCQAGgCAGgFQAFgFACgIQAEgIAAgMQAAgJgDgJQgBgJgGgGQgEgGgIgDQgIgEgLAAIgXAAgAnPBHIAAiMIAfAAIAACMgAn+BHQgCgHgBgKIgCgRQgBgLgFgFQgFgGgMAAIgfAAIAAA4IgfAAIAAiMIBMAAQAJAAAIADQAIACAFAGQAGAFADAHQACAHAAAIQAAAMgFAKQgFAJgMAEQAGACADADQAEADACAEIAEAKIAEAlIADAIgAo5gGIAiAAQAKAAAGgFQAFgEAAgLQAAgLgFgDQgGgGgKAAIgiAAgAUYgQIAAgPIAMAAIAAAPgAuOgQIAAgPIAMAAIAAAPg");
	this.shape.setTransform(36.125,36.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_twoYears, new cjs.Rectangle(-113.5,29.4,299.3,14.800000000000004), null);


(lib.txt_theAssets = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgPAQIAAgfIAfAAIAAAfg");
	this.shape.setTransform(150.05,-83.875);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AE5DBQgIgCgHgEQgGgEgFgHQgEgGgBgJIAdAAQACAIAGADQAGADAIAAQAMAAAGgHQAFgHAAgLIAAgOIAAAAQgFAIgJAEQgIAEgKAAQgMAAgIgEQgJgEgGgIQgFgHgDgKQgCgJAAgLQAAgKADgKQADgJAFgIQAGgHAJgEQAIgFALAAQALAAAIAEQAIAEAFAJIAAAAIAAgOIAcAAIAABjIgCAPQgCAIgFAHQgGAHgLAFQgLAFgSAAQgIAAgIgCgAFBBHQgEACgDAEQgEAFgBAFQgBAFAAAHIABALIAEAKQADAEAEADQAEADAHAAQAHAAAEgCQAFgDADgEQADgEACgFQABgFAAgGQAAgHgBgGQgBgFgDgFQgDgEgFgDQgEgDgIAAQgGAAgEADgAIdCcQgJgCgHgEQgHgEgEgIQgFgHAAgKIAbAAQAAAEACAEQACADAEACQACACAEABIAJABIAGAAIAGgDQADgBACgDQACgCAAgEQAAgHgJgDQgJgDgPgEIgMgDQgHgCgEgDQgFgDgDgFQgDgFAAgHQAAgKAEgGQAEgHAHgEQAGgEAJgBQAIgCAIAAQAJAAAIACQAIACAGAEQAHADAEAHQAEAGABAKIgcAAQAAgIgGgDQgGgDgHAAIgLABIgEADQgCACAAADQAAAFADACQADACAFACIAjAJQAGACAFADQAEAEADAFQADAFAAAHQAAAKgEAIQgFAHgGAEQgHAEgJACQgIACgJAAQgKAAgIgCgAGqCaQgKgEgGgIQgHgHgEgKQgEgKAAgNQAAgMAEgKQAEgKAHgIQAHgHAKgEQAKgFAMAAQAOAAAKAGQAKAFAGAJQAGAIADAMQADALgBAMIhMAAQABAOAGAHQAHAGAMAAQAJAAAGgEQAGgFACgFIAaAAQgHATgMAJQgNAIgSAAQgMAAgLgEgAG1BHQgFACgDAEQgDADgBAEIgBAHIAvAAQgCgLgFgGQgFgGgLAAQgHAAgEADgAC1CZQgJgFgGgHQgGgIgDgKQgDgLAAgLQAAgKADgKQADgKAGgIQAGgHAJgFQAIgFAMAAQAKAAAIAEQAIAEAFAIIABAAIAAg1IAdAAIAACSIgcAAIAAgOIAAAAQgFAJgJAEQgIAEgKAAQgMAAgJgFgADFBHQgFADgDAFQgDAEgBAHQgCAFAAAHIACAMQABAGADAFQADAFAFADQAFADAHAAQAHAAAFgDQAFgDADgFQACgEACgHIABgMIgBgNIgEgKQgEgFgEgDQgFgDgHAAQgHAAgFADgAjaCcQgHgCgFgEQgFgEgDgGQgCgGAAgIQAAgJADgGQADgGAFgDQAFgDAHgCIAlgGQAFgCACgCQADgCAAgFQAAgFgBgCQgCgDgCgCIgHgCIgHAAQgIAAgFAEQgFADgBAJIgdAAQABgLAEgGQAFgHAHgEQAGgEAJgCQAJgCAJAAIAQACQAIABAHADQAHADAEAGQAEAGAAAKIABBEQABAHACADIgeAAIgCgKQgGAHgKADQgJADgKAAQgIAAgGgCgAiuBqIgGABIgOACIgHACIgFADIgEAEQgBADAAAEQAAAEABACQACADACACIAGACIAHAAQAIAAAFgCQAFgDACgEQACgEABgEIAAgSgAlICaQgKgEgHgIQgHgHgDgKQgFgJAAgMQAAgNAEgKQAEgLAHgHQAHgIAKgEQAKgFAMAAQAKAAAJADQAIACAHAFQAHAFAEAIQAFAHAAAKIgcAAQgDgSgTAAQgHAAgEADQgFAEgDAFIgEALIgBAMIABALIAEALQACAFAFADQAFADAHAAQAKAAAGgGQAFgGACgKIAcAAQgDAWgOALQgNALgVAAQgMAAgKgEgAnsCaQgKgEgHgHQgHgIgEgKQgEgKAAgNQAAgMAEgLQAEgKAHgHQAHgIAKgEQAKgEAMAAQANAAAKAEQAKAEAHAIQAIAHADAKQAEALAAAMQAAANgEAKQgDAKgIAIQgHAHgKAEQgKAEgNAAQgMAAgKgEgAniBHQgFADgDAFQgDAFgBAGQgBAGAAAGIABANQABAGADAEQADAFAFADQAFADAHAAQAIAAAFgDQAFgDADgFQADgEABgGIABgNIgBgMQgBgGgDgFQgDgFgFgDQgFgDgIAAQgHAAgFADgAgPCbQgGgBgEgDQgFgCgDgFQgCgFAAgIIAAg+IgSAAIAAgUIASAAIAAgfIAdAAIAAAfIAUAAIAAAUIgUAAIAAA0QAAAHACADQADACAGAAIAJAAIAAAWIgQABgAo3CbQgHgBgEgDQgFgCgCgFQgDgFAAgIIAAg+IgSAAIAAgUIASAAIAAgfIAdAAIAAAfIAVAAIAAAUIgVAAIAAA0QAAAHADADQACACAHAAIAJAAIAAAWIgRABgABvCbIAAhqIAeAAIAABqgAAfCbIAAhqIAbAAIAAAUIABAAQACgFADgEIAIgHQAFgDAFgCQAFgCAFAAIAHABIAAAbIgLgBQgIAAgFADQgGADgDAEQgDAFgCAGQgBAGAAAHIAAAwgAh+CbIAAhqIAcAAIAAAUIAAAAIAGgJIAIgHQAEgDAGgCQAFgCAFAAIAHABIAAAbIgLgBQgIAAgFADQgGADgDAEQgEAFgBAGQgBAGAAAHIAAAwgABvAhIAAgYIAeAAIAAAYgAjkgvQgNgGgJgLQgIgKgFgOQgEgOAAgPQAAgPAEgOQAFgOAIgKQAJgLANgGQANgHASAAQARAAANAHQANAGAJALQAJAKAEAOQAFAOAAAPQAAAPgFAOQgEAOgJAKQgJALgNAGQgNAGgRAAQgSAAgNgGgAjcisQgKAFgGAJQgGAIgDALQgDALAAALQAAALADALQADAKAGAJQAGAJAKAFQAJAFAOAAQANAAAKgFQAJgFAGgJQAGgIADgLQADgLAAgLQAAgLgDgLQgDgLgGgIQgGgJgJgFQgKgFgNAAQgOAAgJAFgAEpguQgKgDgGgIQgGgHgDgKQgDgKAAgMQAAgLADgLQADgKAGgIQAGgHAKgFQAJgEANAAQAJAAAIACQAHACAHAFQAFAEAEAHQAEAHABAJIgSAAQgCgKgGgFQgHgGgLAAQgJAAgHAEQgGADgEAGQgDAGgCAHQgCAHAAAIQAAAIACAHQACAHADAFQAEAGAGADQAGADAIAAQANAAAHgHQAIgGABgNIASAAQgDAUgMALQgLAKgVAAQgMAAgJgEgADwguQgEgDAAgJQgHAJgKADQgJAEgLAAQgHAAgHgBQgGgCgFgEQgFgDgDgGQgCgFAAgIQAAgJADgGQADgGAFgDQAFgEAGgBIAmgIQAFgBADgDQADgCAAgFQAAgGgCgDQgCgEgEgCQgDgCgEAAIgIgBQgLAAgIAEQgHAFgBALIgRAAQAAgKAEgGQADgHAHgEQAGgFAIgBQAIgCAJAAIAOABQAHABAGADQAFADAEAGQADAGAAAJIABA/QABADAEAAIAFgBIAAAOQgEACgIAAQgHAAgEgEgADihfIgXADIgKADQgFACgDAEQgDAEAAAGQAAAFACADQABADADABIAHADIAIABQAIAAAGgCQAHgDADgDQAEgEACgEIACgIIAAgSQgDADgGABgABhgrIgKgCIgJgFQgEgDgDgFIAAAAIAAAOIgRAAIAAiSIARAAIAAA3IAAAAQAFgJAJgEQAJgEALAAQAMAAAJAEQAJAFAGAHQAGAIAEAKQADAKAAAMQAAALgDAKQgDAKgGAHQgGAIgKAEQgJAEgMAAgABYiFQgHADgDAGQgEAFgCAIQgCAHAAAHQAAAIACAHQACAHAEAGQAEAFAGAEQAGADAKAAQAJAAAGgDQAGgEADgGQAEgFACgIIABgPQAAgHgCgHQgCgHgEgGQgEgFgGgDQgGgEgIAAQgJAAgGAEgAHDgsIglg3IgQAPIAAAoIgRAAIAAiSIARAAIAABWIAwguIAYAAIgqAnIAtBDgAhTgsIAAiCIgwAAIAAgQIB0AAIAAAQIgwAAIAACCgAkzgsIhMh1IgBAAIAAB1IgSAAIAAiSIAVAAIBMB2IABAAIAAh2IASAAIAACSg");
	this.shape_1.setTransform(86.725,-97.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_theAssets, new cjs.Rectangle(26.1,-117.3,125.6,39), null);


(lib.txt_noMore = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMIAAgXIAXAAIAAAXg");
	this.shape.setTransform(106.575,-38.475);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgUA0QgKgEgGgHQgHgIgDgLQgDgKgBgMQAAgMAEgKQAEgLAHgHQAHgIAJgEQAKgEAKAAQAOAAAKAGQAJAGAGAJQAGAKACALQADAKgBAJIhRAAQAAAIACAGQACAHAEAFQAEAEAHADQAHADAHAAQAMAAAHgFQAHgFADgLIARAAQgDASgMAKQgNAJgSAAQgMAAgKgFgAgMgmQgGADgEAEQgEAEgCAFQgCAGgBAGIA+AAQAAgGgDgGQgCgFgEgEQgEgEgGgDQgGgDgGABQgGgBgGADg");
	this.shape_1.setTransform(97.9542,-42.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AghBMIgGgBIAAgRIAFACIAFABQAGAAADgDQAEgDACgFIAHgSIgrhrIAUAAIAfBYIABAAIAehYIATAAIgvB6IgGAOQgDAFgDAEQgEADgFACQgEABgGAAg");
	this.shape_2.setTransform(86.725,-40.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGBMIgKgDQgFgCgEgDQgEgDgDgFIgBAAIAAAOIgSAAIAAiWIASAAIAAA5IABAAQAEgJAKgEQAJgEALAAQAMAAAKAEQAJAFAGAIQAHAIADAKQADAJAAAMQAAAMgDAKQgDAKgGAIQgHAIgJAEQgJAFgNAAgAgPgRQgHAEgEAFQgEAGgBAHQgCAHAAAIQAAAIACAHQACAIAEAFQAEAGAGADQAHAEAIAAQAJAAAHgEQAGgDAEgGQAEgGABgIQACgHAAgIQAAgIgCgHQgCgHgEgFQgEgGgHgDQgGgEgIAAQgJAAgGAEg");
	this.shape_3.setTransform(75.325,-44.725);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgWBIQgKgFgGgIQgGgHgEgLQgDgKAAgMQAAgLADgKQADgKAHgIQAGgHAJgFQAKgEAMAAIAIAAIAKADQAFACAEAEQAEADADAFIABAAIAAg5IASAAIAACWIgSAAIAAgPIgBAAQgEAKgJAEQgKAEgKAAQgNAAgJgFgAgOgRQgHAEgDAFQgEAGgCAHQgCAIAAAIQAAAHACAHQACAIAFAFQAEAGAGAEQAHADAHAAQAJAAAHgEQAGgDAEgGQAEgGACgHQACgIAAgHQAAgIgCgIQgCgGgEgGQgEgGgHgDQgHgEgJAAQgIAAgGAEg");
	this.shape_4.setTransform(62.025,-44.725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA0QgKgEgIgIQgGgIgDgKQgEgKAAgMQAAgLAEgLQADgKAGgIQAIgIAKgEQAKgEALAAQAOAAAJAEQAKAEAHAIQAGAIAEAKQADALAAALQAAAMgDAKQgEAKgGAIQgHAIgKAEQgJAFgOAAQgLAAgKgFgAgMgmQgGADgFAFQgEAFgDAJQgDAHAAAJQAAAKADAHQADAJAEAFQAFAFAGADQAGACAGAAQAHAAAHgCQAFgDAFgFQAFgFADgJQACgHAAgKQAAgJgCgHQgDgJgFgFQgFgFgFgDQgHgCgHAAQgGAAgGACg");
	this.shape_5.setTransform(49.85,-42.75);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA0QgLgEgGgIQgHgIgDgKQgEgKAAgMQAAgLAEgLQADgKAHgIQAGgIALgEQAKgEALAAQAOAAAJAEQAKAEAHAIQAGAIAEAKQADALAAALQAAAMgDAKQgEAKgGAIQgHAIgKAEQgJAFgOAAQgLAAgKgFgAgMgmQgHADgEAFQgEAFgDAJQgDAHAAAJQAAAKADAHQADAJAEAFQAEAFAHADQAGACAGAAQAHAAAHgCQAFgDAFgFQAFgFADgJQACgHAAgKQAAgJgCgHQgDgJgFgFQgFgFgFgDQgHgCgHAAQgGAAgGACg");
	this.shape_6.setTransform(37.6,-42.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgPBMQgIgCgGgDQgHgEgEgGQgEgGgBgJIASAAQAAAFAEADQACADAEADIAJADIAIABQAKAAAFgEQAGgDAEgFQAFgFACgIQABgIABgJIAAgHIgBAAQgFAKgJAFQgKAFgJAAQgNAAgIgFQgJgEgHgIQgGgHgDgKQgDgJAAgLQAAgKACgKQADgLAGgIQAGgIAKgGQAJgFANAAQALAAAIAFQAJAEAFAJIABAAIAAgPIAQAAIAABiQAAAbgMAOQgNANgZAAIgPgCgAgMg6QgHADgDAGQgFAFgBAIQgCAHAAAIIABAOQACAHAEAGQADAGAGADQAGAEAIAAQAJAAAGgEQAGgDAEgGQAEgGACgHQACgHAAgIIgCgOQgCgHgEgGQgDgFgGgEQgGgDgJAAQgHAAgGADg");
	this.shape_7.setTransform(25,-40.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgTA/QgKgCgJgFQgHgFgGgIQgFgJAAgMIAgAAQAAAGACAEIAGAFQAEAEAEABIAJABIAIgBIAHgDQADgCACgDQACgCAAgFQAAgIgKgDQgKgEgRgFIgPgDQgHgDgFgCQgGgEgDgFQgDgHAAgIQAAgMAEgHQAFgHAIgFQAHgFAKgCQAJgBAKAAQAKAAAJACQAJACAIAEQAHAFAFAHQAFAIABALIggAAQgBgJgHgEQgGgEgIAAIgHABIgGACIgFADQgBADAAADQAAAFADADQADACAGACIALADIAOAEIAPADQAHADAFAEQAGADADAGQADAFAAAJQAAAMgFAJQgEAIgIAFQgIAFgKACQgLACgKAAQgKAAgKgCg");
	this.shape_8.setTransform(5.875,-43.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYA9QgMgFgIgJQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgJQAIgIAMgFQALgFANAAQAQAAAMAGQAMAGAHAKQAIALADANQADANgBANIhYAAQABARAIAIQAHAHAOAAQAKAAAHgGQAIgEABgGIAeAAQgHAWgPAJQgPAKgVAAQgNAAgMgEgAgMgkQgFADgEAEQgDAEgBAFIgCAIIA2AAQgCgNgGgHQgGgGgNAAQgHgBgFADg");
	this.shape_9.setTransform(-7.5875,-43.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgVBVQgIgDgIgEQgJgFgFgIQgEgHgCgLIAiAAQADAKAGADQAIAEAIAAQAOAAAHgIQAGgJAAgNIAAgRIgBAAQgFAKgKAFQgKAFgKAAQgOAAgLgFQgKgFgGgJQgGgIgEgKQgDgMAAgNQABgMADgLQADgLAIgIQAGgJAKgFQAKgFANAAQALAAAJAFQAJAEAGALIABAAIAAgRIAhAAIAABzQAAAIgDAJQgBAKgIAIQgGAIgNAGQgNAGgTAAQgKAAgKgCgAgLg5QgFACgEAFQgDAFgCAHQgCAGABAHIABANQABAHADAFQADAEAGAEQAFADAHAAQAHAAAGgDQAGgDADgFQAEgDACgGQABgGAAgHQAAgIgBgHQgCgHgDgFQgEgFgFgDQgGgDgIAAQgGAAgFADg");
	this.shape_10.setTransform(-22.2,-41.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeBSQgLgGgHgJQgHgJgDgMQgEgMAAgNQAAgMAEgLQADgLAHgKQAHgJAKgEQAKgGAOAAQAKAAAKAEQAKAFAGAJIAAAAIAAg+IAiAAIAACqIggAAIAAgQQgHALgKAEQgJAEgLAAQgOAAgKgFgAgMgNQgGADgDAFQgEAFgBAIQgCAGAAAIQAAAHACAIQACAGADAGQAEAGAFADQAGAEAHAAQAJAAAFgEQAFgDAEgGQAEgFABgHQABgIABgHQgBgIgBgHQgBgHgEgFQgEgFgFgDQgFgEgJABQgIgBgFAEg");
	this.shape_11.setTransform(-37,-45.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgQBWIAAh7IAhAAIAAB7gAgQg4IAAgcIAhAAIAAAcg");
	this.shape_12.setTransform(-47.3,-45.85);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgnBAIAAh7IAgAAIAAAWIABAAQACgFAEgFQADgFAGgEQAFgDAGgBQAGgCAGgBIAIACIAAAfIgGgBIgGAAQgKAAgGADQgHADgEAFQgCAGgCAHQgCAHAAAHIAAA5g");
	this.shape_13.setTransform(-54.575,-43.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAUBRIgPgBQgGgBgGgDQgFgDgDgGQgDgFAAgKIAAhIIgVAAIAAgXIAVAAIAAglIAhAAIAAAlIAZAAIAAAXIgZAAIAAA8QAAAJADADQACACAJAAIAGAAIAFgBIAAAbIgKABg");
	this.shape_14.setTransform(-64.325,-45.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgnBAIAAh7IAgAAIAAAWIABAAQACgFAEgFQADgFAGgEQAFgDAGgBQAGgCAGgBIAIACIAAAfIgGgBIgGAAQgKAAgGADQgHADgEAFQgCAGgCAHQgCAHAAAHIAAA5g");
	this.shape_15.setTransform(-72.625,-43.65);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgiA/QgHgCgGgFQgGgFgDgGQgEgHAAgKQAAgLAFgGQADgHAGgEQAGgDAHgCIAPgEIAQgBIAMgCQAFgCAEgDQADgCAAgGQAAgFgCgEIgEgEIgIgDIgIgBQgJAAgGAFQgGAEAAALIgiAAQAAgMAFgJQAGgHAIgFQAIgFAKgCQAKgCAJAAIATABQAKABAIAFQAIADAFAHQAFAHAAALIAAA/IABARQABAHADAEIgjAAIgBgGIgBgGQgJAIgKAEQgLADgLAAQgJAAgIgCgAARAFIgIABIgHABIgIABIgHACIgGAEIgFAFQgCADAAAFQAAAFACACQACADADADIAHACIAHABQAJgBAGgDQAFgDADgEQADgGAAgEIABgIIAAgNg");
	this.shape_16.setTransform(-85,-43.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgXA9QgLgFgJgJQgIgIgEgMQgFgLAAgOQAAgOAFgMQADgMAJgJQAIgJALgFQAMgFAOAAQAMAAAJACQALADAHAGQAJAHAFAIQAFAJABAMIgiAAQgDgWgWABQgHgBgFAEQgGAEgDAFQgEAHgCAHIgBAMIABAPQACAGADAGQAEAFAFAEQAFAEAHAAQAMAAAHgHQAGgHACgLIAhAAQgDAYgQANQgQANgZAAQgMAAgMgEg");
	this.shape_17.setTransform(-98.7,-43.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgYA8QgMgEgIgJQgIgJgEgMQgFgMAAgOQAAgNAFgLQAEgMAJgKQAIgIAMgFQALgFANAAQAQAAAMAGQAMAGAHALQAIAJADAOQADANgBANIhYAAQABARAIAHQAHAIAOAAQAKAAAHgGQAIgFABgGIAeAAQgHAXgPAKQgPAJgVAAQgNAAgMgFgAgMgkQgFADgEAEQgDAEgBAEIgCAJIA2AAQgCgNgGgHQgGgGgNgBQgHABgFACg");
	this.shape_18.setTransform(76.5125,-62.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgSA+Igqh7IAkAAIAZBUIAAAAIAahUIAiAAIgqB7g");
	this.shape_19.setTransform(63.275,-62.65);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgQBWIAAh8IAhAAIAAB8gAgQg4IAAgcIAhAAIAAAcg");
	this.shape_20.setTransform(53.85,-65);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgTA/QgKgCgJgFQgHgFgGgJQgFgIAAgMIAgAAQAAAGACAEIAGAGQAEADAEAAIAJABIAIAAIAHgDQADgCACgDQACgDAAgEQAAgIgKgEQgKgDgRgFIgPgDQgHgDgFgDQgGgDgDgGQgDgFAAgIQAAgNAEgHQAFgIAIgEQAHgFAKgCQAJgBAKAAQAKAAAJACQAJABAIAFQAHAFAFAHQAFAIABAMIggAAQgBgKgHgEQgGgEgIABIgHAAIgGACIgFADQgBACAAAEQAAAFADADQADADAGABIALAEIAOACIAPAEQAHADAFAEQAGADADAGQADAGAAAIQAAANgFAHQgEAJgIAFQgIAFgKACQgLACgKAAQgKAAgKgCg");
	this.shape_21.setTransform(44.125,-62.65);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAYBAIAAhGQAAgOgEgJQgGgHgLAAQgOAAgGAJQgGAHAAAUIAABAIgiAAIAAh8IAgAAIAAASIABAAQAHgLAKgFQAJgFALABQANgBAJAEQAJAEAFAGQAFAHACAJQACAKAAALIAABMg");
	this.shape_22.setTransform(30.5,-62.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgYA8QgMgEgIgJQgIgJgEgMQgFgMAAgOQAAgNAFgLQAEgMAJgKQAIgIAMgFQALgFANAAQAQAAAMAGQAMAGAHALQAIAJADAOQADANgBANIhYAAQABARAIAHQAHAIAOAAQAKAAAHgGQAIgFABgGIAeAAQgHAXgPAKQgPAJgVAAQgNAAgMgFgAgMgkQgFADgEAEQgDAEgBAEIgCAJIA2AAQgCgNgGgHQgGgGgNgBQgHABgFACg");
	this.shape_23.setTransform(16.3625,-62.65);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag+BVIAAimIAgAAIAAAQIABAAQAGgKAJgFQAKgEALAAQAOAAALAFQALAGAGAJQAHAJAEAMQADAMAAANQAAANgDAKQgEAMgGAIQgIAJgJAGQgLAFgOAAQgKAAgJgFQgLgEgFgKIgBAAIAAA7gAgOg3QgGADgDAGQgEAFgBAHIgBAPQAAAIABAHQACAGADAFQAEAGAFADQAGAEAIAAQAIAAAGgEQAFgDAEgGQADgFABgGQACgHAAgIQAAgHgCgHQgCgIgDgFQgEgGgFgDQgFgEgIAAQgIAAgGAEg");
	this.shape_24.setTransform(2.3,-60.625);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAaA+IgagnIgZAnIgmAAIAshAIgog7IAmAAIAVAgIAWggIAlAAIgoA6IAtBBg");
	this.shape_25.setTransform(-11.875,-62.65);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgYA8QgMgEgIgJQgIgJgEgMQgFgMAAgOQAAgNAFgLQAEgMAJgKQAIgIAMgFQALgFANAAQAQAAAMAGQAMAGAHALQAIAJADAOQADANgBANIhYAAQABARAIAHQAHAIAOAAQAKAAAHgGQAIgFABgGIAeAAQgHAXgPAKQgPAJgVAAQgNAAgMgFgAgMgkQgFADgEAEQgDAEgBAEIgCAJIA2AAQgCgNgGgHQgGgGgNgBQgHABgFACg");
	this.shape_26.setTransform(-25.3375,-62.65);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgQA3QgJgCgGgFQgHgEgDgGQgEgIgBgKIASAAQABAGACAEQADAEAEADQAEACAFABIAKABIAJgBIAJgCQADgCADgDQADgDAAgFQAAgHgGgEQgFgDgIgCIgQgFIgRgEQgJgDgFgGQgFgFAAgLQAAgIADgHQAEgFAGgEQAGgEAHgBIAOgCQAJAAAHACQAIABAHAEQAFAEAEAGQAEAHAAAKIgSAAQAAgGgCgDIgGgFIgIgEIgIgBIgIABIgHACQgEACgCADQgCACAAAFQAAAEADADQAEADAEACIAMADIAMAEIAMADQAHACAFADQAFAEADAFQADAFABAHQgBAKgEAHQgEAGgHAEQgGAFgJABQgIACgIAAQgJAAgHgCg");
	this.shape_27.setTransform(-44.45,-61.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgRA3QgIgCgGgFQgGgEgFgGQgDgIgBgKIASAAQABAGACAEQADAEAEADQAEACAFABIAKABIAIgBIAJgCQAEgCADgDQADgDgBgFQABgHgGgEQgGgDgHgCIgRgFIgRgEQgHgDgGgGQgFgFAAgLQAAgIAEgHQAEgFAFgEQAGgEAHgBIAPgCQAIAAAIACQAHABAGAEQAHAEADAGQAEAHABAKIgSAAQgBgGgCgDIgGgFIgIgEIgIgBIgIABIgIACQgDACgCADQgCACAAAFQAAAEADADQADADAGACIALADIALAEIAOADQAGACAFADQAFAEADAFQAEAFgBAHQABAKgFAHQgEAGgGAEQgHAFgJABQgIACgIAAQgIAAgJgCg");
	this.shape_28.setTransform(-55.2,-61.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgIBMIAAhsIARAAIAABsgAgIg1IAAgWIARAAIAAAWg");
	this.shape_29.setTransform(-62.95,-64);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAlBMIg2hMIgYAXIAAA1IgVAAIAAiXIAVAAIAABLIBLhLIAaAAIg/A+IBBBZg");
	this.shape_30.setTransform(-71.65,-64);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_noMore, new cjs.Rectangle(-198.1,-80.8,400.29999999999995,49.599999999999994), null);


(lib.txt_lets = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgQARIAAghIAiAAIAAAhg");
	this.shape.setTransform(203.7,-69.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AATBQIgfg0IgMAMIAAAoIggAAIAAifIAgAAIAABVIAngpIAlAAIgrAqIAwBJg");
	this.shape_1.setTransform(196.075,-75.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgkA7IAAhzIAeAAIAAAWIABAAQACgFADgEQADgGAFgCQAFgEAGgCQAFgCAGAAIAHABIAAAeIgFgBIgGAAQgJAAgGADQgGADgEAFQgCAFgCAHQgBAGAAAHIAAA0g");
	this.shape_2.setTransform(186.175,-73.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgYA5QgLgFgHgIQgIgHgFgMQgEgLAAgOQAAgNAEgLQAFgMAIgHQAHgIALgFQALgEANAAQANAAALAEQAMAFAHAIQAIAHAFAMQAEALAAANQAAAOgEALQgFAMgIAHQgHAIgMAFQgLAEgNAAQgNAAgLgEgAgNggQgFADgDAEQgEAGgBAHIgBAMIABAOQABAHAEAEQADAGAFADQAFADAIAAQAIAAAFgDQAGgDADgGQAEgEAAgHIACgOQAAgGgCgGQAAgHgEgGQgDgEgGgDQgFgEgIAAQgIAAgFAEg");
	this.shape_3.setTransform(175.5,-73.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAVA6IgVhNIAAAAIgTBNIghAAIglhzIAiAAIAVBOIAAAAIAUhOIAeAAIATBOIABAAIAVhOIAhAAIglBzg");
	this.shape_4.setTransform(160.675,-73.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgYA5QgLgFgIgIQgIgHgDgMQgFgLAAgOQAAgNAFgLQADgMAIgHQAIgIALgFQALgEANAAQANAAAMAEQAKAFAJAIQAHAHAFAMQAEALAAANQAAAOgEALQgFAMgHAHQgJAIgKAFQgMAEgNAAQgNAAgLgEgAgNggQgFADgDAEQgEAGgBAHIgBAMIABAOQABAHAEAEQADAGAFADQAGADAHAAQAIAAAFgDQAGgDADgGQAEgEABgHIABgOIgBgMQgBgHgEgGQgDgEgGgDQgFgEgIAAQgHAAgGAEg");
	this.shape_5.setTransform(140.7,-73.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AASBMIgOgBQgFgBgFgDQgFgDgDgFQgDgGAAgIIAAhEIgTAAIAAgVIATAAIAAgjIAfAAIAAAjIAXAAIAAAVIgXAAIAAA5QAAAIADACQACADAIAAIAGAAIAEgBIAAAZIgJABg");
	this.shape_6.setTransform(130.9,-74.775);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AATBQIgfg0IgMAMIAAAoIggAAIAAifIAgAAIAABVIAngpIAlAAIgrAqIAwBJg");
	this.shape_7.setTransform(117.425,-75.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgVA5QgLgFgIgIQgHgHgFgMQgEgKAAgNQAAgNAEgLQAEgLAIgJQAHgJALgEQALgFANAAQAKAAAKADQAJADAIAFQAIAGAEAHQAFAJAAALIgfAAQgDgUgUAAQgHAAgFAEQgFADgDAGQgEAFgBAHIgBALIABAOQACAGACAFQAEAFAFAEQAFADAGAAQALAAAHgGQAGgGABgLIAfAAQgDAWgOANQgQAMgXAAQgMAAgKgEg");
	this.shape_8.setTransform(105,-73.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgfA7QgIgCgFgFQgGgDgDgHQgDgGAAgKQABgKADgGQAEgGAFgEQAFgDAIgBIAOgEIAOgCIALgBQAGgCACgDQAEgCAAgFQAAgFgCgDQgCgDgDgCIgGgCIgIAAQgJAAgEADQgGAFgBAJIggAAQABgMAFgGQAEgIAJgFQAHgEAJgCQAKgCAJAAIASACQAIAAAHAEQAIAEAFAGQAFAGgBALIAAA7IABAQQACAGACAEIghAAIgBgGIgBgFQgHAIgLADQgJADgLAAQgIAAgHgCgAAPAEIgGACIgHABIgHABIgHACIgGADIgEAEQgBADAAAFQAAAEABADQABADADACIAGACIAIABQAJAAAEgEQAGgDACgEQACgEABgEIABgIIAAgMg");
	this.shape_9.setTransform(93.05,-73.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgLBNQgLgEgFgJIAAAAIAAAOIgeAAIAAifIAfAAIAAA7IABAAQAFgJAKgFQAKgEAKAAQAJABAIADQAJAEAHAHQAHAIAEALQAFALAAAQQAAAPgFAMQgEAMgHAHQgHAHgJAEQgIAEgJAAQgLgBgKgEgAgMgNQgFAEgDAFQgDAEgCAGQgBAIgBAHQABAHABAGQACAHADAGQADAEAFAEQAGADAGAAQAHAAAEgDQAGgEADgEQADgGACgHQACgGgBgHQABgHgCgIQgCgGgDgEQgDgFgGgEQgEgCgHAAQgGAAgGACg");
	this.shape_10.setTransform(81.15,-75.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AARBLIgOgBQgDgBgEgCQgDgDgBgFQgCgFAAgIIAAhJIgUAAIAAgRIAUAAIAAgiIASAAIAAAiIAXAAIAAARIgXAAIAABHIABAFQAAABAAAAQAAABAAAAQABABAAAAQAAAAABABIAEABIAHAAIAJAAIAAARg");
	this.shape_11.setTransform(66.35,-74.775);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgVA4QgKgFgHgHQgHgJgEgLQgDgLgBgNQAAgNAEgLQAEgKAIgJQAHgIAKgEQAKgEALgBQAPABAKAGQALAGAGAKQAGAKACALQADAMgBAKIhWAAQAAAIACAGQACAHAFAFQAEAGAHACQAHAEAJAAQAMAAAHgGQAIgFADgMIASAAQgEAUgMAJQgNALgUAAQgNAAgKgFgAgNgoQgGACgEAFQgEAFgDAFQgCAHgBAGIBCAAQAAgGgDgHQgDgGgEgEQgEgFgGgCQgGgCgHgBQgHABgGACg");
	this.shape_12.setTransform(58.3042,-73.05);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgQBRQgIgCgHgEQgHgEgFgHQgEgGAAgJIATAAQAAAFADADIAHAGIAJADIAJABQAKAAAGgDQAHgDAEgGQAFgGACgIQABgIAAgJIAAgIIAAAAQgFALgKAFQgKAFgKAAQgNAAgKgFQgJgFgHgHQgGgIgDgLQgEgKAAgMQAAgKADgLQACgLAHgIQAGgJAKgGQAKgGAOAAQALAAAKAFQAJAFAFAKIAAAAIAAgRIASAAIAABpQAAAcgMAOQgOAPgbAAQgHAAgJgCgAgNg9QgGADgFAGQgEAGgCAHQgCAIAAAIQAAAIACAIQACAHADAGQAEAGAGAEQAHAEAIAAQAJAAAHgEQAHgEADgGQAEgGADgHQACgIAAgIQAAgIgCgHQgCgIgEgGQgEgGgHgDQgFgEgKAAQgHAAgHAEg");
	this.shape_13.setTransform(46.5,-70.825);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgSA6QgIgCgHgEQgHgEgEgJQgEgHAAgLIATAAQAAAHADAEQACAEAFADIAKAEIAKABIAJgBIAJgDQAEgBADgDQADgEAAgFQAAgIgGgDQgFgFgJgBIgRgFQgKgCgIgDQgJgDgFgGQgGgGAAgLQAAgJAEgHQAEgGAGgEQAGgEAIgCQAIgCAHAAQAJABAIABQAJACAGAEQAHAEADAHQAEAIABAKIgTAAQgBgGgCgEIgGgGIgJgDIgIgBIgJABIgIACQgDACgCADQgDADAAAEQAAAFAEAEQADADAGABIAMAEIAMAEIAOADIAMAFQAFAEAEAFQADAGAAAIQAAALgEAGQgFAIgHAEQgHAEgJACIgRACQgJgBgJgCg");
	this.shape_14.setTransform(30.825,-73.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgLASQADAAADgCQADgCABgDIACgIIAAgGIgNAAIAAgZIAYAAIAAAZQABAFgCAHQgBAFgEAFQgDAFgDACQgFADgGAAg");
	this.shape_15.setTransform(23.15,-80.35);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AARBLIgOgBQgDgBgEgCQgDgDgBgFQgCgFAAgIIAAhJIgUAAIAAgRIAUAAIAAgiIASAAIAAAiIAXAAIAAARIgXAAIAABHIABAFQAAABAAAAQAAABAAAAQABABAAAAQAAAAAAABIAFABIAHAAIAJAAIAAARg");
	this.shape_16.setTransform(17.4,-74.775);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgVA4QgKgFgHgHQgHgJgEgLQgDgLgBgNQAAgNAEgLQAEgKAIgJQAHgIAKgEQAKgEALgBQAPABAKAGQALAGAGAKQAGAKACALQADAMgBAKIhWAAQAAAIACAGQACAHAFAFQAEAGAHACQAHAEAJAAQAMAAAHgGQAIgFADgMIASAAQgEAUgMAJQgNALgUAAQgNAAgKgFgAgNgoQgGACgEAFQgEAFgDAFQgCAHgBAGIBCAAQAAgGgDgHQgDgGgEgEQgEgFgGgCQgGgCgHgBQgHABgGACg");
	this.shape_17.setTransform(9.3542,-73.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("Ag0BQIAAifIAVAAIAACNIBUAAIAAASg");
	this.shape_18.setTransform(-1.1,-75.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_lets, new cjs.Rectangle(-9,-90,215.7,28.5), null);


(lib.txt_ecoTankPro_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AlkBZQgJgEgGgHQgGgHgDgKQgDgKgBgMQAAgLAEgKQADgKAHgHQAGgHAJgEQAJgEALAAQAOAAAJAGQAJAFAFAIQAGAJACALQACAKgBAKIhNAAQAAAGACAGQABAHAFAEQAEAFAGADQAGACAIAAQALAAAHgFQAHgEACgLIARAAQgEASgLAIQgMAJgRAAQgMAAgKgEgAlcADQgFACgEAEIgGAJQgDAGAAAFIA7AAQAAgFgCgGQgDgFgEgEQgDgEgGgCQgFgDgGAAQgHAAgFADgAnNBZQgJgEgGgHQgHgHgDgKQgDgKAAgMQAAgLAEgKQADgKAHgHQAGgHAJgEQAJgEAKAAQAOAAAJAGQAJAFAGAIQAFAJACALQADAKgBAKIhNAAQAAAGABAGQACAHAFAEQADAFAHADQAGACAIAAQALAAAHgFQAHgEACgLIAQAAQgDASgLAIQgMAJgRAAQgNAAgJgEgAnFADQgGACgDAEQgEAEgCAFQgDAGAAAFIA7AAQAAgFgDgGQgCgFgEgEQgDgEgGgCQgFgDgGAAQgHAAgFADgAj9BaQgFgBgDgCQgDgDgBgEQgBgEAAgHIAAhCIgSAAIAAgOIASAAIAAgfIARAAIAAAfIAUAAIAAAOIgUAAIAABAIAAAFIACACIAEACIAOAAIAAAPgAoQBbIAAh2IgBAAIgsB2IgQAAIgth2IAAB2IgSAAIAAiNIAaAAIAtB2IAth2IAaAAIAACNgABmBXQgKgEgHgHQgHgHgDgKQgFgKAAgMQAAgNAFgKQADgKAHgGQAHgHAKgEQAKgEAMAAQAMAAAKAEQAKAEAHAHQAHAGADAKQAEAKAAANQAAAMgEAKQgDAKgHAHQgHAHgKAEQgKAEgMAAQgMAAgKgEgABwAGQgFADgDAFQgDAFgBAGIgBAMIABAMQABAGADAEQADAFAFADQAFADAHAAQAHAAAFgDQAFgDADgFQADgEABgGQABgGAAgGQAAgHgBgFQgBgGgDgFQgDgFgFgDQgFgDgHAAQgHAAgFADgAgKBXQgKgEgGgHQgIgHgDgKQgEgJAAgMQAAgMAEgKQADgKAHgHQAHgIAJgEQAKgEAMAAQAJAAAJACQAIADAHAFQAGAFAEAGQAFAHAAAKIgcAAQgCgSgSAAQgHAAgEADQgEAEgDAFQgDAEgBAGIgBAMIABAMQABAFADAFQACAFAFADQAEADAGAAQAKAAAGgGQAFgGACgJIAbAAQgDAUgNALQgNALgVAAQgKAAgKgEgAEoBYQgHgBgEgEQgFgEgDgGQgDgFAAgIQAAgJADgGQAEgFAEgDQAFgEAHgBIAjgGIAHgEQADgCAAgEQAAgFgCgDQAAAAAAgBQgBAAAAgBQgBAAAAgBQgBAAAAAAQgDgCgDgBIgHAAQgIAAgFADQgFAEgBAIIgbAAQAAgKAEgGQAFgGAGgEQAHgDAJgCIAQgCIAQABQAIABAGADQAHAEAEAFQAEAFAAAJIABBCQAAAGADAEIgdAAIgCgLQgGAHgKADQgIADgKAAQgHAAgGgCgAFSAoIgZAFIgFADIgEAEQgCADAAAEQAAAEACACQABADADABIAFACIAHABQAIAAAEgDQAFgDACgEIADgHIAAgRgAiiBYIAAiNIBrAAIAAAaIhMAAIAAAeIBFAAIAAAYIhFAAIAAAjIBNAAIAAAagAI5BYIgdguIgKALIAAAjIgcAAIAAiMIAcAAIAABLIAjgkIAhAAIgmAkIAqBBgAHKBYIAAg6QAAgMgDgHQgEgGgKAAQgMAAgFAHQgFAHAAAPIAAA2IgcAAIAAhlIAbAAIAAANIABAAQAFgIAIgEQAIgEAJAAQALAAAHADQAIADAEAFQAEAFABAIQACAIAAAJIAAA/gADTBYIAAhyIgqAAIAAgaIBzAAIAAAaIgqAAIAABygAJmgnIgJgGQgEgDgDgGQgBgFAAgGQAAgGABgFQADgFAEgDQAEgEAFgCQAFgCAFAAQAHAAAEACQAFACAEAEQAEADACAFQADAFAAAGQAAAGgDAFQgCAGgEADIgJAGQgEACgHAAQgFAAgFgCgAJphUQgFABgCADIgEAHQgCADAAAFQAAAFACAEIAEAHQACADAFABQADACAEAAQAFAAAEgCIAGgEIAFgHQABgEAAgFQAAgFgBgDIgFgHIgGgEQgEgCgFAAQgEAAgDACgAJ3gxIgHgNIgFAAIAAANIgFAAIAAgfIALAAQAGAAADACQADACAAAFIgBADIgBADIgDACIgDABIAIANgAJrhDIAGAAIAEgBQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIAAgCIgCgCIgKAAg");
	this.shape.setTransform(-21.125,-41.675);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_ecoTankPro_Logo, new cjs.Rectangle(-86.4,-50.9,130.60000000000002,18.5), null);


(lib.txt_EcoTankPro = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1F1F1F").s().p("AApAYIAAgkIAAAAIgOAkIgHAAIgOgkIAAAkIgHAAIAAgvIAMAAIANAgIANggIANAAIAAAvgAgjAYIAAgnIgOAAIAAgIIAmAAIAAAIIgOAAIAAAng");
	this.shape.setTransform(75.725,-157.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#1F1F1F").s().p("AgTAUIAAgnIAnAAIAAAng");
	this.shape_1.setTransform(73.05,-141.925);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#1F1F1F").s().p("AgSBeIAAi7IAlAAIAAC7g");
	this.shape_2.setTransform(66.125,-149.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#1F1F1F").s().p("AgSBeIAAi7IAlAAIAAC7g");
	this.shape_3.setTransform(59.475,-149.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#1F1F1F").s().p("AgSBeIAAiHIAlAAIAACHgAgSg+IAAgfIAlAAIAAAfg");
	this.shape_4.setTransform(52.825,-149.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#1F1F1F").s().p("AAbBeIAAhNQgBgRgFgHQgGgIgNAAQgOAAgHAJQgHAIAAAVIAABHIglAAIAAi7IAlAAIAABHIABAAQAHgMAMgGQAKgFAKAAQAPAAAJAEQAKAEAGAHQAGAIACAKQACALAAALIAABUg");
	this.shape_5.setTransform(41.7,-149.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#1F1F1F").s().p("AgZBDQgNgGgJgJQgJgJgFgNQgFgNAAgPQAAgPAEgNQAFgOAJgKQAJgKANgFQANgGAPAAQANAAALADQALADAJAHQAJAGAFAKQAGAKABANIglAAQgEgYgYAAQgIAAgGAEQgGAEgEAHQgEAHgBAHQgCAIAAAHIACAPQABAHAEAHQAEAGAGAEQAGAEAHAAQAOAAAHgIQAHgHACgNIAkAAQgDAbgSAOQgRAPgbAAQgPAAgMgFg");
	this.shape_6.setTransform(26.575,-146.725);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#1F1F1F").s().p("AgyBdQgLgDgIgIQgIgHgFgLQgEgKAAgNQAAgLADgHQAEgJAFgHQAGgHAIgDIAQgKQgIgJgFgJQgGgJABgNQgBgKAFgIQAEgHAHgGQAGgGAJgDQAKgDAJAAQAKAAAJADQAJACAHAHQAIAFADAIQAFAJAAALQAAAQgKAMQgJAMgPAHIAZAdIAEgLIACgMIAgAAQgBANgEAMQgEAMgJAKIAmAtIgtAAIgPgTQgMALgMAFQgMAGgQAAQgNAAgMgEgAgiAQIgIAGQgFAEgCAFQgCAEAAAHQAAAEACAFQACAFAFADQADADAFACQAFACAFABQAKgBAIgFQAGgEAGgHIgegogAgXhCQgFAEAAAHQAAAKAFAGIAJANQAJgFAFgGQAFgGAAgKQAAgIgFgEQgFgGgHAAQgGAAgFAFg");
	this.shape_7.setTransform(3.25,-149.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#1F1F1F").s().p("AgSBeIAAi7IAlAAIAAC7g");
	this.shape_8.setTransform(-16.825,-149.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#1F1F1F").s().p("AgSBeIAAi7IAlAAIAAC7g");
	this.shape_9.setTransform(-23.475,-149.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#1F1F1F").s().p("AgSBeIAAiHIAlAAIAACHgAgSg+IAAgfIAlAAIAAAfg");
	this.shape_10.setTransform(-30.175,-149.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#1F1F1F").s().p("AgUBeIAAhuIgXAAIAAgZIAXAAIAAgLQgBgSAMgMQAKgLAXAAIAKAAIAKABIAAAcIgOgBQgIAAgDAEQgDADAAAJIAAAIIAaAAIAAAZIgaAAIAABug");
	this.shape_11.setTransform(-37.85,-149.325);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#1F1F1F").s().p("AAGBYQgHgBgGgDQgGgEgEgHQgDgFAAgLIAAhPIgXAAIAAgZIAXAAIAAgqIAkAAIAAAqIAcAAIAAAZIgcAAIAABCQAAAJAEAEQADADAJAAIAGAAIAGgBIAAAdIgLABIgLAAg");
	this.shape_12.setTransform(-54.125,-148.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#1F1F1F").s().p("AgVBFQgLgCgJgGQgJgFgGgJQgGgJAAgOIAkAAQAAAGACAEQADAFAEACQADADAGACIAJABIAJgBIAIgDQADgCACgDQADgEAAgFQAAgIgLgEQgMgEgTgFIgQgEQgHgDgHgDQgGgEgDgGQgEgGAAgJQAAgNAFgJQAFgIAJgFQAIgFALgCQAKgCALAAQALAAAKACQAKACAJAFQAIAFAFAJQAGAIABANIgkAAQgBgLgHgEQgIgEgJAAIgGABIgHABIgFAEQgCADAAAEQAAAFADADQAEADAGACIANAEIAPADIAQAFQAIACAGAFQAGADAEAGQADAHAAAJQAAAOgFAJQgGAJgIAGQgJAFgLACQgLADgMAAQgLAAgLgDg");
	this.shape_13.setTransform(-65.625,-146.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#1F1F1F").s().p("AgmBCQgKgEgFgHQgGgHgCgLQgCgLAAgMIAAhTIAlAAIAABMQAAARAFAJQAGAHANABQAPgBAHgIQAGgJABgWIAAhGIAlAAIAACIIgkAAIAAgUIAAAAQgIAMgLAFQgLAGgMAAQgOAAgKgEg");
	this.shape_14.setTransform(-80.35,-146.55);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#1F1F1F").s().p("AgWBdQgLgEgJgHQgIgHgGgLQgFgLgBgPIAAgQIAmAAIAAAIIACANQABAGACAEQADAEAEACQAFADAHAAQAHAAAFgEQAEgCACgEQACgGAAgFIABgKIAAh/IApAAIAACAQAAAKgBALQgCALgHAJQgHAKgLAHQgNAHgVAAQgLAAgLgEg");
	this.shape_15.setTransform(-96.15,-149.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_EcoTankPro, new cjs.Rectangle(-104.2,-167.1,186.2,34.400000000000006), null);


(lib.printer_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.printer();
	this.instance.setTransform(-284.05,-32.95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_02, new cjs.Rectangle(-284,-32.9,373,292), null);


(lib.printer_01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.printer();
	this.instance.setTransform(1040.35,-402.25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_01, new cjs.Rectangle(1040.4,-402.2,373,292), null);


(lib.main_paint = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EgmTAvIQgmhrgZihQgylAA/kHIDDuTQgQgugXg3QgshugcgsQgyhLgoiPQhSkfAvlUQAbjIBKkZQCUoxDtmOQBPisBPjqQCdnSAAkvIAjjkQAmjvAWg1INDgFQiNBSiXByQkvDkgyCdQiRIrg8DSQgpBJg1B6QhtDzhCDuQjUL7EZGvIDRkYQA3hXA6hsQBzjXANhkQAWibA+i4QB7lvDBiRQBkhACJgaQEQg0C1DBQA+BTAeCDQA5EHipDzQggAyhkBVQjICqlSCvIhMAnQhfA0hcBEQknDZiiElQBBBQBTBbQCkC0BYAyQB4BNB9BVQD6CqAZAmQAtj8BkkfQDIo8ETipQgFh6AvieQBck7D/ivQBuhLB4hNQDtibAsgNQCHlyCBmqQEBtWgfkZIDIAAQAKAUAHAoQAQBQgNBkQg1EpgqE6QhVJxAyBLIAmg0QAthAAnhAQB9jOANh9IAihZQAuhqA+hTQDIkMEgA4QBfAoBfBLQC+CWAACvQAIBdg9B5Qh7DzlYCQIruE2QAFB1AVCbQArE2BRC8IBZDaQBdDlASA+QAoD2AlFaQBIK0gTH6IBlBZQB6ByBvB8QFgGOBeFkUhN0gAUgAUAAKgAC3naQhLBzgeBfQC2hdCojpQBTh0AwhiQjiBkiWDmg");
	mask.setTransform(-20.9436,175.8081);

	// Layer_1
	this.instance = new lib.paintColors();
	this.instance.setTransform(-279.55,-123.75);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.main_paint, new cjs.Rectangle(-276.9,-123.7,510.4,600), null);


(lib.epson_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#2A3283").s().p("AB/B3QgZgKgOgRQgPgRgIgXQgJgYAAgbQAAgbAJgXQAIgYAPgSQAOgSAZgKQAXgKAbAAQAeAAAWAKQAYAKAOASQAQASAJAYQAHAXAAAbQAAAbgHAYQgJAXgQARQgOARgYAKQgWALgeAAQgbAAgXgLgACThLQgNAGgJANQgHAKgEARQgEAPAAAPQAAAPAEAQQAEAOAHANQAJALANAGQANAJARAAQATAAAOgJQAMgGAIgLQAHgNAEgOQAEgQAAgPQAAgPgEgPQgEgRgHgKQgIgNgMgGQgOgJgTAAQgRAAgNAJgAhnB9QgUgGgOgLQgPgKgJgRQgJgQACgXIAzAAQABANAEAIQAFAJAIAEQAGAGALAEQAJABALAAIAPAAQAJgBAHgFQAHgCAFgHQAGgGAAgKQAAgJgHgIIgQgKIhOgWQgNgFgMgHQgJgIgHgMQgGgMAAgQQAAgUAIgPQAIgMAOgLQANgJAQgFQARgEARAAQATAAASADQASAGANAJQAOALAIAOQAHAPAAAXIgzAAQAAgMgFgIQgDgGgGgEQgIgGgIgBIgTgCIgOABQgGACgEAEQgHAEgCAEQgEAFAAAJQAAAHADAEQADAFAIAEIBRAXQAKADALAHQANAHAIANQAKAOAAAWQAAAQgIAOQgFAQgOALQgMAJgUAHQgSAGgbAAQgTAAgTgFgAHbB8IhnilIAAClIgzAAIAAj2IA3AAIBnCkIABAAIAAikIAyAAIAAD2gAmNB8IAAj2IBxAAQAWAAAQAHQAQAFAKALQALALAFAPQAFAPAAANQAAARgFAOQgFAOgLALQgKALgQAGQgQAHgWAAIg7AAIAABZgAlXgGIA9gBQAIgBAHgFQAHgEAEgIQADgGAAgOQAAgKgDgHQgEgHgHgEQgHgFgIgBIg9gBgApqB8IAAj2IC4AAIAAAsIiCAAIAAA1IB4AAIAAApIh4AAIAAA/ICGAAIAAAtgAJHhKQgFgCgFgDIgFgKQgDgFAAgFQAAgHADgFIAFgJQAFgFAFgBQAFgBAEAAQAGAAAGABQAFABADAFIAHAJIAAAMIAAAKIgHAKQgDADgFACQgGABgGAAQgEAAgFgBgAJJh4QgEACgCADQgEACgCAEIgBAKIABAIQACADAEADQACAEAEACIAHABIAJgBQAEgCADgEIAEgGIABgIIgBgKQgBgEgDgCQgDgDgEgCIgJgBIgHABgAJWhVIgGgNIgEAAIAAANIgHAAIAAgeIALAAQAHAAADACQAEACAAAFIAAAEIgCADIgDAAIgDABIAIANgAJMhmIAEAAIAGAAIAAgFIAAgCIAAgBIgKAAg");
	this.shape.setTransform(65.75,33.1971,1.8837,1.8837);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.epson_logo, new cjs.Rectangle(-50.9,8.8,233.4,48.900000000000006), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAdIAAguIgRAAIAAgLIAvAAIAAALIgSAAIAAAug");
	this.shape.setTransform(25.25,-0.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRAXQgGgFAAgMIAAgiIAMAAIAAAiIAAAFIACAEIAEACQACACADAAQAHAAACgDQADgDAAgHIAAgiIAMAAIAAAiQAAAMgGAFQgHAGgLAAQgLAAgGgGg");
	this.shape_1.setTransform(19.975,-0.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgKAcQgGgDgDgEQgEgEgCgFQgCgGAAgGQAAgFACgGQACgFAEgFQADgDAGgDQAEgCAGAAQAHAAAFACQAFADAEADQADAFACAFQACAGAAAFQAAAGgCAGQgCAFgDAEQgEAEgFADQgFACgHAAQgGAAgEgCgAgGgRIgFAEIgDAHIgBAGIABAHIADAGIAFAEQADADADAAQAFAAADgDQADgBABgDIADgGIABgHIgBgGIgDgHIgEgEQgDgCgFAAQgDAAgDACg");
	this.shape_2.setTransform(14,-0.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGAdIAAguIgRAAIAAgLIAuAAIAAALIgRAAIAAAug");
	this.shape_3.setTransform(6.5,-0.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgFAdIAAg5IALAAIAAA5g");
	this.shape_4.setTransform(2.975,-0.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AALAdIgQgaIgIAHIAAATIgMAAIAAg5IAMAAIAAAYIAWgYIAPAAIgWAXIAYAig");
	this.shape_5.setTransform(-2.775,-0.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgJAcQgGgDgDgEQgEgEgCgFQgCgGAAgGQAAgFACgGQACgFAEgFQADgDAGgDQAFgCAFAAQAFAAAEABQAFACADADQADACACAEQACADABAFIgMAAIgCgEIgCgCIgEgDIgFgBQgDAAgDACIgFAEIgCAHIgBAGIABAHIACAGIAFAEQADADADAAQAGAAADgEQAEgDAAgHIANAAIgDAKQgCAEgDADQgEADgEACQgEACgGAAQgFAAgFgCg");
	this.shape_6.setTransform(-8.775,-0.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgVAdIAAg5IAqAAIAAALIgdAAIAAAMIAaAAIAAAJIgaAAIAAAOIAeAAIAAALg");
	this.shape_7.setTransform(-14.075,-0.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AALAdIAAgZIgWAAIAAAZIgMAAIAAg5IAMAAIAAAXIAWAAIAAgXIANAAIAAA5g");
	this.shape_8.setTransform(-19.625,-0.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJAcQgGgDgDgEQgEgEgCgFQgCgGAAgGQAAgFACgGQACgFAEgFQADgDAGgDQAFgCAFAAQAFAAAEABQAFACADADQADACACAEQACADABAFIgMAAIgCgEIgCgCIgEgDIgFgBQgDAAgDACIgFAEIgCAHIgBAGIABAHIACAGIAFAEQADADADAAQAGAAADgEQAEgDAAgHIANAAIgDAKQgCAEgDADQgEADgEACQgEACgGAAQgFAAgFgCg");
	this.shape_9.setTransform(-25.425,-0.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E61404").s().p("AkjBiQgcAAAAgbIAAiNQAAgbAcAAIJHAAQAcAAAAAbIAACNQAAAbgcAAg");
	this.shape_10.setTransform(-0.125,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_10).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-32.1,-9.9,64,19.700000000000003), null);


(lib.cartridge_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.cartridges_01();
	this.instance.setTransform(-244.05,-76.95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.cartridge_mc, new cjs.Rectangle(-244,-76.9,1020,250), null);


// stage content:
(lib.Epson_B2B_NonPro_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		var root = this; //Declared variable for access to global scope.
		
		this.popUp_btn.addEventListener("click", popUpBtn.bind(this));
		this.panel.addEventListener("click", exitPanel.bind(this));
		
		
		this.on("click", function (e) {
			window.open(clickTag, "_blank");
			console.log("ClickTag pressed");
			
		});
		
		
		function popUpBtn(e) {
			e.stopPropagation();
			root.panel.x = 0;
			root.stop();
			console.log("PopUp button pressed");
		}
		
		
		function exitPanel(e) {
			e.stopPropagation();
			root.panel.x = 320;
			root.play();
			console.log("Panel Closed");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(277));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EBLygFJIAAKTMiXjAAAIAAqTg");
	this.shape.setTransform(159.9991,24.9998,0.3299,0.7576);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(277));

	// epson_logo
	this.instance = new lib.epson_logo();
	this.instance.setTransform(21.45,7,0.1503,0.1503,0,0,0,67.8,32.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(251).to({_off:false},0).to({alpha:1},8).wait(18));

	// ctaBtn_Mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_259 = new cjs.Graphics().p("AjzBSQgWAAAAgWIAAAAIAAh2QAAgXAWAAIAAAAIHnAAQAWAAAAAXIAAAAIAAB2QAAAWgWAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(259).to({graphics:mask_graphics_259,x:275.5458,y:26.2165}).wait(18));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.9,-3.9,6,3.9).s().p("AjpDjIFboTIB4BOIlbITg");
	this.shape_1.setTransform(242.575,15.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-5.9,-3.9,6,3.9).s().p("AjpDjIFcoUIB3BPIlcIUg");
	this.shape_2.setTransform(243.075,15.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-6,-3.9,6,3.9).s().p("AjrDmIFeoZIB5BPIleIYg");
	this.shape_3.setTransform(244.575,15.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-6,-4,6.1,3.9).s().p("AjuDoIFjofIB6BQIljIfg");
	this.shape_4.setTransform(247.075,16.65);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-6.2,-4.1,6.2,4).s().p("AjzDsIFqopIB9BRIlqIqg");
	this.shape_5.setTransform(250.575,17.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-6.3,-4.2,6.4,4.1).s().p("Aj4DxIFyo1IB/BTIlyI2g");
	this.shape_6.setTransform(255.075,19);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-6.5,-4.3,6.5,4.2).s().p("Aj/D5IF8pGICDBWIl8JFg");
	this.shape_7.setTransform(260.6,20.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-6.7,-4.5,6.7,4.3).s().p("AkHEAIGIpYICHBYImIJZg");
	this.shape_8.setTransform(267.125,22.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-7,-4.6,6.9,4.5).s().p("AkREKIGXpuICMBcImXJtg");
	this.shape_9.setTransform(274.625,24.675);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-7.2,-4.7,7.3,4.7).s().p("AkbETIGmqEICRBeImmKFg");
	this.shape_10.setTransform(282.875,27.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-7.4,-4.9,7.5,4.9).s().p("AkkEdIGzqaICWBhImzKbg");
	this.shape_11.setTransform(290.375,29.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-7.7,-5,7.7,5).s().p("AksElIHAqtICaBlInBKsg");
	this.shape_12.setTransform(296.9,31.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-7.9,-5.1,7.8,5.1).s().p("AkzErIHJq8ICeBnInJK8g");
	this.shape_13.setTransform(302.4,32.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-8,-5.2,8,5.2).s().p("Ak5ExIHSrJIChBpInSLIg");
	this.shape_14.setTransform(306.925,34.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-8.1,-5.3,8.1,5.3).s().p("Ak9E1IHYrTICjBrInZLSg");
	this.shape_15.setTransform(310.425,35.15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-8.2,-5.4,8.2,5.3).s().p("AlAE3IHdrZICkBrIndLag");
	this.shape_16.setTransform(312.925,35.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-8.2,-5.4,8.2,5.4).s().p("AlCE6IHgreIClBrIngLeg");
	this.shape_17.setTransform(314.425,36.325);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.369)","rgba(255,255,255,0)"],[0,0.51,1],-8.3,-5.4,8.2,5.4).s().p("AlDE6IHhrfICmBsInhLfg");
	this.shape_18.setTransform(314.925,36.475);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10,this.shape_11,this.shape_12,this.shape_13,this.shape_14,this.shape_15,this.shape_16,this.shape_17,this.shape_18];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},259).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).wait(1));

	// ctaBtn
	this.instance_1 = new lib.ctaBtn();
	this.instance_1.setTransform(275.9,26.55,0.8333,0.8333,0,0,0,0.3,0.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(251).to({_off:false},0).to({alpha:1},8).wait(18));

	// txt_EcoTankPro
	this.instance_2 = new lib.txt_EcoTankPro();
	this.instance_2.setTransform(103.75,122.45,0.65,0.65,0,0,0,0.1,0);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(251).to({_off:false},0).to({alpha:1},8,cjs.Ease.quadOut).wait(18));

	// Layer_85
	this.instance_3 = new lib.printer_02();
	this.instance_3.setTransform(200,27.9,0.1874,0.1874,0,0,0,-93.7,110.7);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(251).to({_off:false},0).to({regY:110.5,scaleX:0.2136,scaleY:0.2136,y:29.4,alpha:1},8,cjs.Ease.quadOut).wait(18));

	// Layer_107
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(255,255,255,0)").s().p("EhPTAaAQgoAAABgpMAAAgyuQgBgoAoABMCemAAAQApgBAAAoIAADTMAAAAsWIAADFQAAApgpAAg");
	this.shape_19.setTransform(491.55,129.35);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("rgba(255,255,255,0.09)").s().p("EhPRAZ7QgoAAAAgoMAAAgylQAAgoAoAAMCejAAAQAoAAAAAoMAAAAylQAAAogoAAg");
	this.shape_20.setTransform(491.375,128.875);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("rgba(255,255,255,0.18)").s().p("EhPPAZ2QgoAAAAgoMAAAgybQAAgoAoAAMCefAAAQAoAAAAAoMAAAAybQAAAogoAAg");
	this.shape_21.setTransform(491.175,128.425);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(255,255,255,0.275)").s().p("EhPNAZxQgoAAAAgoMAAAgySQAAgoAoABMCebAAAQAogBAAAoMAAAAySQAAAogoAAg");
	this.shape_22.setTransform(491,127.95);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("rgba(255,255,255,0.365)").s().p("EhPLAZtQgoAAAAgoMAAAgyJQAAgoAoAAMCeXAAAQAoAAAAAoMAAAAyJQAAAogoAAg");
	this.shape_23.setTransform(490.825,127.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("rgba(255,255,255,0.455)").s().p("EhPKAZoQgoAAABgoMAAAgx/QgBgoAoAAMCeUAAAQApAAAAAoMAAAAx/QAAAogpAAg");
	this.shape_24.setTransform(490.65,127.025);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("rgba(255,255,255,0.545)").s().p("EhPIAZkQgoAAABgoMAAAgx3QgBgoAoAAMCeRAAAQAoAAgBAoMAAAAx3QABAogoAAg");
	this.shape_25.setTransform(490.45,126.575);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("rgba(255,255,255,0.635)").s().p("EhPGAZfQgoAAAAgoMAAAgxtQAAgoAoAAMCeNAAAQAoAAAAAoMAAAAxtQAAAogoAAg");
	this.shape_26.setTransform(490.275,126.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("rgba(255,255,255,0.725)").s().p("EhPEAZaQgoAAAAgnMAAAgxlQAAgoAoABMCeJAAAQAogBAAAoMAAAAxlQAAAngoAAg");
	this.shape_27.setTransform(490.1,125.65);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("rgba(255,255,255,0.82)").s().p("EhPCAZWQgoAAAAgoMAAAgxbQAAgoAoAAMCeFAAAQAoAAAAAoMAAAAxbQAAAogoAAg");
	this.shape_28.setTransform(489.925,125.175);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("rgba(255,255,255,0.91)").s().p("EhPAAZRQgoAAAAgoMAAAgxRQAAgoAoAAMCeBAAAQAoAAAAAoMAAAAxRQAAAogoAAg");
	this.shape_29.setTransform(489.725,124.725);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("EhO/AZMQgoABABgoMAAAgxJQgBgoAoABMCd/AAAQAogBgBAoIAADTMAAAArGIAACwQABAogogBg");
	this.shape_30.setTransform(489.55,124.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_19}]},239).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[]},1).wait(26));

	// txt_noMore
	this.instance_4 = new lib.txt_noMore();
	this.instance_4.setTransform(152.65,64.35);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(193).to({_off:false},0).to({y:76.85,alpha:1},8,cjs.Ease.quadOut).to({_off:true},50).wait(26));

	// Layer_102
	this.instance_5 = new lib.cartridge_mc();
	this.instance_5.setTransform(-178.7,32,0.342,0.342,0,0,0,257.4,56.9);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(183).to({_off:false},0).to({x:166.8},15,cjs.Ease.quadOut).to({_off:true},53).wait(26));

	// main_paint
	this.instance_6 = new lib.main_paint();
	this.instance_6.setTransform(416,-71.75,0.3278,0.3278,0,0,0,0.1,-0.6);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(119).to({_off:false},0).to({x:-66},28,cjs.Ease.quadInOut).to({_off:true},1).wait(129));

	// Layer_1 (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_90 = new cjs.Graphics().p("EhtZAwOMgAWhgbIFlAAIGIAAIAEAAILoAAMCJLAAAIGMAAIDMAAMAxjAAAMgNBBgRIgCAKg");
	var mask_1_graphics_119 = new cjs.Graphics().p("Egj2AP0IgH/nIB1AAICAAAIABAAID0AAMAs9AAAICCAAIBDAAIQQAAIkSfkIAAADg");
	var mask_1_graphics_120 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_121 = new cjs.Graphics().p("Egj3AP0IgH/nMBH8AAAIkRfng");
	var mask_1_graphics_122 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_123 = new cjs.Graphics().p("Egj3AP0IgG/nMBH7AAAIkRfng");
	var mask_1_graphics_124 = new cjs.Graphics().p("Egj3AP0IgH/nMBH9AAAIkSfng");
	var mask_1_graphics_125 = new cjs.Graphics().p("Egj3AP0IgH/nMBH9AAAIkSfng");
	var mask_1_graphics_126 = new cjs.Graphics().p("Egj3AP0IgH/nMBH8AAAIkRfng");
	var mask_1_graphics_127 = new cjs.Graphics().p("Egj3AP0IgH/nMBH8AAAIkRfng");
	var mask_1_graphics_128 = new cjs.Graphics().p("Egj3AP0IgH/nMBH9AAAIkSfng");
	var mask_1_graphics_129 = new cjs.Graphics().p("Egj2AP0IgH/nMBH7AAAIkRfng");
	var mask_1_graphics_130 = new cjs.Graphics().p("Egj3AP0IgG/nMBH7AAAIkRfng");
	var mask_1_graphics_131 = new cjs.Graphics().p("Egj3AP0IgG/nMBH7AAAIkRfng");
	var mask_1_graphics_132 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_133 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_134 = new cjs.Graphics().p("Egj3AP0IgH/nMBH9AAAIkSfng");
	var mask_1_graphics_135 = new cjs.Graphics().p("Egj3AP0IgG/nMBH7AAAIkRfng");
	var mask_1_graphics_136 = new cjs.Graphics().p("Egj3AP0IgG/nMBH7AAAIkRfng");
	var mask_1_graphics_137 = new cjs.Graphics().p("Egj3AP0IgH/nMBH8AAAIkRfng");
	var mask_1_graphics_138 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_139 = new cjs.Graphics().p("Egj2AP0IgH/nMBH7AAAIkRfng");
	var mask_1_graphics_140 = new cjs.Graphics().p("Egj2AP0IgH/nMBH7AAAIkRfng");
	var mask_1_graphics_141 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_142 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_143 = new cjs.Graphics().p("Egj3AP0IgG/nMBH7AAAIkRfng");
	var mask_1_graphics_144 = new cjs.Graphics().p("Egj2AP0IgI/nMBH9AAAIkSfng");
	var mask_1_graphics_145 = new cjs.Graphics().p("Egj2AP0IgH/nMBH7AAAIkRfng");
	var mask_1_graphics_146 = new cjs.Graphics().p("Egj3AP0IgH/nMBH9AAAIkSfng");
	var mask_1_graphics_147 = new cjs.Graphics().p("Egj3AP0IgH/nIB1AAICBAAIABAAID0AAMAs+AAAICBAAIBDAAIQPAAIkQfkIgBADg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(90).to({graphics:mask_1_graphics_90,x:660.725,y:62.35}).wait(29).to({graphics:mask_1_graphics_119,x:218.45,y:17.925}).wait(1).to({graphics:mask_1_graphics_120,x:217.2,y:17.925}).wait(1).to({graphics:mask_1_graphics_121,x:213.55,y:17.925}).wait(1).to({graphics:mask_1_graphics_122,x:207.4,y:17.925}).wait(1).to({graphics:mask_1_graphics_123,x:198.8,y:17.925}).wait(1).to({graphics:mask_1_graphics_124,x:187.7,y:17.925}).wait(1).to({graphics:mask_1_graphics_125,x:174.2,y:17.925}).wait(1).to({graphics:mask_1_graphics_126,x:158.2,y:17.925}).wait(1).to({graphics:mask_1_graphics_127,x:139.75,y:17.925}).wait(1).to({graphics:mask_1_graphics_128,x:118.85,y:17.925}).wait(1).to({graphics:mask_1_graphics_129,x:95.5,y:17.925}).wait(1).to({graphics:mask_1_graphics_130,x:69.65,y:17.925}).wait(1).to({graphics:mask_1_graphics_131,x:41.4,y:17.925}).wait(1).to({graphics:mask_1_graphics_132,x:10.65,y:17.925}).wait(1).to({graphics:mask_1_graphics_133,x:-22.55,y:17.925}).wait(1).to({graphics:mask_1_graphics_134,x:-55.75,y:17.925}).wait(1).to({graphics:mask_1_graphics_135,x:-86.5,y:17.925}).wait(1).to({graphics:mask_1_graphics_136,x:-114.75,y:17.925}).wait(1).to({graphics:mask_1_graphics_137,x:-140.6,y:17.925}).wait(1).to({graphics:mask_1_graphics_138,x:-163.95,y:17.925}).wait(1).to({graphics:mask_1_graphics_139,x:-184.85,y:17.925}).wait(1).to({graphics:mask_1_graphics_140,x:-203.3,y:17.925}).wait(1).to({graphics:mask_1_graphics_141,x:-219.3,y:17.925}).wait(1).to({graphics:mask_1_graphics_142,x:-232.8,y:17.925}).wait(1).to({graphics:mask_1_graphics_143,x:-243.9,y:17.925}).wait(1).to({graphics:mask_1_graphics_144,x:-252.5,y:17.925}).wait(1).to({graphics:mask_1_graphics_145,x:-258.65,y:17.925}).wait(1).to({graphics:mask_1_graphics_146,x:-262.3,y:17.925}).wait(1).to({graphics:mask_1_graphics_147,x:-263.55,y:17.925}).wait(1).to({graphics:null,x:0,y:0}).wait(129));

	// epson_logo
	this.instance_7 = new lib.epson_logo();
	this.instance_7.setTransform(21.15,7.15,0.1469,0.1469,0,0,0,66.8,34.4);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(90).to({_off:false},0).to({alpha:1},8).to({_off:true},43).wait(136));

	// Layer_22
	this.instance_8 = new lib.txt_ecoTankPro_Logo();
	this.instance_8.setTransform(148.7,56.9);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(90).to({_off:false},0).to({y:64.4,alpha:1},8,cjs.Ease.quadOut).to({_off:true},43).wait(136));

	// txt_pain
	this.instance_9 = new lib.printer_01();
	this.instance_9.setTransform(242.6,30.85,0.1939,0.1771,0,0,0,1227.8,-253.8);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(90).to({_off:false},0).to({regX:1227.5,regY:-254,scaleX:0.2234,scaleY:0.2041,alpha:1},8,cjs.Ease.quadOut).to({_off:true},43).wait(136));

	// Layer_2 (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_119 = new cjs.Graphics().p("EhniAu5MAI7hdpUAAAgAjA/KAB8IAQAAUAKFAAUA5TAAsUA4iAArAK2AAXMAAABaOg");
	var mask_2_graphics_120 = new cjs.Graphics().p("EhemguwQAAgNIcAIQITAIQkAdIM1AYIADAAIERAIIMsAYIARABQDgAHJQAKIL1ALIMBALIDYADIbYAVIcqAXQe+AbHwARIABAKMAAABaDMjPCAABg");
	var mask_2_graphics_121 = new cjs.Graphics().p("EhndAu5MAI7hdnQAAgOIXAGQIQAHQoAeIM0AXIAEAAIEQAIIMrAZIARAAQDiAHJOAKIL0AMIMBAKIDXADIbYAWQQLAMMgALQe4AaH2ARIAAAKMAAABaCIm8AEg");
	var mask_2_graphics_122 = new cjs.Graphics().p("EhnWAu6MAI6hdkQAAgRIRADQIJAIQuAdIMzAXIAEAAIERAIIMpAZIARAAQDjAHJMAKIL0AMIL/ALIDYADIbXAWIcqAXQewAaH+ARIAAAKMAAABZ+Im1AKg");
	var mask_2_graphics_123 = new cjs.Graphics().p("EhnNAu7MAI5hdfQABgVIHgBQH/AHQ3AeIMzAXIAFAAIEPAIIMoAYIARABQDlAHJHAKIL0AMIL+ALIDXADIbWAWIcqAXQemAaIJARIABAKMAAABZ5ImuASg");
	var mask_2_graphics_124 = new cjs.Graphics().p("EhnCAu9MAI4hdZQACgaH7gGQHzAGRDAeIMyAYIAEAAIEQAIIMkAYIARAAQDoAIJDAKILyAMIL9ALIDXADIbTAXIcsAXQeWAaIYAQIABAJMAAABZ1ImjAbg");
	var mask_2_graphics_125 = new cjs.Graphics().p("Ehm0Au/MAI3hdSQACgfHtgMQHkAFRRAeIMxAYIAEAAIEPAHIMhAYIARABQDrAHI+AKILwANIL8AMIDXADIbQAXIcsAXQeDAaIsAQIABAJMAAABZtImXAng");
	var mask_2_graphics_126 = new cjs.Graphics().p("EhmjAvCMAI2hdJQACgnHcgTQHSAERiAeIMvAYIAEAAIEPAIIMdAYIARAAQDvAII3AKILuANIL7AMIDWAEQLfAKPvAMIcsAYQdtAZJCAPIABAJMAAABZlImIA2g");
	var mask_2_graphics_127 = new cjs.Graphics().p("EhmQAvFMAI1hc/QACguHIgcQG+ADR1AfIMuAXIAEAAIEPAIIMYAYIARAAQDzAIIvAKILsAOIL6AMIDVAEIbKAXIctAXQdVAZJaAQIACAIMAAABZcIl3BFg");
	var mask_2_graphics_128 = new cjs.Graphics().p("Ehl7AvJMAI0hc1QADg2GygmQGnACSLAgIMrAWIAEAAIEOAIIMUAYIARABQD5AHIkALQFKAGGgAHIL4AOIDVADQLJAMP9ANIctAWQc4AZJ5APIABAIMAAABZRIljBYg");
	var mask_2_graphics_129 = new cjs.Graphics().p("EhliAvNMAIxhcoQAFhAGXgxQGOAASjAgIMqAXIAEAAIENAIIMOAXIAQABQEAAIIaAKILnAPIL2ANIDUAEQK9AMQFANIcuAXQcZAYKYAPIACAHMAAABZFIlNBtg");
	var mask_2_graphics_130 = new cjs.Graphics().p("EhlHAvSMAIuhcaQAHhMF8g9QFwgBS/AhIMnAXIAFAAIEMAHIMHAYIARAAQEFAIIPALQFNAHGXAIILzAOIDUAEQKvAMQPAOIcuAXQb2AXK8AOIACAHMAAABY4Ik2CEg");
	var mask_2_graphics_131 = new cjs.Graphics().p("EhkqAvXMAIshcLQAIhYFdhKQFRgDTcAhIMmAXIAEAAIEMAIIL/AXIARABQENAIIDALILhAPILwAPIDTAFQKfAMQZAOIcwAXQbPAWLiAOIAEAHMAAABYoIkbCeg");
	var mask_2_graphics_132 = new cjs.Graphics().p("EhkKAvdMAIqhb7QAIhkE9hZQEugFT9AiIMjAXIAFAAIEKAIIL4AXIARAAQEUAJH1AKILeARILtAQIDTAFQKOAMQkAOIcxAYQalAVMNAOIAEAFMAAABYZIj/C5g");
	var mask_2_graphics_133 = new cjs.Graphics().p("EhjoAvjMAInhbpQAKhzEZhoQEKgHUgAjIMgAXIAEAAIEKAHILvAXIARAAQEdAJHnALILaARILqARIDSAFQJ8ANQvAPIcyAXQZ4AVM7ANIAFAFMAAABYIIjgDWg");
	var mask_2_graphics_134 = new cjs.Graphics().p("EhjFAvpMAIkhbXQALiBD1h3QDlgJVDAkIMdAWIAEAAIEJAIILnAWIARAAQElAJHYAMILXARILnASIDRAFQJqAOQ7APQN5AMO6ALQZLAUNoANIAGAEMAAABX3IjBDzg");
	var mask_2_graphics_135 = new cjs.Graphics().p("EhimAvvMAIihbHQANiNDTiGQDEgLVjAlIMaAWIAFAAIEIAHILfAWIAQABQEtAJHLALILTATILkATIDRAFQJZAORGAQIc0AXMAm0AAfIAHAEMAAABXnIimEOg");
	var mask_2_graphics_136 = new cjs.Graphics().p("EhiIAv0MAIfha4QAOiZC1iTQCkgNWAAlIMZAWIAFAAIEGAIILZAWIARAAQEzAKG/ALILQATILhAUIDQAGQJKAORQAQIc1AXMAm1AAeIAGADMAAABXYIiKEog");
	var mask_2_graphics_137 = new cjs.Graphics().p("EhhtAv5MAIdhaqQAPikCZifQCIgOWbAlIMXAWIAEAAIEGAIILSAWIARAAILtAVILNAUILfAUIDPAGQI8APRZAQQNMAMPqALMAm1AAdIAHADMAAABXLIhyE+g");
	var mask_2_graphics_138 = new cjs.Graphics().p("EhhVAv+MAIbhaeQAQiuCAiqQBugQWzAmIMWAWIADAAIEGAIILMAVIARABILoAVILLAUILcAVIDPAGQIvAPRhARQNAALP3AMMAm2AAcIAIACMAAABW/IhcFUg");
	var mask_2_graphics_139 = new cjs.Graphics().p("EhhAAwCMAIbhaTQAQi3Bpi0QBXgRXKAnIMTAWIAEAAIEFAIILHAVIARAAILlAWILHAUILcAWIDNAGQIkAQRoAQQM0AMQEAMQWbAQQbALIAJABMAAABW0IhJFng");
	var mask_2_graphics_140 = new cjs.Graphics().p("EhgsAwFMAIYhaIQARi/BVi9QBDgSXdAoIMSAVIAEAAIEEAIILCAVIARABILhAVILGAVILaAWIDNAHQIaAPRvARQMqAMQOAMQWCAQQ1AKIAIABMAAABWrIg4F2g");
	var mask_2_graphics_141 = new cjs.Graphics().p("EhgcAwJMAIXhaAQASjGBEjEQAxgTXuAoIMQAVIAEAAIEFAIIK9AVIARAAILfAWILEAWILYAWIDMAHQISAPR0ARQMiAMQXAMQVsAQRLAKIAJABMAAABWiIgpGFg");
	var mask_2_graphics_142 = new cjs.Graphics().p("EhgOAwLMAIWhZ5QASjLA2jKQAigUX8AoIMPAVIAEAAIEEAIIK7AVIAQAAILcAWILCAWILYAXIDMAHQIKAQR5ARQMaALQgAMQVZAQReAJIAJABMAAABWbIgdGRg");
	var mask_2_graphics_143 = new cjs.Graphics().p("EhgCAwNMAIUhZzQATjQAqjPQAWgVYHAoIMOAWIAEAAIEEAHIK4AVIAQABILaAWILBAWILXAXIDLAHQIEAQR9ARQMVAMQlAMQVLAPRsAKIAKAAMAAABWWIgSGag");
	var mask_2_graphics_144 = new cjs.Graphics().p("Ehf5AwPMAIUhZvQATjTAgjUQAMgVYRApIMOAVIAEAAIEDAIIK1AUIARABILYAWILBAWILVAYIDLAHQIAAQSAARQMQAMQqAMQU/APR4AJIAKAAMAAABWSIgKGig");
	var mask_2_graphics_145 = new cjs.Graphics().p("EhfzAwQMAIUhZrQATjXAajWQAFgVYXAoIMNAWIAEAAIEDAHIK0AVIARAAILXAXILAAWILVAYIDLAHQH8AQSCARQMNAMQuAMQU2APSBAJIAKAAMAAABWOIgFGog");
	var mask_2_graphics_146 = new cjs.Graphics().p("EhfvAwRMAIThZpIApmwQABgWYcApIMMAVIAFAAIEDAIIKyAUIARABILWAWIK/AXILVAXIDLAHQH6ARSEARQMKAMQxAMQUxAPSGAJIAKAAMgABBc3g");
	var mask_2_graphics_147 = new cjs.Graphics().p("EhfuAwRMAI7hgZQAAgWYdApIMMAVIAEAAIEDAIQJ/ASMbAZIK/AXILUAXIDLAHUANOAAcApqAAeQU2APSMAJMAAABc3g");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(119).to({graphics:mask_2_graphics_119,x:1077.925,y:-34.6017}).wait(1).to({graphics:mask_2_graphics_120,x:1076.6,y:-34.5524}).wait(1).to({graphics:mask_2_graphics_121,x:1072.525,y:-34.4628}).wait(1).to({graphics:mask_2_graphics_122,x:1065.775,y:-34.3542}).wait(1).to({graphics:mask_2_graphics_123,x:1056.35,y:-34.275}).wait(1).to({graphics:mask_2_graphics_124,x:1044.2,y:-34.175}).wait(1).to({graphics:mask_2_graphics_125,x:1029.375,y:-34.05}).wait(1).to({graphics:mask_2_graphics_126,x:1011.825,y:-33.9}).wait(1).to({graphics:mask_2_graphics_127,x:991.6,y:-33.775}).wait(1).to({graphics:mask_2_graphics_128,x:968.65,y:-33.6}).wait(1).to({graphics:mask_2_graphics_129,x:943.025,y:-33.375}).wait(1).to({graphics:mask_2_graphics_130,x:914.7,y:-33.1783}).wait(1).to({graphics:mask_2_graphics_131,x:883.675,y:-32.9375}).wait(1).to({graphics:mask_2_graphics_132,x:849.95,y:-32.7071}).wait(1).to({graphics:mask_2_graphics_133,x:813.525,y:-32.4333}).wait(1).to({graphics:mask_2_graphics_134,x:777.125,y:-32.215}).wait(1).to({graphics:mask_2_graphics_135,x:743.4,y:-32.001}).wait(1).to({graphics:mask_2_graphics_136,x:712.35,y:-31.7828}).wait(1).to({graphics:mask_2_graphics_137,x:684.025,y:-31.6153}).wait(1).to({graphics:mask_2_graphics_138,x:658.4,y:-31.4349}).wait(1).to({graphics:mask_2_graphics_139,x:635.45,y:-31.283}).wait(1).to({graphics:mask_2_graphics_140,x:615.225,y:-31.1817}).wait(1).to({graphics:mask_2_graphics_141,x:597.675,y:-31.0559}).wait(1).to({graphics:mask_2_graphics_142,x:582.85,y:-30.9583}).wait(1).to({graphics:mask_2_graphics_143,x:570.725,y:-30.8835}).wait(1).to({graphics:mask_2_graphics_144,x:561.275,y:-30.8448}).wait(1).to({graphics:mask_2_graphics_145,x:554.525,y:-30.7978}).wait(1).to({graphics:mask_2_graphics_146,x:550.5,y:-30.7841}).wait(1).to({graphics:mask_2_graphics_147,x:549.125,y:-30.7591}).wait(37).to({graphics:null,x:0,y:0}).wait(93));

	// txt_twoYears
	this.instance_10 = new lib.txt_twoYears();
	this.instance_10.setTransform(251.7,32.45,1,1,0,0,0,128.1,46);
	this.instance_10._off = true;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(119).to({_off:false},0).wait(55).to({y:52.45,alpha:0},9,cjs.Ease.quadIn).to({_off:true},1).wait(93));

	// txt_theAssets
	this.instance_11 = new lib.txt_theAssets();
	this.instance_11.setTransform(147.6,110.1);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(47).to({_off:false},0).to({y:124.1,alpha:1},7,cjs.Ease.quadOut).wait(28).to({y:148.1,alpha:0},7,cjs.Ease.quadIn).to({_off:true},1).wait(187));

	// Layer_94
	this.instance_12 = new lib.cartridge_mc();
	this.instance_12.setTransform(-167.25,27.35,0.3367,0.3367,0,0,0,278,57.6);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(44).to({_off:false},0).to({x:-16.25},10,cjs.Ease.quadOut).wait(28).to({alpha:0},7).to({_off:true},1).wait(187));

	// txt_isYour
	this.instance_13 = new lib.txt_lets();
	this.instance_13.setTransform(56.3,82.95);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).to({y:100.95,alpha:1},8,cjs.Ease.quadOut).wait(32).to({y:116.95,alpha:0},6,cjs.Ease.quadIn).to({_off:true},1).wait(230));

	// background_color
	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("EhKBAFKQhwAAAAgJIAAqBQAAgJBwAAMCUDAAAQBwAAAAAJIAAKBQAAAJhwAAg");
	this.shape_31.setTransform(159.9991,24.9998,0.3299,0.7576);

	this.timeline.addTween(cjs.Tween.get(this.shape_31).wait(277));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-190.2,-88.3,1193.3,384);
// library properties:
lib.properties = {
	id: 'D13842C17BB34EAD8425AF1A57942765',
	width: 320,
	height: 50,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"cartridges_01.jpg", id:"cartridges_01"},
		{src:"paintColors.jpg", id:"paintColors"},
		{src:"printer.jpg", id:"printer"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['D13842C17BB34EAD8425AF1A57942765'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;