(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Epson_Logo = function() {
	this.initialize(img.Epson_Logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,154,51);


(lib.projector_image = function() {
	this.initialize(img.projector_image);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,643,250);


(lib.shield_icon = function() {
	this.initialize(img.shield_icon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,108,126);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt_Tolerant = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AggBcQgNgEgIgIQgHgHgEgLQgDgKAAgOIAAgGIArAAIAAAGQAAAMAGAHQAGAIAMAAQAKAAAGgGQAHgFAAgLQAAgJgFgFQgGgEgHgDIgfgMQgTgHgLgLQgJgMgBgUQAAgLAFgKQADgKAIgIQAJgHAMgFQANgEARAAQAgAAAPAOQAQANAAAZIAAAIIgqAAQgBgPgEgGQgFgHgLAAQgIAAgHAFQgHAFAAAKQABAHAEAFQAEAFAMAEIAbAKQAWAHAJALQAKAMgBAVQAAAPgEAKQgGALgJAHQgJAHgMADQgMAEgPAAQgTAAgNgEg");
	this.shape.setTransform(79.75,64.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgDB0QgJgBgEgHQgFgFgBgJQgCgJAAgPIAAhnIgYAAIAAggIAYAAIAAg0IAuAAIAAA0IAbAAIAAAgIgbAAIAABiQAAALADAEQADAFALAAIAFAAIAFAAIAAAgIgPAAIgPABQgOAAgIgCg");
	this.shape_1.setTransform(67.5,62.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AAXBeIAAh9QgBgPgFgFQgEgGgLAAQgXAAAAAeIAAB5IgwAAIAAi2IAtAAIAAAVIACAAQAGgNANgHQALgGAPAAQAWAAANAMQALANABAbIAACHg");
	this.shape_2.setTransform(54.15,64.775);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_3.setTransform(38.075,64.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("ABCBeIAAh/QAAgMgEgGQgEgGgKAAQgLAAgHAIQgGAHAAAQIAAB4IguAAIAAh/QAAgMgFgGQgEgGgKAAQgLAAgHAIQgGAHAAAQIAAB4IgvAAIAAi2IAtAAIAAATIABAAQAIgNALgGQALgFAQAAQAQAAAKAIQALAHAEAOIAAAAQAGgOAMgIQAMgHARAAQAXAAALAOQALAOAAAbIAACEg");
	this.shape_4.setTransform(17.575,64.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AAXBeIAAh9QgBgPgFgFQgEgGgLAAQgYAAABAeIAAB5IgwAAIAAi2IAtAAIAAAVIABAAQAIgNAMgHQAKgGAQAAQAWAAAMAMQAMANABAbIAACHg");
	this.shape_5.setTransform(-3.55,64.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgEgTQgDgSAAgYQAAgWAEgSQADgSAJgMQAJgMANgHQAOgGATAAQAVAAAOAGQAOAGAIAMQAJAMACASQAEASAAAXQAAAYgEASQgDASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgNg6QgFAEgCAJQgCAJgCALIAAAZIAAAaQACAMACAJQACAIAFAFQAGAFAHAAQAOAAAGgPQAFgPAAgjQAAghgFgPQgGgPgOAAQgHAAgGAFg");
	this.shape_6.setTransform(-19.95,64.9731);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_7.setTransform(-32.775,64.775);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_8.setTransform(-42.975,61.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgZBcIgwi2IAxAAIAaCBIAAAAIAZiBIAvAAIguC2g");
	this.shape_9.setTransform(-54.325,65);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AAWBeIAAh9QAAgPgEgFQgFgGgKAAQgZAAAAAeIAAB5IguAAIAAi2IAtAAIAAAVIAAAAQAIgNALgHQAMgGAOAAQAXAAAMAMQAMANAAAbIAACHg");
	this.shape_10.setTransform(-70.1,64.775);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_11.setTransform(-86.175,64.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("Ag7B5IAAgkIANACQANAAAFgHQAGgGABgMIg0i2IAxAAIAbB9IAAAAIAYh9IAvAAIgsCpQgGAXgGAOQgGAOgHAJQgHAHgKADQgLACgRAAg");
	this.shape_12.setTransform(111.125,30.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_13.setTransform(98.925,27.625);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgEgTQgDgSAAgYQAAgWAEgSQAEgSAIgMQAIgMAOgHQAOgGATAAQAVAAAOAGQAOAGAIAMQAIAMAEASQADASAAAXQAAAYgDASQgEASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgMg6QgGAEgCAJQgDAJgBALIAAAZIAAAaQABAMADAJQACAIAGAFQAEAFAIAAQAOAAAGgPQAFgPAAgjQAAghgFgPQgGgPgOAAQgIAAgEAFg");
	this.shape_14.setTransform(84.65,27.8231);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgDB0QgIgCgFgFQgFgGgBgJQgCgJAAgPIAAhnIgYAAIAAggIAYAAIAAg0IAuAAIAAA0IAbAAIAAAgIgbAAIAABiQgBALAEAFQADAEALAAIAFAAIAFAAIAAAgIgPABIgQAAQgNAAgIgCg");
	this.shape_15.setTransform(71.8,25.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgeBbQgNgEgIgLQgJgLgEgTQgFgSAAgcQAAgbAGgTQAFgSAKgLQAKgLANgFQAOgEAPAAQAhAAAQATQARATAAAhIgtAAIgBgNIgDgMQgCgGgEgDQgEgDgHAAQgIAAgFAEQgFAEgDAHQgDAIgBAMIgBAbIABAdQABAMADAIQADAHAEAEQAFAEAHAAQAMAAAGgLQAFgKAAgWIAtAAQAAAkgQATQgRATglAAQgQAAgOgFg");
	this.shape_16.setTransform(59.125,27.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AgvBbQgIgEgFgIQgFgHgCgJQgDgKAAgJQAAgNADgJQADgJAFgHQAGgGAIgEQAJgFANgDIAZgHQALgDADgFQAFgEAAgKQAAgKgGgGQgEgGgMAAQgKAAgFAHQgGAGAAALIAAAFIgqAAIAAgFQAAgQAFgKQAFgLAIgHQAJgGAMgDQAMgDANAAQAUAAANAEQANAEAHAIQAHAHADALQACAKABAMIAABfIABAUIAEAQIgtAAIgDgKIgCgJIgBAAQgIAOgLAEQgKAFgQAAQgNAAgJgFgAALAGIgKADQgOAEgGAHQgGAHAAAMQAAALAEAHQAEAIAKAAIAJgCQAFgBAEgEQAEgDADgGQACgFABgIIAAgkg");
	this.shape_17.setTransform(43.2,27.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgYB8IAAiWIgYAAIAAggIAYAAIAAgVQAAgMADgJQAEgIAGgFQAGgFAIgDQAKgCALAAIAZABIAAAiIgFgBIgEAAQgKAAgEAEQgEADgBAIIAAAQIAcAAIAAAgIgcAAIAACWg");
	this.shape_18.setTransform(30.45,24.625);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgYB8IAAiWIgYAAIAAggIAYAAIAAgVQAAgMADgJQADgIAHgFQAGgFAJgDQAIgCAMAAIAZABIAAAiIgFgBIgEAAQgKAAgEAEQgFADABAIIAAAQIAbAAIAAAgIgbAAIAACWg");
	this.shape_19.setTransform(12.75,24.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgEgTQgDgSAAgYQAAgWAEgSQADgSAJgMQAJgMANgHQAOgGATAAQAVAAAOAGQAOAGAIAMQAJAMACASQAEASAAAXQAAAYgEASQgDASgJAMQgIAMgOAGQgOAGgUAAQgUAAgOgGgAgNg6QgEAEgDAJQgCAJgCALIAAAZIAAAaQACAMACAJQADAIAEAFQAGAFAHAAQAOAAAGgPQAFgPAAgjQAAghgFgPQgGgPgOAAQgHAAgGAFg");
	this.shape_20.setTransform(-0.25,27.8231);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgDB0QgIgCgFgFQgFgGgBgJQgCgJAAgPIAAhnIgYAAIAAggIAYAAIAAg0IAuAAIAAA0IAbAAIAAAgIgbAAIAABiQAAALADAFQADAEAKAAIAGAAIAFAAIAAAgIgPABIgQAAQgNAAgIgCg");
	this.shape_21.setTransform(-21,25.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AAWBeIAAh9QAAgPgEgFQgFgGgLAAQgYAAAAAeIAAB5IgvAAIAAi2IAtAAIAAAVIABAAQAHgNAMgHQALgGAPAAQAXAAAMAMQANANAAAbIAACHg");
	this.shape_22.setTransform(-34.35,27.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AguBbQgJgEgFgIQgFgHgDgJQgCgKAAgJQAAgNADgJQACgJAGgHQAFgGAKgEQAIgFAMgDIAagHQAKgDAFgFQADgEAAgKQAAgKgEgGQgGgGgKAAQgLAAgGAHQgFAGAAALIAAAFIgqAAIAAgFQAAgQAFgKQAFgLAJgHQAIgGAMgDQALgDAOAAQAUAAANAEQANAEAHAIQAIAHACALQADAKgBAMIAABfIABAUIAFAQIgtAAIgDgKIgDgJIAAAAQgJAOgKAEQgKAFgRAAQgMAAgIgFgAAKAGIgKADQgNAEgGAHQgGAHAAAMQAAALAEAHQAEAIAJAAIAJgCQAFgBAFgEQAEgDADgGQADgFgBgIIAAgkg");
	this.shape_23.setTransform(-50.9,27.825);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_24.setTransform(-63.625,27.625);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_25.setTransform(-77.575,27.825);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_26.setTransform(-89.275,24.875);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgDgTQgEgSAAgYQAAgWAEgSQAEgSAIgMQAIgMAPgHQANgGATAAQAVAAAOAGQAOAGAJAMQAHAMADASQAEASAAAXQAAAYgEASQgDASgJAMQgIAMgOAGQgOAGgUAAQgUAAgOgGgAgNg6QgEAEgDAJQgDAJAAALIgBAZIABAaQAAAMADAJQADAIAEAFQAFAFAIAAQAPAAAFgPQAFgPAAgjQAAghgFgPQgFgPgPAAQgIAAgFAFg");
	this.shape_27.setTransform(-101.25,27.8231);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("AgYB5IAAjJIg0AAIAAgoICaAAIAAAoIg1AAIAADJg");
	this.shape_28.setTransform(-117.3,24.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_Tolerant, new cjs.Rectangle(-188,2.4,369,81.3), null);


(lib.txt_toDyeFor = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgTAXIAAgtIAnAAIAAAtg");
	this.shape.setTransform(65.375,-81.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgpBTIAAihIAnAAIAAAWIABAAQAFgMAJgHQAJgHANAAIAEAAIADABIAAAnIgGAAIgGAAIgLABQgGACgEADQgFAEgCAFQgCAGAAAIIAABgg");
	this.shape_1.setTransform(57.925,-87.875);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgeBQQgMgFgHgLQgHgKgEgQQgDgRAAgUQAAgUADgQQAEgQAIgLQAHgKAMgGQAMgFARAAQASgBANAGQAMAFAIALQAGALAEAPQACAQAAAVQAAAUgCAQQgEAQgHALQgIAKgMAFQgNAGgRAAQgSAAgMgFgAgLgzQgFAEgCAIQgCAHAAALIgBAWIABAWQAAALACAHQACAIAFAEQAFAEAGAAQANAAAEgNQAFgNAAgeQAAgegFgNQgEgNgNAAQgGAAgFAEg");
	this.shape_2.setTransform(45.6,-87.7021);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgVBtIAAiEIgVAAIAAgcIAVAAIAAgSQAAgLADgIQADgHAFgFQAGgEAHgCQAIgCAKAAIAWABIAAAdIgEAAIgEAAQgIAAgEADQgEADAAAHIAAAOIAYAAIAAAcIgYAAIAACEg");
	this.shape_3.setTransform(34.55,-90.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgiBNQgMgHgGgNQgGgNgCgPIAAgdQAAgQABgQQADgPAGgLQAIgMAMgHQANgGATAAQASgBAMAGQALAGAHAKQAHAMACAOQADAQAAATIAAAIIhRAAIAAAMIABAPIADALQACAFAFAEQAEADAEAAQAKAAAGgHQAEgIACgQIAlAAQgBAdgOAPQgOAOgdAAQgWABgNgIgAgIg1QgFADgCAFIgDAKIgBALIAAAHIApAAIgCgRQAAgGgCgFQgDgFgEgDQgDgDgHABQgFAAgEACg");
	this.shape_4.setTransform(16.95,-87.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("Ag0BrIAAgfIALABQAMAAAEgGQAGgGAAgKIgtihIArAAIAXBvIABAAIAVhvIApAAIgnCWQgFAUgFAMQgFANgHAHQgFAHgKACQgJACgPAAg");
	this.shape_5.setTransform(3.85,-85.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AgyBZQgMgTAAgtQAAgsAMgUQAMgUAaAAQALAAAHAEQAJAFAGAKIABAAIAAhEIApAAIAADVIgoAAIAAgRIAAAAQgHAMgJAEQgHAFgMAAQgaAAgMgUgAgRgOQgEANAAAaQAAAaAEANQAFAOAMAAQAOAAAEgOQAEgNAAgaQAAgagEgNQgEgNgOAAQgMAAgFANg");
	this.shape_6.setTransform(-10,-90.125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgeBQQgMgFgHgLQgIgKgCgQQgEgRAAgUQAAgUAEgQQADgQAIgLQAHgKAMgGQAMgFARAAQASgBANAGQAMAFAHALQAIALACAPQADAQAAAVQAAAUgDAQQgDAQgHALQgIAKgMAFQgNAGgRAAQgRAAgNgFgAgLgzQgFAEgCAIQgCAHgBALIAAAWIAAAWQABALACAHQACAIAFAEQAEAEAHAAQANAAAEgNQAFgNAAgeQAAgegFgNQgEgNgNAAQgHAAgEAEg");
	this.shape_7.setTransform(-30.7,-87.7021);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgDBnQgHgCgEgFQgEgFgCgIQgBgIAAgNIAAhbIgVAAIAAgcIAVAAIAAguIAoAAIAAAuIAYAAIAAAcIgYAAIAABWQAAAKADAEQADAEAJAAIAFAAIAEgBIAAAdIgNABIgOAAQgMAAgHgBg");
	this.shape_8.setTransform(-41.75,-89.925);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgcBRQgMgEgHgGQgGgHgDgJQgDgKAAgLIAAgGIAlAAIAAAGQAAAKAGAHQAFAGALAAQAJAAAFgFQAGgFAAgJQAAgIgFgEQgEgEgGgDIgcgKQgRgGgJgKQgJgLAAgRQAAgKAEgJQADgJAHgGQAHgHAMgEQALgDAPAAQAcAAANALQAOAMAAAXIAAAGIglAAQAAgMgEgHQgEgFgLAAQgGgBgGAFQgGAEAAAJQAAAGAEAFQADAFALADIAYAJQATAGAIAKQAJAKAAATQAAAMgFAKQgEAKgIAFQgIAHgLACQgLADgNAAQgRAAgLgDg");
	this.shape_9.setTransform(-59.075,-87.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgSAwIAAhfIAkAAIAABfg");
	this.shape_10.setTransform(-69.15,-96.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgCBnQgIgCgEgFQgEgFgBgIQgCgIAAgNIAAhbIgVAAIAAgcIAVAAIAAguIAoAAIAAAuIAYAAIAAAcIgYAAIAABWQAAAKADAEQADAEAJAAIAEAAIAFgBIAAAdIgNABIgOAAQgMAAgGgBg");
	this.shape_11.setTransform(-76.9,-89.925);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgVBrIAAjVIArAAIAADVg");
	this.shape_12.setTransform(-84.725,-90.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_toDyeFor, new cjs.Rectangle(-194.5,-110.4,369,39.5), null);


(lib.txt_sureColor_f10070_endFrame = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AykEpIAAggIALACQAMAAAEgGQAGgHAAgKIgtiiIArAAIAZBwIABAAIAUhwIAqAAIgoCYQgFATgFAOQgFAMgGAHQgHAHgKACQgJACgPAAgASEDxQgNgIgGgNQgGgMgBgQIgBgeQAAgRABgPQADgPAGgMQAIgLAMgHQANgHAVAAQASAAALAFQAMAHAHAKQAHALACAPQADAQAAATIAAAJIhTAAIABAbIAEAMQACAFAEADQAEADAGAAQAKABAFgIQAEgHACgRIAmAAQgBAdgOAPQgOAPgeAAQgWAAgNgHgASdBtQgEADgCAFIgEAKIgBASIAqAAIgBgRQgBgHgCgFQgCgFgEgDQgEgCgGAAQgHAAgEADgAEIDzQgMgFgIgLQgHgKgDgQQgDgRAAgVQAAgUADgRQAEgPAHgMQAIgKAMgGQAMgFASAAQASgBANAGQAMAFAIALQAHALADAQQADAQAAAVQAAAVgDAQQgEAQgHALQgIAKgMAGQgNAFgRAAQgTAAgMgFgAEbBuQgFAFgCAHQgDAIAAALIAAAtQAAAKADAJQACAHAFAEQAFAFAHgBQANAAAEgMQAFgPAAgeQAAgegFgOQgEgNgNAAQgHAAgFAEgAgnD0QgHgEgFgGQgEgHgDgIQgCgJAAgIQAAgLACgJQADgIAFgFQAFgHAIgDQAHgFALgCIAXgHQAKgCADgFQADgDABgJQAAgJgFgGQgEgFgLAAQgJAAgEAGQgFAFgBAKIAAAFIglAAIAAgFQAAgNAFgKQAFgJAHgGQAIgGAKgCQAKgDALAAQAUAAAKADQAMAEAHAGQAFAIADAJQADAJgBAKIABBoIAEANIgoAAIgDgIIgBgJIgBAAQgHANgKAEQgIAEgQAAQgLAAgHgEgAAMCpIgJACQgNADgEAHQgGAFAAAMQAAAKAEAGQADAHAJgBIAIgBQAEgBAEgDQAEgDACgFQACgFABgHIAAgggAn3DzQgJgEgGgMIgBAAIAAARIgoAAIAAjXIAqAAIAABEIAAAAQAHgJAIgGQAIgEAMAAQAaAAAMAUQAMAUAAAtQAAAugMATQgMAUgaAAQgMAAgJgFgAoCB7QgDAOAAAaQAAAbADAOQAFANANAAQAOAAAEgNQAEgOAAgbQAAgagEgOQgEgNgOAAQgNAAgFANgAq3DtQgKgKAAgYIAAh5IAqAAIAABwQgBANAFAFQAEAFAKAAQAVAAAAgcIAAhrIAqAAIAACiIgoAAIAAgSIgBAAQgGAMgLAFQgKAFgNAAQgVAAgLgLgAtQDoQgQgQAAgeIAAgJIArAAIABAUQABAGAEAFQADAEAGADQAGACAIAAQAKAAAIgHQAIgGAAgOQAAgHgCgFQgCgGgFgEQgEgEgHgDIgTgIQgOgEgLgGQgKgGgHgIQgHgIgEgKQgDgJAAgOQAAggASgQQARgPAgAAQAOgBAMAEQANADAIAHQAJAHAGALQAFAMAAAOIAAAHIgqAAQAAgQgGgIQgFgJgNAAQgHAAgFACQgFADgDADQgDAEAAAEIgCAKQAAAJAEAIQAEAGAPAGIAiAPQALAFAIAGQAIAGAFAHQAFAHACAHQABAIAAAKQABAjgVAQQgTAPgkAAQglAAgPgQgAwODxQgMgIgGgNQgGgMgCgQIgBgeQAAgRACgPQADgPAGgMQAIgLAMgHQAMgHAWAAQASAAAMAFQALAHAHAKQAGALADAPQACAQAAATIAAAJIhSAAIABAbIADAMQADAFAEADQAEADAFAAQALABAFgIQAFgHABgRIAmAAQgBAdgOAPQgOAPgeAAQgXAAgNgHgAv0BtQgEADgDAFIgDAKIgBASIAqAAIgBgRQAAgHgDgFQgCgFgEgDQgEgCgHAAQgGAAgEADgAQ2D0QgIgCgEgFQgDgFgCgIQgBgIgBgMIAAheIgUAAIAAgcIAUAAIAAguIAqAAIAAAuIAYAAIAAAcIgYAAIAABYQAAAKADAFQADADAJAAIAJAAIAAAcIgbABQgNABgHgCgABwD0QgHgCgEgFQgEgFgCgIQgBgIAAgMIAAheIgVAAIAAgcIAVAAIAAguIApAAIAAAuIAYAAIAAAcIgYAAIAABYQAAAKADAFQADADAJAAIAJAAIAAAcIgbABQgMABgIgCgAT1D0IAAiiIAoAAIAAAWIAAAAQAHgMAJgHQAJgHANAAIAEAAIADABIAAAnIgMgBIgMACQgFACgFADQgEADgDAHQgDAFAAAIIAABhgAPaD0IAAhvQAAgNgEgFQgFgFgJAAQgWAAAAAbIAABrIgpAAIAAiiIAnAAIAAATIAAAAQAHgMALgGQALgFANAAQAUAAAKALQAMAKAAAZIAAB4gANGD0IAAiiIApAAIAACigALmD0IAAiiIAnAAIAAAWIABAAQAGgMAJgHQAKgHANAAIADAAIAEABIAAAnIgNgBIgLACQgGACgEADQgEADgDAHQgDAFAAAIIAABhgAJPD0IAAjXIBMAAQAQAAANAGQAKAFAIAJQAGAJAEAMQACALAAAMQAAARgEANQgGAMgJAIQgJAIgMADQgNAEgPABIgXAAIAABVgAJ7B+IATAAQAMAAAJgIQAIgHgBgRQABgQgHgIQgHgJgRAAIgRAAgAHKD0IAAhvQAAgNgEgFQgEgFgKAAQgWAAAAAbIAABrIgqAAIAAiiIAoAAIAAATIABAAQAGgMALgGQALgFANAAQAUAAALALQAKAKAAAZIAAB4gACqD0IAAiiIAqAAIAACigAh2D0IAAhxQAAgKgEgGQgEgFgJAAQgKAAgGAHQgFAGgBAPIAABqIgqAAIAAhxQAAgKgDgGQgEgFgIAAQgLAAgFAHQgHAGAAAPIAABqIgpAAIAAiiIAoAAIAAARIAAAAQAJgMAJgFQAKgEAOAAQAOAAAKAGQAKAHADANIABAAQAEgNALgHQALgGAPAAQAUAAALAMQAJANAAAXIAAB2gAlZD0IAAiiIArAAIAACigAmcD0IAAjXIAqAAIAADXgA1JD0IAAjXIBHAAQAYAAANAHQAOAIAHANQAJAOACATQACAUABAYQAAAcgDAVQgEAVgJAOQgIANgOAHQgOAGgWAAgA0dDVIATAAQALAAAIgEQAGgEAEgJQAFgKABgPIAAhFQgBgOgEgIQgDgKgIgEQgHgGgNABIgSAAgANGA+IAAgjIApAAIAAAjgACqA+IAAgjIAqAAIAAAjgAlZA+IAAgjIArAAIAAAjgANlhPQgNgFgHgMQgJgMgCgUQgEgUAAgcIACgqQABgVAHgPQAGgRAOgJQANgJAYAAQAUgBAMAGQANAFAHANQAIANAEATQACAUAAAcIgBArQgBAUgHAQQgGAPgOAKQgNAIgYABQgUAAgMgGgAN5kCQgEAEgCAIQgEAIgBAOIAABaQABANAEAHQACAHAEADQAFADAHAAQAHAAAFgEQAEgDADgIQACgIABgOIAAhbQgBgMgCgIQgDgHgEgDQgFgCgHAAQgHAAgFADgAJPhPQgNgFgHgMQgJgMgCgUQgEgUAAgcIACgqQABgVAHgPQAGgRAOgJQANgJAYAAQAUgBAMAGQANAFAIANQAIANADATQACAUAAAcIgBArQgCAUgGAQQgHAPgNAKQgOAIgXABQgTAAgNgGgAJjkCQgEAEgCAIQgEAIgBAOIAABaQABANAEAHQACAHAEADQAFADAHAAQAHAAAFgEQAEgDADgIQADgIAAgOIAAhbQgBgMgCgIQgDgHgEgDQgFgCgHAAQgHAAgFADgAHEhPQgNgFgIgMQgIgMgDgUQgCgUAAgcIABgqQACgVAGgPQAHgRANgJQAOgJAXAAQATgBAOAGQAMAFAHANQAJANACATQAEAUAAAcIgCArQgBAUgHAQQgGAPgOAKQgNAIgYABQgUAAgMgGgAHZkCQgFAEgDAIQgCAIgBAOIAABaQABANACAHQADAHAFADQAEADAHAAQAHAAAFgEQAEgDADgIQADgIABgOIAAhbQgBgMgEgIQgCgHgEgDQgFgCgHAAQgIAAgDADgAiAhPQgMgFgHgLQgHgKgDgQQgDgRAAgUQAAgVADgQQAEgPAHgMQAHgKAMgGQANgFASAAQASgBAMAGQAMAFAIALQAHALADAPQADAQAAAWQAAAUgDAQQgEARgHAKQgIALgMAEQgMAGgRAAQgTAAgNgFgAhtjTQgEAFgCAHQgCAHgBALIAAAuQABAKACAIQACAHAEAEQAFAFAIAAQAMAAAFgOQAEgNAAgeQAAgegEgOQgFgNgMAAQgIAAgFAEgAlOhPQgMgFgHgLQgHgKgDgQQgDgRAAgUQAAgVADgQQADgPAIgMQAIgKALgGQANgFASAAQASgBAMAGQAMAFAIALQAHALADAPQADAQAAAWQAAAUgDAQQgEARgHAKQgIALgMAEQgMAGgRAAQgTAAgNgFgAk7jTQgEAFgCAHQgCAHgBALIAAAuQABAKACAIQACAHAEAEQAFAFAIAAQAMAAAFgOQAFgNgBgeQABgegFgOQgFgNgMAAQgIAAgFAEgAnmhSQgOgIgIgPQgHgOgDgVQgCgUAAgZQAAgYACgVQADgUAHgPQAIgPAOgHQAOgJAZAAQAXAAAOAIQANAHAGAMQAHALACAOIABAYIgrAAQAAgXgFgKQgGgLgPAAQgIAAgFAEQgGAEgDALQgCAJgBAQIgCAnQAAAXACAQQABAOAEAJQAEAIAEADQAGADAHAAQAFAAAGgCQAFgCADgGQADgGACgLQADgKAAgSIArAAQAAASgDAQQgCAPgIAMQgHAMgNAGQgOAHgVAAQgZAAgOgIgAp1hRQgMgIgHgMQgGgNgBgPIgBgfQAAgQACgPQACgPAHgLQAHgMANgHQAMgHAVAAQASAAAMAFQALAHAHAKQAGALADAPQACAQAAASIAAAJIhSAAIABAbIAEAMQACAFAEADQAEADAFABQALAAAFgIQAFgHACgQIAlAAQgCAcgOAPQgNAPgeAAQgWAAgNgHgApcjUQgEADgCAEIgEALIgBARIArAAIgCgQQgBgHgCgFQgCgFgEgDQgEgCgHAAQgGAAgEADgAtvhVQgLgKABgYIAAh4IAoAAIAABwQABAMAEAFQAEAFAJAAQAXAAAAgbIAAhrIAoAAIAAChIgnAAIAAgTIAAAAQgHANgKAEQgLAGgOAAQgTAAgLgLgAwHhaQgQgQgBgdIAAgJIAsAAIABATQABAGADAFQAEAEAFADQAGACAIAAQAKAAAIgHQAIgGAAgOQAAgGgCgGQgCgFgEgEQgEgFgIgDIgSgHQgPgFgKgGQgKgFgHgIQgIgIgDgJQgEgLAAgNQAAggASgPQASgQAfAAQAOAAANADQALAEAJAGQAJAIAGAKQAEALAAAPIAAAGIgpAAQAAgOgFgJQgGgIgMAAQgIAAgEACQgGACgCADQgDAEgBAEIgCAKQABAJAEAHQAEAHAOAGIAhAOQAMAFAJAGQAHAHAFAGQAFAHACAIQABAIAAAKQAAAigTAQQgUAPgjAAQglAAgPgQgALPhNQADgTAFgVQAEgVAJgXQAHgWAMgWQALgWAQgVIhZAAIAAglICCAAIAAAhQgNATgKAUQgKAWgIAWQgIAXgFAXQgGAXgCAXgAFIhNIAAiWIgrAAIAAgdIAFAAQAVAAAMgHQAMgJAEgRIAgAAIAADUgACbhNIAAjWIB3AAIAAAjIhNAAIAAAyIBIAAIAAAkIhIAAIAABdgAgPhOIAAihIAmAAIAAAWIAAAAQAHgMAJgHQAJgHANAAIAEAAIADABIAAAnIgMgBIgMACQgFABgFAEQgEAEgCAFQgEAGAAAHIAABhgAjchOIAAjWIApAAIAADWgArohOIAAihIAnAAIAAAWIAAAAQAHgMAJgHQAJgHANAAIAEAAIADABIAAAnIgMgBIgMACQgFABgFAEQgEAEgCAFQgEAGAAAHIAABhg");
	this.shape.setTransform(-1.2545,-133.1113,0.8316,0.8316);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070_endFrame, new cjs.Rectangle(-113.8,-157.8,225.2,49.400000000000006), null);


(lib.txt_sureColor_f10070 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AvlD9IAAgbIAJACQAKAAAEgFQAEgGABgIIgniKIAlAAIAVBfIABAAIARhfIAkAAIgiCAIgIAcQgFALgGAGQgFAGgJACQgIABgMAAgAPNDOQgLgHgFgKQgFgLgBgOIgBgaQAAgOACgNQACgNAFgJQAGgLALgFQALgGASAAQAPAAAKAFQAKAFAGAJQAGAKACAMQACANAAAQIAAAIIhHAAIABAXIAEALQABAEAEADQADACAFABQAJgBAEgGQAEgHACgNIAgAAQgBAZgMAMQgMANgaAAQgSAAgMgGgAPjBdQgEADgBAEIgEAJIgBAPIAlAAIgCgOQAAgGgCgEQgCgEgDgDQgEgCgFAAQgGAAgDACgADWDQQgKgEgGgKQgGgIgDgOQgCgPAAgRQAAgSACgOQADgNAHgKQAGgIAKgFQALgFAPAAQAQAAALAFQAKADAGAKQAHAJACAOQADAOAAASQAAARgDAPQgDANgHAJQgGAJgKAEQgLAFgPAAQgQAAgLgEgADnBfQgEADgCAGQgCAHgBAJIAAAnQABAJACAHQACAGAEADQAEAFAGAAQALgBAEgKQAEgMAAgaQAAgagEgMQgEgLgLAAQgGAAgEAEgAgmDQQgGgDgEgGQgEgFgCgHQgCgHAAgHQAAgKADgHQACgHAEgFQAEgFAHgDIAPgHIAUgEQAIgCADgFQADgCAAgIQAAgIgEgFQgDgEgJAAQgIAAgEAFQgEAFAAAIIAAAEIggAAIAAgEQAAgMAEgHQAEgIAGgGQAHgEAIgCQAJgDAKAAQAQAAAJADQAKADAFAGQAGAGACAHQACAIAAAJIABBZIADALIgiAAIgDgHIgBgIIgBAAQgGAMgHACQgIAEgNAAQgJAAgHgEgAAFCQIgHADQgLACgEAFQgFAFAAAKQAAAIADAGQADAFAIABIAHgCQADgBAEgDIAFgGQACgEAAgHIAAgagAmpDQQgHgEgGgKIAAAPIgiAAIAAi3IAjAAIAAA5IABAAQAFgHAHgFQAHgEAKAAQAWAAAKARQALARAAAnQAAAngLAQQgKARgWAAQgLAAgHgEgAmyBqQgDALAAAXQAAAWADAMQAEAMAMgBQALABADgMQAEgMAAgWQAAgXgEgLQgDgMgLAAQgMAAgEAMgApMDLQgJgJAAgVIAAhmIAkAAIAABfQAAALADAEQAEAFAIgBQATAAAAgXIAAhbIAjAAIAACKIgiAAIAAgRQgGALgJAEQgJAFgLAAQgSAAgJgJgArMDGQgNgOAAgZIAAgHIAlAAIAAARQABAFADAEQADADAFACQAFACAHAAQAIABAHgGQAHgFAAgMQAAgGgCgFQgBgEgEgEQgEgEgGgDIgQgGIgVgJQgJgEgGgIQgGgGgDgJQgDgIAAgMQAAgaAPgNQAPgOAbgBQAMAAALAEQAKADAIAFQAHAGAFAJQAEAKAAANIAAAFIgkAAQAAgNgEgHQgFgHgLAAQgGAAgEABQgEADgDADQgCACgBAFIgBAIQAAAHAEAGQADAGAMAFIAdANQAKAFAHAFQAGAEAFAGQAEAGABAHQACAGAAAJQAAAegRANQgRANgeAAQggAAgNgOgAtlDOQgLgHgFgKQgFgLgCgOIAAgaQAAgOABgNQACgNAGgJQAGgLALgFQAKgGASAAQAQAAAKAFQAJAFAGAJQAGAKACAMQACANAAAQIAAAIIhHAAIABAXIAEALQABAEAEADQADACAFABQAJgBAFgGQADgHACgNIAgAAQgBAZgMAMQgMANgZAAQgTAAgLgGgAtQBdQgEADgBAEIgEAJIgBAPIAlAAIgBgOQgBgGgCgEQgBgEgEgDQgDgCgGAAQgGAAgDACgAOLDQQgGgBgEgFQgDgEgBgHQgCgHAAgKIAAhPIgRAAIAAgYIARAAIAAgoIAkAAIAAAoIAUAAIAAAYIgUAAIAABLQAAAIACADQADADAHAAIAIAAIAAAZIgXAAIgRgBgABbDQQgGgBgEgFQgDgEgBgHQgCgHAAgKIAAhPIgSAAIAAgYIASAAIAAgoIAjAAIAAAoIAVAAIAAAYIgVAAIAABLQAAAIADADQACADAIAAIAIAAIAAAZIgXAAIgRgBgAQuDRIAAiKIAiAAIAAATIAAAAQAGgLAHgGQAIgGALAAIADAAIADAAIAAAiIgLAAIgJABQgFABgEAEQgDACgDAGQgCAEAAAHIAABTgAM9DRIAAhgQAAgKgEgEQgDgFgIAAQgUAAAAAYIAABbIgiAAIAAiKIAhAAIAAAQIABAAQAFgKAJgFQAJgFAMAAQARAAAJAJQAJAJAAAWIAABmgAK/DRIAAiKIAjAAIAACKgAJtDRIAAiKIAiAAIAAATIAAAAQAGgLAIgGQAHgGALAAIAEAAIADAAIAAAiIgLAAIgKABQgEABgEAEQgEACgCAGQgDAEAAAHIAABTgAHtDRIAAi3IBBAAQAOgBAKAFQAJAFAGAIQAGAHADALQACAJAAALQAAANgEALQgEALgIAGQgIAHgLAEQgKADgNAAIgUAAIAABJgAISBsIARAAQAKAAAHgHQAHgGAAgOQAAgOgGgHQgGgIgOABIgPAAgAF8DRIAAhgQAAgKgEgEQgDgFgIAAQgTAAAAAYIAABbIgjAAIAAiKIAhAAIAAAQIABAAQAFgKAJgFQAJgFAMAAQARAAAJAJQAJAJAAAWIAABmgACMDRIAAiKIAjAAIAACKgAhmDRIAAhhQAAgIgEgFQgEgFgHAAQgIAAgFAGQgFAGAAAMIAABbIgkAAIAAhhQAAgIgDgFQgDgFgHAAQgJAAgFAGQgFAGAAAMIAABbIgjAAIAAiKIAiAAIAAANQAHgIAIgFQAIgEAMAAQAMAAAJAGQAIAGADALIAAAAQAEgLAJgGQAJgGANAAQASAAAIALQAIALAAATIAABlgAklDRIAAiKIAkAAIAACKgAleDRIAAi3IAkAAIAAC3gAxyDRIAAi3IA9AAQAUAAALAFQAMAHAGALQAHANACAQQACARAAAUQAAAYgCARQgDATgHAMQgIALgLAFQgMAGgTAAgAxMC1IAQAAQAKAAAGgCQAGgEADgIQAEgIABgMIAAg7QgBgMgDgIQgEgHgGgEQgGgFgLABIgPAAgAK/A2IAAgfIAjAAIAAAfgACMA2IAAgfIAjAAIAAAfgAklA2IAAgfIAkAAIAAAfgAPkhFQgLgDgHgLQgHgLgCgQQgDgRAAgYIACgkQABgRAFgNQAGgOALgJQAMgHAUgBQAQAAALAGQALAEAGAKQAHALADARQACAQAAAYIgBAlQgBARgGANQgFAOgMAIQgLAHgUABQgRgBgKgFgAP1jdQgEAEgCAGQgCAIgBALIAABNQABALACAGQACAGAEADQAEACAGAAQAGAAAEgDQADgDADgHQACgHABgLIAAhOQgBgKgCgHQgDgGgDgCQgEgCgGAAQgHAAgDACgAL3hFQgLgDgGgLQgHgLgDgQQgCgRAAgYIABgkQABgRAGgNQAFgOAMgJQALgHAUgBQARAAALAGQALAEAGAKQAHALACARQADAQAAAYIgBAlQgCARgFANQgGAOgLAIQgMAHgUABQgQgBgLgFgAMJjdQgEAEgCAGQgDAIgBALIAABNQABALADAGQACAGAEADQADACAGAAQAGAAAEgDQAEgDADgHQACgHABgLIAAhOQgBgKgDgHQgCgGgEgCQgEgCgGAAQgGAAgDACgAKBhFQgLgDgGgLQgHgLgDgQQgCgRAAgYIABgkQABgRAGgNQAFgOAMgJQALgHAUgBQARAAALAGQAKAEAHAKQAHALACARQADAQAAAYIgCAlQgBARgFANQgGAOgLAIQgMAHgUABQgQgBgLgFgAKSjdQgDAEgDAGQgCAIgBALIAABNQABALACAGQADAGADADQAEACAGAAQAGAAAEgDQAEgDACgHQACgHABgLIAAhOQgBgKgCgHQgCgGgEgCQgEgCgGAAQgGAAgEACgAA3hEQgKgEgGgJQgGgJgDgOQgCgNAAgSQAAgSACgOQADgNAHgJQAGgJAKgFQALgFAPABQAQgBAKAFQAKAEAHAKQAGAJACANQADAOAAASQAAASgDANQgDAOgGAJQgGAIgLAEQgKAFgPABQgQAAgLgFgABIi0QgEADgCAHQgCAHAAAJIAAAmQAAAJACAHQACAGAEADQADAEAHAAQAKAAAFgLQAEgMAAgZQAAgagEgLQgFgMgKAAQgHAAgDAEgAh3hEQgKgEgGgJQgGgJgDgOQgCgNAAgSQAAgSACgOQADgNAHgJQAGgJAKgFQALgFAPABQAPgBALAFQAKAEAHAKQAGAJACANQADAOAAASQAAASgDANQgDAOgGAJQgHAIgKAEQgKAFgPABQgQAAgLgFgAhni0QgDADgCAHQgCAHgBAJIAAAmQABAJACAHQACAGADADQAEAEAHAAQAKAAAFgLQADgMAAgZQAAgagDgLQgFgMgKAAQgHAAgEAEgAj4hGQgMgIgHgLQgHgNgCgSQgBgRAAgVQAAgUABgSQACgRAHgMQAHgNAMgIQAMgGAVAAQATgBAMAHQALAGAFAKQAGAKACAMIABAVIglAAQAAgUgEgJQgFgJgNAAQgHAAgEADQgFAEgCAIQgDAIAAAOIgBAhIABAhQABANADAHQADAHAEACQAFADAGAAQAFAAAEgCQAEgCADgEQADgFACgKQACgIAAgPIAlAAQAAAPgDANQgCANgGAKQgGAKgMAFQgLAGgSABQgVgBgMgGgAlyhGQgLgHgFgKQgFgLgBgNIgBgZQAAgOACgNQACgNAFgKQAGgKALgGQALgFARAAQAQgBAKAFQAJAFAGAKQAGAIACANQACANAAAQIAAAIIhGAAIABAXIADAKQACAFADADQAEACAEAAQAJAAAEgHQAEgGACgNIAgAAQgBAYgMAMQgMAOgZAAQgTAAgLgHgAldi1QgDACgCAEIgDAJIgBAPIAkAAIgBgOQgBgGgCgEQgCgFgDgBQgDgDgGAAQgFAAgEADgApHhIQgJgKAAgUIAAhmIAjAAIAABfQAAALAEADQAEAFAIAAQASAAAAgXIAAhbIAjAAIAACJIghAAIAAgQIgBAAQgFALgJADQgJAFgMABQgRgBgJgIgArIhOQgOgNAAgZIAAgIIAlAAIABASQABAFADAEQACADAFACQAFACAHAAQAIAAAHgGQAHgFAAgMQAAgFgCgFQgBgFgEgEQgEgCgGgEIgPgFIgWgJQgJgGgGgGQgFgGgDgJQgDgIAAgMQAAgaAOgOQAQgNAaAAQAMAAALACQAKADAIAGQAHAGAEAKQAEAIAAANIAAAGIgjAAQAAgNgEgIQgFgGgLAAQgGAAgEACQgEABgDADIgDAHIgBAIQAAAIAEAGQADAGAMAFIAdAMQAKAEAHAFQAGAFAEAGQAEAGACAHQABAGAAAJQAAAdgQANQgRAOgeAAQgfAAgNgPgAtohGQgLgHgFgKQgFgLgBgNIgBgZQAAgOABgNQADgNAFgKQAGgKALgGQAKgFASAAQAQgBAJAFQAKAFAGAKQAGAIACANQABANAAAQIAAAIIhFAAIABAXIADAKQACAFADADQADACAFAAQAJAAAEgHQAEgGACgNIAgAAQgCAYgLAMQgMAOgZAAQgTAAgLgHgAtTi1QgDACgCAEIgDAJIgBAPIAkAAIgBgOQgBgGgCgEQgCgFgDgBQgEgDgFAAQgGAAgDADgANkhDIAHgiQAEgSAGgTQAHgTAKgSQAKgTANgSIhMAAIAAgfIBvAAIAAAcQgLAPgJASQgJASgGAUQgHATgEATQgFAUgCATgAIXhDIAAh/IgkAAIAAgZIAEAAQASAAAKgGQALgHADgQIAbAAIAAC1gAGEhDIAAi2IBmAAIAAAeIhCAAIAAArIA+AAIAAAeIg+AAIAABPgACXhDIAAiJIAhAAIAAASIABAAQAFgKAIgGQAIgFALAAIADAAIADAAIAAAhIgLAAIgJACQgFABgEACQgEAEgCAFQgCAEAAAHIAABSgAgXhDIAAi2IAjAAIAAC2gAnUhDIAAiJIAhAAIAAASIABAAQAFgKAIgGQAIgFALAAIADAAIADAAIAAAhIgLAAIgJACQgFABgEACQgEAEgCAFQgCAEAAAHIAABSgAuxhDIAAheQAAgLgDgFQgEgDgIAAQgTAAAAAWIAABbIgiAAIAAi2IAiAAIAAA7IABAAQAKgRAXAAQARAAAJAJQAJAJAAAUIAABmgAxNhDIAAiYIgoAAIAAgeIB1AAIAAAeIgoAAIAACYgAEGiRQgIgEgGgFQgHgGgDgJQgDgIAAgJQAAgJADgIQADgIAHgGQAGgGAIgDQAIgEAJAAQAJAAAIAEQAIADAGAGQAGAGAEAIQADAIAAAJQAAAJgDAIQgEAJgGAGQgGAFgIAEQgIADgJAAQgJAAgIgDgAEKjWQgFACgEAEQgFAEgCAGQgCAGAAAGQAAAHACAFQACAGAFAFQAEAEAFACQAGADAHAAQAHAAAFgDQAGgCAEgEQAEgFACgGQADgFAAgHQAAgGgDgGQgCgGgEgEQgEgEgGgCQgFgDgHAAQgHAAgGADgAEfiiIgLgTIgEAAIAAATIgLAAIAAgwIATAAQAJABAFAEQAEADAAAHQAAAHgDACQgDADgGACIAMATgAEQi9IAIAAIAGgBQACgCAAgEIgBgCQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAAAAAIgDgBIgKAAg");
	this.shape.setTransform(-6.225,-122.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_sureColor_f10070, new cjs.Rectangle(-120.4,-147.4,228.4,50.7), null);


(lib.txt_purposeBuilt = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("Ag7B5IAAgkIANACQANAAAFgHQAGgGABgMIg0i2IAxAAIAbB+IAAAAIAYh+IAvAAIgsCpQgGAYgGAOQgGANgHAJQgHAHgKACQgLADgRAAg");
	this.shape.setTransform(132.925,64.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgDB0QgIgCgFgFQgFgGgCgJQgBgJAAgOIAAhoIgYAAIAAggIAYAAIAAg0IAtAAIAAA0IAcAAIAAAgIgcAAIAABiQABALADAFQADAEALAAIAFAAIAFgBIAAAhIgPABIgPAAQgOAAgIgCg");
	this.shape_1.setTransform(120.7,58.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_2.setTransform(111.775,58.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_3.setTransform(103.875,58.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_4.setTransform(95.975,58.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgIB2QgJgFgIgNIgBAAIAAATIgtAAIAAjxIAvAAIAABMIACAAQAGgLAKgFQAJgFANAAQAcAAAOAWQANAXAAAyQAAAzgNAWQgOAWgcAAQgOAAgKgFgAgTgQQgFAPAAAdQAAAeAFAPQAFAPAOAAQAQAAAEgPQAFgPAAgeQAAgdgFgPQgEgPgQAAQgOAAgFAPg");
	this.shape_5.setTransform(83.85,58.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AguBbQgJgEgFgIQgFgHgDgJQgCgKAAgJQAAgNADgJQACgJAGgHQAFgGAJgEQAJgFAMgDIAagHQALgDAEgFQADgEAAgKQAAgKgEgGQgGgGgKAAQgLAAgGAHQgFAGAAALIAAAFIgqAAIAAgFQAAgQAFgKQAFgLAJgHQAJgGALgDQAMgDANAAQAUAAANAEQANAEAHAIQAHAHADALQACAKAAAMIAABfIABAUIAFAQIgtAAIgDgKIgDgJIAAAAQgJAOgKAEQgKAFgRAAQgMAAgIgFgAAKAGIgKADQgNAEgGAHQgGAHAAAMQAAALAEAHQAEAIAJAAIAJgCQAFgBAFgEQAEgDADgGQACgFAAgIIAAgkg");
	this.shape_6.setTransform(67.1,61.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_7.setTransform(55.225,58.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_8.setTransform(47.325,58.375);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_9.setTransform(35.675,61.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_10.setTransform(23.125,61.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_11.setTransform(5.025,58.375);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgvBbQgIgEgFgIQgFgHgDgJQgCgKAAgJQAAgNADgJQADgJAFgHQAGgGAJgEQAIgFANgDIAZgHQAKgDAEgFQAFgEAAgKQAAgKgGgGQgFgGgLAAQgKAAgFAHQgGAGAAALIAAAFIgqAAIAAgFQAAgQAFgKQAFgLAIgHQAJgGAMgDQALgDAOAAQAUAAANAEQANAEAHAIQAIAHACALQACAKABAMIAABfIAAAUIAFAQIgtAAIgDgKIgCgJIgBAAQgIAOgLAEQgKAFgQAAQgNAAgJgFgAALAGIgKADQgOAEgGAHQgGAHAAAMQAAALAEAHQAEAIAKAAIAJgCQAEgBAFgEQAEgDADgGQACgFABgIIAAgkg");
	this.shape_12.setTransform(-7.1,61.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AAWBeIAAh9QABgPgGgFQgEgGgKAAQgZAAAAAeIAAB5IguAAIAAi2IAtAAIAAAVIABAAQAGgNAMgHQAMgGAOAAQAXAAANAMQAMANgBAbIAACHg");
	this.shape_13.setTransform(-23.4,61.125);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgDgTQgEgSAAgYQAAgWAEgSQADgSAJgMQAIgMAPgHQANgGATAAQAVAAAOAGQAOAGAJAMQAHAMAEASQADASAAAXQAAAYgDASQgEASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgMg6QgFAEgDAJQgCAJgBALIgBAZIABAaQABAMACAJQADAIAFAFQAEAFAIAAQAPAAAFgPQAFgPAAgjQAAghgFgPQgFgPgPAAQgIAAgEAFg");
	this.shape_14.setTransform(-39.8,61.3231);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_15.setTransform(-51.775,58.225);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgDB0QgIgCgFgFQgFgGgCgJQgBgJAAgOIAAhoIgYAAIAAggIAYAAIAAg0IAtAAIAAA0IAcAAIAAAgIgcAAIAABiQABALADAFQADAEAKAAIAGAAIAFgBIAAAhIgPABIgPAAQgOAAgIgCg");
	this.shape_16.setTransform(-60.55,58.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AhGB7IAAjxIAtAAIAAAUIABAAQAHgNAKgGQAIgFAOAAQAdAAAOAWQAOAXAAAzQAAAygOAWQgOAWgdAAQgNAAgIgFQgJgFgIgLIAAAAIAABMgAgThHQgEAPAAAeQAAAdAEAPQAEAPAQAAQAPAAAEgPQAFgPAAgdQAAgegFgPQgEgPgPAAQgQAAgEAPg");
	this.shape_17.setTransform(-73.7,64.075);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_18.setTransform(-89.975,61.325);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgeBbQgNgEgIgLQgJgLgEgTQgFgSAAgcQAAgbAGgTQAFgSAKgLQAKgLANgFQAOgEAPAAQAhAAAQATQARATAAAhIgtAAIgBgNIgDgMQgCgGgEgDQgEgDgHAAQgIAAgFAEQgFAEgDAHQgDAIgBAMIgBAbIABAdQABAMADAIQADAHAEAEQAFAEAHAAQAMAAAGgLQAFgKAAgWIAtAAQAAAkgQATQgRATglAAQgQAAgOgFg");
	this.shape_19.setTransform(-105.425,61.325);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AAbBbIgbg7IgaA7IgxAAIAxhcIgvhZIAxAAIAYA2IAZg2IAxAAIgwBZIAyBcg");
	this.shape_20.setTransform(-120.9,61.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_21.setTransform(-136.325,61.325);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_22.setTransform(105.525,23.975);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgDgTQgEgSAAgYQAAgWAEgSQAEgSAIgMQAIgMAPgHQANgGATAAQAVAAAOAGQAOAGAJAMQAHAMADASQAEASAAAXQAAAYgEASQgDASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgMg6QgFAEgDAJQgDAJAAALIgBAZIABAaQAAAMADAJQADAIAFAFQAEAFAIAAQAPAAAFgPQAFgPAAgjQAAghgFgPQgFgPgPAAQgIAAgEAFg");
	this.shape_23.setTransform(91.25,24.1731);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgYB8IAAiWIgYAAIAAggIAYAAIAAgVQAAgMADgJQADgIAHgFQAGgFAIgDQAKgCALAAIAZABIAAAiIgFgBIgEAAQgKAAgEAEQgEADgBAIIAAAQIAcAAIAAAgIgcAAIAACWg");
	this.shape_24.setTransform(78.4,20.975);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgDB0QgJgBgEgHQgFgFgCgJQgBgJAAgOIAAhoIgYAAIAAggIAYAAIAAg0IAtAAIAAA0IAcAAIAAAgIgcAAIAABiQAAALAEAEQADAFAKAAIAGAAIAFgBIAAAhIgPAAIgQABQgNAAgIgCg");
	this.shape_25.setTransform(60.7,21.65);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_26.setTransform(51.775,21.225);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_27.setTransform(43.875,21.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("Ag4BSQgNgMAAgcIAAiHIAwAAIAAB9QAAAPAEAFQAFAHALgBQAYAAAAgeIAAh5IAvAAIAAC3IgtAAIAAgWIgBAAQgIAOgLAFQgLAHgPAAQgXAAgMgMg");
	this.shape_28.setTransform(31.55,24.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("AgIB2QgJgFgIgNIgBAAIAAATIgtAAIAAjxIAvAAIAABMIACAAQAGgLAKgFQAJgFANAAQAcAAAOAWQANAXAAAyQAAAzgNAWQgOAWgcAAQgOAAgKgFgAgTgQQgFAPAAAdQAAAeAFAPQAFAPAOAAQAQAAAEgPQAFgPAAgeQAAgdgFgPQgEgPgQAAQgOAAgFAPg");
	this.shape_29.setTransform(15,21.425);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AgvAUIAAgnIBfAAIAAAng");
	this.shape_30.setTransform(0.3,23.525);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_31.setTransform(-13.575,24.175);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#353535").s().p("AggBcQgNgEgIgIQgHgHgEgLQgDgKAAgOIAAgGIArAAIAAAGQAAAMAGAHQAGAIAMAAQAKAAAGgGQAHgFAAgLQAAgJgFgFQgGgEgHgDIgfgMQgTgHgLgLQgJgMgBgUQAAgLAFgKQADgKAIgIQAJgHAMgFQANgEARAAQAgAAAPAOQAQANAAAZIAAAIIgrAAQAAgPgEgGQgFgHgLAAQgIAAgHAFQgHAFAAAKQABAHAEAFQAEAFAMAEIAbAKQAWAHAJALQAKAMgBAVQAAAPgEAKQgGALgJAHQgJAHgMADQgMAEgPAAQgTAAgNgEg");
	this.shape_32.setTransform(-28.7,24.175);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgEgTQgDgSAAgYQAAgWAEgSQAEgSAIgMQAJgMANgHQAOgGATAAQAVAAAOAGQAOAGAIAMQAIAMAEASQADASAAAXQAAAYgDASQgEASgJAMQgJAMgNAGQgOAGgUAAQgUAAgOgGgAgNg6QgFAEgCAJQgDAJgBALIAAAZIAAAaQABAMADAJQACAIAFAFQAGAFAHAAQAPAAAFgPQAFgPAAgjQAAghgFgPQgFgPgPAAQgHAAgGAFg");
	this.shape_33.setTransform(-44.15,24.1731);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#353535").s().p("AhHB7IAAjxIAtAAIAAAUIABAAQAIgNAJgGQAKgFAOAAQAdAAANAWQAOAXAAAzQAAAygOAWQgNAWgdAAQgOAAgIgFQgJgFgIgLIgBAAIAABMgAgThHQgEAPgBAeQABAdAEAPQAFAPAOAAQAPAAAFgPQAFgPAAgdQAAgegFgPQgFgPgPAAQgOAAgFAPg");
	this.shape_34.setTransform(-60.35,26.925);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_35.setTransform(-73.725,23.975);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#353535").s().p("Ag5BSQgLgMgBgcIAAiHIAvAAIAAB9QABAPAFAFQAEAHALgBQAXAAAAgeIAAh5IAwAAIAAC3IgtAAIAAgWIgCAAQgGAOgNAFQgLAHgPAAQgWAAgNgMg");
	this.shape_36.setTransform(-88.35,24.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#353535").s().p("AhLB5IAAjxIBUAAQATAAANAGQANAGAHAKQAIAKAEAOQADANAAANQAAATgGAOQgFAOgKAIQgKAIgPAFQgOAEgQAAIgaAAIAABhgAgagLIAVAAQAOAAAJgJQAJgIAAgTQAAgSgIgKQgHgJgSAAIgUAAg");
	this.shape_37.setTransform(-104.875,21.225);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_purposeBuilt, new cjs.Rectangle(-186.5,-1.3,369,81.3), null);


(lib.txt_industrialLevel = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AggBcQgOgEgHgIQgIgHgCgLQgDgKAAgOIAAgGIApAAIAAAGQAAAMAHAHQAGAIAMAAQAKAAAHgGQAGgFAAgLQAAgJgGgFQgFgEgGgDIgggMQgUgHgJgLQgLgMABgUQAAgLADgKQAEgKAJgIQAHgHANgFQANgEARAAQAgAAAPAOQAPANAAAZIAAAIIgpAAQAAgPgFgGQgFgHgMAAQgHAAgGAFQgIAFABAKQgBAHAFAFQAEAFAMAEIAbAKQAWAHAKALQAIAMABAVQgBAPgFAKQgFALgIAHQgJAHgNADQgNAEgOAAQgTAAgNgEg");
	this.shape.setTransform(115.35,49.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("Ag5BlQgOgWAAgzQAAgyAOgXQAOgWAdAAQANAAAIAFQAJAFAHALIABAAIAAhMIAvAAIAADxIgtAAIAAgTIgBAAQgHANgKAFQgIAFgOAAQgdAAgOgWgAgTgQQgFAPAAAdQAAAeAFAPQAEAPAPAAQAQAAAEgPQAEgPAAgeQAAgdgEgPQgEgPgQAAQgPAAgEAPg");
	this.shape_1.setTransform(99.35,46.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_2.setTransform(83.475,49.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_3.setTransform(68.025,49.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AhHB7IAAjxIAtAAIAAAUIACAAQAHgNAJgGQAJgFAOAAQAdAAAOAWQANAXAAAzQAAAygNAWQgOAWgdAAQgMAAgJgFQgKgFgGgLIgBAAIAABMgAgThHQgFAPABAeQgBAdAFAPQAEAPAPAAQAQAAAEgPQAFgPAAgdQAAgegFgPQgEgPgQAAQgPAAgEAPg");
	this.shape_4.setTransform(52.1,52.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AggBcQgOgEgHgIQgIgHgDgLQgCgKAAgOIAAgGIApAAIAAAGQAAAMAHAHQAGAIAMAAQAKAAAGgGQAHgFAAgLQAAgJgGgFQgFgEgGgDIgggMQgTgHgKgLQgLgMABgUQAAgLADgKQAEgKAJgIQAHgHANgFQANgEARAAQAgAAAPAOQAPANAAAZIAAAIIgpAAQAAgPgFgGQgFgHgMAAQgHAAgGAFQgIAFABAKQgBAHAFAFQAEAFAMAEIAbAKQAWAHAKALQAIAMABAVQgBAPgFAKQgFALgIAHQgJAHgNADQgNAEgOAAQgTAAgNgEg");
	this.shape_5.setTransform(36.15,49.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAWBeIAAh9QAAgPgEgFQgFgGgLAAQgYAAAAAeIAAB5IgvAAIAAi2IAtAAIAAAVIABAAQAIgNALgHQALgGAPAAQAXAAAMAMQANANAAAbIAACHg");
	this.shape_6.setTransform(12.45,49.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgEgTQgDgSAAgYQAAgWAEgSQADgSAJgMQAJgMAOgHQANgGATAAQAVAAAOAGQAOAGAIAMQAJAMACASQAEASAAAXQAAAYgEASQgDASgJAMQgIAMgOAGQgOAGgUAAQgUAAgOgGgAgNg6QgEAEgDAJQgCAJgBALIgBAZIABAaQABAMACAJQADAIAEAFQAFAFAIAAQAPAAAFgPQAFgPAAgjQAAghgFgPQgFgPgPAAQgIAAgFAFg");
	this.shape_7.setTransform(-3.95,49.5231);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_8.setTransform(-15.925,46.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgDB0QgJgCgEgFQgFgGgCgJQgBgJAAgOIAAhoIgYAAIAAggIAYAAIAAg0IAtAAIAAA0IAcAAIAAAgIgcAAIAABiQAAALAEAFQADAEAKAAIAGAAIAFgBIAAAhIgPABIgQAAQgNAAgIgCg");
	this.shape_9.setTransform(-24.7,47);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AgeBbQgNgEgIgLQgJgLgEgTQgFgSAAgcQAAgbAGgTQAFgSAKgLQAKgLANgFQAOgEAPAAQAhAAAQATQARATAAAhIgtAAIgBgNIgDgMQgCgGgEgDQgEgDgHAAQgIAAgFAEQgFAEgDAHQgDAIgBAMIgBAbIABAdQABAMADAIQADAHAEAEQAFAEAHAAQAMAAAGgLQAFgKAAgWIAtAAQAAAkgQATQgRATglAAQgQAAgOgFg");
	this.shape_10.setTransform(-37.375,49.525);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("Ag4BRQgNgMAAgbIAAiGIAwAAIAAB9QAAAOAEAFQAFAHALAAQAYgBAAgeIAAh4IAvAAIAAC1IgtAAIAAgVIgBAAQgIAOgLAGQgLAFgPABQgXAAgMgNg");
	this.shape_11.setTransform(-53.5,49.75);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("Ag5BlQgNgWAAgzQAAgyANgXQAOgWAcAAQANAAAJAFQAKAFAGALIABAAIAAhMIAwAAIAADxIgtAAIAAgTIgBAAQgIANgJAFQgKAFgOAAQgcAAgOgWgAgTgQQgFAPAAAdQAAAeAFAPQAEAPAPAAQAQAAAEgPQAFgPgBgeQABgdgFgPQgEgPgQAAQgPAAgEAPg");
	this.shape_12.setTransform(-70.45,46.775);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AgiBaQgOgFgIgNQgIgLgEgTQgDgSAAgYQAAgWAEgSQADgSAJgMQAJgMANgHQAOgGATAAQAVAAAOAGQAOAGAIAMQAJAMACASQAEASAAAXQAAAYgEASQgDASgJAMQgIAMgOAGQgOAGgUAAQgUAAgOgGgAgNg6QgEAEgDAJQgCAJgCALIAAAZIAAAaQACAMACAJQADAIAEAFQAGAFAHAAQAOAAAGgPQAFgPAAgjQAAghgFgPQgGgPgOAAQgHAAgGAFg");
	this.shape_13.setTransform(-86.65,49.5231);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_14.setTransform(-99.475,49.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AhHB7IAAjxIAtAAIAAAUIABAAQAIgNAJgGQAKgFAOAAQAdAAANAWQAOAXAAAzQAAAygOAWQgNAWgdAAQgOAAgIgFQgJgFgIgLIgBAAIAABMgAgThHQgEAPgBAeQABAdAEAPQAFAPAOAAQAPAAAFgPQAFgPAAgdQAAgegFgPQgFgPgPAAQgOAAgFAPg");
	this.shape_15.setTransform(-113.9,52.275);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_16.setTransform(96.225,9.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_17.setTransform(84.575,12.375);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgZBbIgwi2IAxAAIAaCDIAAAAIAZiDIAvAAIguC2g");
	this.shape_18.setTransform(69.425,12.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgmBXQgOgJgHgNQgHgOgBgSIgCghQAAgTADgRQACgRAIgNQAHgNAPgIQAOgIAXAAQAUAAANAHQANAGAIAMQAHANADARQADARAAAVIAAAJIhcAAIAAAPIABAQIAEANQADAGAEAEQAFAEAFAAQAMAAAGgJQAFgIACgSIAqAAQgBAggQARQgQARghAAQgZAAgOgJgAgKg8QgEAEgDAFIgEALIgBANIAAAIIAvAAIgBgTQgBgIgDgGQgCgFgFgDQgFgDgHAAQgGAAgFADg");
	this.shape_19.setTransform(54.325,12.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_20.setTransform(42.625,9.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AgvAUIAAgnIBfAAIAAAng");
	this.shape_21.setTransform(32.55,11.725);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#353535").s().p("AgWB5IAAjxIAtAAIAADxg");
	this.shape_22.setTransform(22.425,9.425);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#353535").s().p("AguBbQgJgEgFgIQgFgHgDgJQgCgKAAgJQAAgNADgJQACgJAGgHQAFgGAKgEQAIgFAMgDIAagHQAKgDAFgFQADgEAAgKQAAgKgEgGQgGgGgKAAQgLAAgFAHQgGAGAAALIAAAFIgqAAIAAgFQAAgQAFgKQAFgLAJgHQAIgGAMgDQALgDAOAAQAUAAANAEQANAEAHAIQAIAHACALQADAKgBAMIAABfIABAUIAFAQIgtAAIgDgKIgDgJIAAAAQgJAOgKAEQgKAFgQAAQgNAAgIgFgAAKAGIgKADQgNAEgGAHQgGAHAAAMQAAALAEAHQAEAIAJAAIAJgCQAFgBAFgEQAEgDADgGQADgFgBgIIAAgkg");
	this.shape_23.setTransform(10.3,12.375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#353535").s().p("AgWB7IAAi2IAtAAIAAC2gAgWhSIAAgoIAtAAIAAAog");
	this.shape_24.setTransform(-1.575,9.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#353535").s().p("AgvBeIAAi2IAtAAIAAAYIABAAQAGgNAKgIQAKgIAPAAIAEAAIAEABIAAAtIgHgBIgHAAIgNACQgGABgFAEQgFAEgDAGQgCAHAAAJIAABtg");
	this.shape_25.setTransform(-10.325,12.175);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#353535").s().p("AgDB0QgIgCgFgGQgFgFgCgJQgBgJAAgOIAAhoIgYAAIAAggIAYAAIAAg0IAtAAIAAA0IAcAAIAAAgIgcAAIAABiQABALADAFQADAEAKAAIAGAAIAFgBIAAAhIgPABIgPAAQgOAAgIgCg");
	this.shape_26.setTransform(-21.4,9.85);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#353535").s().p("AggBcQgNgEgIgIQgHgHgEgLQgDgKAAgOIAAgGIArAAIAAAGQgBAMAHAHQAGAIAMAAQAKAAAGgGQAHgFAAgLQAAgJgGgFQgEgEgIgDIgfgMQgTgHgLgLQgKgMAAgUQAAgLAFgKQADgKAJgIQAHgHANgFQANgEARAAQAgAAAPAOQAPANABAZIAAAIIgqAAQgBgPgEgGQgFgHgLAAQgIAAgGAFQgIAFAAAKQABAHAEAFQAEAFAMAEIAbAKQAWAHAJALQAKAMgBAVQABAPgGAKQgEALgJAHQgKAHgMADQgMAEgPAAQgTAAgNgEg");
	this.shape_27.setTransform(-33.75,12.375);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#353535").s().p("Ag4BSQgMgMgBgcIAAiHIAvAAIAAB9QABAPAEAFQAFAHALgBQAYAAgBgeIAAh5IAwAAIAAC2IgtAAIAAgVIgBAAQgIAOgMAFQgKAHgQAAQgWgBgMgLg");
	this.shape_28.setTransform(-49.55,12.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#353535").s().p("Ag5BlQgNgWAAgzQAAgyANgXQAOgWAdAAQAMAAAJAFQAKAFAGALIABAAIAAhMIAwAAIAADxIgtAAIAAgTIgCAAQgHANgJAFQgJAFgOAAQgdAAgOgWgAgTgQQgFAPAAAdQAAAeAFAPQAEAPAPAAQAQAAAEgPQAFgPgBgeQABgdgFgPQgEgPgQAAQgPAAgEAPg");
	this.shape_29.setTransform(-66.5,9.625);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#353535").s().p("AAWBeIAAh9QAAgPgEgFQgFgGgLAAQgYAAAAAeIAAB5IgvAAIAAi2IAtAAIAAAVIABAAQAIgNALgHQALgGAPAAQAXAAAMAMQAMANAAAbIAACHg");
	this.shape_30.setTransform(-83.05,12.175);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#353535").s().p("AgYB5IAAjxIAwAAIAADxg");
	this.shape_31.setTransform(-95.65,9.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_industrialLevel, new cjs.Rectangle(-184.5,-13.1,369,81.3), null);


(lib.txt_humor = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#353535").s().p("AgVBQIAJgUIAHgSQACgKABgKIABgWIgBgUIgDgUIgHgTIgJgVIATAAQAMAWAGAUQAGAUAAASQAAAUgGAUQgGAUgMAUg");
	this.shape.setTransform(70.725,-65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#353535").s().p("AgLAOIAAgbIAXAAIAAAbg");
	this.shape_1.setTransform(66.675,-61.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#353535").s().p("AgYAyIAAhgIAXAAIAAANIABAAQACgHAGgEQAFgFAIAAIACABIACAAIAAAYIgDgBIgEAAIgHABQgDABgDACIgEAFQgBAEAAAFIAAA5g");
	this.shape_2.setTransform(62.225,-65.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#353535").s().p("AgSAwQgHgDgEgGQgFgHgBgJQgCgKAAgNQAAgLACgKQACgJAEgHQAFgGAHgDQAHgEAKAAQALAAAHADQAIADAEAHQAFAHABAJQACAKAAALQAAANgCAJQgCAKgEAGQgFAHgHADQgHADgLAAQgKAAgIgDgAgGgeQgDACgBAFIgCALIAAAMIAAAOIACALQABAEADADQACACAEAAQAIAAACgIQADgHAAgTQAAgRgDgIQgCgIgIAAQgEAAgCADg");
	this.shape_3.setTransform(54.875,-65.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#353535").s().p("AAjAyIAAhDQAAgGgCgDQgCgDgGAAQgGAAgDADQgEAEAAAJIAAA/IgXAAIAAhDQAAgGgDgDQgCgDgFAAQgGAAgEADQgDAEAAAJIAAA/IgZAAIAAhgIAYAAIAAAKIAAAAQAFgHAGgDQAGgDAIAAQAIAAAFAEQAGAEACAIIAAAAQADgIAHgEQAGgEAJAAQAMAAAGAIQAGAHAAAOIAABGg");
	this.shape_4.setTransform(44.075,-65.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#353535").s().p("AgeAsQgFgHAAgPIAAhHIAYAAIAABDQAAAHADADQACADAGAAQAMAAAAgQIAAhAIAZAAIAABgIgYAAIAAgLIgBAAQgEAIgGACQgFADgIAAQgMAAgHgFg");
	this.shape_5.setTransform(33.05,-64.95);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#353535").s().p("AAMBAIAAhCQAAgHgDgDQgCgDgGAAQgMAAAAAPIAABAIgZAAIAAh/IAZAAIAAApIABAAQAGgMAQAAQAMAAAGAGQAHAHgBAOIAABHg");
	this.shape_6.setTransform(24.35,-66.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#353535").s().p("AgYAyIAAhgIAXAAIAAANIABAAQACgHAGgEQAFgFAIAAIACABIACAAIAAAYIgDgBIgEAAIgHABQgDABgDACIgEAFQgBAEAAAFIAAA5g");
	this.shape_7.setTransform(13.575,-65.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#353535").s().p("AgTAuQgIgEgDgIQgEgHgBgJIgBgSQAAgJABgJQACgJAEgHQAEgHAHgEQAIgFALAAQAMAAAGAEQAIADADAHQAEAGACAJIABAVIAAAEIgwAAIAAAIIABAIIACAHQABAEACABQADACACAAQAGAAADgEQADgFACgJIAWAAQgBARgJAJQgIAJgSAAQgMAAgHgFgAgFgfQgCACgBADIgCAGIgBAHIAAADIAZAAIgCgJIgBgIQgBgDgDgBQgDgCgDAAQgDAAgDACg");
	this.shape_8.setTransform(6.35,-65.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#353535").s().p("AgTAuQgIgEgDgIQgEgHgBgJIgBgSQAAgJABgJQACgJAEgHQAEgHAHgEQAIgFALAAQAMAAAGAEQAHADAFAHQAEAGABAJIABAVIAAAEIgwAAIAAAIIABAIIACAHQABAEADABQACACACAAQAGAAADgEQADgFACgJIAWAAQgBARgJAJQgHAJgTAAQgMAAgHgFgAgEgfQgDACgBADIgCAGIgBAHIAAADIAZAAIgBgJIgCgIQgBgDgDgBQgDgCgDAAQgDAAgCACg");
	this.shape_9.setTransform(-1.65,-65.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#353535").s().p("AAMAyIAAhCQAAgIgDgDQgCgCgGAAQgMAAAAAQIAAA/IgZAAIAAhgIAYAAIAAALIAAAAQAFgHAFgDQAGgEAIAAQAMAAAHAHQAFAGAAAPIAABHg");
	this.shape_10.setTransform(-10,-65.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#353535").s().p("AgMBBIAAhgIAYAAIAABggAgMgqIAAgWIAYAAIAAAWg");
	this.shape_11.setTransform(-16.35,-66.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#353535").s().p("AgbA7QgIgHAAgMIAYAAQAAAFADADIAEACIAEAAQAHAAADgFQADgEAAgIIAAgMIAAAAQgEAFgFADQgFADgGAAQgOAAgIgLQgHgLAAgZIABgSQABgJADgGQADgIAGgEQAGgFAKAAQAFAAAFADQAFADAEAIIAAAAIAAgMIAYAAIAABcQAAASgJAKQgJAJgVAAQgQAAgJgHgAgFgsQgDACgBAEIgCAKIgBARIABAJIACAHQABAEACADQADACADAAQAEAAACgCIAEgHQACgDABgEIAAgLQAAgSgDgIQgCgHgIAAQgDABgCABg");
	this.shape_12.setTransform(-22.825,-63.55);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#353535").s().p("AAMAyIAAhCQAAgIgCgDQgDgCgGAAQgMAAAAAQIAAA/IgYAAIAAhgIAXAAIAAALIAAAAQAFgHAFgDQAGgEAIAAQAMAAAGAHQAGAGABAPIAABHg");
	this.shape_13.setTransform(-31.4,-65.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#353535").s().p("AgTAuQgIgEgEgIQgDgHgBgJIgBgSQAAgJACgJQABgJAEgHQAEgHAIgEQAHgFALAAQALAAAHAEQAIADADAHQAFAGABAJIABAVIAAAEIgwAAIAAAIIABAIIACAHQABAEACABQADACACAAQAHAAADgEQACgFABgJIAXAAQgBARgIAJQgJAJgRAAQgNAAgHgFgAgFgfQgCACgBADIgCAGIgBAHIAAADIAYAAIgBgJIgBgIQgCgDgCgBQgCgCgEAAQgDAAgDACg");
	this.shape_14.setTransform(-39.75,-65.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#353535").s().p("AgLAQQAFgBACgEQACgEAAgFIAAgCIgJAAIAAgcIAXAAIAAAYIgBALQgBAGgDAFQgDAEgEADQgEADgHAAg");
	this.shape_15.setTransform(-49.725,-60.15);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#353535").s().p("AgeBAIAAgTIAGABQAGAAAEgDQACgEABgGIgbhgIAaAAIANBCIAAAAIANhCIAZAAIgYBaIgGATQgDAHgDAEQgEAFgGABIgNABg");
	this.shape_16.setTransform(-55.55,-63.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#353535").s().p("AgYAyIAAhgIAXAAIAAANIABAAQACgHAGgEQAFgFAIAAIACABIACAAIAAAYIgDgBIgEAAIgHABQgDABgDACIgEAFQgBAEAAAFIAAA5g");
	this.shape_17.setTransform(-61.825,-65.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#353535").s().p("AgYAyIAAhgIAXAAIAAANIABAAQACgHAGgEQAFgFAIAAIACABIACAAIAAAYIgDgBIgEAAIgHABQgDABgDACIgEAFQgBAEAAAFIAAA5g");
	this.shape_18.setTransform(-67.475,-65.175);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#353535").s().p("AgSAwQgHgDgEgGQgFgHgBgJQgCgKAAgNQAAgLACgKQACgJAEgHQAFgGAHgDQAHgEAKAAQALAAAHADQAIADAEAHQAFAHABAJQACAKAAALQAAANgCAJQgCAKgEAGQgFAHgHADQgHADgLAAQgKAAgIgDgAgGgeQgDACgBAFIgCALIAAAMIAAAOIACALQABAEADADQACACAEAAQAIAAACgIQADgHAAgTQAAgRgDgIQgCgIgIAAQgEAAgCADg");
	this.shape_19.setTransform(-74.825,-65.075);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#353535").s().p("AggA5QgKgJAAgTIAAgEIAaAAIAAADIABAIIADAHQABACAEABQADACAEAAQAGAAAFgEQAFgEAAgIIgBgHIgEgGQgDgDgEgBIgKgFQgJgDgGgDQgHgEgEgDQgEgFgCgGQgCgGAAgIQAAgTALgJQAKgKATABQAHAAAIACQAHABAFAEQAGAFADAHQADAGAAAJIAAAEIgZAAQAAgJgEgGQgDgEgHAAQgEAAgDABIgEADIgCAFIgBAFQAAAHACADQADAFAIADIATAIQAIAEAEACIAIAIQADAEABAFIABAKQAAAVgMAJQgMAJgUAAQgWAAgJgJg");
	this.shape_20.setTransform(-83.475,-66.65);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#353535").s().p("AADBQQgNgUgFgUQgGgUAAgUQAAgSAGgUQAFgUANgWIATAAQgGALgDAKIgHATQgCAJgBALIgBAUIABAWQABAKACAKIAHASQADAKAGAKg");
	this.shape_21.setTransform(-90.025,-65);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_humor, new cjs.Rectangle(-194.3,-79.5,369,25.299999999999997), null);


(lib.printer_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","#FFFFFF"],[0.216,0.604,1],37.4,0,-37.2,0).s().p("Al0HgIAAu/ILqAAIAAO/g");
	this.shape.setTransform(-380.35,113.725);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","#FFFFFF","#FFFFFF"],[0,0.463,1],-97.5,0,97.6,0).s().p("AvPHgIAAu/IefAAIAAO/g");
	this.shape_1.setTransform(390.575,116.275);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.projector_image();
	this.instance.setTransform(-393.95,-153.15,1.2254,1.2254);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.printer_mc, new cjs.Rectangle(-417.7,-153.1,905.9,317.4), null);


(lib.Epson_Logo_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Epson_Logo();
	this.instance.setTransform(-87.5,-36.15,0.5726,0.5726);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Epson_Logo_1, new cjs.Rectangle(-87.5,-36.1,88.2,29.200000000000003), null);


(lib.ctaBtn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape.setTransform(61.025,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_1.setTransform(47.475,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag1A1QgWgVAAggQAAgeAWgXQAWgVAfgBQAfABAWAVQAXAXAAAeQAAAggXAVQgWAXgfAAQgfAAgWgXgAghghQgOAOAAATQAAAUAOAOQAOAPATAAQAUAAAOgPQAOgOAAgUQAAgTgOgOQgOgPgUAAQgTAAgOAPg");
	this.shape_2.setTransform(31.275,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBBMQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAIglhSIgBAAIgMBOQAAADgEABIgSAAQgFgBABgEIAZiNQAAAAAAgBQABAAAAgBQABAAAAAAQABgBAAAAIAEAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAIAuBiIAAAAIAuhiQABAAAAAAQAAgBABAAQAAAAABAAQAAgBABAAIADAAQABAAABABQABAAAAAAQABABAAAAQAAABAAAAIAZCNQABAEgFABIgTAAQgDgBgBgDIgMhOIgBAAIglBSQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(13.1508,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA3BMQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIhUheIgBAAIAABZQAAAEgEABIgTAAQgEgBAAgEIAAiMQAAgDAEgBIADAAQABABAAAAQAAAAABAAQAAAAABAAQAAABABAAIBUBaIAAAAIAAhVQAAgFAFAAIATAAQAEAAAAAFIAACMQAAADgEABg");
	this.shape_4.setTransform(-10,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAbBKQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAAAgBIgbg3IgYAAIAAA1QAAAEgEABIgTAAQgEgBAAgEIAAiJQAAgFAEAAIA7AAQATABANANQAOANAAASQAAAPgJALQgIALgOAFIAdA2QAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAgAgagFIAhAAQAIAAAGgHQAHgGAAgJQAAgIgHgGQgGgHgIAAIghAAg");
	this.shape_5.setTransform(-25.075,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAwBLQgEgBgCgEIgLgWIg+AAIgKAWQgBAEgFABIgSAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIBBiNQABAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIACAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAIBACNQABAAAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAAVAYIgVgtIAAAAIgUAtIApAAg");
	this.shape_6.setTransform(-39.85,0.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqBKQgEgBAAgEIAAiJQAAgFAEAAIBVAAQAEAAAAAFIAAARQAAADgEAAIg+AAIAAAjIAzAAQAEAAAAAEIAAAQQAAAFgEAAIgzAAIAAAlIA+AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_7.setTransform(-52.925,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBKQgEgBAAgEIAAiJQAAgFAEAAIATAAQAEAAAAAFIAAB1IA0AAQAEAAAAADIAAARQAAAEgEABg");
	this.shape_8.setTransform(-64.475,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#06539E").s().p("ArwECQg8AAAAg8IAAmLQAAg8A8AAIXhAAQA8AAAAA8IAAGLQAAA8g8AAg");
	this.shape_9.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_9).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.ctaBtn, new cjs.Rectangle(-81.2,-25.7,162.5,51.5), null);


(lib.shield_mc = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon();
	this.instance.setTransform(-54,-63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.shield_mc, new cjs.Rectangle(-54,-63,108,126), null);


(lib.gauge_needle = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#06539E").s().p("AhYBiIgCgCIgDgDQgmgmAAg3QAAg2AmgnQAngmA2AAQA3AAAmAmIADADIACACQAiAmAAAyQAAA3gnAmQgmAng3AAQgyAAgmgig");
	this.shape.setTransform(-1.125,0.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_1.setTransform(33.9503,-32.507);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(6).p("AkNFzIKfryIgDgKQgJgDgBABQgBACsMKWQgKALgCASQgFAlAlAnQAeAfAmgMQAbgIAIgOg");
	this.shape_2.setTransform(34.1373,-32.507);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#06539E").s().p("AlzF2QgkgnAEglQADgSAJgLIMOqYQABgBAJADIADAKIqgLyQgIAOgbAIQgKADgKAAQgaAAgWgWg");
	this.shape_3.setTransform(33.9503,-32.507);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.gauge_needle, new cjs.Rectangle(-16.3,-75.1,94.1,89.3), null);


(lib.checkMark_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(14).p("AgwgMQAgARAdAX");
	this.shape.setTransform(30.8836,-45.505);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(14).p("AiSgqQCCAUBnBQ");
	this.shape_1.setTransform(23.5006,-48.4675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(14).p("Ai6grQAZgCAbAAQC2AACLBq");
	this.shape_2.setTransform(13.5125,-48.805);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(14).p("AkvAjQB+hQCfAAQC2AACMBq");
	this.shape_3.setTransform(1.8625,-48.805);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(14).p("AmdDIQAnhtBYhYQCdibDcAAQC3AACMBr");
	this.shape_4.setTransform(-9.1375,-38.1235);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(14).p("AmLFqQghhYAAhlQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_5.setTransform(-10.6375,-17.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(14).p("AhnICQhcgnhMhMQididAAjdQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_6.setTransform(-10.6375,-2.0625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(14).p("AG9GQQiWCHjNAAQjdAAicidQidicAAjeQAAjdCdicQCcidDdAAQC3AACLBs");
	this.shape_7.setTransform(-9,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(14).p("AIWgeQABAPAAAPQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_8.setTransform(-0.025,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#06539E").ss(14).p("AHjjoQA0BqAAB+QAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACMBs");
	this.shape_9.setTransform(-0.025,0);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#06539E").ss(14).p("AGdlTQB6CRAADCQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQC3AACLBs");
	this.shape_10.setTransform(-0.025,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#06539E").ss(14).p("AIXAAQAADeidCcQidCdjdAAQjcAAididQidicAAjeQAAjdCdicQCdidDcAAQDdAACdCdQCdCcAADdg");
	this.shape_11.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).wait(133));

	// Layer_3
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#06539E").ss(14,2,1).p("AgJgKIATAV");
	this.shape_12.setTransform(-19.3125,1.375);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#06539E").ss(14,2,1).p("AgkgmIBJBN");
	this.shape_13.setTransform(-16.6125,4.1875);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#06539E").ss(14).p("AAZgYIgyAx");
	this.shape_14.setTransform(-4.4,11.7375);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#06539E").ss(14,1,1).p("AAXAYIgtgv");
	this.shape_15.setTransform(-9.275,11.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#06539E").ss(14,2,1).p("AgrgtIBXBb");
	this.shape_16.setTransform(-15.975,4.85);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#06539E").ss(14).p("ABEhCIiHCF");
	this.shape_17.setTransform(-0.125,7.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#06539E").ss(14).p("ACAh9Ij/D7");
	this.shape_18.setTransform(5.8875,1.6125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f().s("#06539E").ss(14).p("AChieIlBE9");
	this.shape_19.setTransform(9.175,-1.625);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("#06539E").ss(14).p("ACtioIlZFR");
	this.shape_20.setTransform(10.3,-2.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#06539E").ss(14).p("ACoijIlPFH");
	this.shape_21.setTransform(9.8,-2.125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_12}]},8).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_17}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_18}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_20}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_21}]},1).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_19}]},1).wait(129));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.5,-60.4,152.7,152.6);


(lib.shield_icon_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// shield_mc (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_5 = new cjs.Graphics().p("Aobp1IQ3AAIAATrIw3AAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(5).to({graphics:mask_graphics_5,x:0,y:0}).wait(113));

	// shine
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(0.1).p("ADQjAIAAAdAjPDBIAAlm");
	this.shape.setTransform(-106.25,31.8125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGDHBMgiKAdaIpJH4g");
	this.shape_1.setTransform(-66.2,-76.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAOIAAgb");
	this.shape_2.setTransform(-84.35,15.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGDHBMgrTAlSg");
	this.shape_3.setTransform(-65.05,-75.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4qPKMArTglTIGDHBMgrTAlSg");
	this.shape_4.setTransform(-61.6,-71.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArUglTIGDHBMgrUAlSg");
	this.shape_5.setTransform(-55.8,-64.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAPIAAgd");
	this.shape_6.setTransform(-67,34);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4rPKMArTglTIGEHBMgrUAlSg");
	this.shape_7.setTransform(-47.7,-56.225);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(0.1).p("AAAAPIAAgc");
	this.shape_8.setTransform(-56.6,45.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(0.1).p("AjPDBIAAlmADQjAIAAAd");
	this.shape_9.setTransform(23.75,172.825);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.298)","rgba(255,255,255,0)"],[0,0.569,1],19.4,22.5,-19.3,-22.4).s().p("A4qPKMArTglTIGDHBMgiLAdbIpIH3g");
	this.shape_10.setTransform(63.8,64.725);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8,this.shape_9,this.shape_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},5).to({state:[{t:this.shape_3,p:{x:-65.05,y:-75.025}},{t:this.shape_2,p:{x:-84.35,y:15.2}}]},1).to({state:[{t:this.shape_4,p:{x:-61.6,y:-71.275}},{t:this.shape_2,p:{x:-80.9,y:18.95}}]},1).to({state:[{t:this.shape_5},{t:this.shape_2,p:{x:-75.1,y:25.25}}]},1).to({state:[{t:this.shape_7},{t:this.shape_6,p:{x:-67,y:34}}]},1).to({state:[{t:this.shape_4,p:{x:-37.3,y:-44.925}},{t:this.shape_8,p:{x:-56.6,y:45.3}}]},1).to({state:[{t:this.shape_4,p:{x:-24.6,y:-31.175}},{t:this.shape_8,p:{x:-43.9,y:59.05}}]},1).to({state:[{t:this.shape_3,p:{x:-9.6,y:-14.875}},{t:this.shape_8,p:{x:-28.9,y:75.35}}]},1).to({state:[{t:this.shape_3,p:{x:7.2,y:3.325}},{t:this.shape_6,p:{x:-12.1,y:93.55}}]},1).to({state:[{t:this.shape_4,p:{x:22.2,y:19.625}},{t:this.shape_8,p:{x:2.9,y:109.85}}]},1).to({state:[{t:this.shape_4,p:{x:34.9,y:33.375}},{t:this.shape_8,p:{x:15.6,y:123.6}}]},1).to({state:[{t:this.shape_3,p:{x:45.3,y:44.675}},{t:this.shape_8,p:{x:26,y:134.9}}]},1).to({state:[{t:this.shape_3,p:{x:53.4,y:53.425}},{t:this.shape_8,p:{x:34.1,y:143.65}}]},1).to({state:[{t:this.shape_4,p:{x:59.2,y:59.725}},{t:this.shape_8,p:{x:39.9,y:149.95}}]},1).to({state:[{t:this.shape_3,p:{x:62.65,y:63.475}},{t:this.shape_8,p:{x:43.35,y:153.7}}]},1).to({state:[{t:this.shape_10},{t:this.shape_9}]},1).wait(98));

	// shield_mc
	this.instance = new lib.shield_mc();
	this.instance.setTransform(0,0,0.7857,0.7857);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.7921,scaleY:0.7921,alpha:0.121},0).wait(1).to({scaleX:0.8091,scaleY:0.8091,alpha:0.4415},0).wait(1).to({scaleX:0.8386,scaleY:0.8386,alpha:1},0).wait(1).to({scaleX:0.9035,scaleY:0.9035},0).wait(1).to({scaleX:0.977,scaleY:0.977},0).wait(1).to({scaleX:1.0343,scaleY:1.0343},0).wait(1).to({scaleX:1.0671,scaleY:1.0671},0).wait(1).to({scaleX:1.0794,scaleY:1.0794},0).to({scaleX:1,scaleY:1},4,cjs.Ease.quadInOut).wait(106));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.3,-68,116.6,136);


(lib.shield_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.shield_icon_1("synched",0,false);
	this.instance.setTransform(4,-42.45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(66).to({startPosition:66},0).to({_off:true},1).wait(293));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_Tolerant();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(58).to({_off:true},1).wait(293));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-188,-110.4,369,243.4);


(lib.gauge_anim = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// gauge_needle
	this.instance = new lib.gauge_needle();
	this.instance.setTransform(0.15,-0.95,0.0838,0.0838,-132.9925,0,0,0.1,0.8);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).to({regX:-0.3,regY:0.5,scaleX:1,scaleY:1,rotation:-132.9917,y:-0.9},5).wait(1).to({regX:31.7,regY:-30.5,rotation:-133.4994,x:-44.25,y:-2.75},0).wait(1).to({rotation:-134.6077,x:-44.3,y:-1.95},0).wait(1).to({regX:-0.1,regY:0.5,scaleX:0.9999,scaleY:0.9999,rotation:-136.3899,x:0.15,y:-1.05},0).to({regX:-0.2,scaleX:1,scaleY:1,rotation:6.0191,x:0.25,y:-0.75},11,cjs.Ease.quadInOut).to({regY:0.4,rotation:-1.643,x:0.2,y:-0.85},3).to({regY:0.3,rotation:3.7245,x:0.3,y:-0.95},3).to({rotation:-1.0125,x:0.25},3).to({rotation:3.7245,x:0.3},3).to({rotation:-0.2544},3).to({rotation:3.7245},3).to({rotation:-1.4769,x:0.25},3).to({rotation:3.7245,x:0.3},3).wait(37));

	// gauge_dial
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#06539E").ss(15).p("AgmDdQAAjJBVil");
	this.shape.setTransform(-76.2611,-24.95);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#06539E").ss(15).p("AhcEyQAAk2DNji");
	this.shape_1.setTransform(-70.8283,-33.4625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#06539E").ss(15).p("Aj1GiQAAlMDqjqQCJiKCsg4");
	this.shape_2.setTransform(-55.508,-44.6875);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#06539E").ss(15).p("AoDG2QAAlMDqjqQDrjqFLAAQB6AABtAf");
	this.shape_3.setTransform(-28.5375,-46.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#06539E").ss(15).p("AqrG2QAAlMDqjqQDrjqFLAAQFNAADqDq");
	this.shape_4.setTransform(-11.75,-46.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#06539E").ss(15).p("AsFG2QAAlMDqjqQDrjqFLAAQFMAADrDqQB5B6A7CS");
	this.shape_5.setTransform(-2.7375,-46.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#06539E").ss(15).p("AsbG2QAAlMDrjqQDrjqFKAAQFNAADqDqQC3C2ApDx");
	this.shape_6.setTransform(-0.5875,-46.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#06539E").ss(15).p("AsgG2QAAlMDrjqQDrjqFKAAQFNAADqDqQDXDWATEo");
	this.shape_7.setTransform(-0.0875,-46.675);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#06539E").ss(15).p("AshG2QAAlMDrjqQDrjqFLAAQFMAADrDqQDrDqAAFM");
	this.shape_8.setTransform(0,-46.675);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape}]},2).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).wait(71));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-108.4,-117.8,196.10000000000002,182.7);


(lib.checkMark_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// checkMark_anim
	this.instance = new lib.checkMark_anim("synched",0,false);
	this.instance.setTransform(19.95,-28.55,1,1,0,0,0,15.8,15.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(78).to({startPosition:78},0).to({_off:true},1).wait(281));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_purposeBuilt();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(70).to({_off:true},1).wait(281));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-186.5,-104.8,369,234.2);


(lib.gauge_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_10
	this.instance = new lib.gauge_anim("synched",0,false);
	this.instance.setTransform(2.05,-47.4,1,1,0,0,0,0,-38.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(46).to({startPosition:20},0).wait(18).to({startPosition:20},0).wait(9).to({startPosition:29},0).to({_off:true},1).wait(286));

	// txt_industrialLevel
	this.instance_1 = new lib.txt_industrialLevel();
	this.instance_1.setTransform(0,49.35);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:29.85,alpha:1},8,cjs.Ease.quadOut).wait(65).to({_off:true},1).wait(286));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-184.5,-126.4,369,244);


// stage content:
(lib.Epson_DyeSub_V3_300x250 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,125.0015,1,0.4167);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// Epson_Logo
	this.instance = new lib.Epson_Logo_1();
	this.instance.setTransform(80.75,40.55,0.8039,0.8039);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},5).wait(355));

	// ctaBtn_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_352 = new cjs.Graphics().p("Am2CWQgjAAAAgjIAAAAIAAjlQAAgjAjAAIAAAAINtAAQAjAAAAAjIAAAAIAADlQAAAjgjAAIAAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(352).to({graphics:mask_graphics_352,x:236.3144,y:219.8146}).wait(8));

	// shine
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.1,-10.9,14.2,10.8).s().p("AoLGHIL8vmIEbDZIr8Pmg");
	this.shape_1.setTransform(76.825,99.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.1,-10.8,14.2,10.9).s().p("AoMGHIL9vnIEcDaIr9Png");
	this.shape_2.setTransform(81.925,101.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.2,-10.9,14.2,10.9).s().p("AoNGJIL+vqIEdDaIr+Ppg");
	this.shape_3.setTransform(97.2,106.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.2,-10.9,14.3,10.9).s().p("AoPGKIMCvuIEdDbIsCPtg");
	this.shape_4.setTransform(122.625,115.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.4,-11,14.3,11).s().p("AoSGMIMFvzIEgDcIsGPzg");
	this.shape_5.setTransform(155.75,126.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.4,-11,14.4,11).s().p("AoUGNIMJv3IEgDdIsJP4g");
	this.shape_6.setTransform(181.175,135.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.5,-11.1,14.4,11).s().p("AoVGPIMLv6IEhDdIsMP6g");
	this.shape_7.setTransform(196.45,140.375);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.498)","rgba(255,255,255,0)"],[0,0.537,1],-14.5,-11.1,14.4,11).s().p("AoWGPIMLv7IEiDeIsMP7g");
	this.shape_8.setTransform(201.55,142.125);

	var maskedShapeInstanceList = [this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6,this.shape_7,this.shape_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},352).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).wait(1));

	// ctaBtn
	this.instance_1 = new lib.ctaBtn();
	this.instance_1.setTransform(236.7,220.2,0.5832,0.5832,0,0,0,0.7,0.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(346).to({_off:false},0).to({alpha:1},6).wait(8));

	// txt_sureColor_f10070
	this.instance_2 = new lib.txt_sureColor_f10070_endFrame();
	this.instance_2.setTransform(149.05,222.95);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(344).to({_off:false},0).to({y:204.45,alpha:1},7,cjs.Ease.quadOut).wait(9));

	// printer_mc
	this.instance_3 = new lib.printer_mc();
	this.instance_3.setTransform(150.2,183.05,0.3848,0.3848);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(344).to({_off:false},0).to({regY:0.1,scaleX:0.3074,scaleY:0.3074,x:145.7,y:151.6},6,cjs.Ease.quadOut).wait(10));

	// txt_toDyeFor
	this.instance_4 = new lib.txt_humor();
	this.instance_4.setTransform(157.25,186.4,1,1,0,0,0,-2,6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(313).to({_off:false},0).to({y:174.35,alpha:1},6,cjs.Ease.quadOut).wait(19).to({y:165.35,alpha:0},7,cjs.Ease.quadIn).to({_off:true},1).wait(14));

	// txt_toDyeFor
	this.instance_5 = new lib.txt_toDyeFor();
	this.instance_5.setTransform(157.25,201.4,1,1,0,0,0,-2,6);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(286).to({_off:false},0).to({y:179.35,alpha:1},5,cjs.Ease.quadOut).wait(22).to({y:168.75},6,cjs.Ease.quadOut).wait(19).to({y:159.75,alpha:0},7,cjs.Ease.quadIn).to({_off:true},1).wait(14));

	// printer_mc
	this.instance_6 = new lib.printer_mc();
	this.instance_6.setTransform(451.2,183.05,0.3848,0.3848);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(283).to({_off:false},0).to({x:150.2},8,cjs.Ease.quadInOut).to({_off:true},54).wait(15));

	// shield_animation
	this.instance_7 = new lib.shield_animation("synched",0,false);
	this.instance_7.setTransform(151.1,161.05,0.826,0.826,0,0,0,0.1,49.4);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(216).to({_off:false},0).wait(67).to({mode:"single",startPosition:49},0).to({x:-118.9},8,cjs.Ease.quadInOut).to({_off:true},1).wait(68));

	// checkMark_animation
	this.instance_8 = new lib.checkMark_animation("synched",0,false);
	this.instance_8.setTransform(151.1,163,0.826,0.826,0,0,0,0.1,49.4);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(133).to({_off:false},0).wait(79).to({mode:"single",startPosition:49},0).to({x:-119.9},6,cjs.Ease.quadInOut).to({_off:true},1).wait(141));

	// gauge_animation
	this.instance_9 = new lib.gauge_animation("synched",0,false);
	this.instance_9.setTransform(146.15,173.2,0.8256,0.8256,0,0,0,0.1,49.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(56).to({_off:false},0).wait(74).to({mode:"single",startPosition:49},0).to({x:-121.85},5,cjs.Ease.quadInOut).to({_off:true},1).wait(224));

	// txt_sureColor_f10070
	this.instance_10 = new lib.txt_sureColor_f10070();
	this.instance_10.setTransform(149.05,222.95);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(19).to({_off:false},0).to({y:208.95,alpha:1},7,cjs.Ease.quadOut).wait(23).to({alpha:0},6).to({_off:true},1).wait(304));

	// printer_mc
	this.instance_11 = new lib.printer_mc();
	this.instance_11.setTransform(328.2,191.1,1.0863,1.0863);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).to({x:238.2,alpha:1},7,cjs.Ease.quadOut).wait(5).to({regX:0.1,scaleX:0.3877,scaleY:0.3877,x:149.25,y:183.55},7,cjs.Ease.quadInOut).wait(30).to({alpha:0},6).to({_off:true},1).wait(304));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-124.2,124,982.7,245.60000000000002);
// library properties:
lib.properties = {
	id: '3E1D9D289AAA471FB8DD4F28FE5CF1AF',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"Epson_Logo.png", id:"Epson_Logo"},
		{src:"projector_image.jpg", id:"projector_image"},
		{src:"shield_icon.png", id:"shield_icon"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3E1D9D289AAA471FB8DD4F28FE5CF1AF'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;