(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.image_01 = function() {
	this.initialize(img.image_01);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,339,400);


(lib.image_02 = function() {
	this.initialize(img.image_02);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.image_03 = function() {
	this.initialize(img.image_03);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,339,397);


(lib.image_04 = function() {
	this.initialize(img.image_04);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,307,610);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.image_04_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.image_04();
	this.instance.setTransform(-90,-302);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_04_1, new cjs.Rectangle(-90,-302,307,610), null);


(lib.image_03_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0,0.259],54.5,-22.5,54.5,-203.5).s().p("A6PMHIAA4NMA0fAAAIAAYNg");
	this.shape.setTransform(86,243.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0.035,0.255],-50.5,73.6,-50.5,254.6).s().p("A63YdMAAAgw5MA1vAAAMAAAAw5g");
	this.shape_1.setTransform(96,-249.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.image_03();
	this.instance.setTransform(-101,-172);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_03_1, new cjs.Rectangle(-101,-405.8,369,726.9000000000001), null);


(lib.image_02_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0,0.239],54.5,-12.5,54.5,-193.5).s().p("A6PNrIAA7VMA0fAAAIAAbVg");
	this.shape.setTransform(50,264.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0.035,0.255],-50.5,73.6,-50.5,254.6).s().p("A63YdMAAAgw5MA1vAAAMAAAAw5g");
	this.shape_1.setTransform(60,-315.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer_1
	this.instance = new lib.image_02();
	this.instance.setTransform(287.05,-355,1.2402,1.2402,0,0,180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_02_1, new cjs.Rectangle(-118,-471.8,405.1,860.9000000000001), null);


(lib.image_01_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0,0.38],16.6,-165.5,197.6,-165.5).s().p("EgNCA8oMAAAh5PIaFAAMAAAB5Pg");
	this.shape.setTransform(-60,50.65);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0.035,0.255],-50.5,73.6,-50.5,254.6).s().p("A63YdMAAAgw5MA1vAAAMAAAAw5g");
	this.shape_1.setTransform(96,-257.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#FFFFFF","rgba(255,255,255,0)"],[0,0.259],54.5,-12.5,54.5,-193.5).s().p("A6PNrIAA7VMA0fAAAIAAbVg");
	this.shape_2.setTransform(86,214.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	// Layer_1
	this.instance = new lib.image_01();
	this.instance.setTransform(-52,-180);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.image_01_1, new cjs.Rectangle(-143.5,-413.8,430.5,852.5), null);


(lib.txt_03 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AtNFsQgYgLgQgUIAggaQAMAQAPAHQAPAIAYAAQAPAAALgEQAMgEAIgJQAIgIAFgLQAEgLAAgOIAAgPQgLAQgSAIQgTAJgUAAQgTAAgTgGQgSgIgNgOQgOgOgJgSQgHgUgBgXQABgXAHgUQAJgSAOgOQANgNASgIQATgHAUAAQATAAATAIQARAKAMAOIAAgcIAnAAIAAC2QABAXgIASQgIASgOANQgOANgSAHQgTAIgVgBQgkAAgXgKgAstCCQgLAFgJAKQgKAIgEANQgGAMABAOQgBAOAGAMQAEANAKAIQAJAKALAFQANAFANAAQAPAAALgFQAMgFAIgKQAJgIAGgNQAEgMAAgOQAAgOgEgMQgGgNgJgIQgIgKgMgFQgMgFgOAAQgNAAgNAFgAKwEiQgHgJAAgLQAAgNAIgIQAHgIANAAQAMAAAIAIQAIAIAAANQAAALgIAJQgIAIgMAAQgMAAgJgIgAH8EgQgTgIgOgOQgOgOgHgSQgIgUAAgVQAAgWAIgTQAHgTAOgOQAOgOATgIQATgIAXAAQAVAAATAHQASAIAOAOQAOANAHASQAIAUAAAWIAAAQIinAAQAEAYASAPQASAPAcAAQAUgBAPgIQAOgKAIgNIAiASQgPAXgWAMQgWANggAAQgZAAgTgHgAJjCtQgEgXgRgNQgQgNgYAAQgZAAgRAOQgQAOgGAVIB9AAIAAAAgABzEgQgTgIgOgOQgOgOgIgSQgHgUAAgVQAAgWAIgTQAHgTAPgOQAOgOASgIQATgIAWAAQAWAAATAHQASAIAOAOQAOANAHASQAIAUAAAWIAAAQIinAAQAFAYARAPQASAPAbAAQAWgBANgIQAOgKAKgNIAgASQgOAXgWAMQgWANghAAQgYAAgTgHgADaCtQgFgXgQgNQgQgNgZAAQgXAAgSAOQgRAOgFAVIB9AAIAAAAgAlyEYQgQgRAAgkIAAhiIgoAAIAAgkIAoAAIAAgrIAngaIAABFIA3AAIAAAkIg3AAIAABiQAAAQAHAHQAHAIAMAAQALAAAJgIIATAhQgJAGgKADQgKADgNAAQgeAAgQgPgAEoEjIAAjGIAnAAIAAAjQAGgTAOgJQAPgKATAAQAKAAAJACQAIACAHAEIgQAmQgJgGgQAAQgVAAgNALQgMAMAAAbIAABvgAgYEjIAAhvQAAgagNgPQgNgPgZAAQgLAAgJAEQgKAEgIAHQgHAIgDALQgFAKAAAOIAABtIgnAAIAAkhIAnAAIAAB2QALgOAQgJQAQgIAUAAQATAAAPAGQAPAGALALQAJALAGARQAGAQgBAUIAABzgAnwEjIAAhvQAAgagNgPQgMgPgZAAQgMAAgKAEQgJAEgHAHQgHAIgFALQgDAKAAAOIAABtIgoAAIAAkhIAnAAIAAB2QALgOAQgJQAQgIAUAAQATAAAPAGQAQAGAJALQALALAGARQAFAQABAUIAABzgAvKEjIAAjGIAoAAIAADGgAxoEjIAAjGIAoAAIAAAjQAFgTAPgJQAOgKAUAAQAJAAAKACQAIACAGAEIgPAmQgKgGgPAAQgWAAgNALQgMAMAAAbIAABvgAvKA2QgJgJABgMQgBgMAJgIQAHgIANAAQAMAAAIAIQAIAIAAAMQAAAMgIAJQgIAIgMAAQgNAAgHgIgAJdhYQgTgIgOgOQgOgNgHgTQgIgTAAgWQAAgVAIgTQAIgUANgOQAOgOAUgHQASgIAWAAQAWgBATAIQATAIANANQANAOAJASQAHATAAAWIAAARIinAAQAFAXARAPQASAPAcAAQAUAAAPgJQANgJAJgOIAiATQgPAWgWANQgWANggAAQgYAAgUgIgALEjLQgFgXgQgNQgQgMgZAAQgXAAgRANQgRAOgHAVIB+AAIAAAAgAAVhYQgTgIgNgOQgOgOgIgTQgIgSAAgXQAAgUAIgTQAIgUAOgOQANgOATgHQATgIAVAAQAVAAAUAIQATAHAOAOQANAOAIAUQAJATAAAUQAAAXgJASQgIATgNAOQgOAOgTAIQgUAIgVAAQgVAAgTgIgAAkj1QgLAGgJAJQgJAJgEAMQgEAMgBANQABAOAEAMQAEANAJAIQAJAKALAFQALAFAOAAQAOAAALgFQAMgFAIgKQAKgIAEgNQAFgMAAgOQAAgNgFgMQgEgMgKgJQgIgJgMgGQgMgEgNAAQgOAAgLAEgAp/hbQgWgLgMgVIAjgVQAKAOAMAIQANAIATAAQAUAAAJgJQAKgIAAgLQAAgHgEgFQgEgEgHgCIg8gQQgMgDgLgHQgJgGgGgLQgHgKABgPQgBgLAGgLQAFgLAKgIQAKgJAPgEQANgFASAAQAcAAATAKQAUAKANARIgjAUQgGgMgMgGQgLgGgQAAQgSAAgJAHQgJAIAAAKQAAANANAEQAMAFAYAEIAYAHQANAEAKAHQAKAGAHALQAGAKAAAPQAAALgFALQgFAMgKAIQgKAKgPAFQgQAGgUAAQgfAAgWgLgAQfhgQgQgQAAglIAAhiIgnAAIAAgkIAnAAIAAgrIAngZIAABEIA4AAIAAAkIg4AAIAABiQAAARAHAHQAHAIAMgBQALAAAJgHIATAgQgJAHgKACQgLADgMABQgegBgQgPgAw+hgQgQgQgBglIAAhiIgnAAIAAgkIAnAAIAAgrIAngZIAABEIA4AAIAAAkIg4AAIAABiQABARAGAHQAIAIALgBQAMAAAIgHIAUAgQgJAHgLACQgKADgMABQgegBgQgPgAOihUIAAhwQAAgagNgPQgNgOgZAAQgLAAgKADQgJAEgIAIQgHAIgEAKQgEALAAANIAABuIgnAAIAAjHIAmAAIAAAcQALgOAPgJQAQgJAVABQAUAAAOAFQAQAHAKALQAKALAHAQQAFARAAAUIAABzgAHQhUIAAh1QAAgWgKgPQgKgNgYAAQgWAAgMANQgNAOAAAbIAABxIgoAAIAAh3QAAgXgLgNQgKgMgWAAQgXAAgMANQgNAOAAAdIAABvIgoAAIAAjHIAnAAIAAAYQAKgNAOgIQAOgGATAAQAYAAAPAJQAQAJAIARQAKgRAQgJQAQgJAXAAQAUAAAPAFQAPAGAKALQAKAMAFAOQAEAQABATIAAB3gAh3hUIAAh1QAAgWgLgPQgKgNgYAAQgVAAgMANQgNAOgBAbIAABxIgnAAIAAh3QAAgXgLgNQgLgMgWAAQgWAAgNANQgMAOAAAdIAABvIgoAAIAAjHIAnAAIAAAYQAKgNANgIQAOgGAUAAQAXAAAQAJQAPAJAJARQAJgRARgJQAQgJAWAAQAVAAAPAFQAOAGALALQAJAMAFAOQAFAQAAATIAAB3gArnhUIAAjHIAoAAIAADHgAs9hUIAAhwQAAgagMgPQgNgOgZAAQgLAAgKADQgJAEgIAIQgHAIgEAKQgEALAAANIAABuIgnAAIAAkiIAnAAIAAB2QALgOAQgIQAPgJAVABQASAAAQAFQAPAHAKALQALALAFAQQAGARAAAUIAABzgArnlCQgJgIAAgMQAAgMAJgIQAHgJAMAAQANAAAIAJQAIAIAAAMQAAAMgIAIQgIAJgNAAQgMAAgHgJg");
	this.shape.setTransform(62.65,-14.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_03, new cjs.Rectangle(-54.4,-61.8,250.5,90), null);


(lib.txt_02 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhiIiQgNgEgJgHIAWghQAGAFAGADQAGAEAIAAIAOgCQAGgCAFgEQAFgEAEgHIANgaIhPi5IApAAIA7CMIA3iMIAoAAIhWDMQgHASgHALQgIANgJAGQgJAIgLADQgLADgOABQgOAAgNgFgAGTHaQgRgHgOgOQgOgOgIgSQgIgSAAgWQAAgUAIgTQAIgSAOgPQAOgNARgIQATgIAWAAQAUAAATAIQASAIAOANQANAPAJASQAHATABAUQgBAWgHASQgJASgNAOQgOAOgSAHQgTAIgUAAQgWAAgTgIgAGjFBQgLAFgJAKQgJAIgFAMQgEAMAAANQAAAOAEAMQAFAMAJAIQAJAJALAFQALAFAOAAQANAAALgFQALgFAIgJQAKgIAEgMQAFgMAAgOQAAgNgFgMQgEgMgKgIQgIgKgLgFQgMgEgMAAQgOAAgLAEgAkTHcQgRgIgOgNQgNgNgJgTQgIgTAAgXQAAgXAIgTQAIgSANgNQAOgOASgGQARgIAUAAQAUAAASAJQARAIALAOIAAh1IAmAAIAAEdIgmAAIAAgdQgLAPgSAJQgSAJgTgBQgUAAgRgGgAkDFAQgLAGgJAJQgJAIgEAMQgGAMAAAOQAAAOAGAMQAEAMAJAIQAJAKALAFQAMAFAOAAQAOAAALgFQAMgGAIgJQAIgIAGgMQAEgMAAgOQAAgNgEgNQgGgLgIgJQgIgJgMgGQgLgEgOAAQgOAAgMAEgAoEHeQgNgEgJgIQgIgIgFgLQgEgKAAgMQAAgfAXgQQAXgSApABIA6AAIAAgEQAAgUgMgLQgMgMgbAAQgTAAgOAHQgOAJgIAOIgjgTQAPgUAWgNQAWgMAgAAQAUAAARAFQAQAGALAKQAMALAFAOQAHAOAAATIAAB4IgmAAIAAgjQgLASgVAKQgUAKgZAAQgQABgNgFgAn4GPQgLAIAAAPQgBAMAKAIQAJAGATABQALAAAJgDQALgDAIgGQAJgEAIgIQAHgHAFgKIAAgRIg3AAQgbAAgMAIgArUHaQgTgHgOgOQgNgNgIgSQgHgTAAgVQgBgVAJgTQAHgSAOgPQAOgNASgIQASgIAWAAQAVAAATAIQASAHANANQANANAIASQAHATAAAWIAAAQIijAAQAEAXARAPQASAOAbAAQAUAAAOgIQAOgKAJgOIAgATQgOAWgWANQgWAMgfAAQgYAAgSgIgApvFrQgFgYgQgMQgQgMgYAAQgYAAgQANQgQANgHAWIB8AAIAAAAgAJGHfIAAjDIAlAAIAAAiQAHgTAOgIQAOgKATAAQAKABAIABQAIACAGAEIgPAlQgJgFgQgBQgUAAgMAMQgMALgBAaIAABugADjHfIAAigIghAAIAAgjIAhAAIAAgLQAAgXAEgOQAEgPAIgKQAKgIAPgEQAOgEAXAAIAJAAIAAAkIgdABQgIACgEAEQgFAFgBAJIgBAgIAwAAIAAAjIgwAAIAACggAukHfIAAjDIAmAAIAAAiQAGgTAOgIQAOgKATAAQAJABAJABQAIACAGAEIgPAlQgJgFgPgBQgVAAgNAMQgMALABAaIAABugAMoBmQgSgIgOgNQgOgOgHgTQgIgRAAgWQABgUAHgTQAIgTAOgNQANgOATgIQASgIAWAAQAWAAASAHQARAIAOANQAOAOAHARQAIATAAAUIAAAQIikAAQAEAYASAOQARAPAbAAQAVAAANgJQAOgJAIgNIAhATQgOAVgWAMQgVANggABQgXAAgUgIgAONgJQgEgXgQgNQgQgNgYAAQgYAAgQAOQgRANgFAWIB6AAIAAAAgAFLBmQgSgIgOgNQgOgOgHgTQgIgRAAgWQABgUAHgTQAIgTAOgNQANgOATgIQASgIAWAAQAWAAARAHQASAIAOANQAOAOAHARQAIATAAAUIAAAQIikAAQAEAYASAOQARAPAbAAQAVAAANgJQAOgJAIgNIAhATQgOAVgWAMQgVANggABQgXAAgUgIgAGwgJQgEgXgQgNQgQgNgYAAQgYAAgQAOQgRANgFAWIB6AAIAAAAgAk9BmQgSgIgOgNQgOgOgHgTQgIgRAAgWQABgUAHgTQAIgTAOgNQANgOATgIQASgIAWAAQAWAAASAHQARAIAOANQAOAOAHARQAIATAAAUIAAAQIikAAQAFAYARAOQARAPAbAAQAVAAANgJQAOgJAIgNIAhATQgOAVgWAMQgVANggABQgYAAgTgIgAjYgJQgEgXgQgNQgQgNgYAAQgYAAgQAOQgRANgFAWIB6AAIAAAAgArYBWQgUgWAAgpIAAhvIAnAAIAABtQAAAYANAPQAMAPAZAAQAKAAAKgEQAKgEAGgIQAIgHADgKQAFgKAAgNIAAhrIAmAAIAADBIgmAAIAAgaQgKAOgPAIQgRAJgTAAQgmAAgWgYgAuSBjQgVgLgMgWIAjgTQAIANANAIQANAHASAAQATABAKgJQAKgIAAgLQgBgGgEgEQgEgEgHgDIg6gQQgNgDgJgHQgKgFgFgJQgHgKABgPQAAgLAEgLQAFgKAKgJQAKgIAOgEQAOgFARAAQAcAAASAJQAUAKANARIgiATQgIgLgKgFQgLgHgQAAQgSAAgJAIQgIAGAAALQAAAMANAEQAMAFAWAFIAYAGQANADAKAGQAJAGAHAKQAGAKAAAQQAAALgEAKQgGALgKAKQgJAIgPAGQgPAFgUABQgfgBgVgKgAJYBpIAAjBIAmAAIAAAiQAHgTAOgIQAOgJASAAQALAAAIABQAIACAGAEIgPAmQgIgHgRABQgUgBgMALQgNAMAAAaIAABsgACOBpIg2iNIg1CNIglAAIhBjBIAoAAIAsCNIA1iNIAmAAIA0CNIAviNIAoAAIhEDBgAoMBpIAAjBIAlAAIAAAiQAHgTAOgIQAOgJASAAQALAAAIABQAIACAGAEIgPAmQgJgHgQABQgUgBgMALQgMAMgBAaIAABsgAH8hIQAQgMAIgLQAJgLAAgNQgBAHgFAEQgEADgGAAQgKAAgHgHQgGgHAAgJQAAgOAIgIQAIgHANgBQAPAAAJAKQAJALAAAPQAAAUgMAQQgMAQgTAMgAFlkOQgTgHgOgOQgNgNgHgTQgIgSAAgWQAAgVAIgSQAHgTAOgOQAOgOATgHQARgJAWAAQAWABASAHQASAIANAMQAOAOAIASQAHASAAAWIAAAQIikAAQAFAYARAOQASAPAbAAQAUAAANgJQAOgJAJgOIAhATQgOAVgWANQgWANgfAAQgYAAgTgIgAHKl+QgFgXgPgNQgQgMgZAAQgXAAgQANQgRAOgGAVIB7AAIAAAAgAhakLQgNgEgIgHQgIgIgFgLQgEgLAAgMQAAgeAWgRQAYgRApAAIA5AAIAAgDQAAgUgMgMQgMgMgaAAQgUAAgNAIQgOAJgJAOIgjgUQAPgTAWgNQAXgNAfAAQAVABAQAFQAQAGALAKQAMALAFAOQAGAOAAASIAAB4IglAAIAAgjQgMASgTAKQgVALgYAAQgQAAgOgFgAhNlaQgMAJAAAOQAAANAJAHQAJAHATAAQALAAAKgDQAKgDAJgFQAJgFAHgIQAHgHAFgKIAAgQIg2AAQgcAAgLAHgArVkOQgTgIgOgOQgNgNgIgSQgIgTAAgVQAAgVAIgSQAIgTANgOQAOgOATgHQASgJAVAAQAVAAASAJQATAHAOAOQAOAOAHATQAJASgBAVQABAVgJATQgHASgOANQgOAOgTAIQgSAIgVAAQgVAAgSgIgArHmnQgLAFgIAJQgJAJgEALQgFAMAAAOQAAAOAFALQAEAMAJAIQAIAKALAFQAMAEANAAQANAAAMgEQALgFAJgKQAJgIAEgMQAFgLAAgOQAAgOgFgMQgEgLgJgJQgJgJgLgFQgMgFgNAAQgNAAgMAFgAt9kWQgPgPAAglIAAhgIgnAAIAAgjIAnAAIAAgpIAmgaIAABDIA3AAIAAAjIg3AAIAABgQAAAQAHAIQAHAHALAAQAMAAAJgHIASAfQgJAHgKACQgKADgNAAQgdAAgQgPgADokKIg+hYIgjAlIAAAzIgmAAIAAkbIAmAAIAAC8IBbhkIAwAAIhMBTIBQBwgAjMkKIAAhyQAAgXgLgOQgKgNgXAAQgVAAgMANQgNAOAAAbIAABuIgnAAIAAh1QAAgWgKgNQgKgMgXAAQgWAAgMANQgNAOAAAcIAABtIgmAAIAAjDIAmAAIAAAXQAKgMANgHQAOgIASAAQAYAAAPAJQAQAKAHAQQAJgQARgJQAQgKAVAAQAVAAAOAHQAPAFAKALQAKALAEAPQAFAPAAASIAAB1g");
	this.shape.setTransform(43.9,15.95);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_02, new cjs.Rectangle(-50.9,-39.1,189.70000000000002,110.1), null);


(lib.txt_01 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AFwHwQgWgLgMgVIAjgUQAJAOAMAHQANAIATAAQATAAAJgIQAKgIAAgMQAAgGgFgEQgEgEgGgDIg7gPQgMgEgKgGQgJgGgGgKQgGgKAAgPQAAgLAFgLQAFgKAKgIQAJgJAPgEQAOgFAQAAQAcAAATAKQATAJANARIgiATQgHgKgLgGQgLgHgQAAQgRAAgJAIQgJAHAAAKQAAAMANAEQANAFAVAFIAZAGQAMAEAKAGQAKAHAGAKQAHAKgBAPQAAALgEALQgFALgKAJQgJAJgQAFQgOAGgVAAQgfAAgUgLgAjLHzQgTgIgOgNQgNgOgIgSQgHgSAAgWQAAgVAIgTQAHgSAPgOQANgOASgIQASgIAXAAQAVAAASAIQASAHANANQAOAOAIASQAHASAAAWIAAAQIikAAQAFAYARAOQASAOAbAAQAUAAAOgIQAOgJAIgOIAhATQgPAVgVANQgWANgfAAQgYAAgTgIgAhmGDQgFgXgQgNQgQgMgXAAQgYAAgRANQgQAOgGAVIB7AAIAAAAgAsIHzQgRgIgOgOQgOgNgIgTQgIgSAAgVQAAgVAIgTQAIgSAOgOQAOgOARgIQATgIAWAAQAUAAASAIQATAIAOAOQAOAOAHASQAJATgBAVQABAVgJASQgHATgOANQgOAOgTAIQgSAIgUAAQgWAAgTgIgAr5FaQgLAFgIAJQgIAIgGAMQgEAMAAAOQAAANAEAMQAGAMAIAIQAIAJALAFQAMAFAOAAQAMAAAMgFQALgFAJgJQAIgIAFgMQAFgMAAgNQAAgOgFgMQgFgMgIgIQgJgJgLgFQgMgFgMAAQgOAAgMAFgADsHrQgPgQAAgkIAAhgIgnAAIAAgjIAnAAIAAgqIAmgZIAABDIA3AAIAAAjIg3AAIAABgQAAAQAHAHQAHAIALAAQAMAAAJgIIASAgQgJAGgKADQgKADgNAAQgdAAgQgPgAByH3IAAhuQAAgZgNgPQgMgOgYAAQgMAAgJAEQgKADgHAIQgHAHgEALQgEALAAANIAABrIglAAIAAjDIAkAAIAAAbQALgOAPgIQAQgJAVAAQASAAAPAGQAPAGAKALQAKALAFAQQAHAQAAAUIAABxgAlUH3IAAhyQAAgXgKgOQgLgNgXAAQgVAAgNANQgMANAAAbIAABvIgnAAIAAh1QAAgWgKgNQgKgMgXAAQgVAAgNANQgMAOAAAcIAABtIgnAAIAAjDIAnAAIAAAXQAIgNAOgHQANgHAUAAQAWAAAQAJQAQAJAIARQAIgQARgJQAQgKAWAAQATAAAPAGQAPAGAJALQALALAEAPQAFAPAAASIAAB1gAuRH3IAAhyQAAgXgLgOQgKgNgXAAQgVAAgMANQgNANAAAbIAABvIgnAAIAAh1QAAgWgKgNQgLgMgWAAQgVAAgNANQgMAOAAAcIAABtIgnAAIAAjDIAnAAIAAAXQAJgNANgHQAOgHASAAQAYAAAPAJQAPAJAJARQAJgQAQgJQAQgKAWAAQATAAAQAGQAOAGAJALQAKALAFAPQAFAPAAASIAAB1gAG8B7QgVgLgNgVIAjgUQAKAOAMAHQAMAIATAAQATAAAJgIQAKgIAAgMQABgGgFgEQgEgEgGgDIg8gPQgMgEgJgGQgJgGgGgKQgGgKgBgOQABgLAFgLQAEgKALgIQAJgJAOgEQAOgFARAAQAbAAAUAKQATAJAMARIghATQgHgKgLgGQgLgHgQAAQgSAAgIAIQgJAHAAAKQAAALAMAEQANAFAWAFIAZAGQAMAEAJAGQALAHAGAKQAGAKAAAPQAAALgFALQgEALgLAJQgJAJgPAFQgPAGgUAAQgfAAgVgLgAm5B+QgTgIgNgOQgOgNgIgTQgIgSAAgVQAAgVAIgSQAIgSAOgOQANgOATgIQASgIAVAAQAVAAASAIQATAIAOAOQAOAOAHASQAJASgBAVQABAVgJASQgHATgOANQgOAOgTAIQgSAIgVAAQgVAAgSgIgAmrgaQgLAFgIAJQgJAIgEALQgFAMAAAOQAAANAFAMQAEAMAJAIQAIAJALAFQAMAFANAAQANAAAMgFQALgFAJgJQAJgIAEgMQAFgMAAgNQAAgOgFgMQgEgLgJgIQgJgJgLgFQgMgFgNAAQgNAAgMAFgAKKB2QgQgQAAgkIAAhfIgmAAIAAgjIAmAAIAAgqIAmgZIAABDIA3AAIAAAjIg3AAIAABfQABAQAGAHQAIAIALAAQALAAAJgIIATAgQgJAGgLADQgJADgNAAQgdAAgQgPgAEQCCIAAjCIAlAAIAAAiQAHgSAOgJQAOgJASAAQALAAAIABQAIACAGAEIgPAmQgJgGgQAAQgUAAgMALQgMALgBAZIAABugAC9CCIAAjCIAmAAIAADCgABCCCIAAifIgiAAIAAgjIAiAAIAAgLQAAgWAEgPQAEgPAJgJQAIgJAQgEQAPgEAWAAIAJAAIAAAkIgcABQgJACgFAFQgEAEgBAJIgCAgIAxAAIAAAjIgxAAIAACfgAh7CCIAAhuQAAgYgMgPQgMgOgZAAQgLAAgKAEQgJADgIAIQgHAHgEALQgDAKAAANIAABrIgnAAIAAjCIAmAAIAAAbQAKgOAPgIQARgJAUAAQASAAAPAGQAPAGAKALQALALAFAQQAGAQAAATIAABxgApDCCIAAjCIAnAAIAADCgAqWCCIAAkbIAmAAIAAEbgArqCCIAAkbIAnAAIAAEbgAs+CCIAAjCIAoAAIAADCgAuRCCIAAhyQAAgWgLgOQgKgNgXAAQgVAAgMANQgNANAAAaIAABvIgnAAIAAh1QAAgVgKgNQgLgMgWAAQgVAAgNANQgMAOAAAbIAABtIgnAAIAAjCIAnAAIAAAXQAJgNANgHQAOgHASAAQAYAAAPAJQAPAJAJARQAJgQAQgJQAQgKAWAAQATAAAQAGQAOAGAJALQAKALAFAPQAFAPAAARIAAB1gAC8hmQgHgIAAgMQAAgMAHgIQAIgIAMAAQAMAAAHAIQAJAIAAAMQAAAMgJAIQgHAIgMAAQgMAAgIgIgApEhmQgHgIAAgMQAAgMAHgIQAJgIALAAQANAAAHAIQAIAIAAAMQAAAMgIAIQgHAIgNAAQgMAAgIgIgAs+hmQgIgIABgMQgBgMAIgIQAIgIAMAAQAMAAAIAIQAHAIABAMQgBAMgHAIQgIAIgMAAQgNAAgHgIgAQQjyQgNgEgIgIQgJgIgEgLQgEgKgBgMQAAgfAYgRQAXgRApAAIA5AAIAAgDQABgUgMgMQgNgMgaAAQgTAAgOAIQgOAJgJAOIgjgUQAPgTAXgNQAWgMAgAAQAUAAARAFQAQAGALAKQAMALAFAOQAGAOAAASIAAB4IgmAAIAAgiQgLARgUALQgUAKgZAAQgRAAgNgEgAQdlBQgMAIAAAOQAAANAJAHQAJAHAUAAQAKAAAKgCQAKgDAJgGQAJgFAIgHQAHgIAEgKIAAgQIg3AAQgaAAgMAIgAILj2QgTgHgOgOQgNgNgIgTQgHgSgBgVQAAgWAJgSQAHgTAOgOQAOgNASgIQASgIAWAAQAVAAATAHQASAIANANQANANAIASQAIATgBAVIAAAQIijAAQAEAYASAOQARAPAbAAQAVAAANgJQAOgJAJgOIAgATQgOAWgWAMQgWANgfAAQgYAAgSgIgAJwlmQgFgXgQgMQgQgNgYAAQgXAAgRAOQgQANgHAVIB8AAIAAAAgAEjj2QgSgHgOgOQgOgNgHgTQgIgSAAgVQABgWAHgSQAIgTAOgOQANgNATgIQASgIAWAAQAWAAARAHQASAIAOANQAOANAHASQAIATAAAVIAAAQIikAAQAEAYASAOQARAPAbAAQAVAAANgJQAOgJAIgOIAhATQgOAWgWAMQgVANggAAQgXAAgUgIgAGIlmQgEgXgQgMQgQgNgYAAQgYAAgQAOQgRANgFAVIB6AAIAAAAgABIj5QgWgKgMgWIAjgTQAJANAMAIQANAHATAAQATAAAJgIQAKgIAAgLQAAgGgFgFQgEgEgGgCIg7gQQgMgDgKgHQgJgGgGgKQgGgKAAgPQAAgLAFgKQAFgLAKgIQAJgIAPgFQAOgEAQAAQAcAAATAJQAUAKAMARIgiATQgHgLgLgGQgLgGgQAAQgRAAgJAHQgJAHAAALQAAALANAFQAMAFAXAEIAYAHQANADAJAHQAKAGAHAKQAFAKAAAQQABAKgFALQgFALgKAJQgKAJgPAGQgOAFgVAAQgfAAgUgLgAjRj2QgSgHgOgOQgOgNgIgTQgHgSAAgVQAAgWAIgSQAIgTAOgOQANgNASgIQATgIAWAAQAVAAASAHQASAIAOANQANANAHASQAIATAAAVIAAAQIijAAQAEAYARAOQARAPAbAAQAVAAAOgJQANgJAJgOIAgATQgNAWgWAMQgWANggAAQgXAAgTgIgAhslmQgEgXgRgMQgPgNgYAAQgYAAgRAOQgQANgGAVIB7AAIAAAAgArkj2QgSgHgOgOQgOgNgIgTQgHgSAAgVQAAgWAIgSQAIgTAOgOQANgNASgIQATgIAWAAQAVAAASAHQASAIAOANQANANAHASQAIATAAAVIAAAQIijAAQAEAYARAOQARAPAbAAQAVAAAOgJQANgJAJgOIAhATQgOAWgXAMQgVANggAAQgXAAgTgIgAp/lmQgEgXgRgMQgPgNgYAAQgYAAgRAOQgQANgGAVIB7AAIAAAAgANIjyIAAhuQAAgYgMgPQgNgPgYAAQgLAAgKAEQgJAEgIAHQgGAIgFAKQgDALAAANIAABrIgnAAIAAjCIAmAAIAAAbQAKgOAQgJQAQgIAUAAQASAAAPAGQAPAGAKALQALALAFAQQAGAQAAAUIAABwgAmajyIhMjCIApAAIA3CSIA7iSIAoAAIhRDCgAutjyIhAjMIhBDMIgnAAIhKkHIApAAIA3DLIBBjLIAkAAIA/DMIA6jMIAoAAIhOEHgAo0mlQARgLAIgLQAJgLAAgNQgCAHgFADQgDAEgHAAQgKAAgGgHQgGgHgBgJQABgOAHgIQAJgIANAAQAPAAAIAKQAKALgBAPQABATgMARQgMAQgUAMg");
	this.shape.setTransform(67.7,13.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt_01, new cjs.Rectangle(-50.7,-37.1,236.8,101.30000000000001), null);


(lib.BSWH_Vertical = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKaN8IAAhCIg+AAIAABCIgiAAIAAiZIAiAAIAAA7IA+AAIAAg7IAiAAIAACZgAFoN8IAAh9IguAAIAAgcIB+AAIAAAcIguAAIAAB9gABWN8IAAiZIAhAAIAAB9IBLAAIAAAcgAhLN8IgLghIg6AAIgMAhIgiAAIA6iZIAjAAIA5CZgAiHNBIAoAAIgUg4IAAAAgAmqN8IAAiZIBzAAIAAAcIhRAAIAAAhIBKAAIAAAaIhKAAIAAAmIBSAAIAAAcgApbN8IAAhCIg+AAIAABCIghAAIAAiZIAhAAIAAA7IA+AAIAAg7IAiAAIAACZgA33KbQgHgGAAgMQAAgMAHgGQAHgGAKAAIAMAAQANAAAGgLQAVggAJgXQAGgOAAgMQAAgOgKgbIgviBQgJgZgFgHQgHgMgPgDIgPgDQgCgDAAgFQABgGADgBQAaACAfAAQAbAAAagCQADABAAAGQABAFgDADIgPADQgOADAAAFQAAAHASAxIATA4QAQApACABQAEgCASgqIAUgwQAVgvAAgNQAAgHgOgDIgTgDQgDgDABgFQAAgGADgBQAaACAbAAQAYAAAWgCQAEACAAAFQAAAFgDADIgKACQgOACgLAPQgKAMgQAiIgiBGQgkBJg5B9QgNAdgZAAQgNAAgHgIgARrIhQgMgigZg4IgkhRQg1BtgWA+QgCACgFAAQgFAAgEgCQgTgugXgzQhLingnhUQgLgWgGgIQgKgMgRgBIgPgCQgCgCAAgFQABgFADgCQAWACAoAAQApAAAcgCQADACAAAEQABAGgDACIgOACQgUABAAAJQAAAKAfBGIBoDhIAvhiQAJgTAAgFQAAgEgEgMQgkhQgfhAQgHgQgIgHQgJgJgOgBIgPgCQgDgDABgFQAAgEAEgCQAXACApAAQAwAAASgCQADACABAEQAAAFgDADIgPACQgSABgCAGQgCAGAJAUIAuBpQAWgsAOgjQAQglgBgMQAAgJgQgBIgSgCQgDgEABgEQAAgFADgBQAWACAjAAQAnAAATgCQADACAAAEQAAAFgCADIgSACQgQABgNARQgFAGgPAdIgZAxIgWAvQgFALAAADQAAAEAEALIA9CJQAehDAYg8IAxh3IAMgiQAGgRAAgEQAAgNgUgBIgSgCQgDgDAAgFQAAgEAEgCQAeACAcAAIABAAIAEAAQAcgBATgLQALgHATgOQAAAAAAAAQABgBAAAAQABAAAAABQABAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQgCAkAAAnIAAB/QAAAJACACQAoggApABQAogBAUAXQASAVAAAiIAABkQAAAiADAIQAEAJAQACIAQABQADACgBAGQAAAHgDAAIg8gBQggAAgYABQgDAAgBgHQAAgGADgCIAMgBQAQgDADgIQADgIAAgiIAAhVQAAgegOgRQgPgSgcAAQgbAAgUAQQgIAHgCAGQgCAFAAAPIAABlQAAAiADAIQAEAJAQACIAMABQADACAAAGQgBAHgDAAQgbgBgeAAQgeAAgcABQgEAAAAgHQgBgFADgDIAPgBQARgCADgJQADgHAAgjIAAkQQAAgbgCgIQgCgFgFABQgMAFgIANQgIANgeBGIgsBlQgnBbgkBeQgDACgEAAQgFAAgEgCgAqlIMQgFgJgFgbQgFgbgBgVQACgDAFAAQAFgBACADQAbBZBNAAQAkAAAUgVQATgTAAgeQAAgYgIgQQgMgYgegTIg5glQhBgsAAg8QAAgtAggdQAigdA5AAQAbgBAdAIQANAEAIAAQAEALADAWQAEAVAAATQgCADgGABQgFAAgCgCQgIgdgOgQQgWgXgmAAQgoAAgSAXQgOASAAAaQAAAXASAVQANARAVAMIAwAfQBLAuAABGQAAAxgjAfQgjAeg6ABQg3AAgngXgAeuIWQgWgKgOgTQgZggAAgtQAAg6AigmQAigoA1AAQAlAAAZAWQAXAUAAAdQAAAMgCADQgCAFghAAIhwAAQgLAAgDADQgCABAAAMQAAAwAaAfQAbAhAvAAQAQABAMgHQAOgHANgQQAKgCABAKQgOAcgdAPQgYANgbAAQgdAAgXgMgAe1FJQgUARAAAQQAAABAAAAQAAABABAAQAAABABAAQABAAABAAIArAAQA2AAAIgGQAEgEAAgHQAAgPgKgLQgNgMgYAAQgZgBgVAUgAbzIPQgMgQAAgeIAAiLQAAgMgBgCQgCgDgJAAIgRAAQgDgBAAgEQgBgFACgCQAcgJALgKQAOgPALgUQADgCADABQAFABACACIAAAbQAAAJABABQACACAHAAIBDAAQAFAEAAAJQAAAKgEACIhEAAQgIAAgBADQgCACAAAKIAABwQAAAgAHAPQAKAUAbAAQAGAAAKgDIAPgIQADAAACADQACADgBAEQgXAcgoAAQgkgBgPgSgAE1IPQgMgQAAgeIAAiLQAAgMgBgCQgCgDgJAAIgRAAQgDgBAAgEQgBgFACgCQAcgJALgKQAOgPALgUQADgCADABQAFABABACIAAAbQAAAJACABQACACAHAAIBDAAQAFAEAAAJQAAAKgEACIhEAAQgIAAgCADQgBACAAAKIAABwQAAAgAHAPQAKAUAbAAQAHAAAJgDQAFgCAKgGQADAAACADQACADgBAEQgXAcgoAAQgkgBgPgSgACAIPQgMgQAAgeIAAiLQAAgMgCgCQgCgDgJAAIgRAAQgCgBgBgEQAAgFABgCQAcgJALgKQAOgNALgWQAJgDAEAFIAAAbQAAAJABABQACACAIAAIBCAAQAGAEgBAJQAAAJgEADIhEAAQgHAAgCADQgCACAAAKIAABwQAAAgAHAPQAKAUAbAAQAHAAAJgDQAGgCAJgGQAEAAACADQABADgBAEQgJALgPAIQgSAIgVABQgjgBgPgSgAidH/QgjgiAAg4QAAg4AlglQAlglA2ABQAzgBAiAjQAkAkAAA2QAAA5gjAkQgjAlg4AAQg1AAgjgjgAh5FRQgUAcAAAwQAAAuATAgQAWAlAlAAQAkgBASghQAOgcAAgpQAAgtgQgfQgVgngoAAQgeAAgTAbgAl+ICQgjghAAg4QAAg1AjgmQAogqBGAAQAfgBAXALQAJAHAAARQAAAIgEAHQgEAHgFAAQgFAAgEgEQgagggiAAQgiAAgXAZQgaAbAAAtQAAAnAYAdQAcAjAtgBQAYAAARgKQAOgIAMgRQADgBAEACQADADAAAEQgOAfgfAQQgaAOgdABQgyAAgggggAxnH/QgkgiAAg4QAAg4AmglQAkglA2ABQA0gBAjAjQAjAkAAA2QAAA5gjAkQgjAlg5AAQg0AAgjgjgAxDFRQgUAcAAAwQAAAuATAgQAVAlAlAAQAlgBASghQAPgcAAgpQAAgtgSgfQgVgngnAAQgeAAgTAbgA5YIPQgFgJgEAAQgCAAgWAMIgUAKQgMAGgLAAQgagBgQgOQgTgQAAgZQAAgTALgLQALgLAcgKIBIgaQAGgDACgEQACgDAAgIIABgbQAAgWgIgNQgLgSgZAAQgOAAgLAHQgNAHgBANQgBARgFADQgGAGgLADQgKADgHAAQgIAAAAgIQAAgYAngaQAngZAhABQAhAAAQASQAPASgBAiIgEBoQgCA1AeAAQAHAAAIgEIAIgEQAEAAAAAIQAAAFgOAJQgRAMgTABQgZgBgPgSgA59G2QgdAKgLAIQgNAKAAAQQAAAMAHAKQAKAOAVAAQAIAAAMgFQALgFAFgFQAFgFACgHIABgQIABgkQAAgIgGAAQgGAAgSAHgAIDH/QgmgfAAguQAAhDBGgcQgYgaAAgaQAAggAWgWQAWgVAfAAQAXAAAQAMQARAMAAAVQAAATgQANQgNAKgMAAQgMAAAHgKQAKgNgEgOQgDgIgJgHQgJgHgMgBQgRgBgLAKQgLAJAAAOQAAAQALALQALAMAfARQAzAbAXAVQAmAgAaA2QAVgZAAggQAAgXgOgRQgIgLgOgCQgRgBgMAKQgFAEgDgCQgGgBACgMQACgPAOgLQAPgKAWAAQAJAAAWAEQARADAGABQAKAAAEgHIAEgCQAEAAACAEQAAARgKAKQgKALgVAFQAJATAAAUQAAArghAjQAOAaAOAKQAPAKAWAAQAHABAJgDIAKgCQAEAAAAADQAAAJgRAGQgRAGgYgBQgXABgQgHQgPgGgUgSQgeASgWAHQgWAGgaAAQg2ABglgggAIMGQQAAAuAhAjQAhAjAsgBQAQAAANgDQANgEATgJQgPgRgLgRIgNgTQgWghgXgVQgPgOgYgSIgMgKQgkAIAAAqgAZ4IZQgfAAgZABQgEAAAAgHQgBgFADgDIANgBQAQgCAEgJQADgHAAgjIAAhoQAAgTgCgFQgDgGgLgIIgGgEQgCgCAAgDQABgEACgBQAKgEAVgKQAUgJALgHQAFAAABAEIgDBKIAABsQAAAiAEAIQADAJAQACIANABQADACgBAGQAAAHgDAAQgbgBgeAAgAs5IZQggAAgYABQgDAAgBgHQAAgGADgCIALgBQARgDADgIQADgIAAgiIAAhoQAAgTgCgFQgCgGgMgIIgFgEQgCgCAAgDQAAgEACgBQAZgJAkgVQAFABAAADIAAAjQAAAFACABQAVgSALgHQATgMAPABQALgBAIAHQAIAHAAAKQAAAOgJAIQgIAHgJgBQgGABgHgFQgOgJgNAAQgNgBgIAMQgIAMAAAjIAABRQAAAiADAIQAEAKARABIAVABQAEACgBAGQgBAHgDAAgAzaIZQgfAAgbABQgDAAgBgHQAAgFADgDIAOgBQAQgCAEgJQADgIAAgiIAAkQQAAgagDgIQgDgHgNgIIgGgEQgCgBAAgFQAAgFACgBQApgNAYgMQAEAAACADIgCBLIAAEcQAAAiADAIQAEAJAQACIAOABQAEACgBAGQgBAHgDAAIg6gBgA/wIZIhFABQgDgBAAgFQgBgFADgEIALgBQAXgEAFgMQAFgLAAgwIAAjlQAAgjgFgKQgFgLgUgCIgTgCQgEgCABgGQAAgFAEgCQA2gFBLAAQBEAAAhARQAuAWAAA1QAAAegRAVQgPARgeAPQAAAGAMADQAeAFAWAXQAcAcAAAsQAAA2gnAeQgqAhhPgBIhIgBgA/UFRQgFACAAAKIAABZQAAAzANAOQAOARAhAAQArAAAZgTQAbgWAAgrQAAgrgYgaQgfgihBAAQgXAAgHAEgA/RCgQgEACgCADQgCAEAAAHIAAB6QAAANAEACQAFADAWgBQAxgCAWgQQAYgTAAgoQAAgpgcgVQgYgTgmAAQgUAAgIADgAZeDqQgJgIAAgMQAAgPAKgJQAJgJAOAAQANAAAJAJQAIAJAAANQAAAPgKAJQgIAHgOAAQgOABgIgKgAilAsIAAkcICbinIAAHDgAAVgeQgIgJAAgMQAAgLAIgIQAIgIAMAAQALAAAIAIQAIAIAAALQAAAMgIAJQgIAHgLAAQgMAAgIgHgAAZhCQgGAGAAAJQAAAKAGAHQAGAGAKABQAJgBAGgGQAGgHAAgKQAAgJgGgGQgGgHgJAAQgKAAgGAHgAAwgjIgIgNIgFAAIAAANIgFAAIAAgfIAMAAQALAAAAAJQAAAIgIABIAJANgAAjg0IAFAAQAIAAAAgFQAAgFgHAAIgGAAgAAMhkIAAkzICbCnIAACMgAC5j/IihieIG2AAIAACegAk9j/IAAieIEmAAIigCegAAYmxIChifICGAAIAACfgAnMmxIAAifIESAAICjCfgAAMt8ICbAAIAAEeIibCmgAilpeIAAiMICbAAIAAEyg");
	this.shape.setTransform(211.1469,89.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BSWH_Vertical, new cjs.Rectangle(0,0,422.3,178.5), null);


(lib.BSWH_Logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AxEDcIAAiGIBJhOIAADUgAvsC5QgEgEAAgGQAAgFAEgEQADgEAGAAQAFAAAEAEQADAEABAFQgBAGgDAEQgEADgFAAQgGAAgDgDgAvqCoQgEADAAAEQAAAFAEADQADADAEAAQAEAAADgDQADgDAAgFQAAgEgDgDQgDgDgEAAQgEAAgDADgAvfC3IgEgHIgDAAIAAAHIgCAAIAAgPIAFAAQAGAAAAAEQAAAEgEAAIAEAHgAvmCuIADAAQABAAABAAQAAAAABAAQAAgBAAAAQABAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAgBAAIgDAAgAhbCeIAAggIgdAAIAAAgIgQAAIAAhJIAQAAIAAAcIAdAAIAAgcIAQAAIAABJgAjrCeIAAg7IgWAAIAAgOIA8AAIAAAOIgWAAIAAA7gAlsCeIAAhJIAPAAIAAA7IAkAAIAAAOgAm4CeIgGgQIgbAAIgFAQIgQAAIAbhJIARAAIAbBJgAnUCCIASAAIgIgbgApdCeIAAhJIA2AAIAAAOIgmAAIAAAPIAjAAIAAAMIgjAAIAAASIAnAAIAAAOgAqwCeIAAggIgeAAIAAAgIgPAAIAAhJIAPAAIAAAcIAeAAIAAgcIAQAAIAABJgAvwCYIAAiQIBIBOIAABCgAufBPIhLhKIDNAAIAABKgAyMBPIAAhKICLAAIhMBKgAneA0QgEgEAAgFQAAgGAEgCQADgDAFAAIAFAAQAGAAADgFQAKgPAEgLQADgGAAgFQAAgGgEgOIgXg8IgHgQQgCgFgIgCIgGgBIgCgEQAAAAABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIAbABIAYgBQABAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAIgGABQgHACAAACIAIAbIAKAaQAGATACABIAKgVIAJgWQALgYgBgFQABgDgIgCIgIgBQAAAAgBAAQAAgBAAAAQAAgBAAAAQgBgBAAgBQAAAAABgBQAAAAAAgBQAAAAABAAQAAgBAAAAIAZABIAWgBQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABAAAAIgGABQgGABgFAHQgFAGgIAQIgPAhQgUAmgYA2QgGANgMAAQgGAAgDgDgAvqgEIBLhKIA/AAIAABKgAzPgEIAAhKICBAAIBNBKgAMDgFQgFgQgMgaIgRgmQgZAygLAeIgDABIgFgBIgTgtIg2h2QgEgLgEgEQgFgFgHgBIgHAAQgBgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAgBQAAAAAAAAIAdABIAhgBQAAAAABAAQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIgHAAQgKABAAAEQABAEAPAiQAQAnAgBCIAWgtIAEgMIgCgHQgPgigQgiQgEgIgDgDQgEgEgHgBIgHAAIgBgEIACgDIAeABIAggBIABADIgBAEIgHAAQgJABAAACQgBADADAKIAWAxQAKgUAHgRQAHgSAAgFQAAgEgIgBIgIAAIgBgEIABgDIAbABIAbgBQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIgBAEIgIAAQgIABgGAIIgKAQQgKATgLAaIgDAHIACAHIAdBAIAZg7IAXg5QAIgXAAgCQAAgGgJgBIgIAAQAAgBgBAAQAAgBgBAAQAAgBAAAAQAAgBAAAAIACgDIAbABIADAAQANgBAJgFIANgKIADAAQAAAAAAABQAAAAABAAQAAAAAAAAQAAAAAAABIgBAjIAAA7QAAAFABABQATgPATAAQATAAAJALQAJAJAAAQIAAAwQAAAPABAEQACAEAHABIAIABQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQgBABAAAAQAAAAgBAAIgcgBIgaABQgBAAAAAAQAAAAgBgBQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAAAIAGgBQAIgBABgEQACgEAAgPIAAgpQAAgOgHgIQgHgIgNAAQgNAAgKAIQgEADAAACIgBAKIAAAwQAAAPABAEQACAEAIABIAFABQABAAAAABQAAAAABAAQAAABAAAAQAAABAAABQAAAAgBABQAAABAAAAQAAABAAAAQgBAAAAAAIgbgBIgcABQAAAAAAAAQAAAAgBgBQAAAAAAgBQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAAAAAAAQABgBAAAAIAHgBQAHgBACgEQACgEAAgPIAAiAQAAgNgCgEQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAQgGACgEAGIgSAnIgVAwQgTAugQApIgEABIgDgBgAhPgPQgCgEgCgNQgDgMgBgKQABgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABQAFAQAJAKQANAQAWAAQARAAAJgKQAIgJAAgOQAAgLgDgIQgFgLgOgJIgagSQgfgTgBgdQABgVAPgOQAQgOAbAAQALAAAOAEIAKABIADAQIABATQAAAAAAAAQAAABgBAAQAAAAgBAAQAAABgBAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgEgOgGgHQgKgLgSAAQgSAAgJALQgHAIABAMQAAAUAXAPIAYAOQAhAWABAgQgBAYgPAOQgQAPgcAAQgZAAgTgLgASLgKQgKgFgHgIQgLgQAAgVQAAgbAQgSQAQgTAYAAQASAAAMALQALAJAAAOIgBAHQgBACgQAAIg1AAQgFAAgBABQgBABAAAGQAAAWAMAPQANAPAWAAQAIAAAFgCQAGgDAHgIQABAAAAgBQAAAAABAAQAAAAABAAQAAABABAAIABADQgGANgOAHQgMAGgMAAQgOAAgLgFgASPhrQgKAIAAAIQAAABAAAAQAAAAAAAAQABABAAAAQAAAAABAAIAUAAQAaAAADgDQACgCABgEQgBgHgFgFQgFgGgMAAQgMAAgJAJgAQ0gOQgGgHAAgOIAAhBQAAgGgBgBQgBgBgEAAIgIAAIgCgDIABgDQAMgEAGgFQAIgHAEgKIADAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIAAANQAAABAAAAQAAABAAABQAAAAABABQAAAAAAAAIAFABIAeAAQADACAAAEQAAAEgCACIggAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABIAAAGIAAA0QAAAPADAHQAFAKANAAQAEAAADgCIAHgDQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQgLANgTAAQgRAAgGgJgAGBgOQgGgHAAgOIAAhBQAAgGgBgBQgBgBgEAAIgIAAIgCgDIABgDQAMgEAGgFQAHgGAFgLIADAAQABAAAAAAQABAAAAABQAAAAABAAQAAAAAAABIAAANIABAEIAEABIAgAAQACACAAAEQgBAEgBACIggAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAABIgCAGIAAA0QAAAPAEAHQAFAKANAAQAEAAADgCIAHgDQAAAAABAAQAAAAAAAAQABAAAAABQAAAAABAAIAAADQgEAFgIAEQgIAEgKAAQgRAAgGgJgAErgOQgGgHABgOIAAhBIgBgHQgBgBgFAAIgIAAIgBgDIABgDQAMgEAGgFQAGgGAFgLIAEAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAABABIAAANQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAAAIAFABIAfAAQACACAAAEQAAAEgCACIgfAAQgBAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAABIAAAGIAAA0QAAAPACAHQAGAKAMAAQAEAAADgCIAIgDQAAAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAIAAADQgLANgSAAQgRAAgHgJgAClgVQgRgQAAgaQAAgaASgSQARgRAZAAQAZAAAQAQQAQARABAZQgBAbgQARQgRARgaAAQgZAAgQgQgAC1hnQgIAOgBAWQABAWAIAPQAKARASAAQARAAAIgQQAIgNAAgTQAAgVgIgPQgKgTgTAAQgOAAgKANgAA7gTQgRgQABgaQAAgZAQgSQATgUAhAAQAOAAALAFQAEAEAAAHQAAAEgCADQgBAEgDAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAgBQgMgOgRAAQgPAAgLALQgNANAAAVQAAATAMANQANAQAVAAQALAAAIgFQAHgDAGgJIADABIABADQgGAPgOAIQgMAGgOAAQgYAAgPgOgAkigVQgRgQAAgaQAAgaASgSQAQgRAaAAQAYAAAQAQQARARABAZQgBAbgRARQgQARgbAAQgYAAgQgQgAkRhnQgKAOAAAWQAAAWAJAPQAKARASAAQAQAAAJgQQAHgNAAgTQAAgVgIgPQgKgTgTAAQgOAAgIANgAoMgOQgDgEgCAAIgDACIgIAEQgMAHgHAAQgNAAgHgGQgJgIAAgMQAAgIAEgGQAGgFANgFIAigMQADgBABgCIAAgFIABgOQAAgJgEgHQgFgIgMAAQgGAAgFADQgHAEAAAGQAAAHgCACQgEADgFABIgIACQgEAAAAgEQAAgLATgMQASgMAQAAQAeAAgBAhIgBAxQgCAZAOAAQAFAAADgCIADgCQABAAAAAAQAAABABAAQAAABAAAAQAAABAAABQAAACgGAFQgJAFgIAAQgMAAgHgJgAodg3QgOAEgFAEQgHAFABAIQAAAFADAFQAFAGAJAAQAFAAAFgCQAGgCACgDQABgCABgDIABgIIABgQQAAgBAAgBQAAgBgBAAQAAgBgBAAQAAAAgBAAQgDAAgIADgAJLgKQgGgCgKgJQgOAJgKADQgKADgNAAQgaAAgRgPQgRgOAAgWQgBgfAhgOQgLgMAAgMQAAgPAKgKQAKgKAQAAQAKAAAIAFQAHAGABAKQAAAJgIAGQgGAEgFAAQgHAAAEgEQAEgGgBgHQgCgEgEgDQgEgDgGgBQgIAAgFAEQgFAFAAAHQAAAHAFAFQAFAGAPAIQAYANALAJQASAPAMAZQAJgLAAgPQAAgLgGgIQgDgFgIgBQgGgBgHAFQgBABAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAQgDgBABgFQABgHAHgFQAHgFALAAIANACIAMACQAEAAACgDIACgCQAAAAABAAQAAAAABABQAAAAAAAAQABABAAAAQAAAIgFAFQgFAFgJADQAEAJAAAJQAAATgQASQAGAMAIAEQAHAFAKAAIAHgBIAFgBQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAQABAEgIADQgIADgMAAQgKAAgIgEgAHlhJQABAWAPAQQAQAQAUAAQAIAAAFgBQAHgCAJgFIgMgQIgGgJQgLgPgLgKIgSgPIgGgEQgQADgBAUgAvwjbIBIAAIAACGIhIBPgAxEhVIAAhCIBJAAIAACRgAP6gJIgbABQAAAAgBAAQAAAAAAgBQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAIAHgBQAHgBACgEQABgEAAgPIAAgyQAAgJgBgCQgBgDgGgDIgCgCIgBgDIACgCIAOgGQAKgFAEgDQABAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIgBAjIAAAzQAAAPABAEQADAEAHABIAGABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAABIgCADIgagBgAiVgJIgZABQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAgBgBAAQAAgBABAAQAAgBAAAAQAAgBAAAAQABgBAAAAIAFgBQAIgBABgEQACgEAAgPIAAgyQAAgJgBgCQgBgDgGgDIgCgCIgBgDIABgCQAOgFAOgJQABAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAQIABADIAPgMQAJgFAHAAQAFAAAEADQAEADAAAFQAAAHgFADQgDADgFAAQgDAAgDgCQgGgEgGAAQgHAAgDAFQgEAFAAARIAAAnQAAAPACAEQACAFAHAAIAKABQABAAAAABQAAAAAAAAQABABAAAAQAAABgBABIgBADgAlYgJIgcABIgCgDQAAgBABgBQAAAAAAgBQAAAAAAAAQABgBAAAAIAGgBQAIgBABgEQACgEAAgPIAAiAQAAgNgCgDQgBgEgGgEIgDgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQgBgBAAAAIABgDQAWgHAJgFQAAAAABAAQAAAAABABQAAAAAAAAQABAAAAABIgBAjIAACGQAAAPACAEQABAEAHABIAIABQAAAAAAABQAAAAABABQAAAAAAABQAAAAAAABQAAAAgBABQAAABAAAAQAAABAAAAQgBAAAAAAIgbgBgArMgJIggABIgCgDIABgEIAFgBQALgCADgFQACgGAAgWIAAhsQAAgQgCgFQgDgFgJgBIgJgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAgBQAAAAABgBQAAAAAAAAQAAgBAAAAQABgBAAAAQAZgCAkAAQAgAAAQAIQAVAKAAAZQAAAOgIAKQgHAIgOAHQAAADAFABQAOADALAKQAOAOAAAUQgBAagSAOQgUAPglAAIgigBgAq+hnQgDABAAAFIAAAqQAAAYAGAGQAGAIARAAQATAAAMgJQANgKAAgUQAAgVgMgMQgOgQgfAAQgKAAgDACgAq9i6IgDACIgBAGIAAA5QAAAGACABQACABAKAAQAXgBALgHQALgJAAgTQAAgUgNgKQgLgJgSAAQgJAAgEACgAPuiXQgFgEAAgGQAAgHAFgEQAEgEAGAAQAGAAAFAEQAEAEAAAHQAAAHgFAEQgEADgGAAQgHAAgDgEg");
	this.shape.setTransform(72.05,23.825);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.BSWH_Logo, new cjs.Rectangle(-51.1,1.8,246.4,44.1), null);


// stage content:
(lib.BAY_LD_Wave3_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [359];
	// timeline functions:
	this.frame_359 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(359).call(this.frame_359).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,0,0,3).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(360));

	// image_mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_262 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_263 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_264 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_265 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_266 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_267 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_268 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_269 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_270 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_271 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_272 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_273 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_274 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_275 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_276 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_277 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_278 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_279 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	var mask_graphics_280 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	var mask_graphics_281 = new cjs.Graphics().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(262).to({graphics:mask_graphics_262,x:694.325,y:835}).wait(1).to({graphics:mask_graphics_263,x:691.825,y:832.3}).wait(1).to({graphics:mask_graphics_264,x:684.375,y:824.25}).wait(1).to({graphics:mask_graphics_265,x:671.975,y:810.85}).wait(1).to({graphics:mask_graphics_266,x:654.625,y:792.1}).wait(1).to({graphics:mask_graphics_267,x:632.275,y:767.95}).wait(1).to({graphics:mask_graphics_268,x:604.975,y:738.45}).wait(1).to({graphics:mask_graphics_269,x:572.675,y:703.6}).wait(1).to({graphics:mask_graphics_270,x:535.425,y:663.35}).wait(1).to({graphics:mask_graphics_271,x:493.225,y:617.75}).wait(1).to({graphics:mask_graphics_272,x:447.325,y:568.1}).wait(1).to({graphics:mask_graphics_273,x:405.125,y:522.5}).wait(1).to({graphics:mask_graphics_274,x:367.875,y:482.3}).wait(1).to({graphics:mask_graphics_275,x:335.575,y:447.4}).wait(1).to({graphics:mask_graphics_276,x:308.275,y:417.9}).wait(1).to({graphics:mask_graphics_277,x:285.975,y:393.75}).wait(1).to({graphics:mask_graphics_278,x:268.575,y:375}).wait(1).to({graphics:mask_graphics_279,x:256.175,y:361.6}).wait(1).to({graphics:mask_graphics_280,x:248.725,y:353.55}).wait(1).to({graphics:mask_graphics_281,x:246.225,y:350.85}).wait(79));

	// BSWH_Logo
	this.instance = new lib.BSWH_Vertical();
	this.instance.setTransform(149.05,250.1,0.5917,0.5917,0,0,0,208.6,89.9);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(262).to({_off:false},0).wait(98));

	// shape_BG
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(182,126,189,0.749)").s().p("EgbfAzlMAAAhnJMA2/AAAMAAABnJg");
	this.shape_1.setTransform(156.05,302.075);
	this.shape_1._off = true;

	var maskedShapeInstanceList = [this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(262).to({_off:false},0).wait(98));

	// Image_04
	this.instance_1 = new lib.image_04_1();
	this.instance_1.setTransform(86.35,308,1.0795,1.0795);
	this.instance_1._off = true;

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(262).to({_off:false},0).to({scaleX:1,scaleY:1,y:298},97).wait(1));

	// pink_transitions
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#916797","#906796"],[0,1],110.2,95.9,-336.5,-292.6).s().p("EhZMgDnMBJPhUNMBpKBbcMhJPBUNg");
	this.shape_2.setTransform(694.325,835);
	this.shape_2._off = true;

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["#916797","#906796"],[0,1],110.2,95.9,-336.5,-292.6).s().p("EhZMgDnMBJPhUNMBpKBbdMhJPBUMg");
	this.shape_3.setTransform(684.375,824.25);
	this.shape_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(262).to({_off:false},0).wait(1).to({x:691.825,y:832.3},0).to({_off:true},1).wait(2).to({_off:false,x:654.625,y:792.1},0).wait(1).to({x:632.275,y:767.95},0).wait(1).to({x:604.975,y:738.45},0).wait(1).to({x:572.675,y:703.6},0).to({_off:true},1).wait(1).to({_off:false,x:493.225,y:617.75},0).to({_off:true},1).wait(2).to({_off:false,x:367.875,y:482.3},0).wait(1).to({x:335.575,y:447.4},0).to({_off:true},1).wait(1).to({_off:false,x:285.975,y:393.75},0).to({_off:true},1).wait(1).to({_off:false,x:256.175,y:361.6},0).to({_off:true},1).wait(80));
	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(264).to({_off:false},0).wait(1).to({x:671.975,y:810.85},0).to({_off:true},1).wait(4).to({_off:false,x:535.425,y:663.35},0).to({_off:true},1).wait(1).to({_off:false,x:447.325,y:568.1},0).wait(1).to({x:405.125,y:522.5},0).to({_off:true},1).wait(2).to({_off:false,x:308.275,y:417.9},0).to({_off:true},1).wait(1).to({_off:false,x:268.575,y:375},0).to({_off:true},1).wait(1).to({_off:false,x:248.725,y:353.55},0).wait(1).to({x:246.225,y:350.85},0).wait(79));

	// BSWH_Logo
	this.instance_2 = new lib.BSWH_Logo();
	this.instance_2.setTransform(79.7,528.05);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(360));

	// image_mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_167 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_168 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_169 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_170 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_171 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_172 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_173 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_174 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_175 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_176 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_177 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_178 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_179 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_180 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_181 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_182 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_183 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	var mask_1_graphics_184 = new cjs.Graphics().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(167).to({graphics:mask_1_graphics_167,x:612.325,y:-327.125}).wait(1).to({graphics:mask_1_graphics_168,x:610.975,y:-325.275}).wait(1).to({graphics:mask_1_graphics_169,x:606.825,y:-319.625}).wait(1).to({graphics:mask_1_graphics_170,x:599.975,y:-310.275}).wait(1).to({graphics:mask_1_graphics_171,x:590.425,y:-297.125}).wait(1).to({graphics:mask_1_graphics_172,x:578.075,y:-280.225}).wait(1).to({graphics:mask_1_graphics_173,x:563.025,y:-259.625}).wait(1).to({graphics:mask_1_graphics_174,x:545.175,y:-235.225}).wait(1).to({graphics:mask_1_graphics_175,x:524.625,y:-207.075}).wait(1).to({graphics:mask_1_graphics_176,x:501.325,y:-175.225}).wait(1).to({graphics:mask_1_graphics_177,x:475.325,y:-139.575}).wait(1).to({graphics:mask_1_graphics_178,x:446.525,y:-100.225}).wait(1).to({graphics:mask_1_graphics_179,x:415.025,y:-57.075}).wait(1).to({graphics:mask_1_graphics_180,x:380.775,y:-10.175}).wait(1).to({graphics:mask_1_graphics_181,x:343.775,y:40.475}).wait(1).to({graphics:mask_1_graphics_182,x:304.025,y:94.825}).wait(1).to({graphics:mask_1_graphics_183,x:261.525,y:152.975}).wait(1).to({graphics:mask_1_graphics_184,x:216.325,y:214.875}).wait(176));

	// txt_03
	this.instance_3 = new lib.txt_03();
	this.instance_3.setTransform(88.25,104.2);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(167).to({_off:false},0).to({x:78.25},114).wait(79));

	// shape_BG
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(250,152,178,0.749)").s().p("EgZ7AzlMAAAhnJMAz3AAAMAAABnJgAAuozIzTTRIAAUeMAmvAAAMAAAg66IAAAAQgMAAzQTLg");
	this.shape_4.setTransform(146.025,302.075);
	this.shape_4._off = true;

	var maskedShapeInstanceList = [this.shape_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(167).to({_off:false},0).wait(193));

	// Image_03
	this.instance_4 = new lib.image_03_1();
	this.instance_4.setTransform(65,300.5);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(167).to({_off:false},0).to({x:78},114).wait(79));

	// pink_transitions
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.lf(["#79E3D4","#78E3D4"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_5.setTransform(612.325,-327.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.lf(["#7BE2D4","#7AE2D4"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_6.setTransform(606.825,-319.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#7DE1D3","#7CE1D3"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_7.setTransform(599.975,-310.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.lf(["#80DFD2","#7FDFD2"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_8.setTransform(590.425,-297.125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.lf(["#84DDD1","#83DCD1"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_9.setTransform(578.075,-280.225);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.lf(["#89DAD0","#88DAD0"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_10.setTransform(563.025,-259.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.lf(["#8FD6CE","#8ED6CE"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_11.setTransform(545.175,-235.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#95D2CC","#95D2CC"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_12.setTransform(524.625,-207.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#9DCECA","#9CCECA"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_13.setTransform(501.325,-175.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#A5C9C8","#A5C9C8"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_14.setTransform(475.325,-139.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#AFC4C6","#AEC3C6"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_15.setTransform(446.525,-100.225);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#B9BEC3","#B8BDC3"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_16.setTransform(415.025,-57.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#C4B7C0","#C3B7C0"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_17.setTransform(380.775,-10.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#D0B0BD","#CFAFBD"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_18.setTransform(343.775,40.475);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#DDA9BA","#DCA8BA"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_19.setTransform(304.025,94.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#EAA1B6","#EAA0B6"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_20.setTransform(261.525,152.975);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#F998B2","#F997B2"],[0.486,1],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_21.setTransform(216.325,214.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_5,p:{x:612.325,y:-327.125}}]},167).to({state:[{t:this.shape_5,p:{x:610.975,y:-325.275}}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).wait(176));

	// image_mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_77 = new cjs.Graphics().p("Eg7IAnpIgFgFI8P7oMBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_78 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_79 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_80 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_81 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_82 = new cjs.Graphics().p("Eg7IAnpIgFgFI8P7oMBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_83 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_84 = new cjs.Graphics().p("Eg7IAnpIgFgFI8P7oMBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_85 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_86 = new cjs.Graphics().p("Eg7IAnpIgFgFI8P7oMBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_87 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_88 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_89 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_90 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_91 = new cjs.Graphics().p("Eg7IAnpIgFgFI8P7oMBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_92 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_93 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_94 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	var mask_2_graphics_95 = new cjs.Graphics().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(77).to({graphics:mask_2_graphics_77,x:661.725,y:-276.45}).wait(1).to({graphics:mask_2_graphics_78,x:659.075,y:-273.4}).wait(1).to({graphics:mask_2_graphics_79,x:651.125,y:-264.3}).wait(1).to({graphics:mask_2_graphics_80,x:637.825,y:-249.1}).wait(1).to({graphics:mask_2_graphics_81,x:619.275,y:-227.85}).wait(1).to({graphics:mask_2_graphics_82,x:595.375,y:-200.5}).wait(1).to({graphics:mask_2_graphics_83,x:566.175,y:-167.1}).wait(1).to({graphics:mask_2_graphics_84,x:531.675,y:-127.6}).wait(1).to({graphics:mask_2_graphics_85,x:491.825,y:-82.05}).wait(1).to({graphics:mask_2_graphics_86,x:446.725,y:-30.4}).wait(1).to({graphics:mask_2_graphics_87,x:401.575,y:21.2}).wait(1).to({graphics:mask_2_graphics_88,x:361.775,y:66.75}).wait(1).to({graphics:mask_2_graphics_89,x:327.225,y:106.25}).wait(1).to({graphics:mask_2_graphics_90,x:298.025,y:139.65}).wait(1).to({graphics:mask_2_graphics_91,x:274.175,y:167}).wait(1).to({graphics:mask_2_graphics_92,x:255.575,y:188.25}).wait(1).to({graphics:mask_2_graphics_93,x:242.275,y:203.45}).wait(1).to({graphics:mask_2_graphics_94,x:234.325,y:212.55}).wait(1).to({graphics:mask_2_graphics_95,x:231.675,y:215.6}).wait(265));

	// txt_02
	this.instance_5 = new lib.txt_02();
	this.instance_5.setTransform(74.2,92.05);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(77).to({_off:false},0).to({x:78.2},107).wait(176));

	// shape_BG
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("rgba(121,227,212,0.749)").s().p("EgZ7AzlMAAAhnJMAz3AAAMAAABnJgAAuozIzTTRIAAUeMAmvAAAMAAAg66IAAAAQgMAAzQTLg");
	this.shape_22.setTransform(146.025,302.075);
	this.shape_22._off = true;

	var maskedShapeInstanceList = [this.shape_22];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.shape_22).wait(77).to({_off:false},0).wait(283));

	// Image_02
	this.instance_6 = new lib.image_02_1();
	this.instance_6.setTransform(85.95,308.5);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(77).to({_off:false},0).to({x:71.95},107).wait(176));

	// blue_transitions
	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#95C0F0","rgba(150,192,240,0)"],[0.486,0.91],96.9,-109.4,-295.4,334.1).s().p("EhX9APPMBcVhoZMBTmBJ8MhcVBoZg");
	this.shape_23.setTransform(522.325,-287.125);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#79E3D4","#78E4D3"],[0.486,1],93.6,-120.2,-298.7,323.3).s().p("Eg7IAnpIgFgFI8P7oMBbThmyMBTmBJ8MheQBrxg");
	this.shape_24.setTransform(661.725,-276.45);
	this.shape_24._off = true;

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#79E3D4","#78E4D3"],[0.486,1],93.6,-120.2,-298.7,323.3).s().p("EhXcAL8MBbThmyMBTmBJ8MheQBrxg");
	this.shape_25.setTransform(659.075,-273.4);
	this.shape_25._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_23}]}).to({state:[{t:this.shape_24}]},77).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_25}]},1).wait(265));
	this.timeline.addTween(cjs.Tween.get(this.shape_24).wait(77).to({_off:false},0).to({_off:true},1).wait(4).to({_off:false,x:595.375,y:-200.5},0).to({_off:true},1).wait(1).to({_off:false,x:531.675,y:-127.6},0).to({_off:true},1).wait(1).to({_off:false,x:446.725,y:-30.4},0).to({_off:true},1).wait(4).to({_off:false,x:274.175,y:167},0).to({_off:true},1).wait(268));
	this.timeline.addTween(cjs.Tween.get(this.shape_25).wait(78).to({_off:false},0).wait(1).to({x:651.125,y:-264.3},0).wait(1).to({x:637.825,y:-249.1},0).wait(1).to({x:619.275,y:-227.85},0).to({_off:true},1).wait(1).to({_off:false,x:566.175,y:-167.1},0).to({_off:true},1).wait(1).to({_off:false,x:491.825,y:-82.05},0).to({_off:true},1).wait(1).to({_off:false,x:401.575,y:21.2},0).wait(1).to({x:361.775,y:66.75},0).wait(1).to({x:327.225,y:106.25},0).wait(1).to({x:298.025,y:139.65},0).to({_off:true},1).wait(1).to({_off:false,x:255.575,y:188.25},0).wait(1).to({x:242.275,y:203.45},0).wait(1).to({x:234.325,y:212.55},0).wait(1).to({x:231.675,y:215.6},0).wait(265));

	// txt_01
	this.instance_7 = new lib.txt_01();
	this.instance_7.setTransform(85.15,92.05);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({x:79.15},95).wait(265));

	// shape_BG
	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("rgba(150,192,240,0.749)").s().p("EgZ7AzlMAAAhnJMAz3AAAMAAABnJgAAuozIzTTRIAAUeMAmvAAAMAAAg66IAAAAQgMAAzQTLg");
	this.shape_26.setTransform(146.025,302.075);

	this.timeline.addTween(cjs.Tween.get(this.shape_26).wait(360));

	// Image_01
	this.instance_8 = new lib.image_01_1();
	this.instance_8.setTransform(60.5,307.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({x:74.5},95).wait(265));

	// wht_BG
	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("EgavAxFMAAAhiJMA1fAAAMAAABiJg");
	this.shape_27.setTransform(147.6,300.075);

	this.timeline.addTween(cjs.Tween.get(this.shape_27).wait(360));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-196.6,-597.8,1461.8999999999999,1994.8999999999999);
// library properties:
lib.properties = {
	id: '7331656131B94D019E721DBDFB0B0DAD',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"image_01.jpg", id:"image_01"},
		{src:"image_02.jpg", id:"image_02"},
		{src:"image_03.jpg", id:"image_03"},
		{src:"image_04.jpg", id:"image_04"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['7331656131B94D019E721DBDFB0B0DAD'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;